---@diagnostic disable: undefined-global

-- Auto-generated by Core/Media/Sound/import_desktop_sound.py. Do not edit by hand.

local LSM = LibStub and LibStub("LibSharedMedia-3.0", true)
if not (LSM and LSM.Register) then
    return
end

local SOUND_ROOT = "Interface\\AddOns\\EXBoss\\Core\\Media\\Sound\\"
local SOUND_ENTRIES = {
    { "[EX] 1", SOUND_ROOT .. "1.ogg" },
    { "[EX] 2", SOUND_ROOT .. "2.ogg" },
    { "[EX] 3", SOUND_ROOT .. "3.ogg" },
    { "[EX] 4", SOUND_ROOT .. "4.ogg" },
    { "[EX] 5", SOUND_ROOT .. "5.ogg" },
    { "[EX] 6", SOUND_ROOT .. "6.ogg" },
    { "[EX] 7", SOUND_ROOT .. "7.ogg" },
    { "[EX] 8", SOUND_ROOT .. "8.ogg" },
    { "[EX] 9", SOUND_ROOT .. "9.ogg" },
    { "[EX] 10", SOUND_ROOT .. "10.ogg" },
    { "[EX] 11", SOUND_ROOT .. "11.ogg" },
    { "[EX] 12.0_Warning0", SOUND_ROOT .. "12.0_Warning0.ogg" },
    { "[EX] 12.0_Warning1", SOUND_ROOT .. "12.0_Warning1.ogg" },
    { "[EX] 12.0_Warning2", SOUND_ROOT .. "12.0_Warning2.ogg" },
    { "[EX] Error", SOUND_ROOT .. "Error.ogg" },
    { "[EX] waining2", SOUND_ROOT .. "waining2.ogg" },
    { "[EX] warning0", SOUND_ROOT .. "warning0.ogg" },
    { "[EX] warning1", SOUND_ROOT .. "warning1.ogg" },
}

for _, entry in ipairs(SOUND_ENTRIES) do
    LSM:Register("sound", entry[1], entry[2])
end
