local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Holy','Priest-Shadow','Druid-Restoration','Mage-Frost','DemonHunter-Devourer','DeathKnight-Unholy','Unknown-Unknown','Druid-Balance','DeathKnight-Blood','Evoker-Augmentation','Evoker-Preservation','Druid-Guardian','Druid-Feral','DeathKnight-Frost','Paladin-Holy','Paladin-Retribution','Warrior-Arms','Warrior-Fury','Mage-Arcane','Shaman-Restoration','Shaman-Elemental','Priest-Discipline','Hunter-BeastMastery','Paladin-Protection','Hunter-Marksmanship','Warlock-Demonology','Warlock-Destruction','Rogue-Subtlety','Rogue-Assassination','Monk-Brewmaster','Monk-Mistweaver','Monk-Windwalker','Warrior-Protection','DemonHunter-Vengeance','DemonHunter-Havoc','Evoker-Devastation','Warlock-Affliction','Hunter-Survival','Rogue-Outlaw','Shaman-Enhancement','Mage-Fire',}
local provider = {region='US',realm='Arathor',name='US',type='weekly',zone=46,date='2026-06-20',data={Aa='Aange:BAAALgADCgYJBgAAAA==.',
Ab='Absoul:BAACLgAFFH8dAAIBAAQJsB1yAQD4AAABAAQJsB1yAQD4AAAuAAQKfzIAAwEACQkfIocEADkDAAEACQkfIocEADkDAAIAAQlxA/doACYAAAAA.',
Ac='Acedia:BAABLgAECn80AAIBAAkJkhYcFgAhAgABAAkJkhYcFgAhAgAAAA==.',
Ad='Adellas:BAACLgAFFH8NAAIDAAQJ0hnJJQAtAQADAAQJ0hnJJQAtAQAuAAQKfywAAgMACAmpIg8MAAADAAMACAmpIg8MAAADAAAA.Adern:BAACLgAFFH8MAAICAAQJ9x1AEgBWAQACAAQJ9x1AEgBWAQAuAAQKfysAAgIACQkIHtkOAGsCAAIACQkIHtkOAGsCAAAA.Adon:BAACLgAFFH8NAAIEAAQJ2xNqXAAmAQAEAAQJ2xNqXAAmAQAuAAQKfywAAgQACQl6HD8nAH4CAAQACQl6HD8nAH4CAAAA.Adondruel:BAAALgAECgEJAgABLgAFFAQJDQAEANsTAA==.',
Ae='Aelali:BAAALgAECgYJEgAAAA==.Aelith:BAABLgAECn8XAAIFAAgJmxszMwD5AQAFAAgJmxszMwD5AQAAAA==.',
Af='Afador:BAAALgAECgUJCAABLgAECgkJKwAGAMgUAA==.',
Ag='Ageling:BAAALgADCgYJCgAAAA==.',
Ai='Aidara:BAAALgAECggJCQABLgAECgkJCQAHAAAAAA==.',
Ak='Akeno:BAAALgAECgMJAwABLgAECgMJBAAHAAAAAA==.Akrom:BAAALgADCgEJAgAAAA==.',
Al='Aladestar:BAACLgAFFH8XAAMDAAYJ3hNmGACbAQADAAYJ3hNmGACbAQAIAAMJrAqoNQCpAAAuAAQKfyoAAwMACQn1GqwbAF4CAAMACQn1GqwbAF4CAAgACAkcIRciAOwBAAAA.Alatar:BAAALgADCgMJAwABLgAECgkJNgAJAPggAA==.Albinodargon:BAABLgAECn8WAAMKAAgJgQsPPAA6AQAKAAgJgQsPPAA6AQALAAEJlQMuTAApAAAAAA==.Alderleise:BAABLgAECn8fAAUDAAkJAwoPUgBHAQADAAkJAwoPUgBHAQAIAAMJtxA6bwBpAAAMAAQJLwk+VgBgAAANAAEJlghRWAAqAAAAAA==.Alecc:BAAALgAECgcJEQAAAA==.Alecw:BAAALgAECgQJCAAAAA==.Alexein:BAACLgAFFH8ZAAIOAAYJygj2CQBSAQAOAAYJygj2CQBSAQAuAAQKfywAAg4ACQlgGA8FAPYBAA4ACQlgGA8FAPYBAAAA.Alienspace:BAAALgADCgEJAQAAAA==.Allila:BAAALgAECgEJAQAAAA==.',
Am='Amets:BAABLgAECn86AAMPAAkJlCP3AQCTAwAPAAkJlCP3AQCTAwAQAAUJXxkJuQASAQAAAA==.Amydh:BAABLgAECn8YAAMQAAgJbg55rQAjAQAQAAcJVwt5rQAjAQAPAAQJPgYlZwCZAAAAAA==.',
An='Anabel:BAAALgADCgkJFwAAAA==.Anamii:BAAALgADCgEJAQAAAA==.Andorsi:BAAALgAECgYJCQAAAA==.Anglechow:BAAALgADCgUJBQAAAA==.',
Ar='Arachne:BAABLgAECn8iAAICAAkJCgnMOwAjAQACAAkJCgnMOwAjAQAAAA==.Aranax:BAAALgADCgEJAgAAAA==.Arce:BAABLgAECn8dAAICAAkJRg8PIwCwAQACAAkJRg8PIwCwAQAAAA==.Architeleaf:BAAALgADCgMJAwABLgAECgMJAwAHAAAAAA==.Areafiftymoo:BAABLgAECn9IAAMRAAkJURYfDAAlAgARAAkJLRYfDAAlAgASAAkJJQwjMQCIAQAAAA==.Arthurleywin:BAAALgADCgIJAgAAAA==.Arysia:BAACLgAFFH8GAAIEAAQJMA0EaQASAQAEAAQJMA0EaQASAQAuAAQKfx0AAwQACQnKEnlMAPYBAAQACQnKEnlMAPYBABMAAwmzDgESAKQAAAAA.Aryya:BAACLgAFFH8FAAINAAMJBxA6FACQAAANAAMJBxA6FACQAAAuAAQKf0YAAw0ACQnGI+ABABkDAA0ACQnGI+ABABkDAAgAAwkcB8FnAIIAAAAA.',
As='Astralbreak:BAAALgADCgQJBQABLgAECgUJBwAHAAAAAA==.',
At='Athelia:BAAALgADCgEJAQAAAA==.',
Au='Aulaes:BAAALgADCgIJAgAAAA==.',
Av='Avalan:BAABLgAECn9CAAISAAkJmyITBwDtAgASAAkJmyITBwDtAgAAAA==.Avanolatwo:BAAALgAECgMJAwABLgAFFAMJCgAUALIcAA==.Avashammy:BAACLgAFFH8KAAIUAAMJshzGOwD0AAAUAAMJshzGOwD0AAAuAAQKfyoAAxQACQmKHQohAEkCABQACQmKHQohAEkCABUAAQlxCIC5ACMAAAAA.Avesia:BAABLgAECn8aAAIWAAYJUhaeIgB/AQAWAAYJUhaeIgB/AQAAAA==.Avhunt:BAAALgAECgYJDgABLgAECgkJQgASAJsiAA==.Aviendah:BAABLgAECn8wAAIXAAkJJBOGPwDkAQAXAAkJJBOGPwDkAQAAAA==.',
Aw='Awsomeonet:BAACLgAFFH8NAAMYAAQJ4A+xCQDaAAAYAAQJ4A+xCQDaAAAQAAEJnQK8zgAxAAAuAAQKfx4AAxgACAm4GRQRALMBABgACAm4GRQRALMBABAAAgk/BBkoAVAAAAAA.',
Ay='Ayot:BAAALgAECgcJEwAAAA==.',
Az='Azdfghop:BAACLgAFFH8iAAMXAAgJFyBnEQDZAQAXAAYJbyNnEQDZAQAZAAYJCBgzFQAbAQAuAAQKfyAAAxkACQm4IjIPAMcCABkACAnIHjIPAMcCABcACAmbIZM/ALEBAAAA.Azzinotica:BAAALgAECgMJBAAAAA==.',
Ba='Baalzeus:BAAALgAECgUJBQABLgAECgkJKwAaAAAUAA==.Babeshot:BAABLgAECn80AAIXAAkJGhaVNAAKAgAXAAkJGhaVNAAKAgAAAA==.Babezila:BAABLgAECn8XAAMbAAYJKQ3CHQC6AAAbAAYJKQ3CHQC6AAAaAAEJNQZvUwErAAAAAA==.Badshahprime:BAABLgAECn8eAAIQAAgJPhpjKgB7AgAQAAgJPhpjKgB7AgAAAA==.Ballzsmasher:BAAALgAECggJDQAAAA==.Bando:BAAALgADCggJCAAAAA==.Barbiegrill:BAABLgAECn8dAAMcAAgJ7x7+DwCmAgAcAAgJEB7+DwCmAgAdAAUJVRxACQCuAQABLgAFFAMJDAAJACgdAA==.Barleb:BAAALgAECgIJAgAAAA==.Battlemaker:BAAALgADCggJDQABLgAECggJOQAUAMMXAA==.Baykin:BAABLgAECn8pAAIeAAkJtSAJBwDHAgAeAAkJtSAJBwDHAgAAAA==.',
Bb='Bbeastt:BAAALgADCgEJAgAAAA==.',
Be='Beefyfivelyr:BAAALgADCgcJBwAAAA==.Beldinnara:BAAALgAECgEJAgAAAA==.Berandas:BAABLgAECn8UAAMfAAcJ/hEGJgCDAQAfAAcJ/hEGJgCDAQAgAAUJjg1qVQC3AAAAAA==.Bereessielin:BAAALgAECgQJBgAAAA==.Bergur:BAAALgAECgQJBAAAAA==.Berkowitz:BAACLgAFFH8MAAIcAAMJexqvAgAKAQAcAAMJexqvAgAKAQAuAAQKfygAAhwACQkRIG8EAPUCABwACQkRIG8EAPUCAAAA.Beyy:BAAALgAECgMJAwABLgAECggJFQAQABYXAA==.',
Bi='Bigbear:BAAALgADCgEJAQABLgADCgMJAwAHAAAAAA==.',
Bl='Blaaze:BAAALgAECgQJBgAAAA==.Blackfrost:BAABLgAECn8ZAAIEAAcJthV9eQCGAQAEAAcJthV9eQCGAQAAAA==.Blaiddyd:BAACLgAFFH8IAAIXAAMJMBcTBwDeAAAXAAMJMBcTBwDeAAAuAAQKf0UAAhcACQmmIEwbAIICABcACQmmIEwbAIICAAAA.Blasphemy:BAAALgADCgYJCwAAAA==.Blead:BAACLgAFFH8MAAQJAAMJKB2AIgDXAAAJAAMJKB2AIgDXAAAOAAEJVAhuKwA7AAAGAAEJtgW9IQE1AAAuAAQKfxYABAkACAkIHroQAAACAAkACAkIHroQAAACAA4AAgnbFeMsAHAAAAYAAgl9FXNqATkAAAAA.Blinkerr:BAAALgADCgkJDAAAAA==.Bluefarm:BAAALgAFFAEJAQAAAA==.',
Bo='Bosliegor:BAAALgAECgIJAgAAAA==.',
Br='Brahot:BAAALgAECgEJAQAAAA==.Brain:BAAALgAECgQJAwAAAA==.Braindi:BAAALgAECgYJBwAAAA==.Brandawn:BAAALgAECgYJEAAAAA==.Branwarden:BAABLgAECn8bAAMSAAYJFQxpXgDaAAASAAYJTglpXgDaAAAhAAIJUQ4mSABTAAAAAA==.Brewsle:BAAALgAECgEJAQAAAA==.Brigantia:BAAALgADCgYJCgAAAA==.',
Bu='Bubblebot:BAAALgAECgMJAwABLgAECgkJNAAFABkgAA==.Bullchitz:BAABLgAECn8WAAIXAAYJ+hibQwChAQAXAAYJ+hibQwChAQAAAA==.Bullchitza:BAAALgADCgcJBwABLgAECgYJFgAXAPoYAA==.Burningooch:BAAALgADCgEJAQAAAA==.',
['Bã']='Bãyy:BAABLgAECn8VAAIQAAgJFhemXAC4AQAQAAgJFhemXAC4AQAAAA==.',
['Bæ']='Bæyy:BAAALgAECgcJCwABLgAECggJFQAQABYXAA==.',
Ca='Calador:BAAALgAECggJEgAAAA==.Capybara:BAAALgAECgcJEgAAAA==.Caster:BAAALgADCgQJBAAAAA==.Cathbad:BAAALgADCgEJAQAAAA==.Caylynn:BAAALgAECgYJEgAAAA==.',
Ce='Celyne:BAABLgAECn80AAQFAAkJGSCYFwCJAgAFAAkJGSCYFwCJAgAiAAcJURf4DQBzAQAjAAMJ/wzESgCMAAAAAA==.Cereza:BAAALgAECgEJAQAAAA==.',
Ch='Chaoslock:BAAALgADCgMJAwAAAA==.Chicknfajita:BAAALgAECgYJDQABLgAECgcJEQAHAAAAAA==.Chickpea:BAAALgAECgMJAwAAAA==.Chrissi:BAABLgAECn8oAAIDAAkJeA8IMgDYAQADAAkJeA8IMgDYAQAAAA==.',
Ci='Cinco:BAAALgADCgUJBQAAAA==.',
Cl='Clearly:BAAALgADCgQJAwAAAA==.Clessidra:BAAALgAECgIJAgAAAA==.',
Co='Coconutcat:BAAALgAECgcJBwAAAA==.Cocytus:BAAALgAECgYJDAAAAA==.Colbith:BAAALgAECgMJBAAAAA==.Conquest:BAABLgAECn8WAAIQAAYJwRLLvAANAQAQAAYJwRLLvAANAQAAAA==.Cordaddy:BAABLgAECn8rAAIDAAkJQSV+BwBAAwADAAkJQSV+BwBAAwAAAA==.Cordragu:BAABLgAECn8dAAIUAAkJDiVTAQDAAwAUAAkJDiVTAQDAAwABLgAECgkJKwADAEElAA==.Cordran:BAAALgAECgYJBgABLgAECgkJKwADAEElAA==.Corinthe:BAABLgAECn8gAAMPAAkJgCS8AQCcAwAPAAkJgCS8AQCcAwAQAAEJYQ9EnAEuAAABLgAECgkJKwADAEElAA==.Corinthin:BAABLgAECn85AAIUAAgJwxeWKgARAgAUAAgJwxeWKgARAgAAAA==.',
Cr='Crax:BAAALgADCgkJDQAAAA==.Crinn:BAABLgAECn8WAAQOAAkJDw/GEQBcAQAOAAgJqwzGEQBcAQAJAAYJYwvYJwAAAQAGAAEJuA3KbAE4AAAAAA==.Crizmon:BAABLgAECn85AAIOAAgJvyI/AQD5AgAOAAgJvyI/AQD5AgAAAA==.Cryomancer:BAAALgADCgQJBAAAAA==.Crõwley:BAAALgAECgEJAgABLgAECgkJKAAWALEgAA==.',
Da='Damage:BAAALgAECgEJAQAAAA==.Damorax:BAABLgAECn8WAAIQAAgJbxSArgAhAQAQAAgJbxSArgAhAQAAAA==.Dangul:BAAALgAECggJDwAAAA==.Darazarke:BAACLgAFFH8pAAQLAAgJCxCjCQASAgALAAgJCxCjCQASAgAKAAIJwBOaUwB7AAAkAAEJRgl+DwA/AAAuAAQKfzAABCQACQkOHhAEANICACQACAkfHxAEANICAAsACAkAH60OAE4CAAoABAk3GUJTAOIAAAAA.Darkcursed:BAABLgAECn84AAIaAAkJRA/wRwDCAQAaAAkJRA/wRwDCAQAAAA==.Darkndeadly:BAABLgAFFH8LAAIXAAQJTgh5TwAMAQAXAAQJTgh5TwAMAQAAAA==.Darksaphira:BAAALgAECggJCAAAAA==.Darksudge:BAAALgAECgEJAQAAAA==.Darps:BAACLgAFFH8NAAIXAAQJtSFzRAAlAQAXAAQJtSFzRAAlAQAuAAQKfzAAAhcACAnfI+UPANECABcACAnfI+UPANECAAAA.Daspoof:BAAALgADCgMJAwAAAA==.Daybreak:BAAALgAECggJEgAAAA==.Dayquil:BAECLgAFFH8UAAIQAAUJwxCgSgAYAQAQAAUJwxCgSgAYAQAuAAQKfysAAxAACQm+HjUcAJwCABAACQm+HjUcAJwCAA8AAQnLGTuGAD4AAAAA.',
De='Deadaddie:BAACLgAFFH8KAAIGAAQJUhL7bAAiAQAGAAQJUhL7bAAiAQAuAAQKfyIAAwYACQkAIJQbAKICAAYACQkAIJQbAKICAA4ABgllF7AXABgBAAAA.Deamoneyes:BAABLgAFFH8FAAIQAAMJZRcxbgDUAAAQAAMJZRcxbgDUAAAAAA==.Deathbakerey:BAAALgADCgUJBQAAAA==.Decastamon:BAACLgAFFH8FAAIEAAIJBgJftABpAAAEAAIJBgJftABpAAAuAAQKfywAAgQACAm2DAqCAHMBAAQACAm2DAqCAHMBAAAA.Delin:BAAALgAECgcJBwABLgAFFAgJKQALAAsQAA==.Deluxdh:BAAALgAECgQJBAAAAA==.Demolitions:BAAALgAECgkJAgAAAA==.Demonslinger:BAAALgADCgUJBQAAAA==.Dendrel:BAAALgAECgUJBQAAAA==.Derpspally:BAAALgAECgEJAQAAAA==.Derpspunch:BAABLgAECn8pAAIfAAkJjhtvDgC4AgAfAAkJjhtvDgC4AgABLgAFFAQJDQAXALUhAA==.Destrox:BAAALgADCgYJBgAAAA==.Dethomag:BAAALgAECgEJAQAAAA==.Dezatra:BAAALgAECgUJEQAAAA==.Deíty:BAAALgADCgUJBgAAAA==.',
Di='Diane:BAEALgAECgkJDAAAAA==.Dieselcon:BAACLgAFFH8FAAIYAAIJuhFNAQB0AAAYAAIJuhFNAQB0AAAuAAQKf2IAAxgACQlhHNgGAHQCABgACQlhHNgGAHQCABAAAgmQCZ9EATIAAAAA.Dieseletta:BAAALgAECgQJBwAAAA==.Dinodruid:BAAALgAECgcJAwAAAA==.Diprivan:BAAALgAFFAIJAgAAAA==.Dizzy:BAAALgAECgYJCAAAAA==.',
Do='Domdog:BAABLgAECn80AAIEAAkJTBaUQQAXAgAEAAkJTBaUQQAXAgAAAA==.Domína:BAAALgAECgUJBQAAAA==.Dontforget:BAABLgAECn8fAAMPAAkJtBHGLACtAQAPAAgJ6RDGLACtAQAQAAcJngNwFQGfAAAAAA==.Dookiesmash:BAABLgAECn8uAAIhAAkJSSQzAwAHAwAhAAkJSSQzAwAHAwABLgAFFAQJDQAXALUhAA==.Doomblast:BAAALgADCgIJAgAAAA==.Doomdealer:BAAALgAFFAEJAgAAAA==.Doomed:BAAALgADCgQJBAABLgAECggJGAAeADQdAA==.Doomrage:BAAALgADCgcJFAAAAA==.Doomsdead:BAAALgADCgcJBwAAAA==.Doomshock:BAAALgADCgYJBQAAAA==.Dorogon:BAAALgAECggJEAAAAA==.',
Dr='Draftymonk:BAABLgAECn88AAMeAAkJyCSTBQDmAgAeAAgJ1SSTBQDmAgAgAAYJWhySJQCIAQAAAA==.Drage:BAAALgAECgUJBQABLgAECgkJSAARAFEWAA==.Drainlock:BAAALgADCgcJBwAAAA==.Drakthar:BAAALgAECgcJBwABLgAFFAgJFQAXAFMaAA==.Drax:BAACLgAFFH8FAAIaAAIJqgVtsgB0AAAaAAIJqgVtsgB0AAAuAAQKfzUAAyUACAnnErwOAEUBABoACAkFDstkAHUBACUABgl2ErwOAEUBAAAA.Dreadgar:BAAALgAECgQJBAABLgAFFAQJCAAVAAYSAA==.Dritzzfive:BAACLgAFFH8GAAIGAAMJvAEf0QCQAAAGAAMJvAEf0QCQAAAuAAQKfyAAAgYACAlUCcyRAEIBAAYACAlUCcyRAEIBAAAA.Dritzzwar:BAAALgAECgYJDAAAAA==.',
Dw='Dwreckslaya:BAAALgADCgcJBwAAAA==.',
Ed='Ediann:BAAALgAECgUJCAAAAA==.',
Ei='Eightnine:BAAALgAECgQJBAAAAA==.Eilica:BAAALgAECgUJBQAAAA==.',
Ek='Ekaine:BAAALgADCgQJBAABLgAECggJGgAeAAMRAA==.',
El='Elandrus:BAABLgAECn8oAAIWAAkJsSBQBABQAwAWAAkJsSBQBABQAwAAAA==.Elishiveth:BAAALgAECgYJEgAAAA==.Elleynre:BAAALgADCgQJBAAAAA==.Elliewilliam:BAAALgADCgQJBAAAAA==.Elreim:BAAALgAFFAIJAwAAAA==.Elwendigo:BAAALgADCgMJAwAAAA==.Elwyna:BAAALgADCgIJAgAAAA==.',
Em='Emmara:BAABLgAECn8sAAIZAAkJYwYJGADyAAAZAAkJYwYJGADyAAAAAA==.',
En='Enhancement:BAAALgADCgcJDQABLgAFFAcJHwAVAFEeAA==.Enitar:BAAALgAECgUJCQABLgAECgkJNAAFABkgAA==.',
Er='Erata:BAABLgAECn8tAAIlAAgJFA0ADwBtAQAlAAgJFA0ADwBtAQAAAA==.Erdix:BAAALgAECgQJBAAAAA==.Erii:BAAALgAECgEJAgAAAA==.Erlangshen:BAAALgADCgUJBQAAAA==.Erravis:BAAALgADCgcJDwABLgAECgMJAwAHAAAAAA==.',
Ev='Evarion:BAAALgADCgEJAQAAAA==.Eviaei:BAAALgAECgMJAwAAAA==.Evulise:BAAALgAECgEJAgAAAA==.Evullight:BAAALgAECgEJAQAAAA==.',
Ez='Ezalan:BAAALgADCgcJBwAAAA==.Ezlok:BAACLgAFFH8IAAIVAAQJBhLIJgD7AAAVAAQJBhLIJgD7AAAuAAQKfxwAAhUACAk4G6AfAOYBABUACAk4G6AfAOYBAAAA.Ezorreodd:BAAALgADCgQJBAAAAA==.Ezzorreodd:BAAALgAECgUJDgAAAA==.',
Fa='Fae:BAABLgAECn8kAAMVAAkJQxVINgBgAQAVAAcJmBRINgBgAQAUAAcJHxUbWQBTAQAAAA==.Faeth:BAAALgAECgUJBwABLgAECgkJJAAVAEMVAA==.Falcyon:BAAALgAECgUJCAAAAA==.Falerin:BAABLgAECn8kAAIDAAkJwxHgNADIAQADAAkJwxHgNADIAQAAAA==.Fantalo:BAAALgAECgEJAQABLgAFFAcJHwAVAFEeAA==.Farenheit:BAABLgAECn81AAQIAAkJuht4DgB1AgAIAAkJuht4DgB1AgADAAQJlQ0dowCDAAAMAAMJsBC2WgBYAAAAAA==.Fatel:BAAALgAFFAEJAgABLgAFFAMJDAAJACgdAA==.Faydwer:BAAALgADCgMJBAAAAA==.Faye:BAAALgAECgQJCAABLgAECgkJJAAVAEMVAA==.Fayfox:BAAALgADCgkJFwAAAA==.Fayzos:BAAALgAECgYJCQAAAA==.',
Fe='Feenex:BAABLgAECn8VAAIGAAgJlhNzYgCjAQAGAAgJlhNzYgCjAQAAAA==.',
Fi='Fillorey:BAAALgAECgMJAwAAAA==.Finick:BAABLgAECn8aAAIDAAcJtw29XQAdAQADAAcJtw29XQAdAQAAAA==.Firedealer:BAACLgAFFH8KAAIZAAQJzg9bFgAOAQAZAAQJzg9bFgAOAQAuAAQKfyQAAhkACAkbGqUJANoBABkACAkbGqUJANoBAAAA.Firnen:BAABLgAECn8dAAILAAgJrRcaGgC7AQALAAgJrRcaGgC7AQABLgAECgkJKAAWALEgAA==.',
Fl='Flahash:BAAALgAECgMJAwAAAA==.Flapjack:BAAALgAECgIJAgABLgAECgUJDQAHAAAAAA==.Flappy:BAABLgAECn8XAAILAAcJVRLdEQCsAQALAAcJVRLdEQCsAQABLgAFFAUJDAAUAIUVAA==.Flapster:BAAALgADCgkJFQABLgAFFAUJDAAUAIUVAA==.Flashmaster:BAAALgAECggJEwAAAA==.Flawlessheal:BAAALgAECgEJCwAAAA==.Flora:BAABLgAECn8cAAIXAAkJNhkpNQAIAgAXAAkJNhkpNQAIAgABLgAECgkJJAAVAEMVAA==.Fluffybutt:BAAALgAECgIJAgAAAA==.',
Fo='Fossora:BAAALgAECgUJDAAAAA==.',
Fr='Frostmagi:BAAALgAECgYJDwABLgAFFAcJHwAVAFEeAA==.Frostybunny:BAAALgAECgcJEgAAAA==.Frozenharded:BAAALgAECgQJAwABLgAECggJHQAUALQXAA==.',
Fu='Furrbidden:BAAALgADCgQJBAAAAA==.Fusionve:BAAALgAECgUJBgAAAA==.',
Ga='Gaffershot:BAAALgADCgMJAwAAAA==.Gafferthicc:BAACLgAFFH8IAAIFAAUJvhMnSAAQAQAFAAUJvhMnSAAQAQAuAAQKfx0AAgUACQknGsgzAPcBAAUACQknGsgzAPcBAAAA.Gaffharir:BAAALgADCgUJBQAAAA==.Galvin:BAAALgADCgYJBgAAAA==.Gannik:BAAALgAECgUJBQAAAA==.Garfeeld:BAAALgADCgcJCwABLgAECggJOQAUAMMXAA==.Garlicroast:BAAALgAECgMJBgAAAA==.Gayden:BAAALgAECgUJBgAAAA==.',
Ge='Gelatin:BAAALgADCgQJBQAAAA==.Gerry:BAACLgAFFH8MAAImAAMJ2xcBHADxAAAmAAMJ2xcBHADxAAAuAAQKfzsAAyYACQmfIHcAAKcBACYACQmfIHcAAKcBABcAAQlBFcweAT4AAAEuAAUUBAkLACYApw0A.Geyora:BAABLgAECn8cAAImAAgJAR+SAwDvAgAmAAgJAR+SAwDvAgAAAA==.',
Gg='Ggkando:BAABLgAECn8WAAIXAAgJGA9uBQDPAAAXAAgJGA9uBQDPAAABLgAECgkJCQAHAAAAAA==.',
Gi='Gigguschadus:BAAALgADCgIJAgAAAA==.Gingerail:BAABLgAECn8dAAIUAAgJtBcOJwAkAgAUAAgJtBcOJwAkAgAAAA==.',
Gl='Glory:BAABLgAECn8xAAIJAAkJ5Bu+CQB3AgAJAAkJ5Bu+CQB3AgAAAA==.',
Gn='Gnerry:BAABLgAFFH8LAAImAAQJpw3jAQDoAAAmAAQJpw3jAQDoAAAAAA==.Gnotorious:BAAALgAECgMJAwAAAA==.',
Go='Goldi:BAAALgAECgIJAgAAAA==.Goochsquirts:BAABLgAECn8wAAMUAAkJYRqHKADuAQAUAAkJYRqHKADuAQAVAAEJ2ARfvAAhAAAAAA==.Gorrick:BAAALgAFFAIJAwAAAA==.Gorriff:BAAALgAECgMJBAAAAA==.',
Gr='Graestrae:BAABLgAECn9HAAIGAAkJ8RNYNAAtAgAGAAkJ8RNYNAAtAgAAAA==.Gravedygger:BAABLgAECn9EAAIXAAkJxhusJABQAgAXAAkJxhusJABQAgAAAA==.Graveflame:BAAALgAECgYJCwAAAA==.Greenonions:BAAALgADCgIJAgAAAA==.Grenswood:BAACLgAFFH8ZAAIbAAcJ8iEVAQAwAgAbAAcJ8iEVAQAwAgAuAAQKfzkAAhsACQkKJkUAAGADABsACQkKJkUAAGADAAAA.Grimmarius:BAAALgAFFAIJAgAAAA==.Grimmkin:BAAALgAFFAMJBAAAAA==.Grimmyr:BAAALgAECgYJBgAAAA==.Growl:BAAALgAECgUJCgAAAA==.Grumbo:BAAALgAECgUJDAAAAA==.Gryff:BAAALgAECgMJAwAAAA==.Gryffindor:BAAALgADCgQJBAAAAA==.',
Gu='Gunnerr:BAAALgAECgMJCQAAAA==.Guuldurak:BAAALgAECgUJDAAAAA==.',
Ha='Halynn:BAAALgAECggJDwAAAA==.Hanadan:BAAALgADCgcJBwAAAA==.Harrod:BAABLgAECn8lAAIEAAkJTwgXfACAAQAEAAkJTwgXfACAAQAAAA==.Hasew:BAABLgAECn8eAAIXAAcJnRvAMgDkAQAXAAcJnRvAMgDkAQAAAA==.Haste:BAAALgAECgMJAwABLgAFFAMJDAAJACgdAA==.Hauken:BAABLgAECn8kAAIJAAkJNSUnAQBWAwAJAAkJNSUnAQBWAwABLgAFFAgJFQAXAFMaAA==.',
He='He:BAAALgAECgEJAQAAAA==.Heimlich:BAAALgAECgIJAwABLgAECggJHgAQAD4aAA==.Hellodoodle:BAAALgAECgYJDAAAAA==.Helpimßlind:BAABLgAECn8rAAIFAAgJrBZKVQCHAQAFAAgJrBZKVQCHAQAAAA==.Hera:BAACLgAFFH8hAAMXAAYJsyBhIQB/AQAXAAUJNCRhIQB/AQAZAAEJrxJLLwBTAAAuAAQKfzUAAhcACQmSJkUCAHYDABcACQmSJkUCAHYDAAAA.Herry:BAABLgAECn8fAAImAAgJGx1cEwALAgAmAAgJGx1cEwALAgABLgAFFAQJCwAmAKcNAA==.Heyner:BAABLgAECn9CAAInAAkJWBl8AwBlAgAnAAkJWBl8AwBlAgAAAA==.',
Hi='Hille:BAAALgAECgEJAQAAAA==.Hinral:BAACLgAFFH8XAAIfAAYJsyGiDQAwAgAfAAYJsyGiDQAwAgAuAAQKfysAAh8ACQlkJSwEAHADAB8ACQlkJSwEAHADAAAA.',
Ho='Hojira:BAABLgAECn8XAAIQAAgJWBWeVwDFAQAQAAgJWBWeVwDFAQAAAA==.Holyangus:BAAALgAECgYJEwAAAA==.Holybabe:BAAALgADCgEJAQAAAA==.Holysmacker:BAAALgAECggJDQABLgAFFAQJCwAEAOAJAA==.',
Hu='Hukkaru:BAAALgADCgYJDgAAAA==.Hurtlawley:BAAALgAECgQJBQAAAA==.',
['Hë']='Hëll:BAABLgAECn8rAAIaAAkJABRrNAAHAgAaAAkJABRrNAAHAgAAAA==.',
Ic='Iceblind:BAABLgAECn8VAAIFAAYJZAoLrQDMAAAFAAYJZAoLrQDMAAAAAA==.',
Il='Ilcanna:BAAALgADCgEJAQAAAA==.Illaynne:BAACLgAFFH8HAAIBAAMJRx39FwD9AAABAAMJRx39FwD9AAAuAAQKfzkAAgEACQmTIFcPAHMCAAEACQmTIFcPAHMCAAAA.Ilvasir:BAAALgAECgIJAgAAAA==.',
Im='Imani:BAACLgAFFH8XAAIoAAYJfQeZBwA+AQAoAAYJfQeZBwA+AQAuAAQKfzIAAigACQncGCQNAO4BACgACQncGCQNAO4BAAAA.Immensepain:BAABLgAECn8mAAIEAAgJqhD/fADXAQAEAAgJqhD/fADXAQAAAA==.Imnotbalding:BAAALgAECgQJBwAAAA==.Imtrynacrack:BAAALgADCgQJBAAAAA==.Imurhucklbry:BAAALgADCggJDQAAAA==.',
In='Inalee:BAAALgAECgcJEgAAAA==.Inoshikacho:BAABLgAECn89AAINAAkJ8g83EgCXAQANAAkJ8g83EgCXAQAAAA==.Invigoraiden:BAAALgADCgEJAQABLgAECgkJPAAjAF0UAA==.Involio:BAAALgAECgUJCQAAAA==.Invý:BAABLgAECn84AAIQAAkJ+xsqKABiAgAQAAkJ+xsqKABiAgAAAA==.',
Ir='Irelià:BAAALgAECgUJCQAAAA==.Irenna:BAAALgADCgUJBQAAAA==.Irishdorf:BAAALgAECgEJAQAAAA==.Irishdots:BAAALgAECgQJBAAAAA==.Irishdrake:BAAALgAECgMJAwAAAA==.Irishkicks:BAABLgAFFH8KAAIfAAYJtAPFMADxAAAfAAYJtAPFMADxAAAAAA==.Irishlife:BAAALgAECgQJBAAAAA==.Irishmecha:BAACLgAFFH8PAAIdAAUJjgS7BgD/AAAdAAUJjgS7BgD/AAAuAAQKfy4AAh0ACQl6Gx4FAEQCAB0ACQl6Gx4FAEQCAAAA.Irishtotems:BAAALgADCgQJBAAAAA==.Irishtraps:BAAALgADCgEJAQAAAA==.',
Is='Isandra:BAAALgADCgEJAQAAAA==.',
It='Itharillys:BAABLgAECn81AAIXAAkJRRYcIgBcAgAXAAkJRRYcIgBcAgAAAA==.',
Ja='Jaadu:BAAALgAECgIJAwAAAA==.',
Je='Jeennkiins:BAAALgAECgEJAQABLgAECgkJOwABAJ0dAA==.Jessibella:BAABLgAECn8pAAQWAAkJrhVUDwB6AgAWAAkJrhVUDwB6AgABAAIJwRgVWwBtAAACAAEJ5APFmQAeAAAAAA==.Jezzako:BAABLgAECn8ZAAMXAAcJbgtlaAAvAQAXAAYJIA1laAAvAQAmAAYJGwSgGwAaAQAAAA==.',
Ji='Jinx:BAABLgAECn8mAAQgAAcJ7xyWFwD3AQAgAAcJ7xyWFwD3AQAeAAMJvRdnZgB+AAAfAAEJiAr/yAAkAAABLgAECgkJJAAVAEMVAA==.',
Jo='Johali:BAABLgAECn8oAAIRAAgJrwjzAQCMAAARAAgJrwjzAQCMAAAAAA==.Jozan:BAAALgADCgkJCQAAAA==.',
Ju='Jupp:BAAALgAECgYJBQAAAA==.Justise:BAABLgAECn8fAAQhAAkJtBfeEQDMAQAhAAkJKxfeEQDMAQASAAUJFBgkVQD4AAARAAEJjQ4LRgAsAAAAAA==.Jutojerry:BAABLgAECn8YAAMeAAgJNB1VFAAMAgAeAAgJNB1VFAAMAgAfAAIJzhwVTQChAAAAAA==.',
['Jî']='Jîru:BAAALgADCgQJBAAAAA==.',
['Jö']='Jöhnblaze:BAACLgAFFH8KAAISAAQJHgpZKQAQAQASAAQJHgpZKQAQAQAuAAQKfyUABBIACQlQFBMwAI4BABIACAlsFBMwAI4BACEACAkTD70fADQBABEAAQlDC5l/ACoAAAAA.Jöker:BAAALgAECgUJBgAAAA==.',
Ka='Kaalya:BAAALgAECgQJBwAAAA==.Kaelus:BAAALgADCgEJAQAAAA==.Kaga:BAAALgAECgEJAQABLgAECgkJNAAFABkgAA==.Kahoona:BAABLgAECn8mAAIDAAgJYSXxBQBZAwADAAgJYSXxBQBZAwAAAA==.Kailys:BAACLgAFFH8KAAIYAAMJaQv0DgCRAAAYAAMJaQv0DgCRAAAuAAQKfzgAAhgACQnvFukWAGoBABgACQnvFukWAGoBAAAA.Kaishias:BAABLgAECn8tAAIQAAkJ7h12GQCrAgAQAAkJ7h12GQCrAgAAAA==.Kamyra:BAABLgAECn8cAAIQAAgJVQu8rwAfAQAQAAgJVQu8rwAfAQAAAA==.Kando:BAAALgAECgkJCQAAAA==.Kandoh:BAAALgAECgEJAQABLgAECgkJCQAHAAAAAA==.Kandoith:BAAALgAECgEJAQABLgAECgkJCQAHAAAAAA==.Kanimeh:BAAALgADCgQJBAAAAA==.Kankuró:BAACLgAFFH8KAAIXAAMJyg+YZwDWAAAXAAMJyg+YZwDWAAAuAAQKf04AAxcACQm0I9cGACkDABcACQm0I9cGACkDABkAAQnIB2qOAC0AAAAA.Karmella:BAAALgAECgQJBAAAAA==.Kartoshka:BAAALgAECgEJAQABLgAECgYJFQANAJEKAA==.',
Ke='Kedzen:BAAALgAECgYJCAABLgAECggJOQAUAMMXAA==.Kenway:BAAALgAECgYJCwAAAA==.Kerfur:BAAALgAECgMJAwAAAA==.',
Ki='Killudead:BAAALgAECggJEQAAAA==.',
Ko='Kodetra:BAABLgAECn8YAAIKAAYJLgcFYAC6AAAKAAYJLgcFYAC6AAAAAA==.Kolgrim:BAACLgAFFH8GAAMJAAIJCRbmLgCKAAAJAAIJCRbmLgCKAAAGAAIJhQPr/wBrAAAuAAQKfyIAAwkACQkfG3IhAEcBAAkACAkhG3IhAEcBAA4ABgkFE7EWACIBAAAA.Korimya:BAAALgAECgEJAgAAAA==.Korva:BAABLgAECn8aAAMeAAgJAxFDKwBeAQAeAAgJAxFDKwBeAQAgAAIJNA5/agBkAAAAAA==.',
Kr='Krianthess:BAAALgAFFAEJAQAAAA==.Krissypoo:BAAALgAECgMJAwAAAA==.Kristie:BAABLgAECn8bAAIEAAcJwQ6NugBsAQAEAAcJwQ6NugBsAQABLgAECggJGgAeAAMRAA==.Krom:BAABLgAECn8xAAIUAAgJPhAcVABkAQAUAAgJPhAcVABkAQAAAA==.',
Ku='Kuadonaran:BAAALgADCgEJAQABLgAECgkJNQAaADQiAA==.Kulitcomandr:BAAALgADCgUJBQAAAA==.Kungfuopanda:BAAALgADCgEJAQAAAA==.Kupquake:BAACLgAFFH8NAAIgAAUJ6gqgHwDbAAAgAAUJ6gqgHwDbAAAuAAQKfy8AAiAACAmwH7cQAHYCACAACAmwH7cQAHYCAAEuAAUUBgkRAAUALBQA.',
Ky='Kynris:BAAALgADCgMJAwABLgAECgkJKAAWALEgAA==.',
La='Laancelot:BAAALgADCgkJDgAAAA==.Lacy:BAAALgADCgEJAQAAAA==.Laetus:BAAALgAECgUJDQAAAA==.Lamort:BAABLgAECn81AAQaAAkJNCL5GACOAgAaAAgJoR/5GACOAgAlAAcJ8yIaBwADAgAbAAYJcxrfEQAqAQAAAA==.Lanaal:BAAALgADCgIJAgAAAA==.Lancewh:BAAALgADCgkJFwAAAA==.Lanciwinluna:BAAALgADCgUJBQAAAA==.Lancywinelia:BAAALgADCgYJBgAAAA==.Lashbane:BAAALgAECgEJAQABLgAECgMJCQAHAAAAAA==.Launzi:BAAALgADCgkJFwAAAA==.Lavirna:BAAALgAECgEJAQABLgAECggJGgAeAAMRAA==.Lazulli:BAAALgADCgMJAwAAAA==.',
Ld='Ldyartavash:BAAALgADCgkJCQAAAA==.',
Le='Leaila:BAAALgAECgYJEAAAAA==.Ledollabean:BAAALgAECgEJAQAAAA==.Legg:BAAALgADCgEJAQAAAA==.Leonora:BAABLgAECn8oAAIZAAkJvA91DQCIAQAZAAkJvA91DQCIAQAAAA==.Levdk:BAAALgAFFAEJAgAAAA==.',
Li='Lightbreakk:BAAALgADCgkJDwABLgAECgUJBwAHAAAAAA==.Lindesong:BAAALgAECgQJBQABLgAFFAgJFQAXAFMaAA==.Linstriker:BAAALgAECgMJAwABLgAFFAcJHwAVAFEeAA==.Lisondrel:BAAALgAECgUJBwAAAA==.',
Lo='Lockbone:BAAALgAECgMJAwAAAA==.Loops:BAACLgAFFH8MAAImAAQJeBp9DgBQAQAmAAQJeBp9DgBQAQAuAAQKfyEAAiYACQnpHo0TAAoCACYACQnpHo0TAAoCAAAA.Lorette:BAACLgAFFH8MAAMBAAQJKxZ4FAAgAQABAAQJKxZ4FAAgAQACAAEJ5hNXOQBHAAAuAAQKfyIAAwIACQkjHpMVAB8CAAIACAmKHZMVAB8CAAEACQmnGM8pAHkBAAAA.Lovelychow:BAAALgADCgYJCQAAAA==.',
Lu='Luckynyx:BAABLgAECn8ZAAIVAAcJ8QS5YADDAAAVAAcJ8QS5YADDAAAAAA==.Lunate:BAAALgAECgUJCAABLgAECgkJMQAKAJgcAA==.',
Lw='Lwinterheart:BAAALgADCgYJCwAAAA==.',
Ly='Ly:BAAALgADCgUJBQAAAA==.Lymriina:BAACLgAFFH8GAAIcAAMJaROkDQARAQAcAAMJaROkDQARAQAuAAQKfxwAAhwACAlsI5wHABYDABwACAlsI5wHABYDAAEuAAUUCAkVABcAUxoA.Lyr:BAAALgADCgcJBwAAAA==.',
Ma='Machotedan:BAACLgAFFH8GAAIQAAQJQRYpQAAqAQAQAAQJQRYpQAAqAQAuAAQKfzQAAhAACQmWIRAVAMQCABAACQmWIRAVAMQCAAAA.Macmittens:BAABLgAECn8rAAIMAAkJjxJBAQADAQAMAAkJjxJBAQADAQAAAA==.Magedude:BAAALgAECgIJAgAAAA==.Mahuna:BAAALgAECggJCAABLgAECgkJCQAHAAAAAA==.Makoes:BAAALgADCgkJCQAAAA==.Maliken:BAABLgAECn8fAAIGAAgJ7B34JQCkAgAGAAgJ7B34JQCkAgAAAA==.Mamadrag:BAABLgAECn8kAAQLAAgJThyTDQD3AQALAAcJDByTDQD3AQAKAAMJXgblWABbAAAkAAIJ8Aa/IABOAAAAAA==.Mambø:BAAALgADCgYJBgAAAA==.Managua:BAAALgAECgIJBQAAAA==.Mandwa:BAAALgAECgcJBwABLgAECgkJNAAFABkgAA==.Mario:BAACLgAFFH8LAAIEAAQJ4AliawANAQAEAAQJ4AliawANAQAuAAQKfyEAAgQACQkAGHc7ACwCAAQACQkAGHc7ACwCAAAA.Masivewin:BAAALgAECgEJAQAAAA==.Mastashifta:BAABLgAECn8aAAQNAAYJIBXCHAAlAQANAAYJ2xPCHAAlAQAIAAUJBRFcTADaAAADAAIJCA2OugBLAAAAAA==.Mataa:BAAALgAECgEJAQABLgAECgkJKAAWALEgAA==.Matryoshka:BAABLgAECn8VAAINAAYJkQqxKwC4AAANAAYJkQqxKwC4AAAAAA==.Mattsadler:BAAALgAECgEJAwAAAA==.Maverex:BAAALgAFFAEJAQAAAA==.Mavok:BAAALgAECgIJBAAAAA==.Maxxim:BAAALgAECgQJBgAAAA==.Mayihmpurleg:BAAALgAECgMJAwABLgAFFAQJCgAZAM4PAA==.Mazeman:BAAALgADCgMJAwAAAA==.',
Mc='Mcnugs:BAAALgAECgUJCQAAAA==.',
Me='Mechamonk:BAAALgADCgIJAgAAAA==.Mellachion:BAAALgAECgEJAQABLgAFFAQJCwAEAOAJAA==.Merczdk:BAAALgADCgYJDAAAAA==.Merczlock:BAAALgAECgQJBAAAAA==.Meta:BAACLgAFFH8IAAIFAAUJdA+oTQACAQAFAAUJdA+oTQACAQAuAAQKfxsAAgUACQlpHKodAGICAAUACQlpHKodAGICAAAA.',
Mi='Mignus:BAAALgAECgIJAwAAAA==.Mindfreeze:BAAALgADCgUJBQAAAA==.Minidudde:BAAALgAECgMJAwAAAA==.Minthara:BAAALgADCgYJDgAAAA==.Missdemon:BAAALgADCgUJBgAAAA==.Missikrissi:BAAALgADCgYJBwAAAA==.Missmorrigan:BAABLgAECn8RAAIFAAgJvwGL9gBWAAAFAAgJvwGL9gBWAAAAAA==.Missî:BAABLgAECn8YAAIUAAcJSAiubAAWAQAUAAcJSAiubAAWAQAAAA==.Mists:BAACLgAFFH8MAAIaAAcJ1BbuDgBnAQAaAAcJ1BbuDgBnAQAuAAQKfyQAAxoACAmLJOwLABsDABoACAmLJOwLABsDABsAAgmaHfZHAJcAAAAA.Miththrawndo:BAABLgAECn81AAMJAAkJZx2YCQB5AgAJAAkJZx2YCQB5AgAOAAEJAAAyGwAIAAAAAA==.',
Ml='Ml:BAABLgAECn8UAAMbAAYJVh4HCwAPAgAbAAYJVh4HCwAPAgAaAAQJJg8FvgDPAAAAAA==.',
Mo='Moldevort:BAAALgAECgUJDQAAAA==.Momjeans:BAABLgAECn8vAAMTAAkJtB6cAQCzAgATAAcJkyGcAQCzAgAEAAkJ6xkTLgBhAgAAAA==.Monfanth:BAAALgAECgEJAQABLgAECggJGgAeAAMRAA==.Morningumbra:BAAALgADCgIJAgAAAA==.',
Ms='Mstryoda:BAAALgADCgUJCAAAAA==.',
Mu='Muramasa:BAAALgAECgkJDgAAAA==.',
My='Myfriendtold:BAAALgADCgEJAgAAAA==.Mythunsarian:BAABLgAECn8xAAIjAAkJXRJ3FwDJAQAjAAkJXRJ3FwDJAQAAAA==.',
['Mâ']='Mâximus:BAAALgAECgEJAgAAAA==.',
['Mä']='Mäylä:BAACLgAFFH8KAAIDAAMJHApWSQCUAAADAAMJHApWSQCUAAAuAAQKfzIAAgMACQkbFiUBAE4BAAMACQkbFiUBAE4BAAAA.',
['Mí']='Míst:BAABLgAECn9HAAIQAAkJDRqUIwB3AgAQAAkJDRqUIwB3AgAAAA==.',
Na='Nazaline:BAAALgADCgIJAgAAAA==.',
Ne='Necrohealiac:BAAALgAECgQJCQAAAA==.Necrotizer:BAAALgADCgMJAwAAAA==.Nephie:BAACLgAFFH8IAAIjAAMJYhjLGADbAAAjAAMJYhjLGADbAAAuAAQKfyUAAiMACQmCHrUNAEoCACMACQmCHrUNAEoCAAAA.Netazia:BAAALgADCgcJGQAAAA==.Nethralfus:BAAALgAECgEJAQAAAA==.Nezqk:BAACLgAFFH8dAAQGAAYJowvHRwBkAQAGAAUJowvHRwBkAQAOAAQJ4AHHFwDNAAAJAAEJAAAjYAAAAAAuAAQKfykAAwYACQloGxhdANsBAAYACQm1GhhdANsBAA4AAglyHHY0AEsAAAAA.',
Ni='Niano:BAAALgAECgEJAQAAAA==.Nirv:BAAALgAECgIJAwABLgAECgkJMQAKAJgcAA==.',
Nm='Nmnenthe:BAAALgAECggJDwAAAA==.',
No='Noelytv:BAAALgADCgcJBwAAAA==.Norman:BAAALgADCgEJAgAAAA==.Notrealword:BAAALgADCgYJBgABLgAECggJHgAXAJ0bAA==.November:BAAALgADCgEJAQAAAA==.Noxren:BAAALgAFFAEJAgAAAA==.',
['Nî']='Nîstø:BAABLgAECn8hAAQYAAgJFRdtDgDeAQAYAAcJzBhtDgDeAQAPAAYJIxxILgCkAQAQAAQJBQo4WQFYAAAAAA==.',
Ob='Obin:BAABLgAECn8pAAISAAkJnRYNJgDHAQASAAkJnRYNJgDHAQAAAA==.',
Oh='Oharachloe:BAAALgADCgYJBgAAAA==.',
Ok='Okotar:BAAALgAECgEJAgAAAA==.',
Ol='Ollenbock:BAAALgAECgYJBwABLgAFFAgJFQAXAFMaAA==.',
On='Onebaaddude:BAAALgAECgUJBQAAAA==.',
Or='Orhanu:BAAALgAECgcJCAAAAA==.',
Ou='Outbbreakk:BAAALgAECgUJBwAAAA==.',
Ow='Owendriel:BAACLgAFFH8LAAIFAAYJ4QZuQQAkAQAFAAYJ4QZuQQAkAQAuAAQKfxsAAgUACQkNF2w7AAYCAAUACQkNF2w7AAYCAAAA.',
Pa='Padocus:BAAALgAECgIJAgAAAA==.Pajamas:BAABLgAECn8zAAIXAAkJrR3rCgDuAgAXAAkJrR3rCgDuAgAAAA==.Pallycoot:BAAALgADCgYJBgABLgAECgkJKwAaAAAUAA==.Palyamorous:BAAALgADCgUJBQAAAA==.Pandress:BAABLgAECn8nAAIXAAkJWRgELgAlAgAXAAkJWRgELgAlAgAAAA==.Pankake:BAAALgAECgUJCAABLgAECgkJKQAeALUgAA==.Paralysis:BAABLgAFFH8RAAIFAAYJLBT5LABzAQAFAAYJLBT5LABzAQAAAA==.',
Pe='Peetza:BAAALgAECgIJAgABLgAECgkJKQAeALUgAA==.Peryite:BAABLgAECn8qAAMWAAkJhhQEGQAKAgAWAAgJGRYEGQAKAgABAAcJSgolRwAdAQAAAA==.',
Ph='Phaedrana:BAAALgAECgEJAQAAAA==.Phelris:BAABLgAECn8YAAIFAAcJQg8ZdQA3AQAFAAcJQg8ZdQA3AQAAAA==.',
Pi='Pillpusher:BAAALgAECgMJBAAAAA==.Pisscat:BAABLgAECn8lAAMMAAgJqAVkPAC0AAAMAAgJqAVkPAC0AAANAAEJNwfPYQAfAAAAAA==.',
Po='Poisongooch:BAAALgAECgcJDAAAAA==.Polymerase:BAAALgAECgkJEQABLgAECgkJNgAGAIAhAA==.',
Pr='Pr:BAAALgAECgQJBAABLgAFFAUJDAAUAIUVAA==.Prideindeath:BAAALgAECgUJBQAAAA==.Promiscuity:BAABLgAECn8UAAIaAAgJBhF5WACUAQAaAAgJBhF5WACUAQAAAA==.Protròast:BAAALgAECgQJBQAAAA==.Prængle:BAABLgAECn8UAAIfAAYJ6RYDPACAAQAfAAYJ6RYDPACAAQAAAA==.',
Ps='Psoas:BAAALgAECgcJDQABLgAECgkJMQAKAJgcAA==.Psypriest:BAABLgAFFH8WAAIBAAQJdiB7DQBzAQABAAQJdiB7DQBzAQABLgAFFAgJPgABAD0gAA==.',
Pu='Pulverine:BAAALgADCgcJDgAAAA==.',
Qu='Quarantinia:BAAALgADCgEJAQAAAA==.',
Ra='Rabbi:BAABLgAECn8xAAMCAAgJ8BtYEwA2AgACAAgJ8BtYEwA2AgABAAUJaA7TTgD9AAAAAA==.Ragerunnerx:BAAALgAECggJDwAAAA==.Rahfna:BAAALgAECgEJBQAAAA==.Rakan:BAAALgADCgIJAgAAAA==.Raledia:BAAALgAECgYJCAAAAA==.Rasaki:BAAALgAECggJCAABLgAECgkJCQAHAAAAAA==.Raynare:BAAALgAECgMJBAAAAA==.',
Re='Reboot:BAAALgADCgcJBwAAAA==.Redall:BAABLgAECn8pAAIZAAkJxg6uDACXAQAZAAkJxg6uDACXAQAAAA==.Reesespbc:BAABLgAECn88AAIEAAkJ4BAOVgDbAQAEAAkJ4BAOVgDbAQAAAA==.Reina:BAABLgAECn8kAAIQAAcJrhfwagCZAQAQAAcJrhfwagCZAQABLgAECgkJJAAVAEMVAA==.Reinir:BAABLgAECn8wAAIhAAkJjCMVBADpAgAhAAkJjCMVBADpAgAAAA==.Reinz:BAABLgAECn8hAAQeAAgJpBk0FgD5AQAeAAgJpBk0FgD5AQAfAAUJshiYQgBjAQAgAAEJ2w4pnAAzAAAAAA==.Rektagar:BAABLgAECn8oAAMVAAkJZiO0EABtAgAVAAgJHyO0EABtAgAUAAQJSR0KXQBGAQABLgAFFAgJFQAXAFMaAA==.Resident:BAAALgAECgQJBgABLgAECgkJMQAKAJgcAA==.Ressandra:BAAALgAECggJDQAAAA==.Reyvanna:BAAALgADCgEJAQAAAA==.Rezo:BAAALgADCgUJBQAAAA==.',
Ro='Roar:BAAALgAECgUJCAABLgAECgkJKwAGAMgUAA==.Robert:BAAALgADCgEJAQAAAA==.Rosavyra:BAAALgAECggJCQAAAA==.Roshara:BAABLgAECn8UAAIaAAYJYwTC0QCxAAAaAAYJYwTC0QCxAAAAAA==.',
Ry='Ryanbutscaly:BAAALgAECgUJCQABLgAFFAQJBgAEADANAA==.Ryce:BAAALgAECgkJDQABLgAECgkJKQAeALUgAA==.Ryoka:BAAALgAECgIJAgAAAA==.',
['Rö']='Rös:BAACLgAFFH8fAAIEAAYJqyDFKwDDAQAEAAYJqyDFKwDDAQAuAAQKfzcAAwQACQntIFUZAMECAAQACQntIFUZAMECACkAAQlfINwMAF0AAAAA.',
['Rü']='Rübblë:BAABLgAECn8eAAMgAAgJagrYOgAWAQAgAAgJKwrYOgAWAQAeAAYJuwjeTADLAAAAAA==.',
Sa='Saberie:BAAALgAECgQJBwABLgAECggJDQAHAAAAAA==.Sacredice:BAAALgAECgUJBgABLgAECggJHQAUALQXAA==.Salamun:BAAALgAECgQJBQAAAA==.Salaria:BAABLgAECn8kAAIFAAkJGArGZgBZAQAFAAkJGArGZgBZAQAAAA==.Salen:BAABLgAECn9NAAMoAAkJeRxWBgB1AgAoAAkJeRxWBgB1AgAUAAQJoQUYpQCDAAAAAA==.Salina:BAEBLgAECn8sAAIiAAkJFhavCwCfAQAiAAkJFhavCwCfAQAAAA==.Sandraia:BAACLgAFFH8KAAIGAAMJ5xTVpwDMAAAGAAMJ5xTVpwDMAAAuAAQKfykAAgYACQkNHDk7ABQCAAYACQkNHDk7ABQCAAAA.Sandstique:BAABLgAECn8gAAIUAAkJuCFqCADvAgAUAAkJuCFqCADvAgAAAA==.Sandtwig:BAAALgADCgEJAQAAAA==.Sandweaver:BAAALgAECgEJAQAAAA==.Sanjira:BAABLgAECn8gAAInAAkJowlaCwBkAQAnAAkJowlaCwBkAQAAAA==.Sarlak:BAABLgAECn8pAAIXAAkJOxm+HQBzAgAXAAkJOxm+HQBzAgAAAA==.Sarusuby:BAACLgAFFH8NAAIMAAQJDAYJIwCPAAAMAAQJDAYJIwCPAAAuAAQKfysAAgwACQkmFKEfAFABAAwACQkmFKEfAFABAAAA.Satae:BAAALgAECgUJCAABLgAECgkJKQAeALUgAA==.',
Sc='Schucks:BAAALgAECgMJAwAAAA==.Schuffles:BAAALgAECgEJAQAAAA==.Scottyfist:BAACLgAFFH8MAAIeAAQJZRlJHQA/AQAeAAQJZRlJHQA/AQAuAAQKfx4AAh4ACQkzIHoWAFUCAB4ACQkzIHoWAFUCAAAA.Scottymac:BAAALgAFFAEJAQABLgAFFAQJDAAeAGUZAA==.',
Se='Sealion:BAACLgAFFH8JAAMPAAMJVyCeEQDDAAAPAAIJQB2eEQDDAAAQAAIJlAuDoAB+AAAuAAQKfxoAAw8ACQmUF2AWAF4CAA8ACQmUF2AWAF4CABAAAwltI8z+ALkAAAAA.Seatah:BAAALgADCgcJBwAAAA==.Seba:BAAALgAECgMJBgAAAA==.Seeta:BAAALgAECggJDQAAAA==.Seetah:BAACLgAFFH8FAAIBAAIJYxc3JwCJAAABAAIJYxc3JwCJAAAuAAQKfyQAAgEACAmPIrsIAMACAAEACAmPIrsIAMACAAAA.Seetur:BAAALgAECgQJBAAAAA==.Seetusk:BAAALgAECgUJBQAAAA==.Serratus:BAABLgAECn8xAAQKAAkJmBx5FAA4AgAKAAkJ7xh5FAA4AgAkAAgJqhsKBgD1AQALAAEJTgRAPgArAAAAAA==.Setcher:BAAALgADCgEJAQAAAA==.',
Sh='Shadaddy:BAACLgAFFH8QAAIEAAQJ6xVnVgAwAQAEAAQJ6xVnVgAwAQAuAAQKfywAAgQACQnUH9kRAO8CAAQACQnUH9kRAO8CAAEuAAUUBAkKAAYAUhIA.Shadowheart:BAAALgAECgcJCgAAAA==.Shadowsyther:BAAALgAECgYJBgAAAA==.Shal:BAAALgAFFAIJAgAAAA==.Shamax:BAAALgADCgEJAgABLgADCgUJBQAHAAAAAA==.Shamommy:BAAALgAECgUJEAAAAA==.Shayes:BAABLgAECn8rAAIMAAkJfR7zBQCmAgAMAAkJfR7zBQCmAgAAAA==.Shifue:BAAALgAFFAEJAQAAAA==.Shimmerstar:BAACLgAFFH8OAAIQAAUJuhwHAwA3AQAQAAUJuhwHAwA3AQAuAAQKfykAAhAACQk8H5kXALUCABAACQk8H5kXALUCAAAA.Shroomgirl:BAAALgAFFAEJAQAAAA==.',
Si='Sigg:BAAALgAECgUJBQAAAA==.Silexe:BAAALgAECgUJBwABLgAECgkJNQAaADQiAA==.Sitar:BAAALgAECgEJAQABLgAECgkJNAAFABkgAA==.Sixseven:BAAALgAECgQJBAAAAA==.',
Sk='Skathae:BAAALgAECgEJAQABLgAECgkJKAAWALEgAA==.Skuld:BAAALgAECgUJBQAAAA==.Skåld:BAABLgAECn8pAAMGAAkJ5hg8LQBLAgAGAAkJ5hg8LQBLAgAJAAEJAADrcAAAAAAAAA==.',
Sl='Slinga:BAAALgAECgUJBQAAAA==.Slipperyboi:BAAALgAFFAEJAwAAAA==.',
Sn='Snuffles:BAABLgAECn8fAAImAAgJ2BqKGQDTAQAmAAgJ2BqKGQDTAQAAAA==.Snugs:BAAALgADCgEJAQAAAA==.',
So='Sofiya:BAAALgADCgEJAQAAAA==.Soldraca:BAABLgAECn8XAAMLAAYJfhS3FQBxAQALAAYJfhS3FQBxAQAkAAEJewOORAAkAAAAAA==.Solthorne:BAAALgADCgEJAQAAAA==.Soulence:BAAALgAECgMJBAAAAA==.Soymaster:BAAALgADCgYJBgABLgAFFAQJCAAVAAYSAA==.',
Sp='Spiritdom:BAAALgADCgUJCAAAAA==.',
St='Stinkbug:BAAALgADCgcJFAAAAA==.Stutters:BAABLgAECn82AAMGAAkJgCHHEgDYAgAGAAkJgCHHEgDYAgAJAAYJNhkpIABDAQAAAA==.',
Su='Sudachi:BAACLgAFFH8LAAMRAAUJ5xDaGgARAQARAAQJbxLaGgARAQAhAAEJxwq2LAA9AAAuAAQKfxcAAxEACQlAG40EAKMCABEACQlAG40EAKMCABIAAgkDDViUAG4AAAEuAAUUBQkJACAAqxwA.Sunnyräy:BAAALgADCgcJDQAAAA==.Suthrheimr:BAAALgAECgcJCQABLgAFFAQJCwAmAKcNAA==.',
Sw='Swineflu:BAAALgAECgMJAwAAAA==.Swizzjenks:BAAALgADCgMJAwAAAA==.',
Sy='Synonym:BAAALgADCgcJBwAAAA==.Syrabane:BAAALgAECgYJBgAAAA==.Syrprize:BAAALgADCgEJAQABLgAECggJGAAeADQdAA==.',
['Sý']='Sýndrá:BAABLgAECn8qAAMbAAkJSSJcAQDaAgAbAAkJOSFcAQDaAgAaAAMJ1RdSrwDlAAAAAA==.',
Ta='Tachyon:BAAALgAECgcJDgAAAA==.Tacobob:BAACLgAFFH8LAAIDAAQJBgazPgC1AAADAAQJBgazPgC1AAAuAAQKfy4AAgMACAlxFm83AMkBAAMACAlxFm83AMkBAAAA.Taethron:BAAALgADCgUJBQAAAA==.Taffeta:BAAALgADCgEJAQAAAA==.Taffyboy:BAAALgADCggJCgAAAA==.Taiya:BAAALgADCgYJBgABLgAECgkJKQAGAOYYAA==.Talespin:BAAALgADCgEJAQAAAA==.Talysiah:BAABLgAECn8cAAIaAAkJPwsyWwCMAQAaAAkJPwsyWwCMAQAAAA==.Tannir:BAAALgAECgEJAQAAAA==.Tarogen:BAAALgADCgQJBgABLgAFFAYJFwAfALMhAA==.Tavhunts:BAAALgAECgEJAQAAAA==.Tavok:BAACLgAFFH8GAAISAAMJARsPLQD/AAASAAMJARsPLQD/AAAuAAQKf0MAAxIACAl4JDQJAM8CABIACAl4JDQJAM8CACEAAQn4FQZEAD0AAAAA.',
Te='Tenacious:BAAALgADCgcJDAAAAA==.Tene:BAAALgADCgMJAwAAAA==.Teratots:BAAALgADCgYJBgAAAA==.Testament:BAAALgADCgcJCAAAAA==.Teusday:BAAALgAECgcJDQAAAA==.',
Th='Thenna:BAAALgAECgMJAwAAAA==.Theosclaws:BAAALgADCgcJDgAAAA==.Theramier:BAABLgAECn8ZAAIQAAYJSgkx3QDiAAAQAAYJSgkx3QDiAAAAAA==.Thiux:BAABLgAECn8jAAQaAAkJ3yEDFgChAgAaAAkJ3yEDFgChAgAlAAEJOB1gMgBXAAAbAAEJAAByXQBWAAAAAA==.Thotsnprayrs:BAAALgADCgUJCAABLgAECggJGAAeADQdAA==.Thourin:BAAALgADCgEJAQAAAA==.Thrappy:BAACLgAFFH8MAAIUAAUJhRWJHQCCAQAUAAUJhRWJHQCCAQAuAAQKfzUAAhQACQk5IS0IAC0DABQACQk5IS0IAC0DAAAA.Thráwñ:BAAALgAECgMJBAAAAA==.',
Ti='Tiddyhammer:BAABLgAECn8kAAMQAAgJVR3YOgAYAgAQAAcJVR3YOgAYAgAPAAcJnRRlRQBiAQAAAA==.Tinora:BAAALgADCgEJAQABLgAECggJOQAUAMMXAA==.Tintaglia:BAAALgAFFAIJAgABLgAFFAQJCwAEAOAJAA==.Tirtun:BAACLgAFFH8NAAIEAAQJ7RZoVQAyAQAEAAQJ7RZoVQAyAQAuAAQKfysAAgQACAlbIZYxAFMCAAQACAlbIZYxAFMCAAAA.',
To='Tomek:BAABLgAECn8tAAMmAAkJGBzeDgA+AgAmAAkJ8hjeDgA+AgAZAAcJyB8MDgB+AQAAAA==.Torukmakto:BAAALgADCggJCAAAAA==.Totemetot:BAAALgAECgYJDwAAAA==.',
Tr='Treemourne:BAAALgADCgEJAQAAAA==.Triggeer:BAABLgAECn8zAAIhAAkJxRbxFACkAQAhAAkJxRbxFACkAQAAAA==.',
Tu='Tully:BAAALgADCgEJAQAAAA==.Turalus:BAAALgADCgYJBgAAAA==.Turina:BAABLgAECn8gAAIaAAgJ+wV0BACbAAAaAAgJ+wV0BACbAAAAAA==.',
Tw='Twelvekill:BAACLgAFFH8dAAIXAAYJ9hZeGgCeAQAXAAYJ9hZeGgCeAQAuAAQKfzIAAhcACQkBHiYaAGsCABcACQkBHiYaAGsCAAAA.',
Ty='Tyliaa:BAACLgAFFH8KAAIUAAMJox4OOAACAQAUAAMJox4OOAACAQAuAAQKfy4AAxQACQmjIUUJAB4DABQACQmjIUUJAB4DABUAAQmFCLa1ACYAAAEuAAQKCAkkAAsAThwA.Tylidus:BAAALgAECgcJCwAAAA==.Tyranny:BAAALgAECgYJEgAAAA==.',
Ub='Ubisami:BAABLgAECn8YAAIOAAgJmAkUCwASAQAOAAgJmAkUCwASAQAAAA==.',
Ud='Udderfailure:BAAALgADCgIJAgAAAA==.',
Uk='Ukstryker:BAAALgAFFAIJAgABLgAFFAMJDAAJACgdAA==.',
Ul='Ullur:BAAALgADCgEJAgAAAA==.Ultramon:BAABLgAECn83AAIQAAkJgw9eXwCyAQAQAAkJgw9eXwCyAQAAAA==.Uly:BAABLgAECn8bAAMFAAcJVSCPOADkAQAFAAYJRCGPOADkAQAiAAEJrBuJLABQAAAAAA==.',
Un='Unwell:BAAALgAECgYJEAABLgAFFAUJDgAcAHcbAA==.',
Up='Uplok:BAAALgADCgIJAgAAAA==.',
Ur='Urgoochness:BAABLgAECn8iAAIDAAgJshYVMwDSAQADAAgJshYVMwDSAQAAAA==.Urikhai:BAAALgAECgQJBQAAAA==.',
Uw='Uwuwu:BAAALgAECgEJAQAAAA==.',
Va='Vaellvoid:BAAALgAECgMJAwAAAA==.Vainglorious:BAABLgAECn8VAAIPAAYJMhz9JgDSAQAPAAYJMhz9JgDSAQABLgAECgkJMQAJAOQbAA==.Valanora:BAABLgAECn8qAAIlAAkJ0BqjAwBbAgAlAAkJ0BqjAwBbAgAAAA==.Valdis:BAAALgADCgcJDgABLgAECggJGgAeAAMRAA==.Valinaxius:BAABLgAECn8fAAMJAAYJiB4BGQCZAQAJAAYJiB4BGQCZAQAGAAQJ7Ah9AQGqAAAAAA==.Valphalk:BAAALgADCggJCQAAAA==.Vanastasia:BAAALgAECgQJBgAAAA==.Vanyr:BAAALgAECgQJBAAAAA==.Vapturov:BAABLgAECn8WAAIGAAYJdQuWzQDsAAAGAAYJdQuWzQDsAAAAAA==.',
Ve='Veeks:BAAALgAECgcJDwAAAA==.Velikirn:BAABLgAECn84AAMgAAkJASMaBwDYAgAgAAkJ5yIaBwDYAgAeAAgJQhnWGADfAQAAAA==.Vellwinnalas:BAAALgADCgUJCAAAAA==.Verah:BAAALgADCgYJBgAAAA==.Versø:BAABLgAECn8qAAQnAAkJURgVBgD2AQAdAAYJSBvvBgD9AQAnAAkJ2xQVBgD2AQAcAAQJ1hmHPgAoAQAAAA==.',
Vi='Villageinn:BAAALgAECgMJAwAAAA==.Vine:BAAALgAECgYJEQAAAA==.Vixxon:BAACLgAFFH8FAAIXAAMJZwVlCwCHAAAXAAMJZwVlCwCHAAAuAAQKfzwAAhcACQk1F905APcBABcACQk1F905APcBAAAA.',
Vl='Vlai:BAAALgAECgIJAwABLgAFFAMJAwAHAAAAAA==.Vly:BAABLgAECn8aAAMcAAkJBg7fJgBgAQAcAAkJoAzfJgBgAQAdAAYJmwmwEwDtAAABLgAFFAMJAwAHAAAAAA==.Vlyrae:BAAALgAECgUJCwABLgAFFAMJAwAHAAAAAA==.Vlysham:BAAALgAECgMJAwABLgAFFAMJAwAHAAAAAA==.Vlythyr:BAAALgAFFAMJAwAAAA==.Vlyzen:BAAALgAECgQJBQABLgAFFAMJAwAHAAAAAA==.',
Vo='Voidhearted:BAABLgAECn87AAICAAkJJx4eDACOAgACAAkJJx4eDACOAgAAAA==.',
Vu='Vulpy:BAAALgAECgEJAQABLgAECggJEgAHAAAAAA==.Vultrash:BAAALgADCgIJAgAAAA==.',
['Vì']='Vìolet:BAAALgAECgYJEwABLgAFFAIJBQAIACsgAA==.',
['Ví']='Víolet:BAABLgAECn8ZAAIjAAgJIht+DwAvAgAjAAgJIht+DwAvAgAAAA==.',
Wa='Waggleton:BAAALgAECgEJAgAAAA==.Warp:BAAALgADCgEJAQAAAA==.Washyourasz:BAAALgAECgkJEwAAAA==.Wasted:BAAALgADCgEJAQABLgAFFAUJDAAUAIUVAA==.Wayshua:BAAALgAECgUJBwAAAA==.',
We='Wearyouout:BAAALgADCgUJBQAAAA==.Wemon:BAAALgAECggJEQAAAA==.Werkajerk:BAACLgAFFH8FAAQeAAQJWBx1PAC1AAAeAAIJzB91PAC1AAAfAAEJ+iA6VABaAAAgAAEJaxMdPgBEAAAuAAQKfzAABB4ACQloI6gGAM8CAB4ACAkgJKgGAM8CAB8AAQnrI7CXAGgAACAAAQnAF0V0AEQAAAEuAAUUBwkfABUAUR4A.Werkjathal:BAACLgAFFH8fAAQVAAcJUR5lAwC1AQAVAAYJUR5lAwC1AQAoAAUJeSPTBQBiAQAUAAMJoAyqGwCKAAAuAAQKfzQABCgACQnFJQMBAEEDACgACQkOJAMBAEEDABUACAknIxkOAMICABQABwnDI4oNAK8CAAAA.Wetribs:BAAALgADCgkJCQAAAA==.',
Wh='Whereareyou:BAAALgADCgkJCQABLgAECgYJFgAXAPoYAA==.Whitedog:BAAALgAECgEJAQAAAA==.Whitetank:BAABLgAECn8gAAIYAAgJBhlPEwCVAQAYAAgJBhlPEwCVAQAAAA==.',
Wi='Willowbeard:BAABLgAECn8UAAIVAAgJXwqUQgApAQAVAAgJXwqUQgApAQAAAA==.Winnelepooh:BAAALgADCgQJBAAAAA==.Winnithebrew:BAAALgAECgYJBwAAAA==.',
Wo='Wobys:BAABLgAECn8dAAIfAAgJWRTaOgCGAQAfAAgJWRTaOgCGAQAAAA==.Wolfblitzer:BAACLgAFFH8HAAIQAAMJuRBhcgDOAAAQAAMJuRBhcgDOAAAuAAQKfzMAAhAACQlyGqYoAGACABAACQlyGqYoAGACAAAA.Wolfmanbro:BAAALgAECgQJBAAAAA==.Worgenator:BAAALgADCgMJAwAAAA==.Worldbane:BAABLgAECn9DAAIbAAkJORWGBgD4AQAbAAkJORWGBgD4AQAAAA==.',
['Wä']='Wärchild:BAAALgAECgUJEAAAAA==.',
Xa='Xalaa:BAAALgAECgYJCgAAAA==.Xalataxfraud:BAAALgAECgQJBAAAAA==.Xanin:BAAALgAECgIJAgABLgAECgQJBgAHAAAAAA==.Xanthos:BAAALgAECgYJEwAAAA==.Xantosz:BAAALgAECgEJAQABLgAFFAYJGwAVAKIVAA==.',
Xe='Xenthriel:BAAALgAECgEJAQAAAA==.',
Xi='Xianyu:BAABLgAECn80AAIeAAgJjhHyJACFAQAeAAgJjhHyJACFAQAAAA==.Ximmer:BAAALgAECgEJAQAAAA==.',
Xr='Xrispy:BAAALgAECgQJBwABLgAFFAUJDAAUAIUVAA==.',
Ya='Yarian:BAAALgAECgMJAwAAAA==.',
Yi='Yintalo:BAAALgAECgQJBAAAAA==.',
Yo='Yormin:BAABLgAECn8WAAIQAAUJcAYuIwGPAAAQAAUJcAYuIwGPAAAAAA==.Yorra:BAAALgAECgIJAgAAAA==.',
Yu='Yuzuu:BAABLgAECn8/AAMUAAkJTxH6LwD1AQAUAAkJTxH6LwD1AQAVAAEJrgGixQAUAAAAAA==.',
Za='Zachhunter:BAABLgAFFH8VAAMXAAgJUxoCEQDcAQAXAAYJrBoCEQDcAQAZAAYJJBGvFAAhAQAAAA==.Zakka:BAAALgAECgEJAgAAAA==.Zakkason:BAAALgAECgEJAwAAAA==.Zan:BAACLgAFFH8bAAMVAAYJohW/IwAKAQAVAAUJ9xS/IwAKAQAUAAUJqw8cOgD6AAAuAAQKfzAAAxUACQlRH6wTAIICABUACAmZH6wTAIICABQABAkpC9O8AFUAAAAA.',
Ze='Zephrie:BAAALgADCgYJBgAAAA==.',
Zo='Zohaan:BAAALgADCgEJAwAAAA==.Zoma:BAAALgADCggJDgAAAA==.',
Zu='Zuhura:BAAALgAECgUJCwAAAA==.Zultrix:BAABLgAECn8UAAIiAAYJyA7CGADZAAAiAAYJyA7CGADZAAAAAA==.',
Zy='Zylaeri:BAAALgAECgkJDwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
