local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Evoker-Augmentation','Mage-Fire','Mage-Frost','Shaman-Restoration','Shaman-Enhancement','Shaman-Elemental','DeathKnight-Unholy','Hunter-Marksmanship','Evoker-Preservation','Evoker-Devastation','Warlock-Demonology','Warlock-Destruction','Priest-Discipline','Priest-Holy','Druid-Guardian','DemonHunter-Devourer','Monk-Windwalker','Hunter-BeastMastery','Rogue-Outlaw','Monk-Brewmaster','Paladin-Holy','Rogue-Subtlety','Warrior-Fury','Monk-Mistweaver','DeathKnight-Frost','DeathKnight-Blood','Druid-Restoration','DemonHunter-Vengeance','Warrior-Arms','Warrior-Protection','Rogue-Assassination','Mage-Arcane','Paladin-Retribution','Paladin-Protection','DemonHunter-Havoc','Druid-Balance','Priest-Shadow','Hunter-Survival',}
local provider = {region='US',realm='MoonGuard',name='US',type='subscribers',zone=46,date='2026-08-11',data={Ag='Ageregressor:BAEALgAECgcJBwAAAA==.',
Ai='Aihime:BAEALgADCgYJBgABLgAECgEJAQABAAAAAA==.',
Al='Alcean:BAEBLgAECn8+AAICAAkJiCJ9BQAIAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQACAAkJiCJ9BQAIAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQAAAA==.Algebra:BAECLgAFFH8kAAMDAAgJxR7aAACXAQhoDAAACgBfAGkMAAAIAGEAawwAAAYAYwBqDAAABABaAGwMAAABAFkAbQwAAAEAIgDqDAAABQBZAG4MAAABAC4ABAAHCaQgnSQA6AEHaAwAAAYAWwBpDAAABQBhAGsMAAAEAGMAagwAAAIAWgBsDAAAAQBZAG0MAAABACIA6gwAAAQAWQADAAYJDyHaAACXAQZoDAAABABfAGkMAAADAF8AawwAAAIAYQBqDAAAAgBXAOoMAAABAFgAbgwAAAEALgAuAAQKfx0AAgQACQmhJAILACEDAAQACQmhJAILACEDAAAA.Aléyna:BAEALgAECgEJAgAAAA==.',
Ar='Araakki:BAEBLgAECn8YAAQFAAkJpR4SIgBDAgloDAAAAwA/AGkMAAACAEEAawwAAAIASwBqDAAAAwBYAGwMAAACAF0AbQwAAAEARwDqDAAACQBgAG4MAAABAEgAbwwAAAEATQAFAAcJAR8SIgBDAgdoDAAAAgA/AGkMAAABAEEAawwAAAEASwBqDAAAAQBYAGwMAAABAF0AbQwAAAEARwDqDAAACQBgAAYABQlgGUcFACkBBWgMAAABAFMAaQwAAAEAPQBrDAAAAQBFAGoMAAABAEoAbAwAAAEALQAHAAMJQQ+bHQBfAANqDAAAAQA7AG4MAAABABwAbwwAAAEAMQAAAA==.Aradell:BAEBLgAFFH8LAAIIAAQJWw4lgAAHAQRoDAAAAwAjAGkMAAADAB8AawwAAAIALADqDAAAAwAjAAgABAlbDiWAAAcBBGgMAAADACMAaQwAAAMAHwBrDAAAAgAsAOoMAAADACMAAAA=.Arceni:BAEALgAECgQJBAABLgAFFAQJCwAIAFsOAA==.Arteron:BAEALgAFFAIJAwABLgAFFAkJHgAJAMEcAA==.',
Ay='Ayoade:BAECLgAFFH9JAAMKAAkJvxocAgCBAgloDAAADQAzAGkMAAANAD0AawwAAA0ATgBqDAAABQBOAGwMAAAEAFkAbQwAAAQARQDqDAAACgBLAG4MAAAGAEcAbwwAAAUAJwAKAAkJvxocAgCBAgloDAAACgAzAGkMAAAKAD0AawwAAAwATgBqDAAABQBOAGwMAAAEAFkAbQwAAAQARQDqDAAACQBLAG4MAAAGAEcAbwwAAAUAJwACAAQJDyM1DACXAQRoDAAAAwBdAGkMAAADAFoAawwAAAEAVgDqDAAAAQBYAC4ABAp/HgADCgAICckeQQEALAIACgAICckeQQEALAIACwACCREV4zEAhwAAAAA=.',
Az='Azazaell:BAEALgAECgkJAQABLgAFFAgJEQAFAHUaAA==.Azzurel:BAEBLgAECn8ZAAMMAAkJ7BMcUQCoAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAwAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAAMAAkJ7BMcUQCoAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAgAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAANAAEJAAA+cgAzAAFqDAAAAQAUAAAA.',
Ba='Babaghanouj:BAEBLgAECn8qAAMOAAkJviHHAwBiAwloDAAABgBSAGkMAAAGAFkAawwAAAYAYQBqDAAABQBUAGwMAAAFAGEAbQwAAAQAWgDqDAAABQBNAG4MAAAEAEwAbwwAAAEAUAAOAAkJviHHAwBiAwloDAAAAwBSAGkMAAADAFkAawwAAAMAYQBqDAAAAwBUAGwMAAADAGEAbQwAAAIAWgDqDAAAAwBNAG4MAAADAEwAbwwAAAEAUAAPAAgJxBkeIgDTAQhoDAAAAwBBAGkMAAADAEgAawwAAAMATQBqDAAAAgA8AGwMAAACADkAbQwAAAIAQADqDAAAAgA1AG4MAAABAEsAAAA=.Bareskin:BAEBLgAFFH8FAAIQAAUJawpFHQCqAAVoDAAAAQAyAGkMAAABAAkAawwAAAEAGwBqDAAAAQAiAOoMAAABABMAEAAFCWsKRR0AqgAFaAwAAAEAMgBpDAAAAQAJAGsMAAABABsAagwAAAEAIgDqDAAAAQATAAEuAAUUBgkUABEANRUA.Basketcase:BAECLgAFFH8WAAIEAAgJeA1+LQC5AQhoDAAABAAXAGkMAAACAD4AawwAAAMAJQBqDAAAAgAeAGwMAAABABYAbQwAAAEACADqDAAACABNAG8MAAABAAkABAAICXgNfi0AuQEIaAwAAAQAFwBpDAAAAgA+AGsMAAADACUAagwAAAIAHgBsDAAAAQAWAG0MAAABAAgA6gwAAAgATQBvDAAAAQAJAC4ABAp/MwACBAAICe4kERoADwMABAAICe4kERoADwMAAAA=.',
Be='Bestcase:BAEBLgAFFH8HAAISAAQJARMsEgArAQRoDAAAAwBNAGkMAAABACkA6gwAAAIANQBuDAAAAQAVABIABAkBEywSACsBBGgMAAADAE0AaQwAAAEAKQDqDAAAAgA1AG4MAAABABUAAS4ABRQICRYABAB4DQA=.',
Bi='Bisqix:BAEALgAECgIJAgABLgAFFAgJGgATAK4TAA==.',
Bl='Bloodroyal:BAEALgAFFAIJAgABLgAFFAMJEgAUAKseAA==.',
Bo='Bobbysan:BAECLgAFFH8wAAIVAAkJZBvNAgBDAgloDAAACABZAGkMAAAHAFMAawwAAAYASQBqDAAABgBIAGwMAAAEADoAbQwAAAIARQDqDAAACABWAG4MAAAEADgAbwwAAAMAKwAVAAkJZBvNAgBDAgloDAAACABZAGkMAAAHAFMAawwAAAYASQBqDAAABgBIAGwMAAAEADoAbQwAAAIARQDqDAAACABWAG4MAAAEADgAbwwAAAMAKwAuAAQKfy8AAhUACQkYIZgKAOACABUACQkYIZgKAOACAAAA.',
Br='Brigbala:BAEALgAECgMJBgAAAA==.',
Bu='Buttlustplz:BAEALgAFFAEJAwABLgAFFAMJCQAWANgfAA==.',
Ch='Chunghús:BAEALgAECgYJBgABLgAFFAkJIwAKAMoNAA==.',
Cl='Clothdaddy:BAEALgAECgYJBgABLgAFFAkJIwAKAMoNAA==.',
Co='Coggettle:BAEBLgAECn8mAAITAAkJTCRGAQBCAwloDAAABQBgAGkMAAAFAF8AawwAAAUAXgBqDAAABQBjAGwMAAAFAGMAbQwAAAQAUgDqDAAABQBhAG4MAAADAFMAbwwAAAEAXQATAAkJTCRGAQBCAwloDAAABQBgAGkMAAAFAF8AawwAAAUAXgBqDAAABQBjAGwMAAAFAGMAbQwAAAQAUgDqDAAABQBhAG4MAAADAFMAbwwAAAEAXQAAAA==.',
Cr='Crustage:BAEALgAECgQJBgABLgAECggJLwAXAGoPAA==.Crustome:BAEBLgAECn8vAAIXAAgJag+FHgCiAQhoDAAACQAYAGkMAAAJACcAawwAAAgAMgBqDAAABgAaAGwMAAAEAD0AbQwAAAMAGwDqDAAABQAjAG4MAAADACUAFwAICWoPhR4AogEIaAwAAAkAGABpDAAACQAnAGsMAAAIADIAagwAAAYAGgBsDAAABAA9AG0MAAADABsA6gwAAAUAIwBuDAAAAwAlAAAA.Crustorc:BAEBLgAECn8hAAIYAAkJ5wlrMQCHAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABgAiAG4MAAAEABQAbwwAAAEAFQAYAAkJ5wlrMQCHAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABgAiAG4MAAAEABQAbwwAAAEAFQABLgAECggJLwAXAGoPAA==.Crustslap:BAEALgAECgQJBAABLgAECggJLwAXAGoPAA==.',
Cu='Cubed:BAEALgAFFAEJAgABLgAFFAgJJAADAMUeAA==.',
Da='Darkstrand:BAEALgAFFAIJAgABLgAFFAMJEgAUAKseAA==.Daylea:BAECLgAFFH85AAICAAkJ/CAGAgAmAwloDAAACQBgAGkMAAAIAGMAawwAAAgAYABqDAAABABfAGwMAAAGAF8AbQwAAAQATgDqDAAACgBjAG4MAAAEAC8AbwwAAAQAPgACAAkJ/CAGAgAmAwloDAAACQBgAGkMAAAIAGMAawwAAAgAYABqDAAABABfAGwMAAAGAF8AbQwAAAQATgDqDAAACgBjAG4MAAAEAC8AbwwAAAQAPgAuAAQKfyUAAwIACQnGJWgBALQDAAIACQnGJWgBALQDAAsABAm3IZUPABIBAAAA.',
De='Deathhealher:BAEALgAECgMJAwABLgAECggJKQARANcLAA==.Deathhunterz:BAEBLgAECn8pAAIRAAgJ1wsdEQADAQhoDAAABgAoAGkMAAAGACAAawwAAAcAFABqDAAABAAaAGwMAAAFACcAbQwAAAMAIwDqDAAACAAbAG4MAAACABAAEQAICdcLHREAAwEIaAwAAAYAKABpDAAABgAgAGsMAAAHABQAagwAAAQAGgBsDAAABQAnAG0MAAADACMA6gwAAAgAGwBuDAAAAgAQAAAA.',
Dr='Dreamspun:BAECLgAFFH8SAAIUAAMJqx5KBwAUAQNoDAAABwBLAGkMAAADAEoA6gwAAAgAVQAUAAMJqx5KBwAUAQNoDAAABwBLAGkMAAADAEoA6gwAAAgAVQAuAAQKfzsAAhQACQkbI4IAAEIDABQACQkbI4IAAEIDAAAA.',
Du='Dubsii:BAECLgAFFH8YAAIZAAYJ5iCHDQAyAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAZAAYJ5iCHDQAyAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAuAAQKfxcAAxkACAmLIZwGAPMCABkACAmLIZwGAPMCABIAAQl/Jp9yAGsAAAEuAAUUCQlJAAoAvxoA.',
Eh='Ehanee:BAEALgAFFAIJAwAAAA==.',
Ei='Eibm:BAEALgAECgEJAQAAAA==.',
Er='Ereshin:BAEBLgAECn8bAAIFAAgJnB+UDQDqAghoDAAABgBjAGkMAAAEAGAAawwAAAQAWQBqDAAAAwBKAGwMAAACAE8AbQwAAAEAEgDqDAAABABdAG4MAAADAGAABQAICZwflA0A6gIIaAwAAAYAYwBpDAAABABgAGsMAAAEAFkAagwAAAMASgBsDAAAAgBPAG0MAAABABIA6gwAAAQAXQBuDAAAAwBgAAAA.',
Fa='Fappimeal:BAECLgAFFH8+AAMIAAkJChy0HwD1AQloDAAADgBiAGkMAAANAGEAawwAAAkAWgBqDAAABABVAGwMAAABAFEAbQwAAAEACQDqDAAADwBjAG4MAAAEADwAbwwAAAEAIwAIAAgJgx+0HwD1AQhoDAAABwBiAGkMAAAIAGEAawwAAAYAWgBqDAAAAgBVAGwMAAABAFEA6gwAAAYAYwBuDAAABAA8AG8MAAABACMAGgAGCVUa8QMAuAEGaAwAAAcAXQBpDAAABQBKAGsMAAADAD0AagwAAAIAJABtDAAAAQAJAOoMAAAJAGEALgAECn9BAAMIAAkJMCZ3AgC0AwAIAAkJMCZ3AgC0AwAaAAYJlh3dCwC6AQAAAA==.Fappisham:BAECLgAFFH8IAAIHAAUJ1xOpEwACAQVoDAAAAgBDAGkMAAACADgAawwAAAIAJwBqDAAAAQALAOoMAAABACcABwAFCdcTqRMAAgEFaAwAAAIAQwBpDAAAAgA4AGsMAAACACcAagwAAAEACwDqDAAAAQAnAC4ABAp/GQADBwAJCV0dIQwAogIABwAICSMhIQwAogIABgAJCS0HQhoAMQEAAS4ABRQJCT4ACAAKHAA=.',
Fe='Felshins:BAEALgADCgMJBgABLgAECggJGwAFAJwfAA==.',
Fl='Flufflez:BAECLgAFFH8mAAIZAAkJ8SClBwCRAgloDAAABwBgAGkMAAAGAFQAawwAAAcAXwBqDAAABABYAGwMAAADAFwAbQwAAAEASQDqDAAABgBhAG4MAAACAFQAbwwAAAIALwAZAAkJ8SClBwCRAgloDAAABwBgAGkMAAAGAFQAawwAAAcAXwBqDAAABABYAGwMAAADAFwAbQwAAAEASQDqDAAABgBhAG4MAAACAFQAbwwAAAIALwAuAAQKf0EAAhkACQkNJgoBAKIDABkACQkNJgoBAKIDAAAA.',
Fo='Fofer:BAECLgAFFH8FAAIVAAQJkx/vFQBzAQRoDAAAAQBWAGkMAAABADoAawwAAAEAWwDqDAAAAgBXABUABAmTH+8VAHMBBGgMAAABAFYAaQwAAAEAOgBrDAAAAQBbAOoMAAACAFcALgAECn8nAAIVAAcJASa+CQCWAgAVAAcJASa+CQCWAgABLgAFFAkJIgAbANsfAA==.Foil:BAEALgADCgkJGwABLgAECgkJkwAcAMglAA==.',
Fr='Froshin:BAEALgADCgUJCwABLgAECggJGwAFAJwfAA==.',
Fu='Funkey:BAECLgAFFH8UAAMRAAYJNRU/OQBAAQZoDAAABQBDAGkMAAAFAFoAawwAAAMAJABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgARAAYJ/A8/OQBAAQZoDAAAAwAhAGkMAAAEADgAawwAAAMAJABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgAdAAIJth6eAgCjAAJoDAAAAgBDAGkMAAABAFoALgAECn8nAAMdAAkJnyDEAQD8AgAdAAgJsyLEAQD8AgARAAYJfhaBVQCGAQAAAA==.',
Gr='Greatares:BAEBLgAFFH8JAAMeAAMJogtyKwC9AANoDAAAAwAZAGkMAAADABIA6gwAAAMALQAeAAMJdAtyKwC9AANoDAAAAwAZAGkMAAACABAA6gwAAAMALQAfAAEJGQegLQA3AAFpDAAAAQASAAAA.Greathades:BAEALgAECgkJAgABLgAFFAMJCQAeAKILAA==.Greatmonkey:BAEALgAFFAEJAQABLgAFFAMJCQAeAKILAA==.Greatodin:BAEALgAECgkJBAABLgAFFAMJCQAeAKILAA==.Greatosiris:BAEALgAECgkJAgABLgAFFAMJCQAeAKILAA==.Greatra:BAEALgADCgEJAQABLgAFFAMJCQAeAKILAA==.Grummel:BAECLgAFFH8NAAIXAAMJACIFJAAEAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgAXAAMJACIFJAAEAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgAuAAQKfycAAxcACQk8IH8JAPkCABcACQk8IH8JAPkCACAAAQlwFGwdAEAAAAAA.',
Ha='Halts:BAEALgAECgMJBQABLgAECggJGwAFAJwfAA==.',
Hb='Hbcarter:BAEBLgAFFH8HAAIcAAMJSxRIOQDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgAcAAMJSxRIOQDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgABLgAFFAkJSQAKAL8aAA==.',
Ia='Iambuns:BAEALgAECggJDAABLgAFFAkJPgAIAAocAA==.',
Il='Illiyania:BAEALgAECgEJAQAAAA==.Ilnarya:BAEALgAECgEJAQABLgAECgkJHgARALIRAA==.',
Im='Imei:BAEALgAECgEJAQABLgAFFAMJBAABAAAAAA==.Imquitelarge:BAEBLgAECn8VAAIeAAkJWhY6DwD6AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAeAAkJWhY6DwD6AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAAAA==.',
Iz='Izapotato:BAECLgAFFH8UAAIRAAYJjBgjCQCXAQZoDAAABABUAGkMAAAEACoAawwAAAQANABqDAAAAwBDAOoMAAAEAEQAbwwAAAEAQgARAAYJjBgjCQCXAQZoDAAABABUAGkMAAAEACoAawwAAAQANABqDAAAAwBDAOoMAAAEAEQAbwwAAAEAQgAuAAQKfyIAAhEABwmhJT0gAFMCABEABwmhJT0gAFMCAAEuAAUUCQkjAAoAyg0A.',
Ja='Jail:BAECLgAFFH8JAAMEAAgJfBHKEQD2AQhoDAAAAgBQAGkMAAABAE0AawwAAAEAEgBqDAAAAQAgAGwMAAABABsAbQwAAAEAIADqDAAAAQA5AG4MAAABABIABAAICRUQyhEA9gEIaAwAAAEANwBpDAAAAQBNAGsMAAABABIAagwAAAEAIABsDAAAAQAbAG0MAAABACAA6gwAAAEAOQBuDAAAAQASACEAAQlRHxYFAF8AAWgMAAABAFAALgAECn82AAMhAAkJ3CQuAABiAwAhAAkJoiQuAABiAwAEAAkJ8h4rBwAaAgAAAA==.',
Jk='Jkey:BAEBLgAFFH8GAAIYAAQJoBEfEAAgAQRoDAAAAgAmAGkMAAACABoAawwAAAEAJADqDAAAAQBPABgABAmgER8QACABBGgMAAACACYAaQwAAAIAGgBrDAAAAQAkAOoMAAABAE8AAS4ABRQGCRQAEQA1FQA=.',
Jl='Jlycett:BAECLgAFFH9GAAMFAAkJ5yF/AAA2AgloDAAADgBZAGkMAAAOAF8AawwAAAsAWwBqDAAACwBjAGwMAAACAEMAbQwAAAEALADqDAAADgBjAG4MAAABAGQAbwwAAAIAXgAFAAkJ5yF/AAA2AgloDAAADgBZAGkMAAANAF8AawwAAAsAWwBqDAAACwBjAGwMAAACAEMAbQwAAAEALADqDAAADABjAG4MAAABAGQAbwwAAAIAXgAHAAIJKCNvGQDOAAJpDAAAAQBUAOoMAAACAF8ALgAECn8zAAMFAAkJ0CWWAAC0AwAFAAkJ0CWWAAC0AwAHAAQJtSPlLgCFAQABLgAFFAkJSQAKAL8aAA==.',
Ka='Kanavi:BAEALgAECgMJBAABLgAFFAMJBAABAAAAAA==.Kantai:BAEALgAECgYJCwABLgAFFAMJBAABAAAAAA==.Katekicks:BAECLgAFFH8NAAISAAYJ7RzRCwBnAQZoDAAAAQBPAGkMAAABAE4AawwAAAEAOQBqDAAAAQAxAOoMAAAHAGEAbgwAAAIAOQASAAYJ7RzRCwBnAQZoDAAAAQBPAGkMAAABAE4AawwAAAEAOQBqDAAAAQAxAOoMAAAHAGEAbgwAAAIAOQAuAAQKfz0AAhIACQkmJWoBAGYDABIACQkmJWoBAGYDAAAA.Katemage:BAEALgADCggJCgABLgAFFAYJDQASAO0cAA==.Katestinks:BAECLgAFFH8XAAMIAAcJKRsDPACBAQdoDAAABABZAGkMAAAEAFkAawwAAAMALgBqDAAAAgARAGwMAAABAB0AbQwAAAMAQQDqDAAABgBhAAgABgkpGwM8AIEBBmgMAAAEAFkAaQwAAAQAWQBrDAAAAwAuAGwMAAABAB0AbQwAAAMAQQDqDAAABgBhABsAAQkAAB1jAAAAAWoMAAACABEALgAECn8sAAMIAAkJNySLBQBOAwAIAAkJNySLBQBOAwAbAAEJtgp7YAApAAABLgAFFAYJDQASAO0cAA==.',
Ke='Kelandrea:BAECLgAFFH8LAAIiAAMJQhL3SgB/AANoDAAABQAoAGkMAAACAD0A6gwAAAQAJgAiAAMJQhL3SgB/AANoDAAABQAoAGkMAAACAD0A6gwAAAQAJgAuAAQKfx8ABCIACQmrG9giAJ4CACIACQmrG9giAJ4CABYAAgnSEPeBAHAAACMAAgkzF+xKAD8AAAEuAAUUBAkLAAgAWw4A.',
Kh='Khega:BAEALgAFFAEJAQABLgAFFAQJDgAkAGIYAA==.',
Ki='Kitowatt:BAEALgAECgYJCgABLgAECgkJKQAlACsfAA==.',
Kr='Kregazi:BAECLgAFFH8ZAAIbAAUJ5RvqFQA8AQVoDAAACABEAGkMAAAHAEkAawwAAAMAXABqDAAAAQBSAOoMAAAGADIAGwAFCeUb6hUAPAEFaAwAAAgARABpDAAABwBJAGsMAAADAFwAagwAAAEAUgDqDAAABgAyAC4ABAp/OgACGwAJCRMjAQUA3QIAGwAJCRMjAQUA3QIAAAA=.',
Ky='Kyriste:BAEBLgAECn8aAAIPAAcJZiFPDwB0AgdoDAAABQBbAGkMAAAFAFoAawwAAAQAWABqDAAAAwBVAGwMAAADAEAA6gwAAAQAWwBuDAAAAgBXAA8ABwlmIU8PAHQCB2gMAAAFAFsAaQwAAAUAWgBrDAAABABYAGoMAAADAFUAbAwAAAMAQADqDAAABABbAG4MAAACAFcAAS4ABRQGCSUAFwBaHgA=.',
La='Larissaqt:BAECLgAFFH8tAAImAAkJnxJmBQApAgloDAAACABTAGkMAAAHAEoAawwAAAgAJQBqDAAABwAgAGwMAAADADEAbQwAAAEAFADqDAAACABQAG4MAAACAA8AbwwAAAEAEwAmAAkJnxJmBQApAgloDAAACABTAGkMAAAHAEoAawwAAAgAJQBqDAAABwAgAGwMAAADADEAbQwAAAEAFADqDAAACABQAG4MAAACAA8AbwwAAAEAEwAuAAQKfzIAAiYACQkOIyQDADEDACYACQkOIyQDADEDAAAA.',
Ma='Maildaddy:BAECLgAFFH8jAAMKAAkJyg07CgAHAgloDAAABgAwAGkMAAAGAEMAawwAAAYAMABqDAAABQBDAGwMAAABAAoAbQwAAAEACADqDAAACAAxAG4MAAABAAQAbwwAAAEADQAKAAkJyg07CgAHAgloDAAABgAwAGkMAAAGAEMAawwAAAYAMABqDAAABQBDAGwMAAABAAoAbQwAAAEACADqDAAABwAxAG4MAAABAAQAbwwAAAEADQACAAEJbBnSNABFAAHqDAAAAQBBAC4ABAp/JgAECgAICQkgCAoAQwIACgAICQkgCAoAQwIAAgAFCSgRKjcAGwEACwADCRwc3ycA4gAAAAA=.Maxxy:BAEBLgAECn8gAAIcAAkJtR2gFgCBAgloDAAABwBdAGkMAAAFAFwAawwAAAUAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAcAAkJtR2gFgCBAgloDAAABwBdAGkMAAAFAFwAawwAAAUAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAAAA==.',
Mc='Mckellen:BAECLgAFFH8RAAMPAAQJeBxcEQBEAQRoDAAABQBFAGkMAAAFAEkAawwAAAMAPADqDAAABABXAA8ABAl4HFwRAEQBBGgMAAAFAEUAaQwAAAQASQBrDAAAAwA8AOoMAAADAFcADgACCREJAhQAlgACaQwAAAEAGgDqDAAAAQAUAC4ABAp/HQADDgAICc4ZmQwAbgIADgAICc4ZmQwAbgIADwAECSYMg1wAwQAAAS4ABRQJCUkACgC/GgA=.',
Me='Medranden:BAEALgADCgcJBwABLgAECggJKQARANcLAA==.Merakkii:BAEBLgAECn8nAAIRAAcJ9h2cLgAMAgdoDAAABQBcAGkMAAAGAF0AawwAAAkAWQBqDAAACQBiAGwMAAAEAFoAbQwAAAEAAQDqDAAABQBdABEABwn2HZwuAAwCB2gMAAAFAFwAaQwAAAYAXQBrDAAACQBZAGoMAAAJAGIAbAwAAAQAWgBtDAAAAQABAOoMAAAFAF0AAAA=.Merarite:BAEBLgAECn8gAAIbAAkJvhduFQDBAQloDAAAAgBVAGkMAAACAEkAawwAAAIALQBqDAAAAgApAGwMAAAGAE8AbQwAAAYAOADqDAAAAgAvAG4MAAAFAC8AbwwAAAUAMgAbAAkJvhduFQDBAQloDAAAAgBVAGkMAAACAEkAawwAAAIALQBqDAAAAgApAGwMAAAGAE8AbQwAAAYAOADqDAAAAgAvAG4MAAAFAC8AbwwAAAUAMgABLgAECgkJNgAVADYQAA==.',
My='Myceliums:BAEALgAECgUJDgAAAA==.',
Na='Nadasa:BAECLgAFFH8lAAIiAAYJJBw2EQB0AQZoDAAACQBcAGkMAAAIAD4AawwAAAcAOgBqDAAAAwAxAGwMAAACAEEA6gwAAAgAUQAiAAYJJBw2EQB0AQZoDAAACQBcAGkMAAAIAD4AawwAAAcAOgBqDAAAAwAxAGwMAAACAEEA6gwAAAgAUQAuAAQKf2cAAiIACQnxImcKABQDACIACQnxImcKABQDAAAA.',
Nh='Nhi:BAEALgAFFAMJBAAAAA==.Nhylia:BAEBLgAFFH8FAAIiAAMJihSRYwDoAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQAiAAMJihSRYwDoAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQABLgAFFAQJCwAIAFsOAA==.',
Ni='Nixaanu:BAEALgAECgEJAQABLgAECggJFAAHAH8aAA==.Nixei:BAEBLgAECn8UAAIHAAgJfxpEGABTAghoDAAAAgAyAGkMAAACAEIAawwAAAIATwBqDAAAAgA3AGwMAAAEAFAAbQwAAAMARwDqDAAAAgA3AG4MAAADAEYABwAICX8aRBgAUwIIaAwAAAIAMgBpDAAAAgBCAGsMAAACAE8AagwAAAIANwBsDAAABABQAG0MAAADAEcA6gwAAAIANwBuDAAAAwBGAAAA.',
No='Nomadwarr:BAEALgADCgIJAwABLgAECggJKQAZACIXAA==.Nomisha:BAEALgAECgIJBAABLgAECgkJGAAFAKUeAA==.',
Ny='Nyriaa:BAECLgAFFH8KAAIPAAQJeRvCEgAzAQRoDAAAAwBOAGkMAAADAFEAawwAAAIAOgDqDAAAAgA+AA8ABAl5G8ISADMBBGgMAAADAE4AaQwAAAMAUQBrDAAAAgA6AOoMAAACAD4ALgAECn8eAAIPAAkJvSMABQAuAwAPAAkJvSMABQAuAwAAAA==.',
['Ní']='Nítedragon:BAEALgAECgEJAQABLgAFFAEJBQAKADQMAA==.',
Ow='Owlenjoyer:BAECLgAFFH8GAAIlAAMJRxUvMADCAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAlAAMJRxUvMADCAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAuAAQKfyQAAiUACQn2GowNAIECACUACQn2GowNAIECAAEuAAUUBgkNABIA7RwA.',
Pa='Palashin:BAEBLgAECn8dAAIWAAYJDB82BwBqAQZoDAAABwBgAGkMAAAGAFYAawwAAAYAWgBqDAAAAwBHAGwMAAABADAA6gwAAAYAUwAWAAYJDB82BwBqAQZoDAAABwBgAGkMAAAGAFYAawwAAAYAWgBqDAAAAwBHAGwMAAABADAA6gwAAAYAUwABLgAECggJGwAFAJwfAA==.',
Pe='Personnelkid:BAEALgAECgcJDQABLgAECgkJPAAPALUZAA==.',
Pl='Platedaddy:BAEALgAECgcJDwABLgAFFAkJIwAKAMoNAA==.',
Po='Potatogogue:BAECLgAFFH8WAAMHAAkJIRf5DgC8AQloDAAABABHAGkMAAACAEkAawwAAAEACQBqDAAAAQAlAGwMAAACAGAAbQwAAAEAJwDqDAAACABYAG4MAAABADQAbwwAAAIAKQAHAAgJDBX5DgC8AQhoDAAAAgBHAGkMAAABAEkAawwAAAEACQBqDAAAAQAlAG0MAAABACcA6gwAAAYAWABuDAAAAQA0AG8MAAABACkABQAFCeUYTxcAEQEFaAwAAAIANwBpDAAAAQBQAGwMAAACADIA6gwAAAIAUwBvDAAAAQAwAC4ABAp/KQADBwAJCR0kvQkAwgIABwAJCR0kvQkAwgIABQAHCZEcTzcA0wEAAS4ABRQJCSMACgDKDQA=.',
Pu='Punchweagle:BAEBLgAECn82AAMVAAkJNhDeIQCZAQloDAAACAAzAGkMAAAHAEAAawwAAAgAOgBqDAAABgAoAGwMAAAGADkAbQwAAAUAEQDqDAAABgAwAG4MAAAFAA0AbwwAAAMAEwAVAAkJ8Q7eIQCZAQloDAAABAAzAGkMAAAEADQAawwAAAQAMwBqDAAABAAZAGwMAAAEADkAbQwAAAUAEQDqDAAABAAqAG4MAAAFAA0AbwwAAAMAEwASAAYJUxRGMgBbAQZoDAAABAAyAGkMAAADAEAAawwAAAQAOgBqDAAAAgAoAGwMAAACACUA6gwAAAIAMAAAAA==.',
Qi='Qixis:BAECLgAFFH8aAAMTAAgJrhPdFgCxAQhoDAAABwBIAGkMAAAGAD8AawwAAAMAPQBqDAAAAgAWAGwMAAABABoAbQwAAAEALwDqDAAABQAmAG4MAAABACoAEwAICe8Q3RYAsQEIaAwAAAQAFgBpDAAAAwA/AGsMAAABAD0AagwAAAIAFgBsDAAAAQAaAG0MAAABAC8A6gwAAAQAJgBuDAAAAQAqACcABAmFDloXABcBBGgMAAADAEgAaQwAAAMAJQBrDAAAAgAjAOoMAAABAAMALgAECn8uAAMTAAkJOCO8DgDFAgATAAkJGSO8DgDFAgAnAAYJLB3aFgDrAQAAAA==.',
Ra='Raveglaive:BAEALgAECgUJAwAAAA==.',
Re='Redvine:BAEALgADCgUJBQABLgAFFAYJFAARADUVAA==.Rexpanda:BAEALgAECgQJBgABLgAECgUJBQABAAAAAA==.Rextank:BAEALgAECgEJAQABLgAECgUJBQABAAAAAA==.',
Ro='Roogies:BAECLgAFFH8lAAIXAAYJWh7oDADEAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAABABdAGwMAAABACgA6gwAAAgAXgAXAAYJWh7oDADEAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAABABdAGwMAAABACgA6gwAAAgAXgAuAAQKf2QAAxcACQnhJWsAAFEDABcACQnhJWsAAFEDACAABwn6IuUAAAcCAAAA.',
Ru='Rumpy:BAEALgAFFAIJBAABLgAFFAMJDQAXAAAiAA==.Runedaddy:BAEALgAECgEJAQABLgAFFAkJIwAKAMoNAA==.',
['Ræ']='Ræx:BAEALgAECgUJBQAAAA==.',
Se='Serenytey:BAEALgAECgcJDQAAAA==.',
Sh='Shiins:BAEALgAECgIJAwABLgAECggJGwAFAJwfAA==.Shinthyr:BAEBLgAECn8YAAIPAAcJ5R4eFQA0AgdoDAAABQBTAGkMAAAEAFUAawwAAAQAXQBqDAAAAwBHAGwMAAACAFUA6gwAAAQASwBuDAAAAgA6AA8ABwnlHh4VADQCB2gMAAAFAFMAaQwAAAQAVQBrDAAABABdAGoMAAADAEcAbAwAAAIAVQDqDAAABABLAG4MAAACADoAAS4ABAoICRsABQCcHwA=.',
Si='Sindalff:BAEALgAFFAQJBAAAAA==.Sizzlefox:BAEALgAECgMJAwABLgAECgkJGAAFAKUeAA==.',
Sk='Skilful:BAEBLgAFFH8FAAIeAAMJuwlUFQCkAANoDAAAAgALAGkMAAACAAkA6gwAAAEANgAeAAMJuwlUFQCkAANoDAAAAgALAGkMAAACAAkA6gwAAAEANgABLgAFFAMJEgAUAKseAA==.',
St='Stygianfox:BAEALgAECgIJBAABLgAECgkJGAAFAKUeAA==.',
Sy='Syldrasi:BAEBLgAECn8XAAInAAcJnxZBBABLAQdoDAAABAA9AGkMAAAEAD0AawwAAAQAQABqDAAAAwBPAGwMAAAEADgA6gwAAAMAOgBuDAAAAQAsACcABwmfFkEEAEsBB2gMAAAEAD0AaQwAAAQAPQBrDAAABABAAGoMAAADAE8AbAwAAAQAOADqDAAAAwA6AG4MAAABACwAAS4ABRQGCSUAFwBaHgA=.',
Ta='Tahune:BAEBLgAECn+TAAQcAAkJyCX3AADWAwloDAAAEwBdAGkMAAASAGIAawwAABIAYgBqDAAAEgBhAGwMAAARAGIAbQwAAA8AYQDqDAAAEgBhAG4MAAANAFoAbwwAAAsAYQAcAAkJyCX3AADWAwloDAAACgBdAGkMAAALAGIAawwAAAkAYgBqDAAACwBhAGwMAAAKAGIAbQwAAAgAYQDqDAAACwBhAG4MAAAHAFoAbwwAAAUAYQAQAAkJJCVRAABdAwloDAAABgBiAGkMAAAGAGIAawwAAAYAYgBqDAAABgBhAGwMAAAGAF8AbQwAAAYAXwDqDAAABgBhAG4MAAAFAFkAbwwAAAUAVwAlAAkJ1SBcAQDNAgloDAAAAwBaAGkMAAABAFkAawwAAAMAWgBqDAAAAQBUAGwMAAABAE4AbQwAAAEAVQDqDAAAAQBaAG4MAAABAEkAbwwAAAEASQAAAA==.Taso:BAEBLgAECn8dAAIVAAgJVhGvLgBKAQhoDAAABgA/AGkMAAAFAEMAawwAAAUASgBqDAAABQBPAGwMAAABAAAAbQwAAAEAAADqDAAABQBBAG4MAAABACYAFQAICVYRry4ASgEIaAwAAAYAPwBpDAAABQBDAGsMAAAFAEoAagwAAAUATwBsDAAAAQAAAG0MAAABAAAA6gwAAAUAQQBuDAAAAQAmAAEuAAUUBQkaABsA6CAA.',
Th='Thawd:BAECLgAFFH9BAAIVAAkJUh2nAwBwAgloDAAADABYAGkMAAAJAGIAawwAAAkAXABqDAAACABQAGwMAAAHADYAbQwAAAMAKADqDAAACgBYAG4MAAAEAEcAbwwAAAMAQgAVAAkJUh2nAwBwAgloDAAADABYAGkMAAAJAGIAawwAAAkAXABqDAAACABQAGwMAAAHADYAbQwAAAMAKADqDAAACgBYAG4MAAAEAEcAbwwAAAMAQgAuAAQKfy8AAxUACQmVITAHAMQCABUACQnOIDAHAMQCABIABgnCHR0WAAcCAAAA.Therapygap:BAEBLgAECn88AAQPAAkJtRmcDQCMAgloDAAACQBMAGkMAAAKADwAawwAAAYATABqDAAABwA7AGwMAAALAEoAbQwAAAQALwDqDAAACAA8AG4MAAADADkAbwwAAAIATQAPAAkJtRmcDQCMAgloDAAABgBMAGkMAAAGADwAawwAAAUATABqDAAABgA7AGwMAAAJAEoAbQwAAAQALwDqDAAABwA8AG4MAAACADkAbwwAAAIATQAmAAYJKwpTXgCeAAZoDAAAAwAnAGkMAAAEABUAawwAAAEAEgBqDAAAAQAHAGwMAAACACkA6gwAAAEACAAOAAEJfAPBiQAgAAFuDAAAAQAIAAAA.',
Tr='Triboon:BAEALgADCgMJAwABLgAFFAgJFwAZAKQaAA==.Trèantdaddy:BAEALgAFFAEJAgABLgAFFAkJIwAKAMoNAA==.',
Tw='Twomonk:BAEALgAFFAEJAQABLgAFFAIJBgASAL4hAA==.',
Un='Unsown:BAEALgAFFAEJAQABLgAFFAMJEgAUAKseAA==.',
Us='Usurah:BAECLgAFFH8fAAIiAAkJBBSWEADqAQloDAAABgBOAGkMAAAGAFYAawwAAAMAQQBqDAAAAwA8AGwMAAACABsAbQwAAAEACADqDAAABAA+AG4MAAADACoAbwwAAAMAJgAiAAkJBBSWEADqAQloDAAABgBOAGkMAAAGAFYAawwAAAMAQQBqDAAAAwA8AGwMAAACABsAbQwAAAEACADqDAAABAA+AG4MAAADACoAbwwAAAMAJgAuAAQKfysAAyIACQmAIsQJAEMDACIACQmAIsQJAEMDACMABQlYHBMcADYBAAAA.',
Vi='Vindh:BAECLgAFFH8SAAMRAAUJugf+WwDcAAVoDAAABgAXAGkMAAAEABUAawwAAAMACABqDAAAAQAJAOoMAAAEABgAEQAFCboH/lsA3AAFaAwAAAYAFwBpDAAABAAVAGsMAAADAAgAagwAAAEACQDqDAAAAwAYAB0AAQkOBpIUACkAAeoMAAABAA8ALgAECn8oAAQRAAkJtxVdPQD/AQARAAkJtxVdPQD/AQAdAAIJOgN5MQA9AAAkAAEJAACRiQAAAAAAAA==.',
Vy='Vyndraennis:BAEBLgAECn8eAAIRAAkJshGwRAC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQARAAkJshGwRAC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQAAAA==.',
['Vî']='Vîtâl:BAEALgADCgMJAwABLgAFFAUJGwAZABAeAA==.',
Wo='Woar:BAEALgAECgMJAwABLgAFFAgJCQAEAHwRAA==.',
Ya='Yaav:BAEBLgAECn8XAAIIAAkJxhAWWwC1AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAIAAkJxhAWWwC1AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAAAA==.',
Yo='Yomi:BAEALgAECgkJDgABLgAFFAMJBAABAAAAAA==.Yoonji:BAEALgAECgYJBwABLgAFFAMJBAABAAAAAA==.',
Yu='Yufia:BAEBLgAECn8ZAAIMAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAMAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAAAA==.',
Za='Zatum:BAEBLgAECn8pAAMlAAkJKx/qDgBvAgloDAAABgBTAGkMAAAGAFYAawwAAAUAUABqDAAABABLAGwMAAAGAFMAbQwAAAIASgDqDAAABgBUAG4MAAAEAEYAbwwAAAIASwAlAAkJKx/qDgBvAgloDAAABgBTAGkMAAAGAFYAawwAAAUAUABqDAAABABLAGwMAAAFAFMAbQwAAAEASgDqDAAABQBUAG4MAAAEAEYAbwwAAAEASwAcAAQJqguxnQB1AARsDAAAAQAiAG0MAAABAB0A6gwAAAEACQBvDAAAAQAtAAAA.',
Zo='Zomb:BAECLgAFFH8aAAIbAAUJ6CCWEgBjAQVoDAAACABbAGkMAAAHAEQAawwAAAQAXQBqDAAAAgBMAOoMAAAFAFQAGwAFCegglhIAYwEFaAwAAAgAWwBpDAAABwBEAGsMAAAEAF0AagwAAAIATADqDAAABQBUAC4ABAp/JQACGwAICY4haQQABQMAGwAICY4haQQABQMAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
