local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Monk-Windwalker','Shaman-Enhancement','Monk-Mistweaver','Paladin-Retribution','Paladin-Holy','Mage-Frost','Priest-Holy','Unknown-Unknown','Rogue-Subtlety','Rogue-Assassination','Priest-Shadow','Warrior-Arms','Evoker-Augmentation','Priest-Discipline','Warrior-Fury','DeathKnight-Unholy','Hunter-Survival','Evoker-Preservation','Mage-Arcane','Paladin-Protection','Druid-Balance','Druid-Restoration','Druid-Feral','Rogue-Outlaw','Evoker-Devastation','Monk-Brewmaster','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Restoration','Shaman-Elemental','Warlock-Demonology','Druid-Guardian','Warlock-Destruction','DemonHunter-Havoc','DeathKnight-Frost','DeathKnight-Blood','Warrior-Protection','DemonHunter-Devourer',}
local provider = {region='US',realm='Dalaran',name='US',type='subscribers',zone=46,date='2026-07-20',data={Ad='Adansso:BAEBLgAECn81AAIBAAkJFxKKHgC5AQloDAAACQArAGkMAAAIADoAawwAAAcAQwBqDAAABQA0AGwMAAAGADEAbQwAAAMAHADqDAAACQA7AG4MAAAFACUAbwwAAAEAGgABAAkJFxKKHgC5AQloDAAACQArAGkMAAAIADoAawwAAAcAQwBqDAAABQA0AGwMAAAGADEAbQwAAAMAHADqDAAACQA7AG4MAAAFACUAbwwAAAEAGgAAAA==.',
Al='Aliastei:BAEALgADCggJEgABLgAECgkJPwACAJMbAA==.',
Ap='Apawcowlypse:BAEALgADCgcJDAABLgAFFAYJGQADADQRAA==.',
As='Ashko:BAEBLgAECn8zAAMEAAgJbBy/OwAVAghoDAAACgBLAGkMAAAJAFcAawwAAAgAUQBqDAAABwBSAGwMAAAFAFEAbQwAAAMAKwDqDAAABwBgAG4MAAACACkABAAICWwcvzsAFQIIaAwAAAkASwBpDAAACABXAGsMAAAGAFEAagwAAAYAUgBsDAAABQBRAG0MAAADACsA6gwAAAYAYABuDAAAAgApAAUABQlwD7xMAAgBBWgMAAABACYAaQwAAAEAHQBrDAAAAgBPAGoMAAABABcA6gwAAAEAGwAAAA==.Astralore:BAEALgAECgMJAwABLgAECgkJUwAEAF8eAA==.',
Ay='Ayodele:BAEBLgAECn84AAIGAAkJtBuCHgCmAgloDAAACQBSAGkMAAAHAEcAawwAAAUAQwBqDAAACABWAGwMAAAGAEkAbQwAAAQAPwDqDAAACABTAG4MAAAGAFYAbwwAAAMAJwAGAAkJtBuCHgCmAgloDAAACQBSAGkMAAAHAEcAawwAAAUAQwBqDAAACABWAGwMAAAGAEkAbQwAAAQAPwDqDAAACABTAG4MAAAGAFYAbwwAAAMAJwAAAA==.',
Az='Azurlia:BAEALgAFFAEJAQAAAA==.',
Ba='Babycora:BAEALgAFFAMJAwABLgAFFAQJEQAHACwhAA==.Bagelandlox:BAEALgADCgEJAQABLgAECgYJDAAIAAAAAA==.Barrui:BAECLgAFFH9NAAMJAAkJPCPpAQC1AgloDAAADABfAGkMAAANAGIAawwAAAwAXABqDAAADABgAGwMAAACAFkAbQwAAAQASQDqDAAACgBdAG4MAAAGAGEAbwwAAAYATwAJAAkJOSPpAQC1AgloDAAACwBfAGkMAAALAGIAawwAAAoAXABqDAAACwBgAGwMAAABAFkAbQwAAAQASQDqDAAACgBdAG4MAAAGAGEAbwwAAAYATwAKAAUJghpmAQA1AQVoDAAAAQBfAGkMAAACAGAAawwAAAIASgBqDAAAAQAeAGwMAAABAAQALgAECn85AAMJAAkJcCTpBQAzAwAJAAkJ8SLpBQAzAwAKAAYJHyEvBABwAgAAAA==.',
Be='Belynila:BAECLgAFFH8dAAILAAUJwx0JCQA/AQVoDAAACgBVAGkMAAAIAD4AawwAAAQAOQBqDAAAAQBJAOoMAAAGAGMACwAFCcMdCQkAPwEFaAwAAAoAVQBpDAAACAA+AGsMAAAEADkAagwAAAEASQDqDAAABgBjAC4ABAp/QAACCwAJCaAhOgUAAgMACwAJCaAhOgUAAgMAAAA=.Bestiavera:BAECLgAFFH8HAAIMAAMJSASpFQB5AANoDAAABAAMAGkMAAACAA8AbwwAAAEABQAMAAMJSASpFQB5AANoDAAABAAMAGkMAAACAA8AbwwAAAEABQAuAAQKf0wAAgwACQnjFwoCAJMBAAwACQnjFwoCAJMBAAAA.',
Br='Briggoker:BAEBLgAECn8WAAINAAkJxRdxAQArAgloDAAABAA6AGkMAAAEAEgAawwAAAMALABqDAAAAgA8AGwMAAACADwAbQwAAAEAPQDqDAAABABJAG4MAAABAEYAbwwAAAEALgANAAkJxRdxAQArAgloDAAABAA6AGkMAAAEAEgAawwAAAMALABqDAAAAgA8AGwMAAACADwAbQwAAAEAPQDqDAAABABJAG4MAAABAEYAbwwAAAEALgAAAA==.Brigmahf:BAEALgAECgQJCQABLgAECgkJFgANAMUXAA==.',
Bu='Bubblindora:BAECLgAFFH8xAAIOAAkJohhiAQAwAgloDAAACQBaAGkMAAAHAFoAawwAAAcASABqDAAABgBQAGwMAAAEACYAbQwAAAIAIwDqDAAACABWAG4MAAADABgAbwwAAAMAMAAOAAkJohhiAQAwAgloDAAACQBaAGkMAAAHAFoAawwAAAcASABqDAAABgBQAGwMAAAEACYAbQwAAAIAIwDqDAAACABWAG4MAAADABgAbwwAAAMAMAAuAAQKfysAAg4ACQkoJZ0AALYDAA4ACQkoJZ0AALYDAAAA.',
Ca='Carbonarra:BAEBLgAECn9XAAIPAAkJjByhAQB7AgloDAAADgBbAGkMAAANAFAAawwAAA0AUgBqDAAACgBYAGwMAAAKAEgAbQwAAAUALADqDAAACgBRAG4MAAAHAEMAbwwAAAUAPwAPAAkJjByhAQB7AgloDAAADgBbAGkMAAANAFAAawwAAA0AUgBqDAAACgBYAGwMAAAKAEgAbQwAAAUALADqDAAACgBRAG4MAAAHAEMAbwwAAAUAPwAAAA==.',
Ch='Chetegos:BAEALgADCgYJBgABLgAFFAMJCQAPABUjAA==.Chíefsquirel:BAEALgAECgYJDAAAAA==.',
Da='Dadbanger:BAECLgAFFH8wAAMBAAkJhyM4AABxAgloDAAABgBiAGkMAAAGAGAAawwAAAUASgBqDAAACABfAGwMAAAGAGMAbQwAAAIASQDqDAAABwBhAG4MAAAEAF0AbwwAAAQAXgABAAkJhyM4AABxAgloDAAABgBiAGkMAAAGAGAAawwAAAUASgBqDAAACABfAGwMAAABAGMAbQwAAAIASQDqDAAABwBhAG4MAAAEAF0AbwwAAAQAXgADAAEJIApqXwBCAAFsDAAABQAZAC4ABAp/KgACAQAICXEmCQIAhAMAAQAICXEmCQIAhAMAAAA=.Daeke:BAEALgADCgUJBQABLgAECgQJBwAIAAAAAA==.Daekeypoo:BAEALgAECgQJBwAAAA==.Darkvirgo:BAEBLgAFFH8YAAIGAAUJbwtraAATAQVoDAAABwAuAGkMAAAHAB4AawwAAAMADwBqDAAAAQARAOoMAAAGABgABgAFCW8La2gAEwEFaAwAAAcALgBpDAAABwAeAGsMAAADAA8AagwAAAEAEQDqDAAABgAYAAEuAAUUCAkpAAsA1xoA.',
De='Deathbeaver:BAEALgAECgYJCwABLgAECgkJUwAEAF8eAA==.Destrom:BAEBLgAECn8UAAIQAAkJuBHYggBeAQloDAAAAwAwAGkMAAADADAAawwAAAMASABqDAAAAgA2AGwMAAABAB4AbQwAAAEAKADqDAAAAwAXAG4MAAACAC0AbwwAAAIANQAQAAkJuBHYggBeAQloDAAAAwAwAGkMAAADADAAawwAAAMASABqDAAAAgA2AGwMAAABAB4AbQwAAAEAKADqDAAAAwAXAG4MAAACAC0AbwwAAAIANQAAAA==.',
Di='Diozi:BAEALgADCgkJCQABLgAECggJLAARAJUlAA==.',
Ep='Epilepticc:BAECLgAFFH8PAAIEAAQJSB7COAA7AQRoDAAABQBCAGkMAAAEAFUAawwAAAMAUADqDAAAAwBNAAQABAlIHsI4ADsBBGgMAAAFAEIAaQwAAAQAVQBrDAAAAwBQAOoMAAADAE0ALgAECn88AAIEAAkJ6yL5GQCoAgAEAAkJ6yL5GQCoAgAAAA==.',
Er='Eronor:BAEALgAECgIJAgABLgAECgkJIwASAN8RAA==.',
Et='Ethalon:BAECLgAFFH8TAAMFAAQJ1Bl5GgBNAQRoDAAABgBOAGkMAAAFAFoAawwAAAMAEwDqDAAABQBMAAUABAnUGXkaAE0BBGgMAAAFAE4AaQwAAAUAWgBrDAAAAwATAOoMAAAFAEwABAABCbcC38cAOQABaAwAAAEABgAuAAQKfycAAwUACQmuGycYAFECAAUACQmuGycYAFECAAQAAgnJFG9OADcAAAAA.',
Ga='Garlooth:BAECLgAFFH8RAAITAAQJ7BYcAQAbAQRoDAAABwAzAGkMAAAFAE4AawwAAAEAMgDqDAAABAA2ABMABAnsFhwBABsBBGgMAAAHADMAaQwAAAUATgBrDAAAAQAyAOoMAAAEADYALgAECn82AAITAAkJFSUvAABiAwATAAkJFSUvAABiAwAAAA==.',
Gl='Glizzygary:BAEALgAFFAUJEgAAAQ==.',
Gr='Grimvalor:BAEBLgAECn9TAAMEAAkJXx7sHACYAgloDAAACwBcAGkMAAAKAEwAawwAAAsAUgBqDAAACQBYAGwMAAAKAFkAbQwAAAcASwDqDAAADABSAG4MAAAIAD0AbwwAAAUAPQAEAAkJXx7sHACYAgloDAAACgBcAGkMAAAKAEwAawwAAAoAUgBqDAAACABYAGwMAAAJAFkAbQwAAAcASwDqDAAACwBSAG4MAAAIAD0AbwwAAAUAPQAUAAUJzwpaQABdAAVoDAAAAQAPAGsMAAABACwAagwAAAEALABsDAAAAQAiAOoMAAABAA8AAAA=.Grunclaws:BAEBLgAECn8VAAQVAAcJIREHQwABAQdoDAAABQAzAGkMAAAFACsAawwAAAQALwBqDAAAAgAfAGwMAAACAEAAbQwAAAEAEwDqDAAAAgAkABUABgl/DwdDAAEBBmgMAAABADMAaQwAAAIAKwBrDAAAAgAvAGoMAAABAB8AbQwAAAEAEwDqDAAAAQAkABYABgkfFWEJAPQABmgMAAAEAE8AaQwAAAMASwBrDAAAAgBEAGoMAAABACEAbAwAAAEACQDqDAAAAQA6ABcAAQlIGblHAEsAAWwMAAABAEAAAS4ABAoJCTMABABsHAA=.Grunjitsu:BAEBLgAECn8WAAMBAAcJVhq2GwDSAQdoDAAABQBHAGkMAAAFAFoAawwAAAQASwBqDAAAAQAdAOoMAAAFAD4AbgwAAAEAJwBvDAAAAQBBAAEABglWGrYbANIBBmgMAAADAEcAaQwAAAMAWgBrDAAAAQBLAOoMAAACAD4AbgwAAAEAJwBvDAAAAQBBAAMABQlyFogOABEBBWgMAAACAEIAaQwAAAIAOwBrDAAAAwAxAGoMAAABAB8A6gwAAAMAUAABLgAECgkJMwAEAGwcAA==.Grunjo:BAEALgAECgkJDQABLgAECgkJMwAEAGwcAA==.Grunsy:BAEALgAECgcJBgABLgAECgkJMwAEAGwcAA==.',
Ha='Haf:BAEBLgAECn8qAAIUAAkJ8hELFQCAAQloDAAABwA9AGkMAAAGAEIAawwAAAYARwBqDAAABQAjAGwMAAAFADYAbQwAAAMAFQDqDAAABgAvAG4MAAACABYAbwwAAAIAFwAUAAkJ8hELFQCAAQloDAAABwA9AGkMAAAGAEIAawwAAAYARwBqDAAABQAjAGwMAAAFADYAbQwAAAMAFQDqDAAABgAvAG4MAAACABYAbwwAAAIAFwAAAA==.',
He='Hertzmuch:BAEALgADCgYJDgABLgAFFAYJGQADADQRAA==.',
Ho='Holeighfuk:BAEALgAECgYJBgAAAA==.',
Ju='Jupiterboiz:BAECLgAFFH8MAAIYAAYJpxMMAAAqAgZoDAAAAwBgAGkMAAADAEUAawwAAAIANgBqDAAAAQALAGwMAAABAAAA6gwAAAIAHgAYAAYJpxMMAAAqAgZoDAAAAwBgAGkMAAADAEUAawwAAAIANgBqDAAAAQALAGwMAAABAAAA6gwAAAIAHgAuAAQKfyoAAhgACQmQIWAAAGcDABgACQmQIWAAAGcDAAEuAAUUBwkQABMAth4A.',
Ka='Kautheros:BAEBLgAECn8jAAQSAAkJ3xEhAwAhAQloDAAABQBIAGkMAAAFAD4AawwAAAUARwBqDAAABAAfAGwMAAADACIAbQwAAAMACQDqDAAABwBDAG4MAAACAB0AbwwAAAEAHwASAAkJ3xEhAwAhAQloDAAAAwBIAGkMAAADAD4AawwAAAMARwBqDAAAAgAfAGwMAAABACIAbQwAAAMACQDqDAAABQBDAG4MAAACAB0AbwwAAAEAHwANAAYJ1wlQXADFAAZoDAAAAQAdAGkMAAABABgAawwAAAIAHABqDAAAAQAkAGwMAAACABcA6gwAAAIAEgAZAAMJmgaqIABOAANoDAAAAQAJAGkMAAABABgAagwAAAEAGgAAAA==.',
Kr='Kroxychi:BAEALgAECgcJDgAAAA==.Kroxypurple:BAEALgADCgIJAgABLgAECgcJDgAIAAAAAA==.',
Ku='Kungfused:BAECLgAFFH8ZAAIDAAYJNBE4IgBcAQZoDAAABgAqAGkMAAAGADoAawwAAAQALwBqDAAAAQAaAGwMAAABABYA6gwAAAcAQgADAAYJNBE4IgBcAQZoDAAABgAqAGkMAAAGADoAawwAAAQALwBqDAAAAQAaAGwMAAABABYA6gwAAAcAQgAuAAQKf3QABAMACQkWHsAKAKUCAAMACQkWHsAKAKUCAAEACQmYFBIYAPMBABoABAn/CHBaAKEAAAAA.',
Le='Lennather:BAEBLgAECn9LAAIBAAkJtCVvAQBkAwloDAAACQBjAGkMAAAJAGEAawwAAAgAYABqDAAACABOAGwMAAAKAGEAbQwAAAkAXgDqDAAACwBfAG4MAAAJAGMAbwwAAAIAWgABAAkJtCVvAQBkAwloDAAACQBjAGkMAAAJAGEAawwAAAgAYABqDAAACABOAGwMAAAKAGEAbQwAAAkAXgDqDAAACwBfAG4MAAAJAGMAbwwAAAIAWgAAAA==.',
Li='Lidomi:BAEALgAECgUJDAABLgAFFAQJCwASAP8PAA==.Lidrunka:BAECLgAFFH8IAAMaAAIJNRehQwCVAAJoDAAAAwAwAOoMAAAFAEUAGgACCTUXoUMAlQACaAwAAAIAMADqDAAABQBFAAEAAQkMAp4UAD0AAWgMAAABAAUALgAECn8YAAMBAAgJdBXVGwD9AQABAAgJ0BTVGwD9AQAaAAQJFhTISgDSAAABLgAFFAQJCwASAP8PAA==.Linnadis:BAEALgADCgcJDwABLgAECgkJPwACAJMbAA==.',
['Lé']='Lépewpew:BAEBLgAECn8ZAAIRAAcJSRI/KABdAQdoDAAABgA+AGkMAAAFADMAawwAAAUAOwBqDAAAAwBNAGwMAAABACYA6gwAAAQAOgBuDAAAAQAKABEABwlJEj8oAF0BB2gMAAAGAD4AaQwAAAUAMwBrDAAABQA7AGoMAAADAE0AbAwAAAEAJgDqDAAABAA6AG4MAAABAAoAAAA=.',
Ma='Mattimus:BAEBLgAECn84AAMbAAkJug6eDQBeAQloDAAACgA9AGkMAAAIACgAawwAAAkAGgBqDAAABwA8AGwMAAAGACYAbQwAAAIAIgDqDAAABwApAG4MAAAEAB8AbwwAAAMAGwAbAAkJug6eDQBeAQloDAAACgA9AGkMAAAHACgAawwAAAgAGgBqDAAABgA8AGwMAAAGACYAbQwAAAIAIgDqDAAABgApAG4MAAAEAB8AbwwAAAMAGwAcAAQJ+QK2cAB8AARpDAAAAQABAGsMAAABAAkAagwAAAEACQDqDAAAAQAMAAAA.',
['Má']='Mákí:BAEBLgAECn8kAAQBAAkJThUJIwCZAQloDAAABQBIAGkMAAAEADQAawwAAAUALwBqDAAABABIAGwMAAADAEEAbQwAAAEAFgDqDAAABwBQAG4MAAAFADUAbwwAAAIAKgABAAgJHRcJIwCZAQhoDAAABABIAGkMAAADADQAawwAAAQALwBqDAAAAgBIAGwMAAADAEEA6gwAAAQAUABuDAAABQA1AG8MAAACACoAGgAFCYIWGTwACwEFaAwAAAEAQABpDAAAAQAyAGsMAAABACUAagwAAAEAPQDqDAAAAgBOAAMAAwn4DiWGAJEAA2oMAAABACsAbQwAAAEAHQDqDAAAAQApAAAA.',
Na='Natebanger:BAEALgAECgYJDAABLgAFFAkJMAABAIcjAA==.',
No='Noeyednuck:BAEALgAECgcJEQABLgAFFAMJDwAbAKsSAA==.',
Nu='Nuckshott:BAECLgAFFH8PAAIbAAMJqxLLXgDnAANoDAAABgA2AGkMAAAEAB0A6gwAAAUAOwAbAAMJqxLLXgDnAANoDAAABgA2AGkMAAAEAB0A6gwAAAUAOwAuAAQKfzUAAhsACQnWHwIaAIkCABsACQnWHwIaAIkCAAAA.',
Og='Ogx:BAEBLgAECn8dAAQdAAYJ1h5zVwBZAQZoDAAACABhAGkMAAAHAE0AawwAAAYATgBqDAAAAgBGAGwMAAABAE0A6gwAAAUASAAdAAQJzh9zVwBZAQRoDAAABABhAGkMAAADAE0AawwAAAIATgDqDAAAAgBIAB4ABQluF44KAOgABWgMAAABACMAaQwAAAIAUQBrDAAAAgA6AGoMAAACADkA6gwAAAEAQAACAAUJIBgWBwC6AAVoDAAAAwBQAGkMAAACADUAawwAAAIAMgBsDAAAAQBUAOoMAAACACcAAS4ABAoJCTMABABsHAA=.',
Ol='Olgass:BAEALgADCgIJAgABLgAECgkJNAAfAGUjAA==.',
Pu='Purlok:BAEALgAECgkJAwABLgAECgkJMwAEAGwcAA==.',
Qu='Quindrox:BAEBLgAECn8aAAINAAkJRSGiBQAFAwloDAAAAgBdAGkMAAACAFMAawwAAAMAVgBqDAAAAwBTAGwMAAADAFoAbQwAAAMATADqDAAABABQAG4MAAADAFoAbwwAAAMATwANAAkJRSGiBQAFAwloDAAAAgBdAGkMAAACAFMAawwAAAMAVgBqDAAAAwBTAGwMAAADAFoAbQwAAAMATADqDAAABABQAG4MAAADAFoAbwwAAAMATwABLgAFFAMJCAAgAIMZAA==.Quinet:BAEBLgAECn80AAMfAAkJZSP6CwDuAgloDAAABwBhAGkMAAAHAFwAawwAAAcAXABqDAAABwBRAGwMAAAGAFwAbQwAAAQAWADqDAAABwBeAG4MAAAFAEcAbwwAAAIAYAAfAAkJZSP6CwDuAgloDAAABwBhAGkMAAAGAFwAawwAAAcAXABqDAAAAQAQAGwMAAAEAFwAbQwAAAQAWADqDAAABwBeAG4MAAAFAEcAbwwAAAIAYAAhAAMJyh5xLwD9AANpDAAAAQBGAGoMAAAGAFEAbAwAAAIAVwAAAA==.Quinman:BAEBLgAECn8aAAQRAAkJRRoQFAAFAgloDAAABQBBAGkMAAAEADMAawwAAAQATwBqDAAAAgAnAGwMAAACAGEAbQwAAAIAOwDqDAAABABBAG4MAAACAD0AbwwAAAEAOgARAAkJixcQFAAFAgloDAAAAQA8AGkMAAABAAAAawwAAAEATwBqDAAAAgAnAGwMAAACAGEAbQwAAAIAOwDqDAAAAwBBAG4MAAACAD0AbwwAAAEAOgAcAAQJWhWQWQDfAARoDAAAAwBBAGkMAAADADMAawwAAAMAMQDqDAAAAQA0ABsAAQkVGNgnAToAAWgMAAABAD0AAS4ABRQDCQgAIACDGQA=.Quinmanbear:BAEBLgAFFH8IAAMgAAMJgxndFQDTAANoDAAAAgA8AGkMAAACAEIA6gwAAAQARAAgAAMJgxndFQDTAANoDAAAAgA8AGkMAAACAEIA6gwAAAMARAAXAAEJeguOIAA4AAHqDAAAAQAdAAAA.Quinroxx:BAEBLgAECn8gAAIGAAgJXiN8KwDFAghoDAAABQBiAGkMAAAFAFsAawwAAAUAXwBqDAAABQBeAGwMAAADAFoAbQwAAAIAUwDqDAAABgBhAG4MAAABAE0ABgAICV4jfCsAxQIIaAwAAAUAYgBpDAAABQBbAGsMAAAFAF8AagwAAAUAXgBsDAAAAwBaAG0MAAACAFMA6gwAAAYAYQBuDAAAAQBNAAEuAAUUAwkIACAAgxkA.Quinvinvin:BAEALgAECgcJDQABLgAFFAMJCAAgAIMZAA==.',
Ra='Ragsnak:BAEALgAECgkJEwABLgAECgkJMwAEAGwcAA==.',
Ro='Ronimus:BAEALgAECgEJAQAAAA==.',
Ru='Rufio:BAECLgAFFH8NAAIiAAMJJQzpHAC7AANoDAAABgA2AGkMAAAEABMA6gwAAAMAEwAiAAMJJQzpHAC7AANoDAAABgA2AGkMAAAEABMA6gwAAAMAEwAuAAQKf0cAAiIACQm4IQEBAPYCACIACQm4IQEBAPYCAAAA.',
Ry='Rytiou:BAECLgAFFH8cAAINAAkJuhdXBQCuAQloDAAABABSAGkMAAAFAFYAawwAAAQALgBqDAAABABJAGwMAAABADUAbQwAAAEAOADqDAAABwBSAG4MAAABABcAbwwAAAEANgANAAkJuhdXBQCuAQloDAAABABSAGkMAAAFAFYAawwAAAQALgBqDAAABABJAGwMAAABADUAbQwAAAEAOADqDAAABwBSAG4MAAABABcAbwwAAAEANgAuAAQKfzIAAg0ACQnqJFkCAIwDAA0ACQnqJFkCAIwDAAAA.',
Sa='Saadxevok:BAEBLgAECn8YAAMZAAgJQRFLEADYAQhoDAAAAwA7AGkMAAADADEAawwAAAMARQBqDAAAAwAwAGwMAAAEAEgAbQwAAAMACADqDAAAAwAkAG4MAAACAAwAGQAICUERSxAA2AEIaAwAAAMAOwBpDAAAAwAxAGsMAAACAEUAagwAAAIAMABsDAAAAwBIAG0MAAABAAgA6gwAAAEAJABuDAAAAQAMABIABglTCD0pACkBBmsMAAABABAAagwAAAEAEQBsDAAAAQARAG0MAAACAB4A6gwAAAIAJwBuDAAAAQAGAAEuAAUUCAkjAAsAZB4A.Saadxm:BAEALgAECgcJDwABLgAFFAgJIwALAGQeAA==.Saadxp:BAECLgAFFH8jAAMLAAgJZB7JAABZAghoDAAABQBjAGkMAAAGAGAAawwAAAYAYABqDAAABgBYAGwMAAADACAAbQwAAAEAVADqDAAABwBeAG4MAAABACkACwAHCV0hyQAAWQIHaAwAAAQAYwBpDAAABQBgAGsMAAAFAGAAagwAAAUAWABtDAAAAQBUAOoMAAAFAF4AbgwAAAEAKQAOAAYJ5RnxAQANAgZoDAAAAQBJAGkMAAABAB0AawwAAAEAWgBqDAAAAQBOAGwMAAADADMA6gwAAAIASgAuAAQKfyUAAwsACAmRJrcDAGADAAsACAmRJrcDAGADAA4ABQkLHz4gAJEBAAAA.',
Se='Sendrys:BAEALgAECgEJAQABLgAECgkJPwACAJMbAA==.',
Sg='Sgtgigachad:BAEALgAECgUJBQABLgAFFAUJEgAIAAAAAQ==.',
Sp='Spilt:BAECLgAFFH86AAIGAAkJ+BivAQCMAgloDAAACQBaAGkMAAAJAFQAawwAAAcAPwBqDAAABwA0AGwMAAAFAEIAbQwAAAQARgDqDAAACgBTAG4MAAAEACgAbwwAAAMACwAGAAkJ+BivAQCMAgloDAAACQBaAGkMAAAJAFQAawwAAAcAPwBqDAAABwA0AGwMAAAFAEIAbQwAAAQARgDqDAAACgBTAG4MAAAEACgAbwwAAAMACwAuAAQKfx8AAgYACQnJJOMKAG0DAAYACQnJJOMKAG0DAAAA.Spilthen:BAEBLgAFFH8cAAIeAAkJuRWxBQAGAgloDAAABABPAGkMAAAEAEQAawwAAAMAJwBqDAAAAgBIAGwMAAAEAFoAbQwAAAEACADqDAAABABLAG4MAAAEAEYAbwwAAAIADAAeAAkJuRWxBQAGAgloDAAABABPAGkMAAAEAEQAawwAAAMAJwBqDAAAAgBIAGwMAAAEAFoAbQwAAAEACADqDAAABABLAG4MAAAEAEYAbwwAAAIADAABLgAFFAkJOgAGAPgYAA==.Spiltmonk:BAEBLgAECn8YAAIBAAYJWh80HAD6AQZoDAAABABGAGkMAAAEAFEAawwAAAQAUgBqDAAABABMAGwMAAADAFIA6gwAAAUAVAABAAYJWh80HAD6AQZoDAAABABGAGkMAAAEAFEAawwAAAQAUgBqDAAABABMAGwMAAADAFIA6gwAAAUAVAABLgAFFAkJOgAGAPgYAA==.Spiltsham:BAEBLgAFFH8GAAMCAAYJYwbTCQChAAZoDAAAAQAEAGkMAAABAAUAawwAAAEABwDqDAAAAQAEAG4MAAABAD8AbwwAAAEADAACAAQJMgLTCQChAARoDAAAAQAEAGkMAAABAAUAawwAAAEABwDqDAAAAQAEAB4AAgnFDqYdAJoAAm4MAAABAD8AbwwAAAEADAABLgAFFAkJOgAGAPgYAA==.',
Ta='Takalune:BAEBLgAECn8dAAMBAAkJsyC8AADkAgloDAAABABfAGkMAAAEAE8AawwAAAQAUwBqDAAAAwBWAGwMAAADAF8AbQwAAAIAUwDqDAAABQBdAG4MAAADADUAbwwAAAEAVQABAAkJqSC8AADkAgloDAAAAwBfAGkMAAADAE8AawwAAAMAUwBqDAAAAwBWAGwMAAADAF8AbQwAAAIAUwDqDAAABABdAG4MAAACADQAbwwAAAEAVQAaAAUJQxrDJQCAAQVoDAAAAQBNAGkMAAABAEQAawwAAAEARgDqDAAAAQBCAG4MAAABADUAAS4ABAoJCSMAEgDfEQA=.Taku:BAEBLgAECn8WAAMjAAcJ9Bm2AgBfAQdoDAAAAwA7AGkMAAADAD8AawwAAAMAQgBqDAAAAwA+AGwMAAADAEUAbQwAAAMAPADqDAAABABPACMABgm0GLYCAF8BBmgMAAACADsAaQwAAAIAPwBrDAAAAgA/AGoMAAACADUAbAwAAAIARQBtDAAAAgA8ACQABwnDE7EoAA8BB2gMAAABADEAaQwAAAEAFwBrDAAAAQBCAGoMAAABAD4AbAwAAAEANABtDAAAAQAfAOoMAAAEAE8AAS4ABAoJCSMAEgDfEQA=.Talakua:BAEALgAECgcJBwABLgAECgkJIwASAN8RAA==.Taymeean:BAEALgAECgMJBAABLgAFFAQJCAANAB4MAA==.Tayvok:BAECLgAFFH8IAAINAAQJHgyzOwDYAARoDAAAAwAsAGkMAAADADAAawwAAAEAFgDqDAAAAQAJAA0ABAkeDLM7ANgABGgMAAADACwAaQwAAAMAMABrDAAAAQAWAOoMAAABAAkALgAECn8xAAMNAAkJkRyjDwBtAgANAAkJkRyjDwBtAgASAAIJ7AYzCgBBAAAAAA==.',
Te='Tentickles:BAECLgAFFH8SAAILAAUJlx90CgAlAQVoDAAABABIAGkMAAAEAFsAawwAAAMAYQBqDAAAAQAjAOoMAAAGAD0ACwAFCZcfdAoAJQEFaAwAAAQASABpDAAABABbAGsMAAADAGEAagwAAAEAIwDqDAAABgA9AC4ABAp/FAACCwAICYgicggA/QIACwAICYgicggA/QIAAS4ABRQJCTAAAQCHIwA=.',
Th='Thecheatt:BAECLgAFFH8JAAMPAAMJFSMLGgDAAANoDAAAAgBbAGkMAAACAFkA6gwAAAUAWAAPAAMJZCILGgDAAANoDAAAAgBbAGkMAAABAFMA6gwAAAUAWAAlAAEJyiKoFQBjAAFpDAAAAQBZAC4ABAp/OgADJQAJCfEjRQcAkQIAJQAJCd4jRQcAkQIADwAGCQge6kkAfQEAAAA=.Therelore:BAEALgAECgkJEwABLgAECgkJFAAQALgRAA==.',
Ty='Tyära:BAEBLgAECn8eAAMQAAgJaAtBuAAIAQhoDAAABgAYAGkMAAAGACQAawwAAAUAPgBqDAAAAwAXAGwMAAACAB4AbQwAAAEADQDqDAAABgAWAG4MAAABAA4AEAAHCUEJQbgACAEHaAwAAAUAEgBpDAAABQAZAGsMAAAEACYAagwAAAIAEwBsDAAAAQAeAOoMAAAEAA0AbgwAAAEADgAkAAcJ1wqZMwDNAAdoDAAAAQAYAGkMAAABACQAawwAAAEAPgBqDAAAAQAXAGwMAAABAAcAbQwAAAEADQDqDAAAAgAWAAEuAAUUBAkYAAYAyw0A.',
Vi='Vilexie:BAEALgAECggJEwAAAA==.',
Wa='Wafflé:BAEALgAECgIJAgAAAA==.',
Wh='Whitecrosses:BAEALgAECgEJAQABLgAECgcJGQARAEkSAA==.',
Wi='Wiskystagger:BAEALgADCgEJAgAAAA==.',
Za='Zanea:BAEALgADCgkJEgABLgAECgkJPwACAJMbAA==.Zargan:BAEALgAECgcJCAABLgAECgkJIwASAN8RAA==.',
Ze='Zertzz:BAEALgAFFAEJAQABLgAFFAgJIgALABgdAA==.',
Zi='Zibbz:BAECLgAFFH8KAAINAAQJIx6NIgBMAQRoDAAAAwBHAGkMAAADAFAAawwAAAEAVwDqDAAAAwBEAA0ABAkjHo0iAEwBBGgMAAADAEcAaQwAAAMAUABrDAAAAQBXAOoMAAADAEQALgAECn8/AAMNAAkJgiUjAgBdAwANAAkJgiUjAgBdAwAZAAcJyxqmBwC/AQAAAA==.Zinia:BAEBLgAECn8/AAICAAkJkxuDAQDZAQloDAAACwBXAGkMAAALAFIAawwAAAsAQQBqDAAACABCAGwMAAAGAE8AbQwAAAMANgDqDAAACQBaAG4MAAADACsAbwwAAAEAPAACAAkJkxuDAQDZAQloDAAACwBXAGkMAAALAFIAawwAAAsAQQBqDAAACABCAGwMAAAGAE8AbQwAAAMANgDqDAAACQBaAG4MAAADACsAbwwAAAEAPAAAAA==.',
Zo='Zoan:BAEALgAECgQJCAABLgAECgkJNAAfAGUjAA==.',
Zu='Zubbfist:BAEALgADCgcJBwABLgAFFAQJCgANACMeAA==.Zubbrael:BAEBLgAECn8sAAMLAAgJHhsNIADFAQhoDAAACQBUAGkMAAAHAEMAawwAAAYARQBqDAAABgBQAGwMAAAGAEMAbQwAAAEAUgDqDAAACABHAG4MAAABACoACwAHCUMaDSAAxQEHaAwAAAcAVABpDAAABQBDAGsMAAAEAEUAagwAAAQAUABsDAAABABDAOoMAAAGAEcAbgwAAAEAKgAOAAcJgwk+OAAyAQdoDAAAAgAOAGkMAAACABUAawwAAAIAIwBqDAAAAgArAGwMAAACABIAbQwAAAEAEgDqDAAAAgATAAEuAAUUBAkKAA0AIx4A.Zubbs:BAEALgAFFAQJBAABLgAFFAQJCgANACMeAA==.Zubbz:BAECLgAFFH8GAAMiAAQJFxKvEgAOAQRoDAAAAwAqAGkMAAABAD0AawwAAAEAGADqDAAAAQA4ACIABAkXEq8SAA4BBGgMAAACACoAaQwAAAEAPQBrDAAAAQAYAOoMAAABADgAJgABCU8IuqIAOAABaAwAAAEAFQAuAAQKfzQAAyYACAkuH5MeAJoCACYACAksHpMeAJoCACIABwmWHvcSAAACAAEuAAUUBAkKAA0AIx4A.Zubbzdh:BAEBLgAFFH8IAAMPAAMJnRUlHACzAANoDAAAAwA7AGkMAAACACAA6gwAAAMASgAPAAMJnRUlHACzAANoDAAAAwA7AGkMAAACACAA6gwAAAIASgAlAAEJcBatGgA9AAHqDAAAAQA5AAEuAAUUBAkKAA0AIx4A.',
Zz='Zzertz:BAECLgAFFH8iAAILAAgJGB1XCADmAQhoDAAACABhAGkMAAAHAGIAawwAAAYAVABqDAAAAwBcAGwMAAABACcAbQwAAAEAQgDqDAAABwBYAG4MAAABAC8ACwAICRgdVwgA5gEIaAwAAAgAYQBpDAAABwBiAGsMAAAGAFQAagwAAAMAXABsDAAAAQAnAG0MAAABAEIA6gwAAAcAWABuDAAAAQAvAC4ABAp/KwACCwAICf8iOgYAKQMACwAICf8iOgYAKQMAAAA=.',
['Àb']='Àbeel:BAEALgAECgUJCAABLgAECgkJPAAKAE8cAA==.Àbel:BAEBLgAECn88AAMKAAkJTxxjBgASAgloDAAACgBXAGkMAAALAFQAawwAAAgAWgBqDAAABwBeAGwMAAAFAD0AbQwAAAIAIwDqDAAADABZAG4MAAAEAFkAbwwAAAEAKQAKAAcJKx5jBgASAgdoDAAACABXAGkMAAAJAFQAawwAAAUAWgBqDAAABQBeAGwMAAAFAD0A6gwAAAkAWQBuDAAAAgAyAAkACAnkGRsaAMgBCGgMAAACAEkAaQwAAAIATwBrDAAAAwBOAGoMAAACAF0AbQwAAAIAIwDqDAAAAwBBAG4MAAACAFkAbwwAAAEAKQAAAA==.Àble:BAEALgAECggJDQABLgAECgkJPAAKAE8cAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
