local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Monk-Windwalker','Shaman-Enhancement','Monk-Mistweaver','Paladin-Retribution','Paladin-Holy','Unknown-Unknown','Mage-Frost','Priest-Holy','Rogue-Subtlety','Rogue-Assassination','Priest-Shadow','Warrior-Arms','Evoker-Augmentation','Priest-Discipline','Warrior-Fury','DeathKnight-Unholy','Druid-Balance','Shaman-Restoration','DeathKnight-Frost','Mage-Arcane','Druid-Guardian','Paladin-Protection','Druid-Restoration','Druid-Feral','Rogue-Outlaw','Evoker-Preservation','Evoker-Devastation','Monk-Brewmaster','Hunter-Survival','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Elemental','Warlock-Demonology','Warlock-Destruction','Mage-Fire','DemonHunter-Havoc','DeathKnight-Blood','Warrior-Protection','DemonHunter-Devourer',}
local provider = {region='US',realm='Dalaran',name='US',type='subscribers',zone=46,date='2026-08-18',data={Ad='Adansso:BAEBLgAECn82AAIBAAkJPRKKHgC5AQloDAAACQArAGkMAAAIADoAawwAAAcAQwBqDAAABQA0AGwMAAAGADEAbQwAAAMAHADqDAAACgA+AG4MAAAFACUAbwwAAAEAGgABAAkJPRKKHgC5AQloDAAACQArAGkMAAAIADoAawwAAAcAQwBqDAAABQA0AGwMAAAGADEAbQwAAAMAHADqDAAACgA+AG4MAAAFACUAbwwAAAEAGgAAAA==.',
Al='Aliastei:BAEALgADCggJEgABLgAECgkJPwACAJMbAA==.',
Ap='Apawcowlypse:BAEALgADCgcJDAABLgAFFAYJGQADADQRAA==.',
As='Ashko:BAEBLgAECn83AAMEAAgJbBy/OwAVAghoDAAACwBLAGkMAAAKAFcAawwAAAgAUQBqDAAABwBSAGwMAAAFAFEAbQwAAAMAKwDqDAAACQBgAG4MAAACACkABAAICWwcvzsAFQIIaAwAAAkASwBpDAAACABXAGsMAAAGAFEAagwAAAYAUgBsDAAABQBRAG0MAAADACsA6gwAAAgAYABuDAAAAgApAAUABQnQErxMAAgBBWgMAAACAFEAaQwAAAIAHQBrDAAAAgBPAGoMAAABABcA6gwAAAEAGwABLgAFFAMJAQAGAAAAAA==.Astralore:BAEALgAECgMJAwABLgAECgkJUwAEAF8eAA==.',
Ay='Ayodele:BAEBLgAECn84AAIHAAkJtBuCHgCmAgloDAAACQBSAGkMAAAHAEcAawwAAAUAQwBqDAAACABWAGwMAAAGAEkAbQwAAAQAPwDqDAAACABTAG4MAAAGAFYAbwwAAAMAJwAHAAkJtBuCHgCmAgloDAAACQBSAGkMAAAHAEcAawwAAAUAQwBqDAAACABWAGwMAAAGAEkAbQwAAAQAPwDqDAAACABTAG4MAAAGAFYAbwwAAAMAJwAAAA==.',
Az='Azurlia:BAEALgAFFAEJAQAAAA==.',
Ba='Babycora:BAEALgAFFAMJAwABLgAFFAcJFwAIAIwaAA==.Bagelandlox:BAEALgADCgEJAQABLgAECgYJDAAGAAAAAA==.Barrui:BAECLgAFFH9mAAMJAAkJXSOMAABGAwloDAAADwBgAGkMAAAQAGIAawwAAA8AXwBqDAAADwBgAGwMAAAFAFkAbQwAAAcASQDqDAAACwBdAG4MAAAJAGEAbwwAAAkATwAJAAkJXSOMAABGAwloDAAADgBgAGkMAAAOAGIAawwAAA0AXwBqDAAADgBgAGwMAAAEAFkAbQwAAAcASQDqDAAACwBdAG4MAAAJAGEAbwwAAAkATwAKAAUJghrdAQApAQVoDAAAAQBfAGkMAAACAGAAawwAAAIASgBqDAAAAQAeAGwMAAABAAQALgAECn85AAMJAAkJcCTpBQAzAwAJAAkJ8SLpBQAzAwAKAAYJHyEvBABwAgAAAA==.',
Be='Belynila:BAECLgAFFH8dAAILAAUJwx0lDAAsAQVoDAAACgBVAGkMAAAIAD4AawwAAAQAOQBqDAAAAQBJAOoMAAAGAGMACwAFCcMdJQwALAEFaAwAAAoAVQBpDAAACAA+AGsMAAAEADkAagwAAAEASQDqDAAABgBjAC4ABAp/RgACCwAJCYUiOgUAAgMACwAJCYUiOgUAAgMAAAA=.Bestiavera:BAECLgAFFH8LAAIMAAMJBAaWGQCBAANoDAAABwAZAGkMAAADAA8AbwwAAAEABQAMAAMJBAaWGQCBAANoDAAABwAZAGkMAAADAA8AbwwAAAEABQAuAAQKf0wAAgwACQnjF9MCAJwBAAwACQnjF9MCAJwBAAAA.',
Br='Briggoker:BAEBLgAECn8YAAINAAkJLhmuAQA8AgloDAAABAA6AGkMAAAEAEgAawwAAAMALABqDAAAAgA8AGwMAAACADwAbQwAAAEAPQDqDAAABQBJAG4MAAABAEYAbwwAAAIASgANAAkJLhmuAQA8AgloDAAABAA6AGkMAAAEAEgAawwAAAMALABqDAAAAgA8AGwMAAACADwAbQwAAAEAPQDqDAAABQBJAG4MAAABAEYAbwwAAAIASgAAAA==.Brigmahf:BAEALgAECgQJCQABLgAECgkJGAANAC4ZAA==.',
Bu='Bubblindora:BAECLgAFFH8/AAIOAAkJFxxiAQAwAgloDAAACgBaAGkMAAAIAFoAawwAAAgASABqDAAABgBQAGwMAAAGACgAbQwAAAQAQQDqDAAACQBhAG4MAAAGADUAbwwAAAYAOAAOAAkJFxxiAQAwAgloDAAACgBaAGkMAAAIAFoAawwAAAgASABqDAAABgBQAGwMAAAGACgAbQwAAAQAQQDqDAAACQBhAG4MAAAGADUAbwwAAAYAOAAuAAQKfysAAg4ACQkoJZ0AALYDAA4ACQkoJZ0AALYDAAAA.',
Ca='Carbonarra:BAEBLgAECn9fAAIPAAkJjhwNAgCIAgloDAAADwBbAGkMAAAOAFAAawwAAA4AUgBqDAAACwBYAGwMAAALAEgAbQwAAAYALADqDAAACgBRAG4MAAAIAEMAbwwAAAYAPwAPAAkJjhwNAgCIAgloDAAADwBbAGkMAAAOAFAAawwAAA4AUgBqDAAACwBYAGwMAAALAEgAbQwAAAYALADqDAAACgBRAG4MAAAIAEMAbwwAAAYAPwAAAA==.',
Ch='Chetegos:BAEALgADCgYJBgABLgAFFAMJCQAPABUjAA==.Chíefsquirel:BAEALgAECgYJDAAAAA==.',
Da='Dadbanger:BAECLgAFFH81AAMBAAkJhyM4AABxAgloDAAABgBiAGkMAAAGAGAAawwAAAUASgBqDAAACABfAGwMAAAHAGMAbQwAAAIASQDqDAAABwBhAG4MAAAGAF0AbwwAAAYAXgABAAkJhyM4AABxAgloDAAABgBiAGkMAAAGAGAAawwAAAUASgBqDAAACABfAGwMAAABAGMAbQwAAAIASQDqDAAABwBhAG4MAAAGAF0AbwwAAAYAXgADAAEJIApqXwBCAAFsDAAABgAZAC4ABAp/KgACAQAICXEmCQIAhAMAAQAICXEmCQIAhAMAAAA=.Darkvirgo:BAEBLgAFFH8YAAIHAAUJbwtraAATAQVoDAAABwAuAGkMAAAHAB4AawwAAAMADwBqDAAAAQARAOoMAAAGABgABwAFCW8La2gAEwEFaAwAAAcALgBpDAAABwAeAGsMAAADAA8AagwAAAEAEQDqDAAABgAYAAEuAAUUCQksAAsA/hkA.',
De='Deathbeaver:BAEALgAECgYJCwABLgAECgkJUwAEAF8eAA==.Destrom:BAEBLgAECn8UAAIQAAkJuBHYggBeAQloDAAAAwAwAGkMAAADADAAawwAAAMASABqDAAAAgA2AGwMAAABAB4AbQwAAAEAKADqDAAAAwAXAG4MAAACAC0AbwwAAAIANQAQAAkJuBHYggBeAQloDAAAAwAwAGkMAAADADAAawwAAAMASABqDAAAAgA2AGwMAAABAB4AbQwAAAEAKADqDAAAAwAXAG4MAAACAC0AbwwAAAIANQAAAA==.',
Di='Diozi:BAEALgADCgkJCQABLgAFFAUJBQARAKcNAA==.',
En='Ensetrenaaki:BAEALgADCgUJBQABLgAECgkJGAASAKUeAA==.',
Ep='Epilepticc:BAECLgAFFH8PAAIEAAQJSB7COAA7AQRoDAAABQBCAGkMAAAEAFUAawwAAAMAUADqDAAAAwBNAAQABAlIHsI4ADsBBGgMAAAFAEIAaQwAAAQAVQBrDAAAAwBQAOoMAAADAE0ALgAECn88AAIEAAkJ6yL5GQCoAgAEAAkJ6yL5GQCoAgAAAA==.',
Er='Eronor:BAEALgAECgIJBAABLgAECgcJFgATAPQZAA==.',
Et='Ethalon:BAECLgAFFH8TAAMFAAQJ1Bl5GgBNAQRoDAAABgBOAGkMAAAFAFoAawwAAAMAEwDqDAAABQBMAAUABAnUGXkaAE0BBGgMAAAFAE4AaQwAAAUAWgBrDAAAAwATAOoMAAAFAEwABAABCbcC38cAOQABaAwAAAEABgAuAAQKfycAAwUACQmuGycYAFECAAUACQmuGycYAFECAAQAAgnJFOthADUAAAAA.',
Ga='Garlooth:BAECLgAFFH8RAAIUAAQJ7BbdAQAGAQRoDAAABwAzAGkMAAAFAE4AawwAAAEAMgDqDAAABAA2ABQABAnsFt0BAAYBBGgMAAAHADMAaQwAAAUATgBrDAAAAQAyAOoMAAAEADYALgAECn82AAIUAAkJFSUvAABiAwAUAAkJFSUvAABiAwAAAA==.',
Gi='Giantquin:BAEALgAECgIJBgABLgAFFAMJCAAVAIMZAA==.',
Gl='Glizzygary:BAEALgAFFAUJEgAAAQ==.',
Gr='Grimvalor:BAEBLgAECn9TAAMEAAkJXx7sHACYAgloDAAACwBcAGkMAAAKAEwAawwAAAsAUgBqDAAACQBYAGwMAAAKAFkAbQwAAAcASwDqDAAADABSAG4MAAAIAD0AbwwAAAUAPQAEAAkJXx7sHACYAgloDAAACgBcAGkMAAAKAEwAawwAAAoAUgBqDAAACABYAGwMAAAJAFkAbQwAAAcASwDqDAAACwBSAG4MAAAIAD0AbwwAAAUAPQAWAAUJzwpaQABdAAVoDAAAAQAPAGsMAAABACwAagwAAAEALABsDAAAAQAiAOoMAAABAA8AAAA=.Grunclaws:BAEBLgAECn8VAAQRAAcJIREHQwABAQdoDAAABQAzAGkMAAAFACsAawwAAAQALwBqDAAAAgAfAGwMAAACAEAAbQwAAAEAEwDqDAAAAgAkABEABgl/DwdDAAEBBmgMAAABADMAaQwAAAIAKwBrDAAAAgAvAGoMAAABAB8AbQwAAAEAEwDqDAAAAQAkABcABgkfFcoLAPUABmgMAAAEAE8AaQwAAAMASwBrDAAAAgBEAGoMAAABACEAbAwAAAEACQDqDAAAAQA6ABgAAQlIGblHAEsAAWwMAAABAEAAAS4ABRQDCQEABgAAAAA=.Grunjitsu:BAEBLgAECn8aAAMBAAcJVhq2GwDSAQdoDAAABgBHAGkMAAAGAFoAawwAAAUASwBqDAAAAQAdAOoMAAAGAD4AbgwAAAEAJwBvDAAAAQBBAAEABglWGrYbANIBBmgMAAADAEcAaQwAAAMAWgBrDAAAAQBLAOoMAAACAD4AbgwAAAEAJwBvDAAAAQBBAAMABQmLGDoPADQBBWgMAAADAFAAaQwAAAMAQABrDAAABAA5AGoMAAABAB8A6gwAAAQAUAABLgAFFAMJAQAGAAAAAA==.Grunjo:BAEALgAECgkJDQABLgAFFAMJAQAGAAAAAA==.Grunsy:BAEALgAECgcJBgABLgAFFAMJAQAGAAAAAA==.Grunzi:BAEALgAFFAMJAQAAAA==.',
Ha='Haf:BAEBLgAECn8qAAIWAAkJ8hELFQCAAQloDAAABwA9AGkMAAAGAEIAawwAAAYARwBqDAAABQAjAGwMAAAFADYAbQwAAAMAFQDqDAAABgAvAG4MAAACABYAbwwAAAIAFwAWAAkJ8hELFQCAAQloDAAABwA9AGkMAAAGAEIAawwAAAYARwBqDAAABQAjAGwMAAAFADYAbQwAAAMAFQDqDAAABgAvAG4MAAACABYAbwwAAAIAFwAAAA==.Halrak:BAEALgADCgEJAQABLgAECgkJPwACAJMbAA==.',
He='Hertzmuch:BAEALgADCgYJDgABLgAFFAYJGQADADQRAA==.',
Ho='Holeighfuk:BAEALgAECgYJBgAAAA==.',
Hu='Huntsso:BAEALgAECgEJAQABLgAECgkJNgABAD0SAA==.',
Ju='Jupiterboiz:BAECLgAFFH8MAAIZAAYJpxMMAAAqAgZoDAAAAwBgAGkMAAADAEUAawwAAAIANgBqDAAAAQALAGwMAAABAAAA6gwAAAIAHgAZAAYJpxMMAAAqAgZoDAAAAwBgAGkMAAADAEUAawwAAAIANgBqDAAAAQALAGwMAAABAAAA6gwAAAIAHgAuAAQKfyoAAhkACQmQIWAAAGcDABkACQmQIWAAAGcDAAEuAAUUCAkRABQAoRwA.',
Ka='Kautheros:BAEBLgAECn8jAAQaAAkJ3xFEBAAgAQloDAAABQBIAGkMAAAFAD4AawwAAAUARwBqDAAABAAfAGwMAAADACIAbQwAAAMACQDqDAAABwBDAG4MAAACAB0AbwwAAAEAHwAaAAkJ3xFEBAAgAQloDAAAAwBIAGkMAAADAD4AawwAAAMARwBqDAAAAgAfAGwMAAABACIAbQwAAAMACQDqDAAABQBDAG4MAAACAB0AbwwAAAEAHwANAAYJ1wlQXADFAAZoDAAAAQAdAGkMAAABABgAawwAAAIAHABqDAAAAQAkAGwMAAACABcA6gwAAAIAEgAbAAMJmgaqIABOAANoDAAAAQAJAGkMAAABABgAagwAAAEAGgABLgAECgcJFgATAPQZAA==.',
Kr='Kroxychi:BAEALgAECgcJDgAAAA==.Kroxypurple:BAEALgADCgIJAgABLgAECgcJDgAGAAAAAA==.',
Ku='Kungfused:BAECLgAFFH8ZAAIDAAYJNBE4IgBcAQZoDAAABgAqAGkMAAAGADoAawwAAAQALwBqDAAAAQAaAGwMAAABABYA6gwAAAcAQgADAAYJNBE4IgBcAQZoDAAABgAqAGkMAAAGADoAawwAAAQALwBqDAAAAQAaAGwMAAABABYA6gwAAAcAQgAuAAQKf3QABAMACQkWHsAKAKUCAAMACQkWHsAKAKUCAAEACQmYFBIYAPMBABwABAn/CHBaAKEAAAAA.',
Le='Lennather:BAEBLgAECn9LAAIBAAkJtCVvAQBkAwloDAAACQBjAGkMAAAJAGEAawwAAAgAYABqDAAACABOAGwMAAAKAGEAbQwAAAkAXgDqDAAACwBfAG4MAAAJAGMAbwwAAAIAWgABAAkJtCVvAQBkAwloDAAACQBjAGkMAAAJAGEAawwAAAgAYABqDAAACABOAGwMAAAKAGEAbQwAAAkAXgDqDAAACwBfAG4MAAAJAGMAbwwAAAIAWgAAAA==.',
Li='Lidomi:BAEALgAECgUJDAABLgAFFAQJCwAaAP8PAA==.Lidrunka:BAECLgAFFH8IAAMcAAIJNRehQwCVAAJoDAAAAwAwAOoMAAAFAEUAHAACCTUXoUMAlQACaAwAAAIAMADqDAAABQBFAAEAAQkMAp4UAD0AAWgMAAABAAUALgAECn8YAAMBAAgJdBXVGwD9AQABAAgJ0BTVGwD9AQAcAAQJFhTISgDSAAABLgAFFAQJCwAaAP8PAA==.Linnadis:BAEALgAECgQJBwABLgAECgkJPwACAJMbAA==.',
['Lé']='Lépewpew:BAEBLgAECn8ZAAIdAAcJSRI/KABdAQdoDAAABgA+AGkMAAAFADMAawwAAAUAOwBqDAAAAwBNAGwMAAABACYA6gwAAAQAOgBuDAAAAQAKAB0ABwlJEj8oAF0BB2gMAAAGAD4AaQwAAAUAMwBrDAAABQA7AGoMAAADAE0AbAwAAAEAJgDqDAAABAA6AG4MAAABAAoAAAA=.',
Ma='Mattimus:BAEBLgAECn9BAAMeAAkJehCaDACpAQloDAAACwA9AGkMAAAJACsAawwAAAoAJwBqDAAACAA8AGwMAAAHADkAbQwAAAMAIgDqDAAACAApAG4MAAAFAB8AbwwAAAQAGwAeAAkJehCaDACpAQloDAAACwA9AGkMAAAIACsAawwAAAkAJwBqDAAABwA8AGwMAAAHADkAbQwAAAMAIgDqDAAABwApAG4MAAAFAB8AbwwAAAQAGwAfAAQJ+QK2cAB8AARpDAAAAQABAGsMAAABAAkAagwAAAEACQDqDAAAAQAMAAAA.',
['Má']='Mákí:BAEBLgAECn8lAAQBAAkJrhcJIwCZAQloDAAABQBIAGkMAAAEADQAawwAAAUALwBqDAAABABIAGwMAAADAEEAbQwAAAEAFgDqDAAABwBQAG4MAAAFADUAbwwAAAMAWwABAAgJHRcJIwCZAQhoDAAABABIAGkMAAADADQAawwAAAQALwBqDAAAAgBIAGwMAAADAEEA6gwAAAQAUABuDAAABQA1AG8MAAACACoAHAAGCSQZGTwACwEGaAwAAAEAQABpDAAAAQAyAGsMAAABACUAagwAAAEAPQDqDAAAAgBOAG8MAAABAFsAAwADCfgOJYYAkQADagwAAAEAKwBtDAAAAQAdAOoMAAABACkAAAA=.',
Na='Natebanger:BAEALgAECgYJDAABLgAFFAkJNQABAIcjAA==.',
No='Noeyednuck:BAEALgAECgcJEQABLgAFFAMJDwAeAKsSAA==.',
Nu='Nuckshott:BAECLgAFFH8PAAIeAAMJqxLLXgDnAANoDAAABgA2AGkMAAAEAB0A6gwAAAUAOwAeAAMJqxLLXgDnAANoDAAABgA2AGkMAAAEAB0A6gwAAAUAOwAuAAQKfzUAAh4ACQnWHwIaAIkCAB4ACQnWHwIaAIkCAAAA.',
Og='Ogx:BAEBLgAECn8pAAQSAAYJDyV7AwB8AgZoDAAACgBhAGkMAAAJAF8AawwAAAkAXwBqDAAABABgAGwMAAADAGAA6gwAAAYAVgASAAYJDyV7AwB8AgZoDAAABgBhAGkMAAAFAF8AawwAAAUAXwBqDAAAAgBgAGwMAAACAGAA6gwAAAMAVgAgAAUJbhdvDgDjAAVoDAAAAQAjAGkMAAACAFEAawwAAAIAOgBqDAAAAgA5AOoMAAABAEAAAgAFCSAYhQkAuAAFaAwAAAMAUABpDAAAAgA1AGsMAAACADIAbAwAAAEAVADqDAAAAgAnAAEuAAUUAwkBAAYAAAAA.',
Ol='Olgass:BAEALgADCgIJAgABLgAECgkJNAAhAGUjAA==.',
Pe='Pewpocalypse:BAEALgADCgkJEgABLgAFFAYJGQADADQRAA==.',
Pu='Purlok:BAEALgAECgkJAwABLgAFFAMJAQAGAAAAAA==.',
Qu='Quindrox:BAEBLgAECn8aAAINAAkJRSGiBQAFAwloDAAAAgBdAGkMAAACAFMAawwAAAMAVgBqDAAAAwBTAGwMAAADAFoAbQwAAAMATADqDAAABABQAG4MAAADAFoAbwwAAAMATwANAAkJRSGiBQAFAwloDAAAAgBdAGkMAAACAFMAawwAAAMAVgBqDAAAAwBTAGwMAAADAFoAbQwAAAMATADqDAAABABQAG4MAAADAFoAbwwAAAMATwABLgAFFAMJCAAVAIMZAA==.Quinet:BAEBLgAECn80AAMhAAkJZSP6CwDuAgloDAAABwBhAGkMAAAHAFwAawwAAAcAXABqDAAABwBRAGwMAAAGAFwAbQwAAAQAWADqDAAABwBeAG4MAAAFAEcAbwwAAAIAYAAhAAkJZSP6CwDuAgloDAAABwBhAGkMAAAGAFwAawwAAAcAXABqDAAAAQAQAGwMAAAEAFwAbQwAAAQAWADqDAAABwBeAG4MAAAFAEcAbwwAAAIAYAAiAAMJyh5xLwD9AANpDAAAAQBGAGoMAAAGAFEAbAwAAAIAVwAAAA==.Quinman:BAEBLgAECn8aAAQdAAkJRRoQFAAFAgloDAAABQBBAGkMAAAEADMAawwAAAQATwBqDAAAAgAnAGwMAAACAGEAbQwAAAIAOwDqDAAABABBAG4MAAACAD0AbwwAAAEAOgAdAAkJixcQFAAFAgloDAAAAQA8AGkMAAABAAAAawwAAAEATwBqDAAAAgAnAGwMAAACAGEAbQwAAAIAOwDqDAAAAwBBAG4MAAACAD0AbwwAAAEAOgAfAAQJWhWQWQDfAARoDAAAAwBBAGkMAAADADMAawwAAAMAMQDqDAAAAQA0AB4AAQkVGNgnAToAAWgMAAABAD0AAS4ABRQDCQgAFQCDGQA=.Quinmanbear:BAEBLgAFFH8IAAMVAAMJgxndFQDTAANoDAAAAgA8AGkMAAACAEIA6gwAAAQARAAVAAMJgxndFQDTAANoDAAAAgA8AGkMAAACAEIA6gwAAAMARAAYAAEJeguOIAA4AAHqDAAAAQAdAAAA.Quinroxx:BAEBLgAECn8gAAIHAAgJXiN8KwDFAghoDAAABQBiAGkMAAAFAFsAawwAAAUAXwBqDAAABQBeAGwMAAADAFoAbQwAAAIAUwDqDAAABgBhAG4MAAABAE0ABwAICV4jfCsAxQIIaAwAAAUAYgBpDAAABQBbAGsMAAAFAF8AagwAAAUAXgBsDAAAAwBaAG0MAAACAFMA6gwAAAYAYQBuDAAAAQBNAAEuAAUUAwkIABUAgxkA.Quinvinvin:BAEALgAECgcJDQABLgAFFAMJCAAVAIMZAA==.',
Ra='Ragsnak:BAEALgAECgkJEwABLgAFFAMJAQAGAAAAAA==.Razzun:BAECLgAFFH9WAAMHAAkJ7SROAgApAwloDAAACABjAGkMAAALAGMAawwAAAoAYQBqDAAACwBhAGwMAAAMAF0AbQwAAAQAUwDqDAAADABjAG4MAAAJAGEAbwwAAAkAVQAHAAkJ7SROAgApAwloDAAACABjAGkMAAAKAGMAawwAAAoAYQBqDAAACwBhAGwMAAAMAF0AbQwAAAMAUwDqDAAADABjAG4MAAAJAGEAbwwAAAkAVQAjAAIJKBSDBACiAAJpDAAAAQBAAG0MAAABACcALgAECn8nAAIHAAkJfSYzAgDcAwAHAAkJfSYzAgDcAwAAAA==.',
Ro='Ronimus:BAEALgAECgEJAQAAAA==.',
Ru='Rufio:BAECLgAFFH8NAAIkAAMJJQzpHAC7AANoDAAABgA2AGkMAAAEABMA6gwAAAMAEwAkAAMJJQzpHAC7AANoDAAABgA2AGkMAAAEABMA6gwAAAMAEwAuAAQKf1IAAiQACQloIxsBAB4DACQACQloIxsBAB4DAAAA.Rufiø:BAEALgAECgkJCQABLgAFFAMJDQAkACUMAA==.',
Ry='Rytiou:BAECLgAFFH8eAAINAAkJuhdXBQCuAQloDAAABABSAGkMAAAFAFYAawwAAAQALgBqDAAABABJAGwMAAABADUAbQwAAAEAOADqDAAACABSAG4MAAABABcAbwwAAAIANgANAAkJuhdXBQCuAQloDAAABABSAGkMAAAFAFYAawwAAAQALgBqDAAABABJAGwMAAABADUAbQwAAAEAOADqDAAACABSAG4MAAABABcAbwwAAAIANgAuAAQKfzIAAg0ACQnqJFkCAIwDAA0ACQnqJFkCAIwDAAAA.',
Sa='Saadxevok:BAEBLgAECn8YAAMbAAgJQRFLEADYAQhoDAAAAwA7AGkMAAADADEAawwAAAMARQBqDAAAAwAwAGwMAAAEAEgAbQwAAAMACADqDAAAAwAkAG4MAAACAAwAGwAICUERSxAA2AEIaAwAAAMAOwBpDAAAAwAxAGsMAAACAEUAagwAAAIAMABsDAAAAwBIAG0MAAABAAgA6gwAAAEAJABuDAAAAQAMABoABglTCD0pACkBBmsMAAABABAAagwAAAEAEQBsDAAAAQARAG0MAAACAB4A6gwAAAIAJwBuDAAAAQAGAAEuAAUUCAkjAAsAZB4A.Saadxm:BAEALgAECgcJDwABLgAFFAgJIwALAGQeAA==.Saadxp:BAECLgAFFH8jAAMLAAgJZB7JAABZAghoDAAABQBjAGkMAAAGAGAAawwAAAYAYABqDAAABgBYAGwMAAADACAAbQwAAAEAVADqDAAABwBeAG4MAAABACkACwAHCV0hyQAAWQIHaAwAAAQAYwBpDAAABQBgAGsMAAAFAGAAagwAAAUAWABtDAAAAQBUAOoMAAAFAF4AbgwAAAEAKQAOAAYJ5RnxAQANAgZoDAAAAQBJAGkMAAABAB0AawwAAAEAWgBqDAAAAQBOAGwMAAADADMA6gwAAAIASgAuAAQKfyYAAwsACAmRJrcDAGADAAsACAmRJrcDAGADAA4ABQkLHz4gAJEBAAAA.',
Se='Sendrys:BAEALgAECgEJAQABLgAECgkJPwACAJMbAA==.',
Sg='Sgtgigachad:BAEALgAECgUJBQABLgAFFAUJEgAGAAAAAQ==.',
Sp='Spilt:BAEBLgAFFH8qAAIgAAkJfhvxAgCqAgloDAAABQBYAGkMAAAGAF0AawwAAAUAPQBqDAAAAgBIAGwMAAAFAFoAbQwAAAQARwDqDAAABgBLAG4MAAAHAEYAbwwAAAIADAAgAAkJfhvxAgCqAgloDAAABQBYAGkMAAAGAF0AawwAAAUAPQBqDAAAAgBIAGwMAAAFAFoAbQwAAAQARwDqDAAABgBLAG4MAAAHAEYAbwwAAAIADAAAAA==.Spiltdh:BAEALgADCgkJCQABLgAFFAkJOgAHAPgYAA==.Spiltmonk:BAEBLgAECn8YAAIBAAYJWh80HAD6AQZoDAAABABGAGkMAAAEAFEAawwAAAQAUgBqDAAABABMAGwMAAADAFIA6gwAAAUAVAABAAYJWh80HAD6AQZoDAAABABGAGkMAAAEAFEAawwAAAQAUgBqDAAABABMAGwMAAADAFIA6gwAAAUAVAABLgAFFAkJOgAHAPgYAA==.Spiltsham:BAEBLgAFFH8OAAMgAAgJ3RMxCQDIAQhoDAAAAgA8AGkMAAABAAUAawwAAAIAOABqDAAAAQBHAGwMAAABAFgA6gwAAAIAHgBuDAAAAwA/AG8MAAACADMAIAAHCdEWMQkAyAEHaAwAAAEAPABrDAAAAQA4AGoMAAABAEcAbAwAAAEAWADqDAAAAQAeAG4MAAADAD8AbwwAAAIAMwACAAQJMgLaCwCfAARoDAAAAQAEAGkMAAABAAUAawwAAAEABwDqDAAAAQAEAAEuAAUUCQk6AAcA+BgA.',
Ta='Takalune:BAEBLgAECn8dAAMBAAkJsyAFAQDXAgloDAAABABfAGkMAAAEAE8AawwAAAQAUwBqDAAAAwBWAGwMAAADAF8AbQwAAAIAUwDqDAAABQBdAG4MAAADADUAbwwAAAEAVQABAAkJqSAFAQDXAgloDAAAAwBfAGkMAAADAE8AawwAAAMAUwBqDAAAAwBWAGwMAAADAF8AbQwAAAIAUwDqDAAABABdAG4MAAACADQAbwwAAAEAVQAcAAUJQxrDJQCAAQVoDAAAAQBNAGkMAAABAEQAawwAAAEARgDqDAAAAQBCAG4MAAABADUAAS4ABAoHCRYAEwD0GQA=.Taku:BAEBLgAECn8WAAMTAAcJ9BmzAwBmAQdoDAAAAwA7AGkMAAADAD8AawwAAAMAQgBqDAAAAwA+AGwMAAADAEUAbQwAAAMAPADqDAAABABPABMABgm0GLMDAGYBBmgMAAACADsAaQwAAAIAPwBrDAAAAgA/AGoMAAACADUAbAwAAAIARQBtDAAAAgA8ACUABwnDE7EoAA8BB2gMAAABADEAaQwAAAEAFwBrDAAAAQBCAGoMAAABAD4AbAwAAAEANABtDAAAAQAfAOoMAAAEAE8AAAA=.Talakua:BAEALgAECgcJBwABLgAECgcJFgATAPQZAA==.Taymeean:BAEALgAECgMJBAABLgAFFAQJCAANAB4MAA==.Tayvok:BAECLgAFFH8IAAINAAQJHgyzOwDYAARoDAAAAwAsAGkMAAADADAAawwAAAEAFgDqDAAAAQAJAA0ABAkeDLM7ANgABGgMAAADACwAaQwAAAMAMABrDAAAAQAWAOoMAAABAAkALgAECn8yAAQNAAkJkRyjDwBtAgANAAkJkRyjDwBtAgAaAAIJ7Ab4DQA8AAAbAAEJ1BJOCQA3AAAAAA==.',
Te='Tentickles:BAECLgAFFH8lAAMLAAUJ0CFMCQBlAQVoDAAACABQAGkMAAAIAFsAawwAAAcAYQBqDAAABQBHAOoMAAAJAEwACwAFCdAhTAkAZQEFaAwAAAcAUABpDAAABwBbAGsMAAAGAGEAagwAAAQARwDqDAAACABMAA4ABQnXCIETAAIBBWgMAAABABwAaQwAAAEAFgBrDAAAAQAdAGoMAAABABIA6gwAAAEADgAuAAQKfxQAAgsACAmIInIIAP0CAAsACAmIInIIAP0CAAEuAAUUCQk1AAEAhyMA.',
Th='Thecheatt:BAECLgAFFH8JAAMPAAMJFSOBKQAPAQNoDAAAAgBbAGkMAAACAFkA6gwAAAUAWAAPAAMJZCKBKQAPAQNoDAAAAgBbAGkMAAABAFMA6gwAAAUAWAAmAAEJyiJiGABhAAFpDAAAAQBZAC4ABAp/OgADJgAJCfEjRQcAkQIAJgAJCd4jRQcAkQIADwAGCQge6kkAfQEAAAA=.Therelore:BAEALgAECgkJEwABLgAECgkJFAAQALgRAA==.',
Ty='Tyära:BAECLgAFFH8FAAIQAAMJFAiFWgCmAANoDAAAAwAsAGkMAAABAAkA6gwAAAEABwAQAAMJFAiFWgCmAANoDAAAAwAsAGkMAAABAAkA6gwAAAEABwAuAAQKfx4AAxAACAloC0G4AAgBABAABwlBCUG4AAgBACUABwnXCpkzAM0AAAEuAAUUBAkYAAcAyw0A.',
Vi='Vilexie:BAEALgAECggJEwAAAA==.',
Wa='Wafflé:BAEALgAECgIJAgAAAA==.',
Wh='Whitecrosses:BAEALgAECgEJAQABLgAECgcJGQAdAEkSAA==.',
Wi='Wiskystagger:BAEALgADCgEJAgAAAA==.',
Za='Zanea:BAEALgADCgkJEgABLgAECgkJPwACAJMbAA==.Zargan:BAEALgAECgcJCAABLgAECgcJFgATAPQZAA==.',
Ze='Zertzz:BAEALgAFFAEJAQABLgAFFAkJJwALAEQdAA==.',
Zi='Zibbz:BAECLgAFFH8KAAINAAQJIx6NIgBMAQRoDAAAAwBHAGkMAAADAFAAawwAAAEAVwDqDAAAAwBEAA0ABAkjHo0iAEwBBGgMAAADAEcAaQwAAAMAUABrDAAAAQBXAOoMAAADAEQALgAECn8/AAMNAAkJgiUjAgBdAwANAAkJgiUjAgBdAwAbAAcJyxqmBwC/AQAAAA==.Zinia:BAEBLgAECn8/AAICAAkJkxspAgDUAQloDAAACwBXAGkMAAALAFIAawwAAAsAQQBqDAAACABCAGwMAAAGAE8AbQwAAAMANgDqDAAACQBaAG4MAAADACsAbwwAAAEAPAACAAkJkxspAgDUAQloDAAACwBXAGkMAAALAFIAawwAAAsAQQBqDAAACABCAGwMAAAGAE8AbQwAAAMANgDqDAAACQBaAG4MAAADACsAbwwAAAEAPAAAAA==.',
Zo='Zoan:BAEALgAECgQJCAABLgAECgkJNAAhAGUjAA==.',
Zu='Zubbcicle:BAEALgAECgYJBgABLgAFFAQJCgANACMeAA==.Zubbfist:BAEALgADCgcJBwABLgAFFAQJCgANACMeAA==.Zubbrael:BAECLgAFFH8FAAILAAMJjhZAEQDlAANoDAAAAwBNAGkMAAABAD0A6gwAAAEAIgALAAMJjhZAEQDlAANoDAAAAwBNAGkMAAABAD0A6gwAAAEAIgAuAAQKfywAAwsACAkeGw0gAMUBAAsABwlDGg0gAMUBAA4ABwmDCT44ADIBAAEuAAUUBAkKAA0AIx4A.Zubbs:BAEALgAFFAQJBAABLgAFFAQJCgANACMeAA==.Zubbz:BAECLgAFFH8GAAMkAAQJFxKvEgAOAQRoDAAAAwAqAGkMAAABAD0AawwAAAEAGADqDAAAAQA4ACQABAkXEq8SAA4BBGgMAAACACoAaQwAAAEAPQBrDAAAAQAYAOoMAAABADgAJwABCU8IuqIAOAABaAwAAAEAFQAuAAQKfzQAAycACAkuH5MeAJoCACcACAksHpMeAJoCACQABwmWHvcSAAACAAEuAAUUBAkKAA0AIx4A.Zubbzdh:BAEBLgAFFH8IAAMPAAMJnRW9IACtAANoDAAAAwA7AGkMAAACACAA6gwAAAMASgAPAAMJnRW9IACtAANoDAAAAwA7AGkMAAACACAA6gwAAAIASgAmAAEJcBZZHgA6AAHqDAAAAQA5AAEuAAUUBAkKAA0AIx4A.',
Zz='Zzertz:BAECLgAFFH8nAAMLAAgJRB0HBQD0AQhoDAAACQBhAGkMAAAIAGIAawwAAAcAVABqDAAABABcAGwMAAACACoAbQwAAAEAQgDqDAAABwBYAG4MAAABAC8ACwAICUQdBwUA9AEIaAwAAAkAYQBpDAAACABiAGsMAAAHAFQAagwAAAMAXABsDAAAAgAqAG0MAAABAEIA6gwAAAcAWABuDAAAAQAvAAgAAQl1DfYeAD0AAWoMAAABACIALgAECn8rAAILAAgJ/yI6BgApAwALAAgJ/yI6BgApAwAAAA==.Zzerz:BAEALgAECgQJBAABLgAFFAkJJwALAEQdAA==.',
['Àb']='Àbeel:BAEALgAECgUJCAABLgAECgkJPAAKAE8cAA==.Àbel:BAEBLgAECn88AAMKAAkJTxxjBgASAgloDAAACgBXAGkMAAALAFQAawwAAAgAWgBqDAAABwBeAGwMAAAFAD0AbQwAAAIAIwDqDAAADABZAG4MAAAEAFkAbwwAAAEAKQAKAAcJKx5jBgASAgdoDAAACABXAGkMAAAJAFQAawwAAAUAWgBqDAAABQBeAGwMAAAFAD0A6gwAAAkAWQBuDAAAAgAyAAkACAnkGRsaAMgBCGgMAAACAEkAaQwAAAIATwBrDAAAAwBOAGoMAAACAF0AbQwAAAIAIwDqDAAAAwBBAG4MAAACAFkAbwwAAAEAKQAAAA==.Àble:BAEALgAECggJDQABLgAECgkJPAAKAE8cAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
