local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Evoker-Augmentation','Mage-Fire','Mage-Frost','DeathKnight-Unholy','Priest-Shadow','Evoker-Preservation','Evoker-Devastation','Shaman-Restoration','Warlock-Demonology','Warlock-Destruction','Druid-Guardian','DemonHunter-Devourer','Monk-Mistweaver','DeathKnight-Frost','Rogue-Outlaw','Monk-Brewmaster','Paladin-Holy','Rogue-Subtlety','Warrior-Fury','Shaman-Elemental','Monk-Windwalker','Priest-Holy','Priest-Discipline','Druid-Feral','DeathKnight-Blood','Druid-Restoration','DemonHunter-Vengeance','Warrior-Arms','Warrior-Protection','Rogue-Assassination','Mage-Arcane','Paladin-Retribution','Paladin-Protection','DemonHunter-Havoc','Druid-Balance',}
local provider = {region='US',realm='MoonGuard',name='US',type='subscribers',zone=46,date='2026-06-22',data={Ad='Advvy:BAEALgAECgUJEgAAAA==.',
Ag='Ageregressor:BAEALgAECgcJBwAAAA==.',
Ai='Aihime:BAEALgADCgYJBgABLgAECgEJAQABAAAAAA==.',
Al='Alcean:BAEBLgAECn8+AAICAAkJiCJ9BQAIAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQACAAkJiCJ9BQAIAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQAAAA==.Algebra:BAECLgAFFH8cAAMDAAcJDCHbAACXAQdoDAAABwBfAGkMAAAGAGEAawwAAAUAYwBqDAAAAwBaAGwMAAABAFkAbQwAAAEAJQDqDAAABQBZAAQABwnUIJwkAOgBB2gMAAAGAFsAaQwAAAUAYQBrDAAABABjAGoMAAACAFoAbAwAAAEAWQBtDAAAAQAlAOoMAAAEAFkAAwAFCcUk2wAAlwEFaAwAAAEAXwBpDAAAAQBfAGsMAAABAGEAagwAAAEAVADqDAAAAQBYAC4ABAp/HQACBAAJCaEkBAsAIQMABAAJCaEkBAsAIQMAAAA=.Aléyna:BAEALgAECgEJAgAAAA==.',
Ar='Araakki:BAEALgAECgcJDwAAAA==.Aradell:BAEBLgAFFH8IAAIFAAQJ+wojgAAHAQRoDAAAAgAjAGkMAAACAAQAawwAAAIALADqDAAAAgAbAAUABAn7CiOAAAcBBGgMAAACACMAaQwAAAIABABrDAAAAgAsAOoMAAACABsAAAA=.Arteron:BAEALgAFFAIJAwABLgAFFAcJHQAGACcdAA==.',
Ay='Ayoade:BAECLgAFFH8hAAIHAAUJSRf9EgBjAQVoDAAACAAzAGkMAAAIAD0AawwAAAgATgBqDAAAAQAfAOoMAAAIAEsABwAFCUkX/RIAYwEFaAwAAAgAMwBpDAAACAA9AGsMAAAIAE4AagwAAAEAHwDqDAAACABLAC4ABAp/GAADBwAICWkcnQoAjAIABwAICWkcnQoAjAIACAACCREV4zEAhwAAAS4ABRQICTgACQB9IAA=.',
Az='Azzurel:BAEBLgAECn8ZAAMKAAkJ7BMaUQCoAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAwAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAAKAAkJ7BMaUQCoAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAgAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAALAAEJAAA+cgAzAAFqDAAAAQAUAAAA.',
Ba='Bareskin:BAEBLgAFFH8FAAIMAAUJawpBHQCqAAVoDAAAAQAyAGkMAAABAAkAawwAAAEAGwBqDAAAAQAiAOoMAAABABMADAAFCWsKQR0AqgAFaAwAAAEAMgBpDAAAAQAJAGsMAAABABsAagwAAAEAIgDqDAAAAQATAAEuAAUUBgkTAA0A8RMA.',
Be='Benghi:BAEALgAFFAIJAgABLgAFFAYJEQAOABYSAA==.Berrii:BAECLgAFFH8cAAMFAAYJrRy3LAC1AQZoDAAABwBMAGkMAAAGAFIAawwAAAQASgBqDAAAAgA0AGwMAAABACgA6gwAAAgAXAAFAAYJrRy3LAC1AQZoDAAABgBMAGkMAAAFAFIAawwAAAQASgBqDAAAAgA0AGwMAAABACgA6gwAAAgAXAAPAAIJHAHoJABXAAJoDAAAAQABAGkMAAABAAMALgAECn82AAIFAAkJzySbDAAIAwAFAAkJzySbDAAIAwAAAA==.',
Bl='Bloodroyal:BAEALgAFFAIJAgABLgAFFAMJEgAQAKseAA==.',
Bo='Bobbysan:BAECLgAFFH8fAAIRAAgJnhj2BwAQAghoDAAABgBQAGkMAAAFAEwAawwAAAQASQBqDAAABABAAGwMAAACACgAbQwAAAEAGwDqDAAACABWAG4MAAABADgAEQAICZ4Y9gcAEAIIaAwAAAYAUABpDAAABQBMAGsMAAAEAEkAagwAAAQAQABsDAAAAgAoAG0MAAABABsA6gwAAAgAVgBuDAAAAQA4AC4ABAp/LwACEQAJCRghmAoA4AIAEQAJCRghmAoA4AIAAAA=.Bonemommyxo:BAECLgAFFH8UAAIFAAYJEiMYCQCIAQZoDAAABQBhAGkMAAAFAGMAawwAAAMAXQBqDAAAAQApAG0MAAABADsA6gwAAAUAYwAFAAYJEiMYCQCIAQZoDAAABQBhAGkMAAAFAGMAawwAAAMAXQBqDAAAAQApAG0MAAABADsA6gwAAAUAYwAuAAQKfysAAgUACQmQJRwCALsDAAUACQmQJRwCALsDAAAA.',
Br='Brigbala:BAEALgAECgMJBgAAAA==.',
Bu='Buttlustplz:BAEALgAFFAEJAwABLgAFFAMJCQASANgfAA==.',
Ch='Chunghús:BAEALgAECgYJBgABLgAFFAgJIQAHANcOAA==.',
Co='Coggettle:BAEALgAECggJDgAAAA==.',
Cr='Crustome:BAEBLgAECn8vAAITAAgJag89AgDiAAhoDAAACQAYAGkMAAAJACcAawwAAAgAMgBqDAAABgAaAGwMAAAEAD0AbQwAAAMAGwDqDAAABQAjAG4MAAADACUAEwAICWoPPQIA4gAIaAwAAAkAGABpDAAACQAnAGsMAAAIADIAagwAAAYAGgBsDAAABAA9AG0MAAADABsA6gwAAAUAIwBuDAAAAwAlAAAA.Crustorc:BAEBLgAECn8hAAIUAAkJ5wlqMQCHAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABgAiAG4MAAAEABQAbwwAAAEAFQAUAAkJ5wlqMQCHAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABgAiAG4MAAAEABQAbwwAAAEAFQABLgAECggJLwATAGoPAA==.',
Cu='Cubed:BAEALgAFFAEJAgABLgAFFAcJHAADAAwhAA==.',
Da='Darkstrand:BAEALgAFFAIJAgABLgAFFAMJEgAQAKseAA==.Daylea:BAECLgAFFH8nAAICAAkJzyAGAgAmAwloDAAABgBgAGkMAAAGAGMAawwAAAgAYABqDAAABABfAGwMAAADAF8AbQwAAAIATQDqDAAABwBjAG4MAAACAC8AbwwAAAEAPAACAAkJzyAGAgAmAwloDAAABgBgAGkMAAAGAGMAawwAAAgAYABqDAAABABfAGwMAAADAF8AbQwAAAIATQDqDAAABwBjAG4MAAACAC8AbwwAAAEAPAAuAAQKfyUAAwIACQnGJWgBALQDAAIACQnGJWgBALQDAAgABAm3IZUPABIBAAAA.',
De='Demagogué:BAECLgAFFH8QAAMVAAgJyRb5DgC8AQhoDAAAAwBHAGkMAAABAEkAawwAAAEACQBqDAAAAQAlAGwMAAACAGAAbQwAAAEAJwDqDAAABgBBAG4MAAABADQAFQAHCU0U+Q4AvAEHaAwAAAIARwBpDAAAAQBJAGsMAAABAAkAagwAAAEAJQBtDAAAAQAnAOoMAAAFAEEAbgwAAAEANAAJAAMJGhV5RADXAANoDAAAAQAcAGwMAAACADIA6gwAAAEAUwAuAAQKfygAAxUACQmOI70JAMICABUACQmOI70JAMICAAkABwmRHEw3ANMBAAEuAAUUCAkhAAcA1w4A.Demonipryde:BAEALgAECgMJAwAAAA==.',
Di='Digitalwior:BAEALgADCgIJAwABLgAECggJKQAOACIXAA==.',
Dr='Dreamspun:BAECLgAFFH8SAAIQAAMJqx5KBwAUAQNoDAAABwBLAGkMAAADAEoA6gwAAAgAVQAQAAMJqx5KBwAUAQNoDAAABwBLAGkMAAADAEoA6gwAAAgAVQAuAAQKfzsAAhAACQkbI4IAAEIDABAACQkbI4IAAEIDAAAA.Drunkenqrow:BAEALgAECgYJDQABLgAECggJEAABAAAAAA==.',
Du='Dubsii:BAECLgAFFH8YAAIOAAYJ5iCHDQAyAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAOAAYJ5iCHDQAyAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAuAAQKfxcAAw4ACAmLIZwGAPMCAA4ACAmLIZwGAPMCABYAAQl/Jp9yAGsAAAEuAAUUCAk4AAkAfSAA.Dubsy:BAECLgAFFH84AAIJAAgJfSB/AAA2AghoDAAADABQAGkMAAAMAF8AawwAAAkAWwBqDAAACgBjAGwMAAABAEMAbQwAAAEALADqDAAACgBWAG4MAAABAGQACQAICX0gfwAANgIIaAwAAAwAUABpDAAADABfAGsMAAAJAFsAagwAAAoAYwBsDAAAAQBDAG0MAAABACwA6gwAAAoAVgBuDAAAAQBkAC4ABAp/MwADCQAJCdAllgAAtAMACQAJCdAllgAAtAMAFQAECbUj4y4AhQEAAAA=.',
Eh='Ehanee:BAEALgAFFAIJAwAAAA==.',
Ei='Eibm:BAEALgAECgEJAQAAAA==.',
Er='Ereshin:BAEBLgAECn8YAAIJAAgJXB+UDQDqAghoDAAABQBjAGkMAAADAGAAawwAAAQAWQBqDAAAAwBKAGwMAAACAE8AbQwAAAEAEgDqDAAAAwBYAG4MAAADAGAACQAICVwflA0A6gIIaAwAAAUAYwBpDAAAAwBgAGsMAAAEAFkAagwAAAMASgBsDAAAAgBPAG0MAAABABIA6gwAAAMAWABuDAAAAwBgAAAA.',
Ev='Evieari:BAECLgAFFH8fAAMXAAYJfh+yBgDtAQZoDAAABgBTAGkMAAAGAGMAawwAAAYAUgBqDAAABAAlAGwMAAABAGAA6gwAAAgAUgAXAAUJ1CKyBgDtAQVoDAAAAwBTAGkMAAADAGMAawwAAAMAUgBsDAAAAQBgAOoMAAAFAFIAGAAFCQcP2CAASgEFaAwAAAMAJQBpDAAAAwAYAGsMAAADAC8AagwAAAQAJQDqDAAAAwAtAC4ABAp/GQADGAAJCdYarR0A4AEAGAAGCaYcrR0A4AEAFwAHCbkZmCkApQEAAS4ABRQGCQUAFwBKHwA=.Evielyssa:BAEBLgAFFH8JAAIXAAUJGRIVEwAwAQVoDAAAAgAZAGkMAAACACUAawwAAAIAMQBqDAAAAQBMAOoMAAACACoAFwAFCRkSFRMAMAEFaAwAAAIAGQBpDAAAAgAlAGsMAAACADEAagwAAAEATADqDAAAAgAqAAEuAAUUBgkFABcASh8A.Evierari:BAEBLgAFFH8FAAMXAAIJSh8uJQCUAAJoDAAAAwBQAGkMAAACAE8AFwACCUofLiUAlAACaAwAAAIAUABpDAAAAgBPAAYAAQkgAb8XADwAAWgMAAABAAIAAAA=.',
Fa='Fappimeal:BAECLgAFFH8tAAMFAAcJIR+5HwD1AQdoDAAACgBiAGkMAAAKAGEAawwAAAgAWgBqDAAABABVAGwMAAABAFEAbQwAAAEACQDqDAAACwBjAAUABgmTJLkfAPUBBmgMAAAHAGIAaQwAAAcAYQBrDAAABgBaAGoMAAACAFUAbAwAAAEAUQDqDAAABgBjAA8ABglAFxEJAF0BBmgMAAADAFwAaQwAAAMAQwBrDAAAAgA9AGoMAAACACQAbQwAAAEACQDqDAAABQBCAC4ABAp/QQADBQAJCTAmdwIAtAMABQAJCTAmdwIAtAMADwAGCZYd3QsAugEAAAA=.Fappisham:BAEALgAECgkJEgABLgAFFAcJLQAFACEfAA==.',
Fd='Fdhi:BAEALgAFFAEJAgABLgAFFAIJBQAZADgiAA==.',
Fe='Felshins:BAEALgADCgMJBgABLgAECggJGAAJAFwfAA==.',
Fo='Fofer:BAECLgAFFH8FAAIRAAQJkx/0FQBzAQRoDAAAAQBWAGkMAAABADoAawwAAAEAWwDqDAAAAgBXABEABAmTH/QVAHMBBGgMAAABAFYAaQwAAAEAOgBrDAAAAQBbAOoMAAACAFcALgAECn8nAAIRAAcJASa+CQCWAgARAAcJASa+CQCWAgABLgAFFAgJIAAaAEIfAA==.Foil:BAEALgADCgkJGwABLgAECgkJaAAbAMglAA==.',
Fr='Froshin:BAEALgADCgUJCwABLgAECggJGAAJAFwfAA==.',
Fs='Fshi:BAEBLgAFFH8FAAIZAAIJOCKADwDJAAJoDAAAAgBVAOoMAAADAFkAGQACCTgigA8AyQACaAwAAAIAVQDqDAAAAwBZAAAA.',
Fu='Funkey:BAECLgAFFH8TAAMNAAYJ8RM+OQBAAQZoDAAABQBDAGkMAAAFAFoAawwAAAIAFABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgANAAYJuA4+OQBAAQZoDAAAAwAhAGkMAAAEADgAawwAAAIAFABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgAcAAIJth6eAgCjAAJoDAAAAgBDAGkMAAABAFoALgAECn8nAAMcAAkJnyDEAQD8AgAcAAgJsyLEAQD8AgANAAYJfhaEVQCGAQAAAA==.',
Gr='Greatares:BAEBLgAFFH8JAAMdAAMJogt3KwC9AANoDAAAAwAZAGkMAAADABIA6gwAAAMALQAdAAMJdAt3KwC9AANoDAAAAwAZAGkMAAACABAA6gwAAAMALQAeAAEJGQedLQA3AAFpDAAAAQASAAAA.Greathades:BAEALgAECgkJAgABLgAFFAMJCQAdAKILAA==.Greatmonkey:BAEALgAECgcJBgABLgAFFAMJCQAdAKILAA==.Greatodin:BAEALgAECgkJBAABLgAFFAMJCQAdAKILAA==.Greatosiris:BAEALgAECgkJAgABLgAFFAMJCQAdAKILAA==.Greatra:BAEALgADCgEJAQABLgAFFAMJCQAdAKILAA==.Grummel:BAECLgAFFH8NAAITAAMJACICJAAEAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgATAAMJACICJAAEAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgAuAAQKfycAAxMACQk8IH8JAPkCABMACQk8IH8JAPkCAB8AAQlwFGwdAEAAAAAA.',
Hb='Hbcarter:BAEBLgAFFH8HAAIbAAMJSxRIOQDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgAbAAMJSxRIOQDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgABLgAFFAgJOAAJAH0gAA==.',
Ia='Iambuns:BAEALgAECgcJBwABLgAFFAcJLQAFACEfAA==.',
Il='Illiyania:BAEALgAECgEJAQAAAA==.Ilnarya:BAEALgAECgEJAQABLgAECgkJHgANALIRAA==.',
Im='Imquitelarge:BAEBLgAECn8VAAIdAAkJWhY6DwD6AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAdAAkJWhY6DwD6AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAAAA==.',
Iz='Izapotato:BAECLgAFFH8TAAINAAUJMxgjCQCXAQVoDAAABABUAGkMAAAEACoAawwAAAQANABqDAAAAwBDAOoMAAAEAEQADQAFCTMYIwkAlwEFaAwAAAQAVABpDAAABAAqAGsMAAAEADQAagwAAAMAQwDqDAAABABEAC4ABAp/IgACDQAHCaElQCAAUwIADQAHCaElQCAAUwIAAS4ABRQICSEABwDXDgA=.',
Ja='Jail:BAEBLgAECn8tAAMgAAkJoiQuAABiAwloDAAACABiAGkMAAAGAGEAawwAAAcAXwBqDAAABQBiAGwMAAAEAF8AbQwAAAMAUgDqDAAABQBgAG4MAAAEAGIAbwwAAAMAVQAgAAkJoiQuAABiAwloDAAABgBiAGkMAAAFAGEAawwAAAUAXwBqDAAABABiAGwMAAADAF8AbQwAAAIAUgDqDAAAAwBgAG4MAAACAGIAbwwAAAIAVQAEAAkJbRUdPgAjAgloDAAAAgA4AGkMAAABADwAawwAAAIAMQBqDAAAAQBEAGwMAAABACMAbQwAAAEAMwDqDAAAAgBMAG4MAAACAEAAbwwAAAEALQAAAA==.',
Ka='Katekicks:BAECLgAFFH8HAAIWAAUJQx7RCwBnAQVoDAAAAQBPAGkMAAABAE4AawwAAAEAOQBqDAAAAQAxAOoMAAADAF4AFgAFCUMe0QsAZwEFaAwAAAEATwBpDAAAAQBOAGsMAAABADkAagwAAAEAMQDqDAAAAwBeAC4ABAp/MAACFgAJCSYlagEAZgMAFgAJCSYlagEAZgMAAAA=.Katestinks:BAECLgAFFH8UAAMFAAYJeBsAPACBAQZoDAAABABZAGkMAAAEAFkAawwAAAMALgBqDAAAAgARAGwMAAABAB0A6gwAAAYAYQAFAAUJeBsAPACBAQVoDAAABABZAGkMAAAEAFkAawwAAAMALgBsDAAAAQAdAOoMAAAGAGEAGgABCQAAGmMAAAABagwAAAIAEQAuAAQKfywAAwUACQk3JIsFAE4DAAUACQk3JIsFAE4DABoAAQm2CnlgACkAAAEuAAUUBQkHABYAQx4A.',
Ke='Kelandrea:BAECLgAFFH8IAAIhAAMJ2w8fcgDOAANoDAAAAwAWAGkMAAABAD0A6gwAAAQAJgAhAAMJ2w8fcgDOAANoDAAAAwAWAGkMAAABAD0A6gwAAAQAJgAuAAQKfx8ABCEACQmrG9giAJ4CACEACQmrG9giAJ4CABIAAgnSEPeBAHAAACIAAgkzF+1KAD8AAAEuAAUUBAkIAAUA+woA.',
Kh='Khega:BAEALgAECgEJAQABLgAFFAMJDAAjAGocAA==.',
Ki='Kirkh:BAEALgAECgcJDAABLgAECgkJJgAGAEobAA==.Kirkpriest:BAEBLgAECn8mAAIGAAkJSht8BwAQAwloDAAABQBbAGkMAAAFAFkAawwAAAUAXABqDAAABQBPAGwMAAAFAFcAbQwAAAQAMADqDAAABQBaAG4MAAADADEAbwwAAAEACQAGAAkJSht8BwAQAwloDAAABQBbAGkMAAAFAFkAawwAAAUAXABqDAAABQBPAGwMAAAFAFcAbQwAAAQAMADqDAAABQBaAG4MAAADADEAbwwAAAEACQAAAA==.Kitowatt:BAEALgAECgYJCgABLgAECgkJJwAkAL0fAA==.',
Kr='Kregazi:BAECLgAFFH8SAAIaAAQJkRvqFQA8AQRoDAAABgBBAGkMAAAGAEkAawwAAAIAXADqDAAABAAyABoABAmRG+oVADwBBGgMAAAGAEEAaQwAAAYASQBrDAAAAgBcAOoMAAAEADIALgAECn86AAIaAAkJEyMEBQDdAgAaAAkJEyMEBQDdAgAAAA==.',
Ky='Kyriste:BAEBLgAECn8aAAIXAAcJZiFODwB0AgdoDAAABQBbAGkMAAAFAFoAawwAAAQAWABqDAAAAwBVAGwMAAADAEAA6gwAAAQAWwBuDAAAAgBXABcABwlmIU4PAHQCB2gMAAAFAFsAaQwAAAUAWgBrDAAABABYAGoMAAADAFUAbAwAAAMAQADqDAAABABbAG4MAAACAFcAAS4ABRQGCSIAEwBaHgA=.',
La='Larissaqt:BAECLgAFFH8mAAIGAAgJxRNnBQApAghoDAAABwBTAGkMAAAGAEoAawwAAAcAHQBqDAAABgAgAGwMAAACADEAbQwAAAEAFADqDAAABwBQAG4MAAACAA8ABgAICcUTZwUAKQIIaAwAAAcAUwBpDAAABgBKAGsMAAAHAB0AagwAAAYAIABsDAAAAgAxAG0MAAABABQA6gwAAAcAUABuDAAAAgAPAC4ABAp/MgACBgAJCQ4jJQMAMQMABgAJCQ4jJQMAMQMAAAA=.',
Li='Lioshi:BAEBLgAFFH8FAAMJAAUJSB3rKABCAQVoDAAAAQBSAGkMAAABAFkAawwAAAEAOgBqDAAAAQBaAOoMAAABADUACQAECbkb6ygAQgEEaAwAAAEAUgBpDAAAAQBZAGsMAAABADoA6gwAAAEANQAVAAEJAACxFAAAAAFqDAAAAQAVAAEuAAUUBAkZAAQALhwA.',
Ma='Maildaddy:BAECLgAFFH8hAAIHAAgJ1w47CgAHAghoDAAABgAwAGkMAAAGAEMAawwAAAYAMABqDAAABQBDAGwMAAABAAoAbQwAAAEACADqDAAABwAxAG4MAAABAAQABwAICdcOOwoABwIIaAwAAAYAMABpDAAABgBDAGsMAAAGADAAagwAAAUAQwBsDAAAAQAKAG0MAAABAAgA6gwAAAcAMQBuDAAAAQAEAC4ABAp/JgAEBwAICQkgCAoAQwIABwAICQkgCAoAQwIAAgAFCSgRKjcAGwEACAADCRwc3ycA4gAAAAA=.Maxxy:BAEBLgAECn8cAAIbAAkJtR2gFgCBAgloDAAABQBdAGkMAAAEAFwAawwAAAQAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAbAAkJtR2gFgCBAgloDAAABQBdAGkMAAAEAFwAawwAAAQAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAAAA==.',
Mc='Mckellen:BAECLgAFFH8RAAMXAAQJeBxdEQBEAQRoDAAABQBFAGkMAAAFAEkAawwAAAMAPADqDAAABABXABcABAl4HF0RAEQBBGgMAAAFAEUAaQwAAAQASQBrDAAAAwA8AOoMAAADAFcAGAACCREJAhQAlgACaQwAAAEAGgDqDAAAAQAUAC4ABAp/HQADGAAICc4ZmQwAbgIAGAAICc4ZmQwAbgIAFwAECSYMg1wAwQAAAS4ABRQICTgACQB9IAA=.',
Me='Merakkii:BAEBLgAECn8nAAINAAcJ9h2eLgAMAgdoDAAABQBcAGkMAAAGAF0AawwAAAkAWQBqDAAACQBiAGwMAAAEAFoAbQwAAAEAAQDqDAAABQBdAA0ABwn2HZ4uAAwCB2gMAAAFAFwAaQwAAAYAXQBrDAAACQBZAGoMAAAJAGIAbAwAAAQAWgBtDAAAAQABAOoMAAAFAF0AAAA=.Merarite:BAEALgAFFAIJAgAAAA==.',
Mo='Mordraius:BAEALgAFFAIJAgABLgAFFAQJGQAEAC4cAA==.',
My='Myceliums:BAEALgAECgUJDgAAAA==.',
['Mö']='Möo:BAEALgAECgEJAQABLgAFFAYJHAAFAK0cAA==.',
Na='Nadasa:BAECLgAFFH8aAAIhAAYJ6hjRHQCRAQZoDAAABgAzAGkMAAAFAD4AawwAAAQAOgBqDAAAAwAxAGwMAAABAEEA6gwAAAcAUQAhAAYJ6hjRHQCRAQZoDAAABgAzAGkMAAAFAD4AawwAAAQAOgBqDAAAAwAxAGwMAAABAEEA6gwAAAcAUQAuAAQKf1IAAiEACQnrIWUKABQDACEACQnrIWUKABQDAAAA.',
Nh='Nhylia:BAEBLgAFFH8FAAIhAAMJihSQYwDoAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQAhAAMJihSQYwDoAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQABLgAFFAQJCAAFAPsKAA==.',
Ni='Nixaanu:BAEALgAECgEJAQABLgAECggJFAAVAH8aAA==.Nixei:BAEBLgAECn8UAAIVAAgJfxpEGABTAghoDAAAAgAyAGkMAAACAEIAawwAAAIATwBqDAAAAgA3AGwMAAAEAFAAbQwAAAMARwDqDAAAAgA3AG4MAAADAEYAFQAICX8aRBgAUwIIaAwAAAIAMgBpDAAAAgBCAGsMAAACAE8AagwAAAIANwBsDAAABABQAG0MAAADAEcA6gwAAAIANwBuDAAAAwBGAAAA.',
Ny='Nyriaa:BAECLgAFFH8KAAIXAAQJeRvBEgAzAQRoDAAAAwBOAGkMAAADAFEAawwAAAIAOgDqDAAAAgA+ABcABAl5G8ESADMBBGgMAAADAE4AaQwAAAMAUQBrDAAAAgA6AOoMAAACAD4ALgAECn8eAAIXAAkJvSMBBQAuAwAXAAkJvSMBBQAuAwAAAA==.',
['Ní']='Nítedragon:BAEALgAECgEJAQABLgAECggJGgAHAA8gAA==.',
Ow='Owlenjoyer:BAECLgAFFH8GAAIkAAMJRxUtMADCAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAkAAMJRxUtMADCAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAuAAQKfx8AAiQACQmGGosNAIECACQACQmGGosNAIECAAEuAAUUBQkHABYAQx4A.',
Pa='Palashin:BAEBLgAECn8aAAISAAYJHx4IHwAKAgZoDAAABgBgAGkMAAAFAE4AawwAAAUAVABqDAAAAwBHAGwMAAABADAA6gwAAAYAUwASAAYJHx4IHwAKAgZoDAAABgBgAGkMAAAFAE4AawwAAAUAVABqDAAAAwBHAGwMAAABADAA6gwAAAYAUwABLgAECggJGAAJAFwfAA==.',
Pe='Personnelkid:BAEALgAECgcJDQABLgAECgkJPAAXALUZAA==.',
Ph='Pheiro:BAEBLgAECn8cAAIEAAgJcQ1wiADBAQhoDAAABQBSAGkMAAAFAC0AawwAAAQAJQBqDAAAAgAXAGwMAAACABAAbQwAAAQADwDqDAAABQAmAG4MAAABAAUABAAICXENcIgAwQEIaAwAAAUAUgBpDAAABQAtAGsMAAAEACUAagwAAAIAFwBsDAAAAgAQAG0MAAAEAA8A6gwAAAUAJgBuDAAAAQAFAAAA.',
Pl='Platedaddy:BAEALgAECgcJDwABLgAFFAgJIQAHANcOAA==.',
Pu='Punchweagle:BAEBLgAECn82AAMRAAkJNhDdIQCZAQloDAAACAAzAGkMAAAHAEAAawwAAAgAOgBqDAAABgAoAGwMAAAGADkAbQwAAAUAEQDqDAAABgAwAG4MAAAFAA0AbwwAAAMAEwARAAkJ8Q7dIQCZAQloDAAABAAzAGkMAAAEADQAawwAAAQAMwBqDAAABAAZAGwMAAAEADkAbQwAAAUAEQDqDAAABAAqAG4MAAAFAA0AbwwAAAMAEwAWAAYJUxRGMgBbAQZoDAAABAAyAGkMAAADAEAAawwAAAQAOgBqDAAAAgAoAGwMAAACACUA6gwAAAIAMAABLgAFFAIJAgABAAAAAA==.',
Qr='Qrowdrake:BAEALgAECgQJBQABLgAECggJEAABAAAAAA==.Qrowfather:BAEALgAECggJEAAAAA==.Qrowsunny:BAEALgAECgQJBQABLgAECggJEAABAAAAAA==.',
Ra='Raveglaive:BAEALgAECgUJAwAAAA==.',
Re='Redvine:BAEALgADCgUJBQABLgAFFAYJEwANAPETAA==.Rexpanda:BAEALgAECgQJBgABLgAECgUJBQABAAAAAA==.Rextank:BAEALgAECgEJAQABLgAECgUJBQABAAAAAA==.',
Ro='Roogies:BAECLgAFFH8iAAITAAYJWh7nDADEAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAAAwBdAGwMAAABACgA6gwAAAYAXgATAAYJWh7nDADEAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAAAwBdAGwMAAABACgA6gwAAAYAXgAuAAQKf0oAAxMACQmNJXgFANsCABMACQleJXgFANsCAB8ABwnrHjgAAKABAAAA.',
Ru='Rumpy:BAEALgAFFAIJBAABLgAFFAMJDQATAAAiAA==.',
['Ræ']='Ræx:BAEALgAECgUJBQAAAA==.',
Se='Serenytey:BAEALgAECgcJDQAAAA==.',
Sh='Shiins:BAEALgAECgIJAwABLgAECggJGAAJAFwfAA==.Shinthyr:BAEBLgAECn8YAAIXAAcJ5R4eFQA0AgdoDAAABQBTAGkMAAAEAFUAawwAAAQAXQBqDAAAAwBHAGwMAAACAFUA6gwAAAQASwBuDAAAAgA6ABcABwnlHh4VADQCB2gMAAAFAFMAaQwAAAQAVQBrDAAABABdAGoMAAADAEcAbAwAAAIAVQDqDAAABABLAG4MAAACADoAAS4ABAoICRgACQBcHwA=.',
Si='Sizzlefox:BAEALgAECgEJAQABLgAECgcJDwABAAAAAA==.',
St='Stygianfox:BAEALgAECgIJBAABLgAECgcJDwABAAAAAA==.',
Sy='Syldrasi:BAEALgAECgcJEQABLgAFFAYJIgATAFoeAA==.',
Ta='Tahune:BAEBLgAECn9oAAQbAAkJyCX3AADWAwloDAAADgBdAGkMAAANAGIAawwAAA0AYgBqDAAADQBhAGwMAAAMAGIAbQwAAAoAYQDqDAAADQBhAG4MAAAJAFoAbwwAAAcAYQAbAAkJyCX3AADWAwloDAAACgBdAGkMAAALAGIAawwAAAkAYgBqDAAACwBhAGwMAAAKAGIAbQwAAAgAYQDqDAAACwBhAG4MAAAHAFoAbwwAAAUAYQAMAAkJayMdAAA7AwloDAAAAgBdAGkMAAACAF4AawwAAAIAXQBqDAAAAgBXAGwMAAACAF8AbQwAAAIAVwDqDAAAAgBYAG4MAAACAFcAbwwAAAIAVAAkAAIJhiG9YACWAAJoDAAAAgBWAGsMAAACAFUAAAA=.Taso:BAEBLgAECn8dAAIRAAgJVhGtLgBKAQhoDAAABgA/AGkMAAAFAEMAawwAAAUASgBqDAAABQBPAGwMAAABAAAAbQwAAAEAAADqDAAABQBBAG4MAAABACYAEQAICVYRrS4ASgEIaAwAAAYAPwBpDAAABQBDAGsMAAAFAEoAagwAAAUATwBsDAAAAQAAAG0MAAABAAAA6gwAAAUAQQBuDAAAAQAmAAEuAAUUBQkaABoA6CAA.',
Th='Therapygap:BAEBLgAECn88AAQXAAkJtRmcDQCMAgloDAAACQBMAGkMAAAKADwAawwAAAYATABqDAAABwA7AGwMAAALAEoAbQwAAAQALwDqDAAACAA8AG4MAAADADkAbwwAAAIATQAXAAkJtRmcDQCMAgloDAAABgBMAGkMAAAGADwAawwAAAUATABqDAAABgA7AGwMAAAJAEoAbQwAAAQALwDqDAAABwA8AG4MAAACADkAbwwAAAIATQAGAAYJKwpOXgCeAAZoDAAAAwAnAGkMAAAEABUAawwAAAEAEgBqDAAAAQAHAGwMAAACACkA6gwAAAEACAAYAAEJfAPCiQAgAAFuDAAAAQAIAAAA.',
Tr='Triboon:BAEALgADCgMJAwABLgAFFAgJFwAOAKQaAA==.Trèantdaddy:BAEALgAFFAEJAgABLgAFFAgJIQAHANcOAA==.',
Tw='Twomonk:BAEALgAFFAEJAQABLgAFFAIJBgAWAL4hAA==.',
Un='Unsown:BAEALgAFFAEJAQABLgAFFAMJEgAQAKseAA==.',
Us='Usurah:BAECLgAFFH8aAAIhAAgJvBSYEADqAQhoDAAABgBOAGkMAAAGAFYAawwAAAMAQQBqDAAAAwA8AGwMAAACABsAbQwAAAEACADqDAAABAA+AG4MAAABACoAIQAICbwUmBAA6gEIaAwAAAYATgBpDAAABgBWAGsMAAADAEEAagwAAAMAPABsDAAAAgAbAG0MAAABAAgA6gwAAAQAPgBuDAAAAQAqAC4ABAp/KwADIQAJCYAixAkAQwMAIQAJCYAixAkAQwMAIgAFCVgcExwANgEAAAA=.',
Vi='Vindh:BAECLgAFFH8SAAMNAAUJugf9WwDcAAVoDAAABgAXAGkMAAAEABUAawwAAAMACABqDAAAAQAJAOoMAAAEABgADQAFCboH/VsA3AAFaAwAAAYAFwBpDAAABAAVAGsMAAADAAgAagwAAAEACQDqDAAAAwAYABwAAQkOBpEUACkAAeoMAAABAA8ALgAECn8oAAQNAAkJtxVdPQD/AQANAAkJtxVdPQD/AQAcAAIJOgN4MQA9AAAjAAEJAACOiQAAAAAAAA==.',
Vy='Vyndraennis:BAEBLgAECn8eAAINAAkJshGxRAC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQANAAkJshGxRAC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQAAAA==.',
['Vî']='Vîtâl:BAEALgADCgMJAwABLgAFFAUJEwAOAB0cAA==.',
Ya='Yaav:BAEBLgAECn8XAAIFAAkJxhAVWwC1AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAFAAkJxhAVWwC1AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAAAA==.',
Yu='Yufia:BAEBLgAECn8ZAAIKAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAKAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAAAA==.',
Za='Zatum:BAEBLgAECn8nAAMkAAkJvR/pDgBvAgloDAAABgBTAGkMAAAGAFYAawwAAAUAUABqDAAABABLAGwMAAAGAFMAbQwAAAIASgDqDAAABgBUAG4MAAADAEYAbwwAAAEAVwAkAAgJZB/pDgBvAghoDAAABgBTAGkMAAAGAFYAawwAAAUAUABqDAAABABLAGwMAAAFAFMAbQwAAAEASgDqDAAABQBUAG4MAAADAEYAGwAECaYLsp0AdQAEbAwAAAEAIgBtDAAAAQAdAOoMAAABAAkAbwwAAAEALQAAAA==.',
Zh='Zhuröng:BAECLgAFFH8ZAAIEAAQJLhwnDgD2AARoDAAACABZAGkMAAAIAE4AawwAAAYAKgDqDAAAAwBPAAQABAkuHCcOAPYABGgMAAAIAFkAaQwAAAgATgBrDAAABgAqAOoMAAADAE8ALgAECn8nAAIEAAkJrh/KTQBNAgAEAAkJrh/KTQBNAgAAAA==.',
Zo='Zomb:BAECLgAFFH8aAAIaAAUJ6CCUEgBjAQVoDAAACABbAGkMAAAHAEQAawwAAAQAXQBqDAAAAgBMAOoMAAAFAFQAGgAFCegglBIAYwEFaAwAAAgAWwBpDAAABwBEAGsMAAAEAF0AagwAAAIATADqDAAABQBUAC4ABAp/JQACGgAICY4haQQABQMAGgAICY4haQQABQMAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
