local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Warrior-Fury','Paladin-Retribution','Shaman-Enhancement','Shaman-Restoration','Priest-Holy','Monk-Brewmaster','Paladin-Holy','Druid-Restoration','Mage-Frost','DeathKnight-Blood','Warrior-Protection','DeathKnight-Unholy','Shaman-Elemental','Druid-Feral','Druid-Guardian','Rogue-Assassination','Rogue-Subtlety','Warlock-Demonology','Warlock-Destruction','Monk-Mistweaver','Paladin-Protection','Priest-Discipline','Hunter-BeastMastery','Hunter-Marksmanship','Evoker-Augmentation','DemonHunter-Devourer','Monk-Windwalker','Evoker-Devastation','Warrior-Arms','DeathKnight-Frost','Rogue-Outlaw','Mage-Arcane','Evoker-Preservation','Priest-Shadow','Druid-Balance','Hunter-Survival','DemonHunter-Havoc','DemonHunter-Vengeance','Warlock-Affliction',}
local provider = {region='US',realm='Akama',name='US',type='weekly',zone=46,date='2026-06-20',data={Ac='Accost:BAAALgAECgQJBgAAAA==.Acronica:BAAALgAECgEJAwAAAA==.',
Ad='Adagar:BAAALgAECgYJDgAAAA==.Adesha:BAAALgADCgYJBgAAAA==.',
Ae='Aeloria:BAAALgAECgcJBgAAAA==.Aeratedlol:BAAALgAFFAIJAwABLgAFFAQJBAABAAAAAA==.Aethandor:BAAALgAECgUJDQAAAA==.',
Ai='Ainslie:BAAALgADCgEJAQAAAA==.',
Ak='Akassa:BAABLgAECn8eAAICAAYJqAniWwDiAAACAAYJqAniWwDiAAAAAA==.Akavaleera:BAAALgAECgQJBwAAAA==.Aknologia:BAAALgADCgYJBgABLgAECgMJAwABAAAAAA==.Akíto:BAAALgAECgcJDQAAAA==.',
Al='Alaric:BAAALgADCgUJBQAAAA==.Alecto:BAABLgAECn8ZAAIDAAkJFAuniABfAQADAAkJFAuniABfAQAAAA==.Algo:BAABLgAECn8aAAMEAAkJVwTJHAAYAQAEAAkJVwTJHAAYAQAFAAcJYwTeggDZAAAAAA==.Allet:BAAALgADCgcJBwABLgAECgkJEgABAAAAAA==.Alune:BAAALgADCgYJDAAAAA==.',
Am='Amalthea:BAAALgAECgMJAwAAAA==.Amarah:BAACLgAFFH8VAAIGAAMJBiUxEgA7AQAGAAMJBiUxEgA7AQAuAAQKf0cAAgYACQn1HmwMAKACAAYACQn1HmwMAKACAAAA.Ameilie:BAAALgADCgYJBgAAAA==.',
An='Andron:BAAALgADCgQJBAAAAA==.Andy:BAAALgADCgcJBwAAAA==.Angryjames:BAAALgADCgYJCgAAAA==.Animehero:BAAALgAECgIJAwABLgAECgkJFQAHAJIcAA==.Ankoki:BAAALgADCggJCAAAAA==.',
Ap='Applemonster:BAAALgAECggJEAAAAA==.',
Ar='Aragörn:BAAALgAFFAEJAQAAAA==.Arboghast:BAAALgAECgUJCAAAAA==.Argadin:BAABLgAFFH8FAAIDAAQJ7AOkgAC1AAADAAQJ7AOkgAC1AAAAAA==.Argdru:BAAALgAECgYJDQABLgAFFAQJBQADAOwDAA==.Arglock:BAAALgADCgIJAgABLgAFFAQJBQADAOwDAA==.Argrekd:BAAALgADCgMJAwABLgAFFAQJBQADAOwDAA==.Aridol:BAAALgADCgUJBAAAAA==.Arigön:BAAALgADCgMJAwAAAA==.Arima:BAAALgAECgIJAwAAAA==.Arknox:BAABLgAECn8dAAMIAAkJJQ2YLgCiAQAIAAkJJQ2YLgCiAQADAAEJEAuFqwEqAAAAAA==.Arthaslk:BAAALgAECgcJEAABLgAECgcJFwACABYYAA==.',
As='Aserus:BAAALgAECgcJCwABLgAFFAcJIQAJAIAbAA==.Ashallel:BAAALgAECgQJBAABLgAFFAcJIQAJAIAbAA==.Ashx:BAAALgADCgIJBAABLgAECgkJIAAKAKoXAA==.Astralock:BAAALgAECgEJAQAAAA==.',
At='Ate:BAABLgAECn8wAAILAAgJmxuLDwATAgALAAgJmxuLDwATAgABLgAECgcJLgAMAB0cAA==.Atlette:BAACLgAFFH8RAAIGAAUJFyEHDACKAQAGAAUJFyEHDACKAQAuAAQKfyoAAgYACQluH2MCAEUDAAYACQluH2MCAEUDAAAA.Atrocitusz:BAAALgAECgIJAgAAAA==.Atroxx:BAACLgAFFH8OAAINAAQJmRDBHgAjAQANAAQJmRDBHgAjAQAuAAQKf1EAAg0ACQmZIswQABcDAA0ACQmZIswQABcDAAEuAAUUBgktAAQA1hoA.Attman:BAACLgAFFH8WAAIFAAUJWBoHHACLAQAFAAUJWBoHHACLAQAuAAQKfx4AAwUACAkSHAYbAHMCAAUACAkSHAYbAHMCAA4AAwlFAzyEADoAAAAA.',
Au='Augtism:BAAALgAECgYJBgAAAA==.Auradawn:BAAALgAECgQJEgAAAA==.',
Ay='Ayaya:BAAALgAECgQJBQABLgAECgYJEQABAAAAAA==.',
Ba='Baetrayer:BAAALgAECgcJCAAAAA==.Bailz:BAAALgADCgMJAwAAAA==.Baldsmon:BAAALgAECgUJBQAAAA==.Balimund:BAAALgAECgEJAQAAAA==.Ballerstatus:BAAALgAECgMJAwAAAA==.Ballsofaith:BAAALgADCgkJFAABLgAECgcJLgAMAB0cAA==.Ballsofire:BAABLgAECn8uAAIMAAcJHRxRFACsAQAMAAcJHRxRFACsAQAAAA==.Balstir:BAAALgADCgkJCQAAAA==.Basherz:BAAALgAECgQJBgAAAA==.',
Be='Bearmane:BAABLgAECn8VAAMPAAcJHB8VEgCZAQAPAAUJUSMVEgCZAQAQAAYJpxhXHwBSAQAAAA==.Beedoc:BAAALgADCgEJAQAAAA==.Behindithu:BAABLgAECn8pAAMRAAkJGhQ5CADKAQARAAgJgxQ5CADKAQASAAcJygfAOADuAAAAAA==.Belithel:BAABLgAECn8gAAIKAAkJqhcFdgDmAQAKAAkJqhcFdgDmAQAAAA==.Bencreepin:BAABLgAECn8jAAILAAcJ/BX5AAA7AQALAAcJ/BX5AAA7AQAAAA==.Beniz:BAACLgAFFH8FAAITAAMJ1wJUkwCbAAATAAMJ1wJUkwCbAAAuAAQKfyAAAxMACAkWCTyNACABABMACAmMCDyNACABABQAAgkFCcdaAF4AAAAA.Bernoulli:BAABLgAECn8fAAIVAAkJOhm/HwAdAgAVAAkJOhm/HwAdAgAAAA==.',
Bi='Bigblunts:BAAALgADCgEJAgAAAA==.Bigcrunch:BAAALgAECggJCQAAAA==.Bignative:BAAALgAECgYJCAAAAA==.Bigrockbiter:BAAALgAECgIJAgAAAA==.Bironic:BAAALgAECgYJDAABLgAECgcJIgASAHURAA==.',
Bl='Bloodbones:BAAALgADCgYJBgAAAA==.Bloodboo:BAAALgAECgQJBAAAAA==.Bloodyhpally:BAAALgAFFAIJAgABLgAFFAkJMQAVAG0dAA==.Bloodymyst:BAABLgAFFH8xAAIVAAkJbR14AACTAgAVAAkJbR14AACTAgAAAA==.Blumpy:BAAALgADCggJCAAAAA==.',
Bo='Boethius:BAAALgAECgMJBQABLgAECgkJEgABAAAAAA==.Boopsnoopems:BAABLgAECn8nAAIWAAgJ0RCzGwA5AQAWAAgJ0RCzGwA5AQAAAA==.Borderline:BAAALgADCgYJBgABLgAFFAYJHwAXAEwOAA==.Bounty:BAABLgAECn8XAAIYAAkJWBkPIgBcAgAYAAkJWBkPIgBcAgAAAA==.',
Br='Briannajade:BAABLgAECn8gAAIKAAgJygh4nABBAQAKAAgJygh4nABBAQAAAA==.Brisha:BAACLgAFFH8pAAIIAAgJkBu6BgBeAgAIAAgJkBu6BgBeAgAuAAQKfzMAAwgACQlIJHQAALUDAAgACQlIJHQAALUDABYAAQk8EhBPADQAAAAA.Brodan:BAAALgAECgQJBAAAAA==.Brokenhealz:BAAALgAECgcJEAAAAA==.',
Bs='Bs:BAAALgAECgYJBgABLgAFFAQJBwANAH8PAA==.',
Bu='Bubble:BAAALgADCgEJAgAAAA==.Bubblehash:BAAALgADCgEJAQAAAA==.Bubbletarded:BAAALgAECgUJBgAAAA==.Bustah:BAABLgAECn8eAAMYAAgJex24DgDFAgAYAAgJex24DgDFAgAZAAYJag3uTwAPAQABLgAFFAQJBwANAH8PAA==.',
Ca='Cacaco:BAAALgADCgIJAgAAAA==.Cactuscooler:BAAALgADCgcJBwAAAA==.Caffrey:BAABLgAECn8ZAAIJAAkJ1SKyAQCJAwAJAAkJ1SKyAQCJAwAAAA==.Calene:BAACLgAFFH8MAAIRAAQJxBJjBQApAQARAAQJxBJjBQApAQAuAAQKfxkAAhEABwliHLcIAL0BABEABwliHLcIAL0BAAAA.Cammi:BAABLgAECn8aAAIIAAYJKRozLgCkAQAIAAYJKRozLgCkAQAAAA==.Cammywammy:BAABLgAECn8fAAIFAAgJehbyKAAaAgAFAAgJehbyKAAaAgAAAA==.Candy:BAAALgAECgEJAQAAAA==.Carlyyrae:BAABLgAECn8sAAMFAAkJpRwWDAD6AgAFAAkJpRwWDAD6AgAOAAIJxwL6vgAfAAAAAA==.Casare:BAABLgAECn8gAAIZAAYJ8Q/EGADrAAAZAAYJ8Q/EGADrAAAAAA==.Catjam:BAABLgAFFH8GAAIDAAQJEyCrLQBZAQADAAQJEyCrLQBZAQABLgAFFAkJMQAaAOEhAA==.',
Ce='Celarc:BAAALgAECgYJDwAAAA==.Celithe:BAABLgAECn8cAAIbAAgJuw9rZgBaAQAbAAgJuw9rZgBaAQABLgAECgkJOwAKACgZAA==.Celyda:BAAALgADCgcJBwAAAA==.Cenarian:BAAALgADCgEJAQAAAA==.',
Ch='Chantriss:BAAALgAECgQJBAAAAA==.Chape:BAACLgAFFH8NAAIVAAYJWxCeHwByAQAVAAYJWxCeHwByAQAuAAQKfzkABBUACQnCIZ4GADkDABUACQnCIZ4GADkDAAcABglKGTEmAH0BABwABAlHGchEAOwAAAAA.Chapito:BAAALgAECgcJCAAAAA==.Chipmonked:BAABLgAECn9CAAQHAAkJlAygJgB6AQAHAAkJ1wugJgB6AQAcAAYJmQtVSgDYAAAVAAUJIwPLUACQAAAAAA==.Chlop:BAABLgAECn8ZAAINAAgJcBx0HADUAgANAAgJcBx0HADUAgAAAA==.Chochalinda:BAAALgAECgEJAwAAAA==.Chunkers:BAAALgAECgQJBAAAAA==.Chuubar:BAAALgADCgYJCwAAAA==.',
Ci='Cinderzin:BAABLgAECn84AAMdAAkJZAnaCgBtAQAdAAkJZAnaCgBtAQAaAAEJvwBYqQAHAAAAAA==.',
Cl='Clawhalla:BAAALgAECgcJEQAAAA==.',
Cn='Cnorthover:BAAALgAECgQJBAAAAA==.',
Co='Cobrallig:BAAALgAECggJDAAAAA==.Colexn:BAAALgAECgQJBAAAAA==.Comfyboi:BAAALgAECgcJDQAAAA==.Cong:BAABLgAFFH8LAAIeAAQJGhYcFwAnAQAeAAQJGhYcFwAnAQABLgAFFAYJHAAbAFAeAA==.Congdh:BAACLgAFFH8cAAIbAAYJUB5OCAChAQAbAAYJUB5OCAChAQAuAAQKfyUAAhsACQkPJMwKAPMCABsACQkPJMwKAPMCAAAA.Conmann:BAAALgAECgYJEgAAAA==.Corg:BAAALgADCgUJBQAAAA==.Cornchipz:BAAALgAECgMJAwAAAA==.Cowmage:BAAALgAECgEJAQAAAA==.',
Cr='Crit:BAAALgADCgcJCAABLgAECgkJHQAIACUNAA==.Crossy:BAAALgAECgQJBQAAAA==.Crusade:BAAALgAECgYJDgAAAA==.Cryogenic:BAAALgAECgYJEgAAAA==.Cryptex:BAAALgADCgEJAQAAAA==.',
Cy='Cyrus:BAAALgAECgcJDQAAAA==.',
Cz='Czznkj:BAAALgADCgkJDgAAAA==.',
['Cá']='Cálívént:BAABLgAECn8cAAIUAAkJfQ6xCwCEAQAUAAkJfQ6xCwCEAQAAAA==.',
Da='Daak:BAAALgAECgEJAQABLgAECgkJQgAHABUVAA==.Daangalangg:BAAALgAFFAIJAwAAAA==.Dabberoni:BAAALgAECgcJAQAAAA==.Dabthorne:BAAALgADCgEJAgAAAA==.Daegra:BAABLgAECn8UAAMRAAkJZBpCBgAHAgARAAYJtR1CBgAHAgASAAgJHg59JABxAQAAAA==.Daelin:BAAALgAECgEJAQAAAA==.Dankkush:BAACLgAFFH8IAAINAAQJaBHHfQALAQANAAQJaBHHfQALAQAuAAQKfxgAAg0ACQmxHhtDAPkBAA0ACQmxHhtDAPkBAAAA.Darkacedia:BAABLgAECn8jAAMTAAgJLh9bHQCmAgATAAgJLh9bHQCmAgAUAAMJyQ9aQwCoAAAAAA==.Darkrubie:BAAALgADCgMJAwAAAA==.Datbish:BAAALgAECgUJCAAAAA==.Dawgis:BAAALgAECgEJAQAAAA==.',
Db='Dbznz:BAAALgADCgYJBwAAAA==.',
De='Deadcell:BAABLgAECn8gAAMNAAcJPSH2NgAjAgANAAcJPSH2NgAjAgAfAAUJxiBBDwCBAQAAAA==.Deadcells:BAABLgAECn8UAAIeAAcJ+h0zEADuAQAeAAcJ+h0zEADuAQABLgAECgcJIAANAD0hAA==.Deadharvest:BAAALgAECgYJBwAAAA==.Deadlift:BAABLgAFFH8FAAINAAIJbxY11QCMAAANAAIJbxY11QCMAAAAAA==.Dealosed:BAACLgAFFH8OAAMRAAYJJQ50BQAoAQARAAUJmxF0BQAoAQASAAQJ+wkYDwD/AAAuAAQKfzQABBEACQkvI2gBAP0CABEACQm7ImgBAP0CABIABwnOIMoRAJECACAABgllHtwHALsBAAAA.Decrepit:BAABLgAECn8rAAINAAkJDBmfKQBaAgANAAkJDBmfKQBaAgAAAA==.Defect:BAAALgAECgQJBAAAAA==.Defy:BAAALgAECgMJBAAAAA==.Demonclawz:BAABLgAECn8VAAITAAgJGgwwcwBTAQATAAgJGgwwcwBTAQAAAA==.Demonscar:BAAALgAECgUJCwAAAA==.Deo:BAAALgAECggJCAAAAA==.Dex:BAAALgAECgEJAQAAAA==.',
Dh='Dhaeverdh:BAAALgADCgIJAgAAAA==.',
Di='Diddious:BAAALgADCgMJBQAAAA==.Diremane:BAAALgAECgIJAgAAAA==.Disastacast:BAAALgAECgMJAwABLgAFFAMJCAAfACAbAA==.Disastasmite:BAAALgADCgEJAQABLgAFFAMJCAAfACAbAA==.Dive:BAACLgAFFH8JAAIKAAQJTSCdRgBZAQAKAAQJTSCdRgBZAQAuAAQKfyUAAwoACQklIuwmANcCAAoACQlhHewmANcCACEABQnyHHwLAB8BAAAA.',
Dk='Dkeruu:BAAALgAECgUJCAAAAA==.',
Do='Doinks:BAABLgAECn8VAAIHAAkJkhwxDgCxAgAHAAkJkhwxDgCxAgAAAA==.Dondozo:BAAALgAECgUJCwAAAA==.Doogru:BAABLgAECn8uAAICAAkJDxc3GwAUAgACAAkJDxc3GwAUAgAAAA==.Doogtwo:BAAALgAECgcJDgABLgAECgkJLgACAA8XAA==.Doufu:BAAALgAECgQJBAABLgAECgYJDAABAAAAAA==.',
Dr='Dracomaibois:BAAALgAECgYJCwAAAA==.Dragonchape:BAAALgAECgEJAQAAAA==.Dragoneggs:BAACLgAFFH8TAAMaAAMJcxnnPgDMAAAaAAMJcxnnPgDMAAAiAAMJqQmyIgCNAAAuAAQKfycAAxoACQnaHuwIAOkCABoACQnaHuwIAOkCACIABwkZE6EaADABAAAA.Dragonforce:BAAALgAECgYJDAABLgAECgkJEQABAAAAAA==.Dratinì:BAAALgAECgEJAQABLgAECgEJAQABAAAAAA==.Draxan:BAAALgADCgcJCAAAAA==.Draxx:BAAALgAECgcJDgAAAA==.Dreammachine:BAABLgAECn8vAAIjAAkJ3CPtBQD0AgAjAAkJ3CPtBQD0AgAAAA==.Driipp:BAABLgAFFH8FAAICAAMJ3Br+KwAEAQACAAMJ3Br+KwAEAQAAAA==.Drizs:BAAALgADCgEJAQAAAA==.Drjoel:BAAALgADCgYJCAAAAA==.Drunkenutz:BAABLgAECn8tAAMVAAgJIRwVEwCEAgAVAAgJIRwVEwCEAgAHAAcJCxhiIACkAQABLgAECggJFAAFAIISAA==.',
Du='Duane:BAAALgADCgEJAQABLgAFFAYJHwAXAEwOAA==.Dundo:BAAALgAFFAIJAgABLgAFFAMJCQAOAD0XAA==.',
Dy='Dyab:BAAALgAECgEJAQAAAA==.',
['Dä']='Dälf:BAABLgAECn8cAAMPAAcJnCFlCwAKAgAPAAYJbiNlCwAKAgAJAAYJLRDfWABIAQABLgAFFAkJNQAdAIUcAA==.',
Ea='Eatinoreos:BAABLgAECn8UAAIkAAkJ/BuaCwCbAgAkAAkJ/BuaCwCbAgAAAA==.',
Ec='Echidona:BAABLgAECn8bAAISAAgJERn8EwB2AgASAAgJERn8EwB2AgAAAA==.',
Ed='Edirii:BAAALgADCgEJAQAAAA==.',
Ee='Eelsky:BAAALgAECgcJEgAAAA==.',
Ef='Efvoidhunter:BAAALgAECgUJBQAAAA==.',
Ek='Eksi:BAEALgAECgQJBAABLgAFFAYJFQATAP8jAA==.',
El='Elenix:BAABLgAECn8aAAMOAAkJyRy0CAAGAwAOAAkJyRy0CAAGAwAFAAMJhA3zgACQAAABLgAFFAMJBgAIABghAA==.Elinras:BAACLgAFFH8QAAIDAAMJgQxiCwBzAAADAAMJgQxiCwBzAAAuAAQKfywAAgMACQkfGswBAIEBAAMACQkfGswBAIEBAAAA.Elliott:BAAALgADCgMJBQABLgADCggJDQABAAAAAA==.Elmesia:BAAALgAECggJAQAAAA==.Elonsalt:BAAALgAECgcJEAAAAA==.Eloris:BAABLgAECn8WAAIbAAgJfxQ2RQC3AQAbAAgJfxQ2RQC3AQAAAA==.Elrizon:BAAALgAECgYJCwAAAA==.Elvar:BAAALgAECggJDwABLgAECgQJBQABAAAAAA==.Elwynbria:BAAALgADCgcJBwAAAA==.Elynith:BAAALgAECgIJBAAAAA==.Elynni:BAABLgAECn8dAAIGAAcJ2RUIIADhAQAGAAcJ2RUIIADhAQAAAA==.',
Em='Emmylou:BAAALgAECgEJAwAAAA==.Emotett:BAAALgADCgQJBAAAAA==.Emz:BAACLgAFFH8KAAIgAAMJVR9cCAD6AAAgAAMJVR9cCAD6AAAuAAQKfysAAiAACAlqIuUAAAwDACAACAlqIuUAAAwDAAAA.',
En='Endboss:BAAALgAECgUJBQAAAA==.Enfuega:BAAALgAECgQJDQAAAA==.Eniar:BAACLgAFFH8MAAIIAAUJUAYzJQD4AAAIAAUJUAYzJQD4AAAuAAQKfxwAAwgACAnHFLguAMgBAAgACAnHFLguAMgBAAMABAl0CTDvALIAAAAA.',
Er='Eroninja:BAAALgAECgQJCAABLgAECgkJIAAKAKoXAA==.',
Eu='Eurong:BAACLgAFFH8UAAIkAAYJuBfyFAB0AQAkAAYJuBfyFAB0AQAuAAQKfxsAAiQACAl0H0waADICACQACAl0H0waADICAAAA.',
Ev='Evangelune:BAABLgAECn8XAAIKAAgJHALR6gDLAAAKAAgJHALR6gDLAAAAAA==.Evral:BAAALgAECgcJBwAAAA==.',
Ew='Ewright:BAAALgAECgEJAQABLgAECggJGAAjADwfAA==.',
Ez='Ezynuff:BAABLgAECn8vAAMFAAkJ2hisGgB1AgAFAAkJ2hisGgB1AgAOAAUJKQgecQCXAAAAAA==.',
['Eï']='Eïr:BAAALgADCgcJCAAAAA==.',
Fa='Fakie:BAAALgAECgQJBAABLgAECgYJFAATACIfAA==.Fapple:BAABLgAECn8lAAMJAAgJxxnkHQBXAgAJAAgJxxnkHQBXAgAkAAcJPxW8KQCFAQABLgAECgkJPgAiACkkAA==.Fatesprocket:BAAALgAECgMJBQAAAA==.Faïry:BAACLgAFFH8cAAMYAAYJWxxrGACnAQAYAAYJzBtrGACnAQAlAAMJTwuwJACtAAAuAAQKfzMAAxgACQkxHcoRAKoCABgACAmpH8oRAKoCACUABgkUCjYjALYAAAAA.',
Fe='Feardih:BAAALgADCgIJAgAAAA==.Felfrostette:BAAALgAECgEJAQAAAA==.Felheart:BAABLgAECn8YAAImAAgJ6BOFGgCrAQAmAAgJ6BOFGgCrAQAAAA==.Feltnutz:BAAALgADCgQJBQABLgAECggJFAAFAIISAA==.Felwyrm:BAAALgAECgYJDAABLgAFFAYJHwAXAEwOAA==.Femboi:BAAALgADCgUJBQAAAA==.Fengshui:BAABLgAFFH8GAAIJAAIJuQ0kWABpAAAJAAIJuQ0kWABpAAAAAA==.Feralle:BAAALgADCgQJBAAAAA==.',
Fl='Flacidmon:BAAALgAECgcJCgAAAA==.Flutterina:BAAALgAECgIJAgAAAA==.Flyjin:BAABLgAECn8dAAMiAAgJEQ5pJABVAQAiAAcJLgxpJABVAQAaAAgJJg5CPgAxAQAAAA==.Flylo:BAAALgADCgMJAwAAAA==.',
Fo='Folandras:BAAALgADCgcJDAABLgAECgcJLgAMAB0cAA==.Forrestpump:BAAALgADCgMJAwAAAA==.',
Fr='Fries:BAECLgAFFH8HAAITAAQJpg+cZQD7AAATAAQJpg+cZQD7AAAuAAQKfyQAAxMACAkDJKEUAKoCABMACAkDJKEUAKoCABQAAQmHGhtgAE8AAAEuAAUUBQkKAAQA/x4A.Frozenpyre:BAAALgAECgYJEQAAAA==.',
Fu='Funch:BAACLgAFFH8MAAIUAAMJFg/9DADQAAAUAAMJFg/9DADQAAAuAAQKfzQAAhQACQk8G3cDAF8CABQACQk8G3cDAF8CAAAA.',
['Fè']='Fènrir:BAAALgAECgYJCAABLgAECggJGAAjADwfAA==.',
Ga='Gabbathegoo:BAACLgAFFH8IAAMTAAYJNQotfQDKAAATAAUJ+wstfQDKAAAUAAEJHQOMKgA9AAAuAAQKfxYAAxMACQl3HVkYAJICABMACQl3HVkYAJICABQAAQkAAA9UAAAAAAAA.Gainz:BAAALgAFFAMJAwAAAA==.Gainzz:BAAALgAECgQJBgAAAA==.Galesdeyn:BAABLgAECn8WAAIbAAcJQhdVWQB7AQAbAAcJQhdVWQB7AQAAAA==.Garl:BAAALgAECgUJBQABLgAECgcJFAAKAD4dAA==.Garonnaa:BAABLgAFFH8PAAILAAUJRAkhJgDBAAALAAUJRAkhJgDBAAAAAA==.',
Gh='Ghari:BAABLgAECn8oAAINAAgJpROigQBgAQANAAgJpROigQBgAQAAAA==.',
Gi='Gilrog:BAABLgAECn8bAAINAAcJDA+CmwAzAQANAAcJDA+CmwAzAQAAAA==.Gingerlock:BAAALgAECgUJCgAAAA==.',
Gl='Gladiusmax:BAAALgADCgQJBAAAAA==.Gloryseeker:BAAALgAECgEJAQAAAA==.',
Gn='Gnoblin:BAAALgAECgQJCAAAAA==.Gnzz:BAAALgAECgcJDAAAAA==.',
Go='Gonz:BAAALgADCgcJBwAAAA==.Gorerich:BAAALgADCgIJAgAAAA==.',
Gr='Gravys:BAAALgAECgcJAwAAAA==.Greka:BAABLgAECn87AAIOAAkJpBIRIwDNAQAOAAkJpBIRIwDNAQAAAA==.Greyer:BAAALgAFFAMJBAABLgAFFAMJCwAeALsiAA==.Greylooms:BAACLgAFFH8LAAMeAAMJuyKqGwANAQAeAAMJuyKqGwANAQACAAEJHRj9UQBHAAAuAAQKfzIAAx4ACQkwIVsDAPwCAB4ACQkwIVsDAPwCAAIABgmEHekyAOABAAAA.Gruuith:BAAALgADCgEJAQAAAA==.',
Gw='Gwath:BAAALgAECgEJAQAAAA==.',
Gy='Gynaris:BAAALgAECgMJBQAAAA==.',
['Gâ']='Gâinzz:BAAALgADCgQJBAAAAA==.',
Ha='Hakun:BAAALgAECgMJAwAAAA==.Hammerdon:BAAALgAECgEJAQAAAA==.Happyfriend:BAACLgAFFH8fAAMXAAYJTA6pIABMAQAXAAYJTA6pIABMAQAjAAEJZABAQgAvAAAuAAQKfysABBcACQn1GA8bAPcBABcACQn1GA8bAPcBACMABwmiEX8kALQBAAYAAQkPCj92ACQAAAAA.Haruko:BAAALgADCgQJBAAAAA==.',
He='Heemski:BAAALgAECgMJAwAAAA==.Hellaholy:BAAALgADCgYJBgAAAA==.Hellbourne:BAAALgADCggJDQAAAA==.Hellbrick:BAAALgADCgMJAwAAAA==.Hermitpurple:BAAALgADCgcJEwABLgAECgkJHQAIACUNAA==.Heàl:BAABLgAECn8YAAMjAAgJPB9cDgBwAgAjAAgJPB9cDgBwAgAXAAEJFgcQgwApAAAAAA==.',
Hi='Hidejames:BAABLgAECn8yAAMRAAkJbxjhAwBnAgARAAkJbxjhAwBnAgASAAMJEQaMVQBSAAAAAA==.Hidolo:BAAALgAECgMJAwAAAA==.Hims:BAABLgAECn8ZAAMbAAYJFiEYNwAaAgAbAAYJFiEYNwAaAgAnAAEJtRxSKABFAAABLgAFFAkJMQAaAOEhAA==.',
Ho='Hoguy:BAAALgAECgYJEAAAAA==.Holofox:BAACLgAFFH8lAAIJAAgJNxr7BADHAgAJAAgJNxr7BADHAgAuAAQKf00AAwkACQlFJs8AANwDAAkACQlFJs8AANwDAA8ABQkXDmkrALoAAAAA.Holycrow:BAAALgAECgMJAwAAAA==.Holytotem:BAAALgADCgEJAQAAAA==.Horman:BAABLgAECn8WAAIcAAYJmwt4VgC0AAAcAAYJmwt4VgC0AAAAAA==.',
Hu='Hunterishard:BAAALgAECggJEAABLgAECgkJEgABAAAAAA==.',
Hy='Hylda:BAAALgAECgMJBgAAAA==.',
['Hï']='Hïru:BAAALgAECgYJCAAAAA==.',
['Hô']='Hôlÿ:BAAALgAECgQJCQABLgAECgkJDwABAAAAAA==.',
Ic='Iclapu:BAAALgAECgEJAgABLgAECgkJMQAHADAdAA==.',
Ig='Iggz:BAAALgADCgkJCQABLgAECgkJQgAHABUVAA==.Ignia:BAAALgADCgYJCgABLgAECgkJQgAHABUVAA==.Igosduikanna:BAAALgADCgQJBQAAAA==.',
Ik='Ikerous:BAABLgAECn8bAAMnAAgJ3RkwBwAWAgAnAAgJ3RkwBwAWAgAmAAMJ1AmTVgCNAAAAAA==.',
Il='Ilililililli:BAABLgAECn8cAAMVAAgJ0RexRgBRAQAVAAgJ0RexRgBRAQAcAAIJdgjrhQBNAAAAAA==.Illinelf:BAAALgADCgYJBgABLgAECgcJFQAPABwfAA==.Illumi:BAAALgAECgEJAQAAAA==.',
Im='Imadwagon:BAAALgADCgkJCAAAAA==.Imapandairl:BAABLgAECn8VAAIOAAcJrR6CEgCOAgAOAAcJrR6CEgCOAgAAAA==.Imfubar:BAAALgAECgMJAwAAAA==.Imhammered:BAABLgAECn8pAAIIAAgJ+BL4IQD0AQAIAAgJ+BL4IQD0AQAAAA==.Impullse:BAABLgAFFH8FAAIFAAIJ7QSObwBeAAAFAAIJ7QSObwBeAAAAAA==.',
Ir='Ironpally:BAAALgAECgYJBwAAAA==.Irsty:BAAALgAECgEJAQABLgAFFAYJDAAaAL8XAA==.',
It='Ithilwen:BAABLgAECn8vAAIXAAkJyB2tCADpAgAXAAkJyB2tCADpAgAAAA==.Itiswhatitiz:BAABLgAECn8dAAIYAAYJ3BmdZwB0AQAYAAYJ3BmdZwB0AQAAAA==.Itsybityshiv:BAACLgAFFH8OAAISAAQJJBxRFgBaAQASAAQJJBxRFgBaAQAuAAQKfzYAAxIACQmbHdYKAHcCABIACQmbHdYKAHcCABEAAQmgGPQfADMAAAAA.',
Iw='Iwillpull:BAAALgADCgcJDgAAAA==.',
Iz='Izzlirkkgazp:BAAALgAECgcJDgAAAA==.',
Ja='Jackiefox:BAAALgAECgIJBAAAAA==.Jahq:BAABLgAECn8VAAIbAAYJAyF8NAAnAgAbAAYJAyF8NAAnAgAAAA==.Jakarr:BAAALgAECgIJAgAAAA==.Jambs:BAAALgADCgEJAQAAAA==.Jandaelia:BAAALgAECgEJAQAAAA==.Jaysontatum:BAAALgAECgEJAQAAAA==.',
Je='Jeabuss:BAAALgADCgkJFQAAAA==.',
Jh='Jhani:BAABLgAECn8ZAAIKAAkJLwSzowA1AQAKAAkJLwSzowA1AQAAAA==.',
Ji='Jixn:BAAALgAECgMJBQAAAA==.',
Jo='Joethemage:BAABLgAECn8wAAIKAAkJASEWGgC9AgAKAAkJASEWGgC9AgAAAA==.Joobles:BAAALgAECgEJAQABLgAECgkJMQAHADAdAA==.Jormojo:BAAALgAECgQJBgAAAA==.Jotwnky:BAABLgAECn8eAAQoAAcJAyC3BQAMAgAoAAUJSSO3BQAMAgAUAAQJsxo7IwA+AQATAAMJGB9WuADoAAAAAA==.Jotwnkyy:BAACLgAFFH8JAAISAAQJAhMnHQA1AQASAAQJAhMnHQA1AQAuAAQKfzIAAhIABwkiILsUAPsBABIABwkiILsUAPsBAAEuAAQKBwkeACgAAyAA.',
Ju='Jungol:BAAALgAECgIJAgAAAA==.',
Ka='Kaela:BAAALgAECgEJAQAAAA==.Kaikova:BAAALgADCgcJCgAAAA==.Kaliban:BAAALgAECgQJBAAAAA==.Kaltank:BAAALgAECggJAwAAAA==.Kamin:BAABLgAECn8jAAIMAAgJwiHjAwARAwAMAAgJwiHjAwARAwAAAA==.Karoka:BAAALgADCgEJAQAAAA==.Kasitos:BAABLgAECn8UAAMTAAgJhxkkdQBPAQATAAgJhxkkdQBPAQAUAAEJnxEdbQA6AAAAAA==.Katamaran:BAAALgAFFAMJBAABLgAFFAYJFgAjAOwQAA==.Kaykaypally:BAABLgAECn8fAAIDAAkJbhI7VwDGAQADAAkJbhI7VwDGAQAAAA==.',
Ke='Keis:BAEALgAECgYJBgABLgAFFAYJFQATAP8jAA==.Keledron:BAAALgADCgcJCgAAAA==.Kellan:BAABLgAECn80AAMDAAcJ+hiAbgCRAQADAAcJ+hiAbgCRAQAIAAQJah12PABVAQAAAA==.Kelos:BAAALgAECgYJCAABLgAFFAEJAgABAAAAAA==.Keylethel:BAAALgADCgEJAQAAAA==.',
Ki='Kideki:BAABLgAECn8nAAIIAAkJSyJsCgDlAgAIAAkJSyJsCgDlAgAAAA==.Kidori:BAAALgAECgEJAQABLgAECgkJJwAIAEsiAA==.Killakevv:BAAALgAECgEJAQAAAA==.Kinji:BAAALgADCgYJCAABLgAECgkJIAAKAKoXAA==.Kirisute:BAAALgAECgEJAQAAAA==.Kittycatmeow:BAAALgADCgUJBQAAAA==.',
Ko='Kolsch:BAAALgADCgQJBAAAAA==.Koopa:BAAALgAECgQJCAABLgAECgkJHQAIACUNAA==.Koriandar:BAABLgAECn83AAIKAAgJ/AxogQB1AQAKAAgJ/AxogQB1AQAAAA==.Koyama:BAAALgADCgcJBwAAAA==.',
Kr='Kristysavage:BAABLgAECn9EAAMlAAkJuyCjBwCkAgAlAAkJuyCjBwCkAgAYAAEJQCLK+gBlAAAAAA==.Krul:BAAALgADCgkJCgAAAA==.Kruya:BAAALgAECgMJBAABLgAECgcJIgASAHURAA==.',
Ku='Kulaesca:BAAALgAECgIJAgAAAA==.Kuru:BAAALgAECgMJAwAAAA==.',
Ky='Kynar:BAACLgAFFH8iAAMNAAgJUBzGGAAbAgANAAcJUBzGGAAbAgALAAUJDhFkIADlAAAuAAQKfxcAAg0ACAkuH60/ADoCAA0ACAkuH60/ADoCAAAA.Kyperion:BAAALgAECgYJDQAAAA==.Kyrieirving:BAAALgAECgEJAQABLgAECgEJAQABAAAAAA==.Kyua:BAABLgAECn8VAAImAAcJFAjuNADrAAAmAAcJFAjuNADrAAAAAA==.',
La='Lambshot:BAABLgAECn8dAAMYAAcJ/CAeQgDcAQAYAAcJ/CAeQgDcAQAZAAEJ/AahjwArAAAAAA==.Lambsy:BAACLgAFFH8vAAQCAAkJZhV7AAAFAgACAAgJABd7AAAFAgAeAAEJYAUOQwBBAAAMAAEJpAgfLQA7AAAuAAQKfx4AAwIACAmrIBARAMgCAAIACAl4HhARAMgCAB4AAQnuI0A5AEsAAAAA.Landwhalexxl:BAABLgAECn8XAAIKAAcJ9BGOpACPAQAKAAcJ9BGOpACPAQAAAA==.Laneera:BAAALgAECgQJDgAAAA==.',
Le='Leap:BAAALgAECgEJAQAAAA==.Ledronys:BAAALgADCgEJAQAAAA==.Ledsole:BAAALgADCgEJAQAAAA==.Lerat:BAABLgAECn8wAAIdAAkJ+iHMAQDJAgAdAAkJ+iHMAQDJAgAAAA==.',
Li='Lichkali:BAAALgADCgMJAwAAAA==.Liegh:BAAALgAECgQJBQAAAA==.Lightofhope:BAABLgAECn8fAAQjAAgJexG7LgBlAQAjAAgJexG7LgBlAQAXAAUJnwbWOADgAAAGAAIJyQZtegAfAAAAAA==.Lihandra:BAAALgAECgYJCgAAAA==.Lillipup:BAAALgAECgQJBAAAAA==.Lillyy:BAAALgAECgIJAgABLgAFFAMJDAAKACgcAA==.Lilyy:BAACLgAFFH8MAAIKAAMJKByRbQAIAQAKAAMJKByRbQAIAQAuAAQKfycAAgoACQmIIFkPAAADAAoACQmIIFkPAAADAAAA.Liria:BAAALgAECgYJDQAAAA==.Lisanalgaib:BAABLgAECn8ZAAIDAAgJlRfdWQC/AQADAAgJlRfdWQC/AQAAAA==.Liulei:BAAALgAECgQJAwAAAA==.Livelyjoker:BAAALgADCgMJAgAAAA==.Lizzimcguire:BAAALgAFFAEJAQABLgAFFAIJAgABAAAAAA==.',
Lo='Loharfal:BAAALgADCgcJCAAAAA==.Loksham:BAAALgAECgkJEQAAAA==.Lokî:BAAALgAECgQJBAAAAA==.Loraen:BAABLgAECn8mAAIKAAgJLA17hgBqAQAKAAgJLA17hgBqAQAAAA==.Lorelei:BAAALgAECgEJAQABLgAECgkJJAAeABkbAA==.Lostep:BAABLgAFFH8IAAIGAAQJKQThIACzAAAGAAQJKQThIACzAAABLgAFFAgJIgAFAI0bAA==.Lowkeyjz:BAAALgADCgIJAgAAAA==.',
Lu='Luasa:BAAALgADCgIJAgAAAA==.Lukadoncic:BAABLgAECn8bAAMVAAcJaRMIOQCNAQAVAAcJaRMIOQCNAQAcAAMJ2Q0iewBcAAABLgAECgEJAQABAAAAAA==.Lunarmon:BAAALgAECgUJDgAAAA==.Lunchable:BAABLgAECn8eAAIOAAgJnhmJFgBlAgAOAAgJnhmJFgBlAgAAAA==.Luxmalleo:BAAALgADCgkJDwABLgAECgcJIgASAHURAA==.',
Ly='Lykho:BAAALgAECgEJAQAAAA==.',
['Lè']='Lèa:BAAALgAECgEJAQABLgAECggJGAAjADwfAA==.',
['Lé']='Léblanc:BAABLgAECn8oAAIKAAkJ/x2DRAAOAgAKAAkJ/x2DRAAOAgAAAA==.',
Ma='Madam:BAAALgADCgMJBwAAAA==.Madday:BAAALgADCgcJDAAAAA==.Maelorus:BAAALgADCgkJEQAAAA==.Magicaltoast:BAAALgAECgcJEQAAAA==.Mahli:BAAALgAECgEJAQAAAA==.Makah:BAAALgAECgMJAwAAAA==.Makizenin:BAAALgADCgcJDwAAAA==.Malenia:BAAALgADCgUJBwAAAA==.Malthezar:BAAALgADCgEJAQAAAA==.Manticus:BAAALgADCgYJEAAAAA==.Maraud:BAAALgADCgEJAQAAAA==.Mari:BAAALgAECgMJBQABLgAFFAMJFQAGAAYlAA==.Matroxx:BAABLgAECn8VAAMcAAcJSRoUMgA+AQAcAAQJex4UMgA+AQAVAAcJfBA7MwAnAQABLgAFFAYJLQAEANYaAA==.',
Me='Meat:BAAALgAECgUJBQAAAA==.Meatballz:BAAALgADCgEJAQAAAA==.Meatbeef:BAAALgADCgEJAQAAAA==.Meenoi:BAACLgAFFH8HAAINAAQJfw9KfQAMAQANAAQJfw9KfQAMAQAuAAQKfysAAg0ACAnQIWYmAKICAA0ACAnQIWYmAKICAAAA.Megamaid:BAAALgAECgYJCgAAAA==.Melysia:BAACLgAFFH8hAAIJAAcJgBuACgBMAgAJAAcJgBuACgBMAgAuAAQKfzoAAwkACQl0IP8MANQCAAkACQl0IP8MANQCAA8AAgmmCdZJAEYAAAAA.',
Mi='Miadas:BAAALgAFFAEJAQABLgAFFAMJBgAPAJQaAA==.Midgeyfam:BAAALgAECgIJAgAAAA==.Midgeyzen:BAAALgAECgQJBAAAAA==.Mika:BAAALgAFFAEJAQABLgAFFAMJFQAGAAYlAA==.Mindi:BAAALgAECgMJAwAAAA==.Mizakina:BAAALgAECgEJAQAAAA==.Mizby:BAAALgADCgIJAwABLgADCgMJAwABAAAAAA==.Mizry:BAAALgADCgMJAwAAAA==.',
Mk='Mk:BAAALgAECgIJAgABLgAFFAMJFQAGAAYlAA==.',
Mo='Moardotsnow:BAABLgAECn8oAAMTAAkJ4ST5PADoAQATAAUJ9iT5PADoAQAUAAQJvSRYEgAkAQAAAA==.Moby:BAABLgAECn8gAAMoAAgJ9Aa1AQCFAAATAAgJFwWGqwDsAAAoAAYJNge1AQCFAAAAAA==.Moistmender:BAAALgAECgkJEgAAAA==.Moonleaf:BAAALgAECgkJAwAAAA==.Moosaki:BAAALgAECgkJCQABLgAECgkJMgASAIwjAA==.Mortui:BAABLgAECn8WAAImAAgJBCCoCQCPAgAmAAgJBCCoCQCPAgABLgAFFAYJLQAEANYaAA==.Mous:BAAALgADCgMJAwAAAA==.',
Mu='Muffasah:BAAALgAECgEJAQAAAA==.Munchkinn:BAAALgADCgYJBgAAAA==.Murbella:BAAALgADCgEJAQABLgAECgcJGAAbAIMiAA==.Murridan:BAABLgAECn8pAAIbAAkJoiKUCQA7AwAbAAkJoiKUCQA7AwAAAA==.',
My='Mykaela:BAABLgAECn8lAAMDAAcJgw7LBwCMAAAWAAcJDAuqKADSAAADAAQJCQjLBwCMAAAAAA==.Myraela:BAAALgAECgYJEgABLgAECgkJIAALAEshAA==.',
['Më']='Mëow:BAABLgAECn80AAIQAAkJOQZLMgDgAAAQAAkJOQZLMgDgAAAAAA==.',
Na='Narrath:BAAALgAECgMJBQAAAA==.Nayalaah:BAABLgAECn8lAAIYAAcJOBJsAwAiAQAYAAcJOBJsAwAiAQAAAA==.',
Ne='Nehpets:BAAALgAECgMJAwAAAA==.Nellybearwl:BAAALgADCgYJBgAAAA==.Nephelym:BAAALgAECgMJAwAAAA==.Nerfherder:BAAALgAECgQJBQAAAA==.Nexes:BAAALgAECgUJBwAAAA==.',
Ni='Nicotinee:BAAALgAECgMJAwAAAA==.Nightbané:BAAALgAECgIJBQAAAA==.Nirina:BAABLgAECn8nAAIYAAgJ3gYYogD9AAAYAAgJ3gYYogD9AAAAAA==.Nixie:BAAALgAECgYJBgAAAA==.',
Nn='Nnuiq:BAAALgAECgIJAwAAAA==.',
No='Nojaw:BAAALgADCgcJBwAAAA==.Noraeri:BAAALgAECgYJBgABLgAECgkJIAAKAKoXAA==.Northsouth:BAAALgAECgEJAgAAAA==.Notdicey:BAAALgAFFAIJAgAAAA==.Notstephen:BAAALgAECgUJCgAAAA==.Novo:BAAALgAECgYJCwAAAA==.',
Nu='Nukefury:BAABLgAECn8nAAMEAAkJTCFYAwDSAgAEAAkJMB5YAwDSAgAOAAYJZyR0GgBAAgABLgAFFAMJCAAfACAbAA==.',
['Ný']='Nýks:BAAALgAECgEJAQAAAA==.',
Od='Oddstriker:BAAALgADCgYJAwAAAA==.',
Oi='Oiflar:BAAALgAECgcJDwABLgAECgkJPgAiACkkAA==.',
Ol='Oliveoil:BAAALgADCgEJAQAAAA==.',
Om='Omnidh:BAACLgAFFH8ZAAIbAAYJhBV0LAB1AQAbAAYJhBV0LAB1AQAuAAQKfyQAAhsACQliIKwPAAEDABsACQliIKwPAAEDAAAA.Omnihead:BAAALgADCgYJBgAAAA==.',
On='Onepavo:BAAALgAECgcJCQAAAA==.Onlybakshots:BAAALgAECgYJCAAAAA==.',
Op='Oppose:BAAALgAECgYJEgAAAA==.',
Or='Orestes:BAAALgAFFAEJAQAAAA==.Orexion:BAABLgAECn8iAAMCAAkJpA0ENgBwAQACAAkJTw0ENgBwAQAeAAYJ8gtFNwDoAAAAAA==.Ormagöden:BAABLgAECn8oAAIfAAkJMhSMAwBPAgAfAAkJMhSMAwBPAgAAAA==.',
Ov='Ovakill:BAAALgADCgEJAQAAAA==.',
Oz='Ozzpoxzo:BAAALgAECgUJCwAAAA==.',
Pa='Palladean:BAABLgAECn8zAAIDAAkJFxdCPAATAgADAAkJFxdCPAATAgAAAA==.Pandemic:BAAALgAECgMJAwAAAA==.Parabow:BAAALgAECgMJAwAAAA==.Parador:BAAALgAECgIJAQABLgAECgMJAwABAAAAAA==.Pastasauce:BAABLgAECn8dAAIDAAcJtg6bhwBrAQADAAcJtg6bhwBrAQAAAA==.',
Pc='Pcpmlsd:BAAALgADCgkJDAAAAA==.',
Pe='Penelohpe:BAAALgAECgcJCgABLgAECggJIwAMAMIhAA==.Penwork:BAAALgAECggJCwAAAA==.Penz:BAABLgAECn8ZAAINAAYJfRuvZgCZAQANAAYJfRuvZgCZAQAAAA==.Perrian:BAAALgADCgMJBAAAAA==.Petey:BAAALgADCgEJAgAAAA==.',
Ph='Phamine:BAAALgAECgMJAwAAAA==.Phatt:BAAALgAECgEJAQAAAA==.Philex:BAEALgAECgYJBwABLgAFFAYJFQATAP8jAA==.Phoenixfyre:BAAALgAECgcJBwAAAA==.Phoon:BAECLgAFFH8VAAITAAYJ/yPYIADNAQATAAYJ/yPYIADNAQAuAAQKfyEABBMACAmoHkMdAKYCABMACAmoHkMdAKYCABQAAglGGVVJAJIAACgAAQkAAKAqAEoAAAAA.Phøenixbane:BAABLgAECn8hAAIDAAgJxh43KQBdAgADAAgJxh43KQBdAgAAAA==.',
Pi='Piggy:BAAALgAECgEJAgAAAA==.Pita:BAAALgAECgcJCwAAAA==.Pitaya:BAAALgAECgcJEwAAAA==.',
Pl='Plaguefist:BAAALgAECgkJEQAAAA==.Plata:BAAALgAECgcJCgAAAA==.Plikxy:BAAALgADCgkJCQAAAA==.Plumsàuce:BAAALgAECgEJAQAAAA==.',
Po='Pocketmage:BAAALgAECgQJBQAAAA==.Pompous:BAAALgAECgEJAQAAAA==.',
Pr='Praytroxx:BAAALgAECgYJCgABLgAFFAYJLQAEANYaAA==.Premonitions:BAABLgAECn8fAAIFAAgJVBTLPQC3AQAFAAgJVBTLPQC3AQAAAA==.Premune:BAABLgAECn84AAQIAAkJ6x9cDQCuAgAIAAkJ6x9cDQCuAgAWAAgJ+RCQGQBNAQADAAIJOgioGwFjAAAAAA==.Preparation:BAAALgAECgQJBAABLgAFFAQJDAARAMQSAA==.Prion:BAACLgAFFH8NAAIbAAQJ8w89RQAYAQAbAAQJ8w89RQAYAQAuAAQKfxkAAhsACAklFEJTAIwBABsACAklFEJTAIwBAAAA.',
Ps='Psycs:BAAALgAECgYJDgAAAA==.',
Pu='Pulga:BAAALgADCgIJAgAAAA==.Pull:BAAALgADCgcJCQABLgAFFAQJCQAKAE0gAA==.Purplemage:BAAALgAECgkJDQABLgAECgkJEgABAAAAAA==.',
Pw='Pwincess:BAAALgADCgMJAwAAAA==.',
['Pú']='Púre:BAAALgAECgIJAgAAAA==.',
Qu='Quigly:BAAALgAECgYJCgAAAA==.Quìts:BAABLgAECn8mAAMTAAgJSB2FOgAiAgATAAgJrhuFOgAiAgAUAAMJzRezJQCGAAAAAA==.Quíts:BAAALgADCgEJAQABLgAECggJJgATAEgdAA==.',
Ra='Radeøn:BAAALgAECgEJAQAAAA==.Ragingtauren:BAAALgAECgMJBwAAAA==.Rainbowdots:BAAALgAECgcJDgAAAA==.Raine:BAACLgAFFH8iAAIFAAgJjRshAAChAgAFAAgJjRshAAChAgAuAAQKfx4AAwUACAkhHysfACQCAAUACAkhHysfACQCAA4ABAkKGWlVAPAAAAAA.Raistlain:BAAALgAECgcJEwAAAA==.Raistlin:BAABLgAECn8gAAMmAAkJ7Bb9FADnAQAmAAkJ7Bb9FADnAQAbAAEJywOo8AAiAAAAAA==.Ralfio:BAABLgAECn8+AAIiAAkJKSQgAQCeAwAiAAkJKSQgAQCeAwAAAA==.Ralfiosky:BAAALgAECggJEwABLgAECgkJPgAiACkkAA==.Ramennoodlez:BAAALgAECgQJBAAAAA==.Rat:BAAALgAFFAIJAgABLgAFFAUJCQAfAAAgAA==.Ratren:BAAALgADCgQJAwAAAA==.Ravalyn:BAAALgADCgkJCgAAAA==.Raynith:BAACLgAFFH8GAAMPAAMJlBq/DADrAAAPAAMJlBq/DADrAAAQAAIJnwhKNgBLAAAuAAQKfysABA8ACQn6GzEKAB4CAA8ABwkjITEKAB4CACQABwlPGNklAJ0BABAACAnDEakeAFgBAAAA.',
Re='Readycheck:BAABLgAECn8yAAMkAAkJoBlLAABVAgAkAAkJlhlLAABVAgAQAAgJyQ8yIwA2AQAAAA==.Reckalossi:BAAALgAECgkJAQABLgAFFAMJEAADAIEMAA==.Redcows:BAAALgAECgUJBQAAAA==.Redeemed:BAAALgADCgEJAQAAAA==.Reikon:BAABLgAECn8iAAIDAAgJzB1pNQBNAgADAAgJzB1pNQBNAgAAAA==.Remulous:BAABLgAECn8VAAIYAAcJyQipqwDsAAAYAAcJyQipqwDsAAAAAA==.Revelaen:BAACLgAFFH8RAAIaAAUJRhDhMgD2AAAaAAUJRhDhMgD2AAAuAAQKfyMAAxoACQlxHQ0JAOcCABoACQlxHQ0JAOcCAB0ABQlYBowoANwAAAAA.',
Ri='Rick:BAACLgAFFH8iAAMYAAUJAiYDGACqAQAYAAUJAiYDGACqAQAZAAEJXBoLJQBUAAAuAAQKfysAAxgACQmkI5wOANwCABkACAlpI+QJAAUDABgACQlqI5wOANwCAAAA.Rickers:BAAALgAECgMJAwABLgAFFAUJIgAYAAImAA==.Rikosan:BAAALgAECgEJAwAAAA==.',
Ro='Roarz:BAAALgADCgkJCQAAAA==.Rollthebones:BAAALgADCgMJAwAAAA==.Roman:BAABLgAECn8hAAMIAAYJayW1FABoAgAIAAYJayW1FABoAgADAAQJnRkyrQAoAQABLgAFFAYJDQAiAH8kAA==.Roonoa:BAAALgAECgQJBAAAAA==.Roust:BAAALgAECgUJBQABLgAFFAQJCQAKAE0gAA==.',
Ru='Runinfear:BAAALgADCgYJBgAAAA==.',
Sa='Saba:BAAALgAECgMJBAAAAA==.Saephora:BAABLgAECn85AAIKAAkJtwYtigBjAQAKAAkJtwYtigBjAQAAAA==.Saerea:BAACLgAFFH8IAAINAAMJNBktkwDmAAANAAMJNBktkwDmAAAuAAQKfyAAAg0ACAkuH30zAGkCAA0ACAkuH30zAGkCAAAA.Saggypants:BAAALgAFFAIJAgAAAA==.Sahhm:BAABLgAFFH8KAAIDAAMJ+SDzBwC7AAADAAMJ+SDzBwC7AAAAAA==.Salali:BAAALgAECgQJBwAAAA==.Samael:BAAALgAECgMJBgABLgAFFAQJDAARAMQSAA==.Sammel:BAABLgAECn8ZAAMjAAgJ9BhXFABNAgAjAAgJ9BhXFABNAgAXAAEJCRFregAxAAAAAA==.Sandmanslim:BAAALgAECgUJBQAAAA==.Sargus:BAAALgADCgEJAQAAAA==.Sathreina:BAACLgAFFH8LAAIDAAQJjg0ETwAQAQADAAQJjg0ETwAQAQAuAAQKfyoAAgMACQlEFnJMAOEBAAMACQlEFnJMAOEBAAAA.Satinofhell:BAAALgAECgQJBgAAAA==.Sawbones:BAAALgAECgYJBgAAAA==.',
Sc='Scaries:BAABLgAECn8XAAIHAAkJKRtoEgCAAgAHAAkJKRtoEgCAAgAAAA==.Schmeckles:BAABLgAFFH8HAAIFAAMJnAMCZAB/AAAFAAMJnAMCZAB/AAAAAA==.Scootzmcgee:BAAALgAFFAEJAQAAAA==.',
Se='Seikura:BAAALgADCgMJAwAAAA==.Sekii:BAEALgAECgQJBAABLgAFFAYJFQATAP8jAA==.Sekimaru:BAACLgAFFH8cAAMSAAYJ9g5YHwApAQASAAUJ+RFYHwApAQARAAEJ6wLtEQBGAAAuAAQKfzQAAxIACQnXGlULAG4CABIACQnXGlULAG4CABEAAQmnB1AqAC0AAAAA.Selok:BAAALgAFFAEJAgAAAA==.',
Sh='Shaddik:BAAALgAECgQJBgABLgAECggJEAABAAAAAA==.Shadowisbad:BAAALgAECgkJEwAAAA==.Shadpriest:BAAALgAECggJEAAAAA==.Shaeledoran:BAACLgAFFH8TAAINAAUJwxuDTgBVAQANAAUJwxuDTgBVAQAuAAQKf0EAAg0ACQnHILsbAKECAA0ACQnHILsbAKECAAAA.Shamaneggs:BAABLgAFFH8HAAIFAAMJKgw/WgCYAAAFAAMJKgw/WgCYAAAAAA==.Shamatroxx:BAACLgAFFH8tAAIEAAYJ1hptAwCeAQAEAAYJ1hptAwCeAQAuAAQKfzEAAgQACQlyJOkAAEoDAAQACQlyJOkAAEoDAAAA.Shamphen:BAAALgAFFAEJAQAAAA==.Shampomaster:BAAALgADCgMJAwAAAA==.Sheist:BAABLgAFFH8FAAIaAAIJygn7XgBbAAAaAAIJygn7XgBbAAABLgAFFAQJCQAKAE0gAA==.Shenzuu:BAAALgAECgUJBwAAAA==.Shieetz:BAAALgAECgYJEQAAAA==.Shlomie:BAAALgADCggJGgAAAA==.Shlomiel:BAAALgADCgEJAQAAAA==.Shlomieo:BAAALgADCgkJFwAAAA==.Shocknasty:BAAALgAECgEJAQAAAA==.Shorttemper:BAAALgAECgIJAgAAAA==.Shänk:BAABLgAECn8iAAMSAAcJdREGJAB0AQASAAcJdREGJAB0AQARAAQJVgtMFgDLAAAAAA==.',
Si='Sibirica:BAAALgADCgEJAQAAAA==.Siena:BAABLgAECn8bAAMFAAgJYwQwdAAAAQAFAAgJYwQwdAAAAQAOAAYJKA2qUwDqAAAAAA==.Silanthius:BAAALgAECgYJCQAAAA==.Silith:BAAALgAECgYJDAAAAA==.Silre:BAABLgAECn8aAAIUAAcJjhDUEQArAQAUAAcJjhDUEQArAQAAAA==.Silverfangg:BAAALgAECgMJAwAAAA==.Sinergy:BAABLgAECn8UAAITAAYJIh8zRAD/AQATAAYJIh8zRAD/AQAAAA==.Singularité:BAAALgAFFAEJAQABLgAFFAQJDAARAMQSAA==.Siz:BAAALgAECgYJCAAAAA==.',
Sk='Skiddlebutt:BAAALgADCgMJAgAAAA==.Skirmish:BAABLgAECn8ZAAINAAYJLRQ4mAA4AQANAAYJLRQ4mAA4AQAAAA==.Skyray:BAAALgADCgUJBQAAAA==.',
Sl='Slappeepries:BAAALgADCgEJAQABLgAECgkJEgABAAAAAA==.Slappeey:BAAALgAECgkJEgAAAA==.',
Sn='Snapbean:BAAALgADCgEJAQAAAA==.Snarls:BAAALgAECgIJAgABLgAECgkJPgAiACkkAA==.Snaxx:BAAALgAECgMJBgABLgAECgcJDQABAAAAAA==.Snorunt:BAAALgAECgYJEAAAAA==.Snuudle:BAACLgAFFH8PAAMNAAMJViBIJgD9AAANAAMJViBIJgD9AAAfAAIJ0hUNBABXAAAuAAQKf00AAw0ACQkmJe8PAO0CAA0ACQlZJO8PAO0CAB8ACAnPJCADAMICAAAA.',
So='Softlight:BAAALgAECgMJAwAAAA==.Solokills:BAAALgAECgcJDwAAAA==.Soulreaperqt:BAAALgAECgMJAwABLgAECgUJCwABAAAAAA==.Soundtrack:BAAALgADCgEJAQABLgAECgkJHQAIACUNAA==.',
Sp='Spaceman:BAAALgAECgQJBwABLgAFFAYJHwAXAEwOAA==.Sproxx:BAAALgAECgEJAgABLgAECgkJEgABAAAAAA==.Spyridon:BAAALgAECgcJCgAAAA==.',
Sq='Sqlpal:BAABLgAECn8cAAMbAAcJox60LwA9AgAbAAcJox60LwA9AgAmAAQJOB77PgAAAQAAAA==.Squirrels:BAABLgAECn9CAAMHAAkJFRVzAACgAQAHAAkJFRVzAACgAQAVAAQJuwXsUgCGAAAAAA==.Squirtstorm:BAABLgAECn8+AAMFAAkJLCCDCQAbAwAFAAkJLCCDCQAbAwAOAAIJbRzzjgBTAAAAAA==.Squirtz:BAAALgADCgUJBAAAAA==.',
Sr='Srgntsnoop:BAAALgADCgUJBQAAAA==.',
St='Stabmywood:BAABLgAECn8yAAMSAAkJjCMwBAD7AgASAAkJjCMwBAD7AgAgAAEJNxbJIgA+AAAAAA==.Stealthberry:BAAALgADCgMJAwAAAA==.Sthella:BAAALgADCgMJAwABLgAECgUJDQABAAAAAA==.Stillcreepin:BAAALgAECgIJAwAAAA==.Stompy:BAAALgADCgkJEAABLgAFFAYJFgAjAOwQAA==.Storienn:BAABLgAECn8WAAMDAAkJ/BaDXAC5AQADAAgJVReDXAC5AQAWAAIJ1hXZOAB7AAAAAA==.Stormzpaly:BAAALgADCgkJCQAAAA==.Stormßlessed:BAAALgADCgUJBQAAAA==.Strokemyhorn:BAAALgAECgQJBQAAAA==.',
Su='Subarashii:BAAALgAECgEJAQABLgAECgYJEQABAAAAAA==.Suküna:BAACLgAFFH8LAAIbAAMJPBhmXgDVAAAbAAMJPBhmXgDVAAAuAAQKfz4AAhsACQl8IyUHABwDABsACQl8IyUHABwDAAAA.Sunglo:BAAALgAECgUJBQAAAA==.Superbean:BAAALgAECgEJAQAAAA==.Surefire:BAAALgAECgEJAQAAAA==.',
Sw='Swaption:BAACLgAFFH8PAAIFAAUJDCS8DgD3AQAFAAUJDCS8DgD3AQAuAAQKfysAAgUACAkKJSAMAL8CAAUACAkKJSAMAL8CAAAA.Swolebane:BAAALgADCgUJBQAAAA==.',
Sy='Sybaü:BAAALgAECgYJDAAAAA==.Synchronize:BAABLgAECn8YAAINAAcJPhSEeQCRAQANAAcJPhSEeQCRAQAAAA==.Syrelia:BAABLgAECn87AAIKAAkJKBmjKwBrAgAKAAkJKBmjKwBrAgAAAA==.',
Ta='Takèda:BAABLgAECn8sAAIlAAkJHCA9AAAyAgAlAAkJHCA9AAAyAgAAAA==.Taldain:BAABLgAECn8cAAQQAAkJ2x2qFQCnAQAkAAgJ4xnlGgD0AQAQAAcJABmqFQCnAQAPAAIJaSOpJwDQAAAAAA==.Talonstrykz:BAABLgAECn8VAAISAAgJ0A42IgDnAQASAAgJ0A42IgDnAQAAAA==.Tankdeesnuts:BAABLgAECn87AAIMAAkJlQeKIQAjAQAMAAkJlQeKIQAjAQAAAA==.Tashalle:BAAALgAECgEJAQABLgAECgkJLwAXAMgdAA==.Tassarosea:BAAALgAFFAIJAgAAAA==.Tauloe:BAABLgAECn8uAAIOAAkJuA0TLwCFAQAOAAkJuA0TLwCFAQAAAA==.Tayna:BAAALgAECgYJCQAAAA==.',
Te='Teejaydh:BAAALgADCgEJAQAAAA==.Tellamon:BAABLgAECn8aAAIDAAgJrhMAgwBpAQADAAgJrhMAgwBpAQAAAA==.Terpene:BAAALgADCgEJAQAAAA==.Tetanus:BAAALgAECgQJBwABLgAECgYJEgABAAAAAA==.Teyassha:BAAALgAECgEJBAAAAA==.',
Th='Thomo:BAABLgAECn8dAAMYAAkJ6gfLYwB+AQAYAAkJmAfLYwB+AQAlAAYJ2gSgHAAMAQAAAA==.Throatfist:BAABLgAFFH8FAAMHAAIJIAsoJABJAAAHAAEJ2RIoJABJAAAcAAEJZwP6EwBCAAABLgAFFAYJHAAbAFAeAA==.Throme:BAAALgAECgkJEAAAAA==.Thunk:BAACLgAFFH8JAAIOAAMJPRfdDQAMAQAOAAMJPRfdDQAMAQAuAAQKfyYAAg4ACQmXJfUDAGADAA4ACQmXJfUDAGADAAAA.',
Ti='Timdawg:BAACLgAFFH8NAAIKAAUJMB6/BABdAQAKAAUJMB6/BABdAQAuAAQKfxQAAgoACAn1InYaALwCAAoACAn1InYaALwCAAAA.',
Tj='Tjkrollsaway:BAAALgAECgIJAgAAAA==.',
To='Todrick:BAAALgAECgEJAQAAAA==.Tomotostein:BAACLgAFFH8PAAIDAAQJfBCpBwDBAAADAAQJfBCpBwDBAAAuAAQKfzMAAgMACQlpIzQJAB8DAAMACQlpIzQJAB8DAAAA.Tonobaggins:BAAALgADCggJCAAAAA==.Toothluss:BAAALgADCgMJAgAAAA==.Totemnutz:BAABLgAECn8UAAMFAAgJghLdNgDVAQAFAAgJghLdNgDVAQAOAAUJ5hHWRwAVAQAAAA==.',
Tr='Tradrael:BAAALgAECgEJAQAAAA==.Tristîtia:BAAALgAFFAEJAQAAAA==.Trulu:BAAALgAECgIJAgAAAA==.',
Ts='Tsume:BAABLgAECn8VAAIYAAcJ8BUDYwB/AQAYAAcJ8BUDYwB/AQAAAA==.',
Tu='Tum:BAAALgAECgcJDQABLgAECgcJDQABAAAAAA==.Tumlek:BAAALgAECgIJAgAAAA==.Tunobuffpapi:BAAALgAFFAIJAgAAAA==.',
Ty='Tyrinn:BAAALgAFFAIJAgAAAA==.Tystian:BAAALgAECgYJDwAAAA==.Tyv:BAABLgAECn80AAMhAAkJAxYhAwABAgAhAAkJAxYhAwABAgAKAAYJKgaf1wDnAAAAAA==.',
['Té']='Téa:BAAALgAECgMJAwABLgAECggJGAAjADwfAA==.',
Ua='Uav:BAAALgAECgEJAQAAAA==.',
Un='Unclejoey:BAAALgAECgEJAQABLgAECgkJPgAiACkkAA==.',
Ur='Urä:BAAALgAECggJDgAAAA==.',
Va='Vainatetosix:BAABLgAECn8VAAINAAgJVwwOlgA8AQANAAgJVwwOlgA8AQAAAA==.Valindra:BAAALgAECgUJCQAAAA==.Vallodon:BAABLgAECn8hAAIKAAkJ6SAcNwA8AgAKAAkJ6SAcNwA8AgAAAA==.Valtasia:BAAALgADCgEJAQAAAA==.Valyndra:BAAALgAECgcJDAAAAA==.Vanquizsher:BAAALgAECgIJAgAAAA==.Vanwolfy:BAACLgAFFH8JAAIMAAQJYxGhFwDdAAAMAAQJYxGhFwDdAAAuAAQKfyMAAgwACQl/DhMYAH8BAAwACQl/DhMYAH8BAAAA.Vaylorian:BAAALgAECgYJBgABLgAECgcJDAABAAAAAA==.',
Ve='Velanthris:BAAALgAECgMJBQABLgAECgcJDAABAAAAAA==.Velectran:BAABLgAECn8qAAIDAAgJJRfaUQDTAQADAAgJJRfaUQDTAQABLgAECgkJOwAKACgZAA==.Velorian:BAAALgAECgUJBwAAAA==.Vesperi:BAAALgAECggJCAABLgAECgkJOwAKACgZAA==.',
Vi='Vilgehkfrúna:BAAALgAECgEJAQAAAA==.Virdreth:BAAALgAECgEJBAAAAA==.Vish:BAAALgAECgUJBgAAAA==.',
Vo='Vortash:BAAALgAECgQJBQAAAA==.',
Vy='Vyndragon:BAAALgAECgMJAwAAAA==.Vynle:BAAALgAECgQJCQAAAA==.Vyrthos:BAAALgADCgkJCQABLgAFFAMJCAAKABMDAA==.',
['Vä']='Vämpira:BAAALgAECgYJCwAAAA==.',
Wa='Warheimer:BAAALgAECgQJBQAAAA==.Warrgodx:BAABLgAECn8XAAMCAAcJFhhYPABUAQACAAcJFhhYPABUAQAeAAMJkxKoRgCvAAAAAA==.Wartroxx:BAAALgAFFAMJAwABLgAFFAYJLQAEANYaAA==.',
We='Welcome:BAAALgADCgYJBAAAAA==.Wengja:BAABLgAECn8gAAQVAAcJryULBwDqAgAVAAcJryULBwDqAgAHAAEJ9QSVjgAnAAAcAAEJAACmiQAlAAAAAA==.',
Wh='Wheri:BAAALgADCggJCAABLgAECgkJJAAeABkbAA==.Whoknows:BAABLgAECn8YAAIbAAcJgyK3IQBLAgAbAAcJgyK3IQBLAgAAAA==.',
Wi='Wiz:BAAALgAECgQJBgAAAA==.',
Wo='Wolfchef:BAAALgAECgYJDAAAAA==.Woodkin:BAAALgAECgUJEQAAAA==.',
Wr='Wrongwookie:BAABLgAECn8iAAIOAAkJxR2mCAAIAwAOAAkJxR2mCAAIAwAAAA==.',
Wy='Wyrmbreaker:BAAALgAECgYJCQAAAA==.',
Xi='Xiak:BAAALgAECgEJAQABLgAFFAMJBgAPAJQaAA==.Xialai:BAAALgADCgMJAwAAAA==.',
Ya='Yako:BAAALgAECgIJAgAAAA==.',
Ye='Yereka:BAAALgADCgQJBAAAAA==.',
Yo='Yoomesbonds:BAAALgAFFAEJAQAAAA==.Youtube:BAACLgAFFH8xAAMaAAkJ4SE5AQB0AgAaAAkJ4SE5AQB0AgAdAAQJ8CG8BAAgAQAuAAQKfyMAAx0ACQkrJVQDAOoCAB0ABwmsJVQDAOoCABoABwkQImwmAK0BAAAA.Yoyohunty:BAAALgAECgEJAgAAAA==.Yozki:BAABLgAECn8fAAIKAAkJTh3sNABFAgAKAAkJTh3sNABFAgAAAA==.',
Yt='Ytix:BAAALgAECgMJAwAAAA==.',
Yu='Yuji:BAAALgAECgEJAQABLgAFFAMJCQAOAD0XAA==.Yuuki:BAAALgAECgQJBQABLgAFFAQJDAARAMQSAA==.Yuulia:BAABLgAECn8kAAMeAAkJGRscCwA2AgAeAAkJqhocCwA2AgAMAAYJeRhvGQCGAQAAAA==.',
Yv='Yvonnê:BAAALgADCgEJAQAAAA==.',
Za='Zabada:BAAALgAECgEJAQAAAA==.Zaee:BAAALgAECgMJBgABLgAFFAQJBwAFACQLAA==.Zariee:BAABLgAECn8vAAImAAgJBxEPIAB5AQAmAAgJBxEPIAB5AQAAAA==.',
Ze='Zel:BAAALgADCgEJAQABLgAECgkJHwAEAIEbAA==.Zemsen:BAACLgAFFH8IAAIKAAMJEwMGMgDgAAAKAAMJEwMGMgDgAAAuAAQKfzAAAwoACQmjGOY8AIQCAAoACQmjGOY8AIQCACEAAgneBcAZAEoAAAAA.Zentrea:BAAALgAECgIJAgABLgAFFAYJFgAjAOwQAA==.Zenyea:BAAALgAFFAEJAgABLgAFFAYJFgAjAOwQAA==.Zetta:BAACLgAFFH8WAAIjAAYJ7BCFCgC3AQAjAAYJ7BCFCgC3AQAuAAQKfysAAiMACQmbH+sMALUCACMACQmbH+sMALUCAAAA.',
Zo='Zoguk:BAAALgADCgEJAQAAAA==.Zoktavir:BAAALgADCgcJCAAAAA==.Zoltan:BAABLgAECn8VAAIKAAYJnQve2QA9AQAKAAYJnQve2QA9AQAAAA==.Zorin:BAAALgADCgcJDgAAAA==.',
Zy='Zyndrael:BAABLgAECn8sAAIDAAkJVR5sHQCVAgADAAkJVR5sHQCVAgAAAA==.',
['Zâ']='Zâgs:BAAALgADCgYJCAAAAA==.',
['Êl']='Êlytz:BAAALgAECggJEAAAAA==.',
['ßl']='ßlue:BAACLgAFFH8HAAIHAAQJDBQPJgARAQAHAAQJDBQPJgARAQAuAAQKf2kABAcACQnQIGsGANQCAAcACQnQIGsGANQCABUACAnFGq0WAGQCABwAAwm+DF1lAIwAAAAA.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
