local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Holy','Monk-Windwalker','Paladin-Holy','Hunter-BeastMastery','Paladin-Retribution','Mage-Arcane','Evoker-Preservation','Evoker-Devastation','Warrior-Arms','Warlock-Demonology','Warlock-Destruction','Warlock-Affliction','Rogue-Assassination','Unknown-Unknown','Druid-Balance','Monk-Brewmaster','Warrior-Protection','Mage-Frost','Shaman-Restoration','Shaman-Elemental','Druid-Restoration','DeathKnight-Blood','DeathKnight-Unholy','Rogue-Subtlety','Druid-Guardian','Priest-Shadow','Druid-Feral','DemonHunter-Devourer','DeathKnight-Frost','Hunter-Marksmanship','DemonHunter-Havoc','Paladin-Protection','Warrior-Fury','Rogue-Outlaw','Shaman-Enhancement','DemonHunter-Vengeance','Priest-Discipline','Mage-Fire','Evoker-Augmentation','Hunter-Survival',}
local provider = {region='US',realm="Dath'Remar",name='US',type='weekly',zone=53,date='2026-10-06',data={Aa='Aaronius:BAAANQAECgIIAwAAAA==.',
Ab='Abduhl:BAAANQAECgEIAQAAAA==.',
Ac='Ackleholic:BAAANQAECgQIBAABNQAECgcIGwABAO0kAA==.',
Ad='Ade:BAABNQAECoEgAAICAAgKzx8UEgCtAgACAAgKzx8UEgCtAgAAAA==.Adezardre:BAAANQAECgUICwAAAA==.Admetriell:BAAANQAECgIIAgABNQAECgkJIAADAC0KAA==.Advosary:BAAANQAECgIIBQAAAA==.',
Af='Affection:BAAANQADCgMJAwAAAA==.Afflictid:BAAANQABCgIIAgAAAA==.Afterburn:BAAANQAECgQIBAAAAA==.',
Ai='Aigmokthar:BAABNQAECoEiAAIEAAgKeBizSgBmAgAEAAgKeBizSgBmAgAAAA==.',
Ak='Akiriah:BAAANQADCggICAAAAA==.Akirial:BAABNQAECoEcAAMDAAgK8w6eYgDMAQADAAgK8w6eYgDMAQAFAAEK2wFymgEgAAABNQAECggIHQAGACshAA==.Aklo:BAAANQAECgMIBgAAAA==.',
Al='Alamysia:BAAANQAECgMIBAAAAA==.Albertfist:BAAANQADCgMIAwAAAA==.Aletech:BAAANQAECgMIAwAAAA==.Ali:BAABNQAECoEaAAMHAAcKYhIyIQCmAQAHAAcKYhIyIQCmAQAIAAEK0wEYPgAjAAAAAA==.Aliesá:BAAANQAECgMICgAAAA==.Alilea:BAAANQAECgQICAAAAA==.Alimagus:BAAANQAECggIDwABNQAFFAUICQAJADQXAA==.Alisandrah:BAACNQAFFIEUAAQKAAYK0hjaCQCfAQAKAAUKLRbaCQCfAQALAAEKCSbwEABxAAAMAAEKjBG8CwBIAAA1AAQKgSgABAsACQrxI+cKAD4CAAoACApmI9ggAOoCAAsABwrBHucKAD4CAAwAAQrDGeAkAEcAAAAA.Alison:BAAANQAECgIIBQAAAA==.Allakeer:BAACNQAFFIEFAAINAAMKtRjjCQASAQANAAMKtRjjCQASAQA1AAQKgSEAAg0ACQqcH8QjADwCAA0ACQqcH8QjADwCAAAA.Allure:BAAANQADCggICAABNQAECgcIGQAEAP0VAA==.Altarios:BAAANQADCggIHAAAAA==.Alyyix:BAAANQAECgEIAQAAAA==.Alza:BAAANQAECgEIAQAAAA==.',
Am='Amber:BAAANQAECgYIDAAAAA==.Amberlicious:BAAANQAECgEIAQABNQAECgYIDAAOAAAAAA==.Amberlily:BAAANQAECgEIAwABNQAECgYIDAAOAAAAAA==.Ambertastic:BAAANQAECgEIAgABNQAECgYIDAAOAAAAAA==.Amilandris:BAABNQAECoEzAAIPAAkK/iDcEAAuAwAPAAkK/iDcEAAuAwAAAA==.Amitié:BAAANQADCgYIBgAAAA==.',
An='Analalea:BAAANQAECgEIAQAAAA==.Analdrainal:BAABNQAECoEhAAIJAAkKMSPZDgB/AwAJAAkKMSPZDgB/AwAAAA==.Anghellic:BAAANQAECgQIBQAAAA==.Annaris:BAAANQADCggIIQAAAA==.',
Ap='Apophani:BAAANQAECgQIBwAAAA==.Appolo:BAABNQAECoEYAAMFAAcKvSHAUQB3AgAFAAcKvSHAUQB3AgADAAIKZhZ94wCHAAAAAA==.',
Aq='Aquadh:BAAANQAECgEIAgAAAA==.',
Ar='Arcanegasm:BAABNQAECoEaAAIGAAgK4x49eQB1AgAGAAgK4x49eQB1AgAAAA==.Archii:BAAANQADCgcIBwABNQAECggIKAAGAGkYAA==.Archslayer:BAAANQAECgUIEgAAAA==.Aresdeekx:BAAANQAECgUICQABNQAECgkJHgAQAF4cAA==.Arneus:BAAANQAECgUICgAAAA==.Arnir:BAABNQAECoEbAAIRAAcKmg33GgBcAQARAAcKmg33GgBcAQAAAA==.Arriving:BAABNQAECoEkAAIKAAgKUA//dADZAQAKAAgKUA//dADZAQAAAA==.Artaq:BAAANQAECgIIBgAAAA==.Artoriöus:BAAANQADCgQIBAABNQAECggICgAOAAAAAA==.Arvanon:BAABNQAECoEYAAISAAYKKQaHGwDrAAASAAYKKQaHGwDrAAAAAA==.',
As='Ashaandra:BAAANQADCggIDwAAAA==.Ashanar:BAABNQAECoEZAAISAAYKCAd1GgD3AAASAAYKCAd1GgD3AAAAAA==.Asharla:BAAANQAECgUIEAAAAA==.Ashbringa:BAAANQAECgUIDwAAAA==.Ashhman:BAABNQAECoEUAAITAAcKxBpRQgAtAgATAAcKxBpRQgAtAgAAAA==.Ashhunt:BAABNQAECoEpAAIEAAgKxx46MAC6AgAEAAgKxx46MAC6AgAAAA==.Ashmend:BAAANQAECgUIDAAAAA==.Ashtotem:BAAANQADCgUIBQAAAA==.Asorrow:BAAANQAECgQICgABNQAFFAMIBQAGAH4VAA==.Assatur:BAAANQAECgYICQAAAA==.Astarna:BAABNQAECoEXAAIUAAcKKwgEigBaAQAUAAcKKwgEigBaAQAAAA==.Asteríx:BAAANQADCgUICQAAAA==.Astier:BAAANQADCgEIAQAAAA==.',
At='Atiatal:BAAANQAECgEIBAAAAA==.Atlasursidae:BAAANQAECgQICQAAAA==.Atoniah:BAAANQAECgYIEgAAAA==.',
Au='Auraz:BAABNQAECoEVAAIBAAgKMyUHCgBgAwABAAgKMyUHCgBgAwAAAA==.',
Av='Avelinna:BAAANQAECgMICQABNQAECgUIBwAOAAAAAA==.',
Aw='Awan:BAAANQADCggIHAABNQAECgQIEAAOAAAAAA==.',
Ay='Ayaya:BAAANQAFFAEIAQABNQAFFAUIEAAVAEYkAA==.',
Az='Aztrayel:BAAANQAECgMIBgAAAA==.',
Ba='Baalial:BAAANQAECgQIDAAAAA==.Baboya:BAAANQAECggIAQAAAA==.Baelgrim:BAAANQAECgMICAAAAA==.Balanoth:BAAANQADCgQIBAAAAA==.Baly:BAAANQADCgYIDAABNQAECgkJGwAKAOsWAA==.Bangbangbro:BAABNQAECoEVAAIFAAcK2QeeyQBPAQAFAAcK2QeeyQBPAQAAAA==.Barium:BAAANQADCgYIEAAAAA==.',
Be='Belfrostbolt:BAAANQAECgQIBQAAAA==.Bentt:BAAANQABCgcICgAAAA==.Beon:BAAANQAECgEIAQAAAA==.Bettÿ:BAAANQADCgYICQABNQAECgUIEgAOAAAAAA==.',
Bi='Bigjawden:BAAANQAECgQIBgAAAA==.Billbee:BAAANQAECgUICgAAAA==.Bimbohaggins:BAAANQAECgMIBgABNQAECgYIHAAKAHchAA==.Bimbò:BAABNQAECoEaAAIBAAcK9AKcmAAQAQABAAcK9AKcmAAQAQAAAA==.Binchicken:BAAANQAECgQIBwAAAA==.Bingler:BAAANQAECgEIAwAAAA==.',
Bj='Bjornhammerz:BAAANQAECgEIBAABNQAECgcIDgAOAAAAAA==.Bjornshockz:BAAANQAECgcIDgAAAA==.',
Bl='Blackvelvet:BAAANQAECgMICAAAAA==.Blaz:BAAANQAECgQIDQAAAA==.Blockz:BAAANQADCggIDwAAAA==.Bloodboi:BAAANQADCgcIDgABNQAECgUIDgAOAAAAAA==.Bloodyeddy:BAAANQAECgEIAgAAAA==.Bluecups:BAAANQAECgUIEgAAAA==.Bluey:BAAANQAECgMIAwAAAA==.',
Bo='Bobbyboom:BAAANQAECgQICAAAAA==.Bonedecays:BAAANQADCgMIBAAAAA==.Bontoad:BAAANQAECgQIEAAAAA==.Boomkini:BAABNQAECoEbAAIPAAcKTBOqRACyAQAPAAcKTBOqRACyAQAAAA==.',
Br='Brewaresx:BAABNQAECoEeAAMQAAkKXhzvBgC2AgAQAAkKXhzvBgC2AgACAAYKUwKvSwCVAAAAAA==.Brewboy:BAAANQADCgIIAgABNQAECgUIDgAOAAAAAA==.Brewtus:BAAANQAECgEIAQAAAA==.Broxaschor:BAAANQABCgQIAwAAAA==.Brutus:BAABNQAECoEgAAMWAAcKAyGTJAB7AgAWAAcKAyGTJAB7AgAXAAUKRw++dQAZAQAAAA==.',
Bu='Bubbleduck:BAAANQAECgIIAgAAAA==.Buggzz:BAABNQAECoEiAAIEAAcKviTnKwDJAgAEAAcKviTnKwDJAgAAAA==.',
Bz='Bzlthazyr:BAACNQAFFIEFAAIXAAIKawiyFgCIAAAXAAIKawiyFgCIAAA1AAQKgR0AAhcACQr9GQovAFICABcACQr9GQovAFICAAAA.',
Ca='Cahtbl:BAAANQAECgQICQAAAA==.Caiaphas:BAAANQAECggIAQAAAA==.Calasandria:BAAANQAECgIJAgABNQAECggIGgAYAPsQAA==.Callin:BAAANQAECgMICgAAAA==.Calyx:BAAANQADCgYICQAAAA==.Caoimhe:BAAANQADCgIIAgABNQAECgUIEwAOAAAAAA==.Cartier:BAAANQAECgQICAABNQAECgcIGQAEAP0VAA==.Casay:BAABNQAECoEWAAIFAAcKkRQglQDEAQAFAAcKkRQglQDEAQAAAA==.Casbot:BAABNQAECoEtAAMYAAkKpR2oBQAkAwAYAAkKpR2oBQAkAwANAAMK+QYlcgCQAAAAAA==.Cashmere:BAABNQAECoEZAAIEAAcK/RWRcQAAAgAEAAcK/RWRcQAAAgAAAA==.Castalight:BAAANQAECgYICgAAAA==.Castlebravo:BAAANQADCgYIBgAAAA==.',
Ce='Cerrylune:BAAANQADCgQIBAAAAA==.',
Ch='Changes:BAAANQADCggIGgAAAA==.Charish:BAAANQADCgEIAQAAAA==.Charlee:BAAANQADCgcIEgAAAA==.Chilpill:BAEANQAECgcICAAAAA==.Chirran:BAABNQAECoFEAAIZAAgK9CDqBgDtAgAZAAgK9CDqBgDtAgAAAA==.Chxdzilla:BAACNQAFFIEPAAIJAAQKsBCtFQA4AQAJAAQKsBCtFQA4AQA1AAQKgS4AAgkACQqlHFE2ANMCAAkACQqlHFE2ANMCAAAA.Chârlie:BAAANQAECgEIAQABNQAECgQICAAOAAAAAA==.',
Ci='Cinnamõn:BAAANQABCgYICwAAAA==.Citryn:BAAANQAECgIIBAABNQAFFAMIBwACAIoQAA==.',
Co='Codexo:BAAANQADCggICAAAAA==.Colpamia:BAAANQAECgEIBgAAAA==.Corldrin:BAAANQAECgUIBwABNQAECgYIBwAOAAAAAA==.Coronis:BAAANQAECgUIEQAAAA==.Corriana:BAAANQAECgUIBwAAAA==.Corwin:BAAANQAECgEIAQAAAA==.',
Cr='Crazee:BAACNQAFFIEKAAMGAAUKoRUdHwBMAQAGAAQK+RIdHwBMAQASAAEKPSBpCwBTAAA1AAQKgSoAAwYACQrxIqgfAFEDAAYACQrxIqgfAFEDABIAAQqFIlczAFYAAAAA.Cruz:BAAANQAECgQIDAAAAA==.Crystalflame:BAABNQAECoEcAAISAAgKiAm9EAByAQASAAgKiAm9EAByAQAAAA==.Crìsp:BAAANQADCgYICwABNQAECgcICAAOAAAAAA==.',
Ct='Ctshammy:BAAANQAECgUIEAAAAA==.',
Cu='Cultistt:BAABNQAECoEkAAMaAAgKBgvgKwCeAQAaAAgKBgvgKwCeAQABAAQK3Qm8sgDHAAAAAA==.Cursedyou:BAABNQAECoETAAIKAAYK2xDhmgBzAQAKAAYK2xDhmgBzAQAAAA==.Curserot:BAABNQAECoEbAAILAAgKYRcdCgBMAgALAAgKYRcdCgBMAgAAAA==.Cuteselenes:BAAANQADCgIIAgAAAA==.',
Cy='Cynal:BAABNQAECoEkAAIEAAgKDBZHTQBfAgAEAAgKDBZHTQBfAgAAAA==.',
Da='Daddyy:BAAANQAECgUICQABNQAFFAUICgAGAKEVAA==.Dammo:BAAANQAECgQIBgAAAA==.Dantallion:BAAANQADCgUICAABNQAECgUICAAOAAAAAA==.Dardroc:BAAANQADCgMIAwAAAA==.Darkholme:BAABNQAECoElAAQZAAgKGRRLHAB5AQAZAAUKhBpLHAB5AQAPAAcKQwpNVQBYAQAbAAQKkRM5HAAMAQAAAA==.Darkk:BAAANQAECgEIAQAAAA==.Darthdraik:BAAANQAECgUIDQAAAA==.',
Dc='Dcver:BAABNQAECoFBAAIKAAgK3CDHIADqAgAKAAgK3CDHIADqAgAAAA==.',
Dd='Ddraigfach:BAAANQABCgMIAwAAAA==.',
De='Deademeat:BAAANQADCgMIAwAAAA==.Deadlynewbz:BAABNQAECoEkAAMNAAkKHSVaAgCsAwANAAkKHSVaAgCsAwAYAAMKth+ENAD0AAAAAA==.Deathboom:BAAANQADCgUIBQABNQAECgkJMAAcAAMdAA==.Deathbow:BAAANQADCgcIBwAAAA==.Deathbyshoe:BAAANQAECgUIEgAAAA==.Deathchain:BAAANQADCgUIBQAAAA==.Deathivy:BAAANQADCgcIIAAAAA==.Deathjam:BAABNQAECoEcAAMXAAYKAhqLUQCkAQAXAAYKAhqLUQCkAQAdAAEKMA6fkQA3AAAAAA==.Deathmore:BAAANQAECgUIDwAAAA==.Deathshrine:BAAANQAECgEIAQAAAA==.Decypha:BAABNQAECoEhAAIeAAcKUhnkIgAWAgAeAAcKUhnkIgAWAgAAAA==.Deidius:BAAANQADCgUIBQAAAA==.Deiwos:BAAANQAECgQIEAAAAA==.Delichtable:BAAANQADCggIIAABNQAECgYIEgAOAAAAAA==.Deltora:BAAANQAECgEIAgABNQAECgYJCwAOAAAAAA==.Demodog:BAABNQAECoEcAAIKAAYKdyFUVwAvAgAKAAYKdyFUVwAvAgAAAA==.Demoneddy:BAAANQAECgMIBAAAAA==.Demonicnight:BAABNQAECoEYAAIfAAgKghYFKwAfAgAfAAgKghYFKwAfAgAAAA==.Derryth:BAABNQAECoEdAAIFAAgKpBoYWABlAgAFAAgKpBoYWABlAgAAAA==.Devo:BAAANQAECggIAQAAAA==.Devpro:BAABNQAECoEZAAIGAAcK7xkolQA5AgAGAAcK7xkolQA5AgAAAA==.Devrothas:BAAANQADCgIJAgABNQAECgcIGQAGAO8ZAA==.Deweysan:BAABNQAECoEVAAIGAAkK8AzWpAAYAgAGAAkK8AzWpAAYAgAAAA==.Dexillo:BAACNQAFFIEOAAIfAAYKwQtWBgC3AQAfAAYKwQtWBgC3AQA1AAQKgSkAAx8ACQqJHI8bAJkCAB8ACQqJHI8bAJkCABwACArwDpssALsBAAAA.',
Dh='Dhaveira:BAABNQAECoEfAAMJAAgKXSE2NwDQAgAJAAgKXSE2NwDQAgARAAEKhR/MNQBPAAAAAA==.',
Di='Diggyhole:BAAANQADCgIIAgAAAA==.Divinegirly:BAABNQAECoEXAAIgAAcKmgtoLgBAAQAgAAcKmgtoLgBAAQAAAA==.',
Do='Dodgeanaxe:BAACNQAFFIEHAAIJAAMK/w/pHQDcAAAJAAMK/w/pHQDcAAA1AAQKgUIAAgkACQrQIWcZAEcDAAkACQrQIWcZAEcDAAAA.Dojoe:BAAANQAECgIICgABNQAECggIJAAWAFIcAA==.Dorá:BAAANQAECgUICQAAAA==.',
Dr='Dracnock:BAABNQAECoEbAAIhAAgKdQ5IDADTAQAhAAgKdQ5IDADTAQAAAA==.Drapary:BAAANQADCggICAABNQAECgMIBQAOAAAAAA==.Drinian:BAAANQAECgUIEAAAAA==.',
Du='Ducker:BAACNQAFFIEIAAICAAQKICVLBQCYAQACAAQKICVLBQCYAQA1AAQKgSEAAgIACQpUJmsCAK8DAAIACQpUJmsCAK8DAAAA.Dustangel:BAAANQAECgcIBwAAAA==.',
Dy='Dylexd:BAABNQAECoEdAAICAAgKCSGUDQDoAgACAAgKCSGUDQDoAgAAAA==.',
['Dã']='Dãwn:BAAANQAECgYIBwAAAA==.',
Ea='Eatmybolts:BAAANQAECgYIBgAAAA==.',
Ec='Eccentricity:BAABNQAECoEWAAIEAAcK3BqhWgA7AgAEAAcK3BqhWgA7AgAAAA==.',
El='Eldarion:BAAANQAECgQIDwAAAA==.Electricmon:BAABNQAECoEUAAIDAAYKHgofqwD/AAADAAYKHgofqwD/AAABNQAFFAMIBwAJAP8PAA==.Elementi:BAAANQADCgIIAgAAAA==.Elemootal:BAAANQADCgcIBwAAAA==.Elfy:BAAANQADCgQIBAABNQAECgIIAwAOAAAAAA==.Eliasidris:BAAANQAECgcIEQABNQAECgkJIgAeAEwNAA==.Elmaco:BAABNQAECoEfAAMKAAgKDyRWEAA9AwAKAAgKDyRWEAA9AwALAAIKtx2bRACoAAAAAA==.Elphkilla:BAAANQADCggICAAAAA==.Elroth:BAAANQADCgYICgAAAA==.Elseapi:BAABNQAECoEZAAIEAAYKYQt2sQBtAQAEAAYKYQt2sQBtAQAAAA==.Elyssae:BAABNQAECoEkAAIGAAgKbiG/RwDlAgAGAAgKbiG/RwDlAgAAAA==.',
En='Endarios:BAAANQAECgQIDgAAAA==.Endsplit:BAABNQAECoEXAAIGAAcKBgNjJAEpAQAGAAcKBgNjJAEpAQAAAA==.Ent:BAAANQAECgUIDAAAAA==.',
Er='Erzalockhart:BAAANQAECgMICQAAAA==.',
Es='Esmaralda:BAAANQADCggIGwAAAA==.',
Et='Etnie:BAAANQADCgYIBgAAAA==.',
Ev='Everleaf:BAAANQADCgQIBgAAAA==.Eviion:BAABNQAECoEbAAMTAAgK6xiHQAA0AgATAAgK6xiHQAA0AgAUAAIKtgeRAQFQAAABNQAECgkJIgAeAEwNAA==.',
Ez='Ezoth:BAAANQAECgQIBwAAAA==.',
Fa='Fallendivine:BAABNQAECoEkAAIGAAgKtAzLxADXAQAGAAgKtAzLxADXAQAAAA==.Fausts:BAAANQAECggICgAAAA==.',
Fe='Fearen:BAAANQAECgcIBwAAAA==.Feetenjoyer:BAAANQADCgMJAwAAAA==.Feipo:BAACNQAFFIEGAAMSAAMKtRVZBQClAAASAAIKLBhZBQClAAAGAAEKxhBbTQBSAAA1AAQKgSIAAgYACQo0HL+gACACAAYACQo0HL+gACACAAAA.Felissa:BAAANQAECgMIBgABNQAECgUIDgAOAAAAAA==.Fensmage:BAAANQAECgcIDgAAAA==.Feralbuffkty:BAABNQAECoEfAAIXAAkKKx9WJQCJAgAXAAkKKx9WJQCJAgABNQAFFAQIBwAbADITAA==.Fere:BAABNQAECoEfAAIiAAgKSiA9BAC4AgAiAAgKSiA9BAC4AgAAAA==.Feurekt:BAABNQAECoFGAAIJAAgKKiH/MQDkAgAJAAgKKiH/MQDkAgAAAA==.',
Fi='Finitaur:BAAANQADCgQIBwAAAA==.Fiz:BAAANQADCggICAABNQAFFAQICAAMAH8JAA==.',
Fl='Flashinlight:BAAANQAECgUIEgAAAA==.Flashstép:BAABNQAECoEaAAMYAAgK+xAfGAAKAgAYAAgK+xAfGAAKAgANAAEKpgdgiQA2AAAAAA==.Flipside:BAABNQAECoEcAAIEAAgKnhouRgBzAgAEAAgKnhouRgBzAgAAAA==.',
Fo='Fomor:BAAANQAECgYIEQAAAA==.Forbs:BAAANQAECgMIBAAAAA==.Foreignerr:BAACNQAFFIEJAAIJAAUKNBf5DQCjAQAJAAUKNBf5DQCjAQA1AAQKgScAAgkACQpZIfsfACkDAAkACQpZIfsfACkDAAAA.',
Fr='Franziscka:BAAANQADCggIIwAAAA==.Friggincute:BAAANQADCgEIAQAAAA==.Frogstomp:BAAANQADCggIDAAAAA==.',
Fu='Furbold:BAAANQAECgYIEQABNQAECggIEgAOAAAAAA==.',
['Få']='Fåe:BAAANQAECgEIAQAAAA==.',
['Fí']='Fíredup:BAAANQAECgUIDgABNQAECgkJHwAJAP8XAA==.',
Ga='Galeira:BAAANQAECgQICwAAAA==.Gallene:BAACNQAFFIERAAIJAAUKfB3CDACzAQAJAAUKfB3CDACzAQA1AAQKgU4AAgkACQo8JWIHALMDAAkACQo8JWIHALMDAAAA.Gandallf:BAAANQADCgUIEQABNQAECgQIDQAOAAAAAA==.Garakarak:BAAANQAECgYIDwAAAA==.Garthinian:BAAANQADCgYICQAAAA==.Garthpally:BAAANQAECgUIDQAAAA==.',
Ge='Genimaculata:BAABNQAECoEhAAIQAAcKKB+WCQBmAgAQAAcKKB+WCQBmAgAAAA==.Germ:BAAANQADCgIIAgAAAA==.Gerothos:BAAANQADCgQIBAAAAA==.Geîsha:BAAANQADCgMIAwAAAA==.',
Gh='Ghislaine:BAAANQADCggIDQABNQAECgcIDQAOAAAAAA==.Ghöst:BAAANQAECgcICgABNQAECggICgAOAAAAAA==.',
Gi='Girthquake:BAAANQAECgYIDgABNQAECggIKAAJAG0jAA==.',
Gl='Gladios:BAAANQAECgEJAwAAAA==.Glarry:BAAANQADCggICAABNQAECgkJHgADAC8eAA==.Glidelicator:BAABNQAECoElAAIfAAgK2A7+MwDaAQAfAAgK2A7+MwDaAQAAAA==.Glittervein:BAAANQADCgUIBQABNQADCgMIAwAOAAAAAA==.',
Go='Goodasnew:BAAANQADCggJGwAAAA==.Gooditoshoes:BAAANQAECgMIBQAAAA==.Gortopia:BAAANQADCgYIDwAAAA==.Goshin:BAAANQADCgYICQAAAA==.Gosublood:BAABNQAECoEUAAIEAAcKmR04VQBJAgAEAAcKmR04VQBJAgABNQAECggIGQABADQiAA==.Gosupriest:BAABNQAECoEZAAMBAAgKNCL4FAASAwABAAgKNCL4FAASAwAaAAMKRg9MTwCpAAAAAA==.Gozhancesham:BAAANQADCgUIBQAAAA==.',
Gr='Graggy:BAABNQAECoEeAAMDAAkKLx6+FAAcAwADAAkKLx6+FAAcAwAFAAEKmwtecQE2AAAAAA==.Grapejelly:BAABNQAECoEoAAIcAAgK5x95DwDnAgAcAAgK5x95DwDnAgAAAA==.Grashk:BAABNQAECoEXAAIJAAcKage8ugBYAQAJAAcKage8ugBYAQAAAA==.Grimbel:BAABNQAECoEXAAIUAAcK/w0edgCPAQAUAAcK/w0edgCPAQAAAA==.Grimcritical:BAAANQAECgMIBAAAAA==.',
['Gø']='Gødspeed:BAAANQAECgcICgAAAA==.',
Ha='Hadeshunt:BAABNQAECoEhAAIEAAYKiBJ9mwCdAQAEAAYKiBJ9mwCdAQAAAA==.Halibelle:BAAANQADCgYJBgAAAA==.Halzarius:BAABNQAECoEXAAIGAAUKHRT9BwFZAQAGAAUKHRT9BwFZAQAAAA==.Handyshammy:BAABNQAECoEwAAIjAAgKCyIABwADAwAjAAgKCyIABwADAwAAAA==.Handywar:BAABNQAECoEaAAIJAAcKTBiiiwDYAQAJAAcKTBiiiwDYAQABNQAECggIMAAjAAsiAA==.Hans:BAAANQAECgUIEwAAAA==.Happyheala:BAAANQAECgUIBgAAAA==.Harleybear:BAAANQAECgEIAgAAAA==.',
Hi='Hitamnya:BAAANQAECgEIAQABNQAECgkJIgAeAEwNAA==.',
Ho='Holyknox:BAAANQAECggIEgAAAA==.Holymender:BAAANQAECgEIAQAAAA==.Holymick:BAAANQAECggIDgAAAA==.',
Hu='Hulkamania:BAAANQADCgUICAAAAA==.Humble:BAABNQAECoEXAAIQAAgKmxXhDQD6AQAQAAgKmxXhDQD6AQAAAA==.',
Hy='Hydromender:BAABNQAECoEVAAITAAgKyx8aHwDRAgATAAgKyx8aHwDRAgAAAA==.Hyperactiv:BAAANQAECgUIDgAAAA==.Hypothermia:BAAANQAECgMIBAABNQAECgYIEgAOAAAAAA==.',
['Hô']='Hôllôw:BAAANQAECggIDgAAAA==.',
['Hø']='Høpeless:BAABNQAECoEfAAIDAAgK+xGgUgACAgADAAgK+xGgUgACAgAAAA==.',
Ic='Icyblast:BAAANQAECgMIBgAAAA==.Icycookiex:BAABNQAECoEUAAMHAAkK9RKSEQB+AgAHAAkK9RKSEQB+AgAIAAEKfASKPAApAAABNQAECgkJFwADANcUAA==.Icymilkyx:BAABNQAECoEXAAMDAAkK1xTAPQBPAgADAAkK1xTAPQBPAgAFAAYKOQth4QAeAQAAAA==.',
Id='Idriel:BAAANQAECgMIAwABNQAECggIGgAJAKIfAA==.',
Ig='Igneel:BAAANQAECgEIAQABNQAECgMICAAOAAAAAA==.',
Il='Illigniteyou:BAABNQAECoFJAAIGAAgKGiPmMgAZAwAGAAgKGiPmMgAZAwAAAA==.Illiranii:BAAANQADCgYIBgABNQAECgUIBwAOAAAAAA==.Illumine:BAAANQAECgMIBAAAAA==.',
In='Inosolan:BAAANQAECgUIEgAAAA==.Inurfacevegi:BAAANQAECgUICQAAAA==.',
Io='Iolololol:BAAANQAECgUIDQABNQAFFAIIBQAXAJwGAA==.Iozt:BAAANQAFFAEIAQAAAA==.',
Ir='Ironpork:BAAANQADCgcIBwAAAA==.Irralis:BAAANQAECgUIBQABNQAFFAYIFwAGALUkAA==.Irritable:BAABNQAECoEVAAIFAAYKSxTZswB+AQAFAAYKSxTZswB+AQAAAA==.Irvina:BAABNQAECoElAAIEAAcKgBsLaQAWAgAEAAcKgBsLaQAWAgAAAA==.Irvinebrown:BAAANQADCgIIBAABNQAECgcIJQAEAIAbAA==.Irvinia:BAAANQADCggIHAABNQAECgcIJQAEAIAbAA==.',
Is='Iskarius:BAAANQAECgYIDQAAAA==.Istenn:BAAANQAECgUIDQAAAA==.',
It='Ithyl:BAAANQAECgMICgAAAA==.Itzshammy:BAABNQAECoEkAAITAAgK7yNUEAAsAwATAAgK7yNUEAAsAwAAAA==.',
Iv='Ivanoviaa:BAAANQADCgMIAwAAAA==.',
Ix='Ixiöm:BAAANQAECgEIAQABNQAECggICgAOAAAAAA==.',
Ja='Jabmojorjo:BAAANQADCgMIAwAAAA==.Jackdaw:BAAANQABCgIIAgAAAA==.Janinda:BAABNQAECoEhAAIFAAgKmCWbJQAVAwAFAAgKmCWbJQAVAwAAAA==.Jassix:BAAANQAECgIIAgAAAA==.Jastina:BAABNQAECoEWAAIGAAYK7hjRzwDBAQAGAAYK7hjRzwDBAQAAAA==.Jaszz:BAABNQAECoEZAAMVAAgKQw+uJgC8AQAVAAgKQw+uJgC8AQAPAAEK/ATyogAvAAAAAA==.',
Jb='Jb:BAAANQAECgcICAAAAA==.',
Je='Jelly:BAAANQADCggIFgAAAA==.Jengil:BAAANQAECgQIBgAAAA==.Jengol:BAAANQAECgEIAQAAAA==.Jesto:BAABNQAECoExAAIRAAkKrx6hBQD2AgARAAkKrx6hBQD2AgAAAA==.',
Jh='Jhonn:BAABNQAECoEUAAIFAAcKrAvu8gD+AAAFAAcKrAvu8gD+AAAAAA==.',
Ji='Jincuiki:BAAANQAECgIIAgAAAA==.Jixni:BAAANQAECgEIAQABNQAECggIGQAWAIUkAA==.',
Jo='Jodiefroster:BAAANQAECgEIAgAAAA==.Joeseppe:BAAANQAECgYIEAABNQAECggIJAAWAFIcAA==.Joeslildk:BAABNQAECoEkAAMWAAgKUhx/IQCPAgAWAAgKUhx/IQCPAgAXAAYKxAwzcgAnAQAAAA==.Joshst:BAAANQAECgEIAQAAAA==.Josta:BAABNQAECoEWAAIQAAgKShUcDQAMAgAQAAgKShUcDQAMAgABNQAECgkJMQARAK8eAA==.Josto:BAAANQAECgYICgABNQAECgkJMQARAK8eAA==.Jovyll:BAAANQAECgYIEwAAAA==.Joyboyluffy:BAAANQAECgQIBQAAAA==.',
Ju='Jurodice:BAABNQAECoEgAAIDAAkKLQpuXQDdAQADAAkKLQpuXQDdAQAAAA==.',
['Jå']='Jårko:BAAANQADCgYIDQAAAA==.',
Ka='Kaahla:BAAANQADCgEIAQAAAA==.Kaelinth:BAAANQADCgcICgAAAA==.Kaelyth:BAABNQAECoEZAAIkAAYKxxq8DADHAQAkAAYKxxq8DADHAQAAAA==.Kamakazie:BAAANQAECgQICAAAAA==.Kamelle:BAAANQAECgEIAgAAAA==.Karmerre:BAAANQAECgQIBwAAAA==.Karramerre:BAAANQADCgUIBQABNQAECgQIBwAOAAAAAA==.Kaydeebug:BAAANQAECgQIDwAAAA==.Kayna:BAABNQAECoEkAAICAAcKdA4JMABiAQACAAcKdA4JMABiAQAAAA==.',
Ke='Kellanis:BAABNQAECoEYAAIfAAYKsAqbSwA5AQAfAAYKsAqbSwA5AQAAAA==.Kelugar:BAAANQADCgIIAgAAAA==.Kerenarye:BAACNQAFFIEHAAIkAAQKux4UAQCDAQAkAAQKux4UAQCDAQA1AAQKgRQAAyQACQrPH9UDAPMCACQACAotItUDAPMCABwABwoKCvg2AGUBAAAA.Keyez:BAAANQAECgYIDgABNQAECggIHAAaAKILAA==.',
Kh='Khaladore:BAABNQAECoEXAAIDAAgKfh6PIQDQAgADAAgKfh6PIQDQAgAAAA==.Kharazhan:BAABNQAECoEYAAIPAAcKBRVNPwDUAQAPAAcKBRVNPwDUAQAAAA==.',
Ki='Kiilbill:BAAANQAECgMIDAABNQAECgUIFAAWAMIdAA==.Killshotbob:BAAANQAECgQIDQAAAA==.Kinkyheaven:BAAANQAECgQIBwAAAA==.Kinnigit:BAABNQAECoEoAAIdAAgK1Ad+VQAJAQAdAAgK1Ad+VQAJAQAAAA==.Kinstalz:BAAANQAECgYIDQAAAA==.Kiotia:BAAANQADCgYIFQAAAA==.Kipp:BAABNQAECoEUAAIEAAcKuyHIPwCHAgAEAAcKuyHIPwCHAgAAAA==.Kiril:BAAANQADCgUIBQAAAA==.Kirky:BAAANQADCgUJCgAAAA==.Kitenna:BAAANQADCgQIBQABNQAECgcIGwARAJoNAA==.Kithraah:BAABNQAECoEdAAMdAAgKjBDTOQCqAQAdAAgK/g7TOQCqAQAXAAcKyww3aQBIAQABNQAFFAIIAwAOAAAAAA==.Kithrah:BAAANQAFFAIIAwAAAA==.Kithrâh:BAAANQAECgEIAQABNQAFFAIIAwAOAAAAAA==.',
Kn='Knifeparty:BAAANQAECgYIEwAAAA==.',
Ko='Kolugar:BAACNQAFFIEGAAIWAAMK8hXuEwDoAAAWAAMK8hXuEwDoAAA1AAQKgSUAAhYACQoRJG8HAHYDABYACQoRJG8HAHYDAAAA.Kommando:BAAANQADCggICAAAAA==.Konkar:BAABNQAECoEbAAMXAAkKHhoiJgCEAgAXAAkKHhoiJgCEAgAWAAEK0gyswgAqAAAAAA==.',
Kr='Kradon:BAAANQAECgYIEAAAAA==.Krakras:BAAANQAECgEIAQAAAA==.Kreedan:BAAANQADCgcJBwABNQAECgcIHAAJAIwXAA==.Kruphix:BAABNQAECoEdAAMbAAkKwxrhBgDOAgAbAAkKlRrhBgDOAgAZAAQKiBatLADrAAAAAA==.Krysania:BAAANQADCgQIBAABNQAECggIFwADAH4eAA==.',
Ku='Kudreanne:BAAANQAECgEIAQAAAA==.Kuri:BAAANQADCggICAAAAA==.Kuzzo:BAAANQAECgIIAgAAAA==.',
La='Lacerta:BAAANQADCgEIAQAAAA==.Laiceeshay:BAABNQAECoEqAAIEAAkKXhOaRwBvAgAEAAkKXhOaRwBvAgAAAA==.Lars:BAABNQAECoEUAAILAAcKFhTzEgDRAQALAAcKFhTzEgDRAQAAAA==.Larxe:BAABNQAECoELAAIcAAYKww4eNgBsAQAcAAYKww4eNgBsAQAAAA==.',
Le='Legendaïry:BAAANQAECgUIDAAAAA==.Letmedie:BAABNQAECoEjAAMhAAYKOAykEwA+AQAhAAYKLAykEwA+AQAJAAYKzwa8zwAdAQAAAA==.Lexillo:BAAANQAECgUICgAAAA==.',
Li='Liaravara:BAAANQAECgEIAgABNQAECgUICQAOAAAAAA==.Lightmender:BAAANQADCgQIBAAAAA==.Lightschamp:BAAANQADCgQIBAABNQAECgUICQAOAAAAAA==.Lilhunty:BAAANQADCgMIAwAAAA==.Lilldemon:BAAANQADCgcIDgAAAA==.Lizzo:BAABNQAECoEoAAMHAAgKkxw6EACSAgAHAAgKkxw6EACSAgAIAAIKmAj/MQBfAAAAAA==.',
Lo='Locksorry:BAAANQAECgEIAQABNQAFFAUJCwAKAGUOAA==.Lokrox:BAAANQADCgEIAQABNQAECgkJHwAJAP8XAA==.Lorieyxo:BAAANQAECgMICgAAAA==.Lorrim:BAAANQAECgUIEQAAAA==.Loungedancer:BAAANQAECggIAQAAAA==.Louron:BAAANQAECgEIAQAAAA==.',
Lu='Luena:BAAANQAECgcIBwAAAA==.Lunabi:BAABNQAECoEZAAIdAAkKAx72GQCUAgAdAAkKAx72GQCUAgABNQAFFAMIBwACAIoQAA==.Lute:BAAANQADCgYIBgAAAA==.Luxdae:BAAANQADCgEIAQAAAA==.',
Ly='Lyrannia:BAABNQAECoEhAAIGAAgKGxv6dwB4AgAGAAgKGxv6dwB4AgAAAA==.Lyrindanna:BAAANQADCgEIAQAAAA==.Lyth:BAABNQAECoEkAAIQAAgKGB/ZBgC5AgAQAAgKGB/ZBgC5AgAAAA==.',
['Lá']='Láiken:BAAANQADCgYJGwAAAA==.',
Ma='Madmoxxie:BAAANQADCgUIBQAAAA==.Mageapayne:BAAANQADCgYJBgAAAA==.Magetom:BAAANQAECgEIAgAAAA==.Maghan:BAAANQADCgQICAAAAA==.Magicus:BAABNQAECoEWAAIGAAkKlxRpfgBpAgAGAAkKlxRpfgBpAgAAAA==.Magikaze:BAABNQAECoEdAAIGAAgKKyHzRwDkAgAGAAgKKyHzRwDkAgAAAA==.Mahgo:BAAANQAECgYICwAAAA==.Maidenkio:BAAANQADCgEIAQAAAA==.Maikara:BAAANQAECgQICQAAAA==.Majinoodle:BAAANQADCgcIBwAAAA==.Malfalcator:BAAANQAECgYIBwAAAA==.Man:BAAANQAECgEIAgAAAA==.Mantori:BAAANQADCgEIAQAAAA==.Marieh:BAAANQAECgMICQAAAA==.Marleer:BAAANQADCggICAABNQAECgcIGQATAOAcAA==.Martha:BAAANQAECgEIAwAAAA==.Maryberry:BAAANQAECgQIBAAAAA==.Massan:BAAANQADCgUICQAAAA==.Masscarnage:BAABNQAECoErAAIKAAgKPx3sMQCmAgAKAAgKPx3sMQCmAgAAAA==.Maywina:BAABNQAECoEcAAIGAAgKAiKbRQDqAgAGAAgKAiKbRQDqAgABNQAECgkJMwAPAP4gAA==.Mazhun:BAABNQAECoEZAAIEAAcKMAoOlwCnAQAEAAcKMAoOlwCnAQAAAA==.',
Me='Meaculpa:BAABNQAECoEjAAMFAAcKtxVKkgDLAQAFAAcKtxVKkgDLAQADAAUKGQTVwwDLAAAAAA==.Mediqua:BAAANQADCgQIAQAAAA==.Megaflame:BAAANQADCgYIHgAAAA==.Mekkii:BAAANQADCgIIAgABNQAFFAIIBQAXAJwGAA==.Mekky:BAACNQAFFIEFAAIXAAIKnAbLFwB+AAAXAAIKnAbLFwB+AAA1AAQKgSgAAhcACQqMGtMrAGQCABcACQqMGtMrAGQCAAAA.Melonheadx:BAAANQADCgIIAgAAAA==.Meltharion:BAAANQAECgMIBgAAAA==.Mercerful:BAAANQADCgUICQAAAA==.Mereaux:BAAANQADCggICwAAAA==.Methex:BAAANQAECggIEgAAAA==.Metzger:BAAANQAECgMICgAAAA==.',
Mi='Mickius:BAAANQAECggIAQABNQAECggIDgAOAAAAAA==.Mingi:BAAANQADCggIGgABNQAECgcIHAALAAEYAA==.Minigore:BAABNQAECoExAAIEAAgKRCHEIgDvAgAEAAgKRCHEIgDvAgAAAA==.Mirya:BAAANQAECgMICgAAAA==.Mishamigo:BAABNQAECoEbAAMBAAcK7SRyHADoAgABAAcK7SRyHADoAgAlAAEKkxu8HwBPAAAAAA==.Missharmony:BAABNQAECoEUAAIPAAYKxw//VQBVAQAPAAYKxw//VQBVAQAAAA==.Misstickles:BAAANQAECgQICwAAAA==.',
Mo='Moistfisting:BAAANQADCggICAABNQAFFAQIDQAPAMEWAA==.Moistpawjob:BAACNQAFFIENAAIPAAQKwRalDgBKAQAPAAQKwRalDgBKAQA1AAQKgSYAAw8ACQr7JBsMAFsDAA8ACQr7JBsMAFsDABUAAgoOG5pSAI4AAAAA.Moistpole:BAAANQAECgEIAQAAAA==.Mojostormale:BAAANQADCgEIAQAAAA==.Monanarr:BAAANQADCgEIAgABNQAECgQIDQAOAAAAAA==.Monmonk:BAAANQAECgQIDQAAAA==.Monotok:BAAANQADCgUIBQAAAA==.Moograin:BAAANQABCgQIBAAAAA==.Moonalisa:BAAANQAECgEIAQAAAA==.Moondropz:BAAANQAECgMIBwAAAA==.Moonsblood:BAAANQAECgYIEwAAAA==.Moontara:BAAANQAECgcIEAAAAA==.Moopsy:BAABNQAECoEfAAIWAAYKSiFtLwA4AgAWAAYKSiFtLwA4AgAAAA==.Mops:BAAANQAECgQICgAAAA==.',
Mu='Muldoom:BAAANQAECgEIBAAAAA==.Mur:BAABNQAECoEXAAMGAAcKAReWtAD3AQAGAAcKrxaWtAD3AQAmAAEKphtkCQBSAAAAAA==.Murdertoys:BAAANQAECgEIAQAAAA==.',
My='Mycotoxin:BAAANQAECgYIDAAAAA==.Myoxidae:BAAANQADCgEIAQAAAA==.Myrrdan:BAABNQAECoEUAAIFAAgKjRQSeAAMAgAFAAgKjRQSeAAMAgAAAA==.Myrrh:BAAANQADCgEIAQAAAA==.Mysst:BAABNQAECoEXAAIBAAYKHAj8lQAYAQABAAYKHAj8lQAYAQAAAA==.Mysteerie:BAABNQAECoEZAAIMAAcKzQgtDQBgAQAMAAcKzQgtDQBgAQAAAA==.Mythlogic:BAABNQAECoEgAAMVAAYKhgw9OgAXAQAVAAYKhgw9OgAXAQAPAAEK3wc2rQAiAAAAAA==.Mythsham:BAAANQAECgQIBQAAAA==.',
['Má']='Mángo:BAABNQAECoEeAAMKAAgKaBICcADnAQAKAAgKeRACcADnAQALAAUKFws0LgAHAQAAAA==.',
['Mí']='Místress:BAAANQAECgQIBgAAAA==.',
['Mù']='Mùshu:BAAANQADCgYIBgAAAA==.',
Na='Nardaran:BAAANQAECggIDQAAAA==.Natsumi:BAAANQAECgMIBQABNQAECgkJMQAWACIgAA==.',
Ne='Needcoffee:BAAANQAECgMIBAAAAA==.Neemixa:BAAANQAECgMICAAAAA==.Neonh:BAAANQAECgQIBwAAAA==.Nereval:BAAANQAECgYIEAABNQAECgkJMwAPAP4gAA==.Nezzidecay:BAAANQAECgEIAQAAAA==.',
Ni='Nicksshaman:BAAANQADCgEIAQAAAA==.Nightwissh:BAABNQAECoEZAAMJAAYKyBsyiQDfAQAJAAYK+RoyiQDfAQAhAAEKLCQ9JABoAAAAAA==.Nitestar:BAAANQADCgcIEwAAAA==.Nitevoker:BAAANQAECgMIBwAAAA==.',
No='Nocturnus:BAAANQADCgQJDAAAAA==.Nordvoker:BAABNQAECoEcAAIHAAgKtwm9IgCSAQAHAAgKtwm9IgCSAQAAAA==.Nospheratu:BAABNQAECoE8AAIGAAkK0RsDWwC3AgAGAAkK0RsDWwC3AgABNQADCgYIBgAOAAAAAA==.',
Nu='Nubu:BAAANQADCggIHAAAAA==.Nukin:BAAANQAECgEIAQAAAA==.',
Ny='Nycepala:BAAANQAECgQIBwAAAA==.Nylaith:BAAANQADCgUIBQAAAA==.Nyni:BAECNQAFFIESAAIWAAUKoguBEAAZAQAWAAUKoguBEAAZAQA1AAQKgSoAAhYACQpFGTckAH0CABYACQpFGTckAH0CAAAA.Nythshade:BAAANQADCgcIDAAAAA==.Nyxe:BAEANQAECgYIBwABNQAFFAUIEgAWAKILAA==.',
['Nü']='Nümnüts:BAAANQAECgIIBgAAAA==.',
Of='Offworlder:BAAANQAECgQIBwAAAA==.',
Ol='Olokun:BAAANQABCgYJBwAAAA==.',
On='Onlyhoofs:BAEBNQAECoEjAAITAAkKkBs+KAChAgATAAkKkBs+KAChAgAAAA==.Onyq:BAAANQAECgYIBwABNQAFFAQIBwAkALseAA==.',
Oo='Oofm:BAABNQAECoEhAAMQAAgKtgo9GwAKAQAQAAcKrwY9GwAKAQACAAMKsg+8RQC7AAAAAA==.Oospider:BAAANQAECgMIDgAAAA==.',
Op='Ophearia:BAAANQAECgEIAQAAAA==.Optimiss:BAABNQAECoEVAAIVAAcK0xWCJQDIAQAVAAcK0xWCJQDIAQAAAA==.',
Or='Orcboy:BAABNQAECoEcAAIJAAcKjBfHgQDzAQAJAAcKjBfHgQDzAQAAAA==.Ordia:BAAANQAECgEIAQAAAA==.Orken:BAAANQADCgEIAQAAAA==.Orthanu:BAAANQADCgUIBQAAAA==.',
Os='Osamul:BAAANQADCgYIBgAAAA==.',
Oz='Ozmagic:BAAANQADCgMIAwAAAA==.Ozxenia:BAAANQAECgUIBwAAAA==.',
Pa='Pacha:BAAANQAFFAQIBAABNQAFFAQIBwAkALseAA==.Paieth:BAABNQAECoEXAAIFAAcKjQaW3AAoAQAFAAcKjQaW3AAoAQAAAA==.Palacid:BAAANQAECggICAAAAA==.Paladerp:BAABNQAECoEoAAIDAAgK7ibHBACfAwADAAgK7ibHBACfAwAAAA==.Palaresx:BAAANQAECgQIBwABNQAECgkJHgAQAF4cAA==.Palean:BAAANQAECgEIAQAAAA==.Pallyshunter:BAABNQAECoErAAIEAAgKxh3wNACqAgAEAAgKxh3wNACqAgAAAA==.Pancake:BAAANQAECgQICQAAAA==.Panchamp:BAAANQADCgcJDgAAAA==.Pandamourne:BAAANQAECgEIAgAAAA==.Pandori:BAABNQAECoEhAAITAAcKUibiFgAAAwATAAcKUibiFgAAAwAAAA==.Panetar:BAAANQAECgEIAwAAAA==.Parchmentham:BAABNQAECoEgAAMBAAgKnRtgPQBQAgABAAgKnRtgPQBQAgAaAAEKnhAzbwAwAAAAAA==.Paryniux:BAAANQAECgMIBQAAAA==.Patience:BAAANQAECggIBwAAAA==.',
Pe='Peridrax:BAAANQAECgEIAQAAAA==.',
Ph='Phenergen:BAAANQAECgQIBAABNQAECgQIBwAOAAAAAA==.',
Pi='Pinchiy:BAAANQADCgQIBAAAAA==.Pinkpanthir:BAABNQAECoEUAAIEAAcKuBOLewDoAQAEAAcKuBOLewDoAQAAAA==.',
Pj='Pjay:BAAANQAECgUICAAAAA==.',
Pl='Plisky:BAAANQAECgQIBwAAAA==.',
Po='Pollywaffle:BAAANQADCggIDAAAAA==.Portals:BAAANQADCggIEAAAAA==.Poùnd:BAAANQAECgIIAgABNQAECgkJHwAJAP8XAA==.',
Pr='Praiseme:BAAANQADCgYIEwAAAA==.Predz:BAABNQAECoEYAAMXAAcKLR66RADgAQAXAAYKJR26RADgAQAWAAYKvxvDSQCxAQAAAA==.Predzious:BAAANQAECgQICQABNQAECgcIGAAXAC0eAA==.Prepaired:BAAANQADCggICAABNQAFFAcIHQAMANAaAA==.Pretzelmix:BAAANQADCgYIBgAAAA==.Priestiitute:BAAANQAECgEIAQAAAA==.',
Ps='Psyreq:BAAANQAECgUICgAAAA==.',
Pu='Pucker:BAAANQADCgQIBAAAAA==.Punkey:BAABNQAECoEYAAIEAAcKqByeRgByAgAEAAcKqByeRgByAgAAAA==.Purplemad:BAAANQADCgEIAQAAAA==.',
Qu='Quartquartma:BAAANQAECgUIEAAAAA==.',
Ra='Raedia:BAAANQADCgMIAwAAAA==.Raft:BAAANQADCggICAAAAA==.Rahll:BAAANQABCggIDgAAAA==.Raindrops:BAAANQAECgQIBAAAAA==.Rainsberg:BAAANQAECgIIAgAAAA==.Raje:BAAANQADCggIDgAAAA==.Ravachiar:BAABNQAECoEfAAIcAAYKVheDLgCrAQAcAAYKVheDLgCrAQABNQAECggIGQAJABcUAA==.Ravenathas:BAAANQADCgUIEgABNQAECgQIDAAOAAAAAA==.Ravenimus:BAAANQAECgQIDAAAAA==.Ravic:BAAANQAECggIEgAAAA==.Razeld:BAAANQAECgQIBwAAAA==.Razhun:BAABNQAECoEXAAIEAAYK4wo/tQBlAQAEAAYK4wo/tQBlAQAAAA==.Razia:BAAANQAECgMICQAAAA==.Razzax:BAAANQADCgUIBQAAAA==.Razzmata:BAABNQAECoEeAAIFAAgKaRyyTgCBAgAFAAgKaRyyTgCBAgAAAA==.',
Re='Reckendorf:BAAANQAECgEIAgAAAA==.Redefine:BAAANQAECgUIDAAAAA==.Reflet:BAAANQAECgUJCAAAAA==.Relay:BAAANQAECgEIBAAAAA==.Rell:BAAANQAECgYICQAAAA==.Rentress:BAAANQADCgYIFwAAAA==.Resolution:BAAANQADCggICAAAAA==.Restik:BAAANQADCggIFQAAAA==.Revyre:BAAANQAECgQJBQAAAA==.Rexxnaar:BAAANQAECgQIDAAAAA==.Rexy:BAABNQAECoEiAAMVAAkKjiDODQDXAgAVAAgK8SDODQDXAgAPAAkKgxqMHQDCAgAAAA==.',
Rh='Rhiari:BAAANQADCggICAABNQAECgcIDQAOAAAAAA==.Rhiotannis:BAAANQAECgYIDAAAAA==.Rhombus:BAAANQADCgYIBgAAAA==.Rhots:BAABNQAECoEWAAMMAAcKfQ4hCgCuAQAMAAcK5w0hCgCuAQAKAAQK9Q8m0AD8AAAAAA==.',
Ri='Ricketyrekt:BAAANQADCgcIBwAAAA==.Rimara:BAABNQAECoEbAAILAAYKpwhTKgAeAQALAAYKpwhTKgAeAQAAAA==.Rishari:BAAANQAECgMICAAAAA==.',
Ro='Rocadin:BAAANQAECgcIEwAAAA==.Rocmon:BAAANQADCgYIBgABNQAECgcIEwAOAAAAAA==.Rorisala:BAAANQADCgYICwABNQAECgUIDAAOAAAAAA==.Rottlee:BAAANQAECgMIBAAAAA==.Rowshamboe:BAAANQAECgEIAQAAAA==.Rozabella:BAABNQAECoEhAAIPAAcK0Rr6MQAtAgAPAAcK0Rr6MQAtAgAAAA==.',
Ru='Rune:BAAANQAECgIIAwABNQAECggIFgAcAMEWAA==.',
['Rê']='Rêdemption:BAAANQAECgIIBAAAAA==.Rêdylive:BAABNQAECoEUAAIUAAcKdAlIsAADAQAUAAcKdAlIsAADAQAAAA==.',
['Rï']='Rïkku:BAAANQAECgYJCwAAAA==.',
['Rø']='Røgue:BAAANQADCgIIBQABNQAECgMIBQAOAAAAAA==.',
Sa='Sacricola:BAAANQADCgYIBgAAAA==.Saelska:BAAANQAECgEIAgAAAA==.Sahven:BAAANQADCgYICQAAAA==.Sakuraharu:BAABNQAECoEmAAIGAAcK1RcfuADwAQAGAAcK1RcfuADwAQAAAA==.Sakuraharune:BAABNQAECoEbAAIKAAcKkhRFeADPAQAKAAcKkhRFeADPAQAAAA==.Sakuraharuno:BAABNQAECoErAAIYAAkKyh/TBAA7AwAYAAkKyh/TBAA7AwAAAA==.Sakuura:BAABNQAECoEWAAIEAAcKHx4NSwBlAgAEAAcKHx4NSwBlAgAAAA==.Sarang:BAABNQAECoEUAAMTAAgKtRKeewBqAQATAAcKcRGeewBqAQAUAAYK+xKQiABeAQAAAA==.Sashay:BAAANQADCgcIBwABNQAECgcIGQAEAP0VAA==.Sassystrasza:BAAANQADCgQIBAAAAA==.Savagepaw:BAAANQAECgcIEQAAAA==.',
Sc='Scarbi:BAAANQAECgIIAwAAAA==.Scarbz:BAABNQAECoEaAAIGAAgKJgTABgFbAQAGAAgKJgTABgFbAQAAAA==.Scrtchnsniff:BAAANQABCgQIAwAAAA==.',
Se='Sehun:BAAANQADCggIHQABNQAECgcIHAALAAEYAA==.Selennys:BAAANQAECgQICQAAAA==.Selest:BAAANQAECgQICAAAAA==.Selinfel:BAAANQAECgEIAQAAAA==.',
Sh='Shadey:BAAANQADCgMIAwAAAA==.Shadowkain:BAABNQAECoEXAAIEAAcKmAk3nQCaAQAEAAcKmAk3nQCaAQAAAA==.Shadowtrix:BAAANQAECgEIAQAAAA==.Shadøws:BAABNQAECoEhAAIYAAgKTgwcGwDrAQAYAAgKTgwcGwDrAQAAAA==.Shagz:BAAANQAECgEIAQAAAA==.Shallios:BAAANQADCgYIEAAAAA==.Shamajov:BAAANQADCgYIDgABNQAECgYIEwAOAAAAAA==.Shamankiing:BAAANQAECgEIBAAAAA==.Shamannigans:BAAANQAECgQIDwAAAA==.Shammyhagar:BAAANQAECgQICAAAAA==.Shamnow:BAAANQAECgEIAQAAAA==.Shanthi:BAAANQAECgEIAQABNQAECgYIIAAVAIYMAA==.Sharkweek:BAAANQAECgYIBwABNQAECgkJHgAQAF4cAA==.Shaytan:BAAANQAECgQIEgAAAA==.Sheogorath:BAABNQAECoEsAAIgAAkKwR6lBwAOAwAgAAkKwR6lBwAOAwAAAA==.Shioñ:BAAANQADCggICAAAAA==.Shocksocks:BAABNQAECoEcAAITAAgKLxuYNgBdAgATAAgKLxuYNgBdAgAAAA==.Shoujian:BAAANQAECgUIEQAAAA==.',
Si='Sianien:BAAANQAECggIEwAAAA==.Sickology:BAABNQAECoErAAIFAAkKKRL3ewACAgAFAAkKKRL3ewACAgAAAA==.Siinatra:BAABNQAECoEgAAMFAAkKESWALgDwAgAFAAcKNyWALgDwAgADAAkKaBiYJwCyAgAAAA==.Siinatrah:BAABNQAECoEgAAMFAAkKxiNDDgCGAwAFAAkKxiNDDgCGAwADAAMKZAndzwC0AAABNQAECgkJIAAFABElAA==.Silverstarr:BAAANQADCgYIDAAAAA==.Sinnafein:BAAANQADCgcIBwAAAA==.Siohban:BAAANQAECgUIEwAAAA==.Sionel:BAAANQADCgUIBQABNQADCgYICgAOAAAAAA==.Siphirahah:BAABNQAECoEVAAIZAAcKRAd+KAAMAQAZAAcKRAd+KAAMAQAAAA==.',
Sk='Skûrge:BAAANQAECgEIAgABNQAECgcIDQAOAAAAAA==.Skürge:BAAANQAECgcIDQAAAA==.',
Sl='Slapntits:BAAANQABCgcIDQAAAA==.Slimreaper:BAABNQAECoEYAAIfAAcKFR7MIgBeAgAfAAcKFR7MIgBeAgAAAA==.Slothination:BAACNQAFFIEHAAIbAAQKMhNDAQBZAQAbAAQKMhNDAQBZAQA1AAQKgR0AAhsACAqoIewEABADABsACAqoIewEABADAAAA.Slurrydots:BAABNQAECoEjAAMBAAkKjRz4FgAGAwABAAkKjRz4FgAGAwAaAAMKVgepWAB1AAAAAA==.',
Sm='Smellymango:BAAANQAECgMIBQAAAA==.',
Sn='Snaglvr:BAAANQADCgQJBQAAAA==.Snappyb:BAAANQADCgIIAgAAAA==.Snorichäun:BAAANQAECgYICgAAAA==.Snowtownz:BAABNQAECoEfAAMIAAgKRhlODgBeAgAIAAgKRhlODgBeAgAnAAIKOwr8HABPAAAAAA==.Snörichäun:BAAANQADCgcIEAAAAA==.Snöríchäûn:BAAANQAECgIIAgAAAA==.',
So='Sokraxx:BAACNQAFFIEGAAIRAAMKASR4AgAxAQARAAMKASR4AgAxAQA1AAQKgSEAAhEACQoeJkoJAIwCABEACQoeJkoJAIwCAAAA.Sonozap:BAABNQAECoEgAAMUAAkK+w50ZQDAAQAUAAgKeQ10ZQDAAQATAAYK5AaIogADAQAAAA==.Sonyc:BAAANQADCgQIBAAAAA==.Soothlocked:BAAANQAECgQICQAAAA==.Soraflash:BAAANQADCggICAAAAA==.Soulreaperau:BAAANQAECgEJAQAAAA==.',
Sp='Spearzy:BAAANQAECgcIDAABNQAECgkJHwAJAP8XAA==.Specticles:BAAANQAECgEIAgAAAA==.Spicedgoat:BAAANQAECgMICAAAAA==.Spinandwin:BAABNQAECoEoAAIJAAgKbSMwIAApAwAJAAgKbSMwIAApAwAAAA==.Springroll:BAABNQAECoEfAAICAAgKbB5CFgB1AgACAAgKbB5CFgB1AgAAAA==.',
Sq='Squishikayla:BAAANQADCgMIAwAAAA==.Squishyman:BAABNQAECoEgAAIGAAkKrRIUjwBGAgAGAAkKrRIUjwBGAgAAAA==.',
Sr='Sram:BAACNQAFFIEKAAMdAAUKkRc+BQB0AQAdAAQKlBw+BQB0AQAWAAEKhQOyNQAaAAA1AAQKgSUAAx0ACQohIvUJADgDAB0ACQohIvUJADgDABYAAQpzCIHFACcAAAAA.Srbenda:BAAANQADCgUJDgAAAA==.',
Ss='Sstormmy:BAABNQAECoEoAAIEAAgKGRTBWwA4AgAEAAgKGRTBWwA4AgAAAA==.',
St='Stabit:BAAANQAECgUICQAAAA==.Starless:BAAANQAECgQJBQAAAA==.Starmyst:BAAANQADCgYIBgAAAA==.Steelbull:BAABNQAECoEZAAIJAAgKFxTBdQATAgAJAAgKFxTBdQATAgAAAA==.Steelmyth:BAABNQAECoEZAAIkAAgKWBIXDQC/AQAkAAgKWBIXDQC/AQAAAA==.Steeven:BAAANQADCgIIAgAAAA==.Stev:BAAANQAECgEIAgAAAA==.Strìder:BAAANQAECgIIBQAAAA==.Strîder:BAABNQAECoEdAAIDAAcKJhAFcACgAQADAAcKJhAFcACgAQAAAA==.',
Su='Summerskye:BAABNQAECoEaAAIJAAgKoh/EPwCzAgAJAAgKoh/EPwCzAgAAAA==.',
Sy='Sy:BAABNQAECoEaAAMaAAcKPhyhHwAYAgAaAAcKPhyhHwAYAgABAAIKzxSd0wBcAAABNQAFFAIIBQAXAGsIAA==.Sycamore:BAAANQAECgUIDgAAAA==.Sydor:BAAANQAECgQICwAAAA==.Sylennia:BAAANQAECgMIBgAAAA==.Sylvatrix:BAAANQAECgUIEAAAAA==.Symbiont:BAAANQADCgcIGgAAAA==.',
Sz='Szarni:BAAANQAECgQIEgAAAA==.',
Ta='Tabitrisao:BAAANQAECgEIAQAAAA==.Talastor:BAAANQADCgMJAwAAAA==.Tamarin:BAAANQABCgIIAgAAAA==.Tamedshot:BAAANQAECgEIAQAAAA==.Taridalas:BAAANQAECgUIDAAAAA==.Taucetid:BAABNQAECoEUAAMVAAcKThxMJQDKAQAVAAcKThxMJQDKAQAPAAEK/gkQqwAkAAAAAA==.Tazington:BAABNQAECoEYAAIFAAgK+xQQfAACAgAFAAgK+xQQfAACAgAAAA==.Tazmage:BAAANQADCgcIBwAAAA==.Tazuki:BAAANQABCgIIAgAAAA==.',
Te='Tehsharp:BAABNQAECoEZAAMEAAcKcR/mWQA9AgAEAAcKcR/mWQA9AgAeAAEKIwicgAAvAAAAAA==.Tehwarrior:BAAANQABCgcIBwAAAA==.Telraena:BAAANQAECgYIEgAAAA==.Terokkar:BAABNQAECoEZAAIjAAYKuAhjHQBSAQAjAAYKuAhjHQBSAQAAAA==.Tesalach:BAAANQAECgQICwAAAA==.Teul:BAABNQAECoEXAAMDAAkKcwfhZwC6AQADAAkKcwfhZwC6AQAFAAQKSQMfNQGJAAABNQAECgkJKwATACwUAA==.',
Th='Thalorian:BAAANQAECgUJCgAAAA==.Thananerion:BAAANQADCgMIAwAAAA==.Thealiaa:BAAANQAECgEIAQAAAA==.Thehexorcist:BAAANQADCggIEwAAAA==.Thiea:BAABNQAECoEjAAMFAAgKbRYGegAHAgAFAAgKbRYGegAHAgAgAAEKwAvPawAkAAAAAA==.Thorel:BAAANQADCgcICAABNQAECgkJIgAeAEwNAA==.Thorrimar:BAAANQADCgUIBQAAAA==.Thorsake:BAAANQAECgYIEgAAAA==.Thromgorr:BAABNQAECoEZAAMTAAgKRx/CIQDCAgATAAgKRx/CIQDCAgAUAAEKbxgOCAFDAAAAAA==.Thunderboo:BAAANQADCggIEAABNQAECgkJHwAJAP8XAA==.Thundercant:BAAANQAECggIEgABNQAFFAcIFgAlAEAWAA==.Thunderpog:BAACNQAFFIEWAAMlAAcKQBZLAABwAgAlAAcKQBZLAABwAgAaAAEKCg2HFABGAAA1AAQKgR8ABBoACQowHvIYAGYCABoACApNHfIYAGYCAAEABwpkGMxkAL4BACUABAoUHVIOADQBAAAA.Thunderwing:BAAANQAECgMIBAABNQAFFAcIFgAlAEAWAA==.',
Ti='Tillicity:BAABNQAECoErAAMTAAkKtxw/KAChAgATAAkKtxw/KAChAgAUAAIKbxtc4ACbAAAAAA==.Tilzabeth:BAAANQADCgQICgABNQAECgkJKwATALccAA==.Timewarp:BAAANQADCggIBQAAAA==.Tinhu:BAAANQAECgEIAQAAAA==.Tinypi:BAAANQAECgYIEwAAAA==.Titanuss:BAAANQADCgcIBwAAAA==.Tivarah:BAAANQADCggICwAAAA==.',
To='Tomahawk:BAAANQADCgEIAQAAAA==.Toosuss:BAAANQADCgcIEQAAAA==.Topshot:BAABNQAECoEdAAIEAAcK3SPXLQDCAgAEAAcK3SPXLQDCAgAAAA==.Torags:BAAANQADCgQIBAAAAA==.Totemorlusta:BAAANQADCgMIAwABNQADCgMIBAAOAAAAAA==.',
Tr='Trazendeath:BAAANQADCgMIAwAAAA==.Treenuff:BAAANQADCgYIBgABNQAECgQIEAAOAAAAAA==.Treesource:BAAANQAECgQICQAAAA==.Trigaa:BAAANQAECgEIAQAAAA==.Trojans:BAAANQAECgEIAwAAAA==.',
Ts='Tsaiko:BAAANQAECgMICgAAAA==.',
Tu='Tuku:BAAANQAECgEIAQABNQAECgQIDQAOAAAAAA==.',
Tw='Twirls:BAABNQAECoEfAAMJAAkK/xezXQBWAgAJAAgKdxizXQBWAgAhAAIK6AsJJQBiAAAAAA==.Twirlshair:BAAANQADCgUIBQAAAA==.',
Ty='Tynzel:BAAANQAECgUICAAAAA==.Tyvaria:BAAANQADCgcIEQAAAA==.',
['Tà']='Tàkhisis:BAAANQAECgQICQAAAA==.',
Ul='Ullbenxt:BAAANQAECgQIBgAAAA==.',
Um='Umbranar:BAAANQADCgQIBAAAAA==.Umf:BAAANQADCggIEQABNQAECggIIAABAJ0bAA==.',
Un='Underwhelmed:BAAANQAECgQICAAAAA==.Unitofglory:BAAANQADCgIIAgABNQAECggIKQABAPUlAA==.Unitoflife:BAABNQAECoEpAAIBAAgK9SW3BwB2AwABAAgK9SW3BwB2AwAAAA==.Unitofshapes:BAAANQAECgUJDAABNQAECggIKQABAPUlAA==.',
Up='Upndown:BAAANQAFFAIIAgAAAA==.',
Va='Valanar:BAAANQADCgMIAwAAAA==.Valdormu:BAAANQAECgYJEgAAAA==.Vanador:BAAANQAECgQIBgAAAA==.Vanarel:BAAANQAECgQIBQAAAA==.Vanel:BAAANQAECgMIBQAAAA==.Vannbeef:BAABNQAECoEUAAMjAAYKEx5rFAD5AQAjAAYKEx5rFAD5AQATAAUKthzzagCcAQAAAA==.Varthlight:BAABNQAECoEVAAIFAAcK2xLKmwC0AQAFAAcK2xLKmwC0AQAAAA==.Vaurien:BAAANQADCgYIBgAAAA==.',
Ve='Veinytotem:BAAANQADCgUIBQAAAA==.Veloran:BAACNQAFFIEMAAMEAAMK9g2bEwD2AAAEAAMK9g2bEwD2AAAeAAEKjwftIAA/AAA1AAQKgU0ABAQACQo2HkcaABcDAAQACQo2HkcaABcDAB4ACAoiD3UzAIcBACgAAgrkCyYPAGEAAAAA.Venomsspawn:BAABNQAECoEYAAIEAAcKChAYiwDDAQAEAAcKChAYiwDDAQAAAA==.Vernonia:BAAANQADCggICQAAAA==.Vexahlia:BAAANQAECgEIAgAAAA==.Veyrathor:BAAANQADCgIIAgAAAA==.',
Vi='Vio:BAACNQAFFIEcAAITAAcKMRnEAQCBAgATAAcKMRnEAQCBAgA1AAQKgS8AAxMACQrTJCwGAIQDABMACQrTJCwGAIQDABQABArYF9qpABEBAAAA.Virtues:BAAANQADCgMIAwAAAA==.Virtus:BAAANQADCgYIBwAAAA==.Viserys:BAAANQAECgUIDwAAAA==.',
Vo='Voidtouched:BAAANQADCgYIBgABNQAECgkJHwAJAP8XAA==.Vows:BAAANQAECgQIDQAAAA==.',
Vu='Vuruul:BAAANQADCgYIDAAAAA==.',
Vy='Vypërz:BAABNQAECoEkAAMTAAkKcyQUBACcAwATAAkKcyQUBACcAwAUAAEKOgjtFwExAAAAAA==.Vyral:BAABNQAECoEoAAIWAAgK7A3xTgCZAQAWAAgK7A3xTgCZAQAAAA==.',
Wa='Wabssevo:BAAANQAECgQIBQABNQAFFAYIDwADAHQTAA==.Wabssjnr:BAACNQAFFIEPAAIDAAYKdBONBQD0AQADAAYKdBONBQD0AQA1AAQKgSMAAgMACQqGIUYJAHEDAAMACQqGIUYJAHEDAAAA.Wararesx:BAAANQADCgUIBwABNQAECgkJHgAQAF4cAA==.Warizard:BAABNQAECoEiAAIRAAgKCyNTBAAoAwARAAgKCyNTBAAoAwAAAA==.Wattanuhbii:BAAANQADCgQJBAAAAA==.Wayz:BAAANQAECgIIAwAAAA==.Wayzpala:BAAANQAECgQIBAAAAA==.',
We='Weyoun:BAAANQAECgUIEgAAAA==.',
Wh='Wheetie:BAABNQAECoEUAAIkAAYKrwO/HAC7AAAkAAYKrwO/HAC7AAAAAA==.',
Wi='Williwaw:BAAANQAECgQIBwAAAA==.Winterstormm:BAABNQAECoEXAAIWAAcKmwW8cAANAQAWAAcKmwW8cAANAQAAAA==.',
Wn='Wno:BAAANQADCgcIBwAAAA==.',
Wo='Wobbuffet:BAAANQAFFAQICAAAAQ==.Wolfen:BAAANQADCgcIDgAAAA==.Woohoowombat:BAAANQADCgMIAwAAAA==.',
Wy='Wyrnn:BAABNQAECoEcAAIdAAgKCSM2EQDmAgAdAAgKCSM2EQDmAgAAAA==.',
['Wå']='Wåyz:BAAANQAECgEIAQAAAA==.',
Xa='Xaniran:BAAANQADCgYICAAAAA==.Xaye:BAAANQAECgUICgAAAA==.',
Xe='Xelbino:BAAANQADCgEIAQAAAA==.',
Xi='Xiaobi:BAACNQAFFIEHAAICAAMKihAoCgDXAAACAAMKihAoCgDXAAA1AAQKgTAAAwIACQrmIhMEAIgDAAIACQrmIhMEAIgDABAABgquEEwYADoBAAAA.Xiiath:BAAANQAECgUIDQAAAA==.Xintar:BAAANQAECgEIAQAAAA==.Xiomana:BAAANQAECgQIDQAAAA==.Xion:BAABNQAECoEcAAMLAAcKARhTHQB7AQAKAAcKUhNSdQDYAQALAAUKohpTHQB7AQAAAA==.',
Xy='Xyluna:BAAANQADCgYIBgABNQAECgkJJgABANccAA==.',
Ye='Yebanned:BAAANQADCggICAABNQAFFAYIIwAEAIccAA==.Yellowajah:BAABNQAECoEZAAIaAAYKXgzNNwA/AQAaAAYKXgzNNwA/AQABNQAFFAUIBwAJAA8MAA==.',
Yi='Yify:BAAANQADCgUIBQABNQAECgQIDAAOAAAAAA==.',
Yn='Yneva:BAAANQAECgEIBAAAAA==.',
Yo='Yogan:BAAANQADCgQIBgAAAA==.',
Yw='Ywrensire:BAAANQAECgEIBgAAAA==.',
Za='Zaabra:BAAANQAECgQIDgAAAA==.Zaion:BAAANQAECgQIDQAAAA==.',
Ze='Zealis:BAAANQAECgYIDgAAAA==.Zebby:BAABNQAECoEUAAMdAAcKEAQxWAD7AAAdAAcKEAQxWAD7AAAXAAEKqAGs6gAUAAAAAA==.Zedar:BAAANQAECgYICAABNQAECggIQQAKANwgAA==.Zerull:BAAANQAECgEIAQAAAA==.',
Zh='Zhi:BAABNQAECoEUAAIaAAUKUAl9QwDvAAAaAAUKUAl9QwDvAAAAAA==.',
Zi='Zilin:BAABNQAECoEZAAITAAcK4Bz9PwA2AgATAAcK4Bz9PwA2AgAAAA==.',
Zo='Zolce:BAAANQAECgIIAgABNQAECgcIEgAOAAAAAA==.',
Zu='Zurbi:BAAANQAECgEIAQABNQAFFAMIBwACAIoQAA==.Zuularok:BAAANQADCgUIBQAAAA==.',
Zy='Zybaxos:BAABNQAECoEsAAIPAAkKBCBsEQAoAwAPAAkKBCBsEQAoAwAAAA==.Zyth:BAAANQAECgUICQAAAA==.',
Zz='Zzro:BAAANQAECgIIAwAAAA==.',
['Àw']='Àwkward:BAAANQADCgQIAwAAAA==.',
['Ãr']='Ãrçâñîst:BAAANQAECgMIAwAAAA==.',
['År']='Årchon:BAAANQAECgQIBQABNQAECgcIGAAnANoXAA==.Årtix:BAAANQADCgYIBgABNQADCgYICgAOAAAAAA==.',
['Îs']='Îssy:BAAANQAECgYIEgAAAA==.',
['Ôr']='Ôrkásh:BAAANQAECgEIAQAAAA==.',
['Öm']='Ömegoss:BAABNQAECoEeAAMbAAYKrB9fDAAoAgAbAAYKrB9fDAAoAgAPAAEKfBDvnAA7AAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
