local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'DeathKnight-Blood','DeathKnight-Frost','Warlock-Destruction','Evoker-Devastation','DemonHunter-Vengeance','Paladin-Retribution','Warrior-Arms','Warlock-Demonology','Unknown-Unknown','Shaman-Elemental','Paladin-Protection','Monk-Mistweaver','Mage-Arcane','Mage-Frost','Mage-Fire','Priest-Discipline','Druid-Balance','Druid-Restoration','Evoker-Preservation','Evoker-Augmentation','Rogue-Outlaw','Rogue-Assassination','Warlock-Affliction','DeathKnight-Unholy','DemonHunter-Havoc','DemonHunter-Devourer','Rogue-Subtlety','Hunter-BeastMastery','Priest-Holy','Priest-Shadow','Druid-Feral','Monk-Windwalker','Hunter-Marksmanship','Druid-Guardian','Paladin-Holy','Monk-Brewmaster','Shaman-Restoration','Shaman-Enhancement',}
local provider = {region='US',realm="Zul'jin",name='US',type='subscribers',zone=53,date='2026-09-21',data={Ae='Aerostatics:BAEANQAECgYJDQAAAA==.',
Al='Alekdk:BAECNQAFFIEIAAIBAAUKdh8LAwDbAQWODQAAAgBcAHUNAAABAGMAfw0AAAEAKwCpDQAAAgBJADMNAAACAF0AAQAFCnYfCwMA2wEFjg0AAAIAXAB1DQAAAQBjAH8NAAABACsAqQ0AAAIASQAzDQAAAgBdADUABAqBHAACAQAJCj4lKQIAvQMAAQAJCj4lKQIAvQMAAAA=.Alekpally:BAEANQAECgcIDAABNQAFFAUICAABAHYfAA==.Alekwar:BAEANQAECgIIAgABNQAFFAUICAABAHYfAA==.Aloro:BAECNQAFFIEFAAICAAMK4hPvBAAAAQOODQAAAgAiAHUNAAABAB4AqQ0AAAIAWAACAAMK4hPvBAAAAQOODQAAAgAiAHUNAAABAB4AqQ0AAAIAWAA1AAQKgSUAAgIACQpoIyQDAI8DAAIACQpoIyQDAI8DAAAA.Altar:BAECNQAFFIEKAAIDAAUKaw1KAACLAQWODQAAAgBbAHUNAAACACQAfw0AAAEAAACpDQAAAwAqADMNAAACAAEAAwAFCmsNSgAAiwEFjg0AAAIAWwB1DQAAAgAkAH8NAAABAAAAqQ0AAAMAKgAzDQAAAgABADUABAqBHwACAwAJCrIjpAAAqQMAAwAJCrIjpAAAqQMAAAA=.',
An='Ancestor:BAEANQAECgIJAgABNQAFFAQICAAEAEAPAA==.Andrilla:BAEBNQAECoEZAAIFAAgKUQ0UCQCyAQiODQAABQAfAHUNAAADACUAfw0AAAQAIQCpDQAABAAwAFwNAAADABUAXQ0AAAIAJgBlDQAAAwAaAKQNAAABACMABQAIClENFAkAsgEIjg0AAAUAHwB1DQAAAwAlAH8NAAAEACEAqQ0AAAQAMABcDQAAAwAVAF0NAAACACYAZQ0AAAMAGgCkDQAAAQAjAAAA.Angelstars:BAEANQAECgIIAQABNQAECgkJIwAGAIAhAA==.Antarys:BAEANQAECgMIAwABNQAFFAMIBQACAOITAA==.Antpala:BAEBNQAECoEgAAIGAAcKQRNjZwC+AQeODQAABwBBAHUNAAAGAEgAfw0AAAQAIQCpDQAABgAkAFwNAAADADEAXQ0AAAEADgAzDQAABQBJAAYABwpBE2NnAL4BB44NAAAHAEEAdQ0AAAYASAB/DQAABAAhAKkNAAAGACQAXA0AAAMAMQBdDQAAAQAOADMNAAAFAEkAAAA=.Antsjamaan:BAEANQADCggIGAABNQAECgcIIAAGAEETAA==.Anzay:BAEANQAECgcIBwABNQAFFAUICgACANIaAA==.',
Ar='Arbiter:BAEBNQAECoEjAAIHAAkKnCXUAwDGAwmODQAABgBhAHUNAAAFAGMAfw0AAAQAYQCpDQAABgBjAFwNAAACAGAAXQ0AAAQAWwBlDQAABABjAKQNAAACAFgAMw0AAAIAYQAHAAkKnCXUAwDGAwmODQAABgBhAHUNAAAFAGMAfw0AAAQAYQCpDQAABgBjAFwNAAACAGAAXQ0AAAQAWwBlDQAABABjAKQNAAACAFgAMw0AAAIAYQAAAA==.Arklos:BAECNQAFFIELAAMIAAYKhwYrBgBRAQaODQAAAwAxAHUNAAACABUAfw0AAAEACQCpDQAAAwANAFwNAAABAAMAMw0AAAEAAgAIAAUK1wUrBgBRAQWODQAAAwAxAH8NAAABAAkAqQ0AAAIACQBcDQAAAQADADMNAAABAAIAAwACCt8GAQoAnQACdQ0AAAIAFQCpDQAAAQANADUABAqBJAADAwAJCv8dlw0A/gEACAAHCkQcojQARQIAAwAHCoMWlw0A/gEAAAA=.Armato:BAEANQADCgYIBgABNQAECgYJDQAJAAAAAA==.',
As='Aspir:BAEBNQAECoEeAAICAAgKuR/EDwCpAgiODQAABQBbAHUNAAAFAF4Afw0AAAQARgCpDQAABABVAFwNAAAEAFYAXQ0AAAQAVgBlDQAAAwBLAKQNAAABADsAAgAICrkfxA8AqQIIjg0AAAUAWwB1DQAABQBeAH8NAAAEAEYAqQ0AAAQAVQBcDQAABABWAF0NAAAEAFYAZQ0AAAMASwCkDQAAAQA7AAAA.',
Ba='Bangkook:BAEANQAECgcIDAABNQAECggJDwAJAAAAAA==.Bayazi:BAECNQAFFIEeAAIKAAgKgSUFAAB4AwiODQAABQBjAHUNAAAEAGIAfw0AAAQAYACpDQAABQBjAFwNAAAEAGAAXQ0AAAMAZABlDQAAAQBkADMNAAAEAEwACgAICoElBQAAeAMIjg0AAAUAYwB1DQAABABiAH8NAAAEAGAAqQ0AAAUAYwBcDQAABABgAF0NAAADAGQAZQ0AAAEAZAAzDQAABABMADUABAqBGAACCgAJChUmRgMAwwMACgAJChUmRgMAwwMAAAA=.',
Be='Bearemanalow:BAEANQAECgQICgABNQAECgcIEAAJAAAAAA==.Belthion:BAECNQAFFIEJAAIKAAQKhR9iBQB2AQSODQAAAwBUAHUNAAACAFgAqQ0AAAMAWAAzDQAAAQA9AAoABAqFH2IFAHYBBI4NAAADAFQAdQ0AAAIAWACpDQAAAwBYADMNAAABAD0ANQAECoEbAAIKAAkKaiXwBACrAwAKAAkKaiXwBACrAwAAAA==.',
Bi='Bigmommakray:BAEANQAECgQIBAAAAA==.Bigswordswin:BAEANQAECggIEgAAAA==.',
Bl='Bluntyuwu:BAEANQADCggJCAABNQAECggKGgAGAEMkAA==.Bluntywaifu:BAEBNQAECoEaAAMGAAgKQyT+EwAzAwiODQAABABcAHUNAAAEAGEAfw0AAAMAYQCpDQAABABZAFwNAAADAFoAXQ0AAAIAYQBlDQAAAgBQADMNAAAEAGEABgAICkMk/hMAMwMIjg0AAAMAXAB1DQAAAgBhAH8NAAACAGEAqQ0AAAMAWQBcDQAAAQBaAF0NAAABAGEAZQ0AAAIAUAAzDQAABABhAAsABgrKII0RAPsBBo4NAAABAFEAdQ0AAAIAWwB/DQAAAQBcAKkNAAABAEcAXA0AAAIARwBdDQAAAQBfAAE1AAQKCAoaAAYAQyQA.',
Bo='Bobboatraces:BAEANQAECggJEwABNQAFFAYJDQAEAPwXAA==.Boomgheera:BAEANQAECgcIDgABNQAFFAQICAAEAEAPAA==.',
Br='Broloc:BAEANQADCgMJAwABNQAECgYJEQAJAAAAAA==.Brunidk:BAEBNQAECoEYAAIBAAgKPiIHDgD+AgiODQAABABVAHUNAAADAFoAfw0AAAMASwCpDQAABABgAFwNAAADAF8AXQ0AAAIAWwBlDQAAAgBaADMNAAADAEwAAQAICj4iBw4A/gIIjg0AAAQAVQB1DQAAAwBaAH8NAAADAEsAqQ0AAAQAYABcDQAAAwBfAF0NAAACAFsAZQ0AAAIAWgAzDQAAAwBMAAAA.',
Bu='Burgerdh:BAEANQADCggICAABNQAECgUIEAAJAAAAAA==.Burgerhunt:BAEANQADCgYIBgABNQAECgUIEAAJAAAAAA==.Burgersxd:BAEANQAECgUIEAAAAA==.Burningfex:BAEANQAECgYJBgAAAA==.',
By='Byce:BAEANQAECgYIBgAAAA==.',
Ca='Cappm:BAEBNQAECoEXAAIMAAkKMyCEAwA+AwmODQAAAwBdAHUNAAADAGIAfw0AAAMAYQCpDQAAAwBgAFwNAAACAGAAXQ0AAAIAUABlDQAAAwBRAKQNAAADACcAMw0AAAEAOgAMAAkKMyCEAwA+AwmODQAAAwBdAHUNAAADAGIAfw0AAAMAYQCpDQAAAwBgAFwNAAACAGAAXQ0AAAIAUABlDQAAAwBRAKQNAAADACcAMw0AAAEAOgAAAA==.Carriedegirl:BAEANQAFFAQIBAAAAA==.',
Ch='Chabdormu:BAEANQAECgMIAwABNQAFFAEIAQAJAAAAAA==.Chabu:BAEANQAFFAEIAQAAAA==.',
Co='Cohrentouch:BAEANQAECgMJBwAAAA==.Comboslice:BAEANQAECggIEAAAAA==.Condemdznuts:BAEANQAECgQJBwABNQAECggICwAJAAAAAA==.',
Cr='Crabfest:BAEBNQAECoEeAAIMAAkKsSVGAADqAwmODQAABABjAHUNAAAEAGMAfw0AAAQAYwCpDQAABABjAFwNAAADAGMAXQ0AAAMAYgBlDQAAAwBQAKQNAAABAFsAMw0AAAQAYwAMAAkKsSVGAADqAwmODQAABABjAHUNAAAEAGMAfw0AAAQAYwCpDQAABABjAFwNAAADAGMAXQ0AAAMAYgBlDQAAAwBQAKQNAAABAFsAMw0AAAQAYwAAAA==.',
['Câ']='Cârâmilk:BAEANQABCgYICgABNQAECggIGAABAD4iAA==.',
Da='Dabbadoo:BAEANQADCgYJBgABNQAECgkJGwANACkPAA==.Daeroth:BAEANQADCggIDQABNQAECggJGAAIAEkaAA==.Darkcam:BAECNQAFFIERAAMNAAcKnRw6AwAxAgeODQAABABaAHUNAAADAFUAfw0AAAIAOACpDQAAAQAuAFwNAAADAFQAXQ0AAAIAQAAzDQAAAgBUAA0ABgooHToDADECBo4NAAAEAFoAdQ0AAAMAVQB/DQAAAgA4AKkNAAABAC4AXA0AAAMAVAAzDQAAAgBUAA4AAQpaGaQDAGYAAV0NAAACAEAANQAECoEtAAQNAAkKVibQBADEAwANAAkKLSbQBADEAwAOAAQKjiaJCADDAQAPAAIKyxVzBQCaAAAAAA==.',
De='Demoncam:BAEANQAECggIEwABNQAFFAcIEQANAJ0cAA==.',
Di='Dirtymikee:BAEANQAECgcJEwAAAA==.',
Do='Doloco:BAEANQADCgYIBgABNQAECgYJEQAJAAAAAA==.',
Dr='Dragheera:BAEBNQAFFIEIAAIEAAQKQA97AwBCAQSODQAAAwA/AHUNAAABACAAfw0AAAEAGACpDQAAAwAkAAQABApAD3sDAEIBBI4NAAADAD8AdQ0AAAEAIAB/DQAAAQAYAKkNAAADACQAAAA=.Dragonzym:BAEANQAECggJEAABNQAECgkJHAAQAKgcAA==.Draloc:BAEANQAECgYJEQAAAA==.Drexen:BAEANQAECgUIBgAAAA==.',
Dy='Dyanna:BAEANQAECgYIBgABNQAECgkJHgAHAGEiAA==.',
['Dó']='Dóubleamp:BAEANQADCgEIAgABNQAFFAgIGwADABQcAA==.',
El='Elkaurif:BAEANQAECgMIBAAAAA==.',
En='Enraeged:BAEANQAECgEIAQABNQAECggIGAANAJAeAA==.',
Ev='Evimonk:BAEANQAECgYIBgABNQAFFAcIEQALAAEOAA==.Evipaladin:BAEBNQAFFIERAAILAAcKAQ4CAQD2AQeODQAABAA1AHUNAAACABQAfw0AAAIAMQCpDQAAAwAoAFwNAAACABIAXQ0AAAEAKAAzDQAAAwAdAAsABwoBDgIBAPYBB44NAAAEADUAdQ0AAAIAFAB/DQAAAgAxAKkNAAADACgAXA0AAAIAEgBdDQAAAQAoADMNAAADAB0AAAA=.',
Ex='Exwarlock:BAEANQAECgcICAAAAA==.',
Fa='Fatalpink:BAEANQAECggICgAAAA==.',
Fe='Felendruid:BAECNQAFFIEHAAMRAAUKnxJgCABHAQWODQAAAgAjAHUNAAABABIAfw0AAAEALACpDQAAAgAsADMNAAABAF8AEQAECvMNYAgARwEEjg0AAAIAIwB1DQAAAQASAH8NAAABACwAqQ0AAAEALAASAAIKawRtCACGAAKpDQAAAQAKADMNAAABAAwANQAECoEcAAMSAAkKmhy1CwCqAgASAAkKmhy1CwCqAgARAAEKDyM+cQBmAAAAAA==.Felenpal:BAEANQAECgQIBQABNQAFFAUIBwARAJ8SAA==.Felenvoker:BAECNQAFFIEaAAITAAcKtBrHAACIAgeODQAABAAWAHUNAAAEAF8Afw0AAAQAUACpDQAABABAAFwNAAADADsAXQ0AAAMARwAzDQAABABTABMABwq0GscAAIgCB44NAAAEABYAdQ0AAAQAXwB/DQAABABQAKkNAAAEAEAAXA0AAAMAOwBdDQAAAwBHADMNAAAEAFMANQAECoEmAAQTAAkKWCFSBABFAwATAAkKWCFSBABFAwAUAAMKEiIvCwAWAQAEAAEKIh1uKgBMAAABNQAFFAUIBwARAJ8SAA==.Felsquish:BAEANQADCgMIAwABNQAECgUJCwAJAAAAAA==.Felzero:BAEBNQAECoEcAAMVAAgKoRj/BABeAgiODQAAAwBBAHUNAAAEADYAfw0AAAQAUwCpDQAABAAhAFwNAAADAEYAXQ0AAAMARQBlDQAAAwBGADMNAAAEADcAFQAICqEY/wQAXgIIjg0AAAMAQQB1DQAABAA2AH8NAAAEAFMAqQ0AAAQAIQBcDQAAAwBGAF0NAAADAEUAZQ0AAAIARgAzDQAABAA3ABYAAQp+BY9bADwAAWUNAAABAA4AAAA=.',
Fi='Fieldbritish:BAECNQAFFIELAAQXAAUKQRllAQCwAAWODQAAAwBfAHUNAAACAGEAfw0AAAEACwCpDQAAAwA+ADMNAAACADgAAwACCokaNAQAwQACdQ0AAAIAYQCpDQAAAgAmABcAAgofF2UBALAAAqkNAAABAD4AMw0AAAIAOAAIAAIKABUdFACnAAKODQAAAwBfAH8NAAABAAsANQAECoEcAAQXAAkKeCQGAQAnAwAXAAgKWyUGAQAnAwADAAYKMBt1EQDPAQAIAAIKjhYUxgB6AAAAAA==.Firstfield:BAEANQAECgMIBwABNQAFFAUICwAXAEEZAA==.',
Fo='Fofer:BAECNQAFFIEPAAIBAAYKeRvdAQAZAgaODQAABABjAHUNAAACACAAfw0AAAIARQCpDQAAAwBPAFwNAAABADcAMw0AAAMAVgABAAYKeRvdAQAZAgaODQAABABjAHUNAAACACAAfw0AAAIARQCpDQAAAwBPAFwNAAABADcAMw0AAAMAVgA1AAQKgR8AAgEACQqbJd8CAK0DAAEACQqbJd8CAK0DAAAA.',
Fr='Fro:BAEBNQAECoEnAAMNAAkK+iOxDgCDAwmODQAABQBfAHUNAAAGAGMAfw0AAAcAYwCpDQAABQBhAFwNAAAEAGEAXQ0AAAMAYABlDQAAAwBdAKQNAAAEAEUAMw0AAAIATwANAAkKJyOxDgCDAwmODQAABABfAHUNAAAEAGMAfw0AAAcAYwCpDQAAAwBdAFwNAAADAFIAXQ0AAAIAYABlDQAAAwBdAKQNAAAEAEUAMw0AAAEATwAOAAYKvhgoBwDuAQaODQAAAQATAHUNAAACAF0AqQ0AAAIAYQBcDQAAAQBhAF0NAAABADMAMw0AAAEAFAAAAA==.Frozenwater:BAEANQAECgIIBAAAAA==.',
Go='Goatbolts:BAEANQAFFAIIAgABNQAFFAYIEAAXAOwgAA==.Gothgock:BAEANQAECgYJCwAAAA==.',
Gr='Grayparson:BAEANQAECgYIBgABNQAECgcICAAJAAAAAA==.Greenbuge:BAEANQAECggJDQABNQAFFAUICwAMAIQlAA==.',
In='Inabeninging:BAECNQAFFIEKAAMCAAUK0hqAAgBpAQWODQAABABWAH8NAAADAEYAqQ0AAAEATQBcDQAAAQA1ADMNAAABADgAAgAECq4agAIAaQEEjg0AAAIAVgCpDQAAAQBNAFwNAAABADUAMw0AAAEAOAAYAAIKMh0zCACtAAKODQAAAgBPAH8NAAADAEYANQAECoEfAAMCAAkK0iTJCQAFAwAYAAkKTiOiDgAHAwACAAgKuyPJCQAFAwAAAA==.',
Ip='Ipposaur:BAEANQAECgcIDwABNQABCgcIBwAJAAAAAA==.',
Ir='Irishthree:BAEBNQAECoEmAAMIAAkKFyUWAgC2AwmODQAABQBjAHUNAAAFAGMAfw0AAAUAXwCpDQAABQBhAFwNAAAEAGAAXQ0AAAQAXwBlDQAAAwBUAKQNAAACAFkAMw0AAAUAXwAIAAkKFyUWAgC2AwmODQAABABjAHUNAAAFAGMAfw0AAAUAXwCpDQAABABhAFwNAAAEAGAAXQ0AAAQAXwBlDQAAAwBUAKQNAAACAFkAMw0AAAUAXwADAAIKgxucRACMAAKODQAAAQBOAKkNAAABAD4AAAA=.Irredeemable:BAEANQAECgIJAgABNQAFFAcJEwANAHYZAA==.',
Iu='Iunarx:BAEANQAECgYICQABNQAFFAcJEwALAEYYAA==.',
Ja='Jaye:BAEANQAECgUICAAAAA==.',
Jb='Jblinkman:BAEANQADCgQIBAABNQAECggIEAAJAAAAAA==.',
Je='Jellyfîsh:BAEANQAECgEIBAABNQAECgYJCAAJAAAAAA==.',
Ji='Jimmi:BAECNQAFFIEHAAMCAAUKtwppAwBAAQWODQAAAgA9AHUNAAABAAIAfw0AAAEAHQBcDQAAAQAbADMNAAACABAAAgAECsoLaQMAQAEEjg0AAAIAPQB1DQAAAQACAH8NAAABAB0AXA0AAAEAGwABAAEKbAafIQAfAAEzDQAAAgAQADUABAqBIAACAgAJCt8dmw4AuwIAAgAJCt8dmw4AuwIAAAA=.',
Ju='Jupitermage:BAECNQAFFIEMAAINAAYKZBmJAwAqAgaODQAAAgA8AHUNAAADAEkAfw0AAAIAXQCpDQAAAgBIAFwNAAABACcAMw0AAAIAMgANAAYKZBmJAwAqAgaODQAAAgA8AHUNAAADAEkAfw0AAAIAXQCpDQAAAgBIAFwNAAABACcAMw0AAAIAMgA1AAQKgRoAAg0ACQrlH+o8ANECAA0ACQrlH+o8ANECAAAA.',
Ka='Kaurif:BAEANQADCgUIBQABNQAECgMIBAAJAAAAAA==.',
Ke='Kellwaterboy:BAEANQAECgEJAQABNQAFFAYJDgATAOIYAA==.Kelnutdragin:BAECNQAFFIEOAAITAAYK4hjiAQAmAgaODQAAAwBVAHUNAAACACUAfw0AAAIAWgCpDQAAAwBFAFwNAAABAAwAMw0AAAMAVgATAAYK4hjiAQAmAgaODQAAAwBVAHUNAAACACUAfw0AAAIAWgCpDQAAAwBFAFwNAAABAAwAMw0AAAMAVgA1AAQKgSEAAhMACQo5HMUJAMgCABMACQo5HMUJAMgCAAAA.',
Kh='Khazak:BAECNQAFFIENAAMCAAcKchHHAAD1AQeODQAAAgBBAHUNAAABADIAfw0AAAMAFwCpDQAAAQADAFwNAAACACYAXQ0AAAEANgAzDQAAAwBMAAIABwo5EccAAPUBB44NAAACAEEAdQ0AAAEAMgB/DQAAAgATAKkNAAABAAMAXA0AAAIAJgBdDQAAAQA2ADMNAAADAEwAGAABClYJmQ8ASQABfw0AAAEAFwA1AAQKgR0AAwIACQpcIzcOAMACAAIACAqRIzcOAMACABgACAqDG0YtAP0BAAAA.',
Ki='Kimiqt:BAEANQAECgYICAABNQAECgYJCwAJAAAAAA==.',
Ko='Koaladh:BAECNQAFFIEJAAMZAAUK0xVbAwCbAQWODQAAAgBFAHUNAAACAC4Afw0AAAEAIwCpDQAAAgAyADMNAAACAE8AGQAFChESWwMAmwEFjg0AAAEAOQB1DQAAAQAJAH8NAAABACMAqQ0AAAIAMgAzDQAAAgBPABoAAgp5FnAIAK4AAo4NAAABAEUAdQ0AAAEALgA1AAQKgSMABBkACQoyIUoOAN0CABoACQpeHvsMAOICABkACAr6HkoOAN0CAAUAAQodAtwcADkAAAAA.Koalaremixsh:BAEANQAECgEIAQABNQAFFAUICQAZANMVAA==.Koàra:BAEANQAECgEJAQABNQAECgcICAAJAAAAAA==.',
Kr='Kramix:BAEBNQAECoEeAAIHAAkK6iL1EQBKAwmODQAABABXAHUNAAAEAFoAfw0AAAMAVwCpDQAABABfAFwNAAADAFsAXQ0AAAQAYABlDQAABABhAKQNAAABADwAMw0AAAMAYQAHAAkK6iL1EQBKAwmODQAABABXAHUNAAAEAFoAfw0AAAMAVwCpDQAABABfAFwNAAADAFsAXQ0AAAQAYABlDQAABABhAKQNAAABADwAMw0AAAMAYQAAAA==.Kramon:BAEBNQAECoEaAAMZAAkK7h1yEgCoAgmODQAABQBOAHUNAAAFAFwAfw0AAAMAQwCpDQAABABHAFwNAAABAE8AXQ0AAAEASABlDQAAAQBFAKQNAAABAEkAMw0AAAUAUwAZAAgKFBtyEgCoAgiODQAAAQBOAHUNAAABAFwAfw0AAAEAQwCpDQAAAQATAFwNAAABAE8AXQ0AAAEASABlDQAAAQBFAKQNAAABAEkAGgAFCusZySwAegEFjg0AAAQAQgB1DQAABABMAH8NAAACACIAqQ0AAAMARwAzDQAABQBTAAE1AAQKCQkeAAcA6iIA.Krypticshado:BAEANQAECgMIAwABNQAFFAUIDwAbAKsSAA==.Krypticstab:BAECNQAFFIEPAAMbAAUKqxLZBABVAQWODQAABQBVAHUNAAADABgAfw0AAAMADgCpDQAAAgBYADMNAAACABkAGwAECqsO2QQAVQEEjg0AAAUAVQB1DQAAAwAYAH8NAAADAA4AMw0AAAIAGQAWAAEKqyLGCQBqAAGpDQAAAgBYADUABAqBJQADGwAJCgUiWQUAFQMAGwAICs8hWQUAFQMAFgAFChsg5iMAsAEAAAA=.',
Ky='Kylier:BAEBNQAECoEUAAIcAAcK0iJ6IQCwAgeODQAAAwBZAHUNAAADAGEAfw0AAAMATQCpDQAAAwBfAFwNAAADAF0AXQ0AAAMAWgBlDQAAAgBQABwABwrSInohALACB44NAAADAFkAdQ0AAAMAYQB/DQAAAwBNAKkNAAADAF8AXA0AAAMAXQBdDQAAAwBaAGUNAAACAFAAATUABRQHCREAFADuHwA=.Kymmie:BAEANQAECgIIAgABNQAFFAMJBQAdAJEXAA==.',
['Kó']='Kóara:BAEANQADCggJCAABNQAECgcICAAJAAAAAA==.',
La='Lamadin:BAEANQAFFAIIBAABNQAECgcIBwAJAAAAAA==.Lambertdh:BAEBNQAFFIEHAAIFAAQKfRmPAABSAQSODQAAAgBdAHUNAAACADMAfw0AAAEAPQCpDQAAAgA2AAUABAp9GY8AAFIBBI4NAAACAF0AdQ0AAAIAMwB/DQAAAQA9AKkNAAACADYAATUABAoHCAcACQAAAAA=.Lambertdk:BAEBNQAFFIEaAAIBAAcKISQPAAARAweODQAABABjAHUNAAAEAGQAfw0AAAQAXQCpDQAABQBjAFwNAAAEAF8AZQ0AAAEAPAAzDQAABABiAAEABwohJA8AABEDB44NAAAEAGMAdQ0AAAQAZAB/DQAABABdAKkNAAAFAGMAXA0AAAQAXwBlDQAAAQA8ADMNAAAEAGIAATUABAoHCAcACQAAAAA=.Lambort:BAEANQAECgcIBwAAAA==.Lamlock:BAEANQADCgEIAgABNQAECgcIBwAJAAAAAA==.Lamwar:BAEANQADCgEIAQABNQAECgcIBwAJAAAAAA==.Lapinlock:BAEANQADCgYIDAABNQAECgkJJgAHACciAA==.Lapinpal:BAEANQAECgUIBgABNQAECgkJJgAHACciAA==.Lapinw:BAEBNQAECoEmAAIHAAkKJyKSDwBaAwmODQAABABZAHUNAAAFAGAAfw0AAAUAXgCpDQAABQBcAFwNAAAEAGIAXQ0AAAUAXQBlDQAABABQAKQNAAACADcAMw0AAAQAVwAHAAkKJyKSDwBaAwmODQAABABZAHUNAAAFAGAAfw0AAAUAXgCpDQAABQBcAFwNAAAEAGIAXQ0AAAUAXQBlDQAABABQAKQNAAACADcAMw0AAAQAVwAAAA==.Layria:BAECNQAFFIENAAISAAUKLQ2bAgCDAQWODQAABAAfAHUNAAACAAkAfw0AAAIAPACpDQAAAwAUADMNAAACAC4AEgAFCi0NmwIAgwEFjg0AAAQAHwB1DQAAAgAJAH8NAAACADwAqQ0AAAMAFAAzDQAAAgAuADUABAqBFgACEgAJCj4XbA4AfAIAEgAJCj4XbA4AfAIAAAA=.',
Le='Lenbar:BAEBNQAECoEdAAMdAAgKziVyBwBSAwiODQAABABjAHUNAAAEAGEAfw0AAAQAYwCpDQAABABhAFwNAAADAF0AXQ0AAAMAYwBlDQAAAwBbADMNAAAEAF8AHQAICs4lcgcAUgMIjg0AAAMAYwB1DQAAAwBhAH8NAAADAGMAqQ0AAAMAYQBcDQAAAwBdAF0NAAADAGMAZQ0AAAMAWwAzDQAAAwBfAB4ABQpYFmInAGYBBY4NAAABAEEAdQ0AAAEAPgB/DQAAAQBUAKkNAAABABIAMw0AAAEANgAAAA==.Lewompwomp:BAEANQADCgEIAQABNQAECgYJCAAJAAAAAA==.',
Li='Likp:BAEANQAECgQIBAABNQAECgkJFgAaALgYAA==.Lilsym:BAEANQAECgYICgABNQAFFAYIFAARANMjAA==.',
Lo='Login:BAEANQAFFAIIAwAAAA==.Louss:BAEBNQAECoEcAAIMAAkKmSGDAgBmAwmODQAABgBjAHUNAAADAGMAfw0AAAIAYACpDQAABABjAFwNAAACAEAAXQ0AAAEAOQBlDQAAAwBZAKQNAAACAEUAMw0AAAUAYQAMAAkKmSGDAgBmAwmODQAABgBjAHUNAAADAGMAfw0AAAIAYACpDQAABABjAFwNAAACAEAAXQ0AAAEAOQBlDQAAAwBZAKQNAAACAEUAMw0AAAUAYQAAAA==.Louzer:BAEANQAECgUJBQABNQAECgkJHAAMAJkhAA==.',
Lu='Luñar:BAEANQAFFAQIBAABNQAFFAcJEwALAEYYAA==.',
['Lâ']='Lâra:BAECNQAFFIETAAINAAcKdhkNAQCTAgeODQAAAwAvAHUNAAADADwAfw0AAAMAXwCpDQAAAwA+AFwNAAACAEEAXQ0AAAEAKgAzDQAABABRAA0ABwp2GQ0BAJMCB44NAAADAC8AdQ0AAAMAPAB/DQAAAwBfAKkNAAADAD4AXA0AAAIAQQBdDQAAAQAqADMNAAAEAFEANQAECoEaAAINAAkKKCOUIwAoAwANAAkKKCOUIwAoAwAAAA==.',
Ma='Macgregor:BAEBNQAECoEWAAIHAAkKpRu1JADbAgmODQAAAwBaAHUNAAADAFMAfw0AAAMAVgCpDQAAAwBWAFwNAAACACsAXQ0AAAIASABlDQAAAwBTAKQNAAABABoAMw0AAAIAPwAHAAkKpRu1JADbAgmODQAAAwBaAHUNAAADAFMAfw0AAAMAVgCpDQAAAwBWAFwNAAACACsAXQ0AAAIASABlDQAAAwBTAKQNAAABABoAMw0AAAIAPwABNQAFFAUICgAGAIwdAA==.Madthelock:BAECNQAFFIEZAAQXAAgKRSIBAAD7AgiODQAAAgBiAHUNAAADAF8Afw0AAAMAUACpDQAABQBjAFwNAAAEAGIAXQ0AAAMASABlDQAAAQA8ADMNAAAEAF8AFwAHCjQhAQAA+wIHjg0AAAEAYQB1DQAAAQBZAH8NAAABADUAqQ0AAAEAYwBcDQAAAgBiAGUNAAABADwAMw0AAAQAXwAIAAUKYiJ0AgDMAQWODQAAAQBiAH8NAAACAFAAqQ0AAAIAWgBcDQAAAgBhAF0NAAADAEgAAwACClAlwQIA0gACdQ0AAAIAXwCpDQAAAgBfADUABAqBGAAEAwAJClEmewIAFAMAAwAJCqUgewIAFAMACAAGCggmXy4AYAIAFwADCmolqQoAOgEAATUABRQIChkAFwBFIgA=.Madthepally:BAEANQAECggJEAABNQAFFAgKGQAXAEUiAA==.Mangoslurpee:BAEBNQAECoEfAAIfAAgKoCKKAgAvAwiODQAABQBfAHUNAAAEAFsAfw0AAAQAXACpDQAABABfAFwNAAAEAF0AXQ0AAAMAOwBlDQAAAgBTADMNAAAFAGAAHwAICqAiigIALwMIjg0AAAUAXwB1DQAABABbAH8NAAAEAFwAqQ0AAAQAXwBcDQAABABdAF0NAAADADsAZQ0AAAIAUwAzDQAABQBgAAAA.Mattukii:BAEBNQAECoEnAAINAAkKkxuwMwDuAgmODQAABQBMAHUNAAAFAFgAfw0AAAUAXACpDQAABQBVAFwNAAAEAAgAXQ0AAAQAVABlDQAAAwAlAKQNAAADAEAAMw0AAAUAYgANAAkKkxuwMwDuAgmODQAABQBMAHUNAAAFAFgAfw0AAAUAXACpDQAABQBVAFwNAAAEAAgAXQ0AAAQAVABlDQAAAwAlAKQNAAADAEAAMw0AAAUAYgAAAA==.Mattyliight:BAECNQAFFIELAAIgAAQK2xLeAwBKAQSODQAAAwAjAHUNAAADACMAfw0AAAIAKgCpDQAAAwBOACAABArbEt4DAEoBBI4NAAADACMAdQ0AAAMAIwB/DQAAAgAqAKkNAAADAE4ANQAECoEfAAMgAAkKWx5RCwDIAgAgAAkKWx5RCwDIAgAMAAEKIQJGNQA2AAAAAA==.Mauxn:BAEANQADCgUIBQABNQAECgYJEQAJAAAAAA==.Mauxuam:BAEANQAECgYJEQAAAA==.',
Me='Meatypete:BAEANQADCggJCAAAAA==.Megabloks:BAEANQAECggICwAAAA==.',
Mi='Mirainikky:BAEANQAECgQIBQABNQAFFAQIDQAWAGQVAA==.',
Mt='Mts:BAECNQAFFIEHAAMcAAQKuh25CQDbAASODQAAAgBaAHUNAAABADAAqQ0AAAIAQgAzDQAAAgBiABwAAgr0JLkJANsAAo4NAAACAFoAMw0AAAIAYgAhAAIKgBa9DQCmAAJ1DQAAAQAwAKkNAAACAEIANQAECoEsAAMcAAkKIyJpJwCTAgAcAAYKiSRpJwCTAgAhAAcKFB7sGQApAgAAAA==.',
Mu='Mudkìp:BAEANQAFFAEJAQABNQAFFAYIEgAiABobAA==.',
Ne='Nexed:BAEBNQAECoElAAQGAAkKHBn0KAC1AgmODQAABQBVAHUNAAAFAEYAfw0AAAUAUgCpDQAABABMAFwNAAAEAC4AXQ0AAAMALwBlDQAAAwAzAKQNAAADACwAMw0AAAUASQAGAAkKHBn0KAC1AgmODQAABQBVAHUNAAAEAEYAfw0AAAQAUgCpDQAABABMAFwNAAADAC4AXQ0AAAIALwBlDQAAAwAzAKQNAAADACwAMw0AAAQASQAjAAQKmQYikwDbAAR1DQAAAQApAH8NAAABAAQAXA0AAAEADwBdDQAAAQAGAAsAAQq3G1ZCAEsAATMNAAABAEYAATUABAoFCAYACQAAAAA=.Nexxed:BAEANQAECgUIBwABNQAECgUIBgAJAAAAAA==.',
Ni='Nidhildr:BAEANQADCggIFAAAAA==.',
Pa='Pallyzilla:BAEBNQAECoEYAAILAAgKERGyFQC6AQiODQAABAAkAHUNAAAEAD0Afw0AAAMAKACpDQAAAwAXAFwNAAACAB4AXQ0AAAIAPABlDQAAAgATADMNAAAEAEwACwAIChERshUAugEIjg0AAAQAJAB1DQAABAA9AH8NAAADACgAqQ0AAAMAFwBcDQAAAgAeAF0NAAACADwAZQ0AAAIAEwAzDQAABABMAAE1AAQKCQkcABAAqBwA.Pawnshopkell:BAEANQAECggIDAABNQAFFAYJDgATAOIYAA==.',
Pe='Pessimistick:BAEANQADCgcIBwABNQABCgcIBwAJAAAAAA==.',
Po='Pocadots:BAEBNQAECoEjAAIeAAkKQRpnDADWAgmODQAABwBbAHUNAAAEAEYAfw0AAAQAUgCpDQAABAA6AFwNAAADAEoAXQ0AAAMARwBlDQAABAA4AKQNAAABACgAMw0AAAUAOwAeAAkKQRpnDADWAgmODQAABwBbAHUNAAAEAEYAfw0AAAQAUgCpDQAABAA6AFwNAAADAEoAXQ0AAAMARwBlDQAABAA4AKQNAAABACgAMw0AAAUAOwAAAA==.Portalingus:BAEANQAECgMIBAAAAA==.Powerscaling:BAECNQAFFIELAAITAAUKSAzjBACPAQWODQAAAwAsAHUNAAACABQAfw0AAAIAGACpDQAAAgAnADMNAAACAB0AEwAFCkgM4wQAjwEFjg0AAAMALAB1DQAAAgAUAH8NAAACABgAqQ0AAAIAJwAzDQAAAgAdADUABAqBGgACEwAJCj8axwcA9QIAEwAJCj8axwcA9QIAAAA=.',
Pr='Priestzilla:BAEBNQAECoEcAAMQAAkKqBwGAgDHAgmODQAABABeAHUNAAAEAFoAfw0AAAMAUACpDQAABABPAFwNAAADAFMAXQ0AAAMAUwBlDQAAAgBEAKQNAAABAAYAMw0AAAQASQAQAAgK6h8GAgDHAgiODQAABABeAHUNAAAEAFoAfw0AAAMAUACpDQAABABPAFwNAAADAFMAXQ0AAAMAUwBlDQAAAgBEADMNAAAEAEkAHQABCpYCWqQAOwABpA0AAAEABgAAAA==.',
Pu='Pureapathy:BAEANQAECgEIAQABNQAECggIGQAFAFENAA==.',
Qu='Queasy:BAEANQAECgQIBAABNQAFFAIIAwAJAAAAAA==.',
Ra='Rammorage:BAEANQAECgMIBwAAAA==.',
Re='Reversedmilk:BAEANQAECgQIBgABNQAFFAYJDwARAL8cAA==.Reversemilk:BAECNQAFFIEPAAIRAAYKvxwYAgAxAgaODQAAAwBRAHUNAAADAFYAfw0AAAIAKQCpDQAAAwBSAFwNAAABAEoAMw0AAAMASgARAAYKvxwYAgAxAgaODQAAAwBRAHUNAAADAFYAfw0AAAIAKQCpDQAAAwBSAFwNAAABAEoAMw0AAAMASgA1AAQKgRsAAhEACQo5IpMOABwDABEACQo5IpMOABwDAAAA.',
Ri='Riidiisi:BAEBNQAECoEuAAMEAAkK2RoKBwDcAgmODQAACQBWAHUNAAAJAFMAfw0AAAcAUgCpDQAABwBTAFwNAAAFADsAXQ0AAAIAUABlDQAAAQA+AKQNAAABAAEAMw0AAAUATgAEAAgKIB4KBwDcAgiODQAABABWAHUNAAAFAFMAfw0AAAQAUgCpDQAAAgBTAFwNAAADADsAXQ0AAAIAUABlDQAAAQA+ADMNAAADAE4AFAAHCo4RPAgAfgEHjg0AAAUARwB1DQAABAAtAH8NAAADACgAqQ0AAAUAMwBcDQAAAgAlAKQNAAABAAEAMw0AAAIAQwAAAA==.Rinmage:BAEANQADCgIIAgABNQAECgYJEgAJAAAAAA==.Rinruid:BAEANQAECgYJEgAAAA==.Rispir:BAECNQAFFIEHAAMhAAUKSRYBCQAlAQWODQAAAwBFAHUNAAABAD8AqQ0AAAEAUABcDQAAAQBEADMNAAABAAIAIQAECiIVAQkAJQEEjg0AAAMARQB1DQAAAQA/AKkNAAABAFAAMw0AAAEAAgAcAAEK4hpGFABrAAFcDQAAAQBEADUABAqBJQADIQAJCt4l3wQAZQMAIQAJCvoh3wQAZQMAHAACClUcu8QArgAAAAA=.',
Ro='Robert:BAECNQAFFIELAAMkAAUKcxZqAgALAQWODQAAAwBdAHUNAAADAEMAfw0AAAEAMQCpDQAAAQAGADMNAAADAEYAJAADCjIeagIACwEDjg0AAAMAXQB1DQAAAwBDADMNAAADAEYADAACCrwMLwUAnQACfw0AAAEAOgCpDQAAAQAGADUABAqBJAAEJAAJClwjnAEAfQMAJAAJClwjnAEAfQMADAACCiwecycArwAAIAABCuojaD0AZgAAAAA=.Roloco:BAEANQAECgYJEAABNQAECgYJEQAJAAAAAA==.Rowjinn:BAEANQADCgcIBwABNQAECgkJHgAEALoUAA==.',
Sa='Saebyeok:BAEANQAECggJDwAAAA==.',
Sc='Scalier:BAECNQAFFIERAAMUAAcK7h8/AADTAgeODQAABABLAHUNAAACAEQAfw0AAAIAXACpDQAAAwBjAFwNAAACAFsAXQ0AAAEAMgAzDQAAAwBeABQABwruHz8AANMCB44NAAACAEsAdQ0AAAEARAB/DQAAAQBcAKkNAAACAGMAXA0AAAIAWwBdDQAAAQAyADMNAAACAF4ABAAFCs4VDgIAmAEFjg0AAAIAPgB1DQAAAQAgAH8NAAABACkAqQ0AAAEAUgAzDQAAAQA8ADUABAqBGgADBAAJCmQlzwYA4QIABAAICqMjzwYA4QIAFAAECtoi4AcAjgEAAAA=.Scewb:BAEANQAECgYJBQABNQAFFAQIDQAWAGQVAA==.',
Se='Seansevoker:BAEANQAECgYICwABNQAFFAcJFQAlAHghAA==.Seansshaman:BAECNQAFFIEVAAIlAAcKeCEuAADaAgeODQAABABfAHUNAAAEAGAAfw0AAAMAVQCpDQAABABfAFwNAAACAFMAXQ0AAAEALgAzDQAAAwBhACUABwp4IS4AANoCB44NAAAEAF8AdQ0AAAQAYAB/DQAAAwBVAKkNAAAEAF8AXA0AAAIAUwBdDQAAAQAuADMNAAADAGEANQAECoEjAAIlAAkKsiXWAQC8AwAlAAkKsiXWAQC8AwAAAA==.Seear:BAEANQAECgcIEAAAAA==.Seeargaming:BAEANQADCgUIBgABNQAECgcIEAAJAAAAAA==.Seeartotems:BAEANQAECgUIBwABNQAECgcIEAAJAAAAAA==.Sensian:BAEBNQAECoEYAAINAAgKkB77PQDNAgiODQAABABcAHUNAAADAFIAfw0AAAMAWgCpDQAAAwBVAFwNAAADAEkAXQ0AAAMAVABlDQAAAwBBADMNAAACADIADQAICpAe+z0AzQIIjg0AAAQAXAB1DQAAAwBSAH8NAAADAFoAqQ0AAAMAVQBcDQAAAwBJAF0NAAADAFQAZQ0AAAMAQQAzDQAAAgAyAAAA.Serinos:BAECNQAFFIEFAAIGAAMK1hlWBwAJAQOODQAAAgBRAHUNAAABACwAqQ0AAAIASAAGAAMK1hlWBwAJAQOODQAAAgBRAHUNAAABACwAqQ0AAAIASAA1AAQKgSAAAwYACQopIzANAGcDAAYACQopIzANAGcDAAsABwq/G7kNADsCAAAA.',
Sh='Shamanapaks:BAEANQAECgYJDgAAAA==.Shiko:BAEANQAECgMIBQABNQAECggIHwAfAKAiAA==.',
Sm='Smashshammy:BAEBNQAECoEfAAMmAAkK1xsVBQADAwmODQAABABCAHUNAAAEAFMAfw0AAAQAUwCpDQAABABXAFwNAAADAEUAXQ0AAAMAMgBlDQAAAwA1AKQNAAACADoAMw0AAAQAVwAmAAkKxhoVBQADAwmODQAAAgBCAHUNAAACAEcAfw0AAAIAUwCpDQAAAgBLAFwNAAACAEUAXQ0AAAIAMgBlDQAAAgA1AKQNAAACADoAMw0AAAIAVwAKAAgK3RWoMwAwAgiODQAAAgBCAHUNAAACAFMAfw0AAAIAKACpDQAAAgBXAFwNAAABAD8AXQ0AAAEADABlDQAAAQAYADMNAAACAEUAAAA=.',
So='Solelock:BAEANQAECgYIDQAAAA==.',
Sq='Squishlee:BAEANQAECgUJCwAAAA==.',
St='Starvinp:BAEANQAECggIBgAAAA==.Stompers:BAEANQADCgYIBgABNQAECgkJFwAMADMgAA==.',
Su='Sunnadin:BAEANQAECgQIBwABNQAFFAUIDQATAN4XAA==.Sunscaled:BAECNQAFFIENAAITAAUK3hfgAwC1AQWODQAAAwA7AHUNAAADAFAAfw0AAAIAVACpDQAAAwAtADMNAAACACMAEwAFCt4X4AMAtQEFjg0AAAMAOwB1DQAAAwBQAH8NAAACAFQAqQ0AAAMALQAzDQAAAgAjADUABAqBGAACEwAJCtcgAQUAMgMAEwAJCtcgAQUAMgMAAAA=.',
Sw='Swaggybolt:BAEBNQAECoEbAAMNAAkKKQ9eeAAmAgmODQAABQBCAHUNAAADADoAfw0AAAQAGQCpDQAABAAwAFwNAAACACIAXQ0AAAIABgBlDQAAAwA9AKQNAAABAA0AMw0AAAMAIwANAAkKKQ9eeAAmAgmODQAABABCAHUNAAADADoAfw0AAAQAGQCpDQAABAAwAFwNAAACACIAXQ0AAAIABgBlDQAAAwA9AKQNAAABAA0AMw0AAAMAIwAOAAEKdA/7LQA7AAGODQAAAQAnAAAA.',
Sy='Sym:BAECNQAFFIEUAAIRAAYK0yMlAQB9AgaODQAABABfAHUNAAADAEcAfw0AAAMAXwCpDQAABABjAF0NAAACAFgAMw0AAAQAZAARAAYK0yMlAQB9AgaODQAABABfAHUNAAADAEcAfw0AAAMAXwCpDQAABABjAF0NAAACAFgAMw0AAAQAZAA1AAQKgRgAAhEACQqJJZcHAHADABEACQqJJZcHAHADAAAA.',
Ta='Talonflame:BAEANQAECgcIBAAAAA==.Tankurthunt:BAECNQAFFIEKAAIcAAUKzhrPAQDRAQV1DQAAAgBNAH8NAAACACYAqQ0AAAMAUgBcDQAAAQBKADMNAAACAEUAHAAFCs4azwEA0QEFdQ0AAAIATQB/DQAAAgAmAKkNAAADAFIAXA0AAAEASgAzDQAAAgBFADUABAqBKQACHAAJCsolywEA1AMAHAAJCsolywEA1AMAAAA=.',
Te='Terrazic:BAEANQAECgYJCwABNQAFFAMIBQAGANYZAA==.',
Th='Theemen:BAEANQAECgUIBQABNQAFFAQIBAAJAAAAAA==.Thetank:BAEANQAECgIIAgAAAA==.Thiaspala:BAEANQAECgUICAABNQAFFAYIDAAdABAgAA==.Thyruslock:BAEANQADCgcIBwABNQAFFAQJCgAHALQeAA==.',
To='Toseji:BAEANQADCgQIBAABNQAECgYIEgAJAAAAAA==.',
Ur='Ursaluna:BAECNQAFFIESAAIiAAYKGhtBAAAdAgaODQAAAwBgAHUNAAADADQAfw0AAAMAUACpDQAAAwBOAFwNAAACACcAMw0AAAQARQAiAAYKGhtBAAAdAgaODQAAAwBgAHUNAAADADQAfw0AAAMAUACpDQAAAwBOAFwNAAACACcAMw0AAAQARQA1AAQKgR4AAiIACQrVJNcAALoDACIACQrVJNcAALoDAAAA.',
Ve='Velèus:BAEANQAECgQIBwABNQAECgcIDQAJAAAAAA==.',
Vo='Vollêy:BAEANQAECggICAAAAA==.',
Wa='Waurynn:BAEANQAECgYJBgAAAA==.',
Xa='Xaenne:BAEBNQAECoEeAAIHAAkKYSJyFAA7AwmODQAABABiAHUNAAADAF4Afw0AAAMAWwCpDQAAAwBTAFwNAAADAFsAXQ0AAAMAXwBlDQAABQBhAKQNAAAEADIAMw0AAAIAWAAHAAkKYSJyFAA7AwmODQAABABiAHUNAAADAF4Afw0AAAMAWwCpDQAAAwBTAFwNAAADAFsAXQ0AAAMAXwBlDQAABQBhAKQNAAAEADIAMw0AAAIAWAAAAA==.',
Xe='Xeab:BAEANQAECggJEwABNQAFFAcJEwAdABsXAA==.Xeam:BAEANQAECgEJAQABNQAFFAcJEwAdABsXAA==.Xeav:BAECNQAFFIETAAIdAAcKGxccAQBgAgeODQAAAwA5AHUNAAADAFcAfw0AAAMAWQCpDQAAAwBEAFwNAAACAEMAXQ0AAAEABQAzDQAABAAnAB0ABwobFxwBAGACB44NAAADADkAdQ0AAAMAVwB/DQAAAwBZAKkNAAADAEQAXA0AAAIAQwBdDQAAAQAFADMNAAAEACcANQAECoEiAAMdAAkKCR+LEwDeAgAdAAkKCR+LEwDeAgAQAAQK+A5aDgDiAAAAAA==.',
Za='Zaljiri:BAEBNQAECoEYAAIIAAgKSRpxLABqAgiODQAABABJAHUNAAADAE0Afw0AAAQARgCpDQAABABMAFwNAAACAEUAXQ0AAAIARQBlDQAAAQASADMNAAAEAFEACAAICkkacSwAagIIjg0AAAQASQB1DQAAAwBNAH8NAAAEAEYAqQ0AAAQATABcDQAAAgBFAF0NAAACAEUAZQ0AAAEAEgAzDQAABABRAAAA.Zashi:BAEBNQAECoEbAAImAAgKcCK2BAAPAwiODQAAAwBfAHUNAAAEAFwAfw0AAAQAYACpDQAABABZAFwNAAAEAF0AXQ0AAAMATQBlDQAAAgBCADMNAAADAF0AJgAICnAitgQADwMIjg0AAAMAXwB1DQAABABcAH8NAAAEAGAAqQ0AAAQAWQBcDQAABABdAF0NAAADAE0AZQ0AAAIAQgAzDQAAAwBdAAAA.Zaxholydrago:BAECNQAFFIENAAIdAAYK7Q4pAwD6AQaODQAAAwA3AHUNAAACABsAfw0AAAEADwCpDQAAAwAwAFwNAAABAAQAMw0AAAMATAAdAAYK7Q4pAwD6AQaODQAAAwA3AHUNAAACABsAfw0AAAEADwCpDQAAAwAwAFwNAAABAAQAMw0AAAMATAA1AAQKgSQAAx0ACQpVIkgJADsDAB0ACQpAIkgJADsDABAABwotF5IFAOsBAAAA.',
['Äm']='Ämy:BAEANQADCgUJBQABNQAECgYIEgAJAAAAAA==.',
['Ñÿ']='Ñÿü:BAECNQAFFIENAAIWAAQKZBVLAgB8AQSODQAABABgAHUNAAADAD0Afw0AAAMAGQCpDQAAAwAkABYABApkFUsCAHwBBI4NAAAEAGAAdQ0AAAMAPQB/DQAAAwAZAKkNAAADACQANQAECoEcAAMWAAkKYSUJAwB3AwAWAAkKYSUJAwB3AwAbAAEKMwxiQAA0AAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
