local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'DeathKnight-Blood','DeathKnight-Unholy','Warrior-Arms','Priest-Holy','Priest-Shadow','DemonHunter-Devourer','Paladin-Retribution','Paladin-Protection','Mage-Frost','Mage-Arcane','DemonHunter-Havoc','Paladin-Holy','Warlock-Destruction','Unknown-Unknown','Rogue-Subtlety','Druid-Feral','Warlock-Affliction','Warlock-Demonology','Rogue-Assassination','Warrior-Fury','Warrior-Protection','Druid-Balance','Priest-Discipline','Shaman-Restoration','Evoker-Devastation','Evoker-Augmentation','Hunter-Marksmanship','Hunter-BeastMastery','Druid-Restoration','DeathKnight-Frost','Shaman-Elemental','Monk-Brewmaster','Shaman-Enhancement','Monk-Windwalker','DemonHunter-Vengeance','Evoker-Preservation','Druid-Guardian','Hunter-Survival','Monk-Mistweaver',}
local provider = {region='US',realm='Magtheridon',name='US',type='weekly',zone=53,date='2026-10-06',data={Ac='Acacia:BAAANQADCgcIDAAAAA==.',
Ae='Aeturnum:BAAANQAECgEIAQAAAA==.',
Ag='Agave:BAAANQAFFAIIAwAAAA==.',
Ai='Aizun:BAABNQAECoEYAAMBAAkKcSJXCwBKAwABAAkKcSJXCwBKAwACAAcKkBJBZgBSAQAAAA==.',
Ak='Akulagos:BAAANQAECgQIBgAAAA==.',
Al='Alakavahm:BAAANQADCgQIBAAAAA==.Aldenfire:BAAANQADCgYICQAAAA==.Alesce:BAABNQAECoErAAIDAAkK1RSwZABBAgADAAkK1RSwZABBAgAAAA==.Alii:BAAANQAECgQICAAAAA==.',
Am='Amaraukyou:BAAANQADCgYIBwAAAA==.Amenadiel:BAABNQAECoEfAAMEAAgKtx4QJwCxAgAEAAgKtx4QJwCxAgAFAAEKPBPYZgBAAAAAAA==.Amythistle:BAAANQAECgQICAAAAA==.',
An='Ancksunamun:BAAANQAECgIIAwAAAA==.Andrü:BAABNQAECoEnAAIDAAgKYBegYwBFAgADAAgKYBegYwBFAgAAAA==.Antiquated:BAAANQAECgcIDwAAAA==.',
Ap='Apsalar:BAAANQAECgQIBwAAAA==.',
Ar='Arcanetarts:BAAANQADCggICAABNQAECgkJKwAGAHIYAA==.Arnblass:BAABNQAECoEdAAIHAAgK2hkXZgA8AgAHAAgK2hkXZgA8AgAAAA==.',
As='Ascend:BAABNQAECoEcAAIFAAgKPh46EgC9AgAFAAgKPh46EgC9AgAAAA==.Ashtana:BAAANQAECgMIBAAAAA==.Ashtar:BAABNQAECoEpAAMHAAgKZxRedgARAgAHAAgKZxRedgARAgAIAAMKiQcCUQBwAAAAAA==.Ashwana:BAAANQADCgIIAgAAAA==.',
Au='Aurora:BAAANQADCgcIBwAAAA==.',
Av='Aviee:BAABNQAECoEnAAMJAAgKthxrCgDwAQAKAAcKdBoklAA7AgAJAAUKICRrCgDwAQAAAA==.',
Ax='Axidin:BAAANQAECgYICgAAAA==.',
Az='Azazi:BAAANQAECggICQAAAA==.Azgul:BAAANQADCgYIDQAAAA==.Azula:BAAANQADCgEIAQAAAA==.Azushi:BAAANQAECgMIBAABNQAFFAcIEgADAK0JAA==.',
Ba='Babyfox:BAAANQADCgMIAwAAAA==.Babymage:BAACNQAFFIEIAAMJAAQKAQ5uAQAgAQAJAAQKQAtuAQAgAQAKAAIKNQnSQQCPAAA1AAQKgS0AAwkACQpuGYcQAHUBAAoACQq8FHuBAGMCAAkABQpSFocQAHUBAAAA.Badform:BAAANQAECgQIDAAAAA==.Badkitteh:BAAANQADCggIFAAAAA==.Baelstrom:BAAANQADCgIIAgABNQAECgkJIAALAIkeAA==.Baendron:BAABNQAECoEkAAIBAAgKQBmHLQBDAgABAAgKQBmHLQBDAgAAAA==.Bahcrypt:BAAANQADCgYIDAAAAA==.Bahnna:BAAANQAECgEIAQAAAA==.Bakaris:BAAANQADCgUIBQAAAA==.Barbarik:BAABNQAECoEgAAIMAAgKyQ2AZQDBAQAMAAgKyQ2AZQDBAQABNQAFFAQIBgANAJMXAA==.Barberry:BAAANQADCgQIBAABNQAECgIIAgAOAAAAAA==.Baretwallace:BAAANQAFFAEIAgABNQAFFAQICQAPAL8RAA==.Battlereaddy:BAAANQAECgYIBwAAAA==.Bayesian:BAAANQABCgIIAgAAAA==.',
Be='Beefwildfire:BAAANQADCggIDQAAAA==.Beerbeeotch:BAAANQADCggICAAAAA==.Beercheer:BAAANQADCgUIEAAAAA==.Beertholomew:BAABNQAECoEXAAIQAAcKJBnzDAAbAgAQAAcKJBnzDAAbAgAAAA==.Beestkyn:BAAANQAECgMIAwABNQAECgcIDAAOAAAAAA==.Behodakhtala:BAAANQADCgYIFQAAAA==.Bellanzo:BAABNQAECoEYAAIKAAkKvxVagwBfAgAKAAkKvxVagwBfAgAAAA==.Bellawaifu:BAAANQABCgQIBAAAAA==.',
Bi='Bigzee:BAEBNQAECoEpAAMRAAkK4xiDBQBGAgARAAgKehmDBQBGAgASAAYKog++ogBgAQABNQAFFAMIAwAOAAAAAA==.Bindanini:BAAANQADCgUICQABNQAECgQICAAOAAAAAA==.',
Bl='Blargin:BAAANQADCgIJAgAAAA==.Blorgin:BAACNQAFFIEWAAMPAAcKeRucBADPAQAPAAUKDxqcBADPAQATAAMKTR0BCgAPAQA1AAQKgS4AAw8ACQroJdwDAFcDAA8ACAphJtwDAFcDABMABgojI60xAN8BAAAA.Bluntmàn:BAAANQAECgUIEQAAAA==.',
Bo='Boogieman:BAAANQADCgYIBgAAAA==.Boohwodoy:BAAANQAECgMIAwAAAA==.Bookers:BAABNQAECoEcAAILAAgKohRULgAFAgALAAgKohRULgAFAgAAAA==.Booplzs:BAAANQADCgUIBQAAAA==.Borgo:BAAANQADCgMIAwABNQAECgkJIAAKADEPAA==.Borugg:BAAANQAECgYIBgAAAA==.Bouladin:BAAANQAECgMIAwABNQAECgYICQAOAAAAAA==.Boulangerie:BAACNQAFFIEXAAIFAAcKJiCsAADSAgAFAAcKJiCsAADSAgA1AAQKgTEAAwUACQqPJg4BANcDAAUACQqPJg4BANcDAAQABAqGEYKlAOkAAAAA.Boulasive:BAAANQAECgQIBAAAAA==.Boulight:BAAANQAECgYICQAAAA==.Boulior:BAAANQAECgIIBAAAAA==.Bowvice:BAEANQADCgUIBQABNQAECgkJNAAHALQjAA==.Boyd:BAACNQAFFIEHAAIUAAQKCQ78AAA8AQAUAAQKCQ78AAA8AQA1AAQKgS8ABBQACQpqIHkCADMDABQACQpqIHkCADMDAAMAAQrPCoAuATsAABUAAQqrAYZDABkAAAAA.',
Br='Brewmungandr:BAAANQAECgYIBgAAAA==.Brodir:BAAANQAECgUIBQAAAA==.Bromayzo:BAAANQABCgIJAgAAAA==.',
['Bø']='Bøøgiêman:BAAANQAECgYIDQAAAA==.',
Ca='Cainpain:BAAANQADCgYICwAAAA==.Canadatrash:BAAANQAECgUIBwABNQAFFAQICQAPAL8RAA==.Carraway:BAABNQAECoEoAAIWAAkKUhjRIgCaAgAWAAkKUhjRIgCaAgAAAA==.Cashewz:BAAANQADCgQIBAAAAA==.Casterella:BAAANQAECgUICQAAAA==.',
Ce='Ceasarsalad:BAACNQAFFIELAAMSAAQKfhBXGgDvAAASAAMKARVXGgDvAAANAAIK8Ag6DwCTAAA1AAQKgTQAAxIACQoZIDEbAAQDABIACQqlHTEbAAQDAA0ABwoQFioNABkCAAAA.Ceazitt:BAABNQAECoEaAAQXAAgK1g9yCADFAQAXAAgKJQ5yCADFAQAFAAUKUBIbOwAnAQAEAAQKwArzsgDGAAAAAA==.Ceazyweasley:BAAANQAECgMIBAABNQAECggIGgAXANYPAA==.Ceci:BAAANQABCgMJAwAAAA==.Celestriå:BAAANQAECgEIAQAAAA==.Cetana:BAACNQAFFIEJAAMPAAQKvxFNCgD/AAAPAAMKJA9NCgD/AAATAAEKjhkZFwBUAAA1AAQKgSkAAw8ACQp6IhoUADcCAA8ABgraIhoUADcCABMABAojIhlGAGcBAAAA.',
Ch='Chadlockb:BAACNQAFFIESAAQNAAYKcSJ4BQDBAAASAAMKRSQ3EgA7AQANAAIKFyF4BQDBAAARAAEKqB/NBgBeAAA1AAQKgScAAxIACQr5JVgNAFADABIACArrJVgNAFADAA0ABQpFI7oTAMoBAAAA.Cheesee:BAABNQAECoEnAAIYAAgKpB/TIgC9AgAYAAgKpB/TIgC9AgAAAA==.Chiko:BAAANQAECgYIDgAAAA==.Christlike:BAAANQADCgcIBwAAAA==.Chronite:BAABNQAECoEgAAMKAAkKMQ8kngAmAgAKAAkKHg4kngAmAgAJAAUKEQt7HgDSAAAAAA==.Chucho:BAAANQADCgYIBgAAAA==.Chárgers:BAAANQAECgUICQAAAA==.',
Ci='Cindr:BAACNQAFFIEOAAIZAAYKbB1fAQArAgAZAAYKbB1fAQArAgA1AAQKgSkAAxkACQpRJNkCAHQDABkACQo3JNkCAHQDABoABQpLGcsRAOcAAAAA.Circumstance:BAAANQAECgUIBQAAAA==.',
Cl='Cleattus:BAABNQAECoEdAAMSAAgKXxjiQQBwAgASAAgKXxjiQQBwAgARAAMKvg4VGACoAAAAAA==.',
Co='Coconutsteve:BAAANQAECggICwAAAA==.Colddblooded:BAAANQAECgUIEgAAAA==.Cololol:BAACNQAFFIEVAAMGAAcKpiGuAAC1AgAGAAcKpiGuAAC1AgALAAEKSgX/GgA9AAA1AAQKgT4AAwYACQqSJnkAAPoDAAYACQqSJnkAAPoDAAsABArIJeY4ALcBAAAA.Compcomp:BAAANQAECgMIBAAAAA==.Compi:BAAANQAECgEIAQABNQAECgMIBAAOAAAAAA==.Cooper:BAABNQAECoEmAAIbAAgKPyIKCwAWAwAbAAgKPyIKCwAWAwAAAA==.Corlys:BAABNQAECoEiAAIKAAgKWB0wYACrAgAKAAgKWB0wYACrAgAAAA==.',
Cr='Crew:BAACNQAFFIEGAAILAAQKzBpxCgBCAQALAAQKzBpxCgBCAQA1AAQKgT8AAwsACQp5JcgCAMEDAAsACQp5JcgCAMEDAAYAAQqjDIlfADQAAAAA.Critflicker:BAAANQADCgYIEwAAAA==.Cronoz:BAABNQAECoElAAIWAAkKHiJ3CQB2AwAWAAkKHiJ3CQB2AwAAAA==.',
Cu='Cucokai:BAAANQAECgYIDQAAAA==.Cuddles:BAAANQAECgUIDAAAAA==.Cuddlestomp:BAACNQAFFIEVAAMbAAcKlxuKBAD+AQAbAAYKJR6KBAD+AQAcAAMKLhRPFADwAAA1AAQKgSsAAxsACQotI6gLAA4DABsACArSJKgLAA4DABwABgrCEce1AGQBAAAA.',
Cy='Cynical:BAAANQAECgcIDAABNQAFFAcICQAIANMPAA==.',
Cz='Czernabog:BAABNQAECoEWAAIdAAgKzRB8IgDmAQAdAAgKzRB8IgDmAQAAAA==.',
['Cä']='Cämulos:BAAANQAECgcIEwAAAA==.',
['Cí']='Círí:BAEANQAECgcIDQABNQAECgcIGAADAAIjAA==.',
Da='Dabbosh:BAAANQAECgYICgAAAA==.Daedrec:BAAANQADCgQIBAABNQAFFAIIBAAOAAAAAA==.Dahl:BAAANQAECgQIDAABNQAECgkJHAAIADUiAA==.Damnhammer:BAACNQAFFIEIAAIMAAQKPxFlDgBCAQAMAAQKPxFlDgBCAQA1AAQKgSMAAgwACQphH2oTACUDAAwACQphH2oTACUDAAAA.Dandalight:BAAANQABCgQIBAAAAA==.Dandie:BAAANQAECgYICAAAAA==.Darkstranger:BAAANQADCgQIBAAAAA==.Darthjinwoo:BAABNQAECoEiAAMPAAkKTxKsEABhAgAPAAkKTxKsEABhAgATAAQKmQqKYADiAAAAAA==.Darthmerlin:BAAANQADCgQIBAABNQAECgkJIgAPAE8SAA==.Dasakko:BAAANQAECgMIAwABNQAFFAQIBwAeANIPAA==.Dasmonko:BAAANQAECgIIAgABNQAFFAQIBwAeANIPAA==.',
Db='Dbowzillaz:BAACNQAFFIEMAAIbAAUKKh5+BwCsAQAbAAUKKh5+BwCsAQA1AAQKgSAAAhsACQo0JJUIADwDABsACQo0JJUIADwDAAAA.',
De='Deathskeeper:BAAANQADCgYJDAAAAA==.Deathsled:BAAANQADCgEIAQAAAA==.Deedee:BAAANQADCgcIBwAAAA==.Demithania:BAAANQAECgIIAwAAAA==.Demonhunterl:BAAANQAECgYIDgAAAA==.Demontim:BAAANQADCgcIBwAAAA==.Demungandr:BAAANQAECggIDQAAAA==.Denden:BAAANQAECgQIBAAAAA==.',
Dh='Dhsil:BAAANQAECgQICgABNQAECgkJGAAQAIoWAA==.',
Di='Diabòlic:BAACNQAFFIETAAMSAAcKkRNJBAAKAgASAAYKzxRJBAAKAgANAAIKcBjXBgC3AAA1AAQKgSkABBIACQoyIlw1AJoCABIACArvH1w1AJoCAA0ABQrbGdMcAH8BABEAAgr+EycaAI8AAAAA.Dirtydiana:BAAANQAECgcIEgAAAA==.',
Dj='Djavol:BAABNQAECoEgAAILAAkKiR5rDgAaAwALAAkKiR5rDgAaAwAAAA==.',
Do='Doc:BAAANQADCgYIEAAAAA==.Doguntarth:BAACNQAFFIESAAIDAAcKrQnJCAD5AQADAAcKrQnJCAD5AQA1AAQKgSwAAgMACQrrHGE3AM8CAAMACQrrHGE3AM8CAAAA.Domerneth:BAAANQADCgYIBwAAAA==.Dominium:BAAANQABCgIIAgAAAA==.',
Dr='Drafi:BAAANQADCgIIAgABNQAECgEIAgAOAAAAAA==.Drankincup:BAACNQAFFIEVAAIfAAYK9BTqBQD0AQAfAAYK9BTqBQD0AQA1AAQKgTEAAh8ACQqVIngNAHADAB8ACQqVIngNAHADAAAA.Drankinkup:BAAANQAECggIEgABNQAFFAYIFQAfAPQUAA==.Drderp:BAAANQADCgQIAwAAAA==.Drstagger:BAEBNQAECoElAAIgAAgKmybjAQCNAwAgAAgKmybjAQCNAwABNQAECgkJMAAgAKgmAA==.',
Du='Dullahan:BAAANQADCgQIBAAAAA==.Durotann:BAABNQAECoEaAAIcAAYKxAjYvABVAQAcAAYKxAjYvABVAQAAAA==.Dusios:BAAANQADCggIJgAAAA==.Duskflower:BAACNQAFFIELAAIdAAUKdBb4BACrAQAdAAUKdBb4BACrAQA1AAQKgTIAAh0ACQqXI2UCAJ4DAB0ACQqXI2UCAJ4DAAAA.',
Dy='Dyslexcia:BAAANQADCgEIAQAAAA==.',
Ed='Eddard:BAAANQAECgEIAQAAAA==.',
El='Elexandur:BAABNQAECoEVAAIhAAkKyRquCgCzAgAhAAkKyRquCgCzAgAAAA==.Elissa:BAAANQADCgYIBgAAAA==.Eliänna:BAAANQADCgIIAgAAAA==.Elleri:BAABNQAECoEbAAIHAAgKGQxyngCuAQAHAAgKGQxyngCuAQAAAA==.',
Em='Emyi:BAAANQAECgUICAAAAA==.',
Ep='Epnokicks:BAACNQAFFIENAAIiAAUKaBV6BQCQAQAiAAUKaBV6BQCQAQA1AAQKgTAAAiIACQrfI6UEAHsDACIACQrfI6UEAHsDAAAA.',
Er='Eroicel:BAACNQAFFIELAAIjAAQK+Q8RAgACAQAjAAQK+Q8RAgACAQA1AAQKgTQAAiMACQosHo4DAAEDACMACQosHo4DAAEDAAAA.',
Es='Esposr:BAAANQAECggIEgAAAA==.',
Ev='Evarielle:BAABNQAECoEcAAIBAAgKsg+XSwCoAQABAAgKsg+XSwCoAQABNQAFFAQICwAjAPkPAA==.',
Fa='Faalindh:BAABNQAECoEZAAILAAgKgBJgLgAFAgALAAgKgBJgLgAFAgAAAA==.Fadedhalo:BAABNQAECoEbAAIEAAcKuA1mdwB8AQAEAAcKuA1mdwB8AQAAAA==.Fadë:BAAANQAECgEIAQAAAA==.Falaya:BAACNQAFFIENAAMNAAUKwRd4CQCqAAASAAMKGRYAGAD/AAANAAIKPRp4CQCqAAA1AAQKgTQABA0ACQqNJXIHAIICAA0ABgpPJXIHAIICABIABgpXI39HAF8CABEAAQqTI8UiAFAAAAAA.Fallinorion:BAAANQADCgQIBAAAAA==.Falst:BAABNQAECoEkAAMfAAgKeh2SKAC9AgAfAAgKeh2SKAC9AgAYAAYKvR2gWADZAQAAAA==.Farion:BAAANQAECgYICwAAAA==.',
Fe='Feldoyle:BAAANQAECgUIBQAAAA==.Felyathas:BAAANQADCgQIBQABNQAECgYIEQAOAAAAAA==.Fennlar:BAABNQAECoEiAAIKAAkKdBJIhgBYAgAKAAkKdBJIhgBYAgAAAA==.Fersos:BAAANQABCgMIAwAAAA==.',
Fl='Flakey:BAAANQABCgIIAgAAAA==.Flawlessxi:BAABNQAECoEnAAIKAAkKSySVDQCZAwAKAAkKSySVDQCZAwAAAA==.Flyntflosy:BAACNQAFFIEKAAIfAAUKABTlCQCeAQAfAAUKABTlCQCeAQA1AAQKgSsAAh8ACQpvIdQPAFwDAB8ACQpvIdQPAFwDAAAA.',
Fo='Fowl:BAABNQAECoEfAAMLAAkKpBIzMwDgAQALAAcKyBUzMwDgAQAGAAgK8AqjLQCyAQAAAA==.Fowlie:BAAANQADCgIIAgAAAA==.',
Fr='Fragment:BAAANQABCgIIAwAAAA==.Freddy:BAAANQADCgMIAwAAAA==.',
Fu='Fuehriån:BAABNQAECoEuAAIKAAkKwxPehABbAgAKAAkKwxPehABbAgAAAA==.Funstar:BAAANQADCgYIBgABNQAFFAUIDAAkAKkWAA==.Furic:BAAANQADCgMJAwABNQAECggIHAAFAD4eAA==.Furyess:BAABNQAECoEqAAIHAAgKaCAOOADNAgAHAAgKaCAOOADNAgAAAA==.',
Ga='Gaelsi:BAAANQAECggIEgAAAA==.Galactic:BAAANQAECgUICgABNQAFFAIIBgAlAK0jAA==.Galgore:BAAANQAECggIEQAAAA==.Garolok:BAABNQAECoEjAAIDAAgKFRzYVQBtAgADAAgKFRzYVQBtAgAAAA==.Gasandflames:BAAANQAECgYICwAAAA==.Gascans:BAAANQAECgUIDQAAAA==.Gazelle:BAEBNQAECoEmAAIgAAgKkxuJCACDAgAgAAgKkxuJCACDAgAAAA==.Gazerakhan:BAABNQAECoEVAAIfAAgKKxIEVgD1AQAfAAgKKxIEVgD1AQABNQAECgkJKwAGAHIYAA==.Gazerielle:BAABNQAECoErAAMGAAkKchh1FwCKAgAGAAkKtRZ1FwCKAgALAAIKXw71cAB7AAAAAA==.',
Ge='Gerpsters:BAAANQABCgQIBAAAAA==.',
Gl='Glizzylizzy:BAACNQAFFIEIAAIhAAQKrh48AgCFAQAhAAQKrh48AgCFAQA1AAQKgSgAAiEACQoAJHICAIMDACEACQoAJHICAIMDAAAA.',
Go='Gothgrippers:BAAANQAECgcIDwAAAA==.Gowownage:BAACNQAFFIEGAAIlAAIKrSPoAwDIAAAlAAIKrSPoAwDIAAA1AAQKgRwAAiUACQoxJsYAAOUDACUACQoxJsYAAOUDAAAA.',
Gr='Gracebinder:BAAANQAECgUIBQAAAA==.Gradeus:BAACNQAFFIEQAAIHAAYKLA0gBgDMAQAHAAYKLA0gBgDMAQA1AAQKgSsAAwcACQoeIMYwAOgCAAcACQoeIMYwAOgCAAwAAQq3B0wDAToAAAAA.Granddh:BAACNQAFFIELAAILAAQKniAuCACDAQALAAQKniAuCACDAQA1AAQKgTcAAwsACQrDJXsDALIDAAsACQq8JXsDALIDACMABwoyIK0GAH8CAAAA.Graydius:BAAANQAECgYICgAAAA==.Greenmango:BAAANQAECgIIAgABNQAFFAQICAAJAAEOAA==.Grimeclipse:BAAANQAECgYIEgAAAA==.Grimr:BAAANQAECgYICwAAAA==.Grovehart:BAAANQAECgcIDAAAAA==.Grumpin:BAAANQADCggIDQABNQAECgYICwAOAAAAAA==.Grumpoo:BAAANQAECgYICwAAAA==.',
Gu='Gurt:BAAANQADCgUIBQAAAA==.Gutz:BAAANQAECgUIBQAAAA==.',
Ha='Hadris:BAAANQAECgQIBAAAAA==.Haku:BAAANQAECgcIEgAAAA==.Haldir:BAAANQADCgQIBAAAAA==.Halestorm:BAAANQAECgEJAQAAAA==.Hattori:BAAANQABCgYICgAAAA==.Havefun:BAABNQAECoEhAAMYAAkKCB8KEQAnAwAYAAkKCB8KEQAnAwAfAAYKXhTZewCAAQABNQAFFAUIDAAkAKkWAA==.',
He='Hedonist:BAABNQAECoEZAAIVAAkKVxT3DQAjAgAVAAkKVxT3DQAjAgABNQAFFAQIBgANAJMXAA==.Hellsbringer:BAAANQAECgQICQAAAA==.Heretik:BAAANQAECgQIBwAAAA==.Hevnoraak:BAAANQAECgYIEAAAAA==.',
Ho='Hogun:BAAANQADCgQIBAAAAA==.Hold:BAACNQAFFIEIAAMGAAQKMxSqCAA4AQAGAAQK8hGqCAA4AQALAAIKzBylEACuAAA1AAQKgSkAAwYACQoeI8AGAF4DAAYACQrRIsAGAF4DAAsABwrLFugzANoBAAAA.Holycandi:BAAANQAECgMICQABNQAECgQICQAOAAAAAA==.Holycaru:BAAANQADCgcIBwAAAA==.Holydoyle:BAABNQAECoEaAAIMAAgKYRY6RQAyAgAMAAgKYRY6RQAyAgAAAA==.Holyho:BAABNQAECoEcAAIHAAkKUxU9ZgA7AgAHAAkKUxU9ZgA7AgAAAA==.Holyjuice:BAAANQAECgQICAAAAA==.Holyraz:BAAANQAFFAQIBAAAAA==.Hotpøcket:BAACNQAFFIELAAMWAAUKXRSVDwA4AQAWAAQKDBaVDwA4AQAdAAEKNhCmEABPAAA1AAQKgSsAAxYACQpHH8wQAC4DABYACQpHH8wQAC4DAB0ACQpeEcYbAC0CAAAA.',
Hu='Huntlzs:BAABNQAECoEmAAIbAAkKxxeuFgCOAgAbAAkKxxeuFgCOAgAAAA==.',
Hy='Hyperìen:BAECNQAFFIEXAAIIAAcKCyGdAACZAgAIAAcKCyGdAACZAgA1AAQKgS0AAggACQpdJngCAJsDAAgACQpdJngCAJsDAAAA.',
['Hø']='Hølý:BAAANQAECgcIEQAAAA==.',
Ic='Icedoggi:BAABNQAECoEkAAIlAAgKrB6kCAC8AgAlAAgKrB6kCAC8AgAAAA==.',
Il='Illzilla:BAAANQADCgIIAgAAAA==.',
Im='Immortalmage:BAAANQADCgYIBgAAAA==.Imsopro:BAAANQABCgIJAgAAAA==.',
In='Indeed:BAACNQAFFIEIAAMFAAQKtiAaCQA7AQAFAAMKUyMaCQA7AQAEAAEKWxbkKwBMAAA1AAQKgScABAUACQpnJUMCALMDAAUACQpnJUMCALMDABcABQoUJUcHAO0BAAQABAqeFOSSACIBAAE1AAUUBggRAAwAhR4A.Inferna:BAAANQADCgUIBQAAAA==.Innerbeast:BAAANQAECgQIBAABNQAFFAcIGwAXAIAjAA==.Intiq:BAAANQADCgMIAwAAAA==.',
Ir='Irbaboon:BAABNQAECoEXAAIDAAgKAxzPWQBhAgADAAgKAxzPWQBhAgAAAA==.Irreletaur:BAACNQAFFIEHAAIDAAUKHg5mEACCAQADAAUKHg5mEACCAQA1AAQKgTQAAgMACQpSIWgfACsDAAMACQpSIWgfACsDAAAA.',
It='Itisovernow:BAAANQADCgUICQABNQAECgEJAQAOAAAAAA==.Itsevokernow:BAAANQADCgUIBQABNQAECgEJAQAOAAAAAA==.Itsovernow:BAAANQAECgEJAQAAAA==.',
Iz='Izimir:BAAANQAECgYIEgAAAA==.',
Ja='Jamloo:BAAANQAECgUIBQAAAA==.Jampu:BAAANQAECgYIAQAAAA==.Jangokin:BAACNQAFFIEPAAIWAAYKsxWmBgD0AQAWAAYKsxWmBgD0AQA1AAQKgSEAAhYACQpPHzwbANQCABYACQpPHzwbANQCAAAA.Jayiasan:BAAANQAECgMIAwABNQAFFAcICgAKAMMQAA==.Jazz:BAAANQADCgUICQAAAA==.',
Je='Jermz:BAAANQADCgUIBgAAAA==.',
Ji='Jimbaha:BAAANQAECgMIAwAAAA==.Jinks:BAAANQADCgYIFAAAAA==.',
Jo='Joytoy:BAAANQADCgMIAwAAAA==.',
['Jè']='Jèrmz:BAAANQADCgYICQAAAA==.',
Ka='Kabang:BAABNQAECoEZAAIKAAcK7xl0qwAKAgAKAAcK7xl0qwAKAgAAAA==.Kachoo:BAABNQAECoEqAAMhAAkKhR1pBwD5AgAhAAkKhR1pBwD5AgAfAAUKqgzZpQAZAQAAAA==.Kaige:BAAANQAECgUIDAAAAA==.Kalithor:BAAANQAECgYIEQAAAA==.Kathoes:BAAANQAECgYICwAAAA==.Kazaroth:BAAANQADCggICAABNQAECgkJKgACAD0kAA==.',
Ke='Keeky:BAAANQADCggICAAAAA==.Kelennin:BAAANQADCgIIAgAAAA==.Kellwildfire:BAABNQAECoEqAAIUAAkKgBXXBgBuAgAUAAkKgBXXBgBuAgAAAA==.',
Kf='Kfish:BAAANQAECgIIAwAAAA==.',
Kh='Khamael:BAABNQAECoEcAAIJAAgKvxodBgB7AgAJAAgKvxodBgB7AgAAAA==.Kheiron:BAABNQAECoEeAAIbAAgKxBXtJQD7AQAbAAgKxBXtJQD7AQAAAA==.',
Ki='Kinu:BAABNQAECoEwAAMYAAkKnyHFDQA+AwAYAAkKnyHFDQA+AwAfAAIKnxyx3AClAAAAAA==.Kissmytotems:BAAANQADCgYICwABNQAECgQICAAOAAAAAA==.Kitane:BAAANQAECgYIDgAAAA==.',
Kl='Klarina:BAABNQAECoEmAAIMAAgKMB2/IgDKAgAMAAgKMB2/IgDKAgAAAA==.',
Kn='Knox:BAAANQAECgEIAQAAAA==.',
Ko='Kobieta:BAAANQADCggJCAAAAA==.Koda:BAAANQADCgYICgAAAA==.Kosolapaya:BAAANQADCgIIAgAAAA==.Kotharsevant:BAAANQADCgcIBwAAAA==.',
Ku='Kurolion:BAABNQAECoEeAAMbAAkKYCAIDAAKAwAbAAkKYCAIDAAKAwAmAAEKNwLqEgAfAAAAAA==.Kurzon:BAAANQADCgEIAQAAAA==.',
Kw='Kwanrbless:BAAANQADCgIIAgAAAA==.',
Ky='Kyasuka:BAAANQADCgIJAgAAAA==.Kyblade:BAABNQAECoEjAAIFAAgK+CJTCwAbAwAFAAgK+CJTCwAbAwAAAA==.',
['Kø']='Køs:BAABNQAECoEWAAQRAAgKnQ2BCADfAQARAAgKnQ2BCADfAQASAAcK8QfhqgBMAQANAAEK2w2WcAA4AAAAAA==.',
La='Lampro:BAAANQAECgIIAgABNQAFFAQICAASAMAXAA==.Lavajato:BAAANQADCgYICQABNQAECgQICAAOAAAAAA==.',
Le='Leemius:BAAANQAECgQIBwABNQAECgUIBQAOAAAAAA==.Leggolass:BAAANQAECgcICgABNQAECgkJHgADAOAdAA==.Leosbryn:BAABNQAECoEcAAINAAgK5hR3DAAlAgANAAgK5hR3DAAlAgAAAA==.Leviträ:BAAANQADCgUIBQAAAA==.',
Li='Liable:BAABNQAECoEfAAIFAAgK4BhOGgBWAgAFAAgK4BhOGgBWAgAAAA==.Ligmadeebliz:BAABNQAECoEhAAIFAAkKIx+vDAAJAwAFAAkKIx+vDAAJAwAAAA==.Lilfister:BAAANQAECgEIAQABNQAFFAYIEQAMAIUeAA==.Lilraz:BAAANQADCgYIBgAAAA==.Liltazzvert:BAABNQAECoEhAAIcAAgKFSXcEwA4AwAcAAgKFSXcEwA4AwAAAA==.Linksded:BAAANQAECgEJAQAAAA==.Listerfyne:BAAANQAECgQIBAAAAA==.Littlepain:BAAANQADCgQIBQAAAA==.',
Lu='Lucero:BAAANQAECgYIDgAAAA==.',
Ly='Lyra:BAAANQADCgUIBgABNQAECgQICAAOAAAAAA==.',
['Lû']='Lûpy:BAAANQADCggIDQABNQABCgQIBgAOAAAAAA==.',
Ma='Mabey:BAAANQAECgEJAQAAAA==.Maerron:BAAANQAECgMIBQAAAA==.Mafi:BAAANQABCgUIBQAAAA==.Mageblprows:BAAANQADCgcIGgAAAA==.Mangemonpain:BAAANQAECgIIAgABNQAECgYIEQAOAAAAAA==.Maraayla:BAAANQADCggICAAAAA==.Matikz:BAACNQAFFIEGAAIPAAUKwgfPBgCDAQAPAAUKwgfPBgCDAQA1AAQKgTMAAg8ACQpVIT8EAEoDAA8ACQpVIT8EAEoDAAAA.Maximages:BAAANQADCggIDwAAAA==.Maximon:BAAANQAECgUIBwAAAA==.Maylla:BAAANQADCgcIDgAAAA==.',
Me='Meddle:BAACNQAFFIEJAAIEAAUK9hylCgC3AQAEAAUK9hylCgC3AQA1AAQKgSQAAgQACQqLIv8fANQCAAQACQqLIv8fANQCAAAA.Mehrunesd:BAAANQAECgUIBwAAAA==.Meowwmix:BAAANQABCgIIAgAAAA==.Merrydeath:BAAANQADCgYICQAAAA==.Meyea:BAACNQAFFIESAAMCAAYK9SGwAQAkAgACAAYKTyGwAQAkAgABAAUKzhSYDABbAQA1AAQKgSwAAwIACQpiJksHAHoDAAIACQpiJksHAHoDAAEAAwoyHdZ4AO8AAAAA.',
Mi='Miller:BAABNQAECoEyAAMcAAkKhyHNJADmAgAcAAkKiR7NJADmAgAbAAkK9xTuGgBjAgAAAA==.Millyvoid:BAAANQADCgcJBwABNQAECgkJMgAcAIchAA==.Miru:BAAANQAECgEJAQAAAA==.Mitis:BAAANQADCgcICAAAAA==.Mizdems:BAABNQAECoEhAAIGAAgKaByFFwCKAgAGAAgKaByFFwCKAgAAAA==.',
Mo='Moistjustice:BAAANQAECgIIAgAAAA==.Moonfun:BAAANQADCgcICgABNQAFFAUIDAAkAKkWAA==.Motmot:BAAANQAECgMIBgABNQAECgkJHwALAKQSAA==.Moufon:BAAANQADCgYIHAAAAA==.',
My='Myrodragon:BAAANQAECgYICgAAAA==.Mythicfritz:BAAANQADCgMIAwAAAA==.',
['Mé']='Mércy:BAABNQAECoEhAAIdAAgK7CFBCwD6AgAdAAgK7CFBCwD6AgAAAA==.',
Na='Navah:BAAANQAECgYIDQAAAA==.',
Ne='Neandratroll:BAABNQAECoEWAAMcAAgKMRU+XAA2AgAcAAgK4hQ+XAA2AgAbAAUKjwoRSADpAAAAAA==.Necrodis:BAAANQAECgEIAQABNQAECgkJIAAKAMgcAA==.Nezemzy:BAAANQADCgUIBQABNQAECgcIDwAOAAAAAA==.',
Ni='Nightlevels:BAACNQAFFIESAAIEAAcKRxq5AgBzAgAEAAcKRxq5AgBzAgA1AAQKgSQABAQACQoeGhQ7AFkCAAQACQrSGRQ7AFkCAAUAAwpyE4pPAKgAABcAAQqTEW0hAEMAAAAA.Nivarr:BAAANQADCgMIAwAAAA==.',
No='No:BAABNQAECoEmAAMKAAcKhBOvwADfAQAKAAcKhBOvwADfAQAJAAIKXgyELgBoAAAAAA==.Nodens:BAAANQAECgcIDgAAAA==.Nogardd:BAABNQAECoEbAAIaAAgKpBb8BgAiAgAaAAgKpBb8BgAiAgAAAA==.Notpetya:BAAANQAECgcIDwAAAA==.Nottills:BAAANQADCgYIDAAAAA==.',
Nu='Nudleboi:BAAANQADCgUIBQAAAA==.Nuulruk:BAAANQAECgMJBQAAAA==.',
Ny='Nylaehh:BAAANQAECgEIAQAAAA==.Nyxtro:BAAANQAECgYIDwAAAA==.',
Oi='Oilslick:BAAANQAECgUICwAAAA==.',
Om='Ombrure:BAAANQAECgYIEQAAAA==.',
On='Onornu:BAACNQAFFIENAAIYAAUKqBpJBwDEAQAYAAUKqBpJBwDEAQA1AAQKgTcAAhgACQooJXoDAKQDABgACQooJXoDAKQDAAAA.',
Or='Orlidan:BAABNQAECoEhAAIIAAgKZSJ5CQDnAgAIAAgKZSJ5CQDnAgAAAA==.',
Ot='Oth:BAACNQAFFIEPAAIEAAYKVSEZAwBoAgAEAAYKVSEZAwBoAgA1AAQKgR8AAwQACQpHJiMCAMADAAQACQpHJiMCAMADABcAAgoOI90TAM8AAAAA.',
Ox='Oxylock:BAABNQAECoE0AAMSAAkKACPYCwBaAwASAAkKACPYCwBaAwANAAcKKQc4KQAkAQAAAA==.',
Pa='Palgeron:BAAANQADCgIJAgAAAA==.Pathlon:BAAANQADCggJGgAAAA==.',
Pe='Peetypirate:BAAANQAECgIIBAAAAA==.Pekapow:BAACNQAFFIEKAAInAAQKbRM/BQAzAQAnAAQKbRM/BQAzAQA1AAQKgS0AAycACQpvEjkWAOkBACcACQpvEjkWAOkBACIAAQoLDepcADkAAAAA.Peta:BAAANQAECgEIAQAAAA==.',
Ph='Phobius:BAACNQAFFIEHAAICAAQK4QvCDAATAQACAAQK4QvCDAATAQA1AAQKgSgAAgIACQr5GoorAGUCAAIACQr5GoorAGUCAAAA.',
Pi='Pinkmango:BAACNQAFFIEHAAIeAAQK0g+gBwAtAQAeAAQK0g+gBwAtAQA1AAQKgSUAAx4ACQqzGWAkAEACAB4ACQpEFmAkAEACAAIACArCFn1JAMkBAAAA.Pireyne:BAAANQADCgYICgAAAA==.Pistachioz:BAABNQAECoEVAAIlAAYKWyFqDwArAgAlAAYKWyFqDwArAgAAAA==.',
Pl='Playfultouch:BAAANQAECgQICwAAAA==.Plunkaplunk:BAAANQADCgcIEgAAAA==.',
Po='Polymorphine:BAAANQAECgQIBQAAAA==.Poonanypie:BAAANQAECgYIDwAAAA==.Poonzer:BAEBNQAECoE0AAIHAAkKtCOiDwB+AwAHAAkKtCOiDwB+AwAAAA==.Porosity:BAABNQAECoEkAAIYAAgKIQwAeAB1AQAYAAgKIQwAeAB1AQAAAA==.',
Pr='Pretreckless:BAAANQADCggICgAAAA==.Proudclod:BAAANQAECgYICAAAAA==.',
Qe='Qetesh:BAAANQADCggIDwAAAA==.',
Ra='Rageflame:BAAANQAECggICQAAAA==.Ragnan:BAAANQADCgYIEAAAAA==.Rain:BAAANQADCgUIBQABNQAECggIJgAMADAdAA==.Ralinis:BAAANQADCgYJDAABNQADCgUIBQAOAAAAAA==.Rathi:BAAANQAECggICwABNQAECggIFwADAAMcAA==.Ravicavasar:BAAANQADCgYICgAAAA==.Rawrschak:BAAANQADCgMIBQAAAA==.Razfu:BAABNQAECoEmAAInAAkKMyDzBgALAwAnAAkKMyDzBgALAwAAAA==.Razul:BAAANQADCggIGgAAAA==.Razzio:BAAANQADCgQIBAAAAA==.',
Re='Rearea:BAAANQADCgUIBQABNQAECgQICAAOAAAAAA==.Redharvest:BAABNQAECoEZAAIjAAgKmRgWCQAsAgAjAAgKmRgWCQAsAgAAAA==.Rekles:BAAANQADCgUIBQABNQAECgkJIAAZACYkAA==.Relentless:BAAANQAECgYIDAAAAA==.Retribution:BAAANQAECgUICAAAAA==.Reznoop:BAEBNQAECoEaAAMRAAgKiR2QAgDVAgARAAgKiR2QAgDVAgASAAEKqQ0ZHAFCAAABNQAECgkJNAAHALQjAA==.',
Ri='Richardtwist:BAAANQAECgEJAQAAAA==.Ringp:BAAANQAECgEIAQAAAA==.',
Rk='Rkoo:BAAANQAECgYIEQAAAA==.',
Ro='Roobee:BAAANQABCgMIBAABNQADCgYICgAOAAAAAA==.Rottingmango:BAAANQADCggICAABNQAFFAQIBwAWAIEJAA==.Roxzor:BAAANQAECggIDgABNQAECggIFwADAAMcAA==.Royok:BAABNQAECoEiAAIVAAgKNRpRDABEAgAVAAgKNRpRDABEAgAAAA==.',
Ru='Ruwey:BAAANQABCgIIAgAAAA==.',
Sa='Saenys:BAAANQADCggIBwAAAA==.Sakardi:BAAANQAECgYIEwAAAA==.Sawedoff:BAABNQAECoEkAAIcAAkKsSEGDQBlAwAcAAkKsSEGDQBlAwAAAA==.',
Sc='Scalybum:BAAANQAECgQIBAAAAA==.Scamall:BAAANQAECgEJAQAAAA==.Schizophreni:BAAANQAECggIEgABNQAFFAcIFwAFACYgAA==.Scionoffury:BAAANQAECgQIBAAAAA==.Scotcolumbus:BAABNQAECoEcAAIIAAkKNSKFBQA/AwAIAAkKNSKFBQA/AwAAAA==.Scullcrusher:BAAANQABCggIDQAAAA==.',
Se='Secsysalad:BAABNQAECoEYAAIEAAgKQBu9OABjAgAEAAgKQBu9OABjAgABNQAFFAQICwASAH4QAA==.Seefoo:BAAANQAECgIIAgABNQAECgcIDAAOAAAAAA==.Sekho:BAAANQAECgUICgAAAA==.Sekhy:BAAANQAECgEIAQABNQAECgUICgAOAAAAAA==.Sero:BAAANQAECgcIEwAAAA==.Serrafir:BAAANQADCgEIAQAAAA==.',
Sg='Sgsmagicman:BAAANQAFFAIIAwAAAA==.',
Sh='Shaamwow:BAAANQAECgQIEAAAAA==.Shackle:BAAANQADCgYIBwAAAA==.Shade:BAACNQAFFIEHAAMPAAQKuwVeCQAeAQAPAAQKtwVeCQAeAQATAAEKWQEsHQA2AAA1AAQKgSoAAw8ACQpQFlUNAJACAA8ACQoqFlUNAJACABMAAQqxDluHADoAAAAA.Shadoewolfe:BAAANQADCgYIEQAAAA==.Shageron:BAACNQAFFIEHAAMbAAUKFgfoDwARAQAbAAQKyQfoDwARAQAcAAEKSgRmKgBWAAA1AAQKgScAAxsACQrBIpUTAK8CABsACQpMIpUTAK8CABwACQrgD4aTALABAAAA.Shalladin:BAAANQAECgQICAAAAA==.Shallshock:BAABNQAECoErAAMYAAkK+BE3SwAKAgAYAAkK+BE3SwAKAgAfAAgK7BD+XADcAQAAAA==.Shandoe:BAAANQADCgQIBAAAAA==.Shankspec:BAACNQAFFIEIAAITAAQKMAoGCQAxAQATAAQKMAoGCQAxAQA1AAQKgSIAAhMACQq2IEwMAAkDABMACQq2IEwMAAkDAAAA.Shaolinshamy:BAABNQAECoEaAAIYAAcKgB3LOwBHAgAYAAcKgB3LOwBHAgAAAA==.Shazlo:BAAANQAFFAIIAwAAAA==.Shifterxmag:BAABNQAECoEmAAIKAAkKuCIRGABtAwAKAAkKuCIRGABtAwAAAA==.Shikaca:BAAANQADCggIEwAAAA==.Shinseina:BAABNQAECoEmAAIHAAgKeB5GQACvAgAHAAgKeB5GQACvAgAAAA==.Shockbite:BAAANQADCgYICwAAAA==.Shockdh:BAAANQAECgIIAgABNQAFFAQIBwAWAIEJAA==.Shockinawe:BAAANQAECgQIBAAAAA==.Short:BAAANQADCgIIAgAAAA==.Shämash:BAABNQAECoEYAAIDAAYKEg2xtwBhAQADAAYKEg2xtwBhAQAAAA==.Shöck:BAAANQAECgMICQAAAA==.',
Si='Sicastic:BAAANQAECgUICQABNQAECggIIAAcADgXAA==.Sicc:BAAANQAECgQICAABNQAECggIIAAcADgXAA==.Siccness:BAABNQAECoEgAAQcAAcKOBe1cAACAgAcAAcKOBe1cAACAgAmAAIK3gqADgB6AAAbAAIKJwYOagBgAAAAAA==.Sieben:BAAANQAECgEIAwAAAA==.Siic:BAAANQADCgYIBgABNQAECggIIAAcADgXAA==.Sindrex:BAACNQAFFIEIAAIkAAQK/hlfCgBYAQAkAAQK/hlfCgBYAQA1AAQKgSoAAiQACQp+JREBAMMDACQACQp+JREBAMMDAAE1AAQKAggCAA4AAAAA.',
Sk='Skwerl:BAAANQADCgMJAwAAAA==.',
Sl='Slimshammy:BAAANQADCgMIAwABNQAECgkJHgADAOAdAA==.Slurmage:BAABNQAECoEjAAIKAAgK/SPkKAA1AwAKAAgK/SPkKAA1AwAAAA==.',
Sm='Smittywerben:BAABNQAECoEhAAIYAAgKdiChGwDkAgAYAAgKdiChGwDkAgAAAA==.Smokfun:BAACNQAFFIEMAAIkAAUKqRZICACRAQAkAAUKqRZICACRAQA1AAQKgRgAAyQACQpWHfsJAPQCACQACQpWHfsJAPQCABoABQq1CcITAMgAAAAA.Smooshi:BAACNQAFFIEIAAIYAAQKOxOsDABWAQAYAAQKOxOsDABWAQA1AAQKgTMAAyEACQovHjgRADYCACEABwqrGzgRADYCABgACQpUF59HABgCAAAA.',
Sn='Sneaktarts:BAAANQAECgQICgABNQAECgkJKwAGAHIYAA==.',
So='Solidjen:BAEANQAFFAMIAwAAAA==.Sololeveling:BAABNQAECoEeAAIBAAYKtQwIaQArAQABAAYKtQwIaQArAQAAAA==.Sootor:BAAANQADCgYICwAAAA==.',
Sp='Spags:BAAANQAECgEJAQABNQAECgcIFwATAKAVAA==.Sparklefarts:BAAANQAECgEIAQAAAA==.Spewky:BAAANQAECgYICAABNQAECgkJJAAcALEhAA==.Splydershot:BAAANQADCgYICQAAAA==.',
St='Stabbydabby:BAAANQADCgIIAgAAAA==.Starfun:BAAANQAECgcIDwABNQAFFAUIDAAkAKkWAA==.Steelheals:BAAANQADCgYICwAAAA==.Stenzwar:BAAANQAECgEJAQABNQAFFAYIEgACAPUhAA==.Stepdaddyfun:BAAANQAECgYIBgABNQAFFAUIDAAkAKkWAA==.Stevensiegal:BAAANQADCgIIAgAAAA==.Stormbless:BAABNQAECoEyAAIiAAkKwR5pEQC2AgAiAAkKwR5pEQC2AgAAAA==.Stormfallz:BAABNQAECoEgAAIKAAkKyBwMVADIAgAKAAkKyBwMVADIAgAAAA==.',
Su='Superfrenzy:BAAANQADCgMIAwAAAA==.Supertotemz:BAAANQAECgEJAQAAAA==.Supervoid:BAAANQAFFAIIAgABNQAFFAIIBgAlAK0jAA==.',
Sw='Swag:BAAANQAECgEIAQABNQAECgUIBQAOAAAAAA==.Sweegie:BAABNQAECoEXAAMPAAgKdBkYEQBcAgAPAAgKBhkYEQBcAgATAAMKcg0yaQC8AAAAAA==.Sweegz:BAAANQADCggICQAAAA==.Sweetlou:BAAANQADCggICAAAAA==.',
Sy='Sydious:BAAANQADCgQIBAABNQAECggIGwACAB4ZAA==.Syds:BAABNQAECoEbAAMCAAgKHhkXOAAgAgACAAgK6BgXOAAgAgAeAAMK2xSJaAC3AAAAAA==.Sylaraa:BAAANQAECgMIAwABNQAECgkJHgAfAIsXAA==.Synapticzion:BAAANQAECggIDwAAAA==.',
['Sí']='Sílk:BAAANQADCggIIAAAAA==.',
Ta='Taara:BAABNQAECoEgAAMhAAkKeCT4CQDCAgAhAAcKMiT4CQDCAgAYAAcKLRQ7cACLAQAAAA==.Takeshi:BAAANQABCgIIBAAAAA==.Takkana:BAABNQAECoElAAMHAAkKaCbaAgDiAwAHAAkKaCbaAgDiAwAIAAIKbSJ5QgDBAAAAAA==.Tamped:BAAANQADCgcIEQAAAA==.Tatsuki:BAAANQABCgIIBAAAAA==.',
Tc='Tchaman:BAAANQAECgQIBAAAAA==.',
Te='Terk:BAACNQAFFIEUAAIhAAcKsiAsAADMAgAhAAcKsiAsAADMAgA1AAQKgS8ABCEACQoHJqcAANcDACEACQoHJqcAANcDAB8AAQoRJCn6AF4AABgAAQpkAwETASIAAAAA.',
Th='Thalrymere:BAABNQAECoEYAAIbAAgK2w0XLADHAQAbAAgK2w0XLADHAQAAAA==.Theory:BAAANQABCgEIAQAAAA==.Thiccerlegs:BAAANQAECgEJAQAAAA==.',
Ti='Tidebeard:BAACNQAFFIEQAAIYAAYKFxN+BQDwAQAYAAYKFxN+BQDwAQA1AAQKgSYAAhgACQruIAkeANcCABgACQruIAkeANcCAAAA.Tikz:BAABNQAECoEmAAISAAgKehIVYgAQAgASAAgKehIVYgAQAgAAAA==.',
To='Tock:BAABNQAECoFIAAMhAAkKBCHFBAA7AwAhAAkKBCHFBAA7AwAfAAYKZhHKjQBRAQAAAA==.Tokenwarrior:BAAANQAECgUIDQAAAA==.Touchmychuby:BAAANQAECgIIAgAAAA==.',
Tr='Tralina:BAAANQADCgMIAwABNQAFFAcICgAKAMMQAA==.Trapstâr:BAACNQAFFIEPAAIbAAcKuBWNAwAnAgAbAAcKuBWNAwAnAgA1AAQKgSEAAhsACQoHJMQDAJQDABsACQoHJMQDAJQDAAAA.Tretox:BAAANQADCggICAAAAA==.',
Ts='Tsarfun:BAAANQADCgcIBwABNQAFFAUIDAAkAKkWAA==.Tsireya:BAAANQAECgUIBQAAAA==.Tsunayoshii:BAAANQAECgcIDwAAAA==.',
Tu='Turaco:BAAANQAECgQIBAABNQAECgkJHwALAKQSAA==.Turf:BAAANQAECgQICAAAAA==.',
Tw='Twizzurp:BAAANQAECgEIAQABNQAECgMIBAAOAAAAAA==.',
Un='Undeadwaifu:BAAANQAECgQJBAAAAA==.Unkledeath:BAAANQAECgYIDQAAAA==.',
Va='Vaeryn:BAAANQADCggIHAAAAA==.Valesyrin:BAABNQAECoElAAISAAgK2xGGZAAIAgASAAgK2xGGZAAIAgAAAA==.Valura:BAAANQAECgIIAwAAAA==.Vansapanda:BAAANQADCggIEAAAAA==.Vaughn:BAACNQAFFIEHAAMDAAQKyAbuGAAPAQADAAQKCAbuGAAPAQAUAAIKrwj8AgCHAAA1AAQKgSYAAxQACQr8HHoFAJ8CABQACQpUGXoFAJ8CAAMACQpyF/xQAHwCAAAA.',
Ve='Veggieboi:BAAANQAFFAIIAwAAAA==.Veledra:BAAANQADCgUIBQAAAA==.Vellast:BAAANQAECgIIAgAAAA==.Vellinda:BAAANQAECgEIAQAAAA==.',
Vi='Viande:BAAANQADCgQIBAAAAA==.Victory:BAAANQAECgYICgAAAA==.Vigilo:BAACNQAFFIEJAAIiAAQKIBn/BgBQAQAiAAQKIBn/BgBQAQA1AAQKgSYAAiIACQqGIYcMAPcCACIACQqGIYcMAPcCAAAA.Vilhelmina:BAABNQAECoEfAAMPAAcKmBmBJgB7AQAPAAUKFBmBJgB7AQATAAIK4RpEcQCVAAAAAA==.Viruzdk:BAABNQAECoErAAQCAAkKJiNGFQD4AgACAAgKiSFGFQD4AgABAAgKvx8YHgCoAgAeAAIKFhmzdwB/AAAAAA==.',
Vl='Vlad:BAAANQAECgQIDAAAAA==.Vladivostok:BAAANQADCgEIAgAAAA==.',
Vy='Vyera:BAAANQABCggIDgAAAA==.',
Wa='Wafi:BAAANQAECgEIAgAAAA==.Wamp:BAACNQAFFIEIAAMSAAQKwBeqFwADAQASAAMKhxyqFwADAQANAAEKbAmCGwBNAAA1AAQKgSoAAxIACQqEH0gcAP4CABIACQqEH0gcAP4CAA0AAQpwDAp1ADMAAAAA.Warcheif:BAAANQADCgYICgABNQAECgYIGgAcAMQIAA==.Warlockl:BAAANQAECgQIBQAAAA==.Warwonka:BAACNQAFFIEIAAIbAAQKmwpzDwAZAQAbAAQKmwpzDwAZAQA1AAQKgSoAAhsACQozHJIUAKUCABsACQozHJIUAKUCAAAA.Watchurbeard:BAABNQAECoEjAAIcAAgK9hV7VgBGAgAcAAgK9hV7VgBGAgAAAA==.',
We='Weenrgulpr:BAAANQADCgcIFQAAAA==.Wetnoodle:BAAANQAECgQIBAABNQAECgkJKwAGAHIYAA==.',
Wh='Whamass:BAAANQAECgYIEwAAAA==.Whiiplash:BAAANQAECgIIAgAAAA==.Whippy:BAAANQADCggIDwABNQAECgIIAgAOAAAAAA==.',
Wi='Windowlicker:BAABNQAECoEeAAMiAAkKwxXIHAAlAgAiAAgK0xfIHAAlAgAnAAkKiQ9NFgDoAQAAAA==.Winnydafoo:BAAANQADCgQIBwAAAA==.',
Wr='Wrapfire:BAABNQAECoEXAAIKAAgKDhAvtQD2AQAKAAgKDhAvtQD2AQAAAA==.',
['Wí']='Wíldspirit:BAAANQADCgYIDwAAAA==.',
['Xè']='Xèra:BAAANQADCggIGAAAAA==.',
Ya='Yacob:BAACNQAFFIEWAAMKAAYKViTsCwD5AQAKAAUKpCPsCwD5AQAJAAIKJCTeAgDTAAA1AAQKgS0AAwoACQoKJmYQAIwDAAoACQpiJWYQAIwDAAkABQrmImIOAJgBAAAA.Yamarahj:BAACNQAFFIEGAAQNAAQKkxdbCACuAAANAAIK0xlbCACuAAASAAEK8hi2MgBTAAARAAEKsxF3CwBIAAA1AAQKgS4ABA0ACQorIrkJAFMCABIACAqOIcUeAPMCAA0ACAoWGbkJAFMCABEAAwo2HzQSAP4AAAAA.',
Yo='Yorikk:BAABNQAECoEYAAMNAAcKHBP9IABeAQANAAUKMRf9IABeAQASAAQKcwpp5wDMAAAAAA==.',
Yu='Yui:BAAANQABCgIIAgAAAA==.',
Za='Zaeo:BAAANQADCgcIBwAAAA==.Zafhir:BAAANQABCgUICAAAAA==.Zankanotachi:BAAANQAECgQICQAAAA==.Zarmaku:BAABNQAECoEcAAMYAAcKrRnvVADmAQAYAAcKrRnvVADmAQAfAAYKCQcOoQAkAQAAAA==.Zartath:BAAANQADCggIHwAAAA==.Zauber:BAACNQAFFIEUAAQRAAcKAyGsAACTAQASAAUKWx65BQDpAQARAAQKyCOsAACTAQANAAIKCCKtBQDAAAA1AAQKgTAABBIACQrmJgYBAOwDABIACQrGJgYBAOwDABEACQqEJloAALcDAA0ABwpxJTAHAIkCAAAA.Zazie:BAABNQAECoEmAAIjAAgKIh13BgCHAgAjAAgKIh13BgCHAgAAAA==.Zazu:BAAANQADCgIIAgAAAA==.',
Ze='Zeetti:BAEANQAECgMIAwABNQAFFAMIAwAOAAAAAA==.Zepian:BAAANQAECgYICAAAAA==.',
Zi='Zirraj:BAACNQAFFIEUAAMDAAcK6xlLBwAXAgADAAYKTRpLBwAXAgAUAAIKGBbcAQDGAAA1AAQKgSsAAwMACQr1JbAJAKEDAAMACQr1JbAJAKEDABQABQpjHfMQAHABAAAA.',
Zy='Zygon:BAAANQADCggIEAABNQAFFAIIBgAlAK0jAA==.',
['Âr']='Ârthilasi:BAAANQAECgQIBAAAAA==.',
['Èó']='Èówyn:BAAANQAECgQICAAAAA==.',
['Év']='Évié:BAEBNQAECoEYAAIDAAcKAiN6RACkAgADAAcKAiN6RACkAgAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
