local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Shaman-Restoration','Warlock-Demonology','Hunter-BeastMastery','Warlock-Destruction','Warlock-Affliction','Paladin-Retribution','Rogue-Assassination','Paladin-Protection','Evoker-Augmentation','Evoker-Devastation','Evoker-Preservation','DeathKnight-Unholy','DemonHunter-Devourer','Unknown-Unknown','DeathKnight-Frost','Priest-Holy','Priest-Shadow','Paladin-Holy','Rogue-Outlaw','Warrior-Arms','Warrior-Protection','Shaman-Elemental','DemonHunter-Havoc','Warrior-Fury','Shaman-Enhancement','Mage-Arcane','Mage-Frost','Druid-Restoration','Druid-Balance','DeathKnight-Blood','Monk-Mistweaver','Druid-Feral','Hunter-Marksmanship','Monk-Windwalker','Monk-Brewmaster','Rogue-Subtlety','DemonHunter-Vengeance','Druid-Guardian','Priest-Discipline',}
local provider = {region='US',realm='Thaurissan',name='US',type='weekly',zone=53,date='2026-10-06',data={Aa='Aarg:BAAANQAECggICAAAAA==.',
Ab='Abcede:BAAANQAECgMIBgABNQAECgkJKgABAJAdAA==.',
Ac='Accio:BAAANQAECgQIBAAAAA==.Achillguy:BAAANQADCgUIBQAAAA==.',
Ad='Adaa:BAAANQAECgEJAQAAAA==.',
Ae='Aeava:BAAANQAECgMIAwABNQAECggILQACALwMAA==.Aelene:BAAANQAECgQIBQAAAA==.',
Ag='Agnostic:BAABNQAECoElAAIDAAkK3R9MHgADAwADAAkK3R9MHgADAwAAAA==.Agonybehold:BAAANQAECgEIAQAAAA==.',
Ai='Aisa:BAACNQAFFIEhAAQEAAcKjR15AwDYAAACAAQK/BjdDAB4AQAEAAIKaSV5AwDYAAAFAAEKFyDCBgBfAAA1AAQKgSAABAQACQo2JegLAC4CAAQABgooI+gLAC4CAAIABgq7IwhgABUCAAUAAQpdJCAfAGYAAAAA.Aish:BAACNQAFFIEhAAIGAAcKaSHKAACyAgAGAAcKaSHKAACyAgA1AAQKgRoAAgYACQq8JngOAIUDAAYACQq8JngOAIUDAAAA.Aiso:BAAANQADCgYIBgAAAA==.',
Ak='Akali:BAACNQAFFIEPAAIHAAUKlSbSAQBGAgAHAAUKlSbSAQBGAgA1AAQKgTsAAgcACAr4JswCAKADAAcACAr4JswCAKADAAAA.',
Al='Alakazami:BAAANQADCgEIAQAAAA==.Aldofio:BAAANQAECgQIBwAAAA==.Aleson:BAAANQADCgYIBgAAAA==.Alhttabe:BAABNQAECoEfAAIIAAcKRCNvDACyAgAIAAcKRCNvDACyAgAAAA==.Alirann:BAABNQAFFIEJAAQJAAQKgQqkBwCMAAAJAAIKAAikBwCMAAAKAAIKRQPWCwB6AAALAAIKTQnjEwBvAAAAAA==.Alisu:BAAANQAECgYICQABNQAFFAMIBwAMAO4WAA==.Alvln:BAACNQAFFIENAAINAAUKUwv8BgCAAQANAAUKUwv8BgCAAQA1AAQKgTgAAg0ACQr5IcIFAG8DAA0ACQr5IcIFAG8DAAAA.',
An='Anduïn:BAAANQADCgIIAgABNQAECgcIKQAGACseAA==.Andyrios:BAAANQAECgUIEgAAAA==.',
Ap='Apoplectic:BAAANQAECgYIEAAAAA==.Apothic:BAAANQAECgEIAQAAAA==.',
Aq='Aquaila:BAAANQADCgcIBwABNQAECgIJAwAOAAAAAA==.',
Ar='Aradesya:BAAANQAECgUICAAAAA==.Aradinya:BAAANQADCggICAAAAA==.Arahat:BAAANQAECgYIBwAAAA==.Arakinya:BAABNQAECoEWAAIPAAgKPQt1PQCUAQAPAAgKPQt1PQCUAQAAAA==.Aralinya:BAACNQAFFIELAAIQAAUK9xjdEABYAQAQAAUK9xjdEABYAQA1AAQKgSoAAxAACQpOFxZKACACABAACQpOFxZKACACABEACArFERNcAGUAAAAA.Aratus:BAABNQAECoEXAAIGAAgKeRYLaQA0AgAGAAgKeRYLaQA0AgAAAA==.Ardentflame:BAABNQAECoEhAAMCAAgK5BQjbwDpAQACAAgK5BQjbwDpAQAFAAEKjA72KQA6AAAAAA==.Arindel:BAAANQADCgIIAgAAAA==.Aristosa:BAAANQAECgQIBAABNQAECgUICwAOAAAAAA==.Arsoul:BAAANQADCgIIAgAAAA==.',
As='Asperonia:BAACNQAFFIEhAAISAAcKCQ2jAwAyAgASAAcKCQ2jAwAyAgA1AAQKgSUAAhIACQrhGdUkAL8CABIACQrhGdUkAL8CAAAA.Asterisk:BAAANQAECgcICgABNQAFFAcIIQAEAI0dAA==.Astinous:BAAANQADCggICAAAAA==.Astlyr:BAAANQADCgUICAAAAA==.Astrid:BAACNQAFFIEXAAILAAcKwBJwAwAvAgALAAcKwBJwAwAvAgA1AAQKgSAAAwsACQpiIpIGADIDAAsACQpiIpIGADIDAAoAAQrzG5AzAFEAAAAA.',
At='Athera:BAAANQADCgYIBgAAAA==.Atiermonk:BAAANQAECgMIBAAAAA==.',
Au='Ausdemonic:BAAANQAECgQICAAAAA==.',
Av='Avell:BAABNQAECoEbAAISAAkKHCUDAwC5AwASAAkKHCUDAwC5AwAAAA==.Avocardio:BAAANQAECgYICwAAAA==.',
Ax='Axiomatic:BAAANQAECgYICAAAAA==.',
Az='Aziluth:BAAANQAECgYICAAAAA==.Azraél:BAAANQAECggIEAAAAA==.Azriox:BAAANQADCgUIBQAAAA==.Azsharia:BAAANQADCgYIBgAAAA==.Azzielliea:BAAANQAECgYJEQAAAA==.',
Ba='Badumdadoom:BAAANQAECgMIAwABNQAFFAcIEgATAFYiAA==.Balance:BAAANQAECgEIAgAAAA==.Barleybrew:BAAANQADCgIIAgABNQADCgEIAQAOAAAAAA==.Battletank:BAABNQAECoEiAAMUAAkKRhsJOQDJAgAUAAkKRhsJOQDJAgAVAAMKUgNoMQBvAAABNQAFFAUIDQANAFMLAA==.',
Be='Beefchar:BAAANQAECgEIAQAAAA==.Beefquake:BAABNQAECoEnAAMBAAkKUxvzKwCPAgABAAkKUxvzKwCPAgAWAAMK+Bf2xgDWAAAAAA==.Bel:BAAANQAECggIAgAAAA==.Betray:BAAANQAECgcIEgAAAA==.Beàr:BAAANQAECgQIBAAAAA==.',
Bi='Bigbadbaka:BAACNQAFFIEiAAIUAAcKmyAKAgC6AgAUAAcKmyAKAgC6AgA1AAQKgSkAAhQACQrRJekIAKYDABQACQrRJekIAKYDAAAA.Bigdecay:BAABNQAECoE0AAMMAAkK1yMgEwAJAwAMAAkK1yMgEwAJAwAPAAQKTxVnVwD/AAAAAA==.',
Bl='Blackfish:BAAANQAECgIIAgAAAA==.Blasez:BAABNQAECoEUAAIMAAcKERpGQgDsAQAMAAcKERpGQgDsAQAAAA==.Blazez:BAACNQAFFIELAAIGAAUKBxX3CACPAQAGAAUKBxX3CACPAQA1AAQKgTUAAgYACQr3JCoxAOYCAAYACQr3JCoxAOYCAAAA.Blazpew:BAAANQAECgMIAwAAAA==.Blood:BAEANQAECgEIAQABNQAECgcIDgAOAAAAAA==.',
Bo='Bogart:BAACNQAFFIEPAAMCAAUKhxb5CQCdAQACAAUKhxb5CQCdAQAEAAEKYg4iGQBQAAA1AAQKgS4ABAQACQq4ItEoACcBAAIACApsIn9/ALsBAAQABAqNHNEoACcBAAUAAQpwHwEhAFoAAAAA.Bomohdh:BAABNQAECoEcAAIXAAkKTBuwKgAhAgAXAAkKTBuwKgAhAgABNQAFFAUICgAUACARAA==.Bomohomo:BAACNQAFFIEKAAMUAAUKIBEqFgAzAQAUAAQKuREqFgAzAQAYAAEKuw4DBABXAAA1AAQKgSQAAhQACQq0H6kxAOUCABQACQq0H6kxAOUCAAAA.Boogeymayne:BAAANQADCgIIAgAAAA==.Bootycallz:BAAANQAECgEJAQAAAA==.Bossimón:BAAANQAECgQIBQAAAA==.',
Br='Brainlag:BAAANQAECgIIAgABNQAECgUIBQAOAAAAAA==.Brawny:BAAANQAECgYIDwAAAA==.Brev:BAAANQADCgEIAQABNQAECggIGQAZAIgdAA==.Brevren:BAAANQADCgMIAwABNQAECggIGQAZAIgdAA==.Brevrin:BAABNQAECoEZAAIZAAgKiB2tDACLAgAZAAgKiB2tDACLAgAAAA==.',
Bu='Bubbix:BAABNQAECoEXAAIDAAYKcBKHnACbAQADAAYKcBKHnACbAQAAAA==.Buddhatime:BAAANQADCgYIBgABNQAECggIEQAOAAAAAA==.Bui:BAABNQAFFIEgAAIIAAcKNCCtAACUAgAIAAcKNCCtAACUAgAAAA==.Buikia:BAABNQAECoEWAAMVAAkKJSM2BAArAwAVAAkKJSM2BAArAwAUAAEKfhsWJAFRAAABNQAFFAcIIAAIADQgAA==.Buikyah:BAAANQAFFAQIBAABNQAFFAcIIAAIADQgAA==.Bunnyhop:BAAANQAECgMIBAAAAA==.Buysfeetpics:BAACNQAFFIEbAAMaAAcKfhQ3CgALAgAaAAYKeRU3CgALAgAbAAEKng7ECgBXAAA1AAQKgSkAAhoACQoCJEMaAGUDABoACQoCJEMaAGUDAAAA.',
['Bâ']='Bânê:BAAANQAECggIEwAAAA==.',
Ca='Calx:BAAANQAECgQIBQABNQAFFAUIDwALAJwUAA==.Camerõn:BAAANQADCgYJBgAAAA==.Cannicus:BAACNQAFFIEXAAIaAAcKiRqTAgCMAgAaAAcKiRqTAgCMAgA1AAQKgSkAAhoACQqrJLIgAE4DABoACQqrJLIgAE4DAAAA.Cantheal:BAAANQAECgUICQAAAA==.Capel:BAAANQADCgIIAgAAAA==.Cardinal:BAAANQAECgYIDAABNQAECggIEQAOAAAAAA==.',
Ce='Celavii:BAABNQAECoEbAAIDAAgKrhhCUwBOAgADAAgKrhhCUwBOAgABNQAECggIHAASAHQdAA==.Celeena:BAAANQAECgYIEQAAAA==.',
Ch='Chakrafool:BAAANQAECgIIAgABNQAFFAcIGAAHAIscAA==.Chamane:BAABNQAECoEWAAIBAAgKWRneNgBcAgABAAgKWRneNgBcAgAAAA==.Chanengtotem:BAAANQADCgcIBwAAAA==.Chappell:BAAANQAECgYIDQAAAA==.Chargeplox:BAAANQAECgcIDAAAAA==.Chii:BAAANQADCgEIAQAAAA==.Chillicheese:BAAANQADCgUIBwAAAA==.Chinnohoho:BAAANQAECggIDgAAAA==.Chinnomojo:BAAANQAECgcIDwAAAA==.',
Ci='Cindermoon:BAAANQAECgIIAwAAAA==.Cinna:BAAANQADCgYIBgAAAA==.',
Cl='Cloudhorn:BAABNQAECoEaAAIcAAgKDxThGwArAgAcAAgKDxThGwArAgAAAA==.',
Cm='Cmi:BAAANQAECggIDQABNQAECggIFgAUALogAA==.',
Co='Colena:BAECNQAFFIEGAAIQAAMKiQosGgDnAAAQAAMKiQosGgDnAAA1AAQKgSkAAhAACQo0GeMuAIwCABAACQo0GeMuAIwCAAAA.Conquest:BAAANQAECgUICQAAAA==.Conzy:BAAANQAECgQIDAAAAA==.Coopsfire:BAAANQAECgQICAAAAA==.Corbulus:BAABNQAECoFAAAIGAAgKnBySTgCBAgAGAAgKnBySTgCBAgAAAA==.',
Cr='Create:BAAANQADCgcIBwABNQAECgQIBQAOAAAAAA==.Crispyarrowz:BAAANQAECgEIAQABNQAECgkJKAAaAMMcAA==.Crispymage:BAABNQAECoEoAAIaAAkKwxxQTQDXAgAaAAkKwxxQTQDXAgAAAA==.Cronus:BAAANQAECgYIEAAAAA==.Crypsis:BAAANQAECgQIBAAAAA==.',
Ct='Ctierwarlock:BAABNQAECoEjAAICAAkKXCOaDwBCAwACAAkKXCOaDwBCAwABNQAFFAcIHQAdALQmAA==.',
Cy='Cyndi:BAAANQAECgMICAAAAA==.Cynxs:BAAANQAECgYIEwABNQAECgkJIwAZAG0cAA==.',
Da='Dahala:BAAANQADCgQIBAABNQAECgkJHQAVAPkdAA==.Dannoh:BAAANQAECgQICgAAAA==.Dannyxie:BAAANQADCgUIBQAAAA==.Darcious:BAABNQAECoEcAAMSAAgKdB0fNwBrAgASAAgKdB0fNwBrAgAGAAIKRAZ5UwFYAAAAAA==.Darkcinders:BAABNQAECoEqAAICAAkKixMsSABcAgACAAkKixMsSABcAgAAAA==.Davayer:BAAANQAECgYJCwAAAA==.Dayao:BAAANQADCgUIBQAAAA==.',
De='Deadjkcocoon:BAAANQADCgMIBAAAAA==.Deadlly:BAABNQAECoEfAAIIAAgKVBpXFQAvAgAIAAgKVBpXFQAvAgAAAA==.Deathbfbirth:BAAANQADCggICAABNQAECgQIBAAOAAAAAA==.Deathdruid:BAAANQAECgIIAwABNQAFFAUICwAMADsdAA==.Deathfire:BAAANQAECgQIBAAAAA==.Deathmage:BAAANQAECgMIAwABNQAFFAUICwAMADsdAA==.Deathmonks:BAAANQAECgEIAQABNQAFFAUICwAMADsdAA==.Deathrocks:BAACNQAFFIELAAMMAAUKOx0cCQBcAQAMAAQKmSEcCQBcAQAeAAEKvwviLwAnAAA1AAQKgSUAAgwACQrJJRAKAFoDAAwACQrJJRAKAFoDAAAA.Deathsdragon:BAAANQABCgEIAQABNQAFFAUICwAMADsdAA==.Deathspriest:BAAANQABCgEIAQABNQAFFAUICwAMADsdAA==.Deathsshaman:BAAANQAECgEIAQABNQAFFAUICwAMADsdAA==.Deathwarlock:BAAANQABCgMIAwABNQAFFAUICwAMADsdAA==.Demöníc:BAAANQAECgcJEQAAAA==.Deplock:BAAANQAECggIEAAAAA==.Destcrypt:BAABNQAECoEYAAIQAAkKSx9BEQApAwAQAAkKSx9BEQApAwABNQAECggIFwAfAN8iAA==.Destinyisall:BAAANQAECgIIAgAAAA==.Destwind:BAABNQAECoEXAAIfAAgK3yIXCAD0AgAfAAgK3yIXCAD0AgAAAA==.',
Di='Dilo:BAAANQADCggIBwAAAA==.Disbelief:BAAANQADCgEIAQAAAA==.Divinfinity:BAABNQAECoEcAAQSAAgKjQkKdgCOAQASAAgKjQkKdgCOAQAIAAYKhhCLLABOAQAGAAIKoQEbiwEpAAAAAA==.',
Do='Doeji:BAABNQAECoEkAAIHAAkK6g/XIgBDAgAHAAkK6g/XIgBDAgAAAA==.Dotdotseckz:BAABNQAECoElAAMEAAcKrhhgMAD7AAACAAUKIhQIrABJAQAEAAMKIhtgMAD7AAAAAA==.',
Dr='Dracdoy:BAAANQAECggIDgABNQAECgkJFQABAHsgAA==.Drackor:BAAANQADCgUIBQAAAA==.Drethalis:BAAANQAECgIIBgAAAA==.Drewstormio:BAAANQAECgUICgAAAA==.Dryene:BAAANQAECgIIAgAAAA==.',
Ds='Dsdh:BAACNQAFFIEXAAINAAcKpRufAQBtAgANAAcKpRufAQBtAgA1AAQKgR0AAg0ACQqfJMcHAE0DAA0ACQqfJMcHAE0DAAAA.',
Du='Dulang:BAABNQAECoEtAAIDAAkKgiAsFgArAwADAAkKgiAsFgArAwAAAA==.Dunfreezeyou:BAAANQAECgEIBAAAAA==.Dunprayliao:BAAANQAECgMIAwAAAA==.Dunsmiteyou:BAAANQAECgQIBQAAAA==.Duskbane:BAAANQAECggICAABNQAECggIEAAOAAAAAA==.',
Ea='Eattherich:BAAANQAECgcIEwAAAA==.',
Eb='Eb:BAAANQAECgMIBwABNQAFFAcIGAAHAIscAA==.',
Ec='Ectruby:BAACNQAFFIEJAAIgAAUKBQsQAQCIAQAgAAUKBQsQAQCIAQA1AAQKgTIAAyAACQpRISMFAAgDACAACQpRISMFAAgDAB0AAgpNEUSPAGQAAAAA.',
Eg='Egwene:BAAANQAECgQIBAAAAA==.',
El='Elammental:BAAANQADCgYIBgAAAA==.Elertricsoup:BAAANQAECgIIAgAAAA==.Elwarlocko:BAABNQAECoEaAAQFAAgKuRjkCgCZAQACAAcKPxLwgAC3AQAFAAUKVxrkCgCZAQAEAAIKcRIoUQCAAAAAAA==.Elyndre:BAACNQAFFIEVAAQJAAYKYRo5AwCoAQAJAAUKWBc5AwCoAQAKAAMKoBxTBwD4AAALAAEKhgrPFABNAAA1AAQKgScABAoACQraHQgLAKECAAoACQq6GggLAKECAAkABQqJIBYJAMsBAAsAAwqAHaYwAPEAAAAA.',
Em='Emberis:BAAANQADCgUIBQAAAA==.',
En='Endari:BAAANQAECgUIBQAAAA==.Endlockz:BAABNQAECoEiAAQCAAkK0xPGRwBeAgACAAkK0xPGRwBeAgAFAAIKOwfNIABbAAAEAAIKsQVIYQBXAAAAAA==.',
Er='Erikk:BAACNQAFFIEjAAINAAcKPRTUAQBgAgANAAcKPRTUAQBgAgA1AAQKgSkAAg0ACQpPIgcHAFkDAA0ACQpPIgcHAFkDAAAA.',
Es='Escher:BAAANQADCgYIEQAAAA==.Espresso:BAAANQAECgIIAgABNQAFFAYIIwADAIccAA==.Esprit:BAAANQAECgQIBgAAAA==.',
Ex='Excalibur:BAAANQAECgMIBAAAAA==.',
Ez='Ezrule:BAAANQAECggICAAAAA==.',
Fa='Faeia:BAABNQAECoEiAAIcAAcKEhp4HgAQAgAcAAcKEhp4HgAQAgABNQAFFAYICAABAFEcAA==.Faenirel:BAABNQAECoEkAAIaAAkK2hYCdgB8AgAaAAkK2hYCdgB8AgABNQAECggIFQAZAMQVAA==.Faeya:BAACNQAFFIEIAAIBAAQKURzqFQDKAAABAAQKURzqFQDKAAA1AAQKgSsAAwEACQoOJSkFAI4DAAEACQoOJSkFAI4DABYABwpWF/pUAPgBAAAA.Fairyen:BAAANQAECgUIDgAAAA==.Faithful:BAAANQAECgcIEwAAAA==.Faithless:BAAANQAECgQIBAAAAA==.Famine:BAAANQADCgUIBQABNQAECggIEAAOAAAAAA==.Farapanda:BAAANQADCgYICQAAAA==.Fastcharge:BAABNQAECoEfAAIRAAkKzxvVDQD5AgARAAkKzxvVDQD5AgABNQAFFAUIDQANAFMLAA==.',
Fe='Feidutdut:BAAANQAECgcIEgAAAA==.Feldown:BAAANQAFFAEIAQABNQAFFAUICQAhAKYVAA==.',
Ff='Ffdeathpunch:BAAANQADCgQIBAABNQAECggIGQAZAIgdAA==.Ffen:BAAANQAECgcIDwABNQAECggIFgACAKAZAA==.',
Fi='Fibanocci:BAABNQAECoEgAAIaAAkKoRjTfwBmAgAaAAkKoRjTfwBmAgAAAA==.Fierce:BAABNQAECoEnAAMKAAkK1RKLEAAvAgAKAAkK1RKLEAAvAgAJAAEKAAMxIwAkAAAAAA==.Filthypally:BAAANQADCgQIBgAAAA==.Firaguy:BAAANQAECgUICgAAAA==.Fixated:BAABNQAECoEtAAMCAAgKvAxUdwDSAQACAAgKvAxUdwDSAQAEAAEKbADlgQAZAAAAAA==.',
Fl='Flamerage:BAABNQAECoEUAAIXAAgKURntJQBFAgAXAAgKURntJQBFAgAAAA==.',
Fr='Frankadelic:BAABNQAECoEdAAIhAAcKaBSmKwDKAQAhAAcKaBSmKwDKAQAAAA==.Frieren:BAAANQAECgQICQAAAA==.Frodolol:BAACNQAFFIEfAAMbAAcKpxveAQABAQAaAAYKtRxvCgAJAgAbAAMKBBjeAQABAQA1AAQKgSsAAhoACQprJEgpADQDABoACQprJEgpADQDAAAA.Frostik:BAAANQAECgEIAQAAAA==.Frostyfruit:BAABNQAECoEgAAMaAAgKOhsnfQBsAgAaAAgKhRonfQBsAgAbAAMKUhEDIADHAAAAAA==.',
Fu='Fufamace:BAAANQADCgIIAwAAAA==.Fufina:BAAANQADCgcIDwAAAA==.',
Fw='Fwoopie:BAABNQAECoEhAAMeAAkKwh7NFADwAgAeAAkKwh7NFADwAgAMAAMKoxXTkwC5AAAAAA==.Fwooplin:BAAANQAECgYICQABNQAECgkJIQAeAMIeAA==.',
Ga='Gandea:BAAANQADCgQIBQAAAA==.Gandlefach:BAAANQADCgQIBAAAAA==.Gannina:BAACNQAFFIEGAAIiAAMK9BSmCQDlAAAiAAMK9BSmCQDlAAA1AAQKgSYAAyIACQouHm0NAOoCACIACQouHm0NAOoCACMABAqlCJ8hAKkAAAAA.Garage:BAAANQADCgEIAQAAAA==.',
Gi='Gillemon:BAAANQADCgQIBQAAAA==.Givre:BAAANQAECgUIBQAAAA==.Gizzy:BAABNQAECoEiAAIUAAgKjANryQAvAQAUAAgKjANryQAvAQAAAA==.',
Go='Goodra:BAAANQAECgQIBAABNQAFFAUIDQANAFMLAA==.Goodwill:BAACNQAFFIEJAAMhAAUKphX3CACOAQAhAAUKphX3CACOAQADAAEKrBaRKgBWAAA1AAQKgSoAAyEACQrAJO4HAEYDACEACAp3JO4HAEYDAAMACApwIXo+AIsCAAAA.Gorillaunitt:BAAANQADCgQIBwAAAA==.Gortrek:BAAANQAECgUIBwAAAA==.',
Gr='Graoul:BAAANQAECgQIBwAAAA==.Greybeards:BAAANQADCgcICQAAAA==.Gritt:BAAANQAECgQIBgAAAA==.Gryffin:BAABNQAECoEfAAIRAAgKYherHAA6AgARAAgKYherHAA6AgAAAA==.',
Gu='Gugudan:BAAANQAECgMIBgAAAA==.Gunnina:BAAANQAECgEIAQAAAA==.Gutsc:BAACNQAFFIEJAAIfAAUK7hFOBwC8AAAfAAUK7hFOBwC8AAA1AAQKgSUAAh8ACQrkH68GABEDAB8ACQrkH68GABEDAAAA.Guyhulikatit:BAAANQADCggICAABNQAFFAcIGAAHAIscAA==.Guzzan:BAAANQAECgYIBwAAAA==.',
Ha='Haialorhwa:BAAANQADCgYIDAAAAA==.Hammerboltie:BAAANQAECgIJAQABNQAECgkJIAAaAKEYAA==.Hatewatching:BAAANQAECgcIDwAAAA==.',
He='Healbòt:BAAANQAECgIIAgAAAA==.Hemorrhage:BAABNQAECoEtAAIkAAkKVR3XBQAfAwAkAAkKVR3XBQAfAwAAAA==.Hermighty:BAAANQAECgYIEAABNQAFFAEIAQAOAAAAAA==.Hershéy:BAABNQAECoElAAIcAAgKaSRGBgBMAwAcAAgKaSRGBgBMAwAAAA==.Hert:BAAANQAECggIEQAAAA==.',
Hi='Hiradaira:BAABNQAFFIEUAAMaAAcKZxeYBABWAgAaAAcKWRWYBABWAgAbAAEKhxUgCgBZAAAAAA==.',
Ho='Holasimón:BAAANQAECgQICgAAAA==.Hollyjoel:BAAANQADCgcIBwAAAA==.Hothotseckz:BAAANQAECgEIBAABNQAECgcIJQAEAK4YAA==.',
Hu='Hukk:BAABNQAECoEdAAMVAAkK+R36CACVAgAVAAgKph76CACVAgAUAAIK5xdTCQGTAAAAAA==.Huwuk:BAAANQAECgEIAwABNQAECgkJHQAVAPkdAA==.',
Hy='Hypervoltage:BAAANQADCgMIAwAAAA==.Hypnos:BAABNQAECoEYAAICAAgKqAkkhACuAQACAAgKqAkkhACuAQAAAA==.',
['Hà']='Hà:BAABNQAECoEcAAIaAAkKIxuUUADPAgAaAAkKIxuUUADPAgAAAA==.',
['Há']='Háá:BAAANQAECgMIBAAAAA==.',
Ia='Iamundecided:BAAANQAECgQIBQAAAA==.Iamzzr:BAAANQAECgcICgAAAA==.',
Ic='Icysun:BAABNQAECoEaAAIMAAkKth8fEQAYAwAMAAkKth8fEQAYAwAAAA==.',
Ig='Igneous:BAAANQAECgUICQAAAA==.',
Im='Image:BAAANQAECgcICgABNQAECgQIBQAOAAAAAA==.Imnotamage:BAAANQADCgMIBgAAAA==.Imthebaglady:BAAANQAECggIBAAAAA==.',
Is='Isatarp:BAAANQAECgUIBwABNQAFFAcIIQAEAI0dAA==.Ish:BAAANQAECggIBgAAAA==.Isopod:BAAANQADCgYICAAAAA==.',
Ja='Jabbah:BAAANQAECgIIBAAAAA==.Jackee:BAAANQAECgYIDwABNQAECggIEAAOAAAAAA==.Janlol:BAAANQAECgQIBAAAAA==.Jashy:BAAANQAECgMIAwABNQAFFAUIDwAhAL4fAA==.Jasmean:BAACNQAFFIEPAAMhAAUKvh/SCACRAQAhAAUKcxjSCACRAQADAAIKuCHIFgDNAAA1AAQKgSkAAyEACQrkIhxCABMBACEACArSIhxCABMBAAMAAwpjFa8CAb4AAAAA.',
Je='Jellybeanss:BAABNQAECoEmAAMXAAgK6R08FwDBAgAXAAgK6R08FwDBAgANAAEKqQ3pXAA8AAAAAA==.Jereu:BAAANQADCgcIDQAAAA==.',
Jo='Jobless:BAAANQAECgYIBwAAAA==.Jodix:BAAANQADCggIGQAAAA==.Johnevoker:BAAANQAECgYICgABNQAFFAIIBgABANQKAA==.Johnpaladin:BAAANQAECgYICwABNQAFFAIIBgABANQKAA==.Johnthedeath:BAAANQAECggIBQABNQAFFAIIBgABANQKAA==.Johnthemonk:BAAANQAECgYIDAABNQAFFAIIBgABANQKAA==.Jojobao:BAAANQAECgEJAQAAAA==.Jombii:BAAANQAECgcIDwABNQAFFAUIEAAHAEsVAA==.Jordoom:BAAANQAECgYIDAAAAA==.',
Ju='Judicas:BAAANQAECgIIAwAAAA==.',
['Jë']='Jëwjuice:BAAANQABCgQIBAAAAA==.',
Ka='Kafra:BAAANQAECgYIBAABNQAFFAEIAQAOAAAAAA==.Kafrial:BAAANQAECggIDwABNQAFFAEIAQAOAAAAAA==.Kamazi:BAABNQAECoETAAIJAAgK6ReKBwAJAgAJAAgK6ReKBwAJAgAAAA==.Kannina:BAAANQAECgEIAQAAAA==.Kariiyon:BAAANQAECgMICAAAAA==.Katalen:BAAANQADCgQIBQAAAA==.Kate:BAAANQAECgEIAQAAAA==.Kayaballs:BAAANQAECgIIAgAAAA==.Kayapau:BAACNQAFFIERAAMWAAUK9As9EAAsAQAWAAQKuQs9EAAsAQABAAMKiwSjFgC+AAA1AAQKgSEAAxYACQomHe4kANICABYACQomHe4kANICABkABAojCw4lAM8AAAAA.',
Ke='Kevd:BAAANQAECgYICgABNQAFFAYIGAABAA0eAA==.Kevin:BAACNQAFFIEYAAIBAAYKDR4uAwBAAgABAAYKDR4uAwBAAgA1AAQKgSMAAgEACQpjJf0EAJADAAEACQpjJf0EAJADAAAA.Kevp:BAAANQAECgYIBgABNQAFFAYIGAABAA0eAA==.',
Kh='Khaii:BAACNQAFFIEPAAMaAAUKqhs2DwDZAQAaAAUKmhg2DwDZAQAbAAIK1w1MBgCZAAA1AAQKgTIAAxsACQqqJdcNAKMBABoACQpYJbB6AHECABsABQo0JNcNAKMBAAAA.',
Ki='Kidevil:BAAANQAECgUIEAAAAA==.Kimmiereed:BAABNQAECoEsAAQFAAgKlh0yBQBQAgAFAAcKeB8yBQBQAgACAAUKkxMXqABTAQAEAAEKKwgcdwAwAAAAAA==.Kinslayer:BAAANQADCgMIAwAAAA==.',
Ko='Kodette:BAAANQAECgQIBAAAAA==.Komai:BAACNQAFFIEGAAIBAAMKlSDcDwAgAQABAAMKlSDcDwAgAQA1AAQKgSkAAwEACQp1InQIAGwDAAEACQp1InQIAGwDABYABgpTHelaAOMBAAAA.Kopikia:BAABNQAECoEiAAMXAAgKnxsRGgCnAgAXAAgKnxsRGgCnAgANAAcKiQoFMwCFAQAAAA==.',
Kr='Krucify:BAAANQAFFAQIBAAAAA==.',
Kt='Ktl:BAAANQAECgcICAABNQAECgkJJQAGAPwjAA==.Ktm:BAAANQAECgMIAwABNQAECgkJJQAGAPwjAA==.Ktx:BAABNQAECoElAAMGAAkK/CNzDQCMAwAGAAkK/CNzDQCMAwASAAEKIgePCAEyAAAAAA==.',
Ku='Kulak:BAAANQADCggICwABNQAECgkJIQADAIERAA==.Kult:BAAANQADCgUIBgAAAA==.',
Ky='Kyall:BAABNQAECoErAAQXAAkK6hyEGgCiAgAXAAkKyxyEGgCiAgAlAAQK0RiyFgARAQANAAQKehNQRAD6AAAAAA==.Kyalln:BAAANQAECgcICwAAAA==.',
La='Ladiesman:BAAANQAECggIBgAAAA==.Lafret:BAAANQAECgMIAwAAAA==.Lamerzz:BAAANQAECgEIAQAAAA==.Lamzhar:BAAANQAECgQIBQAAAA==.',
Le='Lebronyames:BAAANQAECgYIDwAAAA==.Lelith:BAABNQAECoEaAAMTAAkKVhlOCQDiAQATAAcKuRZOCQDiAQAHAAUKdxlFPwCNAQAAAA==.Lerazar:BAAANQAECgEIAQAAAA==.Lettuce:BAAANQAECggIEQAAAA==.',
Lh='Lhx:BAAANQAECgEIAQABNQAFFAUIDwAaAFoeAA==.',
Li='Light:BAAANQADCggICAAAAA==.Lipskiz:BAAANQAECgQIAwAAAA==.Liquidstorm:BAAANQAECgEIAQABNQAECgkJKQAQACQfAA==.Liquidvoid:BAABNQAECoEpAAMQAAkKJB9eEQAoAwAQAAkKJB9eEQAoAwARAAgKDA2vKAC8AQAAAA==.Littleannie:BAAANQAECgUICAAAAA==.',
Lo='Logbonk:BAAANQAECgUIBQABNQAFFAUIDwACAIcWAA==.Lokk:BAAANQAECgYICQAAAA==.Longfang:BAAANQADCgYIBgAAAA==.Lothrian:BAAANQADCgEIAQAAAA==.',
Lu='Luurch:BAACNQAFFIEPAAMkAAUKPh16BADTAQAkAAUKIhx6BADTAQAHAAEKkiAhFQBgAAA1AAQKgS8AAyQACQqZJPMDAFQDACQACAo6JfMDAFQDAAcABAomH0JIAFsBAAAA.',
Ly='Lynnae:BAAANQAECgUICQABNQAECgkJIQADAIERAA==.Lythillen:BAAANQADCgMIBAAAAA==.Lythium:BAAANQADCgMIAwAAAA==.',
['Lî']='Lîght:BAAANQAECgcIEQABNQAECggIEAAOAAAAAA==.',
Ma='Maceson:BAAANQADCggIDgAAAA==.Maddenz:BAAANQADCgYIBgAAAA==.Magikcreepz:BAAANQAECggIDgAAAA==.Magnamund:BAAANQABCgYIDQAAAA==.Marvik:BAAANQADCgIIAgAAAA==.Masquerapet:BAACNQAFFIEdAAIeAAcKmBa0AgBPAgAeAAcKmBa0AgBPAgA1AAQKgSYAAh4ACQqoHAkdALACAB4ACQqoHAkdALACAAAA.Mavqt:BAABNQAECoEWAAIUAAgKuiBfRgCeAgAUAAgKuiBfRgCeAgAAAA==.',
Me='Medina:BAAANQAECgUICAAAAA==.Megadeath:BAABNQAECoEoAAIPAAkKkRu7GwCGAgAPAAkKkRu7GwCGAgAAAA==.Mentalas:BAABNQAECoEeAAIDAAgK6ApqdQD3AQADAAgK6ApqdQD3AQAAAA==.Mepuzzible:BAAANQAECgYIBgABNQAFFAMIAwAOAAAAAA==.Meulah:BAAANQAFFAEIAQAAAA==.',
Mi='Miah:BAAANQAECggIEQAAAA==.Miao:BAACNQAFFIEVAAIBAAYKahl/BAAMAgABAAYKahl/BAAMAgA1AAQKgScAAgEACQocJWUDAKUDAAEACQocJWUDAKUDAAAA.Miaomiaomiao:BAACNQAFFIESAAIcAAYKahJUAwDrAQAcAAYKahJUAwDrAQA1AAQKgSgAAhwACQo9IAsJABwDABwACQo9IAsJABwDAAE1AAUUBggVAAEAahkA.Miaomiaorawr:BAACNQAFFIELAAIQAAUKOQuIDgCCAQAQAAUKOQuIDgCCAQA1AAQKgRkAAhAABwoiHu03AGYCABAABwoiHu03AGYCAAE1AAUUBggVAAEAahkA.Minamai:BAABNQAECoEgAAMQAAcK+Q7WdQCBAQAQAAcK+Q7WdQCBAQARAAEK5RQ8aAA9AAABNQAECgkJKgABAJAdAA==.Minaminis:BAAANQAECgYIDwAAAA==.Misdirecting:BAAANQADCgYICgABNQAECgQIBQAOAAAAAA==.',
Mo='Monggoloid:BAAANQADCgMIAwAAAA==.Monsieurstun:BAAANQADCgEIAQAAAA==.Monsta:BAAANQADCgIIAgAAAA==.Moomooda:BAAANQAECgYICQAAAA==.Moongrass:BAAANQAECgUIDAAAAA==.Mousemarâ:BAABNQAECoEfAAMHAAgKkA41LwDvAQAHAAgKkA41LwDvAQAkAAMKuQMpQACIAAAAAA==.',
Mu='Mungomania:BAABNQAECoEbAAIiAAgK4RtDFQCDAgAiAAgK4RtDFQCDAgAAAA==.Mutedz:BAABNQAECoEVAAISAAkKag+9SgAeAgASAAkKag+9SgAeAgAAAA==.',
Na='Nagaridar:BAAANQADCgUIBQAAAA==.Nargorr:BAAANQADCgYIDAAAAA==.',
Ne='Necroraven:BAAANQAECgIIAgAAAA==.Necroticdr:BAABNQAECoEWAAMgAAkKbBYiCgBnAgAgAAkKChQiCgBnAgAmAAEKix6YQwBWAAABNQAFFAQICwAMAPIPAA==.Necroticlol:BAACNQAFFIELAAQMAAQK8g8tEADVAAAMAAMKBwwtEADVAAAPAAIKGhGMDwCbAAAeAAEKqRdUJgBEAAA1AAQKgTAAAwwACQo+JDcOADEDAAwACQo1JDcOADEDAA8ABwqDH74hAFQCAAAA.Necroticlòl:BAABNQAECoEgAAMGAAgKMRYkfAACAgAGAAgKEBUkfAACAgAIAAIKIxj8TgB8AAABNQAFFAQICwAMAPIPAA==.Neeyana:BAAANQADCggIDwAAAA==.Neff:BAABNQAECoEWAAICAAgKoBnaPACBAgACAAgKoBnaPACBAgAAAA==.Neffpally:BAAANQAECgYIBwABNQAECggIFgACAKAZAA==.Nefpore:BAAANQAECgYIEQAAAA==.Nenepok:BAAANQAECgQIAwAAAA==.Nephelem:BAAANQADCgIIAgAAAA==.Nereuss:BAAANQAECgMIAwAAAA==.',
Ni='Niij:BAAANQAECgYIEQAAAA==.Nimon:BAAANQADCgQIBAAAAA==.Nitox:BAAANQAECgMICAAAAA==.',
No='Nocchii:BAAANQAECgMIBAAAAA==.Nolimits:BAAANQAECgYIBgAAAA==.Nopantiesx:BAAANQAECgEIAQAAAA==.Norielia:BAAANQADCgYIDAAAAA==.Noruid:BAAANQAECggIEAAAAA==.Nosivire:BAAANQAECgEIAQAAAA==.Nosok:BAAANQAECgIIBAABNQAECggIEwAOAAAAAA==.Notwiththema:BAABNQAECoEZAAMQAAgKZRQaVQD3AQAQAAgKZRQaVQD3AQAnAAEKgAb0JgAxAAAAAA==.Noughtawolf:BAABNQAECoEmAAIVAAgKuB9RBgDgAgAVAAgKuB9RBgDgAgAAAA==.',
Nt='Nthope:BAAANQAFFAYIGAAAAQ==.',
Nv='Nvictus:BAAANQADCggIDQAAAA==.',
Od='Odîn:BAAANQADCggICgAAAA==.',
On='Onlyfire:BAAANQAECgYIDAAAAA==.Onlylight:BAAANQAECggIAgAAAA==.',
Pa='Padthai:BAAANQAECgIIAgABNQAECgQIBgAOAAAAAA==.Palabean:BAAANQADCgcIEAAAAA==.Pamie:BAAANQAECgUICwABNQAECgkJMQASAFAhAA==.Patsie:BAABNQAECoEXAAIDAAgKuR9ILwC9AgADAAgKuR9ILwC9AgAAAA==.',
Pe='Peach:BAAANQAECggIDwABNQAFFAYIFwAkAG4WAA==.Peeta:BAAANQADCgIIAgAAAA==.Pepperino:BAAANQAECgYIEgAAAA==.Perseph:BAAANQAECggIBwAAAA==.',
Ph='Pharmercy:BAAANQAECgUIBgABNQAFFAcIIQAEAI0dAA==.Phoebe:BAAANQADCgYIBgAAAA==.',
Pi='Piyona:BAAANQAECgcIEAAAAA==.',
Po='Pocketpie:BAAANQABCgYICwAAAA==.Poros:BAAANQADCgYIBgABNQAECgkJMAAMABkiAA==.Porosdk:BAABNQAECoEwAAIMAAkKGSIEEAAiAwAMAAkKGSIEEAAiAwAAAA==.Poteb:BAAANQADCgUIBwAAAA==.Powerangers:BAAANQAECgUICQAAAA==.',
Pr='Prevailor:BAAANQADCgUIAgAAAA==.Prodigal:BAACNQAFFIEKAAIlAAUKqwlVAgDlAAAlAAUKqwlVAgDlAAA1AAQKgSIAAiUACQrsE/QMAMIBACUACQrsE/QMAMIBAAAA.',
Pt='Pterion:BAAANQAFFAIIAwAAAA==.',
Pu='Pumba:BAAANQADCggICAAAAA==.Pumbz:BAABNQAECoEcAAMDAAgK7CAfcwD8AQADAAUKBiMfcwD8AQAhAAQK2h0IOQBZAQAAAA==.Punprepared:BAEBNQAECoEiAAMNAAgKYSZrBACHAwANAAgKYSZrBACHAwAlAAEKjBD5KABBAAAAAA==.',
Qe='Qeb:BAACNQAFFIEYAAIHAAcKixyTAADIAgAHAAcKixyTAADIAgA1AAQKgSgAAwcACQoiJOkGAE8DAAcACQoiJOkGAE8DACQABQouEV4vACYBAAAA.Qezam:BAAANQAECgUIBQAAAA==.',
Qi='Qio:BAAANQADCgIIAgAAAA==.Qisz:BAABNQAECoEgAAITAAgKthaeBgBKAgATAAgKthaeBgBKAgAAAA==.',
['Qí']='Qíqi:BAABNQAECoEvAAIRAAkKMhfmFQCMAgARAAkKMhfmFQCMAgAAAA==.',
Ra='Raincy:BAAANQADCgEIAQAAAA==.Rainrain:BAAANQAECgQIBQABNQAFFAUIDwAaAFoeAA==.Rashes:BAAANQAECgcIDgAAAA==.Rashika:BAAANQAECgcIBgABNQAFFAEIAQAOAAAAAA==.Rashypoopy:BAAANQAECgEIAQAAAA==.Ratix:BAAANQAECgIIAgAAAA==.Ravenn:BAAANQAECgQJBQABNQAECgUICgAOAAAAAA==.Razoxaynne:BAAANQAECgQIBQAAAA==.',
Re='Resolute:BAAANQAECgMIBQAAAA==.Restinpieces:BAAANQAECggICgAAAA==.Reverb:BAAANQABCgUIAwABNQAECggILQACALwMAA==.Reverencia:BAAANQAECgEIAwAAAA==.Revnger:BAAANQADCggIEAAAAA==.',
Rh='Rhyker:BAAANQAECgcIDQAAAA==.',
Ri='Riinegan:BAAANQAECgQIBAAAAA==.Rimreaper:BAAANQAECgYIEAAAAA==.Rinnegan:BAAANQAECgQIBgAAAA==.',
Ro='Rolypollie:BAAANQAECgEIAgAAAA==.Ronniepaws:BAAANQADCgIIAQABNQAECggIAgAOAAAAAA==.Rorak:BAAANQADCgQICAABNQAECgkJLgAUAJsUAA==.Roughlly:BAAANQADCggICAAAAA==.',
Ru='Rubmytotem:BAAANQAECgQIBAAAAA==.Ruptured:BAABNQAECoE4AAIHAAgKyyQJCQAwAwAHAAgKyyQJCQAwAwAAAA==.',
Ry='Ryndra:BAAANQAECgEIAQAAAA==.',
['Rä']='Räzoxane:BAAANQADCgIIAgAAAA==.',
['Rï']='Rïsing:BAAANQADCgYIBgAAAA==.',
Sa='Salamifreak:BAAANQAECggIEAAAAA==.Satria:BAAANQADCggJDwAAAA==.Saveth:BAAANQAECgMJAwABNQAECgUICwAOAAAAAA==.',
Sc='Scamdawg:BAAANQADCggIFQAAAA==.Screamin:BAAANQADCgEIAQAAAA==.Scumdawg:BAAANQAECgIIAgAAAA==.',
Se='Senyorita:BAAANQAECgMIAwAAAA==.',
Sh='Shadesong:BAAANQAECgIJAwAAAA==.Shadowboiz:BAACNQAFFIEGAAQFAAMKECI6AgDMAAAFAAIK9CE6AgDMAAACAAIKEB2jIgCwAAAEAAEKSCKTEQBoAAA1AAQKgSgAAwIACQoqJosBAN4DAAIACQoqJosBAN4DAAQAAgrWFlNJAJkAAAAA.Shadowlesz:BAAANQAECggICwAAAA==.Shamdoy:BAABNQAECoEVAAMBAAkKeyAeFAASAwABAAgKwSIeFAASAwAWAAUKPCJ/YwDGAQAAAA==.Shampagne:BAABNQAECoEbAAIBAAgKBhCwZgCpAQABAAgKBhCwZgCpAQABNQAECggILQACALwMAA==.Shapeshiift:BAAANQADCgYIBgAAAA==.Shidann:BAACNQAFFIEdAAMdAAcKtCaLAAAVAwAdAAcKtCaLAAAVAwAmAAYKhhExAQCwAQA1AAQKgSYAAx0ACQr6JqMAAPkDAB0ACQr6JqMAAPkDACYAAwqJI6oiADsBAAAA.Shiifty:BAAANQADCgIIBAAAAA==.Shintopal:BAABNQAECoEcAAIGAAgK5BVbcwAZAgAGAAgK5BVbcwAZAgAAAA==.Shintoslash:BAAANQAECgUICgAAAA==.Shopgirl:BAAANQADCgYIBgAAAA==.',
Si='Siewteng:BAAANQAECgIIAgAAAA==.Silentsnipe:BAAANQADCggICAAAAA==.Silverdeath:BAABNQAECoEXAAIPAAgKlg6aOQCsAQAPAAgKlg6aOQCsAQAAAA==.Silvermaiden:BAAANQABCgIIAgAAAA==.Sinorph:BAACNQAFFIEGAAIlAAMKJhAZAwCuAAAlAAMKJhAZAwCuAAA1AAQKgSkAAiUACQo4HL8EAMkCACUACQo4HL8EAMkCAAAA.',
Sl='Slappuccino:BAABNQAECoEgAAIfAAgKEiC3CADoAgAfAAgKEiC3CADoAgAAAA==.Sleeptime:BAAANQAECggIEQAAAA==.',
Sn='Sneakyitch:BAAANQAECgcIEQAAAA==.Snipez:BAAANQAECgEIAQABNQAFFAUICgABAL0bAA==.Snowflake:BAAANQAECgUICAAAAA==.',
So='Soggybiscuit:BAAANQAECgEIAQAAAA==.Soil:BAACNQAFFIEPAAILAAUKnBSiCACHAQALAAUKnBSiCACHAQA1AAQKgS0AAwsACQrGGTcQAJMCAAsACQrGGTcQAJMCAAoACAqNCbEZAJABAAAA.Solanaz:BAAANQAECgQIDQAAAA==.Somedruid:BAAANQAECgQIBQABNQAECggIFQAZAMQVAA==.Somepally:BAABNQAECoEXAAMIAAkKFBPjFwAQAgAIAAkKFBPjFwAQAgAGAAQKNwvAFAHFAAABNQAECggIFQAZAMQVAA==.Songfíre:BAAANQAECgUICwAAAA==.Sorahal:BAAANQADCgEIAQAAAA==.',
Sp='Spagalnero:BAAANQAECgEJAQAAAA==.Spinnywinny:BAAANQAECgEIAQAAAA==.',
St='Stampedê:BAAANQAECgQIBAAAAA==.Stan:BAACNQAFFIEUAAMDAAUK5yEoBAD5AQADAAUK5yEoBAD5AQAhAAMKLRCEFADDAAA1AAQKgTEAAwMACQr9JKEPAFMDAAMACAoUJqEPAFMDACEACArpHI8gACwCAAAA.Stanstanstan:BAABNQAECoEXAAIZAAgKXR+/BwDxAgAZAAgKXR+/BwDxAgABNQAFFAUIFAADAOchAA==.Starleet:BAAANQAECgQIBQAAAA==.Stier:BAAANQAECgQICAABNQAECgQIBQAOAAAAAA==.Stiggyy:BAAANQAECggIEwAAAA==.Stiria:BAAANQAECgQIBwAAAA==.Stormscythe:BAAANQAECgMICAAAAA==.',
Su='Supercleave:BAAANQAECgQIDQAAAA==.Superdope:BAAANQAECgQIDAAAAA==.Superfly:BAABNQAECoEaAAIRAAgKjxNiIwDwAQARAAgKjxNiIwDwAQAAAA==.Supermayhem:BAAANQADCgQJBQAAAA==.Suspense:BAAANQABCgYICAAAAA==.Sutiao:BAACNQAFFIELAAIaAAUKUxifFQCiAQAaAAUKUxifFQCiAQA1AAQKgSoAAhoACQpSJJUVAHYDABoACQpSJJUVAHYDAAAA.',
Sw='Swissarmy:BAAANQAECgYICQAAAA==.Switchknife:BAABNQAECoEhAAMHAAgKsyK9CwAQAwAHAAgKUiK9CwAQAwAkAAQK5R1hKgBWAQAAAA==.',
Sy='Sylasiana:BAAANQAECgEIAQAAAA==.Synasta:BAACNQAFFIEOAAMCAAYKXBwABwDPAQACAAUK1xwABwDPAQAEAAIKcBEZDQCeAAA1AAQKgTIABAQACQqZJLUGAJUCAAIACAoFJOsSAC4DAAQABwqJILUGAJUCAAUAAgqaIXwWALsAAAAA.Syrent:BAAANQAECgQICAAAAA==.Systematic:BAAANQADCgMIAwAAAA==.',
Ta='Taano:BAAANQADCgUICwAAAA==.Tallia:BAAANQAECgUIDQABNQAECgkJLQAaAE0eAA==.Talons:BAABNQAECoEXAAILAAgK2xiCEgBvAgALAAgK2xiCEgBvAgAAAA==.Tamed:BAAANQAECgUICwAAAA==.Tancs:BAAANQAECgcIDgAAAA==.Tandem:BAAANQAECgUIBQAAAA==.Tarocakes:BAABNQAECoEaAAMJAAkKkgl2DwAaAQAJAAcKSgh2DwAaAQALAAgKlwBVQwBZAAAAAA==.Taurium:BAABNQAECoEoAAMGAAkKBRdUXABZAgAGAAkKBRdUXABZAgASAAcKRhBbcgCZAQAAAA==.',
Te='Teaki:BAABNQAECoE4AAIaAAkKrw99lwA0AgAaAAkKrw99lwA0AgAAAA==.Telsh:BAABNQAECoEdAAIDAAkKdhxRHgADAwADAAkKdhxRHgADAwABNQAFFAEIAQAOAAAAAA==.Temperance:BAAANQAECgMIBAABNQAECgkJJwABAFMbAA==.Temsik:BAABNQAECoErAAIDAAkK2SF6DABpAwADAAkK2SF6DABpAwAAAA==.Temsikdab:BAAANQAECgIIAgAAAA==.',
Th='Thaedre:BAAANQAECgEIAQAAAA==.Thewaterboy:BAAANQAECgEIAQAAAA==.Thoth:BAACNQAFFIEIAAQCAAUK9Q+uGwDoAAACAAQK2BGuGwDoAAAEAAIKAgNVEQBrAAAFAAEKaQgAAAAAAAA1AAQKgSYABAIACQoIHYdwAOUBAAIABgq6HIdwAOUBAAQAAwq5FWU6AM0AAAUAAgr/GigZAJwAAAE1AAQKBggQAA4AAAAA.Thrallish:BAAANQAECgMIBAAAAA==.Thrux:BAAANQAECgcIEwAAAA==.Thura:BAAANQAECgEIAQAAAA==.',
Ti='Tidal:BAAANQAECggIDwABNQAECggIEAAOAAAAAA==.Tiddlyniblit:BAAANQAECgUICAAAAA==.Tigbugha:BAAANQADCgYIEgAAAA==.',
To='Tommyh:BAACNQAFFIEeAAIRAAcKNSAJAQCmAgARAAcKNSAJAQCmAgA1AAQKgSkAAhEACQpeJVQEAIcDABEACQpeJVQEAIcDAAAA.Topuzzible:BAAANQAECgUIBAABNQAFFAMIAwAOAAAAAA==.Torress:BAAANQAECgYIEwAAAA==.Totemistyk:BAAANQAECggJDQAAAA==.Toufz:BAABNQAECoEsAAMhAAkKch3iIAAoAgAhAAgKOxniIAAoAgADAAUKZCGYhADSAQAAAA==.',
Tr='Trianth:BAABNQAECoEpAAIGAAcKKx6UYgBGAgAGAAcKKx6UYgBGAgAAAA==.Tribbie:BAABNQAECoEbAAQMAAkKwx6cNAAzAgAMAAgKCSCcNAAzAgAPAAEKlBTtjgA8AAAeAAEKgRG7vAAwAAAAAA==.Tribbier:BAACNQAFFIEQAAMHAAUKNAzxBQCLAQAHAAUKNAzxBQCLAQAkAAIKFAGaDgB8AAA1AAQKgRgAAwcACQpNGH8ZAIgCAAcACQpNGH8ZAIgCACQAAQoQD5RIAEAAAAE1AAQKCQkbAAwAwx4A.Truepower:BAAANQAECgIIAgAAAA==.',
Tw='Twidger:BAAANQAECgYIDQAAAA==.',
Ty='Tyranadia:BAABNQAECoEoAAIMAAkKeBk9LgBWAgAMAAkKeBk9LgBWAgAAAA==.Tystus:BAAANQAECgQIBgAAAA==.',
Um='Um:BAAANQAECgEIAQAAAA==.',
Up='Upstairs:BAACNQAFFIEGAAIBAAIK1Ap3HQCNAAABAAIK1Ap3HQCNAAA1AAQKgSIAAgEACQraGNI1AGECAAEACQraGNI1AGECAAAA.',
Ur='Uruga:BAAANQAECgEIAQAAAA==.',
Uz='Uzryn:BAAANQAECgcIDAAAAA==.',
Va='Varnoxx:BAACNQAFFIEPAAMMAAUKFRw9CgBFAQAMAAQKDRs9CgBFAQAeAAEKNiB1IgBcAAA1AAQKgTMAAwwACQqIJLsdALwCAAwACQqIJLsdALwCAB4AAQrWJfChAG0AAAAA.',
Vi='Vicioûs:BAAANQAECgUJCwAAAA==.Vinkwink:BAAANQADCgYIBgAAAA==.Vinwink:BAAANQAECgEIAgAAAA==.Vishnar:BAACNQAFFIELAAICAAUKHAVuDwBYAQACAAUKHAVuDwBYAQA1AAQKgR8AAgIACAoDGfBPAEQCAAIACAoDGfBPAEQCAAAA.',
Vo='Vollic:BAAANQADCggICAAAAA==.',
Vv='Vvoo:BAAANQAECgQICgAAAA==.',
Vy='Vyndish:BAAANQAECgQIBAAAAA==.',
Wa='Wander:BAAANQAECgUIEwAAAA==.Wardz:BAAANQADCgYICwAAAA==.Watever:BAAANQAECggIEgAAAA==.Wavedash:BAAANQAECgYIEQAAAA==.Wazaldin:BAAANQAECgEJAQAAAA==.',
We='Wendell:BAAANQADCggIEgAAAA==.Wetpantees:BAAANQAECgEIAQAAAA==.',
Wh='Whispess:BAAANQAECgMICAAAAA==.',
Wi='Winnievoid:BAAANQAECgcJDgAAAA==.',
Wo='Woodro:BAABNQAECoEZAAISAAkKqBBUSgAfAgASAAkKqBBUSgAfAgAAAA==.Woz:BAAANQAECgQIBAABNQAECgYIBwAOAAAAAA==.',
Xa='Xahara:BAAANQADCggICAAAAA==.',
Xl='Xln:BAAANQAECgQIEAABNQAECgkJKgABAJAdAA==.',
Xt='Xtion:BAACNQAFFIEPAAMhAAUK9hrZDABGAQAhAAQKCxrZDABGAQADAAEKpB4VKQBaAAA1AAQKgTIAAyEACQqNJVwMAAUDACEACQqoJFwMAAUDAAMAAgrTIYoGAbIAAAAA.',
Ya='Yagnatia:BAAANQAECgUIDAAAAA==.',
Yo='Yongbok:BAAANQAECgMIBwAAAA==.',
Yr='Yrano:BAAANQAECgYJCwAAAA==.',
Za='Zae:BAAANQADCgEIAQAAAA==.Zapu:BAAANQADCgUIBQAAAA==.Zaraxes:BAAANQAECgUIBgAAAA==.',
Ze='Zeladine:BAAANQABCggIEgAAAA==.Zelgaira:BAACNQAFFIEOAAIMAAUKeyHkAgD1AQAMAAUKeyHkAgD1AQA1AAQKgR8AAgwACQqeIc0bAMkCAAwACQqeIc0bAMkCAAE1AAUUBggOAAIAXBwA.Zelind:BAAANQAECgYICQABNQAECggINQARADoIAA==.Zelvaris:BAACNQAFFIESAAITAAcKViIhAACcAgATAAcKViIhAACcAgA1AAQKgUAAAhMACQr5JUsAANsDABMACQr5JUsAANsDAAAA.Zenõ:BAABNQAECoEbAAISAAkKeRgJKwCiAgASAAkKeRgJKwCiAgAAAA==.Zerine:BAAANQAECgQIBwAAAA==.Zerkerman:BAAANQADCgcIBwAAAA==.Zeño:BAAANQAECgIIAgABNQAECgkJGwASAHkYAA==.',
Zi='Zipp:BAAANQABCgQIBAABNQAFFAQIAQAOAAAAAA==.Zipps:BAAANQAECgQIAgABNQAFFAQIAQAOAAAAAA==.Zips:BAAANQAFFAQIAQAAAA==.Zirka:BAABNQAECoEtAAIaAAkKTR7KNgAOAwAaAAkKTR7KNgAOAwAAAA==.Zivayhr:BAAANQADCgEIAQAAAA==.',
Zu='Zucchini:BAAANQADCgYICAAAAA==.',
Zy='Zylexo:BAAANQABCggIGAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
