local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Evoker-Preservation','Shaman-Restoration','Warlock-Demonology','Warlock-Destruction','Paladin-Retribution','DeathKnight-Blood','Unknown-Unknown','Warrior-Arms','Priest-Holy','Druid-Balance','Mage-Frost','Monk-Windwalker','DeathKnight-Frost','Druid-Restoration','Warlock-Affliction','Priest-Shadow','Paladin-Holy','Evoker-Augmentation','Mage-Arcane','Monk-Brewmaster','Rogue-Subtlety','Rogue-Assassination','Hunter-BeastMastery','Evoker-Devastation','DeathKnight-Unholy','Paladin-Protection','Shaman-Elemental','Warrior-Fury','Warrior-Protection','Monk-Mistweaver','Hunter-Survival','Hunter-Marksmanship','Druid-Guardian','Druid-Feral','Priest-Discipline','DemonHunter-Havoc','Mage-Fire','DemonHunter-Devourer',}
local provider = {region='US',realm='Sargeras',name='US',type='subscribers',zone=53,date='2026-09-29',data={Ab='Abeblinkìn:BAEANQAECggICgAAAA==.',
Ad='Aderak:BAEBNQAECoEYAAIBAAgKQRD1GgDWAQiODQAABQA5AHUNAAADADMAfw0AAAMAJgCpDQAABAArAFwNAAACADIAXQ0AAAIAJQBlDQAAAQASADMNAAAEACMAAQAICkEQ9RoA1gEIjg0AAAUAOQB1DQAAAwAzAH8NAAADACYAqQ0AAAQAKwBcDQAAAgAyAF0NAAACACUAZQ0AAAEAEgAzDQAABAAjAAAA.Adventures:BAEBNQAECoEaAAICAAkKRyPICgBJAwmODQAABABbAHUNAAADAF4Afw0AAAMAWgCpDQAAAgBZAFwNAAACAFkAXQ0AAAIATwBlDQAABABTAKQNAAACAF8AMw0AAAQAYwACAAkKRyPICgBJAwmODQAABABbAHUNAAADAF4Afw0AAAMAWgCpDQAAAgBZAFwNAAACAFkAXQ0AAAIATwBlDQAABABTAKQNAAACAF8AMw0AAAQAYwAAAA==.Advntr:BAEANQAECgYIDQABNQAECgkJGgACAEcjAA==.',
Ai='Aiferian:BAEANQADCgEIAQABNQAFFAQIBwACANQPAA==.',
Ak='Akand:BAECNQAFFIEFAAMDAAIKfhLzJwBqAAKODQAABABZAKkNAAABAAQAAwABChoj8ycAagABjg0AAAQAWQAEAAEK4wEAAAAAAAGpDQAAAQAEADUABAqBIQADAwAJCogjyQ4AMwMAAwAICtgjyQ4AMwMABAAECrgawiQAOAEAAAA=.',
Al='Alarius:BAECNQAFFIEPAAIFAAUKzBy5AwDlAQWODQAABABYAHUNAAACAD0Afw0AAAIAHwCpDQAABABcADMNAAADAF4ABQAFCswcuQMA5QEFjg0AAAQAWAB1DQAAAgA9AH8NAAACAB8AqQ0AAAQAXAAzDQAAAwBeADUABAqBJgACBQAJCrwkchcAQgMABQAJCrwkchcAQgMAAAA=.',
An='Ankleshankèr:BAEANQAECgEIAQABNQAFFAUICQAGACAdAA==.Antho:BAEANQAECggICQAAAA==.Anthodk:BAEANQADCgIIAgABNQAECggICQAHAAAAAA==.',
Ar='Archimtiros:BAECNQAFFIESAAIIAAcKWiHEAQCmAgeODQAAAgBfAHUNAAADAFgAfw0AAAIAWACpDQAABABgAFwNAAACAFAAXQ0AAAIAQwAzDQAAAwBRAAgABwpaIcQBAKYCB44NAAACAF8AdQ0AAAMAWAB/DQAAAgBYAKkNAAAEAGAAXA0AAAIAUABdDQAAAgBDADMNAAADAFEANQAECoEhAAIIAAkKbyYhCACjAwAIAAkKbyYhCACjAwAAAA==.',
As='Aspirational:BAEANQAECgYIDgAAAA==.',
Au='Auratic:BAEANQAECgEIAQABNQAFFAYIEgAJAIAjAA==.',
Aw='Awesumpawsum:BAEANQADCgcJCwABNQAECgkJLQAKAO0VAA==.',
Be='Beccastarr:BAEBNQAECoEhAAILAAkKmRqxBACXAgmODQAABgBQAHUNAAADADUAfw0AAAQAVwCpDQAABAA/AFwNAAACAEEAXQ0AAAIARQBlDQAABAA+AKQNAAADACQAMw0AAAUAXAALAAkKmRqxBACXAgmODQAABgBQAHUNAAADADUAfw0AAAQAVwCpDQAABAA/AFwNAAACAEEAXQ0AAAIARQBlDQAABAA+AKQNAAADACQAMw0AAAUAXAAAAA==.Bestdead:BAEANQAECgQIBAABNQAFFAQICQAMAMwOAA==.',
Bi='Bidussybean:BAECNQAFFIEGAAINAAMKpwrACQDWAAOODQAAAwANAHUNAAABABEAqQ0AAAIAMgANAAMKpwrACQDWAAOODQAAAwANAHUNAAABABEAqQ0AAAIAMgA1AAQKgSIAAg0ACQpgIP4PANcCAA0ACQpgIP4PANcCAAAA.Bigmoos:BAECNQAFFIEQAAIOAAUKNyEMAgD6AQWODQAABABfAHUNAAADAD4Afw0AAAIAYACpDQAABABTADMNAAADAFcADgAFCjchDAIA+gEFjg0AAAQAXwB1DQAAAwA+AH8NAAACAGAAqQ0AAAQAUwAzDQAAAwBXADUABAqBIAADDgAJCoci1gYALgMADgAJCoci1gYALgMACgABCmMYHosARQAAAAA=.Bigpptotem:BAEANQAECgYIDQAAAA==.Bigsax:BAEANQAECgEIAQABNQAFFAUIEAAOADchAA==.Biörnjr:BAEANQAECgcICgABNQAFFAYIEAAFAKMXAA==.',
Bj='Bjornsr:BAECNQAFFIEQAAIFAAYKoxc+AgAeAgaODQAAAgBWAHUNAAACACgAfw0AAAMAUACpDQAABAA4AFwNAAABABoAMw0AAAQARwAFAAYKoxc+AgAeAgaODQAAAgBWAHUNAAACACgAfw0AAAMAUACpDQAABAA4AFwNAAABABoAMw0AAAQARwA1AAQKgSgAAgUACQrPI18KAJMDAAUACQrPI18KAJMDAAAA.',
Bl='Blizidan:BAEANQADCggICQABNQAFFAUIEAAEAAoOAA==.Blizinator:BAECNQAFFIEQAAQEAAUKCg48DQCaAAWODQAABABDAHUNAAADABMAfw0AAAIAJQCpDQAABAATADMNAAADACQAAwACCoEUzx8AnwACjg0AAAQAQwB/DQAAAgAlAAQAAgqGBzwNAJoAAnUNAAADABMAqQ0AAAQAEwAPAAEKIw5sCgBJAAEzDQAAAwAkADUABAqBGwADBAAJClAiHBQAwgEAAwAHCg4iDDoAaAIABAAGCjMaHBQAwgEAAAA=.Blizishout:BAEANQAECgQIBQABNQAFFAUIEAAEAAoOAA==.',
Bo='Boidotatchi:BAEANQAECgEIAQABNQAFFAYIEgACAGUgAA==.Bokkiepi:BAECNQAFFIEhAAIQAAcKySFzAADNAgeODQAABQBiAHUNAAAFAGEAfw0AAAUANACpDQAABQBiAFwNAAAEAGAAXQ0AAAQAUgAzDQAABQBQABAABwrJIXMAAM0CB44NAAAFAGIAdQ0AAAUAYQB/DQAABQA0AKkNAAAFAGIAXA0AAAQAYABdDQAABABSADMNAAAFAFAANQAECoEgAAMQAAkKPibOAQC7AwAQAAkKPibOAQC7AwAJAAEKchUfwgBEAAAAAA==.Bokkievoker:BAEANQAECgYIBgABNQAFFAcIIQAQAMkhAA==.Boldion:BAEBNQAECoEkAAMFAAgKYCbRDwBuAwiODQAABQBjAHUNAAAGAGAAfw0AAAYAYgCpDQAABgBjAFwNAAAEAGIAXQ0AAAMAYwBlDQAABABgADMNAAACAGIABQAICmAm0Q8AbgMIjg0AAAUAYwB1DQAABQBgAH8NAAAFAGIAqQ0AAAUAYwBcDQAABABiAF0NAAADAGMAZQ0AAAQAYAAzDQAAAgBiABEAAwpaH2KSABMBA3UNAAABAD4Afw0AAAEAYACpDQAAAQBSAAE1AAUUAggFAAMAfhIA.Borban:BAECNQAFFIERAAIDAAcKMxXtAQAzAgeODQAABQBIAHUNAAAEAFAAfw0AAAIAQQCpDQAAAgAbAFwNAAABAAAAXQ0AAAEANAAzDQAAAgBQAAMABwozFe0BADMCB44NAAAFAEgAdQ0AAAQAUAB/DQAAAgBBAKkNAAACABsAXA0AAAEAAABdDQAAAQA0ADMNAAACAFAANQAECoEeAAMDAAkK/yRXCQBdAwADAAkK/yRXCQBdAwAEAAIK3Rs6QgCmAAAAAA==.',
Bu='Bubleohseven:BAEBNQAECoEXAAIFAAcKjx1BUABUAgeODQAABQBOAHUNAAAEAFIAfw0AAAQATwCpDQAABABPAFwNAAADAFUAXQ0AAAIAWQBlDQAAAQAjAAUABwqPHUFQAFQCB44NAAAFAE4AdQ0AAAQAUgB/DQAABABPAKkNAAAEAE8AXA0AAAMAVQBdDQAAAgBZAGUNAAABACMAAAA=.Budlitelime:BAEANQAECggICgABNQAFFAYIDgASAGkWAA==.',
Ca='Caraxxys:BAEBNQAECoE7AAITAAkKQx+AJAA2AwmODQAACgBbAHUNAAAHAFsAfw0AAAgAYQCpDQAACwBYAFwNAAAHAFgAXQ0AAAQAUABlDQAABAA9AKQNAAACACAAMw0AAAYAVwATAAkKQx+AJAA2AwmODQAACgBbAHUNAAAHAFsAfw0AAAgAYQCpDQAACwBYAFwNAAAHAFgAXQ0AAAQAUABlDQAABAA9AKQNAAACACAAMw0AAAYAVwAAAA==.Castn:BAEANQAECgcIEwABNQAECggIGwAIAAYkAA==.',
Ch='Challsy:BAEANQAECgQIBgABNQAFFAUICwAIABIMAA==.Chancelbrew:BAEANQAECgYIEAAAAA==.Chaotixbolt:BAECNQAFFIEdAAMDAAcKFSMzAQBgAgeODQAABQBhAHUNAAAFAGIAfw0AAAUASQCpDQAABQBjAFwNAAAEAFsAXQ0AAAMARwAzDQAAAgBhAAMABgqEIjMBAGACBo4NAAAFAGEAfw0AAAUASQCpDQAAAwBjAFwNAAAEAFsAXQ0AAAMARwAzDQAAAgBhAAQAAgpTIrcEAMYAAnUNAAAFAGIAqQ0AAAIATQA1AAQKgSEABAQACQrGJkcCAC0DAAQACAqmIkcCAC0DAAMABwpPJnsXAP0CAA8AAQr5JooZAHYAAAE1AAQKBwgRAAcAAAAA.Chaotixdh:BAEANQAECgYIDAABNQAECgcIEQAHAAAAAA==.Chyrus:BAEBNQAECoEXAAIIAAkKfCJxDACCAwmODQAABABiAHUNAAADAFkAfw0AAAMAUgCpDQAAAwBaAFwNAAACAGMAXQ0AAAEAQABlDQAAAwBaAKQNAAABAFMAMw0AAAMAXwAIAAkKfCJxDACCAwmODQAABABiAHUNAAADAFkAfw0AAAMAUgCpDQAAAwBaAFwNAAACAGMAXQ0AAAEAQABlDQAAAwBaAKQNAAABAFMAMw0AAAMAXwABNQAFFAIIBQAGAPsfAA==.',
Ci='Ciaoticks:BAEANQAECgcIEQAAAA==.',
Cl='Clawañdorder:BAEANQAECgUIBQABNQAECgcIFwAFAI8dAA==.',
Co='Coleblast:BAEANQAECgMIAgAAAA==.',
Cu='Cuddi:BAEANQAECgIIAgAAAA==.',
Da='Dalailarma:BAEBNQAECoEaAAMMAAgKzRjdFwA3AgiODQAABAA5AHUNAAAEAFAAfw0AAAMALwCpDQAABABMAFwNAAADAEYAXQ0AAAIAOwBlDQAAAgAwADMNAAAEAEUADAAICs0Y3RcANwIIjg0AAAMAOQB1DQAABABQAH8NAAADAC8AqQ0AAAQATABcDQAAAwBGAF0NAAACADsAZQ0AAAIAMAAzDQAAAwBFABQAAgrAEFkjAGIAAo4NAAABACkAMw0AAAEALAAAAA==.Daraceae:BAEBNQAECoEnAAIOAAkKCiIxBABmAwmODQAABgBdAHUNAAAFAFoAfw0AAAQAYACpDQAABQBfAFwNAAAEAFsAXQ0AAAMAWABlDQAABABSAKQNAAACADAAMw0AAAYAYQAOAAkKCiIxBABmAwmODQAABgBdAHUNAAAFAFoAfw0AAAQAYACpDQAABQBfAFwNAAAEAFsAXQ0AAAMAWABlDQAABABSAKQNAAACADAAMw0AAAYAYQAAAA==.Dariaana:BAEANQAECgYIBwABNQAECgkJKQAGAOwkAA==.Davebtw:BAEANQAECgIIAgAAAA==.',
De='Deaddari:BAEBNQAECoEpAAIGAAkK7CT0AgC0AwmODQAABgBgAHUNAAAFAGIAfw0AAAUAVwCpDQAABQBgAFwNAAAFAGMAXQ0AAAQAYgBlDQAABQBaAKQNAAACAF8AMw0AAAQAVwAGAAkK7CT0AgC0AwmODQAABgBgAHUNAAAFAGIAfw0AAAUAVwCpDQAABQBgAFwNAAAFAGMAXQ0AAAQAYgBlDQAABQBaAKQNAAACAF8AMw0AAAQAVwAAAA==.Dedbrew:BAEANQAECgMJAwABNQAECgUJCAAHAAAAAA==.Deddh:BAEANQAECgIJAwABNQAECgUJCAAHAAAAAA==.Deddk:BAEANQAECgUJCAAAAA==.Defected:BAECNQAFFIEFAAIGAAIK+x+yEgC8AAKODQAAAwBdAKkNAAACAEYABgACCvsfshIAvAACjg0AAAMAXQCpDQAAAgBGADUABAqBIwACBgAJCjsmqgEA0gMABgAJCjsmqgEA0gMAAAA=.Devmetz:BAEANQAECgQIBAABNQAFFAUIDwAVALgbAA==.Devroguemetz:BAECNQAFFIEPAAMVAAUKuBvqBQB0AQWODQAABABLAHUNAAADAFEAfw0AAAIALACpDQAAAwBSADMNAAADAEYAFQAECo0a6gUAdAEEjg0AAAQASwB1DQAAAwBRAH8NAAACACwAMw0AAAMARgAWAAEKYiBgEABdAAGpDQAAAwBSADUABAqBJwADFQAJCjUk9BAATwIAFQAGCkkk9BAATwIAFgAECo0h0jgAcAEAAAA=.',
Di='Disörder:BAEANQAFFAIIAgAAAA==.Divinebo:BAEANQADCggJDQABNQAFFAMIBgAIANwIAA==.Divinelightx:BAEANQADCggICAABNQAFFAUICQAXAJUdAA==.',
Dk='Dkpoc:BAEBNQAECoEdAAIGAAgKqRXlOQDdAQiODQAABQA/AHUNAAAEAD4Afw0AAAQAQQCpDQAABAA6AFwNAAAEAD4AXQ0AAAMAMQBlDQAAAwAwADMNAAACACAABgAICqkV5TkA3QEIjg0AAAUAPwB1DQAABAA+AH8NAAAEAEEAqQ0AAAQAOgBcDQAABAA+AF0NAAADADEAZQ0AAAMAMAAzDQAAAgAgAAE1AAUUAQgBAAcAAAAA.',
Do='Dokanalha:BAEANQAECgUIBgAAAA==.Doubledime:BAEANQAECgYICgAAAA==.',
Dr='Drakdeez:BAEANQADCgIIAgABNQAECggICQAHAAAAAA==.Drdwagon:BAECNQAFFIEQAAISAAcKNA1RAQAbAgeODQAABAA7AHUNAAADABQAfw0AAAEAAQCpDQAAAwAaAFwNAAACAD0AXQ0AAAEABAAzDQAAAgA+ABIABwo0DVEBABsCB44NAAAEADsAdQ0AAAMAFAB/DQAAAQABAKkNAAADABoAXA0AAAIAPQBdDQAAAQAEADMNAAACAD4ANQAECoEfAAMSAAkKvyIKAwDiAgASAAgK+CMKAwDiAgAYAAgKLhRjFADFAQAAAA==.Drinkzonme:BAEANQAECgUICgAAAA==.Dräka:BAEANQADCgYIHwAAAA==.',
['Dä']='Däddysips:BAEANQAECgYIEAABNQAFFAMIBgANAKcKAA==.',
['Dì']='Dìsorder:BAEANQAFFAEIAQABNQAFFAIIAgAHAAAAAA==.',
Ec='Ecobrew:BAEANQAECggIEQABNQAECgkJJwAZAFYfAA==.Ecosdk:BAEANQAECggIBQABNQAECgkJJgAJAKkcAA==.Ecospally:BAEANQAECgYICAABNQAECgkJJgAJAKkcAA==.',
Ed='Edgelordxd:BAEANQADCgIIAgABNQAECgUICgAHAAAAAA==.',
Ei='Eightpuppies:BAECNQAFFIEWAAITAAcKdx0zAQCzAgeODQAABQBfAHUNAAADAFsAfw0AAAMATQCpDQAABABjAFwNAAACAFsAXQ0AAAEAGgAzDQAABAAtABMABwp3HTMBALMCB44NAAAFAF8AdQ0AAAMAWwB/DQAAAwBNAKkNAAAEAGMAXA0AAAIAWwBdDQAAAQAaADMNAAAEAC0ANQAECoEiAAITAAkKniSdIwA5AwATAAkKniSdIwA5AwAAAA==.',
El='Eldan:BAEBNQAECoEXAAIaAAkKpR8wCQDQAgmODQAAAwBXAHUNAAADAGIAfw0AAAIAQQCpDQAAAwBaAFwNAAACAF4AXQ0AAAIAVQBlDQAABABPAKQNAAACADsAMw0AAAIAQwAaAAkKpR8wCQDQAgmODQAAAwBXAHUNAAADAGIAfw0AAAIAQQCpDQAAAwBaAFwNAAACAF4AXQ0AAAIAVQBlDQAABABPAKQNAAACADsAMw0AAAIAQwAAAA==.Eldist:BAEANQAECggIEgABNQAECgkJFwAaAKUfAA==.',
Em='Embulance:BAEANQAECgYIEQABNQAECgkKIAAJABYYAA==.Emchii:BAEANQADCggICAABNQAECgkKIAAJABYYAA==.Emluminate:BAEBNQAECoEgAAMJAAkKFhjLMgBaAgmODQAABgA3AHUNAAAGAFcAfw0AAAUAUwCpDQAABQBHAFwNAAADADYAXQ0AAAEARgBlDQAAAQAhAKQNAAABACIAMw0AAAQAPgAJAAgKchnLMgBaAgiODQAABQA3AHUNAAAGAFcAfw0AAAUAUwCpDQAABQBHAFwNAAADADYAXQ0AAAEARgCkDQAAAQAiADMNAAAEAD4AEAACCsQDZVUAVwACjg0AAAEACQBlDQAAAQAJAAE1AAQKCQogAAkAFhgA.',
Ep='Epp:BAEANQADCgIIAgABNQAECgkJJwAOAAoiAA==.',
Ev='Evokur:BAEANQAECgQICgAAAA==.',
Ex='Executiexd:BAEANQADCgYICQABNQAECgUICgAHAAAAAA==.',
Ey='Eyrae:BAEANQAECgIIAwABNQAECgkJGgAUAH4dAA==.',
Fa='Fainmaven:BAEANQAECgUICAABNQAECgcIBwAHAAAAAA==.Fainpaven:BAEANQAECgQICgABNQAECgcIBwAHAAAAAA==.Fatdari:BAEANQAECgEJAQABNQAECgkJKQAGAOwkAA==.Fatescurse:BAEBNQAECoEcAAQDAAgKcB1OSQAzAgiODQAABgBaAHUNAAAEADIAfw0AAAQAYQCpDQAABABQAFwNAAACAEgAXQ0AAAIALQBlDQAAAwBEADMNAAADAGEAAwAHCgocTkkAMwIHjg0AAAYAWgB1DQAAAQAeAH8NAAAEAGEAXA0AAAEASABdDQAAAgAtAGUNAAACAEQAMw0AAAMAYQAEAAMKmROmOgDCAAN1DQAAAwAyAKkNAAAEAFAAZQ0AAAEAEwAPAAEKQhbtHwBMAAFcDQAAAQA4AAAA.',
Fl='Fláminis:BAECNQAFFIESAAICAAYKZSArAgBJAgaODQAABABaAHUNAAADAF0Afw0AAAMAOQCpDQAAAwBQAFwNAAACAE8AMw0AAAMAXwACAAYKZSArAgBJAgaODQAABABaAHUNAAADAF0Afw0AAAMAOQCpDQAAAwBQAFwNAAACAE8AMw0AAAMAXwA1AAQKgSMAAwIACQrIJMQCAKkDAAIACQrIJMQCAKkDABsACAqsGw86AEUCAAAA.',
Fo='Fofer:BAEANQAFFAMIAwABNQAFFAYIEgAGAN0bAA==.',
Fu='Furymike:BAEBNQAECoEjAAMIAAgKGRXUYAAjAgiODQAABQAvAHUNAAAFAEEAfw0AAAUAOACpDQAABQAgAFwNAAAEAEMAXQ0AAAQAJQBlDQAAAgAsADMNAAAFAFEACAAICrgU1GAAIwIIjg0AAAMALwB1DQAAAwBBAH8NAAADADgAqQ0AAAMAGQBcDQAAAwBDAF0NAAADACUAZQ0AAAIALAAzDQAAAwBRABwABwqYC3EPAF0BB44NAAACACEAdQ0AAAIAMgB/DQAAAgAcAKkNAAACACAAXA0AAAEABwBdDQAAAQAMADMNAAACACkAAAA=.',
Fy='Fystpriest:BAEANQAECgcICQAAAA==.',
Ga='Gahdania:BAEANQAECgQIBwAAAA==.',
Ge='Genshii:BAECNQAFFIEUAAIdAAYKpB1XAAAsAgaODQAABABeAHUNAAAEAEUAfw0AAAMAOwCpDQAABABZAFwNAAABADMAMw0AAAQAWwAdAAYKpB1XAAAsAgaODQAABABeAHUNAAAEAEUAfw0AAAMAOwCpDQAABABZAFwNAAABADMAMw0AAAQAWwA1AAQKgSEAAh0ACQrNIugCAEgDAB0ACQrNIugCAEgDAAE1AAUUBgoUAB0ApB0A.',
Gh='Ghet:BAEANQAECgcIBwABNQAECgcICQAHAAAAAA==.',
Gi='Ginjao:BAEANQADCgcIBwABNQAFFAQICQAeANEiAA==.Ginjaoo:BAECNQAFFIEJAAIeAAQK0SJpAwBmAQSODQAAAgBiAH8NAAABAEAAqQ0AAAIAYwAzDQAABABeAB4ABArRImkDAGYBBI4NAAACAGIAfw0AAAEAQACpDQAAAgBjADMNAAAEAF4ANQAECoE2AAIeAAkKcSZAAADsAwAeAAkKcSZAAADsAwAAAA==.',
Gr='Greatllama:BAEANQAECggIEQAAAA==.Groovii:BAECNQAFFIEdAAIBAAcK8SR1AADqAgeODQAABABVAHUNAAAEAGIAfw0AAAQAYwCpDQAABABaAFwNAAAEAFsAXQ0AAAQAZAAzDQAABQBfAAEABwrxJHUAAOoCB44NAAAEAFUAdQ0AAAQAYgB/DQAABABjAKkNAAAEAFoAXA0AAAQAWwBdDQAABABkADMNAAAFAF8ANQAECoEXAAIBAAkKUSEfCAAFAwABAAkKUSEfCAAFAwAAAA==.',
Gu='Gunimal:BAEANQAECgEJAgABNQAFFAQICAAfAF0XAA==.Gunrunner:BAECNQAFFIEIAAIfAAQKXRdxAAB1AQSODQAAAwAxAHUNAAABAC0AqQ0AAAIAUgAzDQAAAgA9AB8ABApdF3EAAHUBBI4NAAADADEAdQ0AAAEALQCpDQAAAgBSADMNAAACAD0ANQAECoEfAAMfAAkKHSNzAgDgAgAfAAkKOyBzAgDgAgAgAAgKNiDJFACMAgAAAA==.',
['Gä']='Gättsu:BAEANQAECgcIDAAAAA==.',
Ha='Hazëy:BAEANQAECgUIEAABNQAFFAQIBwAXACQfAA==.',
He='Henzill:BAEANQAECggICQABNQAFFAMIBgADAHUSAA==.Henzillxlock:BAECNQAFFIEGAAQDAAMKdRK5IwCSAAOODQAAAwA0AKkNAAACAEcAMw0AAAEAEQADAAIK8wu5IwCSAAKODQAAAwA0AKkNAAABAAgABAABChoc8BMAWAABqQ0AAAEARwAPAAEK4wYqDABDAAEzDQAAAQARADUABAqBJwAEAwAJCoEbS0EATgIAAwAICnAbS0EATgIABAAECpMPXDIA5gAADwABCh8awh8ATQAAAAA=.',
Ho='Holysele:BAEBNQAECoEXAAIFAAkKix+yNQCzAgmODQAAAwBRAHUNAAADAFAAfw0AAAIASgCpDQAAAwBZAFwNAAACAFMAXQ0AAAIAQwBlDQAABABcAKQNAAACAEEAMw0AAAIAXAAFAAkKix+yNQCzAgmODQAAAwBRAHUNAAADAFAAfw0AAAIASgCpDQAAAwBZAFwNAAACAFMAXQ0AAAIAQwBlDQAABABcAKQNAAACAEEAMw0AAAIAXAABNQAFFAUICAAXABkXAA==.',
Hu='Hunterbo:BAEANQAECggICAABNQAFFAMIBgAIANwIAA==.',
Hy='Hydrohunter:BAEANQADCgEIAQABNQAFFAUIBwAbADYYAA==.Hydrosplash:BAECNQAFFIEHAAIbAAUKNhgfBgC8AQWODQAAAQBIAHUNAAABACIAfw0AAAEAIgCpDQAAAgBVADMNAAACAFEAGwAFCjYYHwYAvAEFjg0AAAEASAB1DQAAAQAiAH8NAAABACIAqQ0AAAIAVQAzDQAAAgBRADUABAqBHAACGwAJCp8krQMAxQMAGwAJCp8krQMAxQMAAAA=.',
['Hâ']='Hâzêy:BAEANQAECgEIAQABNQAFFAQIBwAXACQfAA==.',
['Hä']='Häzey:BAECNQAFFIEHAAIXAAQKJB9PBgCNAQSODQAAAwBjAHUNAAABAGEAfw0AAAEAGQCpDQAAAgBgABcABAokH08GAI0BBI4NAAADAGMAdQ0AAAEAYQB/DQAAAQAZAKkNAAACAGAANQAECoE+AAIXAAkKsyaxAAD7AwAXAAkKsyaxAAD7AwAAAA==.',
Ib='Ibdapopo:BAEBNQAECoEpAAIXAAgKuySVDgBIAwiODQAACQBjAHUNAAAFAFoAfw0AAAUAUACpDQAABQBhAFwNAAADAGAAXQ0AAAMAYABlDQAABgBiAKQNAAAFAFwAFwAICrsklQ4ASAMIjg0AAAkAYwB1DQAABQBaAH8NAAAFAFAAqQ0AAAUAYQBcDQAAAwBgAF0NAAADAGAAZQ0AAAYAYgCkDQAABQBcAAAA.',
Im='Imsíght:BAEANQADCggICAAAAA==.',
Jo='Johncxvii:BAECNQAFFIEHAAITAAQKdwqtHAAnAQSODQAAAwBVAH8NAAABAAQAqQ0AAAIACQAzDQAAAQAHABMABAp3Cq0cACcBBI4NAAADAFUAfw0AAAEABACpDQAAAgAJADMNAAABAAcANQAECoEsAAITAAkK2h2dMQAMAwATAAkK2h2dMQAMAwAAAA==.',
Jy='Jyst:BAEANQADCgYIBgABNQAECgcICQAHAAAAAA==.',
Ka='Kajse:BAEANQAFFAQIEAAAAQ==.',
Ke='Keveighnne:BAEANQAECgcIDQAAAA==.Keylana:BAEBNQAECoEaAAIUAAkKfh3TBADqAgmODQAABABWAHUNAAAEAFQAfw0AAAQAVQCpDQAAAwBRAFwNAAACAFoAXQ0AAAIAPgBlDQAAAgAxAKQNAAABADQAMw0AAAQAVwAUAAkKfh3TBADqAgmODQAABABWAHUNAAAEAFQAfw0AAAQAVQCpDQAAAwBRAFwNAAACAFoAXQ0AAAIAPgBlDQAAAgAxAKQNAAABADQAMw0AAAQAVwAAAA==.',
Ko='Kokobear:BAEANQAECggIDgABNQAFFAIIBQADAH4SAA==.Kostbar:BAEANQAECgUIBQABNQAECgkJIQAhAKwgAA==.',
Kp='Kpóc:BAEANQAECgcJBwABNQAFFAEIAQAHAAAAAA==.',
Ku='Kuweeph:BAEANQADCgYIBgABNQAECgcIDQAHAAAAAA==.',
La='Lardorable:BAEANQADCgIIAgABNQAECggIGgAMAM0YAA==.Larkiron:BAEANQADCgIIAgABNQAECggIGgAMAM0YAA==.Lavrie:BAECNQAFFIEOAAMiAAcKFRxqAADrAQeODQAAAwBNAHUNAAACAGEAfw0AAAIAKgCpDQAAAgBCAFwNAAACAGIAXQ0AAAEAFgAzDQAAAgBiACIABQpQHGoAAOsBBY4NAAACAE0AdQ0AAAIAYQCpDQAAAgBCAFwNAAACAGIAXQ0AAAEAFgAOAAMKnRtuBwD7AAOODQAAAQBaAH8NAAACAEEAMw0AAAIAOAA1AAQKgSoAAw4ACQrVJH4EAGADAA4ACQrVJH4EAGADACIABwo8JSUFAOACAAAA.',
Li='Lilyythe:BAEANQAECgIIAwABNQAECgcIEwAHAAAAAA==.Livrae:BAEANQAECgUIBQABNQAFFAcIDgAiABUcAA==.',
Ll='Llamwar:BAEANQAECgMIAwABNQAECggIEQAHAAAAAA==.',
Lo='Lookaway:BAEANQAECgIIAgAAAA==.',
Ma='Machfive:BAEBNQAECoEcAAIIAAkKEiQpDwBwAwmODQAABABYAHUNAAADAGIAfw0AAAMAYgCpDQAAAwBLAFwNAAADAFgAXQ0AAAMAYABlDQAABABhAKQNAAADAGEAMw0AAAIAWgAIAAkKEiQpDwBwAwmODQAABABYAHUNAAADAGIAfw0AAAMAYgCpDQAAAwBLAFwNAAADAFgAXQ0AAAMAYABlDQAABABhAKQNAAADAGEAMw0AAAIAWgAAAA==.Malthor:BAEANQAECgEIAQABNQAFFAIIBQADAH4SAA==.Marebear:BAEANQADCggJEAABNQAECgkJIwAJAIkUAA==.Maredithe:BAEBNQAECoEjAAMJAAkKiRTZPQAqAgmODQAABQA6AHUNAAAFADcAfw0AAAUANwCpDQAABQAyAFwNAAAEADYAXQ0AAAMARgBlDQAAAwAjAKQNAAABABIAMw0AAAQASQAJAAkKiRTZPQAqAgmODQAABAA6AHUNAAAEADcAfw0AAAUANwCpDQAABQAyAFwNAAAEADYAXQ0AAAMARgBlDQAAAwAjAKQNAAABABIAMw0AAAQASQAjAAIK8hGeGABtAAKODQAAAQA6AHUNAAABACEAAAA=.Maritt:BAECNQAFFIESAAIJAAYKgCN7AQCIAgaODQAABABiAHUNAAADAFUAfw0AAAMAWgCpDQAAAwBhAFwNAAACAFAAMw0AAAMAXAAJAAYKgCN7AQCIAgaODQAABABiAHUNAAADAFUAfw0AAAMAWgCpDQAAAwBhAFwNAAACAFAAMw0AAAMAXAA1AAQKgS8AAwkACQqWJdICAKsDAAkACQqWJdICAKsDACMABAobD4kSAMUAAAAA.',
Mc='Mchimba:BAEANQAECggIBwAAAA==.',
Me='Meatmagician:BAEANQAECgYIBgABNQAFFAYIDgASAGkWAA==.Meatrub:BAEANQAECgQIBAABNQAFFAYIDgASAGkWAA==.Mec:BAEBNQAECoEcAAMVAAkKlBxnDQCEAgmODQAABgBYAHUNAAAEAE8Afw0AAAQASQCpDQAAAgBeAFwNAAADAFwAXQ0AAAEAMgBlDQAABABJAKQNAAACABIAMw0AAAIAWAAVAAgKOR9nDQCEAgiODQAABgBYAHUNAAACAE8Afw0AAAMASQCpDQAAAgBeAFwNAAADAFwAXQ0AAAEAMgBlDQAAAgBJADMNAAACAFgAFgAEChoXzEUAHwEEdQ0AAAIATgB/DQAAAQBJAGUNAAACAEEApA0AAAIAEgAAAA==.',
Mo='Molecyl:BAEANQADCggJCAABNQAFFAIIBQAGAPsfAA==.Mowre:BAEBNQAECoEfAAIkAAkK3iGeBgBuAwmODQAABQBTAHUNAAAFAFwAfw0AAAQAWwCpDQAABABYAFwNAAAEAF4AXQ0AAAIATgBlDQAAAwBXAKQNAAABAFAAMw0AAAMAUgAkAAkK3iGeBgBuAwmODQAABQBTAHUNAAAFAFwAfw0AAAQAWwCpDQAABABYAFwNAAAEAF4AXQ0AAAIATgBlDQAAAwBXAKQNAAABAFAAMw0AAAMAUgAAAA==.Mowridan:BAEANQADCgcIBwABNQAECgkJHwAkAN4hAA==.',
Mu='Murderbêard:BAEBNQAECoEeAAIRAAcKvB8ULQB5AgeODQAABgBWAHUNAAAFAF0Afw0AAAQAYACpDQAABABSAFwNAAAEAEcAXQ0AAAMAPgAzDQAABABJABEABwq8HxQtAHkCB44NAAAGAFYAdQ0AAAUAXQB/DQAABABgAKkNAAAEAFIAXA0AAAQARwBdDQAAAwA+ADMNAAAEAEkAATUABAoICAoABwAAAAA=.Murtag:BAECNQAFFIEdAAIIAAcKvyTNAADrAgeODQAABQBjAHUNAAADAGAAfw0AAAMAWQCpDQAABQBiAFwNAAAEAGEAXQ0AAAQATQAzDQAABQBiAAgABwq/JM0AAOsCB44NAAAFAGMAdQ0AAAMAYAB/DQAAAwBZAKkNAAAFAGIAXA0AAAQAYQBdDQAABABNADMNAAAFAGIANQAECoEmAAIIAAkK2ibXAAD7AwAIAAkK2ibXAAD7AwAAAA==.Murtmonk:BAEANQABCgYIBwABNQAFFAcIHQAIAL8kAA==.Murtwarr:BAEBNQAECoEZAAIIAAkKqSJTLQDaAgmODQAAAwBfAHUNAAADAFUAfw0AAAMAWQCpDQAAAwBjAFwNAAADAFIAXQ0AAAMAXQBlDQAAAwBSAKQNAAACAEsAMw0AAAIAXgAIAAkKqSJTLQDaAgmODQAAAwBfAHUNAAADAFUAfw0AAAMAWQCpDQAAAwBjAFwNAAADAFIAXQ0AAAMAXQBlDQAAAwBSAKQNAAACAEsAMw0AAAIAXgABNQAFFAcIHQAIAL8kAA==.',
My='Mycropht:BAEBNQAECoEjAAIFAAkKVBnCPgCQAgmODQAABgBJAHUNAAAEADsAfw0AAAQARQCpDQAABABAAFwNAAADAEgAXQ0AAAMANABlDQAABAA5AKQNAAACADYAMw0AAAUATwAFAAkKVBnCPgCQAgmODQAABgBJAHUNAAAEADsAfw0AAAQARQCpDQAABABAAFwNAAADAEgAXQ0AAAMANABlDQAABAA5AKQNAAACADYAMw0AAAUATwAAAA==.',
['Mä']='Mäxemas:BAECNQAFFIEOAAMQAAYKyR9gAQBaAgaODQAAAgBjAHUNAAADAFQAfw0AAAIAXQCpDQAAAwBeAFwNAAABADQAMw0AAAMAPwAQAAYKyR9gAQBaAgaODQAAAgBjAHUNAAADAFQAfw0AAAIAXQCpDQAAAwBeAFwNAAABADQAMw0AAAIAPwAJAAEKKRSgJABRAAEzDQAAAQAzADUABAqBJwAEEAAJClMm9gEAtgMAEAAJClMm9gEAtgMAIwAECrwZlg4AEAEACQADCroZO44A9gAAAAA=.Mäxemås:BAEANQAECgMIAwABNQAFFAYIDgAQAMkfAA==.',
['Må']='Måxemäs:BAEANQADCggIEAABNQAFFAYIDgAQAMkfAA==.',
Na='Nateg:BAEANQADCgMIAwABNQAFFAMICAATALkfAA==.Nattygee:BAECNQAFFIEIAAITAAMKuR8rHAAtAQOODQAABQBhAKkNAAACADMAMw0AAAEAXwATAAMKuR8rHAAtAQOODQAABQBhAKkNAAACADMAMw0AAAEAXwA1AAQKgSYAAhMACQqMIXYZAF0DABMACQqMIXYZAF0DAAAA.',
No='Nosfarkia:BAEANQADCgEIAQABNQAECggIGwAIAEYmAA==.Notoriousrip:BAEANQAFFAIIAwABNQAFFAUIEQAgAMMbAA==.Nozdd:BAEBNQAFFIENAAIDAAUKLRPaBgCeAQWODQAAAwA5AHUNAAACABYAfw0AAAEAWgCpDQAABAAsADMNAAADAB4AAwAFCi0T2gYAngEFjg0AAAMAOQB1DQAAAgAWAH8NAAABAFoAqQ0AAAQALAAzDQAAAwAeAAAA.Nozfarkia:BAEBNQAECoEbAAMIAAgKRialFABPAwiODQAABQBjAHUNAAAEAGEAfw0AAAQAYQCpDQAABQBjAFwNAAACAGMAXQ0AAAMAYgBlDQAAAgBiADMNAAACAFwACAAICqIlpRQATwMIjg0AAAEAXgB1DQAABABhAH8NAAABAF8AqQ0AAAUAYwBcDQAAAQBfAF0NAAADAGIAZQ0AAAIAYgAzDQAAAQBbABwABAoJJiwLAMMBBI4NAAAEAGMAfw0AAAMAYQBcDQAAAQBjADMNAAABAFwAAAA=.',
Ot='Otwind:BAEBNQAECoEhAAIbAAkK0yNLCACTAwmODQAABQBhAHUNAAAEAF4Afw0AAAQAWQCpDQAABABiAFwNAAAEAFkAXQ0AAAMAVwBlDQAABABXAKQNAAADAFcAMw0AAAIAXQAbAAkK0yNLCACTAwmODQAABQBhAHUNAAAEAF4Afw0AAAQAWQCpDQAABABiAFwNAAAEAFkAXQ0AAAMAVwBlDQAABABXAKQNAAADAFcAMw0AAAIAXQABNQAFFAIIBQADAH4SAA==.',
Pl='Ploog:BAEANQAECggICQAAAA==.Ploogyw:BAEANQAECgEIAQABNQAECggICQAHAAAAAA==.',
Pr='Prantho:BAEANQAECgUIBQABNQAECggICQAHAAAAAA==.Prec:BAEBNQAECoEhAAMhAAkKrCASAwBOAwmODQAABgBWAHUNAAAEAF0Afw0AAAQAUQCpDQAABABeAFwNAAAEAFwAXQ0AAAIAUgBlDQAAAwBDAKQNAAACAD8AMw0AAAQAWgAhAAkKrCASAwBOAwmODQAABgBWAHUNAAADAF0Afw0AAAMAUQCpDQAABABeAFwNAAADAFwAXQ0AAAIAUgBlDQAAAwBDAKQNAAACAD8AMw0AAAMAWgAiAAQK1Au0HADQAAR1DQAAAQArAH8NAAABABcAXA0AAAEALQAzDQAAAQAIAAAA.',
Pu='Punanilani:BAECNQAFFIEFAAITAAIKIQRkOgCGAAKODQAABAAPAKkNAAABAAUAEwACCiEEZDoAhgACjg0AAAQADwCpDQAAAQAFADUABAqBJgADEwAJCqEdwDgA+QIAEwAJCqEdwDgA+QIAJQAECukOQAUA6wAAATUABAoHCA0ABwAAAAA=.',
Ra='Raerlynn:BAEANQAECgUICwAAAA==.Ragebo:BAECNQAFFIEGAAIIAAMK3AhDGQDMAAOODQAAAgARAHUNAAACAAwAqQ0AAAIAJgAIAAMK3AhDGQDMAAOODQAAAgARAHUNAAACAAwAqQ0AAAIAJgA1AAQKgSYAAggACQoxG/07AJ8CAAgACQoxG/07AJ8CAAAA.',
Re='Remilia:BAEANQAECgIJAwAAAA==.',
Ri='Ribroast:BAEANQADCggIEAABNQAFFAYIDgASAGkWAA==.',
Ro='Rolykins:BAEANQAECgcICQABNQAFFAUICwAFAEYbAA==.Rolym:BAEANQAECggICAABNQAFFAUICwAFAEYbAA==.Roubow:BAEANQADCggICAABNQAECgYIEgAHAAAAAA==.Roullaeu:BAEANQAECgYIEgAAAA==.Rozeybear:BAECNQAFFIELAAIbAAUKeA18CACDAQWODQAAAgA+AHUNAAADABUAfw0AAAEADgCpDQAAAwA2ADMNAAACABQAGwAFCngNfAgAgwEFjg0AAAIAPgB1DQAAAwAVAH8NAAABAA4AqQ0AAAMANgAzDQAAAgAUADUABAqBKQACGwAJCm8eQRIAOwMAGwAJCm8eQRIAOwMAAAA=.',
Ru='Ruossaeu:BAEANQAECgMIBQABNQAECgYIEgAHAAAAAA==.Ruxs:BAEANQAECgUIBQABNQAECgUIEAAHAAAAAA==.',
Sa='Sagoriken:BAECNQAFFIEHAAICAAQK1A+fCgBCAQSODQAAAgARAHUNAAABADcAfw0AAAEAKACpDQAAAwAwAAIABArUD58KAEIBBI4NAAACABEAdQ0AAAEANwB/DQAAAQAoAKkNAAADADAANQAECoEwAAICAAkKlyMcBQCIAwACAAkKlyMcBQCIAwAAAA==.Saphacan:BAEANQADCgUIBQABNQAECgYIEwAHAAAAAA==.Saphigon:BAEANQAECgYIEwAAAA==.Sayuri:BAEANQAECgMIAwABNQAFFAMIBgAmAGoNAA==.',
Sc='Schooty:BAECNQAFFIEKAAIXAAUKgBJNBQCkAQWODQAAAwBdAHUNAAACACQAfw0AAAEALQCpDQAAAgAhADMNAAACABsAFwAFCoASTQUApAEFjg0AAAMAXQB1DQAAAgAkAH8NAAABAC0AqQ0AAAIAIQAzDQAAAgAbADUABAqBIQADFwAJCmUgDiYAxQIAFwAJCmUgDiYAxQIAIAAHCm0RLi0AiwEAAAA=.',
Se='Selenium:BAEANQAECgUIEgAAAA==.',
Sh='Shämydavisjr:BAEANQAECgYIDAABNQAECgcIFwAFAI8dAA==.',
Si='Siñful:BAEANQAECggICgABNQAECgkJIQAiAHsfAA==.',
Sl='Slammystabby:BAEBNQAECoEdAAMWAAkKfxhgMQCiAQmODQAABQBPAHUNAAAFAE4Afw0AAAQATACpDQAAAwBCAFwNAAADAEMAXQ0AAAIANQBlDQAAAwAiAKQNAAABACkAMw0AAAMAQwAWAAYKcxVgMQCiAQaODQAAAQBPAKkNAAADAEIAXQ0AAAIANQBlDQAAAwAiAKQNAAABACkAMw0AAAEANgAVAAUKUBzDIgCLAQWODQAABABIAHUNAAAFAE4Afw0AAAQATABcDQAAAwBDADMNAAACAEMAATUABAoICBIABwAAAAA=.Slammywhammy:BAEANQAECggIEgAAAA==.',
Sm='Smackthelip:BAECNQAFFIEOAAMSAAYKaRZSAQAaAgaODQAABABgAHUNAAABAA8Afw0AAAMAOwCpDQAABABaAFwNAAABAC8AMw0AAAEAIwASAAYKaRZSAQAaAgaODQAAAgBgAHUNAAABAA8Afw0AAAMAOwCpDQAAAgBaAFwNAAABAC8AMw0AAAEAIwAYAAIKmBr0CACWAAKODQAAAgA1AKkNAAACAFIANQAECoEeAAQSAAkKziIpAwDWAgASAAcKhiUpAwDWAgAYAAcKXh1TEgDsAQABAAIK3g4POwBtAAAAAA==.Smashn:BAEBNQAECoEbAAIIAAgKBiTIGQA0AwiODQAABABbAHUNAAAEAF8Afw0AAAQAXgCpDQAABABgAFwNAAAEAGEAXQ0AAAMAVQBlDQAAAgBcADMNAAACAFQACAAICgYkyBkANAMIjg0AAAQAWwB1DQAABABfAH8NAAAEAF4AqQ0AAAQAYABcDQAABABhAF0NAAADAFUAZQ0AAAIAXAAzDQAAAgBUAAAA.',
Sn='Snuggless:BAECNQAFFIERAAIgAAUKwxu4BQCzAQWODQAAAgBUAHUNAAADADwAfw0AAAIAIgCpDQAABQBfADMNAAAFAE8AIAAFCsMbuAUAswEFjg0AAAIAVAB1DQAAAwA8AH8NAAACACIAqQ0AAAUAXwAzDQAABQBPADUABAqBGQADIAAICmIiUQ0A5gIAIAAICpggUQ0A5gIAFwAHCngf7GgA6gEAAAA=.',
So='Solex:BAEBNQAECoEtAAIKAAkK7RXCHwCaAgmODQAABwBNAHUNAAAGAFIAfw0AAAYAWgCpDQAABwAyAFwNAAAFACkAXQ0AAAUAIwBlDQAABAAnAKQNAAACABcAMw0AAAMAQAAKAAkK7RXCHwCaAgmODQAABwBNAHUNAAAGAFIAfw0AAAYAWgCpDQAABwAyAFwNAAAFACkAXQ0AAAUAIwBlDQAABAAnAKQNAAACABcAMw0AAAMAQAAAAA==.Sondragosa:BAEANQAECgYIEgAAAA==.',
Ss='Ssoth:BAEBNQAECoErAAIZAAkKmCIzCABfAwmODQAABwBcAHUNAAAHAGEAfw0AAAYAWwCpDQAABgBdAFwNAAAEAGEAXQ0AAAQAQQBlDQAABABeAKQNAAACAE4AMw0AAAMAVwAZAAkKmCIzCABfAwmODQAABwBcAHUNAAAHAGEAfw0AAAYAWwCpDQAABgBdAFwNAAAEAGEAXQ0AAAQAQQBlDQAABABeAKQNAAACAE4AMw0AAAMAVwAAAA==.Ssothdh:BAEANQADCgEIAQABNQAECgkJKwAZAJgiAA==.',
Sw='Swagles:BAEANQAECgEIAQABNQAECgkJKAAOALMiAA==.Switching:BAEBNQAECoEmAAMJAAkKqRyzEQAQAwmODQAABgBVAHUNAAAFAGIAfw0AAAUAYACpDQAABQBOAFwNAAAFAFIAXQ0AAAQAOgBlDQAAAwAZAKQNAAADAFUAMw0AAAIAMAAJAAkKqRyzEQAQAwmODQAABQBVAHUNAAAFAGIAfw0AAAUAYACpDQAABQBOAFwNAAAFAFIAXQ0AAAQAOgBlDQAAAwAZAKQNAAADAFUAMw0AAAIAMAAjAAEK6hsHIAA5AAGODQAAAQBHAAAA.',
Ta='Tanczak:BAEBNQAECoEjAAImAAkKEB49CwAOAwmODQAABgBHAHUNAAAEAFoAfw0AAAQAXACpDQAABwBKAFwNAAADAEYAXQ0AAAIAVABlDQAABABIAKQNAAACADoAMw0AAAMATQAmAAkKEB49CwAOAwmODQAABgBHAHUNAAAEAFoAfw0AAAQAXACpDQAABwBKAFwNAAADAEYAXQ0AAAIAVABlDQAABABIAKQNAAACADoAMw0AAAMATQAAAA==.',
Te='Tekli:BAEANQAECgUIBQABNQAECgkJIQAhAKwgAA==.',
Th='Theokar:BAEBNQAECoEbAAIbAAkKZCX8AgDOAwmODQAAAgBeAHUNAAADAGIAfw0AAAQAXgCpDQAABABhAFwNAAADAF8AXQ0AAAQAYQBlDQAAAgBZAKQNAAABAGAAMw0AAAQAYQAbAAkKZCX8AgDOAwmODQAAAgBeAHUNAAADAGIAfw0AAAQAXgCpDQAABABhAFwNAAADAF8AXQ0AAAQAYQBlDQAAAgBZAKQNAAABAGAAMw0AAAQAYQABNQAECgkJIwATAN0jAA==.Theomag:BAEBNQAECoEjAAQTAAkK3SONLAAcAwmODQAABgBcAHUNAAAEAF8Afw0AAAMAXACpDQAABABiAFwNAAAEAGEAXQ0AAAMAYgBlDQAABABcAKQNAAADAEMAMw0AAAQAXAATAAkKnCGNLAAcAwmODQAABgBcAHUNAAAEAF8Afw0AAAMAXACpDQAAAgBJAFwNAAAEAGEAXQ0AAAEARwBlDQAABABcAKQNAAADAEMAMw0AAAMAXAALAAIKUCafGwDPAAKpDQAAAgBiAF0NAAACAGIAJQABCsodSwgAUQABMw0AAAEATAAAAA==.Theorior:BAEANQADCgYICgABNQAECgkJIwATAN0jAA==.Thiaslock:BAEANQAECgQIBAABNQAFFAcIEgAJADYfAA==.Thiasmonk:BAEANQAECgEIAQABNQAFFAcIEgAJADYfAA==.Thiaspriest:BAECNQAFFIESAAMJAAcKNh+nAAC5AgeODQAAAgA3AHUNAAADAF0Afw0AAAMAXwCpDQAABABYAFwNAAABAFQAXQ0AAAEANAAzDQAABABYAAkABwo2H6cAALkCB44NAAABADcAdQ0AAAMAXQB/DQAAAwBfAKkNAAAEAFgAXA0AAAEAVABdDQAAAQA0ADMNAAAEAFgAIwABChYNAQMASwABjg0AAAEAIQA1AAQKgSQAAwkACQq2JY0EAI8DAAkACQq2JY0EAI8DACMAAQo4HJcbAFYAAAAA.',
To='Toedek:BAEANQAECggICAABNQAECggICwAHAAAAAA==.Toxiclightx:BAEANQAECgIICAABNQAFFAUICQAXAJUdAA==.',
Tr='Traumaxd:BAEANQAECgMIBQAAAA==.',
Un='Unclightx:BAECNQAFFIEJAAIXAAUKlR1KAwDdAQWODQAAAwBMAHUNAAACAFUAfw0AAAEAUgCpDQAAAgBZADMNAAABACwAFwAFCpUdSgMA3QEFjg0AAAMATAB1DQAAAgBVAH8NAAABAFIAqQ0AAAIAWQAzDQAAAQAsADUABAqBJQADFwAJCqQkqQMAuAMAFwAJCqQkqQMAuAMAIAAICt0L/yoAoQEAAAA=.',
Us='Usonja:BAEANQAECgQIBAABNQAFFAQICQAeANEiAA==.',
Vo='Vortexis:BAEANQADCggICgABNQAECgYIEwAHAAAAAA==.',
Wa='Waffietv:BAEANQAECgYICAABNQAECggICQAHAAAAAA==.Wafflestv:BAEANQAECggICQAAAA==.Warminis:BAEANQAECgIIAwABNQAFFAYIEgACAGUgAA==.',
Wi='Wildery:BAEANQAFFAIIAgAAAA==.Wildgracettv:BAEANQAECgcICwABNQAECgkKOwAhALElAA==.Wildgracetv:BAEBNQAECoE7AAIhAAkKsSWCAADsAwmODQAACQBhAHUNAAAJAGIAfw0AAAsAYwCpDQAACQBgAFwNAAAFAGIAXQ0AAAQAXwBlDQAAAwBhAKQNAAADAFYAMw0AAAYAYQAhAAkKsSWCAADsAwmODQAACQBhAHUNAAAJAGIAfw0AAAsAYwCpDQAACQBgAFwNAAAFAGIAXQ0AAAQAXwBlDQAAAwBhAKQNAAADAFYAMw0AAAYAYQABNQAECgkKOwAhALElAA==.Wildthyr:BAEANQAECgYIBgABNQAFFAIIAgAHAAAAAA==.',
Wo='Wolfsmage:BAECNQAFFIESAAMTAAYK0xpiBgAcAgaODQAAAwBcAHUNAAADADIAfw0AAAMAJACpDQAABABRAFwNAAACAEgAMw0AAAMATgATAAYK0xpiBgAcAgaODQAAAwBcAHUNAAADADIAfw0AAAMAJACpDQAABABRAFwNAAABAEgAMw0AAAMATgAlAAEK1RhyAABlAAFcDQAAAQA/ADUABAqBHQADEwAJClAjRicALAMAEwAJCr4iRicALAMAJQABCqEkcgcAagAAAAA=.Wolfspriest:BAEANQAECgEIAQABNQAFFAYIEgATANMaAA==.',
Xh='Xharacen:BAEBNQAECoEbAAIIAAkKyiDjOQCnAgmODQAABABjAHUNAAACAFkAfw0AAAEAAwCpDQAAAgBgAFwNAAACAFYAXQ0AAAIAWwBlDQAABwBiAKQNAAAGAFsAMw0AAAEAYgAIAAkKyiDjOQCnAgmODQAABABjAHUNAAACAFkAfw0AAAEAAwCpDQAAAgBgAFwNAAACAFYAXQ0AAAIAWwBlDQAABwBiAKQNAAAGAFsAMw0AAAEAYgABNQAECgkJFwAZAEUlAA==.Xhurnyra:BAEBNQAECoElAAIFAAgKAiWTHQAgAwiODQAABQBgAHUNAAAGAGIAfw0AAAYAYgCpDQAABgBhAFwNAAAEAF4AXQ0AAAMAWwBlDQAAAgBUADMNAAAFAF8ABQAICgIlkx0AIAMIjg0AAAUAYAB1DQAABgBiAH8NAAAGAGIAqQ0AAAYAYQBcDQAABABeAF0NAAADAFsAZQ0AAAIAVAAzDQAABQBfAAAA.',
Xy='Xydeco:BAEBNQAECoEpAAIfAAgKvyUSAQBdAwiODQAABgBjAHUNAAAHAGIAfw0AAAcAYwCpDQAABgBjAFwNAAAEAF0AXQ0AAAQAYQBlDQAAAgBWADMNAAAFAGMAHwAICr8lEgEAXQMIjg0AAAYAYwB1DQAABwBiAH8NAAAHAGMAqQ0AAAYAYwBcDQAABABdAF0NAAAEAGEAZQ0AAAIAVgAzDQAABQBjAAAA.',
Ya='Yakoß:BAEBNQAECoEjAAIYAAgKJRnSDABiAgiODQAABgBOAHUNAAAEAEwAfw0AAAQAQQCpDQAABQBKAFwNAAAEADkAXQ0AAAQAIgBlDQAABAA3ADMNAAAEAEcAGAAICiUZ0gwAYgIIjg0AAAYATgB1DQAABABMAH8NAAAEAEEAqQ0AAAUASgBcDQAABAA5AF0NAAAEACIAZQ0AAAQANwAzDQAABABHAAAA.',
Za='Zandikar:BAEANQADCgQIBAABNQAECgkJIwATAN0jAA==.',
Zh='Zhaobo:BAEANQAECgMIAwABNQAFFAYIEAAaAAMgAA==.',
Zu='Zuzusu:BAEANQAECgUIEAAAAA==.',
['Ða']='Ðaybreak:BAEANQAECggIDgABNQAFFAUIDQAZAI0YAA==.Ðaywraith:BAECNQAFFIENAAIZAAUKjRj5AwCVAQWODQAAAwBdAHUNAAADAD4Afw0AAAIAGwCpDQAAAwBSADMNAAACADAAGQAFCo0Y+QMAlQEFjg0AAAMAXQB1DQAAAwA+AH8NAAACABsAqQ0AAAMAUgAzDQAAAgAwADUABAqBFQACGQAICoogCB4AkAIAGQAICoogCB4AkAIAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
