local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Rogue-Outlaw','Rogue-Assassination','Priest-Shadow','Priest-Holy','DemonHunter-Devourer','Warlock-Affliction','Warlock-Demonology','Warlock-Destruction','DeathKnight-Frost','Shaman-Enhancement','Rogue-Subtlety','Mage-Arcane','Mage-Frost','Paladin-Holy','Shaman-Elemental','Shaman-Restoration','Hunter-BeastMastery','Monk-Windwalker','DemonHunter-Havoc','Monk-Brewmaster','Hunter-Marksmanship','Evoker-Devastation','DeathKnight-Unholy','Paladin-Retribution','DemonHunter-Vengeance','Druid-Restoration','Evoker-Preservation','Druid-Guardian','Warrior-Arms','Paladin-Protection','DeathKnight-Blood','Priest-Discipline','Warrior-Protection','Druid-Balance','Warrior-Fury','Hunter-Survival','Monk-Mistweaver','Evoker-Augmentation',}
local provider = {region='US',realm='BurningBlade',name='US',type='weekly',zone=53,date='2026-10-06',data={Aa='Aatto:BAAANQADCgYICgABNQAECgUICAABAAAAAA==.',
Ab='Abefroman:BAAANQAECgIIBAAAAA==.Abefromen:BAAANQADCggICAAAAA==.',
Ac='Acertrick:BAACNQAFFIEgAAMCAAcK6CMIAAD5AgACAAcK6CMIAAD5AgADAAQKWxhzBwBcAQA1AAQKgS4AAwIACQqSJiIAAPQDAAIACQqSJiIAAPQDAAMAAwrQGwJbAPwAAAAA.',
Ad='Adampriest:BAABNQAECoEgAAMEAAkK9iF7BwBSAwAEAAkK9iF7BwBSAwAFAAcKEB4iNQBxAgAAAA==.Addh:BAACNQAFFIEGAAIGAAMKdxdHCgD0AAAGAAMKdxdHCgD0AAA1AAQKgScAAgYACQrTHJwQANoCAAYACQrTHJwQANoCAAAA.Adria:BAAANQAECgEIAQAAAA==.',
Ae='Aelwyd:BAACNQAFFIEKAAMHAAMKbAT1AQDdAAAHAAMKAgT1AQDdAAAIAAEKoQG2OgBEAAA1AAQKgTkABAcACQoMHWQCAOACAAcACQrMGmQCAOACAAkACQoGD+ANAA8CAAgABQrvCxbGABABAAAA.Aenden:BAAANQADCgQIBAAAAA==.Aeoni:BAAANQADCggICAABNQAECgkJJwAKADUhAA==.Aeronis:BAAANQAECgUICQAAAA==.Aery:BAAANQAECgYIBgABNQAFFAEIAQABAAAAAA==.Aessara:BAAANQAECgUIEQAAAA==.',
Ag='Aggron:BAABNQAECoEtAAILAAkKVyGuAwBZAwALAAkKVyGuAwBZAwAAAA==.',
Ai='Ailurun:BAAANQADCgEJAgAAAA==.',
Al='Alexassassin:BAABNQAECoEdAAIMAAkK9hunDACbAgAMAAkK9hunDACbAgAAAA==.Aloriannis:BAABNQAECoEcAAMNAAcKkhxwrgAEAgANAAYKoR1wrgAEAgAOAAIK6gvUMwBUAAAAAA==.Aluas:BAAANQAECgUIBwAAAA==.Alurai:BAAANQADCggIFQAAAA==.',
Am='Amaracepally:BAABNQAECoEdAAIPAAcKdRxgQgA9AgAPAAcKdRxgQgA9AgAAAA==.Amethar:BAAANQAFFAEIAQABNQAFFAcIGgALAJ8dAA==.Amowdrood:BAAANQAECgMIAwABNQAECgkJKAAQAPIdAA==.Amowshamow:BAABNQAECoEoAAMQAAkK8h2YKQC4AgAQAAgKMB6YKQC4AgARAAcKvQ7VcQCGAQAAAA==.',
An='Anan:BAAANQAECgIJAwAAAA==.Anaria:BAAANQADCgYJCwAAAA==.Anatall:BAABNQAECoEtAAISAAkKpiNxBAC4AwASAAkKpiNxBAC4AwABNQAECgkJJgAPAOQjAA==.Andrin:BAABNQAECoEdAAIPAAgKBCJeFwAMAwAPAAgKBCJeFwAMAwAAAA==.Andy:BAAANQADCgYIBgAAAA==.Aneira:BAAANQADCgUIBQAAAA==.Anitá:BAAANQAECgIJAgAAAA==.',
Ap='Applebees:BAAANQAECgYICwABNQAECgkJLAATAL4hAA==.',
Ar='Araragi:BAABNQAECoEaAAMGAAkK+RjWFwCGAgAGAAkK+RjWFwCGAgAUAAEKXwWsgwAzAAAAAA==.Archaon:BAABNQAECoElAAMOAAkKGyBGAgAtAwAOAAkKoh5GAgAtAwANAAkKlhCOkwA8AgAAAA==.Arei:BAABNQAECoEhAAIVAAgKGx9RCACJAgAVAAgKGx9RCACJAgABNQAFFAEIAQABAAAAAA==.Argosa:BAABNQAECoEZAAMNAAcK/xBH2QCuAQANAAcKtg9H2QCuAQAOAAEK0QpBPQA5AAAAAA==.Argy:BAAANQAECggIEQAAAA==.Ari:BAABNQAECoExAAITAAkKmyM3BACGAwATAAkKmyM3BACGAwAAAA==.Arianagrande:BAAANQAECgIIAwAAAA==.Aridk:BAAANQAECgIIAgABNQAECgkJMQATAJsjAA==.Ariehh:BAAANQADCgcIDQABNQAECgkJMQATAJsjAA==.Arihog:BAAANQAECgYIEgAAAA==.Arioch:BAAANQAECgIIBQAAAA==.Arkilytê:BAACNQAFFIEZAAMUAAYKYiG8AgA+AgAUAAYKox68AgA+AgAGAAQKxx+ABwBmAQA1AAQKgS0AAwYACQqOJIwHAFEDAAYACQoSI4wHAFEDABQABQroIsgwAPIBAAAA.Aryaana:BAAANQADCgcIBwAAAA==.Aryä:BAAANQAECgEIAQAAAA==.',
As='Ascend:BAECNQAFFIEXAAIPAAcKphB2AwA6AgAPAAcKphB2AwA6AgA1AAQKgR0AAg8ACQoEHgMZAAIDAA8ACQoEHgMZAAIDAAAA.Ascendant:BAECNQAFFIEMAAIRAAcKYwjABAAGAgARAAcKYwjABAAGAgA1AAQKgRYAAxEACArdDmdiALcBABEACArdDmdiALcBABAAAQoXFEMKAUAAAAE1AAUUBwgXAA8AphAA.Astraeá:BAABNQAECoEeAAMSAAgKNB+sLADGAgASAAgKNB+sLADGAgAWAAEK1gZpfgAxAAAAAA==.',
At='Ataci:BAAANQAECgIIAgAAAA==.',
Au='Auroch:BAABNQAECoEhAAIXAAkKPBvsBwDpAgAXAAkKPBvsBwDpAgAAAA==.Auxilary:BAABNQAECoElAAMKAAkKGRFkLQD+AQAKAAkKGRFkLQD+AQAYAAIKAgklugBVAAAAAA==.',
Av='Avalen:BAAANQAECgEIAQAAAA==.Avarathyr:BAAANQABCgIIAgAAAA==.Avarcis:BAABNQAECoEaAAIZAAkK1B45JAAbAwAZAAkK1B45JAAbAwAAAA==.Avasauras:BAAANQAECgEIAQABNQAECgEIAQABAAAAAA==.Aveleni:BAABNQAECoErAAINAAkK1hFjjABLAgANAAkK1hFjjABLAgAAAA==.Aveloree:BAAANQAECgEIAQAAAA==.',
Aw='Awakening:BAAANQAECgUJBQAAAA==.',
Az='Azelie:BAABNQAECoEaAAIaAAgKsho+BwBqAgAaAAgKsho+BwBqAgAAAA==.',
Ba='Babwe:BAAANQAECgUICAABNQAECggIHQAKALQVAA==.Baddragön:BAAANQADCgIIAgABNQAECgkJJwAbAPMUAA==.Baery:BAAANQAFFAEIAQAAAA==.Baidoom:BAAANQABCgQIBAAAAA==.Balcmeg:BAABNQAECoEZAAILAAgKtx94CADgAgALAAgKtx94CADgAgABNQAECggIGgAFAPYMAA==.Bandrui:BAAANQAECgMIAwAAAA==.Banick:BAAANQAECgcICgAAAA==.Bartszsimpsn:BAAANQAECgUIBQABNQAECgYIEgABAAAAAA==.Bartszwar:BAAANQAECgYIEgAAAA==.',
Be='Bendie:BAAANQAECgEJAQAAAA==.Beret:BAACNQAFFIEGAAIcAAMK4RwqDQAKAQAcAAMK4RwqDQAKAQA1AAQKgSkAAhwACQpOH3wJAP0CABwACQpOH3wJAP0CAAAA.Bewmbat:BAAANQAECgYICgABNQAECgQIBAABAAAAAQ==.',
Bg='Bgaraecen:BAAANQADCgQIBAAAAA==.',
Bi='Bigchimpn:BAAANQAECgUIBgAAAA==.Bimbo:BAAANQAECgYIEgAAAA==.Bindkickplz:BAAANQABCgQIBwAAAA==.Birdinii:BAAANQAFFAIIAgAAAA==.Birstormrage:BAAANQAECgMIBgAAAA==.',
Bl='Blacksmoke:BAAANQADCgUIBAAAAA==.Blacktusk:BAABNQAECoEaAAQJAAgKTQx+HgByAQAJAAcKOQp+HgByAQAIAAcKrQeZqQBPAQAHAAQKZQwoEwDtAAAAAA==.Bladestorm:BAAANQAECgQIAwAAAA==.Blargdruid:BAACNQAFFIELAAIdAAUKyQpVAgA6AQAdAAUKyQpVAgA6AQA1AAQKgTkAAh0ACQqXHmcFABsDAB0ACQqXHmcFABsDAAAA.Blargwar:BAABNQAECoEYAAIeAAgKlhSzaQA0AgAeAAgKlhSzaQA0AgABNQAFFAUICwAdAMkKAA==.Blessthat:BAEANQAECgIIAwAAAA==.Blindnada:BAAANQAECgEJAQABNQAECggIFQAfAPwhAA==.',
Bo='Bonkie:BAAANQAECgQICgABNQAECggIGgAUAKIQAA==.Boomkíll:BAAANQADCgUIBwABNQAECgQIBQABAAAAAA==.',
Br='Breaze:BAAANQAECgcIEAAAAA==.Brewdyne:BAAANQADCggICAABNQAECgkJLAANAHgUAA==.Brewsef:BAAANQADCggICgAAAA==.Bricktøp:BAAANQAECgEIAQABNQAECggIGQAgADMeAA==.Brignis:BAAANQADCgUIBQAAAA==.Brisnger:BAAANQADCgYICAAAAA==.Brizz:BAAANQAECgQICAABNQAECggIGgARAIcbAA==.Brojojojojo:BAABNQAECoEYAAITAAgKsBytFgBvAgATAAgKsBytFgBvAgAAAA==.Broxas:BAAANQAECgEIAQAAAA==.Brøken:BAAANQAECggIEAAAAA==.',
Bu='Bubbleblade:BAAANQADCgEIAQAAAA==.Bubblesbro:BAACNQAFFIEOAAIZAAYKGhsHAwAqAgAZAAYKGhsHAwAqAgA1AAQKgSkAAhkACQqfJmkDANsDABkACQqfJmkDANsDAAAA.Bubkiss:BAAANQAECgQIBAAAAQ==.Buffalo:BAACNQAFFIEGAAIeAAMKhRYDGwDyAAAeAAMKhRYDGwDyAAA1AAQKgSwAAh4ACQo/IZAaAEEDAB4ACQo/IZAaAEEDAAAA.Buffs:BAAANQADCgIIAgABNQAECgcIDgABAAAAAA==.Buffy:BAAANQAECgYICgAAAA==.Bulbasaurz:BAAANQAECgYIBwAAAA==.Buldair:BAAANQAECgEIAgAAAA==.Bunsski:BAABNQAECoEXAAIRAAYK4xegbwCNAQARAAYK4xegbwCNAQAAAA==.Bunsskijr:BAAANQABCgcICQAAAA==.Burntbacon:BAAANQAECgUIBQABNQAECgkJKQAgAIsRAA==.Burstygirl:BAABNQAECoEkAAIGAAkKoBlHEwC5AgAGAAkKoBlHEwC5AgAAAA==.Buzzkill:BAAANQADCgMIAwAAAA==.',
Bw='Bwis:BAAANQAECgMIAwAAAA==.',
['Bø']='Bøkari:BAAANQAECgUIEQAAAA==.',
Ca='Café:BAAANQADCgYIBgAAAA==.Cakes:BAAANQADCgMIAwAAAA==.Caldrick:BAAANQAECgEIAgAAAA==.Callie:BAACNQAFFIEjAAIFAAcKkhknAgCIAgAFAAcKkhknAgCIAgA1AAQKgS4AAwUACQqBItcPADMDAAUACQqBItcPADMDACEACAoVCMoLAGoBAAAA.Caloren:BAAANQAECgQIBwABNQAECgcIGgAGAHkYAA==.Calypsoza:BAAANQAECgMIBQAAAA==.Capitis:BAAANQAECgYICgAAAA==.Catwink:BAAANQAECgMIAwAAAA==.Caulkfu:BAAANQADCgQIBAABNQAECggIJQAeAPkdAA==.Caulkgoblinz:BAAANQADCgMIAwABNQAECggIJQAeAPkdAA==.',
Ce='Celaine:BAAANQADCgIIAgAAAA==.Celika:BAAANQADCgQIBAAAAA==.Celine:BAABNQAECoEfAAIbAAgK5RlRGABVAgAbAAgK5RlRGABVAgAAAA==.Ceol:BAAANQAECgUICAAAAA==.Cernath:BAAANQADCgYIBgAAAA==.',
Ch='Chaddbrochil:BAAANQAECgcIBwAAAA==.Chaosblade:BAAANQAECgYICAAAAA==.Chickengawdz:BAAANQAECgYIBgAAAA==.Chilicheese:BAAANQADCgEIAQAAAA==.Chocobomb:BAABNQAECoEqAAMQAAkKUxPCSwAbAgAQAAkKUxPCSwAbAgARAAYKAQJXugDKAAAAAA==.Chosen:BAAANQAECgIIAgAAAA==.Chronarfs:BAAANQAECgYIEAAAAA==.',
Ci='Cicatrizesp:BAABNQAECoEoAAILAAkKKBNHDQB/AgALAAkKKBNHDQB/AgAAAA==.Cini:BAAANQADCggICAAAAA==.Citrine:BAAANQADCgUIBQAAAA==.Cive:BAABNQAECoEdAAIWAAgKBAjbMgCMAQAWAAgKBAjbMgCMAQAAAA==.',
Cl='Clayberd:BAAANQADCgUIBQABNQAECgMIAwABAAAAAA==.Clocho:BAAANQAECggICAAAAA==.',
Co='Coldhearrted:BAACNQAFFIEGAAQYAAMKrxW5EgCpAAAYAAIKKhy5EgCpAAAKAAEKswN0GgA6AAAgAAEKuQj4MQAjAAA1AAQKgSwAAwoACQq3Hu4ZAJQCAAoACQpoHO4ZAJQCABgABwryGtU/APgBAAAA.Copyleft:BAAANQAECgUIBQAAAA==.Cosmere:BAAANQAECggIDwAAAA==.',
Cr='Cracku:BAAANQADCgYIBgAAAA==.Crookamow:BAAANQAECgYIBwABNQAECgkJKAAQAPIdAA==.Cryt:BAAANQAECggIEAAAAA==.',
Da='Dagather:BAAANQADCgcICwAAAA==.Dalmore:BAAANQAECgcIDgAAAA==.Danala:BAAANQADCgYICgABNQAECggIHQAIAMEXAA==.Danendena:BAAANQAECgcIEwAAAA==.Danglars:BAAANQADCggJCwABNQAECgkJGgARAIUlAA==.Darkcorn:BAABNQAECoEgAAIeAAcK9BGknACrAQAeAAcK9BGknACrAQAAAA==.Darkdecayy:BAAANQADCgQIBQAAAA==.Darkshieldz:BAABNQAECoEgAAMfAAkKNQzWIwCVAQAfAAkKNQzWIwCVAQAZAAcKHgbQ2wApAQAAAA==.Darkstarex:BAAANQAECgMIBQAAAA==.Darktiranus:BAAANQADCggICAAAAA==.David:BAACNQAFFIEGAAIWAAMKaSLKDgAkAQAWAAMKaSLKDgAkAQA1AAQKgSYAAxYACQqUJV8HAE4DABYACApnJV8HAE4DABIAAQr3JuYZAXQAAAAA.',
De='Deadkyle:BAAANQADCgQIBAABNQAECgcIDQABAAAAAA==.Deadly:BAAANQADCgUIBQAAAA==.Deathcalls:BAAANQAECgUJBgAAAA==.Deathlywind:BAAANQAECggJDQAAAA==.Delphias:BAAANQAECgYIDwAAAA==.Deru:BAAANQAECgEJAQAAAA==.Destrorin:BAAANQAECgQIBAAAAA==.Dethlok:BAAANQADCgcIFgAAAA==.Deucedeuce:BAAANQADCggIOwAAAA==.Devigosa:BAAANQAECgYICAABNQAECgkJJwAKADUhAA==.Devowizard:BAACNQAFFIEjAAINAAkK5x84AACDAwANAAkK5x84AACDAwA1AAQKgRcAAg0ACQqzIKJIAOICAA0ACQqzIKJIAOICAAAA.Dewshaman:BAAANQADCgIIAgAAAA==.',
Di='Dibib:BAACNQAFFIEjAAMIAAcKjRmPAwAeAgAIAAYKrRePAwAeAgAJAAEKzCQ6EQBsAAA1AAQKgS4AAwgACQqBJRUQAD8DAAgACApdJRUQAD8DAAkACArkEukNAA8CAAAA.Dingbat:BAAANQABCgQIBAABNQAECgQIBAABAAAAAQ==.Dinglebery:BAABNQAECoEpAAIgAAkKixFcOwD1AQAgAAkKixFcOwD1AQAAAA==.Dinkee:BAAANQADCgUIBQABNQAECgcIEAABAAAAAA==.Dirac:BAAANQAECgYJCgAAAA==.Dirkdiggles:BAAANQAECgcIDQAAAA==.Dirtybirdz:BAAANQADCggIEAAAAA==.Discowalker:BAACNQAFFIEIAAITAAMKDRBFCgDUAAATAAMKDRBFCgDUAAA1AAQKgRkAAhMACQrVFKQaAD0CABMACQrVFKQaAD0CAAAA.Dislexy:BAAANQADCgQIBQAAAA==.Diviinity:BAAANQADCgEIAQABNQAECgQIBwABAAAAAA==.',
Dk='Dkittie:BAAANQAECgQIBQABNQAECgkJHgAPAGUfAA==.Dkitty:BAABNQAECoEeAAMPAAkKZR+iFAAdAwAPAAkKZR+iFAAdAwAZAAYK7BBGugBvAQAAAA==.Dkittykat:BAAANQAECgMIBgABNQAECgkJHgAPAGUfAA==.Dkizzy:BAAANQAECgYICwABNQAECgkJHgAPAGUfAA==.',
Do='Dogs:BAAANQAECgQIBQAAAA==.Donkeydonng:BAABNQAECoEaAAIgAAgKGwn6WgBlAQAgAAgKGwn6WgBlAQAAAA==.Doodlez:BAAANQAECgEIAQAAAA==.Dota:BAAANQAECgUICwAAAA==.',
Dr='Dracke:BAAANQADCggICwAAAA==.Draga:BAABNQAECoEmAAIKAAkK3RiRGQCYAgAKAAkK3RiRGQCYAgAAAA==.Dragondeezn:BAAANQAECggIEAAAAA==.Drak:BAACNQAFFIEJAAISAAUKiBnFBgC5AQASAAUKiBnFBgC5AQA1AAQKgSYAAxIACQr/InwKAHkDABIACQr/InwKAHkDABYAAgrLCx1mAG0AAAAA.Dralëon:BAAANQAECgUICgAAAA==.Drekzul:BAABNQAECoEYAAISAAgKLxfGSQBpAgASAAgKLxfGSQBpAgAAAA==.Drutara:BAAANQAECggIEwAAAA==.',
Du='Ducey:BAABNQAECoEVAAIbAAkKKhV5FACDAgAbAAkKKhV5FACDAgAAAA==.Ducksicker:BAAANQAECgcIEwAAAA==.Dumpsterbaby:BAAANQAECgYIDQAAAA==.Dumpsterfire:BAAANQAECgYIBwAAAA==.Durlklok:BAAANQAECgcIDgAAAA==.',
Dw='Dwarfsmasher:BAAANQADCgUIBwABNQAECgQIBwABAAAAAA==.',
['Dè']='Dèschain:BAAANQAECgQIBAAAAA==.',
['Dé']='Démonic:BAAANQADCgQIBAAAAA==.',
['Dë']='Dëku:BAAANQADCgcIBwAAAA==.',
['Dó']='Dóth:BAABNQAECoEVAAIZAAgKcB/nTQCDAgAZAAgKcB/nTQCDAgAAAA==.',
['Dø']='Dørf:BAAANQADCgUIBwAAAA==.',
Ef='Effinaye:BAAANQABCgYICAAAAA==.',
Ei='Eightfingers:BAABNQAECoEiAAMKAAkKvBVHMADqAQAKAAgK+hRHMADqAQAYAAIKNRnSnwCWAAAAAA==.Eisenklopfer:BAAANQAECgIIAgAAAA==.',
Ek='Ekim:BAAANQAECgEIAgAAAA==.',
El='Elara:BAABNQAECoEZAAIJAAcKRx+EBgCaAgAJAAcKRx+EBgCaAgAAAA==.Elentiya:BAAANQADCgUIBwAAAA==.Elyaen:BAABNQAECoEbAAIgAAgKYROtRADJAQAgAAgKYROtRADJAQAAAA==.',
Em='Emailed:BAECNQAFFIEQAAMRAAUKlAsXEAAcAQARAAQKPwgXEAAcAQAQAAIKRRO8HQCdAAA1AAQKgScAAxAACQq0HlklANACABAACQq0HlklANACABEAAwqtF2u7AMcAAAAA.Emi:BAAANQAECgIIAgAAAA==.Emofemboy:BAAANQADCgYICwAAAA==.',
En='Engost:BAAANQADCgQIAQAAAA==.Envy:BAAANQAECgYIEgAAAA==.',
Eo='Eore:BAAANQAECgUJCAAAAA==.',
Er='Erasris:BAAANQADCgQIBAAAAA==.Erequem:BAAANQADCgEIAQAAAA==.',
Eu='Eupatorus:BAAANQAECgQIBgAAAA==.',
Ew='Ewokhunter:BAABNQAECoEpAAIMAAkKECZ+AADsAwAMAAkKECZ+AADsAwAAAA==.',
Ex='Execuwute:BAAANQABCgYICAAAAA==.',
Fa='Fathernylla:BAAANQADCgUIBQABNQAFFAQICgANADoMAA==.',
Fe='Felonee:BAAANQADCggIIgAAAA==.Felrenze:BAAANQADCgQIBQAAAA==.Festermight:BAACNQAFFIEOAAQKAAMKrhfjDwCZAAAKAAIKdhjjDwCZAAAYAAIKoBjNFgCHAAAgAAEKwxETKwA0AAA1AAQKgTkAAwoACQpqJbACAK8DAAoACQpcJbACAK8DABgACQoTH3wzADoCAAAA.',
Fi='Finnhunter:BAAANQADCgEIAQAAAA==.Fireballs:BAAANQAECggIDQAAAA==.Firedur:BAAANQADCgYIBwABNQAECgcIEgABAAAAAA==.Firenze:BAAANQAECgQIBAAAAA==.Fishpockets:BAAANQADCgEIAQAAAA==.',
Fl='Flosstradamu:BAAANQABCgMIAQAAAA==.',
Fo='Forgivënëss:BAAANQADCggIDAABNQAECggIHAAiAEsjAA==.',
Fr='Fredrock:BAABNQAECoEaAAIRAAkKhSWdAQDGAwARAAkKhSWdAQDGAwAAAA==.',
Fu='Fuzziewuzzie:BAAANQAECgMIBAAAAA==.',
['Fî']='Fîshy:BAACNQAFFIEOAAMRAAYKRxw8BAAXAgARAAYKRxw8BAAXAgAQAAEKRQg9KgBGAAA1AAQKgRwAAhEACQobFZtRAPIBABEACQobFZtRAPIBAAAA.',
Ga='Gaibe:BAACNQAFFIEJAAIPAAUKYRN+CQChAQAPAAUKYRN+CQChAQA1AAQKgSUAAg8ACQqOJTUCAMcDAA8ACQqOJTUCAMcDAAAA.Gamba:BAABNQAECoEaAAQKAAcKbyGGMwDTAQAKAAcK7xuGMwDTAQAgAAIKHyJXigC0AAAYAAEKdBngwwBBAAAAAA==.Gambaj:BAAANQADCgYIBwAAAA==.Ganicuss:BAAANQAECgcICAAAAA==.Garuum:BAAANQADCggICAABNQAECggIHQAIAMEXAA==.Gawrek:BAAANQABCgIIAwAAAA==.',
Gb='Gb:BAAANQADCgYIBgAAAA==.',
Ge='Genghiscaulk:BAABNQAECoElAAIeAAgK+R2BRwCaAgAeAAgK+R2BRwCaAgAAAA==.Georgehunter:BAAANQAECgUIBQABNQAFFAMIEAAKANERAA==.Georgeknight:BAACNQAFFIEQAAQKAAMK0RF+DwCcAAAKAAIKghV+DwCcAAAYAAIKxRdeFACbAAAgAAEK9wObNQAbAAA1AAQKgS0AAwoACQo4I9AOAP4CAAoACQq/H9AOAP4CABgACQohINgfAK0CAAAA.Gertrùde:BAABNQAECoEaAAIFAAgK9gwkawCmAQAFAAgK9gwkawCmAQAAAA==.Gerunash:BAAANQADCggICAABNQAFFAgIHQAMAOUNAA==.Gewnz:BAABNQAECoEjAAQEAAkK3RxaFQCTAgAEAAgKJhxaFQCTAgAhAAUKGgltEgDnAAAFAAMK0AkdvACuAAABNQAECgQIBAABAAAAAA==.',
Gi='Gildharts:BAABNQAECoEhAAIFAAkKaCEHCwBYAwAFAAkKaCEHCwBYAwAAAA==.Gingergiant:BAAANQAECgQIBQABNQAECgUIDgABAAAAAA==.Girl:BAAANQAECgYIEQAAAA==.',
Gl='Glaiverush:BAAANQADCgMIAwAAAA==.Glowlimn:BAAANQAECgQIBAABNQAECgkJIwASAJQhAA==.',
Go='Gobirdz:BAAANQADCgEIAQABNQADCgcJBwABAAAAAA==.Goblindur:BAAANQAECgcIEgAAAA==.Gogeta:BAAANQADCgIIAgAAAA==.',
Gr='Gradris:BAACNQAFFIEGAAIZAAMKGRJLEwDiAAAZAAMKGRJLEwDiAAA1AAQKgSoAAhkACQqUHocvAO0CABkACQqUHocvAO0CAAAA.Gragdagonet:BAAANQADCggIDgABNQAECggIGgAdAKgZAA==.Greener:BAABNQAECoErAAIUAAkKDB94DwAPAwAUAAkKDB94DwAPAwAAAA==.Griddy:BAAANQAECgcJDQABNQAECgcIDgABAAAAAA==.Grimfu:BAAANQADCgcIBwABNQAECgYIIQAPAOAcAA==.Grimghar:BAAANQAECgIIAwAAAA==.Grimhoof:BAAANQADCgcIBwABNQAECgYIIQAPAOAcAA==.Grimrael:BAAANQADCggIDAABNQAECgYIIQAPAOAcAA==.Grimreapyr:BAAANQADCgUIBgABNQAECgYIIQAPAOAcAA==.Grimtar:BAABNQAECoErAAIRAAkKDyTVAwCgAwARAAkKDyTVAwCgAwABNQAECgYIIQAPAOAcAA==.Grimtariel:BAABNQAECoEhAAMPAAYK4BzoUwD+AQAPAAYK4BzoUwD+AQAZAAMKQAvCKgGdAAAAAA==.Grimtoh:BAAANQADCggICAABNQAECgYIIQAPAOAcAA==.Grimzilla:BAAANQAECgQIBQABNQAECgYIIQAPAOAcAA==.Grindkíng:BAAANQADCgQJBAAAAA==.Grippin:BAABNQAECoEdAAIYAAgKPiNqHADFAgAYAAgKPiNqHADFAgAAAA==.Gritspark:BAAANQAECgIIAgAAAA==.',
Gu='Guldar:BAAANQADCgYIBgAAAA==.Gunoil:BAABNQAECoEaAAIRAAgKwCCaGgDqAgARAAgKwCCaGgDqAgAAAA==.',
['Gì']='Gìngerale:BAAANQAECgUICQAAAA==.',
['Gü']='Gümby:BAAANQAECgQIBAAAAA==.',
Ha='Hamrshifts:BAAANQAECgUICQAAAA==.Hamrshocks:BAAANQADCgMIAwAAAA==.Hamrwitch:BAAANQADCgYIBgAAAA==.Harritapoter:BAAANQABCgYIBgAAAA==.Havartihavoc:BAAANQAECgQICAAAAA==.Hawtdots:BAAANQAECgMIBAABNQAECgYIDQABAAAAAA==.',
He='Healmeplx:BAAANQAECgQIBgAAAA==.Healsfadayz:BAAANQAECgQIBAAAAA==.Heiku:BAAANQAECgIIAwAAAA==.Hekaraa:BAAANQAECgIIAgAAAA==.Hellequin:BAAANQAECgIIAgAAAA==.Hellhammer:BAAANQAECgQIBAAAAA==.Herenya:BAAANQAECgcICwAAAA==.Herrina:BAAANQAECgEIAQABNQAECgcIFwAZADoeAA==.Hexual:BAAANQAECgQIBAAAAA==.',
Hi='Hiccup:BAAANQAECgUIBwAAAA==.Hideyourtoes:BAAANQAECgYIFgABNQAFFAYIFAAWAEAgAQ==.Himnick:BAACNQAFFIEdAAQHAAgK4BvIAAB8AQAHAAQKSxnIAAB8AQAJAAMKRR8IAgD/AAAIAAMK1RJ5GgDuAAA1AAQKgTYABAkACQpCJoIGAJoCAAkABwpeI4IGAJoCAAgABwqXH3xKAFUCAAcABQo7JZ4GABwCAAAA.',
Ho='Holmadic:BAAANQAECggIDAAAAA==.Holyslimes:BAAANQADCgMIAwAAAA==.Honoree:BAAANQAECgQICAAAAA==.Honse:BAAANQAECgYIDwAAAA==.Hoodal:BAACNQAFFIEVAAIPAAYKShS3BgDXAQAPAAYKShS3BgDXAQA1AAQKgR4AAg8ACQqoGJQuAJACAA8ACQqoGJQuAJACAAAA.Hope:BAABNQAFFIEGAAIcAAQKGALtDQDuAAAcAAQKGALtDQDuAAABNQAECgkKFwAPAE8YAA==.',
Hu='Hugzug:BAAANQAECgQJBAAAAA==.Huntrez:BAAANQADCgEIAQABNQAECgIIAgABAAAAAA==.Hustlepuff:BAAANQADCgYJEQAAAA==.',
Hy='Hyllah:BAAANQAECgIIAwAAAA==.',
['Hè']='Hèrrinà:BAABNQAECoEXAAMZAAcKOh7VjwDRAQAZAAYK5RzVjwDRAQAPAAEK2gQdBgE1AAAAAA==.',
['Hò']='Hòrnz:BAAANQABCgIIAgAAAA==.',
Ik='Ikissdudes:BAABNQAECoEsAAITAAkKviG+BgBQAwATAAkKviG+BgBQAwAAAA==.',
Il='Illuunni:BAABNQAECoEfAAIbAAgKKBiiGQBGAgAbAAgKKBiiGQBGAgAAAA==.',
Im='Imbecile:BAAANQADCgYIBgABNQAECgYICwABAAAAAA==.Imblack:BAABNQAECoEjAAIjAAkK0yEQDwA/AwAjAAkK0yEQDwA/AwAAAA==.Improv:BAAANQADCggICQABNQAECgkJIgAKALwVAA==.',
Ir='Ironsite:BAAANQABCgQIBAAAAA==.',
Ja='Jaunjaun:BAAANQABCggICAAAAA==.',
Jc='Jclaw:BAAANQAECgYIBgAAAA==.',
Je='Jeddak:BAAANQAECgYICgAAAA==.Jennay:BAAANQAECgEIAQAAAA==.Jennzen:BAAANQAECgIJAgABNQAECgMIAwABAAAAAA==.Jesterawr:BAAANQADCgUIBQABNQAECgQIBAABAAAAAA==.',
Ji='Jinjin:BAABNQAECoEVAAINAAgK5xMYpwATAgANAAgK5xMYpwATAgAAAA==.',
Jl='Jlimremix:BAAANQAECggIDwAAAA==.',
Jo='Jouley:BAAANQAECgYICgAAAA==.',
Ju='Justamage:BAAANQAECgYIDAAAAA==.Justsaiyan:BAAANQAECgEIAQAAAA==.',
Jx='Jx:BAAANQAECggIJgAAAQ==.',
Jz='Jzimm:BAAANQAECgcICAAAAA==.',
['Jå']='Jåcob:BAAANQADCggIBgABNQAECgIJAwABAAAAAA==.',
Ka='Kadane:BAAANQADCgYICwAAAA==.Kaeori:BAACNQAFFIEdAAIjAAgK7xUbAgCbAgAjAAgK7xUbAgCbAgA1AAQKgSQAAiMACQqTH+IaANcCACMACQqTH+IaANcCAAAA.Kaeorishock:BAAANQAECgYIBgABNQAFFAgIHQAjAO8VAA==.Kalïsta:BAABNQAECoEXAAMGAAcKNxROKQDYAQAGAAcKNxROKQDYAQAaAAYKjw5GFAA1AQAAAA==.Karlach:BAAANQADCggIHQAAAA==.Karnesia:BAAANQABCgMIAwAAAA==.Karra:BAABNQAECoEnAAIKAAkKNSEjCwArAwAKAAkKNSEjCwArAwAAAA==.Kayliezra:BAAANQAECgMIAwAAAA==.Kayssa:BAAANQAECgcIDQAAAA==.',
Ke='Keegan:BAABNQAECoEsAAMkAAkKqSQXAgBLAwAkAAgKzyQXAgBLAwAeAAIK2hzdAQGmAAAAAA==.Keiragosa:BAAANQAECgUIEAAAAA==.Keita:BAABNQAECoEeAAIlAAkKkiONAACpAwAlAAkKkiONAACpAwAAAA==.Kelaran:BAAANQADCgEIAQAAAA==.Kellired:BAAANQADCgIIAgAAAA==.Kelsara:BAACNQAFFIELAAINAAUK8xqlEQDCAQANAAUK8xqlEQDCAQA1AAQKgS8AAg0ACQqCJSEHAL4DAA0ACQqCJSEHAL4DAAAA.Keltan:BAAANQADCgQIBAAAAA==.',
Kh='Khaladyn:BAAANQADCgUJBQAAAA==.Khaladynie:BAAANQAECgUICQAAAA==.Khazjin:BAAANQADCgYIBgAAAA==.',
Ki='Kiko:BAAANQADCgcIEAABNQAECgMIAwABAAAAAA==.Killersmallz:BAABNQAECoEcAAIgAAgKuyCZGADRAgAgAAgKuyCZGADRAgAAAA==.Killshott:BAAANQADCgYIBgAAAA==.Killstardo:BAAANQAECggIDwAAAA==.Kindatipsy:BAAANQADCgYIEwAAAA==.Kirasti:BAAANQAECgUICQAAAA==.Kiriko:BAAANQAECgQIBAAAAA==.Kirkadh:BAAANQAECgYICAABNQAFFAgIJAAbAGAkAA==.Kirkam:BAAANQAECgcICAABNQAFFAgIJAAbAGAkAA==.Kirkap:BAAANQADCgUIBQABNQAFFAgIJAAbAGAkAA==.Kirkas:BAAANQAECgMICgABNQAFFAgIJAAbAGAkAA==.Kisspr:BAAANQAECgQIBQAAAA==.Kisswar:BAABNQAECoEcAAIeAAgKfSQAHAA7AwAeAAgKfSQAHAA7AwAAAA==.Kitkatt:BAAANQAECgQIBAAAAA==.Kittyen:BAAANQADCggICAAAAA==.',
Kl='Klet:BAABNQAECoEgAAMIAAgKYxunWwAiAgAIAAcKmhmnWwAiAgAJAAQKERG3LwD/AAAAAA==.',
Km='Kmage:BAAANQAECgIIAwAAAA==.',
Kn='Knull:BAAANQADCgIIAgAAAA==.',
Ko='Kogarasu:BAAANQAECgUICQAAAA==.Kokodrilo:BAAANQAECggIBgAAAA==.Koramar:BAAANQAECgIIAgABNQAFFAgIHQAMAOUNAA==.',
Kr='Kragarsf:BAAANQAECgIJAgAAAA==.Kronsicus:BAAANQAECggICAAAAA==.',
Ku='Kubernaughty:BAAANQADCgYIBgAAAA==.Kuulistin:BAAANQAECgUIDQAAAA==.',
Ky='Kyoppy:BAABNQAECoExAAIPAAkK/CBPDABXAwAPAAkK/CBPDABXAwAAAA==.',
La='Labluegirl:BAAANQADCgYIBgABNQAECgUICAABAAAAAA==.Lacusclyne:BAAANQADCgEIAQAAAA==.Lareith:BAAANQADCgcICgAAAA==.Lavaßurst:BAAANQAECgEIAQAAAA==.',
Le='Leejohn:BAAANQADCgYIBgAAAA==.Leeoz:BAAANQAECgIIAgAAAA==.Legitasaurus:BAAANQADCggIEAAAAA==.Legndairy:BAABNQAECoEeAAIeAAgKviE9JwAMAwAeAAgKviE9JwAMAwAAAA==.Legola:BAAANQADCgQIBQAAAA==.Lenala:BAACNQAFFIEJAAIZAAUKxBGXBwCrAQAZAAUKxBGXBwCrAQA1AAQKgRcAAhkACQpZGUxhAEkCABkACQpZGUxhAEkCAAAA.Leoz:BAAANQAECgIIAgAAAA==.',
Li='Lichedout:BAAANQADCgMIAwABNQAECgEIAQABAAAAAA==.Lickwid:BAAANQADCgIIAgAAAA==.Lightdeity:BAAANQADCgQIBgAAAA==.Lilbeefroni:BAAANQABCgEIAQAAAA==.Lilith:BAAANQAECgMIAwAAAA==.Lilythh:BAAANQADCgIIAgABNQAECgIIAgABAAAAAA==.Limp:BAAANQAECgIIAgAAAA==.Linessa:BAAANQAECgUIBAAAAA==.Lineste:BAAANQADCggICAAAAA==.Littlelion:BAABNQAECoEcAAIjAAkKygzkOgDxAQAjAAkKygzkOgDxAQAAAA==.Littlepigboy:BAAANQAECggIDwAAAA==.Littleteapot:BAABNQAECoEdAAIjAAgKzRW6NQAUAgAjAAgKzRW6NQAUAgAAAA==.',
Lo='Lockedup:BAAANQADCgcJBwAAAA==.Lockjim:BAAANQADCgMIAwAAAA==.Lookatthisph:BAAANQADCgIIAgABNQADCgcJBwABAAAAAA==.',
Lu='Lucentil:BAAANQAECgMIAwAAAA==.Lucie:BAAANQAECgYIEwAAAA==.Lucigoosey:BAAANQAECgIIAgAAAA==.Lucindra:BAAANQAECgIJAgABNQAECgMIAwABAAAAAA==.Luckycharms:BAAANQAECgIIAgAAAA==.Luckycharrmz:BAAANQADCgcJBwAAAA==.Luckyscharmm:BAAANQADCgEIAQABNQAECgIIAgABAAAAAA==.Luminth:BAABNQAECoEaAAIUAAgK1BtzJABQAgAUAAgK1BtzJABQAgAAAA==.Lutreaux:BAAANQADCggICwABNQAECggIHQAIAMEXAA==.',
Lv='Lv:BAAANQAECggIDwAAAA==.',
Ly='Lyka:BAABNQAECoEpAAIFAAcK/CEaKgCiAgAFAAcK/CEaKgCiAgAAAA==.',
Ma='Madoria:BAAANQAECgQIBgAAAA==.Madorie:BAAANQAECgIIAwAAAA==.Magice:BAAANQAECgIIAgAAAA==.Magistus:BAACNQAFFIEYAAImAAgK4g+zAAB4AgAmAAgK4g+zAAB4AgA1AAQKgTMAAyYACQp6H8QEAEMDACYACQp6H8QEAEMDABUAAQoOHUgqAEcAAAAA.Maravia:BAAANQADCggIDgAAAA==.Marmalady:BAECNQAFFIEVAAIcAAgKzxwiAQC1AgAcAAgKzxwiAQC1AgA1AAQKgSIAAhwACQr+IyIFAFIDABwACQr+IyIFAFIDAAAA.Masa:BAACNQAFFIEjAAIbAAcKmx90AACsAgAbAAcKmx90AACsAgA1AAQKgS4AAhsACQriJIsCAJgDABsACQriJIsCAJgDAAAA.Masq:BAABNQAECoEaAAIUAAgKohAPMgDpAQAUAAgKohAPMgDpAQAAAA==.Matamharicas:BAAANQAECgYIEwAAAA==.Matt:BAAANQAECgMIBAAAAA==.Mauled:BAACNQAFFIEHAAIgAAQKrhhWDgA9AQAgAAQKrhhWDgA9AQA1AAQKgRYAAiAACQqwIGcMAD4DACAACQqwIGcMAD4DAAE1AAUUCAgWAB8A/A8A.Maulnificent:BAAANQAECgIIAgABNQAFFAgIFgAfAPwPAA==.Maulo:BAACNQAFFIEWAAIfAAgK/A/GAQAUAgAfAAgK/A/GAQAUAgA1AAQKgRwAAh8ACQrFHhEMALgCAB8ACQrFHhEMALgCAAAA.Maynaminty:BAABNQAECoEdAAINAAcKehB0ywDKAQANAAcKehB0ywDKAQABNQAFFAUIGAAUAA4UAA==.',
Mc='Mclovin:BAAANQAECgEIAQAAAA==.',
Me='Medspriest:BAAANQAECgIIAgAAAA==.Megasoreass:BAAANQADCggICwAAAA==.Meliria:BAABNQAECoEhAAIPAAkKUR7GFAAcAwAPAAkKUR7GFAAcAwAAAA==.',
Mi='Microshanks:BAAANQADCggICQABNQAECgQIBAABAAAAAA==.Midgert:BAACNQAFFIERAAMNAAUKTBPLHgBOAQANAAQK6BfLHgBOAQAOAAEK2wDWDgBKAAA1AAQKgSoAAg0ACQoJItA2AA4DAA0ACQoJItA2AA4DAAAA.Mimint:BAAANQAECgIIAgABNQAFFAgIHQASAIIlAA==.Misfortune:BAAANQADCgUIBQAAAA==.Mistfit:BAAANQADCgYICgAAAA==.Mitula:BAAANQABCgUIAwAAAA==.',
Mo='Moadebe:BAAANQAECgIIAgAAAA==.Mommyenergy:BAAANQAECgUIBgABNQAECggIEAABAAAAAA==.Moomoomeadow:BAABNQAECoEYAAIjAAgKow3SRACxAQAjAAgKow3SRACxAQAAAA==.Moorpheus:BAAANQADCgYIBgAAAA==.Moreshaman:BAAANQADCgIJAQAAAA==.Morgianax:BAAANQAECgEIAQAAAA==.Morphsz:BAAANQAECgEIAQAAAA==.Morphunter:BAAANQAECgYIEQAAAA==.Mozerdozer:BAAANQADCgYIBgAAAA==.',
Mu='Muthabara:BAAANQADCggIDgAAAA==.Muwu:BAABNQAECoEsAAIZAAkKPiTDCwCXAwAZAAkKPiTDCwCXAwAAAA==.',
My='Myfursona:BAAANQAECgcIDwAAAA==.Mysticpizza:BAAANQADCgMJBAAAAA==.Mystrali:BAABNQAECoEdAAIIAAgKwRcOTABQAgAIAAgKwRcOTABQAgAAAA==.Mytzvearn:BAAANQAECgEIAgAAAA==.Myztified:BAAANQADCgUIBQAAAA==.',
['Mã']='Mãyhem:BAAANQADCgIIAgABNQAECgIJAwABAAAAAA==.',
['Mä']='Mädrina:BAAANQAECgMIBQAAAA==.',
Na='Naelyni:BAAANQAECgUIBQABNQADCggICwABAAAAAA==.Naloxone:BAAANQADCgEIAQAAAA==.Nathrezara:BAAANQABCgIIAgAAAA==.Nawtikal:BAAANQAECgUIDgAAAA==.',
Nc='Nck:BAAANQAECgQIBAAAAA==.',
Ne='Necrootter:BAABNQAECoEcAAMYAAgK/xKxSwC/AQAYAAgK4xKxSwC/AQAgAAIKVgsgqABcAAAAAA==.Negrumps:BAAANQADCgYJBwAAAA==.Nelune:BAAANQAECggICAAAAA==.Neoheals:BAAANQAECgEIAQAAAA==.Neotank:BAAANQADCgUIBQAAAA==.Netgehai:BAAANQADCgQIBAAAAA==.Neurosurgeon:BAAANQADCgEIAQAAAA==.Nezdh:BAACNQAFFIEiAAIUAAcKdSA5AQCdAgAUAAcKdSA5AQCdAgA1AAQKgSoAAxQACQoXJhgDALoDABQACQoXJhgDALoDAAYABwqXHnYlAPsBAAAA.',
Ni='Nibbs:BAAANQAECgIIAgAAAA==.Nizal:BAAANQAECgQIBAAAAA==.',
No='Nosimpin:BAAANQADCggIHwAAAA==.Notbrianp:BAAANQADCgMIAwABNQAECgUICAABAAAAAA==.Notbrianpage:BAAANQAECgUICAAAAA==.Nox:BAAANQADCggIEQAAAA==.',
Nu='Nutzferbuttz:BAAANQAECgIIAgABNQAECggIGQAQAOcSAA==.',
Ny='Nyllamage:BAACNQAFFIEKAAINAAQKOgzvIgAwAQANAAQKOgzvIgAwAQA1AAQKgSQAAg0ACQpCIMA8AP8CAA0ACQpCIMA8AP8CAAAA.',
['Nâ']='Nâ:BAAANQAECgEIAQAAAA==.',
Ob='Obdromeda:BAABNQAECoEoAAIbAAkKnx0QDADvAgAbAAkKnx0QDADvAgAAAA==.Oberron:BAABNQAECoEmAAIPAAkK5CNbAwC0AwAPAAkK5CNbAwC0AwAAAA==.',
Ok='Okixs:BAAANQAECgcIEQAAAA==.',
On='Onebaddruid:BAAANQAECgQICwAAAA==.Onebadwarr:BAABNQAECoEYAAIeAAgKigUi8ADOAAAeAAgKigUi8ADOAAABNQAECgQICwABAAAAAA==.',
Oo='Oogabgooga:BAABNQAECoEaAAISAAgK3xNaVABMAgASAAgK3xNaVABMAgAAAA==.',
Os='Oscartheorc:BAAANQADCgEIAQABNQADCgIJAQABAAAAAA==.Oshamma:BAABNQAECoEbAAIQAAcK/hhdVAD7AQAQAAcK/hhdVAD7AQAAAA==.Ossoleil:BAAANQADCgYIBgABNQAECggIGQAZAEQZAA==.',
Ot='Otterfang:BAAANQAECgcIEwAAAA==.',
Oz='Ozatar:BAAANQAECgQICAABNQAECgcIEQABAAAAAA==.Ozcane:BAAANQAECgcIEQAAAA==.Ozen:BAAANQAECgYIEwABNQAECgcIEQABAAAAAA==.Ozfernal:BAAANQAECgQIBAABNQAECgcIEQABAAAAAA==.Ozlayn:BAAANQAECgUIBgABNQAECgcIEQABAAAAAA==.Ozpal:BAAANQAECgUIEQABNQAECgcIEQABAAAAAA==.Ozplode:BAAANQADCgEIAQABNQAECgcIEQABAAAAAA==.Oztide:BAAANQAECgQICwABNQAECgcIEQABAAAAAA==.Oztington:BAAANQADCgEIAQAAAA==.',
Pa='Paegan:BAAANQADCgQIBAAAAA==.Paiku:BAAANQADCgYICgAAAA==.Palaky:BAABNQAECoEZAAIZAAgKRBkIYABOAgAZAAgKRBkIYABOAgAAAA==.Para:BAABNQAECoEgAAMPAAgK5RbaQwA4AgAPAAgK5RbaQwA4AgAZAAMKXgPbTQFhAAAAAA==.',
Pe='Peahole:BAAANQADCgQIBAAAAA==.Peccavi:BAAANQADCgYICQAAAA==.Pelusa:BAABNQAECoEXAAMgAAcKCgqQaQApAQAgAAcKWQiQaQApAQAKAAYKmQjEVAANAQAAAA==.Penelopi:BAABNQAECoEjAAISAAkKlCG8DgBYAwASAAkKlCG8DgBYAwAAAA==.Penguinia:BAAANQAECgEJAQAAAA==.Pensman:BAAANQABCgQIBAAAAA==.Peåches:BAAANQADCgUICQAAAA==.',
Pi='Pillowpantsu:BAAANQAECgMIAwAAAA==.Pitukis:BAAANQADCgYIBgAAAA==.',
Pl='Plandalorian:BAAANQAECgEJAQAAAA==.Platectonics:BAAANQADCgUIBwAAAA==.Plexadin:BAAANQAECgUICwAAAA==.',
Po='Ponch:BAAANQADCgQIBAAAAA==.Pookydooky:BAAANQADCgYIBgAAAA==.Popmybubble:BAABNQAECoErAAMZAAgKDw5bmQC6AQAZAAgKDw5bmQC6AQAfAAIKPAcVXgA/AAAAAA==.',
Pr='Prepotenté:BAABNQAECoEkAAIeAAkKGhcuYQBMAgAeAAkKGhcuYQBMAgAAAA==.Priesta:BAACNQAFFIEGAAIFAAIK6gzWIgCaAAAFAAIK6gzWIgCaAAA1AAQKgUIAAgUACQrzHpYYAPwCAAUACQrzHpYYAPwCAAAA.Pronebone:BAABNQAECoEeAAMeAAgKJhdFbgAnAgAeAAgKJhdFbgAnAgAiAAEKywNvQAAiAAAAAA==.',
Qu='Quomy:BAAANQAECgcIDgAAAA==.',
Ra='Rackblaster:BAAANQABCgMIAwAAAA==.Raei:BAABNQAECoE7AAIRAAkKfBhBKQCcAgARAAkKfBhBKQCcAgAAAA==.Ragestrasz:BAABNQAECoEdAAIdAAgKTyA8BwDjAgAdAAgKTyA8BwDjAgAAAA==.Raladin:BAABNQAECoEZAAIPAAgKwRkbOQBjAgAPAAgKwRkbOQBjAgAAAA==.Ralathroll:BAAANQAECgUIBQAAAA==.Ramchi:BAACNQAFFIEdAAMWAAgKhyHdAQB/AgAWAAcKMyHdAQB/AgASAAQKNiDNCACUAQA1AAQKgSUAAxYACQpWJpQEAIMDABYACQqRJZQEAIMDABIAAgofJnoAAcUAAAAA.Ramhorn:BAAANQAECgIJAgAAAA==.Ramsaur:BAABNQAECoEkAAIeAAkK9R4THgAyAwAeAAkK9R4THgAyAwAAAA==.Ranniel:BAAANQADCgEIAQAAAA==.Rasalghul:BAAANQADCgYICwAAAA==.Ratchetron:BAAANQABCgMIAwAAAA==.Raythe:BAAANQADCgIIAwAAAA==.Razorfists:BAABNQAECoEgAAMTAAgKgh5qEADDAgATAAgKgh5qEADDAgAVAAIK0gJmKgBGAAABNQAFFAcIGgAcANwLAA==.Razorscales:BAACNQAFFIEaAAQcAAcK3AsoCwBBAQAcAAUKMgYoCwBBAQAXAAMKQge4CADLAAAnAAEKDwQFCgBMAAA1AAQKgTAABBwACQonFVQVAEgCABwACQonFVQVAEgCABcABwqhHZERABwCACcAAQrVHccdAEYAAAAA.',
Re='Reckon:BAAANQAECgQIBgAAAA==.Reeleaf:BAABNQAECoEnAAMbAAkK8xSJGABTAgAbAAkK8xSJGABTAgAdAAEKEwvpUAArAAAAAA==.Reformedbtw:BAAANQAECgYIBAAAAA==.Remainn:BAAANQAECgEIAgAAAA==.Remlar:BAABNQAECoEWAAIZAAgKihuXXABYAgAZAAgKihuXXABYAgABNQAECgkJJAAGAKAZAA==.Renske:BAAANQADCgYICwAAAA==.',
Ri='Ricè:BAAANQAECgYIBgABNQAECgcIFAAVACkgAA==.Ride:BAAANQAECgIJAwAAAA==.Rixi:BAAANQAECgYIBAAAAA==.Rizzard:BAAANQAECggIEwAAAA==.',
Ro='Ronanss:BAAANQABCgIJBAAAAA==.Roriel:BAABNQAECoEmAAIbAAkKnRxlCgAHAwAbAAkKnRxlCgAHAwAAAA==.Rougarou:BAAANQAECgUIBwAAAA==.Rowdyronda:BAAANQABCgIIBAAAAA==.Roweana:BAAANQAECgUICQAAAA==.',
Rr='Rrambo:BAAANQAECggICAAAAA==.',
Ru='Rubmytotéms:BAAANQADCgUIBQABNQAECggIKwAZAA8OAA==.Rumblecat:BAAANQAECgQIBwABNQAECggIGgARAMAgAA==.',
Ry='Rylankneth:BAAANQADCgYIBgAAAA==.',
['Rî']='Rîce:BAABNQAECoEUAAIVAAcKKSBFCQBwAgAVAAcKKSBFCQBwAgAAAA==.',
Sa='Sabelorn:BAABNQAECoEiAAMjAAkKexj7HwCvAgAjAAkKexj7HwCvAgAdAAUKFAjhMQDGAAAAAA==.Sacredfear:BAABNQAECoErAAMIAAkKcyBFHAD+AgAIAAkKcyBFHAD+AgAJAAIKHA2FWwBmAAAAAA==.Sacredshammy:BAABNQAECoEbAAMRAAkKkxUiOQBTAgARAAkKkxUiOQBTAgAQAAUKeQ+AugDvAAABNQAECgkJKwAIAHMgAA==.Sandayy:BAACNQAFFIEjAAMWAAcKyB+eBQDcAQAWAAUKlx6eBQDcAQASAAQKuyG1CQCDAQA1AAQKgS0AAxYACQoZJmsLABIDABYACApIJWsLABIDABIABwpTJictAMUCAAAA.Sathion:BAAANQADCggIDAABNQAECggIHAAiAEsjAA==.Satsao:BAAANQADCgEIAQAAAA==.Sawario:BAAANQADCgMIAwAAAA==.',
Sc='Scalekyle:BAAANQAECgcIDQAAAA==.Screwheals:BAAANQAECgYIDQABNQAECgkJKQAgAIsRAA==.Scrotobaginz:BAAANQAECgEIAQAAAA==.',
Se='Sellene:BAACNQAFFIEkAAIbAAgKYCQ1AADjAgAbAAgKYCQ1AADjAgA1AAQKgSsAAhsACQqzJBAKAAwDABsACQqzJBAKAAwDAAAA.Sellina:BAAANQAECgIIAgABNQAFFAgIJAAbAGAkAA==.Seneriya:BAAANQAECgcIBwAAAA==.Senorbang:BAABNQAECoEXAAISAAcKGxUBdgD1AQASAAcKGxUBdgD1AQAAAA==.Sep:BAABNQAECoEhAAIRAAkK0RznIwC4AgARAAkK0RznIwC4AgAAAA==.Serenashadow:BAAANQADCgUIBQAAAA==.',
Sh='Shadowflare:BAAANQADCgcIEwAAAA==.Shadowplay:BAAANQAECggIBgAAAA==.Shaggsalt:BAAANQAECggIAwAAAA==.Shakeysha:BAAANQAECgcIBwAAAA==.Shalth:BAAANQADCggICgAAAA==.Shaolinhunk:BAABNQAECoEeAAITAAkK3Q4MJgDBAQATAAkK3Q4MJgDBAQAAAA==.Sharks:BAACNQAFFIEGAAIgAAMKiBB5FwC2AAAgAAMKiBB5FwC2AAA1AAQKgSkAAiAACQrUHEMcALUCACAACQrUHEMcALUCAAAA.Shawshanks:BAAANQAECgQIBAAAAA==.Shazzman:BAAANQAECgMICAAAAA==.Shelandria:BAACNQAFFIEdAAMMAAgK5Q1oAQBRAgAMAAcK0QxoAQBRAgADAAQKaw4pCABLAQA1AAQKgToAAwMACQqWJBYCALQDAAMACQp3JBYCALQDAAwACQoAHpIFACYDAAAA.Shiko:BAEANQAECggIEgABNQAFFAIIBAABAAAAAA==.Shiroee:BAAANQABCggIBwABNQAECggIHAAYAP8SAA==.Shoda:BAACNQAFFIEcAAMWAAYKPBgbCgB4AQAWAAUK3hAbCgB4AQASAAMK1CI/DwAlAQA1AAQKgS4AAxYACQpcJbEQANACABYACAo4I7EQANACABIABgp+JcFaADoCAAAA.Shootrmcgávn:BAABNQAECoEYAAISAAcKNiPjLgC+AgASAAcKNiPjLgC+AgAAAA==.Shreker:BAACNQAFFIEGAAIFAAMKRh/CFAAjAQAFAAMKRh/CFAAjAQA1AAQKgR0AAgUACQpdHd01AG4CAAUACQpdHd01AG4CAAAA.',
Si='Sidchatic:BAAANQADCgEIAQAAAA==.Sidebo:BAAANQAECgEIAQAAAA==.Sinhunter:BAABNQAECoEeAAIlAAgKKhhPBAB/AgAlAAgKKhhPBAB/AgAAAA==.Sirn:BAAANQAECgQIBQAAAA==.Sitonmytotem:BAAANQADCgQIBQABNQAECgQIBAABAAAAAA==.',
Sj='Sjp:BAAANQAECgIIAgABNQAECggIEwAeADoYAA==.',
Sk='Skeetoo:BAABNQAECoEfAAISAAkKIRvOMQC0AgASAAkKIRvOMQC0AgAAAA==.Skeetwo:BAAANQADCggICAABNQAECgkJHwASACEbAA==.Skiera:BAAANQAECgIIAgABNQAECgkJJwAKADUhAA==.Skiplegs:BAABNQAECoEdAAIZAAkKjBHCigDdAQAZAAkKjBHCigDdAQAAAA==.Skorpeo:BAAANQAECgYIDQAAAA==.',
Sl='Slimes:BAAANQADCgIIAgAAAA==.Slimxx:BAAANQAECgcICQAAAA==.',
Sm='Smargendk:BAAANQADCgYIBwABNQAFFAcIGgALAJ8dAA==.Smargenrog:BAACNQAFFIEaAAILAAcKnx1TAACYAgALAAcKnx1TAACYAgA1AAQKgScAAgsACQpxJVECAIgDAAsACQpxJVECAIgDAAAA.Smokeknight:BAAANQADCgEIAQAAAA==.',
Sn='Snaven:BAAANQAECgUIEAAAAA==.Sneggs:BAAANQADCggIGQAAAA==.Snifellz:BAABNQAECoEcAAIiAAgKSyOEBAAgAwAiAAgKSyOEBAAgAwAAAA==.Snifflez:BAAANQAECgQICAABNQAECggIHAAiAEsjAA==.Snipermonkey:BAABNQAECoEjAAISAAkKWyJNEQBIAwASAAkKWyJNEQBIAwAAAA==.Snowstep:BAAANQADCgQIBAAAAA==.',
So='Soiled:BAAANQAECgEIAQAAAA==.Solidshaft:BAAANQAECgIIAwAAAA==.Solikar:BAAANQADCggIEwAAAA==.Sopheia:BAAANQAECgQIBQAAAA==.Soul:BAACNQAFFIEGAAINAAMKzBPkKwDuAAANAAMKzBPkKwDuAAA1AAQKgSwAAg0ACQo/IeMnADgDAA0ACQo/IeMnADgDAAAA.',
Sp='Spek:BAACNQAFFIEOAAMRAAYKEgqpBwC6AQARAAYKEgqpBwC6AQAQAAIKrRaCGwCnAAA1AAQKgSUAAxAACQqTIvQYABwDABAACQqTIvQYABwDABEAAgoWEWTsAGAAAAAA.Split:BAABNQAECoEfAAMMAAgKARkjGAAKAgAMAAcKchgjGAAKAgADAAQKkRSqVAAaAQAAAA==.Springonion:BAACNQAFFIEGAAIPAAYKRQcmCAC4AQAPAAYKRQcmCAC4AQA1AAQKgRcAAg8ACQqKE/UsAJgCAA8ACQqKE/UsAJgCAAE1AAUUCAgfABEAxw0A.',
Sq='Squidward:BAACNQAFFIELAAIGAAUKyhpaBQC9AQAGAAUKyhpaBQC9AQA1AAQKgTAAAgYACQrKIo0FAHMDAAYACQrKIo0FAHMDAAAA.',
Ss='Ssbraun:BAAANQADCgUJBQAAAA==.',
St='Standardhors:BAAANQAECgIIAgABNQAECgkJLAAQAAwmAA==.Steadchi:BAAANQAECgYJBgAAAA==.Steadyy:BAAANQABCgQIBAAAAA==.Steakburrito:BAAANQAECgQICAAAAA==.Stedk:BAACNQAFFIEbAAIgAAYKIiTNAQB4AgAgAAYKIiTNAQB4AgA1AAQKgSYAAiAACQqXJlYCAMkDACAACQqXJlYCAMkDAAAA.Stepally:BAABNQAFFIEIAAIfAAYKhRJuAwCOAQAfAAYKhRJuAwCOAQAAAA==.Steven:BAAANQAECgYIDgABNQAFFAQIDwAQAD8PAA==.Strongmace:BAAANQAECgEIAQAAAA==.Strongshift:BAAANQAECgEIAQABNQAECgEIAQABAAAAAA==.Stygwyggyr:BAABNQAECoEaAAIMAAkKVQ1NFwATAgAMAAkKVQ1NFwATAgAAAA==.',
Su='Suebird:BAAANQAECggIDQABNQAFFAMIBgAFAEYfAA==.Sugarzcoat:BAABNQAECoEZAAMRAAkKGR19HADfAgARAAkKGR19HADfAgAQAAEK/QIuMwEiAAAAAA==.Sulphurous:BAAANQAECgcIEAAAAA==.Sunlight:BAAANQAECgMIBQAAAA==.Supdudejr:BAABNQAECoEfAAIeAAgKyhkvXQBXAgAeAAgKyhkvXQBXAgAAAA==.Supernovi:BAAANQADCggICAAAAA==.',
Sw='Sweetstache:BAAANQABCgQIBgAAAA==.Swiftus:BAAANQADCgEIAQAAAA==.Swippin:BAAANQADCgYIBwABNQAECggIHQAYAD4jAA==.',
Sy='Syenite:BAAANQAECgUIBQAAAA==.Sykomike:BAABNQAECoEmAAMSAAkKLh+vFQAuAwASAAkKLh+vFQAuAwAWAAEKxAJUhgAoAAAAAA==.Sylarria:BAAANQADCgcIDQAAAA==.Syler:BAACNQAFFIENAAIDAAUKWBGLBgB4AQADAAUKWBGLBgB4AQA1AAQKgSoAAgMACQpyI+EGAFADAAMACQpyI+EGAFADAAAA.Sylár:BAAANQAECgUIDQAAAA==.Symbol:BAAANQABCgQIBAAAAA==.Syreal:BAAANQADCgYICAAAAA==.',
['Sä']='Säcred:BAAANQAECgQICQABNQAECgkJKwAIAHMgAA==.',
Ta='Tahlia:BAABNQAECoEsAAIbAAkKCyCXBgBGAwAbAAkKCyCXBgBGAwAAAA==.Talren:BAAANQAECgcIEwAAAA==.Talìa:BAABNQAECoEfAAIGAAgKDhPOIAAoAgAGAAgKDhPOIAAoAgAAAA==.Tannadà:BAABNQAECoEVAAIfAAgK/CHxDgCIAgAfAAgK/CHxDgCIAgAAAA==.Tasari:BAACNQAFFIEjAAIVAAcK4CIZAADgAgAVAAcK4CIZAADgAgA1AAQKgS0AAhUACQo7JocAAN8DABUACQo7JocAAN8DAAAA.Taurenadin:BAAANQADCgIIAgAAAA==.Tayson:BAAANQADCggICQAAAA==.Tazzdingo:BAAANQADCgEIAQAAAA==.',
Te='Tekain:BAAANQAECgEIAQAAAA==.Tequilla:BAAANQADCggICgAAAA==.Terryn:BAAANQAECgUICQAAAA==.Tesia:BAAANQADCgcIEwAAAA==.',
Th='Thedeadlypug:BAAANQAECgQIBAAAAA==.Theeripper:BAAANQAECgUIDgAAAA==.Thrashwar:BAABNQAECoEYAAIeAAcKWBd2hADsAQAeAAcKWBd2hADsAQAAAA==.Thrustie:BAABNQAECoEhAAMMAAgKyBRUFQAoAgAMAAgKyBRUFQAoAgADAAMKYAoHbQCrAAAAAA==.Thusios:BAABNQAECoEdAAIaAAgKoSIUAwAaAwAaAAgKoSIUAwAaAwAAAA==.',
Ti='Tiazz:BAAANQADCgUIBQAAAA==.Tichu:BAAANQAECgUICgAAAA==.Tiekho:BAAANQADCgUIBQAAAA==.Tifaun:BAAANQADCgUIBQAAAA==.Tifelia:BAAANQAECgMIAwAAAA==.Tigorain:BAAANQADCgcIBgAAAA==.Tizirk:BAABNQAECoEZAAIbAAkKwBp+DADpAgAbAAkKwBp+DADpAgAAAA==.',
Tk='Tkdtwo:BAABNQAECoEjAAIZAAgKrBudXgBSAgAZAAgKrBudXgBSAgAAAA==.',
To='Toastybutter:BAAANQADCgYIDAAAAA==.Tonyz:BAAANQAECggIEQAAAA==.Torrak:BAABNQAECoErAAMiAAkKEB60BgDVAgAiAAgKhiC0BgDVAgAeAAMK9AweAAGqAAAAAA==.Torrential:BAAANQADCgYIBgAAAA==.Torthie:BAACNQAFFIEjAAMNAAcKQRySBQBDAgANAAYKoh+SBQBDAgAOAAEK+QckCwBVAAA1AAQKgS0AAw0ACQqQJO0bAF4DAA0ACQqQJO0bAF4DAA4AAQqmIYY1AE4AAAAA.Tothdk:BAAANQAFFAcIAQAAAA==.Toxaaris:BAAANQADCgIIAgAAAA==.',
Tr='Trale:BAAANQADCgQIBAAAAA==.Treason:BAAANQADCgYIBwABNQAECgQIBgABAAAAAA==.Treeage:BAAANQAECgIIBAAAAA==.Tripp:BAAANQAECgMIBgAAAA==.Trisao:BAAANQABCgMIAgABNQAECggIHQAIAMEXAA==.Troah:BAAANQADCgQIBAAAAA==.Troeg:BAAANQABCgUIAwAAAA==.Trollerella:BAAANQADCgQIBAABNQAECgkJJAAGAKAZAA==.Trollzealot:BAAANQAECgMIAwAAAA==.Tronxx:BAAANQADCgQIBAAAAA==.Troxigar:BAAANQAECgcIEwAAAA==.Trumoo:BAAANQADCgEIAQAAAA==.',
Ts='Tsukajara:BAAANQAECggIDAAAAA==.',
Tu='Tullyspring:BAAANQADCggJDwAAAA==.Turkeysub:BAAANQADCggIGQAAAA==.',
Tv='Tverdydh:BAAANQAECgYIDwAAAA==.Tverdydk:BAAANQAECgcIEwAAAA==.Tverdydruid:BAAANQAECgMIAwAAAA==.',
Tw='Twertlekat:BAABNQAECoEgAAISAAgKSBbMUABVAgASAAgKSBbMUABVAgAAAA==.Twinkiez:BAAANQAECgQICAABNQAECgkJGQARABkdAA==.Twistkun:BAAANQAECgUIBQAAAA==.',
Un='Unclehog:BAAANQAECgYIEgAAAA==.Unfixable:BAAANQAECgQJBwABNQAFFAYIGgABAAAAAQ==.Unplayable:BAAANQAFFAYIGgAAAQ==.Unusualhorse:BAABNQAECoEsAAMQAAkKDCaCAQDrAwAQAAkKDCaCAQDrAwARAAcKFB5QOABWAgAAAA==.',
Ur='Urbanii:BAAANQADCgEIAQAAAA==.',
Uu='Uunfar:BAABNQAECoErAAIRAAkK+yWEAQDJAwARAAkK+yWEAQDJAwAAAA==.',
Va='Valby:BAAANQABCgYICAAAAA==.Valedia:BAABNQAECoEYAAIEAAgKvBEiIwDyAQAEAAgKvBEiIwDyAQAAAA==.Valn:BAAANQAECgcIEAAAAA==.Valtross:BAAANQAECgMIBgAAAA==.Vangough:BAABNQAECoErAAIeAAkKlRxFNwDQAgAeAAkKlRxFNwDQAgAAAA==.Vapor:BAAANQAECgEIAQAAAA==.Vashanis:BAAANQADCgQIBAABNQAECggIGgAdAKgZAA==.Vayu:BAAANQADCgQIBAAAAA==.',
Ve='Veloshock:BAAANQAECgEIAQAAAA==.Velvetvixen:BAABNQAECoEaAAIGAAcKMRlKIgAZAgAGAAcKMRlKIgAZAgAAAA==.',
Vi='Violaswamp:BAAANQADCgYICgAAAA==.Viper:BAACNQAFFIEGAAIDAAMKNQ++CwDsAAADAAMKNQ++CwDsAAA1AAQKgSsAAwMACQrYHiMLABcDAAMACQrYHiMLABcDAAwAAwoxE3A6AL4AAAAA.',
Vl='Vlad:BAAANQAECggIEAAAAA==.',
Vo='Voodooblady:BAAANQADCgEIAQAAAA==.Voreâu:BAAANQADCgEIAQAAAA==.Vorpmi:BAAANQAECgUIBQABNQAECgkJIgAKALwVAA==.Vosslar:BAABNQAECoEhAAIfAAgKMCKbCAD6AgAfAAgKMCKbCAD6AgAAAA==.Vosslarr:BAAANQAECgQIBAAAAA==.',
Vv='Vvarden:BAAANQAECgQIBgAAAA==.',
['Vî']='Vîper:BAAANQAECgQIBwAAAA==.',
Wa='Waarrlockk:BAACNQAFFIEdAAQIAAcKQhlsCAC1AQAIAAUKRBVsCAC1AQAJAAIKPCPNBADGAAAHAAEK2xP3CgBJAAA1AAQKgS4ABAkACQptJYsCACcDAAkACQqcH4sCACcDAAgABwrGJGYmANMCAAcAAQpDI5wgAF0AAAAA.Walrusrider:BAAANQAECggIEwAAAA==.Wang:BAABNQAECoEcAAITAAkKfRq7GABVAgATAAkKfRq7GABVAgAAAA==.Warbird:BAABNQAECoEjAAIjAAgKPBr7KgBeAgAjAAgKPBr7KgBeAgAAAA==.Warhmonger:BAAANQADCggJCQAAAA==.Wassy:BAABNQAECoEhAAIXAAgKHyVoAwBiAwAXAAgKHyVoAwBiAwAAAA==.Watharaim:BAAANQAECgQIBAABNQAECggIKwAZAA8OAA==.',
We='Wedlock:BAAANQADCggICAAAAA==.Wemgobyama:BAACNQAFFIEUAAIWAAYKQCAwAwA4AgAWAAYKQCAwAwA4AgA1AAQKgTIABBYACQqqJCsEAIsDABYACQqMJCsEAIsDABIAAgqaI9AGAbEAACUAAQpWAEUTABIAAAAA.',
Wh='Whispy:BAAANQABCgIIAgAAAA==.Whm:BAAANQAECgQIBQAAAA==.Whobe:BAABNQAECoEqAAIMAAkKxhOKDwBxAgAMAAkKxhOKDwBxAgAAAA==.',
Wi='Witherfang:BAAANQAECgMIBQAAAA==.Wizsera:BAAANQAECgIIAgABNQAECgcIIQAQAPYdAA==.Wizshock:BAABNQAECoEhAAIQAAcK9h3KTgAPAgAQAAcK9h3KTgAPAgAAAA==.',
Wn='Wnred:BAACNQAFFIEeAAMnAAcKHh+/AQArAgAnAAYKmB6/AQArAgAXAAUKiB4ZAwCzAQA1AAQKgS4AAycACQrCJWcBAHQDACcACQprJGcBAHQDABcACAp+JX4GAA0DAAAA.',
Wo='Wombly:BAAANQAECgQIBAAAAA==.Womboree:BAABNQAECoEmAAIjAAgKyiJTEwAYAwAjAAgKyiJTEwAYAwAAAA==.Wonderful:BAAANQADCgcIAgAAAA==.Woobie:BAAANQADCgEIAQAAAA==.Wos:BAAANQAECgYICwAAAA==.',
Xa='Xanarius:BAABNQAECoEaAAIdAAgKqBmwDABeAgAdAAgKqBmwDABeAgAAAA==.',
Xc='Xckz:BAAANQAECgUICAAAAA==.',
Ye='Yellowslice:BAAANQADCgYIBgAAAA==.Yeofp:BAAANQADCgUIBQAAAA==.',
Yk='Ykime:BAAANQADCgEIAQAAAA==.',
Ym='Ymr:BAAANQAECgYIBgAAAA==.',
Yu='Yukarna:BAABNQAECoEmAAIDAAkK3SFVBQBpAwADAAkK3SFVBQBpAwAAAA==.Yukionná:BAAANQADCgYJBgABNQAECgcIFAAZAAccAA==.',
Za='Zaafkiel:BAABNQAECoEeAAQZAAgKjBWtvwBkAQAZAAcKIA6tvwBkAQAfAAUK9hbHNwAAAQAPAAUKZwX3tQDnAAAAAA==.Zabuza:BAAANQADCgUIBQAAAA==.Zanaroth:BAAANQAECgUIBwAAAA==.Zandrissil:BAEANQADCgYIBgABNQAECgYIEgABAAAAAA==.Zapadude:BAAANQADCgcIDgABNQAECgQIBQABAAAAAA==.Zaraeywa:BAEANQADCgcIBwABNQAECgYIEgABAAAAAA==.Zarafie:BAEANQADCggIFAABNQAECgYIEgABAAAAAA==.Zarantharia:BAEANQADCgMIAwABNQAECgYIEgABAAAAAA==.Zaraphym:BAEANQAECgYIEgAAAA==.Zarazlow:BAEANQADCgQIBAABNQAECgYIEgABAAAAAA==.Zarreh:BAAANQADCggIHQAAAA==.',
Ze='Zephyrine:BAAANQADCgQIBAAAAA==.Zetec:BAAANQAECggICAAAAA==.Zexan:BAAANQAECgEIAgAAAA==.',
Zh='Zhuzhu:BAABNQAECoEZAAQhAAcKyBUeEQD+AAAFAAYKRRlibACiAQAhAAQKHxUeEQD+AAAEAAIKHwVkYgBPAAAAAA==.',
Zi='Zigy:BAABNQAECoErAAIiAAkK+iQ+AQC4AwAiAAkK+iQ+AQC4AwAAAA==.Zinblix:BAAANQABCgIIAgAAAA==.',
Zo='Zoeý:BAAANQADCgcIBwAAAA==.Zombie:BAAANQAECgUIEgAAAA==.',
Zu='Zukko:BAAANQAECggIEQAAAA==.Zulkaris:BAAANQADCggICAAAAA==.Zuroxxar:BAEANQAECgIJAgABNQAECgYIEgABAAAAAA==.Zuwitsudh:BAAANQADCgQIBAAAAA==.',
Zy='Zynny:BAABNQAECoEdAAIKAAgKtBU2MADrAQAKAAgKtBU2MADrAQAAAA==.',
['Zë']='Zëll:BAAANQAECgEIAQAAAA==.',
['Åa']='Åa:BAAANQAECgIIBAABNQAECggIJgABAAAAAA==.',
['Èp']='Èpídemíc:BAAANQABCggIDwAAAA==.',
['Ðo']='Ðolo:BAAANQADCggIFQABNQAECggIHwAGAA4TAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
