local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'DeathKnight-Unholy','Shaman-Restoration','Paladin-Holy','Paladin-Protection','Unknown-Unknown','Shaman-Elemental','Shaman-Enhancement','DemonHunter-Devourer','Mage-Arcane','Druid-Restoration','Hunter-BeastMastery','Hunter-Marksmanship','Rogue-Assassination','Warrior-Arms','Monk-Mistweaver','Mage-Frost','Priest-Holy','Priest-Discipline','Priest-Shadow','DeathKnight-Frost','Druid-Balance','DeathKnight-Blood','Warlock-Destruction','Warlock-Demonology','Warrior-Fury','Paladin-Retribution','DemonHunter-Havoc','Hunter-Survival','Monk-Windwalker','DemonHunter-Vengeance','Rogue-Subtlety','Evoker-Preservation','Evoker-Devastation','Evoker-Augmentation','Druid-Guardian','Warlock-Affliction','Druid-Feral','Mage-Fire','Rogue-Outlaw','Monk-Brewmaster','Warrior-Protection',}
local provider = {region='US',realm='Icecrown',name='US',type='weekly',zone=53,date='2026-10-06',data={Aa='Aaronstorm:BAAANQAECgYIDwAAAA==.',
Ac='Acesaber:BAAANQABCgIJBAAAAA==.Ackward:BAABNQAECoEhAAIBAAgK/iBqGgDTAgABAAgK/iBqGgDTAgAAAA==.Ackwarder:BAAANQAECgYIEAABNQAECggIIQABAP4gAA==.Acrylia:BAAANQAECgIIAwAAAA==.',
Ae='Aeryx:BAACNQAFFIEGAAICAAMK+gWdFQDOAAACAAMK+gWdFQDOAAA1AAQKgScAAgIACQrwFfBEACICAAIACQrwFfBEACICAAAA.',
Ah='Ahridne:BAAANQAECgUICwAAAA==.Ahsôka:BAAANQAECgQIDQAAAA==.',
Ak='Akisa:BAAANQADCgIIAgAAAA==.',
Al='Alagorn:BAAANQADCggJDQAAAA==.Alamage:BAAANQADCgUIBQAAAA==.Alantis:BAAANQADCgQIBAAAAA==.Alinael:BAAANQADCggIEgAAAA==.Alisterr:BAAANQAECgcIDAAAAA==.Alistra:BAAANQADCggIDQAAAA==.Alrera:BAAANQAECgQIBAAAAA==.Alynaa:BAAANQAECgUIDAAAAA==.',
Am='Amadixiechic:BAAANQADCggIDAAAAA==.Amafrey:BAABNQAECoEfAAMDAAgKTwuxawCtAQADAAgKTwuxawCtAQAEAAMK4RJxSgCWAAAAAA==.Ambush:BAAANQADCggIEgAAAA==.Amishbert:BAAANQADCggICAAAAA==.Amo:BAAANQAECggIJgAAAQ==.Amocat:BAAANQAECgUICAABNQAECggIJgAFAAAAAQ==.Amoresto:BAAANQADCgYIBgABNQAECggIJgAFAAAAAQ==.Amoret:BAAANQADCgQIBQABNQAECggIJgAFAAAAAQ==.',
An='Ancestraljr:BAABNQAECoEWAAQCAAkKYR58KQCbAgACAAgKYB18KQCbAgAGAAUKmRr4iQBaAQAHAAMKFhOWJQDGAAAAAA==.Andaa:BAAANQADCgUIBQAAAA==.Andalocke:BAABNQAECoEgAAIIAAkKbRmNEgDBAgAIAAkKbRmNEgDBAgAAAA==.Andalucia:BAAANQAECgMIAwAAAA==.Andraka:BAAANQAECgUIBgAAAA==.Andrew:BAAANQADCgQIBAAAAA==.Animalstyle:BAAANQAECgcIBwABNQAFFAgILAAJANIjAA==.Anitapotion:BAAANQADCgUICAAAAA==.Annalucia:BAAANQADCgEIAQAAAA==.Annboleyn:BAAANQAECgEIAQAAAA==.',
Ap='Aporkchop:BAAANQAECgcICQAAAA==.',
Ar='Arabelle:BAABNQAECoEZAAIKAAYK4A1NOQAeAQAKAAYK4A1NOQAeAQAAAA==.Arcatraz:BAAANQADCgEIAQABNQAECgIIBAAFAAAAAA==.Archurroso:BAAANQADCgUJBQAAAA==.Ares:BAAANQADCgcIEQAAAA==.Ariens:BAABNQAECoEdAAMLAAgKeRehUQBSAgALAAcKoRqhUQBSAgAMAAIKpgbnbQBSAAAAAA==.Arlaeya:BAAANQAECgEIAQAAAA==.Arocyra:BAAANQABCgYIDAAAAA==.Artemislux:BAABNQAECoEgAAMMAAkKkxo6GQB0AgAMAAkKwBk6GQB0AgALAAMK/Bfe9QDjAAAAAA==.Aránda:BAAANQAECgMIAwABNQAECgQIBQAFAAAAAA==.',
As='Asline:BAAANQAECgUIBQAAAA==.Astelle:BAABNQAECoEhAAINAAgKuxjHIQBKAgANAAgKuxjHIQBKAgAAAA==.Astralxeth:BAAANQAECgUIBQAAAA==.Astronoth:BAAANQADCgYICQAAAA==.',
At='Atagos:BAABNQAECoEZAAIOAAcKQRRWlgC8AQAOAAcKQRRWlgC8AQAAAA==.Athanor:BAAANQAECgQICAABNQAECggIHQAPAFQOAA==.Atonementism:BAAANQAECgUIEQABNQAECgUIBQAFAAAAAA==.',
Au='Aurawa:BAAANQAECgIIAgAAAA==.Aurus:BAAANQAECgEIAQAAAA==.Austin:BAAANQAECggIEgAAAA==.Autumnn:BAAANQAECgcIBwAAAA==.',
Av='Avannia:BAAANQADCgcICwAAAA==.Avaren:BAABNQAECoEmAAIQAAkKeSI8AQB1AwAQAAkKeSI8AQB1AwABNQAECgkJMQARALckAA==.Avarens:BAAANQAECgcIDQABNQAECgkJMQARALckAA==.Avawen:BAABNQAECoExAAQRAAkKtyQFAwCwAwARAAkKISQFAwCwAwASAAgKBh+oAgDUAgATAAEKeBB2bAA1AAAAAA==.Averyg:BAAANQADCgYJFAAAAA==.',
Aw='Awhbeans:BAEBNQAECoEXAAMCAAcKMiArTgD/AQACAAYKZR8rTgD/AQAGAAEKJRY4BgFHAAAAAA==.',
Ax='Axtafal:BAABNQAECoEXAAIUAAcKViAWHACDAgAUAAcKViAWHACDAgAAAA==.',
Ay='Ayla:BAAANQADCgcIDgAAAA==.',
['Aá']='Aáronstorm:BAAANQADCggICgABNQAECgYIDwAFAAAAAA==.',
Ba='Babaganouj:BAAANQADCgYIFgAAAA==.Baineblood:BAABNQAECoEZAAIVAAgKvRqeKgBgAgAVAAgKvRqeKgBgAgAAAA==.Bainelock:BAAANQAECgQIBgAAAA==.Bambislayer:BAAANQAECggIBwAAAA==.Bandaidhealz:BAAANQAECgUICgAAAA==.Bandledin:BAAANQAECgYIDwAAAA==.Barelilus:BAAANQAECgMJAwAAAA==.Barthus:BAAANQAECgIIAgABNQAECgUICgAFAAAAAA==.Baseballman:BAAANQAECgUIBQABNQAECgkJMQARALckAA==.Bassproshops:BAACNQAFFIEPAAILAAYK0hY5AwASAgALAAYK0hY5AwASAgA1AAQKgS8AAwsACQqII4kTADoDAAsACQpPIokTADoDAAwABQrRHtwtALYBAAAA.Baulder:BAAANQAECgIIAgAAAA==.',
Be='Bear:BAAANQAECgEIAQABNQAFFAYIHQAWAEYmAA==.Belmyridon:BAAANQADCgcICgAAAA==.Belzebozz:BAAANQADCgMIAwAAAA==.Bendecido:BAAANQADCggIDQAAAA==.',
Bf='Bfc:BAAANQADCgUIBQAAAA==.',
Bi='Biaxident:BAABNQAECoEaAAMXAAYKtiOZCABqAgAXAAYKtiOZCABqAgAYAAMKXBZJ4gDYAAAAAA==.Bigboy:BAAANQAECgYIDQAAAA==.Bigjoe:BAAANQAECgUJBQAAAA==.Birdyy:BAAANQADCgYICgABNQADCggJDgAFAAAAAA==.',
Bj='Bjorne:BAABNQAECoE6AAIZAAgKBBJcCgABAgAZAAgKBBJcCgABAgAAAA==.',
Bl='Blammo:BAAANQADCgUIBQAAAA==.Blastoise:BAAANQAECgEIAgAAAA==.Blazter:BAABNQAECoEXAAIaAAgKOBfVcwAYAgAaAAgKOBfVcwAYAgAAAA==.Bleo:BAAANQAECgEIAQAAAA==.Blueberryjam:BAAANQADCggIDgABNQAECggIGwAJAOMJAA==.Blututh:BAABNQAECoEdAAIbAAgK6A8GMwDhAQAbAAgK6A8GMwDhAQAAAA==.Blïght:BAAANQADCggIHAAAAA==.',
Bm='Bmjr:BAABNQAECoElAAIOAAkK2SMTCgCeAwAOAAkK2SMTCgCeAwAAAA==.',
Bo='Bodhran:BAABNQAECoEvAAIGAAkKahczMgCLAgAGAAkKahczMgCLAgAAAA==.Bombadill:BAAANQAECgEIAwAAAA==.Bonewings:BAAANQADCggICQAAAA==.Boombang:BAAANQAECgEIAQAAAA==.',
Br='Breezerk:BAABNQAECoEoAAIOAAkKtSB6FQBaAwAOAAkKtSB6FQBaAwAAAA==.Brill:BAAANQABCgIIAgAAAA==.Brudrushah:BAAANQAECgQIBAABNQAECgYIFAAcAEcgAA==.',
Bu='Bubblebetuna:BAAANQABCgIIAgABNQABCgYIBgAFAAAAAA==.Buggerella:BAAANQAECgIIAgAAAA==.Bullithead:BAAANQADCggICQAAAA==.Bulrog:BAABNQAECoEiAAIdAAkKPhriFACJAgAdAAkKPhriFACJAgAAAA==.Bumpey:BAAANQADCgUICQABNQADCggIDAAFAAAAAA==.Bus:BAACNQAFFIETAAIWAAYKECLBAgBNAgAWAAYKECLBAgBNAgA1AAQKgSEAAhYACQr6Jd8CAL8DABYACQr6Jd8CAL8DAAAA.Bushlite:BAABNQAECoEcAAMaAAkKXxJHfgD9AQAaAAkKXxJHfgD9AQAEAAMKKwbjTwB3AAAAAA==.',
By='Byni:BAAANQAECgUIEAAAAA==.',
['Bá']='Bádabing:BAAANQABCgQIBgAAAA==.',
Ca='Calorenn:BAAANQADCgYICgABNQAECgcIGgAIAHoYAA==.Caluu:BAABNQAECoEvAAMaAAkKsSCyMADoAgAaAAkK3hyyMADoAgAEAAIKDhkQTQCIAAAAAA==.Cankles:BAABNQAECoEYAAIaAAgKThkuXwBQAgAaAAgKThkuXwBQAgAAAA==.Canolope:BAAANQADCgYIBgABNQAECgcJDgAFAAAAAA==.Cantcant:BAAANQAECgQICAABNQAECgkJMQARALckAA==.Catfood:BAABNQAECoEVAAQIAAgKix42JAAGAgAIAAcK4xo2JAAGAgAbAAQKfB+NVAADAQAeAAEKVQvuLAArAAAAAA==.Cattibriee:BAAANQADCgMJAwAAAA==.Cattibrië:BAAANQAECggIBAAAAA==.',
Ce='Cece:BAAANQAECgQIBAABNQAECgUICwAFAAAAAA==.Celedhring:BAABNQAECoE6AAMaAAgKBxaBbwAjAgAaAAgKxRSBbwAjAgAEAAIKyRhVSwCSAAAAAA==.',
Ch='Chainsaww:BAAANQADCgMIAwAAAA==.Chaktaw:BAABNQAECoEgAAMSAAcKQxryBQAhAgASAAcKQxryBQAhAgATAAEKqxLaaQA6AAAAAA==.Chatubaholy:BAAANQAECgQIBQAAAA==.Chayito:BAABNQAECoEoAAMIAAkK9hkpFwCOAgAIAAkK9hkpFwCOAgAeAAUKqQ0fGAD8AAAAAA==.Cheezi:BAAANQAECgQIBAAAAA==.Chickenism:BAECNQAFFIEnAAIVAAgKWR+MAAAVAwAVAAgKWR+MAAAVAwA1AAQKgTAAAhUACQrbJpUAAPsDABUACQrbJpUAAPsDAAAA.Chiknsmoothi:BAAANQADCgYICwAAAA==.Chirpa:BAAANQADCgMIAwAAAA==.Chiwallow:BAAANQAECgQIBAAAAA==.Chloe:BAAANQAECgUIDgAAAA==.Chowtime:BAABNQAECoEhAAIJAAgKFRj3lgA1AgAJAAgKFRj3lgA1AgAAAA==.Chromium:BAABNQAECoEdAAIEAAgKHB4/DgCTAgAEAAgKHB4/DgCTAgAAAA==.Chrysanthia:BAAANQADCgEIAQAAAA==.',
Ci='Cinderstorm:BAAANQADCgYICQAAAA==.Cirilla:BAAANQABCgIIAgAAAA==.Citronia:BAAANQAECgYIDgAAAA==.',
Cl='Clamps:BAABNQAECoEWAAMCAAgK8iCHMAB5AgACAAgK8iCHMAB5AgAHAAEK/AU6MQAzAAAAAA==.Clandmage:BAAANQAECgYIBgAAAA==.Clandon:BAACNQAFFIEsAAISAAgKPx4MAAAnAwASAAgKPx4MAAAnAwA1AAQKgS4AAhIACQrYJhAAAAcEABIACQrYJhAAAAcEAAAA.Clawsy:BAAANQAECgUIBQABNQAECgYIDQAFAAAAAA==.Claxton:BAABNQAECoEqAAMZAAkKYBf+BQCKAgAZAAkKYBf+BQCKAgAOAAYKfQnVxgA2AQAAAA==.Clomari:BAAANQAECgcIEAAAAA==.Clynlyn:BAAANQAECgMIAwAAAA==.',
Co='Cole:BAAANQADCgcIBwAAAA==.Commietotem:BAAANQAECgIIBAAAAA==.Concepts:BAABNQAECoEkAAMaAAgKxh1POADMAgAaAAgKxh1POADMAgADAAMKJg9e0gCvAAAAAA==.Conjax:BAAANQAECgEIAQAAAA==.Costcomember:BAAANQADCgcICQAAAA==.Coyn:BAAANQADCgQIBQABNQADCgUIBQAFAAAAAA==.',
Cr='Crashout:BAAANQAECgEIAgAAAA==.Crison:BAAANQADCgcIFAABNQAECgYIDQAFAAAAAA==.Cron:BAAANQADCgcIBwAAAA==.Croneos:BAAANQAECgQICAAAAA==.Cross:BAABNQAECoEqAAMEAAgKRRkyFgAlAgAEAAgKRRkyFgAlAgAaAAIKrRBiSwFkAAAAAA==.Crucifi:BAAANQAECggIBgAAAA==.Cryssalis:BAAANQADCgEIAQAAAA==.',
Cu='Cudz:BAAANQAECgUIDwAAAA==.Curl:BAAANQAECgUIDgAAAA==.',
Cy='Cyn:BAAANQADCgEIAQAAAA==.Cytanous:BAAANQADCgYIEgAAAA==.',
Da='Daddydeath:BAABNQAECoEXAAITAAcKXBOLKQC0AQATAAcKXBOLKQC0AQAAAA==.Dadrex:BAAANQADCgMIAwAAAA==.Daesyn:BAAANQADCgEIAQAAAA==.Daffodyll:BAAANQAECgIIAgAAAA==.Dagonfive:BAAANQAECgYIDwAAAA==.Dahrla:BAAANQAECgYIEQAAAA==.Daisyann:BAABNQAECoEcAAIZAAcKDgfFFAAtAQAZAAcKDgfFFAAtAQAAAA==.Dalebeanhrdt:BAAANQADCggIDAAAAA==.Dallasx:BAAANQADCgUIBQAAAA==.Dalmarr:BAAANQAECgUICQAAAA==.Dancouga:BAABNQAECoEnAAIfAAgKiQvmGwDjAQAfAAgKiQvmGwDjAQAAAA==.Dantallon:BAEANQAECgIIBgABNQAECgcIHAAaAGMiAA==.Darkdarius:BAAANQADCgUICQAAAA==.Darthmaulus:BAAANQAECgUJCAABNQAECggIHQAJAB4KAA==.Daruncic:BAAANQAECgUIEwAAAA==.Dave:BAABNQAECoEbAAIJAAgK4wn/zADHAQAJAAgK4wn/zADHAQAAAA==.Dawnchatters:BAAANQADCgQIBAAAAA==.Dawnkyslayer:BAAANQADCgUIBQAAAA==.Dawntodusk:BAAANQADCgYIBgAAAA==.Daymia:BAABNQAECoEXAAIRAAcKJwfMigA7AQARAAcKJwfMigA7AQAAAA==.Dazknight:BAABNQAECoEdAAQUAAgKXRqdJQA2AgAUAAgKXRqdJQA2AgAWAAQKFQ6+fgDYAAABAAEK5AWI2QAnAAAAAA==.Dazshaman:BAAANQAECgQIBAABNQAECggIHQAUAF0aAA==.',
De='Deadion:BAAANQAECgcIFgAAAQ==.Deadpaly:BAAANQADCgMIAwABNQAECgcIFgAFAAAAAQ==.Deadspinwin:BAAANQADCgIIAgABNQAECgcIFgAFAAAAAQ==.Dearmage:BAABNQAECoEZAAIJAAgKXBMfowAbAgAJAAgKXBMfowAbAgAAAA==.Deathgripz:BAAANQADCggIGwAAAA==.Deathlockdes:BAAANQAECgEIAQAAAA==.Decormei:BAAANQAECgUIEwAAAA==.Dedman:BAAANQABCgQIAwAAAA==.Deltatoast:BAAANQADCgQICAAAAA==.Delusionz:BAAANQAECgYIDgABNQAECgUICgAFAAAAAA==.Demera:BAABNQAECoEUAAMLAAYKJRmGgADcAQALAAYKJRmGgADcAQAMAAEKygGBhgAoAAAAAA==.Demolack:BAAANQADCgIIBwAAAA==.Destheleye:BAAANQADCgMIAwAAAA==.Dethnyte:BAAANQAECgUJBwAAAA==.Deyjavaknadi:BAAANQADCgUIBQAAAA==.',
Di='Diaf:BAABNQAECoEdAAIJAAcKZBHg5gCVAQAJAAcKZBHg5gCVAQAAAA==.Diniwen:BAABNQAECoEZAAIJAAgKCB7pXwCsAgAJAAgKCB7pXwCsAgAAAA==.Dirienna:BAAANQABCgIIAgAAAA==.Dirtbikes:BAAANQAECgcIDgAAAA==.Discordmod:BAAANQAECgYICwAAAA==.Dithia:BAAANQAECgcIEQAAAA==.Divided:BAAANQAFFAEIAQAAAA==.Division:BAABNQAECoEYAAIHAAkKPCTrAgBwAwAHAAkKPCTrAgBwAwAAAA==.',
Dj='Djparrot:BAAANQAECgYIEgAAAA==.',
Do='Domrï:BAAANQAECgcICwAAAA==.Donkayslayer:BAABNQAECoEXAAIVAAcKSBDKSACbAQAVAAcKSBDKSACbAQAAAA==.Donlock:BAAANQAECgUIBQAAAA==.Doohoo:BAABNQAECoEbAAINAAgKphQ6JQAyAgANAAgKphQ6JQAyAgAAAA==.Dordrel:BAAANQADCgEIAQAAAA==.Douchekanu:BAAANQAECgEIAQAAAA==.Downpour:BAAANQAECgcICwAAAA==.',
Dr='Dracdad:BAAANQADCgEIAQABNQAECgMIBgAFAAAAAA==.Draevon:BAAANQADCgQICAABNQAECgUIDAAFAAAAAA==.Dragathor:BAAANQADCggIDwAAAA==.Dragondnutz:BAAANQAECgIIAgABNQAECggIEQAFAAAAAA==.Dragoness:BAAANQADCgQIBAAAAA==.Dragonflight:BAABNQAECoEdAAIgAAgKhQ4zHgDNAQAgAAgKhQ4zHgDNAQAAAA==.Drakloak:BAACNQAFFIEaAAMhAAgKgB2JAQAdAgAhAAYKoR2JAQAdAgAiAAQK3BYDBABwAQA1AAQKgSkAAyEACQrKJUMCAIkDACEACQokJUMCAIkDACIAAwr1JZINAEYBAAAA.Drclaw:BAAANQADCgQIBAABNQADCggIDwAFAAAAAA==.Drench:BAABNQAECoEcAAICAAgKKxsVMQB2AgACAAgKKxsVMQB2AgAAAA==.',
Du='Duckdodger:BAAANQADCgIIAgAAAA==.Durota:BAABNQAECoEcAAILAAcKKgUovgBSAQALAAcKKgUovgBSAQAAAA==.Dusktodawn:BAAANQABCgIIAgAAAA==.',
Dv='Dv:BAAANQADCggJDgAAAA==.',
Dw='Dwarftoss:BAABNQAECoEoAAIGAAgKVhmpOQBoAgAGAAgKVhmpOQBoAgAAAA==.',
Dz='Dzasterpiece:BAACNQAFFIEOAAMUAAcKFRcIAQBEAgAUAAcKFRcIAQBEAgAWAAEKGhZ7JwA/AAA1AAQKgUAABBQACQoKJsgBAMgDABQACQpeJcgBAMgDAAEACAqTJCAKAFkDABYAAQoZD868ADAAAAAA.',
['Dà']='Dàmnàtion:BAAANQADCgEIAQAAAA==.',
['Dä']='Däemarcus:BAABNQAECoEWAAMDAAcKjw7rdwCIAQADAAcKjw7rdwCIAQAaAAYKWQvs1AA3AQAAAA==.',
['Dò']='Dòyòùnèèd:BAAANQAECgIIAgAAAA==.',
Ec='Ectyxx:BAACNQAFFIEJAAIJAAUKThNGFwCWAQAJAAUKThNGFwCWAQA1AAQKgSQAAgkACQqbITYoADcDAAkACQqbITYoADcDAAAA.',
Ed='Edris:BAAANQAECgYIEAAAAA==.',
Ef='Effört:BAAANQADCggJGQAAAA==.',
Ei='Eightlug:BAAANQAECgEIAQAAAA==.',
El='Elareis:BAAANQADCgUIDwAAAA==.Elebits:BAAANQADCgIIBAABNQAFFAYICwALANkOAA==.Eluned:BAABNQAECoEXAAIaAAgKnRVGgAD3AQAaAAgKnRVGgAD3AQAAAA==.Elwynn:BAAANQAECggIIQAAAQ==.Elycia:BAAANQADCgYICwAAAA==.',
Em='Emosmaug:BAACNQAFFIEKAAIIAAUK2hCWBgCRAQAIAAUK2hCWBgCRAQA1AAQKgSIAAggACQozIYgHAFEDAAgACQozIYgHAFEDAAAA.',
En='Endezard:BAAANQABCgYIBgAAAA==.Enkistral:BAAANQAECgMIAwABNQAFFAQICgAVAFYUAA==.Envi:BAAANQAECgMIBAAAAA==.',
Er='Eretar:BAAANQAECgMIBAAAAA==.Erotaph:BAAANQAECgUIEwAAAA==.',
Eu='Euron:BAAANQAECgUIDAAAAA==.',
Ev='Evach:BAABNQAECoEkAAMMAAkKhiLfGQBuAgAMAAgKziLfGQBuAgALAAIKrRuaFQGAAAAAAA==.Everblight:BAAANQADCgYICwAAAA==.',
Fa='Facex:BAAANQADCggIDgAAAA==.Faelor:BAAANQADCggIGwAAAA==.Faet:BAABNQAECoEZAAILAAcKCCb1IAD2AgALAAcKCCb1IAD2AgAAAA==.Faeyt:BAABNQAECoEcAAQKAAcKWx11GQBHAgAKAAcKWx11GQBHAgAjAAUKFxMKKQAHAQAVAAIKOwhmkwBVAAAAAA==.Fatkokmage:BAAANQADCggIDAAAAA==.',
Fc='Fcawfng:BAAANQADCgUIBwAAAA==.',
Fe='Felakai:BAAANQADCggIHQAAAA==.',
Fi='Fidgetspinna:BAAANQADCgIIAgAAAA==.Finaljudgmnt:BAAANQADCgIIAgABNQAECgkJHQARABwOAA==.Finesthour:BAACNQAFFIElAAMBAAgK/SUGAACHAwABAAgK/SUGAACHAwAWAAEKmxRIKQA5AAA1AAQKgS0AAgEACQrRJvMDAKoDAAEACQrRJvMDAKoDAAAA.Fingerlicker:BAAANQADCgcIDQAAAA==.Finnaburnya:BAAANQADCgYIBwAAAA==.Finnacreep:BAAANQADCgcIBwAAAA==.Firepower:BAAANQABCgIIAgAAAA==.Fitzwilliam:BAABNQAECoEXAAMGAAgKdQrUgAByAQAGAAcK0wnUgAByAQACAAUKEBjxjgA1AQAAAA==.Fives:BAAANQAECgcIDwAAAA==.',
Fj='Fjordchi:BAABNQAECoEWAAIdAAYK6h2VIAD7AQAdAAYK6h2VIAD7AQAAAA==.',
Fl='Fluxy:BAAANQADCgYIBgAAAA==.',
Fo='Fonzie:BAABNQAECoEYAAIBAAcKPBAqaABLAQABAAcKPBAqaABLAQAAAA==.Foozykinz:BAAANQADCgMIAwAAAA==.Forlorn:BAAANQAECgUIEgAAAA==.Fortsmite:BAAANQADCgUICQAAAA==.Foxicious:BAABNQAECoEcAAITAAkK9hFhHAA+AgATAAkK9hFhHAA+AgAAAA==.Foxjaw:BAAANQADCgIIAgAAAA==.Foxpaw:BAABNQAECoE9AAILAAgKfA36agARAgALAAgKfA36agARAgAAAA==.',
Fr='Fraggle:BAEANQAECgIIAgAAAA==.Frankoc:BAAANQADCgMIAwAAAA==.Freeza:BAAANQADCgQIBAAAAA==.Freshlock:BAABNQAECoEjAAMYAAkKESQXBwCFAwAYAAkKESQXBwCFAwAXAAEKmx/mZgBHAAAAAA==.Freyr:BAAANQAFFAIIAwAAAA==.Frostbitë:BAAANQADCgEIAQAAAA==.Frostfires:BAABNQAECoEfAAIJAAgKRBqTegByAgAJAAgKRBqTegByAgAAAA==.Frostlawlz:BAAANQADCgUICQAAAA==.',
Fu='Fubashi:BAABNQAECoErAAIKAAkKdCN2AwCDAwAKAAkKdCN2AwCDAwABNQAECgUICgAFAAAAAA==.Furritoo:BAAANQAECgcJDgAAAA==.Fuzzie:BAAANQAECgQIBQAAAA==.',
Fy='Fyneshi:BAAANQADCgUIBQAAAA==.',
Ga='Gachiwl:BAACNQAFFIEjAAQYAAgKCR4DBAARAgAYAAYKExsDBAARAgAkAAMKEB8ZAQA8AQAXAAIKPCZFBADMAAA1AAQKgTYABCQACQqyJh4AAOUDACQACQpmJR4AAOUDABcACAqpJSsCAD0DABgABgoqJgxGAGMCAAAA.Galirana:BAAANQAECgcIDwAAAA==.Gamergoo:BAAANQAECggIEQAAAA==.Gampshwago:BAABNQAECoEcAAMhAAkKVyGTBwDxAgAhAAgKVyGTBwDxAgAgAAkKfQ0TGgAGAgABNQAECggIDAAFAAAAAA==.Garion:BAAANQADCgQIBAAAAA==.Garkk:BAAANQAECgcIEwAAAA==.Garronan:BAACNQAFFIErAAMMAAgKHSRyAAAhAwAMAAgK9h9yAAAhAwALAAEKGSMWJgBmAAA1AAQKgS0AAwwACQoyJqIIADsDAAwACAoiJqIIADsDAAsAAgpsJXsKAaUAAAAA.',
Ge='Geary:BAAANQAECgQIBgABNQAECgYIDQAFAAAAAA==.Gelina:BAABNQAECoEaAAIfAAgKUxhBEABnAgAfAAgKUxhBEABnAgAAAA==.Getfookd:BAAANQADCgYIBgAAAA==.Geveesa:BAABNQAECoEXAAIXAAcKrBL6EQDcAQAXAAcKrBL6EQDcAQAAAA==.',
Gi='Gibdk:BAAANQAECgMIAwABNQAECgkJJAAYAKoZAA==.Gibletss:BAABNQAECoEkAAQYAAkKqhn4ZgABAgAYAAcK4xf4ZgABAgAXAAQKoxThLAAPAQAkAAEK4CGiHwBjAAAAAA==.',
Gl='Glaivedigger:BAABNQAECoEjAAIIAAgKFBpqGQB1AgAIAAgKFBpqGQB1AgAAAA==.Glollan:BAAANQAECgUIBgAAAA==.',
Go='Golda:BAABNQAECoEnAAIdAAcKEA0AMABiAQAdAAcKEA0AMABiAQAAAA==.Goldielocks:BAAANQADCggICAAAAA==.Goonerbait:BAAANQAECgQJBQAAAA==.Goragon:BAAANQAECgYIEQAAAA==.Gorkgork:BAAANQAECgQICAAAAA==.',
Gr='Grass:BAAANQADCgcICgAAAA==.Grcorolla:BAACNQAFFIEKAAIOAAUKwBlNDAC6AQAOAAUKwBlNDAC6AQA1AAQKgSkAAg4ACQq+JWIFAMUDAA4ACQq+JWIFAMUDAAAA.Grindder:BAAANQAECgMIBQAAAA==.Grippers:BAAANQADCgYIDAAAAA==.Groshnok:BAAANQAECgYIEAAAAA==.Grunky:BAABNQAECoEZAAMCAAkKTRkOKACiAgACAAkKTRkOKACiAgAGAAQKORbtwADiAAAAAA==.Grunkyvoke:BAAANQAECgIIAwABNQAECgkJGQACAE0ZAA==.',
Gu='Guanyin:BAAANQADCgUIBQAAAA==.Gustobooms:BAAANQAECgMIAwAAAA==.',
Gw='Gwantanamata:BAAANQADCggICAAAAA==.',
['Gì']='Gìrthquake:BAACNQAFFIEJAAIGAAUKJh46BgDsAQAGAAUKJh46BgDsAQA1AAQKgSYAAgYACQrOIqcNAG8DAAYACQrOIqcNAG8DAAAA.',
Ha='Haiayla:BAAANQADCgcIDAAAAA==.Haleybug:BAAANQADCgUIBwAAAA==.Halyax:BAAANQAECgQICgAAAA==.Hammerslol:BAAANQADCggICAAAAA==.Hamoron:BAAANQADCgYIBgAAAA==.',
Hd='Hdog:BAAANQAECgIIBQAAAA==.',
He='Heisenbergz:BAAANQADCgUIDAAAAA==.Helicopter:BAAANQADCggICAABNQAECgQIBwAFAAAAAA==.Henter:BAAANQADCgUIBQAAAA==.Herm:BAAANQAECgUIDAAAAA==.Hesel:BAAANQAECgcIDQABNQAFFAQIBgAgAAIPAA==.',
Hi='Hihowareya:BAACNQAFFIELAAIIAAUKhSEVBADxAQAIAAUKhSEVBADxAQA1AAQKgTQAAwgACQq4JncAAPoDAAgACQq4JncAAPoDABsAAwoCI7tMADIBAAAA.Hildegar:BAAANQAECgYIEQAAAA==.',
Ho='Hokiette:BAAANQAECgYIDwAAAA==.Holdmydeeps:BAAANQAECgYIDgAAAA==.Holybabs:BAAANQADCgIIAgAAAA==.Holyheals:BAAANQAECgIIAgAAAA==.Horehronie:BAAANQADCggIHwAAAA==.Hosebaggins:BAAANQADCgcIDQABNQAECgUIEwAFAAAAAA==.How:BAAANQADCgUIBQAAAA==.',
Hu='Hubbles:BAACNQAFFIEmAAICAAgKnhbXAADDAgACAAgKnhbXAADDAgA1AAQKgSwAAgIACQqGJHQGAIEDAAIACQqGJHQGAIEDAAAA.Hububbles:BAAANQAECgQICgABNQAFFAgIJgACAJ4WAA==.',
Hy='Hybla:BAAANQADCgYIBgAAAA==.Hylikus:BAAANQAECgcIEQAAAA==.',
['Hë']='Hëlen:BAAANQADCgYICgAAAA==.Hëllräisër:BAAANQADCgUIBQAAAA==.',
['Hô']='Hôlystôrm:BAAANQAECgYIEgAAAA==.',
Ic='Icesaber:BAAANQAECgUIEwAAAA==.Icevili:BAABNQAECoEgAAIJAAgKSwd93ACpAQAJAAgKSwd93ACpAQAAAA==.Ichigonyne:BAAANQADCgcJFgAAAA==.Iciala:BAAANQADCgMIBAAAAA==.',
Ig='Iggar:BAAANQAECgQIBQAAAA==.Igotu:BAAANQAECgMIBwAAAA==.Igris:BAAANQAECgQICgAAAA==.',
Il='Illistan:BAAANQAECgUIBQAAAA==.',
Im='Imira:BAAANQADCgYIDAABNQAECgUIDAAFAAAAAA==.Impster:BAAANQADCggICAAAAA==.Impushpop:BAAANQAECgUICwAAAA==.Imsokool:BAAANQAECgEIAQAAAA==.Imsure:BAABNQAECoEXAAMCAAYKxwvGlgAhAQACAAYKxwvGlgAhAQAGAAEKWgbGIQEsAAAAAA==.',
In='Indigos:BAAANQAECgIIAgAAAA==.Ineedhelp:BAAANQAECggIAQAAAA==.',
Ir='Irasyn:BAAANQADCgYICwAAAA==.Ironpork:BAAANQADCgYICwAAAA==.',
Is='Isam:BAABNQAECoEaAAMLAAcKPB3IagARAgALAAcKPB3IagARAgAMAAEK0wMnhwAnAAAAAA==.',
Ja='Jackietran:BAAANQADCggIDwAAAA==.Jadefire:BAABNQAECoEmAAIdAAkKTB2nDwDOAgAdAAkKTB2nDwDOAgAAAA==.Jaedemon:BAABNQAECoEzAAIbAAkKFCFvCwA9AwAbAAkKFCFvCwA9AwAAAA==.Jakuta:BAAANQAECgUICQAAAA==.Jawbreaker:BAAANQABCgMIAgAAAA==.Jaysön:BAAANQADCgcIDwAAAA==.',
Je='Jebuku:BAAANQAECgUICgAAAA==.Jenkeez:BAAANQABCggICAAAAA==.Jestius:BAAANQAECgEIAQAAAA==.Jetpakmonkey:BAAANQAECgIIAgAAAA==.Jeudi:BAAANQADCgcIEgAAAA==.',
Ji='Jinxblue:BAABNQAECoEYAAIGAAgKYx6VKgCyAgAGAAgKYx6VKgCyAgAAAA==.Jiroyan:BAAANQAECgUIDgAAAA==.',
Jo='Jollyflow:BAAANQAECgYIDAAAAA==.Joralö:BAAANQAECgYIEAAAAA==.',
Jt='Jtvikiing:BAAANQAECgEIAgABNQAECggIEwAVAMIZAA==.',
Ju='Jubilee:BAABNQAECoEfAAMUAAcKiBPnPgCLAQAUAAcK2BLnPgCLAQABAAYKfAyweQAKAQAAAA==.Jumpies:BAAANQAECgUIEwAAAA==.Jupiturr:BAABNQAECoEWAAIaAAYKgAsT0ABBAQAaAAYKgAsT0ABBAQAAAA==.Justian:BAAANQAECgEIAQAAAA==.Juunbroh:BAABNQAECoE0AAIDAAkK7hbqLgCPAgADAAkK7hbqLgCPAgAAAA==.',
['Jé']='Jénova:BAAANQAECgEIAQAAAA==.',
['Jö']='Jörd:BAAANQAECgUICgAAAA==.',
Ka='Kaa:BAAANQADCgUIBQABNQAFFAQICQAWAFMaAA==.Kaarin:BAAANQADCgcIBwABNQAECggIHQAJAB4KAA==.Kabillabob:BAAANQADCgYICgAAAA==.Kadowe:BAABNQAECoEXAAIJAAgKpx4yYQCpAgAJAAgKpx4yYQCpAgAAAA==.Kaiyla:BAAANQADCgcICQAAAA==.Kalacrity:BAAANQAECgIIAgABNQAECgkJIQAHAOYcAA==.Kaladinn:BAABNQAECoEVAAIOAAcKIgf6uwBVAQAOAAcKIgf6uwBVAQAAAA==.Kalintene:BAAANQADCgIIAgABNQAECgkJJAAlAAsfAA==.Kalpanda:BAAANQAECgQIBgABNQAECgkJIQAHAOYcAA==.Kaonashi:BAAANQADCgcIBwAAAA==.Kargan:BAAANQAECgIIAwABNQAECgcIGgAJAHcYAA==.Karma:BAAANQADCgcICwAAAA==.Karthas:BAABNQAECoEXAAIfAAcKxA5yHwC/AQAfAAcKxA5yHwC/AQAAAA==.Kassian:BAAANQAECgUIEwAAAA==.Kastbeel:BAAANQADCggIEAAAAA==.Kayhana:BAAANQAECgEIAQAAAA==.',
Ke='Keillea:BAAANQADCgcIDgABNQAFFAIIBAAFAAAAAA==.Keir:BAABNQAECoEXAAIeAAcK5CTvAwDuAgAeAAcK5CTvAwDuAgAAAA==.Kelsey:BAAANQADCgYICQABNQAECgYIEwAFAAAAAA==.Kenny:BAAANQAECgUIDwAAAA==.Kevindurand:BAAANQABCgQIBAAAAA==.Keyanor:BAAANQAECgcIEgAAAA==.',
Kh='Khaeltharion:BAAANQAECgcIEgAAAA==.Khalan:BAABNQAECoEbAAIlAAgK9xRKDQASAgAlAAgK9xRKDQASAgAAAA==.Khavatari:BAABNQAECoEdAAIOAAgKmxZ5cAAhAgAOAAgKmxZ5cAAhAgAAAA==.Khazidhea:BAAANQADCgQICgABNQAECgYIEwAFAAAAAA==.Khazmyk:BAAANQADCgIIAgABNQAECgYIEwAFAAAAAA==.Khazrael:BAAANQAECgYIEwAAAA==.Khazriel:BAAANQADCgcIEgABNQAECgYIEwAFAAAAAA==.',
Ki='Killerpin:BAAANQAECgQICgAAAA==.Killig:BAAANQABCgIIAgAAAA==.Kilmanov:BAAANQAECggIBwAAAA==.Kitmeup:BAACNQAFFIEVAAIJAAcKlRZHBQBJAgAJAAcKlRZHBQBJAgA1AAQKgR8AAgkACQq3JdgaAGMDAAkACQq3JdgaAGMDAAAA.',
Ko='Kookiez:BAABNQAECoEpAAIYAAkKJg64XAAfAgAYAAkKJg64XAAfAgAAAA==.Korbane:BAAANQADCgYICwAAAA==.Kordormu:BAAANQADCgMIAwAAAA==.Korrupshun:BAAANQAECgcJDgAAAA==.Korvian:BAABNQAECoEeAAIDAAgKGgtNbgClAQADAAgKGgtNbgClAQAAAA==.Kozzyy:BAAANQAECgQIBAAAAA==.',
Kr='Kraatose:BAAANQADCgYIDQABNQAECgMIBQAFAAAAAA==.Kraizy:BAABNQAECoEfAAIRAAkKsBuVHADnAgARAAkKsBuVHADnAgABNQAFFAIIAwAJAM8OAA==.Kro:BAAANQADCgYIDQAAAA==.Krymsy:BAAANQAECgYICwAAAA==.',
Ku='Kuki:BAAANQABCgIIAgAAAA==.',
Ky='Kynigós:BAABNQAECoEhAAILAAcKTh+pRAB4AgALAAcKTh+pRAB4AgAAAA==.',
Kz='Kzerg:BAAANQAECgQIBwAAAA==.',
La='Laastira:BAAANQADCgQIBAABNQAECgMIBQAFAAAAAA==.Labzy:BAAANQADCgQIBAAAAA==.Laestra:BAAANQABCgIIAgAAAA==.Lalinthor:BAAANQADCgUIBgAAAA==.Lamìà:BAAANQADCgcJBwABNQAECggIIQAOAH8aAA==.Lavendér:BAABNQAECoEhAAIYAAkK9xceMwCiAgAYAAkK9xceMwCiAgAAAA==.',
Le='Leadk:BAAANQAECgUIBQAAAA==.Leerooy:BAAANQADCgIIAgAAAA==.Leobardo:BAAANQADCggIDAAAAA==.',
Li='Lightsfury:BAAANQADCgEIAQABNQAECgQIBQAFAAAAAA==.Lihp:BAAANQAECgYIDQAAAA==.Liljj:BAAANQAECgIIAgAAAA==.Limmy:BAAANQADCgMJAwAAAA==.Linndara:BAAANQAECgIIAwAAAA==.Linting:BAABNQAECoEdAAMRAAkKHA7IUgD/AQARAAkKHA7IUgD/AQATAAQKCQ2pRwDWAAAAAA==.Lithsong:BAABNQAECoExAAMWAAkKHCL0CgBOAwAWAAkKHCL0CgBOAwABAAIKSgKZwwBCAAAAAA==.',
Lo='Lockthor:BAABNQAECoEhAAIYAAkKDRDAWQAoAgAYAAkKDRDAWQAoAgAAAA==.Lonie:BAABNQAECoEZAAITAAcKVx1AHQAzAgATAAcKVx1AHQAzAgAAAA==.Loto:BAAANQAECgMIAwAAAA==.',
Lu='Lucyfury:BAAANQADCgEIAQAAAA==.Luedragosa:BAABNQAECoE0AAQhAAgKeAWUIAAxAQAhAAcKywSUIAAxAQAiAAUK3gRKFQCzAAAgAAUKhgHfPgCCAAAAAA==.Lunademon:BAAANQADCgUIBQAAAA==.Lunadk:BAABNQAECoEbAAIWAAgKXxkYLQBGAgAWAAgKXxkYLQBGAgAAAA==.Lunanecro:BAAANQAECgYIBwAAAA==.Luxmortae:BAAANQABCgIIAgAAAA==.Luxserena:BAAANQAECgEIAQAAAA==.Luxumbrae:BAAANQAECgMIAwAAAA==.',
Ly='Lydie:BAAANQAECgYIDQAAAA==.Lynthara:BAAANQADCgYIBgAAAA==.Lysunder:BAABNQAECoEVAAImAAcKtwY3BABXAQAmAAcKtwY3BABXAQAAAA==.Lythronax:BAABNQAECoEdAAIhAAcKDxsVEAA4AgAhAAcKDxsVEAA4AgAAAA==.',
['Lö']='Löwen:BAAANQAECgcIEAAAAA==.',
Ma='Mackro:BAAANQADCggIDgAAAA==.Madblackjack:BAAANQADCgUICQAAAA==.Madmurph:BAAANQADCgUIBQABNQAECgQIBAAFAAAAAA==.Maestro:BAAANQAECgQIBgAAAA==.Magark:BAAANQAECgQIBQAAAA==.Mahanar:BAAANQADCgcICAAAAA==.Maimai:BAAANQADCgcICQAAAA==.Makandcheese:BAAANQADCgIIAQAAAA==.Malefîcent:BAAANQAECgYIBgAAAA==.Malice:BAAANQADCggICAAAAA==.Malisenta:BAABNQAECoEwAAMgAAkKARikDQC6AgAgAAkKARikDQC6AgAiAAYKeQVzEgDcAAAAAA==.Mallboro:BAAANQADCgQIBAAAAA==.Mallis:BAAANQAECgcIEgAAAA==.Mardew:BAABNQAECoEhAAIOAAgKfxr9XABYAgAOAAgKfxr9XABYAgAAAA==.Markoramius:BAAANQAECgUIEAAAAA==.Marpew:BAAANQADCgcIDAABNQAECggIIQAOAH8aAA==.Mathelas:BAAANQADCgEIAQAAAA==.',
Mc='Mcscales:BAAANQAECgEIAQAAAA==.',
Me='Meatballa:BAAANQAECggICAABNQAECggIDwAFAAAAAA==.Mehkasingh:BAABNQAECoEbAAIVAAkKKyPBBwCIAwAVAAkKKyPBBwCIAwAAAA==.Melanotic:BAAANQAECggICAAAAA==.Melbur:BAAANQADCgYIBgAAAA==.Mellicanisis:BAAANQAECgQIBAAAAA==.Melvalint:BAABNQAECoEdAAIJAAgKHgrlzwDBAQAJAAgKHgrlzwDBAQAAAA==.Memademic:BAABNQAECoEXAAIBAAkKPRI8PAAKAgABAAkKPRI8PAAKAgAAAA==.Memhuntz:BAAANQADCgUIBQAAAA==.Mendsong:BAAANQAECgUICQAAAA==.Meralonnë:BAEANQAECgMIBQABNQAECgcIHAAaAGMiAA==.Merigold:BAAANQADCgEIAQAAAA==.Merlins:BAABNQAECoFIAAIYAAkKYxmSLAC6AgAYAAkKYxmSLAC6AgAAAA==.Messner:BAAANQAECgIIAgAAAA==.',
Mi='Miamiganster:BAABNQAFFIEJAAMNAAYKdhhVAgAjAgANAAYKdhhVAgAjAgAfAAMKlQTRCgDvAAABNQAECggIDAAFAAAAAA==.Milestheevil:BAAANQADCgcICQAAAA==.Mindbullets:BAAANQAECgQICQAAAA==.Mirah:BAABNQAECoEcAAIKAAYK0ha9KQCeAQAKAAYK0ha9KQCeAQAAAA==.Misclick:BAABNQAECoEkAAIJAAkKzyXFAgDhAwAJAAkKzyXFAgDhAwAAAA==.',
Mm='Mmbeans:BAAANQAECgMIAwABNQAECgUIDQAFAAAAAA==.',
Mo='Mochabean:BAAANQAECgUIBQABNQAECggIGQAVAL0aAA==.Mochikat:BAACNQAFFIEhAAIDAAcKvxBPAwA/AgADAAcKvxBPAwA/AgA1AAQKgS4AAgMACQoDI4oHAIMDAAMACQoDI4oHAIMDAAAA.Mogamemnon:BAAANQAECgQIBAAAAA==.Mogriya:BAAANQAECgcIEgAAAA==.Moisttank:BAAANQAECgEIAQAAAA==.Mokt:BAAANQAECgcIDwAAAA==.Mollywhop:BAABNQAECoEgAAMCAAgKwBZWQAA0AgACAAgKwBZWQAA0AgAGAAQKEA59vQDpAAAAAA==.Molyneaux:BAAANQAECgUIBwAAAA==.Moonpaw:BAAANQAECgQICwAAAA==.Moonwisp:BAAANQAECgUIBQAAAA==.Mooskaroo:BAABNQAECoEiAAIVAAkKMCPCCQBzAwAVAAkKMCPCCQBzAwAAAA==.Moraa:BAAANQAECgEIAQAAAA==.Moregoth:BAAANQAECgUICgAAAA==.Morrows:BAABNQAECoEWAAIUAAgKlBZEKwAMAgAUAAgKlBZEKwAMAgAAAA==.Mossylock:BAAANQADCgQIBAAAAA==.Mossyoaks:BAAANQAECgEIAQAAAA==.Mossytank:BAAANQAECgMIBQAAAA==.Mossywarrior:BAAANQAECgIIAgAAAA==.',
Mu='Muggle:BAAANQADCgcICwAAAA==.Multiply:BAAANQAECgcICwAAAA==.Murph:BAAANQAECgQIBAAAAA==.Murphgoat:BAAANQAECgYIEwAAAA==.Mutilatee:BAACNQAFFIEnAAMNAAgKqCQlAABQAwANAAgKfSMlAABQAwAfAAYK0R2eAQBDAgA1AAQKgSwABA0ACQrkJpkHAEUDAA0ACAoyJJkHAEUDAB8ABwrMJfoJAMkCACcAAQqgIdgXAEoAAAAA.',
My='Myeyeonu:BAAANQADCggIJwABNQAECgMIBwAFAAAAAA==.Myrollan:BAAANQADCgYIBgAAAA==.Mystampede:BAABNQAECoEYAAILAAkKphpRKADXAgALAAkKphpRKADXAgABNQAECgkJMQARALckAA==.Mystshots:BAABNQAECoEbAAILAAgKzQ8RaAAYAgALAAgKzQ8RaAAYAgAAAA==.',
['Mí']='Míra:BAABNQAECoFFAAIWAAgK3CUuCABtAwAWAAgK3CUuCABtAwAAAA==.',
['Mø']='Møzrt:BAAANQADCggIGwABNQAECgcIDgAFAAAAAA==.',
Na='Nachtengel:BAABNQAECoEfAAIYAAgKPAfLkwCFAQAYAAgKPAfLkwCFAQAAAA==.Nagda:BAAANQADCgYIBgAAAA==.Naismene:BAAANQAECgUICgAAAA==.Naismine:BAAANQAECgUIBgAAAA==.Namswoam:BAAANQAECggIDAAAAA==.Nate:BAAANQAECgUICgAAAA==.Naustaire:BAAANQADCgUIBQAAAA==.Nazendrenz:BAABNQAECoEtAAQYAAkKQiIzIADtAgAYAAgK2iEzIADtAgAXAAQK5xEWLAATAQAkAAIKCw9hHQBwAAAAAA==.',
Nc='Nconceivable:BAAANQADCgUIBQAAAA==.',
Ne='Nebieul:BAAANQAECgUIDgAAAA==.Necromantic:BAABNQAECoEgAAMBAAgKpCMSDwAqAwABAAgKpCMSDwAqAwAWAAUKMRnvYgBEAQAAAA==.Neihtdk:BAAANQAECgUICAAAAA==.Nerissraven:BAABNQAECoEWAAIYAAYK4CPpRgBgAgAYAAYK4CPpRgBgAgAAAA==.Nesaru:BAABNQAECoEcAAICAAcKpiKRJQCvAgACAAcKpiKRJQCvAgAAAA==.Nesho:BAAANQADCgQIBAAAAA==.Nesse:BAAANQADCggIDQAAAA==.Nestah:BAAANQAECgUIEgAAAA==.Neundorff:BAAANQADCgUICQAAAA==.',
Ni='Niemira:BAAANQADCgQIBAAAAA==.Nighthunter:BAAANQAECgMJAwAAAA==.Nightshift:BAAANQADCgIIAgAAAA==.Nightwatch:BAABNQAECoEWAAIDAAcKjRxNQgA+AgADAAcKjRxNQgA+AgAAAA==.Niki:BAAANQAECggIDgAAAA==.Nisaloth:BAAANQAECgYIEAAAAA==.',
No='No:BAAANQADCgEIAQAAAA==.Nonaz:BAAANQAECgUICgAAAA==.Nonrahnu:BAAANQAECgQIBgAAAA==.Nontoxic:BAAANQAECggIDQAAAQ==.Noodlemaker:BAABNQAECoEWAAMdAAgKtx7PFgBuAgAdAAgKEx3PFgBuAgAoAAMK8RW/HwDBAAAAAA==.Noop:BAAANQAECgUIBgAAAA==.Norot:BAAANQAECgIIAgAAAA==.Northcut:BAAANQAECgcIDQAAAA==.Nozomga:BAEANQABCgIIAwAAAA==.',
Nu='Nual:BAABNQAECoEuAAITAAkKLB2nDgDvAgATAAkKLB2nDgDvAgAAAA==.Nualandvoid:BAAANQAECgQIBAABNQAECgkJLgATACwdAA==.Nubur:BAAANQADCgEIAQAAAA==.Nudag:BAAANQAECgQICgAAAA==.Nukelele:BAAANQAECgEIAgAAAA==.',
Ny='Nystanari:BAAANQAECgcIDQAAAA==.',
['Nà']='Nàturally:BAAANQAECgMIAwAAAA==.',
['Nï']='Nïghtmare:BAAANQADCgIIAwAAAA==.',
Oa='Oakendeath:BAAANQAECgYIEAAAAA==.',
Od='Odania:BAABNQAECoEeAAIdAAcKqRrmIAD4AQAdAAcKqRrmIAD4AQAAAA==.',
Oh='Ohmâ:BAAANQABCgUICwAAAA==.',
Ol='Older:BAABNQAECoFHAAIKAAgKuyYWAwCMAwAKAAgKuyYWAwCMAwAAAA==.Olk:BAABNQAECoEkAAIVAAgK8R9JGgDbAgAVAAgK8R9JGgDbAgAAAA==.',
Om='Omari:BAAANQADCgcICwAAAA==.',
On='Onlytotems:BAAANQADCgUIBQAAAA==.',
Oo='Oodustotem:BAAANQADCgYIBwAAAA==.Oohgabooga:BAAANQAFFAEIAgABNQAFFAUICgAbABIhAA==.',
Or='Oreganodh:BAAANQAECgIIAgABNQAFFAgIJgAkAJMgAA==.Oreganom:BAAANQAECgYIDgABNQAFFAgIJgAkAJMgAA==.Oreganosh:BAAANQADCgQIBQABNQAFFAgIJgAkAJMgAA==.Oreganow:BAACNQAFFIEmAAQkAAgKkyACAAAoAwAkAAgKMB0CAAAoAwAYAAYKqBuEBAAFAgAXAAMKbyLSAQAIAQA1AAQKgS0ABBgACQrMJnkEAKcDABgACQrkJXkEAKcDABcACAq6JSkCAD0DACQABAomJsYJALgBAAAA.Orenghar:BAABNQAECoEqAAICAAkKox0DHADiAgACAAkKox0DHADiAgAAAA==.',
Os='Os:BAAANQAECgQIBQAAAA==.',
Ov='Overbite:BAAANQADCgEIAQAAAA==.Overcast:BAAANQAECgQICAAAAA==.',
Ow='Owlcapwn:BAAANQADCgUIBQAAAA==.',
Pa='Pajamajacks:BAABNQAECoEvAAMBAAkKECArJQCKAgABAAgKACErJQCKAgAUAAYKNhqkNQDFAQABNQAFFAgIHgAVACwXAA==.Paladracdad:BAAANQAECgMIBgAAAA==.Pallylujâh:BAEBNQAECoEcAAMaAAcKYyKpPQC4AgAaAAcKYyKpPQC4AgADAAQKGiCXhQBhAQAAAA==.Palmerz:BAAANQAECgIIAgAAAA==.Papi:BAAANQADCggIDAAAAA==.Papy:BAAANQADCgQJBAAAAA==.Pardak:BAAANQAECgYIEAAAAA==.Partition:BAAANQAECgQIBwAAAA==.Patchwork:BAAANQAECgEIAQAAAA==.Pavlov:BAAANQAECgEIAQAAAA==.Paìn:BAAANQAECgYIBgABNQAFFAUIBgAIAFAUAA==.',
Pe='Pengpeng:BAABNQAECoErAAMJAAkKWxC4kABCAgAJAAkKWxC4kABCAgAQAAEKgguURAAtAAAAAA==.Perryy:BAAANQAECgQIBQAAAA==.Persephenie:BAAANQADCggIBwAAAA==.Pesmerga:BAAANQAECgQIBgAAAA==.Pestis:BAAANQABCgMJAwAAAA==.Pestosham:BAAANQAECgYIBAAAAA==.Pestulence:BAAANQADCgMIAwAAAA==.Pewpew:BAAANQADCgEIAQAAAA==.',
Ph='Phaithe:BAAANQADCgQIBwABNQAECgUIEAAFAAAAAA==.Phantasm:BAAANQADCggIDAAAAA==.Phil:BAAANQADCgQIBAABNQAECgYIDQAFAAAAAA==.Philibert:BAAANQABCgcICQAAAA==.Philwhite:BAAANQAECgQIBgABNQAECgYIDQAFAAAAAA==.Phriaa:BAAANQAECgQIBAABNQAECgUIDAAFAAAAAA==.Phungerclap:BAACNQAFFIEQAAIOAAcKAiRSAQDiAgAOAAcKAiRSAQDiAgA1AAQKgUEAAw4ACQr5JrMAAAYEAA4ACQr5JrMAAAYEACkABQpnH6QWAJQBAAAA.',
Pi='Pikarfor:BAABNQAECoEWAAIfAAcKshrNEgBGAgAfAAcKshrNEgBGAgAAAA==.Pingu:BAACNQAFFIEeAAICAAcKvyD/AAC2AgACAAcKvyD/AAC2AgA1AAQKgSwAAgIACQoSJfYGAHwDAAIACQoSJfYGAHwDAAAA.',
Pk='Pkspyro:BAAANQAECgQICgAAAA==.',
Pl='Planckshock:BAAANQAECgEIAQABNQAECggIEQAFAAAAAA==.Planckwar:BAAANQAECggIEQAAAA==.',
Po='Polarexpress:BAAANQAECgQIBwAAAA==.Ponfe:BAAANQAECgEIAQABNQAECgQIBwAFAAAAAA==.Ponfomage:BAAANQAECgQIBwAAAA==.Ponfop:BAAANQAECgIIBAABNQAECgQIBwAFAAAAAA==.Pootydin:BAAANQAECgYIBgAAAA==.Popicus:BAAANQAECgYIEAAAAA==.Porridge:BAAANQAECgMIBwAAAA==.',
Pr='Pratz:BAABNQAECoEdAAMXAAkKqhANFgC1AQAYAAkKbQpDdQDYAQAXAAcKkg4NFgC1AQAAAA==.Priestism:BAEANQAECggIEAABNQAFFAgIJwAVAFkfAA==.Primordikal:BAABNQAECoEhAAIHAAkK5hwuBwD/AgAHAAkK5hwuBwD/AgAAAA==.Priscillå:BAAANQAECggIBAAAAA==.',
Ps='Psamaithe:BAAANQADCggICAAAAA==.',
Pu='Pudders:BAACNQAFFIEeAAIVAAgKLBcfAQDaAgAVAAgKLBcfAQDaAgA1AAQKgSwAAhUACQpVJQgEALUDABUACQpVJQgEALUDAAAA.Puffss:BAAANQADCgQIBAAAAA==.Pumperdumper:BAAANQAECggIBwAAAA==.Punchfist:BAAANQAECgUIEwAAAA==.Puppy:BAAANQABCgcICgAAAA==.',
Pw='Pwdrtoastman:BAAANQABCggIDwAAAA==.',
Qu='Quartzviper:BAAANQADCgYICQAAAA==.Quickcast:BAABNQAECoEnAAMJAAkKASJXKQA0AwAJAAkKZCFXKQA0AwAQAAEKtCDuMQBbAAAAAA==.',
Ra='Raddru:BAABNQAECoEWAAIjAAkK2iYmAAATBAAjAAkK2iYmAAATBAABNQAFFAcIJgAWAB8lAA==.Radel:BAACNQAFFIEmAAIWAAcKHyV0AADyAgAWAAcKHyV0AADyAgA1AAQKgVAAAhYACQo/JiACAM0DABYACQo/JiACAM0DAAAA.Radlyn:BAAANQAECggIEwABNQAFFAcIJgAWAB8lAA==.Radmonk:BAAANQAFFAIIAgABNQAFFAcIJgAWAB8lAA==.Radpal:BAACNQAFFIEHAAIEAAMKeBWdBwC4AAAEAAMKeBWdBwC4AAA1AAQKgSoAAgQACQoCJwgAABsEAAQACQoCJwgAABsEAAE1AAUUBwgmABYAHyUA.Radwar:BAABNQAECoEpAAMpAAkKwyYlAAAHBAApAAkKwyYlAAAHBAAOAAkKFgBbVQEFAAAAAA==.Raesham:BAAANQAECgIIAwAAAA==.Ragemaster:BAAANQADCgYIDAAAAA==.Raginghunter:BAAANQADCgQIBAABNQADCgYIDAAFAAAAAA==.Raidbuff:BAAANQAECgIJAgAAAA==.Ralah:BAABNQAECoEZAAIPAAcKFRNrGwCeAQAPAAcKFRNrGwCeAQAAAA==.Ratdk:BAAANQAECgUIDQAAAA==.Raydoth:BAAANQAECggIDwAAAA==.Raziel:BAAANQADCgYIBgAAAA==.',
Re='Redi:BAAANQADCgYIBgAAAA==.Redouté:BAAANQADCgEIAQABNQAECggIDwAFAAAAAA==.Redsaint:BAAANQAECgYIEQAAAA==.Reinys:BAAANQAECgcIEwAAAA==.Reload:BAAANQAECgIIAgABNQAECggIEQAFAAAAAA==.Remiwolf:BAAANQADCggIDAAAAA==.Renniei:BAAANQAECgUIBwAAAA==.Renârd:BAAANQADCggICQAAAA==.Retpally:BAAANQADCgMIAwAAAA==.Rezispacqt:BAAANQAECgIIAwAAAA==.',
Rh='Rheha:BAAANQADCgYIBgAAAA==.Rhizah:BAAANQAECggIEAAAAA==.',
Ri='Richkrakbaby:BAAANQAECgYIDwAAAA==.Riskytriscut:BAAANQADCgMIAwAAAA==.Riyan:BAAANQADCggIDgAAAA==.',
Ro='Rob:BAAANQAECgUJBwAAAA==.Robinhoød:BAAANQAECgYIEwAAAA==.Robinn:BAAANQAECgQIBwAAAA==.Rocknmage:BAAANQAECgcIBgAAAA==.Rocknsham:BAAANQAECgMJAwAAAA==.Roosifer:BAAANQADCgIIAgAAAA==.Rossin:BAAANQAECgYIEgAAAA==.Routerslayrx:BAABNQAECoEWAAMeAAkK/CBJAgBJAwAeAAkKTiBJAgBJAwAbAAIKvxiOaQCeAAABNQAECgkJSQAjAMcmAA==.Roxington:BAAANQAECgEIAQAAAA==.',
Ry='Ryddlesr:BAAANQADCggICQAAAA==.Ryeshot:BAACNQAFFIEkAAITAAgK5yMrAABOAwATAAgK5yMrAABOAwA1AAQKgS0AAhMACQqxJv4AANkDABMACQqxJv4AANkDAAAA.Ryukotsuei:BAAANQAECgUICwAAAA==.Ryzonc:BAAANQABCgIIAgAAAA==.',
['Rë']='Rëëlix:BAAANQAECgQIBAAAAA==.',
['Rø']='Røcknpriest:BAAANQADCgcIBwAAAA==.',
Sa='Saeros:BAAANQADCgEIAQAAAA==.Sagemister:BAAANQADCgIIAgAAAA==.Saidin:BAAANQABCgIIBAAAAA==.Sange:BAAANQADCgQIBwAAAA==.Sanguinet:BAAANQAECgIJBAAAAA==.Sarlina:BAABNQAECoE/AAMRAAgK8BdPQQBAAgARAAgK8BdPQQBAAgATAAEKSASafgAeAAAAAA==.Sarrius:BAAANQABCgIIAgAAAA==.Sarudomi:BAACNQAFFIELAAMVAAUKKxj4DgBFAQAVAAQKmhb4DgBFAQAKAAIKeA15DQCYAAA1AAQKgR0AAxUACQr1Ia8SAB0DABUACQr1Ia8SAB0DAAoABAp3DQxGAMwAAAAA.Sarusham:BAAANQAECgcIEgAAAA==.Saruu:BAAANQAECgYICgAAAA==.Saruwu:BAAANQAECgYIBgAAAA==.Sarïss:BAAANQAECggIDwAAAA==.Savviana:BAAANQAECgMIBQAAAA==.',
Sb='Sbw:BAAANQAECgQIBQABNQAFFAUIDgAGAKAXAA==.',
Sc='Scalemor:BAABNQAECoEbAAILAAgKth21LQDCAgALAAgKth21LQDCAgAAAA==.Scales:BAAANQADCgUICAAAAA==.Scarlah:BAAANQAECgEIAQAAAA==.Sciel:BAAANQAECgUIEwAAAA==.Scrabbles:BAABNQAECoEaAAICAAgKUR4LJwCoAgACAAgKUR4LJwCoAgAAAA==.',
Se='Secretwife:BAAANQAECgYICAAAAA==.Senara:BAABNQAECoEaAAIJAAcKdxhgqAAQAgAJAAcKdxhgqAAQAgAAAA==.Sendriss:BAAANQAECgQIBAAAAA==.Sephoniara:BAAANQAECgEIAQAAAA==.Sephonie:BAAANQADCgIIAwAAAA==.Serath:BAAANQAECgMJBAAAAA==.Setralan:BAAANQABCgQIBAAAAA==.',
Sh='Shaded:BAAANQABCgIIAgAAAA==.Shadowfactor:BAAANQAECgIIAgAAAA==.Shadowhawks:BAAANQAECgUICwAAAA==.Shadownej:BAAANQAECgIIAgAAAA==.Shadowsteel:BAAANQADCgkJEAAAAA==.Shamonlee:BAAANQAECgUIEAAAAA==.Shamydracdad:BAAANQADCggIDgABNQAECgMIBgAFAAAAAA==.Shapaladin:BAAANQADCggICAABNQAECgQIBgAFAAAAAA==.Sheepdoll:BAAANQAECgcIEwAAAA==.Shengo:BAAANQADCgEIAQAAAA==.Sherfin:BAAANQAECgQIBQAAAA==.Sheshindy:BAABNQAECoEdAAIkAAcKuQ+mCQC9AQAkAAcKuQ+mCQC9AQAAAA==.Shiftfour:BAAANQABCgEIAQAAAA==.Shiftysmom:BAABNQAECoE9AAIOAAgKhRieXwBQAgAOAAgKhRieXwBQAgAAAA==.Shigz:BAAANQADCgYIBgABNQAECgYIDwAFAAAAAA==.Shinigamì:BAAANQAECgQIDAAAAA==.Shocklock:BAAANQAECggJEAAAAA==.Shogun:BAABNQAECoEhAAIbAAgKCxRXLgAFAgAbAAgKCxRXLgAFAgAAAA==.Shortypie:BAAANQABCgIIAgAAAA==.Shrimpngrits:BAAANQADCgMIBAAAAA==.Shylø:BAAANQAECggICAAAAA==.Shámázing:BAAANQAECgQIBgAAAA==.Shåcø:BAACNQAFFIEHAAINAAQKvA9hCABFAQANAAQKvA9hCABFAQA1AAQKgTAAAw0ACQqKIv8DAIYDAA0ACQqKIv8DAIYDAB8ACAoEG7UUADACAAE1AAUUBAoHAA0AvA8A.',
Si='Sickmoves:BAAANQADCgQIBAAAAA==.Sillyheals:BAAANQAECgEIAQABNQAECggIEgAFAAAAAA==.Sillyness:BAAANQADCgcJBgABNQAECggIEgAFAAAAAA==.Sillypálly:BAAANQAECggIEgAAAA==.Sinatra:BAAANQADCgMIBAAAAA==.Sindorael:BAAANQADCgQIBAAAAA==.Sinknight:BAAANQAECgcJCgAAAA==.Sithweaver:BAAANQADCgUIBgAAAA==.',
Sk='Skateorpie:BAABNQAECoEWAAINAAYKZRZmOwCjAQANAAYKZRZmOwCjAQAAAA==.Skeebadae:BAABNQAECoEaAAIHAAgKmRubCwCgAgAHAAgKmRubCwCgAgAAAA==.Skelestar:BAABNQAECoEgAAIVAAkK5CFFCwBkAwAVAAkK5CFFCwBkAwAAAA==.Skrt:BAAANQADCgIIAgAAAA==.Skullx:BAAANQAECgQIBAABNQAECgkJHAAJAGUaAA==.Skädir:BAAANQAECgEIAQABNQAECgkJKwAJAFsQAA==.',
Sl='Slayabunny:BAABNQAECoEjAAMOAAgKuiIfLgDxAgAOAAgKpCEfLgDxAgApAAUKMRhAHgA2AQAAAA==.Slep:BAABNQAECoEXAAIcAAgKABydAwCnAgAcAAgKABydAwCnAgAAAA==.Slepslep:BAAANQADCggIEAABNQAECggIFwAcAAAcAA==.Slepybaer:BAAANQADCgYICQABNQAECggIFwAcAAAcAA==.Slimzilla:BAABNQAECoE4AAMUAAkKhSRtAgC1AwAUAAkKZiRtAgC1AwABAAQKNhAfjwDGAAAAAA==.',
Sm='Smaugdan:BAAANQAECgYIBQABNQAFFAUICgAIANoQAA==.Smaugkfc:BAAANQAECggIBgABNQAFFAUICgAIANoQAA==.Smaugkitten:BAAANQADCgUIBQABNQAFFAUICgAIANoQAA==.Smaugvoker:BAAANQADCgYICQABNQAFFAUICgAIANoQAA==.Smegatron:BAAANQAECgUIDQAAAA==.Smoosh:BAAANQAECggIEQAAAA==.',
Sn='Sneakyaggro:BAAANQADCgcIDQABNQAECgUIDAAFAAAAAA==.Sneakyheals:BAAANQAECgUIDAAAAA==.Sneakyrage:BAABNQAECoEYAAIOAAcKsxVZjQDUAQAOAAcKsxVZjQDUAQAAAA==.Snipedya:BAAANQAECgYIEgAAAA==.Snolin:BAAANQAECgMIBwAAAA==.Snowblowwer:BAAANQADCgIIAgAAAA==.Snowyrainz:BAAANQAECgIIAwAAAA==.',
So='Soliat:BAABNQAECoEcAAIJAAgKcQ4jywDLAQAJAAgKcQ4jywDLAQAAAA==.Sooblysham:BAAANQAECgYIBwAAAA==.Soulshadez:BAAANQADCggICAAAAA==.Southpau:BAAANQABCgUIBQABNQAECgYIBgAFAAAAAA==.Souupded:BAAANQAECgcIEgAAAA==.',
Sp='Spamzvoltz:BAAANQAECgcIEwAAAA==.Sparklies:BAAANQADCgMIBAABNQAECgMIAwAFAAAAAA==.Spedometers:BAABNQAECoEaAAIaAAcKNiKrQQCqAgAaAAcKNiKrQQCqAgAAAA==.Spedometre:BAAANQAECgIIAgABNQAECgcIGgAaADYiAA==.Spee:BAAANQABCgQIBAAAAA==.Spoondk:BAAANQAECgcIBwAAAA==.Sprinkel:BAAANQADCgMIAwAAAA==.',
Sq='Squrly:BAAANQABCgIJBAAAAA==.',
Ss='Ssjorion:BAAANQADCgMIAwAAAA==.Ssjryukan:BAAANQADCgYICwAAAA==.',
St='Stacybeam:BAABNQAECoEaAAMIAAkKUx5oEADcAgAIAAkKUx5oEADcAgAbAAEKOwmPgwAzAAAAAA==.Standune:BAAANQAECgUIDwAAAA==.Starrie:BAAANQAECgcJBwAAAA==.Staticshock:BAAANQAECgEIAQAAAA==.Steakñbake:BAAANQADCggIFQAAAA==.Stealthylick:BAAANQAECgYIEQAAAA==.Stelus:BAAANQAECgYIEQAAAA==.Stereosity:BAAANQAECgQIBgABNQAECgkJMQARALckAA==.Stickobutter:BAABNQAECoEWAAIOAAcKhQ8ymgCxAQAOAAcKhQ8ymgCxAQAAAA==.Stoicism:BAAANQAECgUIBQAAAA==.Stopngo:BAAANQADCgcICAAAAA==.',
Su='Sukuna:BAAANQAECgQICAAAAA==.Sunai:BAAANQAECgQIBwAAAA==.Suntra:BAAANQADCgMIAwAAAA==.Supbro:BAAANQADCgMIAwAAAA==.Suraxon:BAAANQADCgIIAgAAAA==.Suspenders:BAAANQAECgUIEAAAAA==.',
Sy='Sykodude:BAABNQAECoEhAAILAAgKhBpNSwBkAgALAAgKhBpNSwBkAgAAAA==.Sykodudet:BAAANQAECgQIBAABNQAECggIIQALAIQaAA==.Sykomage:BAAANQABCgUJBQAAAA==.Sykototem:BAAANQADCgQIBAABNQAECggIIQALAIQaAA==.Sylvanassimp:BAAANQAECgUIDAAAAA==.Syrac:BAAANQADCgYIBgAAAA==.',
Ta='Taelil:BAAANQAECgQICAAAAA==.Tailented:BAABNQAECoEdAAMPAAgKVA7dGgCnAQAPAAgKVA7dGgCnAQAoAAYK/AFWIQCtAAAAAA==.Takadra:BAAANQADCggIHQAAAA==.Tanalock:BAAANQAECgUIEgAAAA==.Tanalord:BAABNQAECoEdAAIJAAkK9yR1CgCpAwAJAAkK9yR1CgCpAwABNQAFFAUICwAIAIUhAA==.Tarly:BAAANQADCgQIBAAAAA==.Taro:BAAANQAECgQIBgAAAA==.Tatertot:BAABNQAECoEfAAICAAgKFR8NKgCYAgACAAgKFR8NKgCYAgAAAA==.Tayrn:BAAANQAECgMIBAAAAA==.',
Te='Teaswift:BAAANQAECgYICQABNQAECggIGgAVAHkZAA==.Temuwhooper:BAAANQAECgQIBAABNQAECgkJMQARALckAA==.',
Th='Thalyn:BAAANQADCgQIBAABNQAECggIGAAKAMYNAA==.Thandaril:BAAANQAECgMIBAAAAA==.Tharn:BAAANQADCgYJBgABNQADCggIDwAFAAAAAA==.Theduckler:BAAANQADCgUIBQAAAA==.Thelonliest:BAABNQAECoEaAAMVAAgKeRkeNQAYAgAVAAcKzxceNQAYAgAKAAUKvRZSMwBLAQAAAA==.Thornstaad:BAABNQAECoEgAAIMAAgKOhOGIwAQAgAMAAgKOhOGIwAQAgAAAA==.Thrashmor:BAAANQAECgMJAwAAAA==.Threetimex:BAAANQAECgIIAgAAAA==.Throckmortus:BAAANQAECgMIAwAAAA==.Thuggymage:BAABNQAECoE2AAIJAAkKrhORnQAnAgAJAAkKrhORnQAnAgAAAA==.Thunderboom:BAAANQAECgcIDgAAAA==.Thundercles:BAAANQAECgUIDgAAAA==.Thunderstruk:BAAANQADCgQIBAAAAA==.Thyself:BAABNQAECoEdAAIPAAgKjBFDGQC8AQAPAAgKjBFDGQC8AQAAAA==.Thór:BAAANQADCgUIBQAAAA==.',
Ti='Tictactotem:BAAANQADCgQIBAAAAA==.Tidebadra:BAABNQAECoEhAAIHAAgK8CM+BABKAwAHAAgK8CM+BABKAwAAAA==.Tideradra:BAACNQAFFIEkAAMGAAgKSyHCAADPAgAGAAcKZiHCAADPAgACAAIKGAWRHgCIAAA1AAQKgSMAAwYACQqrJcUGAKkDAAYACQqrJcUGAKkDAAIACApmDv92AHgBAAAA.Ting:BAAANQAECgYICwAAAA==.Tirays:BAAANQAECgEIAQAAAA==.',
Tk='Tkd:BAAANQAECgEIAQABNQAECgQJCgAFAAAAAA==.',
To='Toats:BAAANQADCgUIBwAAAA==.Toixic:BAABNQAFFIEGAAIPAAUKOhCyAwCWAQAPAAUKOhCyAwCWAQABNQAFFAgIHwACAMcNAA==.Toixtem:BAACNQAFFIEfAAICAAgKxw3BAQCBAgACAAgKxw3BAQCBAgA1AAQKgRgAAgIACQr1IBUlALICAAIACQr1IBUlALICAAAA.Tomfoolery:BAAANQADCgQIBAAAAA==.Tootihunt:BAACNQAFFIERAAMLAAYKxCIuDgA6AQAMAAQKNR1NCwBjAQALAAMKwSIuDgA6AQA1AAQKgSQAAwwACQqQJBgIAEQDAAwACQozJBgIAEQDAAsABwoXHYyIAMkBAAAA.Topg:BAAANQAECgQIDAAAAA==.Totmdispenzr:BAAANQAECgIIAgAAAA==.Toukai:BAAANQADCggIGwABNQAECgUIEAAFAAAAAA==.Toukuhd:BAAANQAECgUIEAAAAA==.',
Tr='Traia:BAAANQADCgYICgAAAA==.Tralinadia:BAAANQADCggICAAAAA==.Travaxian:BAAANQADCgYIBgAAAA==.Trendz:BAAANQABCgQICQAAAA==.Trihold:BAAANQADCgEIAQAAAA==.Trog:BAAANQADCgUIBQAAAA==.',
Ts='Tselli:BAAANQAECgQICwABNQAECgkJLAAHAA4iAA==.Tsellie:BAABNQAECoEsAAMHAAkKDiKCAgCAAwAHAAkKDiKCAgCAAwACAAcKcBgBXQDJAQAAAA==.Tselliepally:BAAANQAECgYIDgABNQAECgkJLAAHAA4iAA==.',
Tu='Tuktukk:BAAANQADCgcIBwAAAA==.Tulas:BAAANQAECgEIAgAAAA==.Tumbler:BAAANQAECgQICAAAAA==.Turkleton:BAAANQAFFAMIBAAAAA==.',
Tw='Twobelow:BAAANQADCgEIAQAAAA==.Twístedteå:BAAANQAECgQIBgAAAA==.',
Ty='Tylos:BAAANQADCggIDAAAAA==.Tyraxous:BAABNQAECoEYAAIbAAgKDw4GNgDMAQAbAAgKDw4GNgDMAQAAAA==.Tyrinnà:BAAANQADCgYICgAAAA==.',
['Tö']='Törryn:BAABNQAECoEWAAIjAAcKuQjgJQAgAQAjAAcKuQjgJQAgAQAAAA==.',
Ul='Ulah:BAAANQADCgcIIQAAAA==.',
Un='Unholyarrie:BAAANQADCgEIAQAAAA==.Unholybaine:BAAANQADCgIIAgAAAA==.Unknownz:BAABNQAECoEeAAMBAAkKISJLKQByAgABAAcKQCJLKQByAgAUAAgKvRSOLgD2AQAAAA==.Unstopubble:BAABNQAECoFHAAIEAAgKPyG3CAD3AgAEAAgKPyG3CAD3AgAAAA==.',
Up='Upyouràrthas:BAAANQAECgMIBgAAAA==.',
Us='Ushinoken:BAAANQABCgEIAQAAAA==.',
Uu='Uuchi:BAAANQAECgQIBQAAAA==.',
Va='Vaariks:BAAANQAECgYIEQAAAA==.Vaera:BAAANQAECgQICgAAAA==.Valeindia:BAAANQAECgQIAgAAAA==.Valenia:BAAANQAECggICAAAAA==.Valgrimm:BAAANQADCgQIBAAAAA==.Valgrin:BAAANQAECgQIBAAAAA==.Valianthe:BAAANQAECgUIDgAAAA==.Valner:BAABNQAECoEVAAMOAAcKQwM41wAJAQAOAAcKQwM41wAJAQAZAAMKuwEoKgBCAAAAAA==.Valthyria:BAAANQAECgcIDgAAAA==.Vandamnit:BAAANQADCgcIBwAAAA==.Vanessaboo:BAAANQAECggIEQABNQAFFAgIJQABAP0lAA==.Varnaxon:BAAANQADCgQIBAAAAA==.',
Ve='Vebel:BAAANQAECgEIAgAAAA==.Vegara:BAAANQADCgMIAwAAAA==.Velthyr:BAAANQADCgIIAgABNQADCggICAAFAAAAAA==.Velínthelyn:BAAANQADCgUIBAAAAA==.Vexthall:BAAANQADCgIIAgAAAA==.',
Vi='Vikingdrood:BAABNQAECoETAAIVAAgKwhniMgAnAgAVAAgKwhniMgAnAgAAAA==.Vikingj:BAAANQADCggIEAABNQAECggIEwAVAMIZAA==.Vikingsham:BAAANQADCgcIBwABNQAECggIEwAVAMIZAA==.Vinnyfr:BAABNQAECoE0AAMfAAkKvCApBABMAwAfAAkKViApBABMAwANAAgKNBoZGgCEAgAAAA==.Virsaviya:BAAANQAECgQICAAAAA==.Viwi:BAAANQAECgYIEwAAAA==.',
Vo='Voidmelky:BAAANQADCgIIAgAAAA==.Vorthak:BAAANQAECgUIBQAAAA==.',
Vu='Vulair:BAAANQAECgUICQABNQAECgkJMgAbABgcAA==.',
Vy='Vyrandar:BAAANQADCggIDgAAAA==.',
Wa='Warraxhunt:BAAANQAECgUIBAAAAA==.Warraxrage:BAABNQAECoEwAAMOAAkKoR5oLQD0AgAOAAkKgx5oLQD0AgAZAAQKSBsDEwBIAQAAAA==.Warwings:BAAANQAECgQICAAAAA==.Watanabi:BAAANQAECgQIBQAAAA==.',
We='Welky:BAAANQADCgIIAgAAAA==.',
Wh='Wheel:BAABNQAECoEeAAITAAgK7h60EQDEAgATAAgK7h60EQDEAgAAAA==.',
Wi='Wickey:BAAANQADCgYIBgAAAA==.Winc:BAAANQADCgIIAgAAAA==.',
Wo='Wonsmash:BAABNQAECoEWAAIOAAcKiBRKjwDPAQAOAAcKiBRKjwDPAQAAAA==.',
Wy='Wynndiego:BAABNQAECoEaAAIVAAcKxxFvRQCuAQAVAAcKxxFvRQCuAQAAAA==.Wyrmslayer:BAACNQAFFIEMAAIOAAUKuBWFDAC2AQAOAAUKuBWFDAC2AQA1AAQKgR0AAg4ACQqkIF0mABADAA4ACQqkIF0mABADAAAA.',
Xa='Xaidra:BAACNQAFFIErAAIgAAgKjBLNAQCCAgAgAAgKjBLNAQCCAgA1AAQKgS0AAiAACQoDIWUIABADACAACQoDIWUIABADAAAA.Xanatu:BAAANQAECgcIDwAAAA==.Xandyr:BAAANQAECgIIAgAAAA==.',
Xe='Xedk:BAABNQAECoEuAAIBAAgKqQ8VUACqAQABAAgKqQ8VUACqAQAAAA==.Xenzlok:BAAANQAECgUICQABNQAECgcIGgAJAHcYAA==.Xepherite:BAAANQAECgYIDQABNQAFFAQICgAGAPEiAA==.Xephsham:BAACNQAFFIEKAAIGAAQK8SL5CQCdAQAGAAQK8SL5CQCdAQA1AAQKgR0AAgYACQr8IjgSAEoDAAYACQr8IjgSAEoDAAAA.Xetholosa:BAAANQAECgQICAAAAA==.Xethoscope:BAAANQAECgMIBQAAAA==.',
Ya='Yarayara:BAAANQADCggICAAAAA==.Yautja:BAAANQAECgMIAwABNQAECggIIwAIABQaAA==.',
Yo='Yogafire:BAAANQADCgcIBwABNQAECgYIGgAXALYjAA==.Yozu:BAAANQADCgEIAQAAAA==.',
Yu='Yuimage:BAAANQAECgYIEAAAAA==.',
['Yö']='Yögifox:BAAANQAECgMJAwABNQAECgQIBAAFAAAAAA==.',
Za='Zaene:BAAANQAECgYIEAAAAA==.Zafyria:BAAANQAECgUIEAAAAA==.Zalea:BAACNQAFFIEsAAIJAAgK0iNsAABKAwAJAAgK0iNsAABKAwA1AAQKgTQAAgkACQpiJqMDANkDAAkACQpiJqMDANkDAAAA.Zaluid:BAAANQAECgYJCQABNQAFFAgILAAJANIjAA==.',
Ze='Zekkial:BAABNQAECoEdAAIHAAgKIhpXDQB+AgAHAAgKIhpXDQB+AgAAAA==.Zendroza:BAAANQADCggJFwABNQAECgUIEwAFAAAAAA==.Zerks:BAAANQADCgQIBAAAAA==.',
Zi='Zippyzapper:BAAANQAECgUICAAAAA==.',
Zl='Zlliks:BAAANQADCgQIBAAAAA==.',
Zo='Zoekai:BAAANQAECgUIEAAAAA==.Zolar:BAAANQADCggJDAAAAA==.Zonovar:BAABNQAECoEmAAIHAAkKSiPYAgBzAwAHAAkKSiPYAgBzAwAAAA==.',
Zu='Zurks:BAABNQAECoEjAAMSAAgK5BjXBABVAgASAAgK5BjXBABVAgATAAEKhwPgeAAkAAAAAA==.Zurkz:BAABNQAECoEeAAIKAAkKLCBEBgBMAwAKAAkKLCBEBgBMAwAAAA==.',
['Zà']='Zàddy:BAABNQAECoEZAAQbAAgKUhEqPgCTAQAbAAcKSA4qPgCTAQAIAAYKoBK2NQBvAQAeAAEKPwZeLwAjAAAAAA==.',
['Äz']='Äzalea:BAAANQADCggJCAABNQAECgcIFgAIAP0YAA==.Äzræll:BAAANQADCggIFgAAAA==.',
['Ås']='Åshborn:BAAANQAFFAIIBAAAAA==.',
['Ér']='Érìs:BAAANQAECgUIDQABNQAECggIIQAOAH8aAA==.',
['Ði']='Ðixiewrecked:BAABNQAECoEcAAIZAAgKLSIcAwARAwAZAAgKLSIcAwARAwAAAA==.',
['Ðu']='Ðuck:BAAANQAECgEIAQAAAA==.',
['ßo']='ßooyeah:BAAANQAECgUICQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
