local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Rogue-Assassination','Monk-Windwalker','Warlock-Affliction','Warlock-Destruction','Warlock-Demonology','Evoker-Augmentation','Unknown-Unknown','Evoker-Devastation','Evoker-Preservation','Rogue-Subtlety','Mage-Frost','Mage-Arcane','Paladin-Holy','Paladin-Retribution','Priest-Holy','Hunter-Marksmanship','Hunter-BeastMastery','Hunter-Survival','Druid-Feral','DemonHunter-Devourer','DemonHunter-Vengeance','Priest-Discipline','DeathKnight-Unholy','Priest-Shadow','Shaman-Enhancement','Mage-Fire','DeathKnight-Blood','DeathKnight-Frost','Paladin-Protection','Monk-Brewmaster','Rogue-Outlaw','Shaman-Elemental','Warrior-Arms','Warrior-Protection','Druid-Guardian','Shaman-Restoration','Druid-Restoration','Druid-Balance','DemonHunter-Havoc',}
local provider = {region='US',realm='Frostmourne',name='US',type='subscribers',zone=53,date='2026-09-22',data={Ab='Abstinate:BAECNQAFFIERAAIBAAYKzB2JAABOAgaODQAABABFAHUNAAADAEMAfw0AAAMASgCpDQAAAgBEAFwNAAACAFQAMw0AAAMAXQABAAYKzB2JAABOAgaODQAABABFAHUNAAADAEMAfw0AAAMASgCpDQAAAgBEAFwNAAACAFQAMw0AAAMAXQA1AAQKgScAAgEACQplJacBAKkDAAEACQplJacBAKkDAAAA.',
Ae='Aenospin:BAEBNQAECoEeAAICAAkKzCGLBgAvAwmODQAABABfAHUNAAADAEYAfw0AAAMAVQCpDQAAAwBNAFwNAAADAGAAXQ0AAAMAVQBlDQAABABfAKQNAAAEAE8AMw0AAAMAXAACAAkKzCGLBgAvAwmODQAABABfAHUNAAADAEYAfw0AAAMAVQCpDQAAAwBNAFwNAAADAGAAXQ0AAAMAVQBlDQAABABfAKQNAAAEAE8AMw0AAAMAXAAAAA==.',
Af='Afflictweave:BAEBNQAECoEWAAQDAAkKPQ7qAwA9AgmODQAAAwAiAHUNAAADABsAfw0AAAMAKQCpDQAAAwBIAFwNAAABACAAXQ0AAAMAIwBlDQAAAwAVAKQNAAABACQAMw0AAAIAGQADAAkKPQ7qAwA9AgmODQAAAwAiAHUNAAACABsAfw0AAAMAKQCpDQAAAwBIAFwNAAABACAAXQ0AAAMAIwBlDQAAAgAVAKQNAAABACQAMw0AAAIAGQAEAAEKcAiKaQAxAAF1DQAAAQAVAAUAAQrpAaTpADEAAWUNAAABAAQAAAA=.',
An='Andalusia:BAEBNQAECoEdAAIGAAcKwQsrCQBfAQeODQAABgAhAHUNAAAEABkAfw0AAAQAIACpDQAABAAoAFwNAAADABQAXQ0AAAIAEQAzDQAABgAoAAYABwrBCysJAF8BB44NAAAGACEAdQ0AAAQAGQB/DQAABAAgAKkNAAAEACgAXA0AAAMAFABdDQAAAgARADMNAAAGACgAAAA=.',
As='Assbringger:BAEANQADCgUIBQABNQAECgQIDQAHAAAAAA==.Asukakira:BAECNQAFFIEFAAMFAAMKugO/GwCIAAOODQAAAgANAHUNAAABAAUAqQ0AAAIACQAFAAIKyQO/GwCIAAKODQAAAgANAHUNAAABAAUABAABCp0DQxYARwABqQ0AAAIACQA1AAQKgSkAAwQACQoWIVgNAAMCAAQABgqIHFgNAAMCAAUABgrhHXhMAO0BAAAA.',
Au='Augmentation:BAEBNQAECoEaAAIGAAgKACCIAgDoAgiODQAABABVAHUNAAAEAFsAfw0AAAQAWQCpDQAABABSAFwNAAADAEwAXQ0AAAIAWABlDQAAAQAyADMNAAAEAFsABgAICgAgiAIA6AIIjg0AAAQAVQB1DQAABABbAH8NAAAEAFkAqQ0AAAQAUgBcDQAAAwBMAF0NAAACAFgAZQ0AAAEAMgAzDQAABABbAAAA.Augtisim:BAECNQAFFIEPAAMGAAYKvRXrAAAUAgaODQAAAwBFAHUNAAADAE0Afw0AAAIAEACpDQAAAwBIAFwNAAABAC4AMw0AAAMAMwAGAAYKvRXrAAAUAgaODQAAAwBFAHUNAAADAE0Afw0AAAIAEACpDQAAAgBIAFwNAAABAC4AMw0AAAEAMwAIAAIKIApuCACGAAKpDQAAAQANADMNAAACACYANQAECoEeAAQGAAkKACPHAQAvAwAGAAkKACPHAQAvAwAIAAYKsBSJFgCEAQAJAAEKrQEPPQAoAAAAAA==.',
Av='Avaelyne:BAEBNQAECoEgAAMBAAkKdRvsEQB2AgmODQAABQBcAHUNAAAEAEkAfw0AAAQAPQCpDQAABAA7AFwNAAAEAFYAXQ0AAAMASQBlDQAAAwBBAKQNAAACADUAMw0AAAMAQwAKAAkKDxVSDACBAgmODQAABABFAHUNAAADAEkAfw0AAAMAPQCpDQAAAwA0AFwNAAADADQAXQ0AAAIAQQBlDQAAAgAWAKQNAAABABMAMw0AAAMAQwABAAgKwBfsEQB2AgiODQAAAQBcAHUNAAABAA0Afw0AAAEAKgCpDQAAAQA7AFwNAAABAFYAXQ0AAAEASQBlDQAAAQBBAKQNAAABADUAAAA=.',
Az='Azzarage:BAEANQAECgYIBgABNQAFFAQJBwALALcaAA==.Azzaraze:BAECNQAFFIEHAAMLAAQKtxokAgCvAASODQAAAgBRAHUNAAABADIAqQ0AAAIASgAzDQAAAgBDAAwAAgoFHfgfALgAAo4NAAACAFEAMw0AAAIAQwALAAIKaBgkAgCvAAJ1DQAAAQAyAKkNAAACAEoANQAECoEoAAMMAAkKNyXrBwCtAwAMAAkKliTrBwCtAwALAAIKXibNFADkAAAAAA==.',
Ba='Baldchud:BAEBNQAECoEgAAMNAAkKnBYUPQADAgmODQAAAgBDAHUNAAACAC4Afw0AAAIAPQCpDQAAAgBHAFwNAAACAFQAXQ0AAAIASQBlDQAACAAWAKQNAAAKAFgAMw0AAAIABAANAAcKcxYUPQADAgeODQAAAgBDAH8NAAACAD0AXA0AAAIAVABdDQAAAgBJAGUNAAACABYApA0AAAoAWAAzDQAAAgAEAA4AAwruIMuwAAUBA3UNAAACAFMAqQ0AAAIATwBlDQAABgBaAAE1AAQKCAgBAAcAAAAA.Barakoshama:BAEANQAECgcIDwABNQAFFAYJEQANANgkAA==.',
Be='Bert:BAECNQAFFIEHAAIPAAMKmAm1DgDtAAOODQAAAwAwAKkNAAADAA4AMw0AAAEACwAPAAMKmAm1DgDtAAOODQAAAwAwAKkNAAADAA4AMw0AAAEACwA1AAQKgRgAAg8ACQrNG94TAOECAA8ACQrNG94TAOECAAAA.Berti:BAEANQADCgYIBgABNQAFFAMJBwAPAJgJAA==.Bertos:BAEANQAECggJDQABNQAFFAMJBwAPAJgJAA==.',
Bl='Blupakhet:BAECNQAFFIEHAAIQAAMKEQ5zDADeAAOODQAAAwATAKkNAAACAC0AMw0AAAIAKgAQAAMKEQ5zDADeAAOODQAAAwATAKkNAAACAC0AMw0AAAIAKgA1AAQKgSIAAxAACQqWHbMXAEcCABAACAr5GrMXAEcCABEABgp9GZdwAJwBAAE1AAEKAwkDAAcAAAAA.',
Ca='Calonclaw:BAEANQAECgIJAgABNQAFFAUICwARAK0jAA==.Calzurv:BAECNQAFFIELAAQRAAUKrSMjAQAKAgWODQAAAgBgAHUNAAACAGMAfw0AAAEARQCpDQAAAwBfADMNAAADAGAAEQAFCq0jIwEACgIFjg0AAAIAYAB1DQAAAQBjAH8NAAABAEUAqQ0AAAMAXwAzDQAAAgBgABIAAQoBEP4AAF4AAXUNAAABACgAEAABCisSHRQATwABMw0AAAEALgA1AAQKgSUABBEACQrQJtABANUDABEACQrQJtABANUDABIABgpYHrkFAMABABAAAgr/IYRGAIoAAAAA.Capzíen:BAEBNQAECoEgAAITAAkK5R5xAgA+AwmODQAABQBdAHUNAAAEAF4Afw0AAAQAVgCpDQAABAA5AFwNAAAEAFMAXQ0AAAMATgBlDQAAAwBJAKQNAAACADoAMw0AAAMAVgATAAkK5R5xAgA+AwmODQAABQBdAHUNAAAEAF4Afw0AAAQAVgCpDQAABAA5AFwNAAAEAFMAXQ0AAAMATgBlDQAAAwBJAKQNAAACADoAMw0AAAMAVgAAAA==.',
Ce='Ceruuledge:BAEBNQAECoEkAAMUAAkKlw+wGQA8AgmODQAABgA3AHUNAAAEACUAfw0AAAUAHQCpDQAABgAVAFwNAAAFADMAXQ0AAAMAOQBlDQAAAwApAKQNAAABAA0AMw0AAAMAMgAUAAkKdA+wGQA8AgmODQAABAA3AHUNAAACACUAfw0AAAIAHQCpDQAAAwASAFwNAAADADMAXQ0AAAMAOQBlDQAAAQApAKQNAAABAA0AMw0AAAMAMgAVAAYKuQbMEAD0AAaODQAAAgAHAHUNAAACAB4Afw0AAAMADQCpDQAAAwAVAFwNAAACAAoAZQ0AAAIAEwABNQAECgkJKgAMACEkAA==.',
Cr='Craftyp:BAEANQAECggJAQAAAA==.Crunchforce:BAEBNQAECoEaAAMWAAgKIw9BDQAAAQiODQAABAAzAHUNAAAEACgAfw0AAAQAPwCpDQAABAAeAFwNAAADACcAXQ0AAAIACwBlDQAAAQAFADMNAAAEAEMADwAHCgQRgVYAfwEHjg0AAAQAMwB1DQAAAwAoAH8NAAADAD8AqQ0AAAMAHgBcDQAAAgAnAF0NAAACAAsAMw0AAAQAQwAWAAUKUQpBDQAAAQV1DQAAAQAjAH8NAAABACEAqQ0AAAEAGQBcDQAAAQAgAGUNAAABAAUAAAA=.',
Di='Digitaldj:BAEANQAECgUJBwAAAA==.',
Dp='Dpsmywifeirl:BAEANQABCggICgABNQABCggIEgAHAAAAAA==.',
Du='Dubber:BAEANQAECgYJDAABNQAFFAcJFQAXAAcZAA==.Dubsx:BAEANQAECgYJCAABNQAFFAcJFQAXAAcZAA==.',
Dw='Dwak:BAEANQAECgcIDQABNQAECgkJIQAIAP8hAA==.Dwakakiwi:BAEBNQAECoEhAAIIAAkK/yHyAwA7AwmODQAABQBhAHUNAAADAFsAfw0AAAEAVwCpDQAABQBhAFwNAAACACUAXQ0AAAEAWABlDQAABgBdAKQNAAAGAFsAMw0AAAQAYQAIAAkK/yHyAwA7AwmODQAABQBhAHUNAAADAFsAfw0AAAEAVwCpDQAABQBhAFwNAAACACUAXQ0AAAEAWABlDQAABgBdAKQNAAAGAFsAMw0AAAQAYQAAAA==.',
Ea='Earthenenh:BAEANQAECgcJCAABNQAFFAMJBQAFALoDAA==.Eatsrats:BAEBNQAECoEvAAQIAAkKRB+fBAAmAwmODQAABgBFAHUNAAAGAF4Afw0AAAYAVwCpDQAABgBTAFwNAAAEAFUAXQ0AAAYAWgBlDQAABgBQAKQNAAADADoAMw0AAAQARwAIAAkKRB+fBAAmAwmODQAABgBFAHUNAAAFAF4Afw0AAAUAVwCpDQAABQBTAFwNAAABAFUAXQ0AAAUAWgBlDQAABgBQAKQNAAADADoAMw0AAAIARwAJAAYKGQOIJwDuAAZ1DQAAAQAOAH8NAAABAAYAqQ0AAAEACQBcDQAAAgADAF0NAAABAAEAMw0AAAIACgAGAAEK1x3uFABWAAFcDQAAAQBMAAAA.',
Ep='Epidestro:BAECNQAFFIEMAAMEAAUKOxDqAwDGAAWODQAAAwAvAHUNAAACACQAfw0AAAEACgCpDQAAAwBdADMNAAADABQABQAECvML8QgALAEEjg0AAAMALwB/DQAAAQAKAKkNAAACACwAMw0AAAMAFAAEAAIKUhnqAwDGAAJ1DQAAAgAkAKkNAAABAF0ANQAECoEjAAMFAAkK6SG6EgD6AgAFAAgKcCG6EgD6AgAEAAYKeRheEgDIAQAAAA==.',
Fa='Faelaelae:BAECNQAFFIEPAAMYAAUKshQLAwCtAQWODQAABABMAHUNAAADAC0Afw0AAAMAIACpDQAAAwBLADMNAAACACIAGAAFCrIUCwMArQEFjg0AAAMATAB1DQAAAwAtAH8NAAADACAAqQ0AAAMASwAzDQAAAgAiAA8AAQrTB8AdAEwAAY4NAAABABQANQAECoEmAAMYAAkKUCSHAgClAwAYAAkKUCSHAgClAwAPAAEKZwatpgA/AAAAAA==.',
Fj='Fj:BAEANQAECgMIAwABNQAFFAUICgAZACchAA==.Fjz:BAECNQAFFIEKAAIZAAUKJyGDAAAAAgWODQAAAgBXAHUNAAACAGAAfw0AAAIAXACpDQAAAwA6ADMNAAABAFkAGQAFCichgwAAAAIFjg0AAAIAVwB1DQAAAgBgAH8NAAACAFwAqQ0AAAMAOgAzDQAAAQBZADUABAqBJQACGQAJCoslYwAA4QMAGQAJCoslYwAA4QMAAAA=.',
Fl='Flapzien:BAEANQADCgYICQABNQAECgkJIAATAOUeAA==.Flayorius:BAEANQAECgYJCQAAAA==.Floorqt:BAEANQAECggIDgABNQAFFAcIGQAGAEkkAA==.Flowito:BAECNQAFFIEOAAMKAAYKDxjAAgDTAQaODQAAAwA6AHUNAAADAEsAfw0AAAMAUgCpDQAAAQA+AFwNAAABABEAMw0AAAMASQAKAAUKcxTAAgDTAQWODQAAAwA6AHUNAAADAEsAfw0AAAMAUgBcDQAAAQARADMNAAACABwAAQACCp4a5gYAtQACqQ0AAAEAPgAzDQAAAQBJADUABAqBJAADAQAJCqQlNhAAjgIAAQAHCkQgNhAAjgIACgAFChMmfxMAFwIAAAA=.Fluffyst:BAEBNQAECoEVAAIMAAgKTg85gwAPAgiODQAAAwA7AHUNAAADADQAfw0AAAMAIwCpDQAAAwA5AFwNAAADAB8AXQ0AAAMALgBlDQAAAgAJAKQNAAABABQADAAICk4POYMADwIIjg0AAAMAOwB1DQAAAwA0AH8NAAADACMAqQ0AAAMAOQBcDQAAAwAfAF0NAAADAC4AZQ0AAAIACQCkDQAAAQAUAAE1AAUUBgkPAAQAFhYA.Fluffyswl:BAECNQAFFIEPAAQEAAYKFhbfBAC9AAaODQAAAwA+AHUNAAADAE8Afw0AAAMACwCpDQAAAwBPAFwNAAABADoAMw0AAAIALgAFAAMKRBFLDQD0AAOODQAAAwA+AH8NAAADAAsAXA0AAAEAOgAEAAIKMx/fBAC9AAJ1DQAAAwBPAKkNAAADAE8AAwABClMSswYAUAABMw0AAAIALgA1AAQKgSUABAQACQo8IZQGAIUCAAUABwq5H7ElAI4CAAQACAoWGpQGAIUCAAMAAwpcF3QPANIAAAAA.',
Ga='Gardevoiir:BAEBNQAECoEqAAMMAAkKISROCACqAwmODQAABgBXAHUNAAAGAGAAfw0AAAUAWACpDQAABgBfAFwNAAAEAGAAXQ0AAAQAYQBlDQAABABXAKQNAAADAFgAMw0AAAQAXwAMAAkKISROCACqAwmODQAABgBXAHUNAAAGAGAAfw0AAAUAWACpDQAABQBfAFwNAAAEAGAAXQ0AAAQAYQBlDQAABABXAKQNAAADAFgAMw0AAAQAXwAaAAEKFRoTBwBPAAGpDQAAAQBCAAAA.Garrydrood:BAEANQAECgMIBAABNQAECggJFwAMAC8dAA==.Garrylock:BAEANQAECgQIBAABNQAECggJFwAMAC8dAA==.Garynarkle:BAEANQABCggIEgAAAA==.Gayvraeladin:BAEANQAFFAEJAgABNQAFFAYIFgAbAGIWAA==.',
Gd='Gdubs:BAECNQAFFIEVAAMXAAcKBxkbAACPAgeODQAABABQAHUNAAAEADEAfw0AAAMAUwCpDQAABABcAFwNAAACAEwAXQ0AAAEAAAAzDQAAAwBAABcABwoHGRsAAI8CB44NAAAEAFAAdQ0AAAQAMQB/DQAAAwBTAKkNAAADAFwAXA0AAAIATABdDQAAAQAAADMNAAADAEAAHAABCr4OJA4AUAABqQ0AAAEAJQA1AAQKgScAAxcACQo6JSkDALYDABcACQo6JSkDALYDABwABAp8Guc3ADYBAAAA.',
Gh='Ghostwolf:BAEANQADCgcIDgAAAA==.',
Go='Gowrymage:BAEBNQAECoEXAAIMAAgKLx22TwCcAgiODQAAAwAxAHUNAAADAEgAfw0AAAMAPACpDQAAAwBLAFwNAAAEAFIAXQ0AAAMAWgBlDQAAAgBRADMNAAACAFUADAAICi8dtk8AnAIIjg0AAAMAMQB1DQAAAwBIAH8NAAADADwAqQ0AAAMASwBcDQAABABSAF0NAAADAFoAZQ0AAAIAUQAzDQAAAgBVAAAA.',
Gr='Grimfleur:BAEANQAECgYIEAAAAA==.',
Gz='Gzw:BAEANQAECggIAwABNQAFFAcJFQAXAAcZAA==.',
Ha='Hatedspec:BAECNQAFFIEZAAQGAAcKSSR2AACKAgeODQAABQBiAHUNAAAEAGMAfw0AAAQAYgCpDQAABABjAFwNAAAEAFIAXQ0AAAMASQAzDQAAAQBhAAYABgr+I3YAAIoCBo4NAAADAGIAdQ0AAAMAYwB/DQAAAgBiAKkNAAADAGMAXA0AAAQAUgBdDQAAAwBJAAgABAqIFXsDAEkBBI4NAAACAEsAdQ0AAAEAPQB/DQAAAgBFAKkNAAABAA0ACQABCncBnBAAOgABMw0AAAEAAwA1AAQKgSAABAYACQrmJeUAAIgDAAYACQrfJeUAAIgDAAgACAoeH6gKAH0CAAkAAQrBAWY8ACsAAAAA.',
He='Heymandude:BAECNQAFFIEHAAIUAAQK0BtbBgALAQSODQAAAwBKAHUNAAABAEQAfw0AAAEAPwAzDQAAAgBOABQABArQG1sGAAsBBI4NAAADAEoAdQ0AAAEARAB/DQAAAQA/ADMNAAACAE4ANQAECoEnAAIUAAkKmiT0AQC1AwAUAAkKmiT0AQC1AwAAAA==.',
Hh='Hhorizon:BAEANQAFFAMJBAAAAA==.',
Il='Illusionqaq:BAECNQAFFIEGAAIOAAMKrBOpDwCYAAOODQAAAwAjAHUNAAABADQAqQ0AAAIAPwAOAAMKrBOpDwCYAAOODQAAAwAjAHUNAAABADQAqQ0AAAIAPwA1AAQKgRsAAw4ACQrxG6YdAPkCAA4ACQrxG6YdAPkCAB0ABQrlCfgvAM0AAAAA.Illusionqwq:BAEANQAECgIIAgABNQAFFAMIBgAOAKwTAA==.',
Ja='Jackowin:BAEBNQAECoEYAAIMAAgKBxo0VwCHAgiODQAABABIAHUNAAADAE8Afw0AAAMATgCpDQAABABTAFwNAAADAE8AXQ0AAAMATQBlDQAAAwATAKQNAAABACoADAAICgcaNFcAhwIIjg0AAAQASAB1DQAAAwBPAH8NAAADAE4AqQ0AAAQAUwBcDQAAAwBPAF0NAAADAE0AZQ0AAAMAEwCkDQAAAQAqAAE1AAUUBQkPABgAshQA.Jackpotjimmy:BAECNQAFFIENAAIeAAMKiAX5AwCeAAOODQAABwAOAKkNAAAEAAsAMw0AAAIAEAAeAAMKiAX5AwCeAAOODQAABwAOAKkNAAAEAAsAMw0AAAIAEAA1AAQKgUIAAh4ACQppFKwHAFcCAB4ACQppFKwHAFcCAAAA.Jaysplosion:BAEBNQAECoEiAAMMAAkKNyMZGQBUAwmODQAABQBhAHUNAAAEAGEAfw0AAAQAWgCpDQAABABbAFwNAAAEAGAAXQ0AAAQAXABlDQAABABQAKQNAAACAEYAMw0AAAMAXQAMAAkKHiMZGQBUAwmODQAABQBhAHUNAAABAF8Afw0AAAQAWgCpDQAABABbAFwNAAAEAGAAXQ0AAAMAXABlDQAABABQAKQNAAACAEYAMw0AAAMAXQALAAIKuSPvGgCpAAJ1DQAAAwBhAF0NAAABAFUAAAA=.',
Je='Jeffm:BAEBNQAECoEUAAIMAAcKlx2MZQBfAgeODQAABQBGAHUNAAADAGIAfw0AAAIAWQCpDQAAAwBRAFwNAAABAEMAXQ0AAAMATABlDQAAAwAuAAwABwqXHYxlAF8CB44NAAAFAEYAdQ0AAAMAYgB/DQAAAgBZAKkNAAADAFEAXA0AAAEAQwBdDQAAAwBMAGUNAAADAC4AAAA=.',
Ju='Jujuza:BAEBNQAECoElAAQKAAkKjCLSAQCTAwmODQAAAwBjAHUNAAAEAFkAfw0AAAMAXQCpDQAABQBdAFwNAAADAGMAXQ0AAAMAYQBlDQAAAwBAAKQNAAAGAD0AMw0AAAcAYQAKAAkKeyLSAQCTAwmODQAAAwBjAHUNAAAEAFkAfw0AAAMAXQCpDQAABABdAFwNAAADAGMAXQ0AAAIAYQBlDQAAAwBAAKQNAAADAD0AMw0AAAQAYAABAAMKBB3gPAD7AAOpDQAAAQBSAF0NAAABAFYApA0AAAMANgAfAAEKPiaeEgBzAAEzDQAAAwBhAAAA.Jujuze:BAEANQAECggJBwABNQAECgkJJQAKAIwiAA==.',
Ka='Karmafuge:BAEANQADCgUIBQABNQAECgkJIAABAHUbAA==.Kaòri:BAEANQAECgMIBAABNQAFFAcIGQAGAEkkAA==.',
Ki='Killchain:BAECNQAFFIELAAIMAAUKjw1ADACcAQWODQAAAwA1AHUNAAACAB4Afw0AAAIAHACpDQAAAwApADMNAAABABIADAAFCo8NQAwAnAEFjg0AAAMANQB1DQAAAgAeAH8NAAACABwAqQ0AAAMAKQAzDQAAAQASADUABAqBKQACDAAJCjkgnCcAHAMADAAJCjkgnCcAHAMAATUABRQFCgsADACPDQA=.Killchainwar:BAEANQADCgUIBQABNQAFFAUKCwAMAI8NAA==.',
['Kì']='Kìnetyk:BAECNQAFFIEUAAIgAAYKfhnUAQAYAgaODQAABQBMAHUNAAADAFsAfw0AAAMAMwCpDQAABAAuAFwNAAACADcAMw0AAAMARgAgAAYKfhnUAQAYAgaODQAABQBMAHUNAAADAFsAfw0AAAMAMwCpDQAABAAuAFwNAAACADcAMw0AAAMARgA1AAQKgSwAAiAACQrtJPcCAMgDACAACQrtJPcCAMgDAAAA.',
La='Lambourne:BAEBNQAECoEaAAIhAAkKASV/BwCgAwmODQAABABjAHUNAAADAF0Afw0AAAMAYgCpDQAABABiAFwNAAADAGMAXQ0AAAMAYQBlDQAAAwBaAKQNAAABAE0AMw0AAAIAYQAhAAkKASV/BwCgAwmODQAABABjAHUNAAADAF0Afw0AAAMAYgCpDQAABABiAFwNAAADAGMAXQ0AAAMAYQBlDQAAAwBaAKQNAAABAE0AMw0AAAIAYQAAAA==.Lambsohot:BAEANQAECgIIAgABNQAECgkJGgAhAAElAA==.',
Li='Linesenjoyer:BAEANQAFFAIIAgAAAA==.Lionyr:BAEBNQAFFIEHAAIiAAQKCg5NAQAnAQSODQAABABNAHUNAAABACcAfw0AAAEACQCpDQAAAQAQACIABAoKDk0BACcBBI4NAAAEAE0AdQ0AAAEAJwB/DQAAAQAJAKkNAAABABAAATUABRQGCBYAGwBiFgA=.Lisael:BAECNQAFFIEOAAIjAAUKJBO6AACHAQWODQAABABNAHUNAAACAB4Afw0AAAEAFQCpDQAABAA6ADMNAAADADgAIwAFCiQTugAAhwEFjg0AAAQATQB1DQAAAgAeAH8NAAABABUAqQ0AAAQAOgAzDQAAAwA4ADUABAqBGQACIwAJCmoghAIAQgMAIwAJCmoghAIAQgMAATUABRQGCBYAGwBiFgA=.',
Ll='Llöcklesnar:BAEANQAECgQIBgAAAA==.',
Lo='Loquewl:BAEANQAECgYIDAAAAA==.',
Lu='Luxmalli:BAECNQAFFIERAAINAAYK2CSjAACJAgaODQAABABbAHUNAAADAGMAfw0AAAMAXQCpDQAAAgBfAFwNAAACAGMAMw0AAAMAVQANAAYK2CSjAACJAgaODQAABABbAHUNAAADAGMAfw0AAAMAXQCpDQAAAgBfAFwNAAACAGMAMw0AAAMAVQA1AAQKgRwAAw0ACQo5JX4BAMgDAA0ACQo5JX4BAMgDAA4AAQqVG6UHAUsAAAAA.',
Ma='Macharius:BAEANQADCgcJDgABNQAECgcIHQAGAMELAA==.Madorimage:BAECNQAFFIERAAIMAAYKrQroBgDoAQaODQAABAA7AHUNAAADABQAfw0AAAIAGACpDQAAAwAhAFwNAAACAAUAMw0AAAMAFAAMAAYKrQroBgDoAQaODQAABAA7AHUNAAADABQAfw0AAAIAGACpDQAAAwAhAFwNAAACAAUAMw0AAAMAFAA1AAQKgSkAAgwACQoxI/8UAGUDAAwACQoxI/8UAGUDAAAA.Madorimagi:BAEANQAECgIIAgABNQAFFAYJEQAMAK0KAA==.Madorion:BAEANQAECgMIBAABNQAFFAYJEQAMAK0KAA==.Malpractis:BAECNQAFFIEZAAIYAAcKgCItAADnAgeODQAAAwBfAHUNAAAEAFYAfw0AAAQASQCpDQAABQBfAFwNAAADAFoAXQ0AAAIAUAAzDQAABABhABgABwqAIi0AAOcCB44NAAADAF8AdQ0AAAQAVgB/DQAABABJAKkNAAAFAF8AXA0AAAMAWgBdDQAAAgBQADMNAAAEAGEANQAECoEZAAIYAAkKZCPGAwCIAwAYAAkKZCPGAwCIAwAAAA==.Malzhuul:BAECNQAFFIELAAIgAAQK/ByTBQCCAQSODQAABgBeAHUNAAABAEQAfw0AAAEANACpDQAAAwBQACAABAr8HJMFAIIBBI4NAAAGAF4AdQ0AAAEARAB/DQAAAQA0AKkNAAADAFAANQAECoEfAAMgAAgK1BrtKAB1AgAgAAgK1BrtKAB1AgAkAAMKsgYnpQCgAAABNQAFFAcIGQAYAIAiAA==.',
Mi='Minglock:BAEBNQAECoEhAAIFAAcKlRcxQwAQAgeODQAABgBWAHUNAAAEAEgAfw0AAAYANgCpDQAABgA9AFwNAAADABIAXQ0AAAIAOQAzDQAABgBHAAUABwqVFzFDABACB44NAAAGAFYAdQ0AAAQASAB/DQAABgA2AKkNAAAGAD0AXA0AAAMAEgBdDQAAAgA5ADMNAAAGAEcAAAA=.Mingmonk:BAEANQAECgMJBQABNQAECgcIIQAFAJUXAA==.Mingshaman:BAEANQAECgEIAgABNQAECgcIIQAFAJUXAA==.',
Mo='Mojache:BAEANQADCggJCAABNQAFFAcJFQAXAAcZAA==.Morkee:BAEANQAECggICAABNQAFFAEIAQAHAAAAAA==.Morkwee:BAEANQAFFAEIAQAAAA==.',
Mu='Multurion:BAEANQADCgcIEQABNQAECgkJHAAkAJAbAA==.',
My='Mybrokenmage:BAEANQADCgQIBAABNQAECgkJIgAIALsXAA==.',
Ni='Niph:BAEANQABCgMJAgAAAQ==.',
No='Nocnitsa:BAEANQADCggICAABNQABCgMJAwAHAAAAAA==.',
On='Onawatchlist:BAEANQAECgEJAQABNQAFFAcIFQAYAP8dAA==.',
Pa='Parobola:BAECNQAFFIEFAAIkAAIKmyVnCwDfAAKODQAAAwBhAKkNAAACAF8AJAACCpslZwsA3wACjg0AAAMAYQCpDQAAAgBfADUABAqBIAACJAAJCm0knQIAqAMAJAAJCm0knQIAqAMAAAA=.Paroböla:BAEANQAECgIIAgABNQAFFAIIBQAkAJslAA==.',
Pe='Peacuc:BAEANQADCgUIBwABNQAECgQIBgAHAAAAAA==.Pelfurion:BAEANQAECggIDQAAAA==.',
Pi='Piyoz:BAEANQAECgUICAABNQAFFAMJBQAFALoDAA==.',
Ra='Raellyn:BAECNQAFFIEZAAMlAAcK4hhMAAB2AgeODQAABABQAHUNAAAEAEcAfw0AAAQAUgCpDQAABABFAFwNAAADADcAXQ0AAAIAGwAzDQAABAA7ACUABwriGEwAAHYCB44NAAADAFAAdQ0AAAQARwB/DQAABABSAKkNAAAEAEUAXA0AAAMANwBdDQAAAgAbADMNAAADADsAJgACCgYKdhQAhQACjg0AAAEAGwAzDQAAAQAYADUABAqBIwADJgAJCmgbuBUA0AIAJgAJCmgbuBUA0AIAJQAJCqgT4hMALgIAAAA=.Raevoke:BAEANQADCggICAABNQAFFAcIGQAlAOIYAA==.Rainons:BAEANQAECgYIBgABNQAFFAIIBAAHAAAAAA==.Rainonsh:BAEANQAFFAIIAgABNQAFFAIIBAAHAAAAAA==.Rainonsz:BAEANQAFFAIIBAAAAA==.Ramm:BAECNQAFFIETAAMFAAcKoyKhAABaAgeODQAAAgBYAHUNAAAEAGMAfw0AAAIAWgCpDQAABABiAFwNAAACAFUAXQ0AAAIAPgAzDQAAAwBgAAUABgqoIaEAAFoCBo4NAAACAFgAfw0AAAIAWgCpDQAAAQBdAFwNAAACAFUAXQ0AAAIAPgAzDQAAAwBgAAQAAgqRJh8CAOYAAnUNAAAEAGMAqQ0AAAMAYgA1AAQKgSIABAQACQruJgUCADUDAAUACAqvJlgFAHUDAAQACApyJAUCADUDAAMAAQr3JT0XAGgAAAAA.Rammtwo:BAEBNQAECoEQAAQEAAgKWCNYBQCqAgiODQAAAwBhAHUNAAACAGEAfw0AAAIAYgCpDQAAAgBeAFwNAAACAF8AXQ0AAAIAXgBlDQAAAQA1ADMNAAACAFwABAAHCgwlWAUAqgIHjg0AAAEAYQB1DQAAAgBhAH8NAAABAFwAqQ0AAAIAXgBcDQAAAQBfAF0NAAABAF4AMw0AAAEAXAAFAAUKCyEZVADRAQWODQAAAgBgAH8NAAABAGIAXQ0AAAEAXABlDQAAAQA1ADMNAAABAFEAAwABCtkkJhgAYgABXA0AAAEAXgABNQAFFAcIEwAFAKMiAA==.',
Ri='Riyria:BAEBNQAECoEgAAMhAAkK8h/nHgAAAwmODQAABABZAHUNAAAEAFsAfw0AAAUAWwCpDQAABABRAFwNAAADAFsAXQ0AAAMAPABlDQAAAwBUAKQNAAACADQAMw0AAAQAXQAhAAkKmB/nHgAAAwmODQAAAwBZAHUNAAADAFsAfw0AAAQAWwCpDQAAAwBJAFwNAAACAFsAXQ0AAAIAPABlDQAAAwBUAKQNAAACADQAMw0AAAMAXQAiAAcKkBsJCQAzAgeODQAAAQBPAHUNAAABAEwAfw0AAAEATgCpDQAAAQBRAFwNAAABACwAXQ0AAAEANwAzDQAAAQBNAAAA.',
Ro='Rosaura:BAECNQAFFIEPAAIBAAUKJSAgAQDzAQWODQAAAwBhAHUNAAADAF8Afw0AAAIAOACpDQAAAwBaADMNAAAEAEcAAQAFCiUgIAEA8wEFjg0AAAMAYQB1DQAAAwBfAH8NAAACADgAqQ0AAAMAWgAzDQAABABHADUABAqBMAADAQAJCuEl+gAAygMAAQAJCuEl+gAAygMACgADCmsWMjIAvwAAAAA=.',
Sa='Saburac:BAEANQAECgIJBAABNQAECgkJIAABAHUbAA==.',
Sc='Scodelario:BAEANQAECgUIBQABNQAECgkJKgAMACEkAA==.Screampies:BAECNQAFFIENAAMPAAQKCg9wDgDyAASODQAABwAvAHUNAAABADUAfw0AAAEADgCpDQAABAAmAA8AAwoNDXAOAPIAA44NAAAFAC8Afw0AAAEADgCpDQAAAwAmABgAAwrHBuIHAOoAA44NAAACAA4AdQ0AAAEAHACpDQAAAQAIADUABAqBIgADDwAJCiAcDR8AlAIADwAJCiAcDR8AlAIAGAACCiUOEEIAiAAAATUABRQHCBkAJQDiGAA=.',
Si='Sileighty:BAEANQAECgMIBAABNQAECgkJGgAhAAElAA==.',
So='Sorryrennon:BAEBNQAECoEiAAQIAAkKuxd/CgCAAgmODQAABwBKAHUNAAAFAEgAfw0AAAQAVQCpDQAABQBOAFwNAAADABQAXQ0AAAIAMABlDQAAAwA7AKQNAAACACAAMw0AAAMASwAIAAkKKRd/CgCAAgmODQAABABJAHUNAAADAEgAfw0AAAIAVQCpDQAABABOAFwNAAACAAgAXQ0AAAIAMABlDQAAAgA7AKQNAAABACAAMw0AAAMASwAGAAcKuRMwBgDkAQeODQAAAgBKAHUNAAABAEgAfw0AAAIATACpDQAAAQA+AFwNAAABABQAZQ0AAAEAKgCkDQAAAQAEAAkAAgokCQAAAAAAAo4NAAABABIAdQ0AAAEAHAAAAA==.',
Sp='Speedaddict:BAEBNQAECoEXAAMGAAkKXRkcBgDqAQmODQAAAwBPAHUNAAAEADwAfw0AAAMAVQCpDQAABABLAFwNAAACAEUAXQ0AAAIAGgBlDQAAAQAtAKQNAAABAEUAMw0AAAMASQAGAAcK8hgcBgDqAQeODQAAAgBPAHUNAAACADwAfw0AAAMAVQCpDQAAAwBLAFwNAAACAEUAXQ0AAAEAAwAzDQAAAgBJAAgABwrhE3ASAMwBB44NAAABADoAdQ0AAAIANwCpDQAAAQAnAF0NAAABABoAZQ0AAAEALQCkDQAAAQBFADMNAAABAD4AATUABRQCCAIABwAAAAA=.',
St='Stmz:BAEANQAECgcJEQABNQAFFAYIDwAZAJcLAA==.Stmzeh:BAEANQAECgEIAQABNQAFFAYIDwAZAJcLAA==.Straxeh:BAECNQAFFIEPAAMZAAYKlwuMAAD5AQaODQAABABGAHUNAAADACAAfw0AAAIABACpDQAAAwAaAFwNAAABAAsAMw0AAAIAIAAZAAYKSQqMAAD5AQaODQAAAQBGAHUNAAABACAAfw0AAAEABACpDQAAAQAGAFwNAAABAAsAMw0AAAEAIAAgAAUKrgSSBwBCAQWODQAAAwAVAHUNAAACAAgAfw0AAAEAAgCpDQAAAgAaADMNAAABAAAANQAECoEeAAMZAAkKKR3aBAAPAwAZAAkKKBraBAAPAwAgAAkKoRauJwB9AgAAAA==.',
Su='Suprised:BAEANQAECggIAQAAAA==.',
Th='Thehorse:BAEANQAECgIIAgABNQAECgkJLwAIAEQfAA==.Thehoss:BAEANQADCgMIAwABNQAECgkJLwAIAEQfAA==.',
Ti='Tieprier:BAEANQAECgYIDAAAAA==.',
To='Tonkotsu:BAEBNQAFFIEWAAIbAAYKYhYfAwDjAQaODQAABABTAHUNAAADAEgAfw0AAAQAOQCpDQAABAAkAFwNAAADABIAMw0AAAQASgAbAAYKYhYfAwDjAQaODQAABABTAHUNAAADAEgAfw0AAAQAOQCpDQAABAAkAFwNAAADABIAMw0AAAQASgAAAA==.Touchingtips:BAEANQADCgEJAQABNQAFFAYIDwAZAJcLAA==.Toxiyks:BAEANQAECgQIDQAAAA==.',
Tr='Treedubs:BAEANQAECgIIAQABNQAFFAcJFQAXAAcZAA==.',
Um='Umbrreon:BAEANQADCgYIBgABNQAECgkJKgAMACEkAA==.',
Va='Vaath:BAEBNQAECoEpAAInAAkKMRoCEADMAgmODQAABQBRAHUNAAAFAE8Afw0AAAUAUwCpDQAABQBDAFwNAAAEADkAXQ0AAAUAQQBlDQAABAA2AKQNAAAEACsAMw0AAAQARgAnAAkKMRoCEADMAgmODQAABQBRAHUNAAAFAE8Afw0AAAUAUwCpDQAABQBDAFwNAAAEADkAXQ0AAAUAQQBlDQAABAA2AKQNAAAEACsAMw0AAAQARgAAAA==.Vailario:BAEANQAECgIIAgABNQAECgkJKgAMACEkAA==.',
Wa='Wakakyrri:BAEBNQAECoEZAAIYAAkKxRyECAAlAwmODQAABABJAHUNAAAEAFoAfw0AAAIATwCpDQAABABQAFwNAAAEAFsAXQ0AAAIAWABlDQAAAgA+AKQNAAABACIAMw0AAAIAPgAYAAkKxRyECAAlAwmODQAABABJAHUNAAAEAFoAfw0AAAIATwCpDQAABABQAFwNAAAEAFsAXQ0AAAIAWABlDQAAAgA+AKQNAAABACIAMw0AAAIAPgABNQAECgkJIQAIAP8hAA==.Warklaw:BAECNQAFFIEVAAIYAAcK/x0hAAD2AgeODQAAAwBgAHUNAAAEAGQAfw0AAAQALACpDQAAAwBjAGUNAAACAAAApA0AAAEAZAAzDQAABABfABgABwr/HSEAAPYCB44NAAADAGAAdQ0AAAQAZAB/DQAABAAsAKkNAAADAGMAZQ0AAAIAAACkDQAAAQBkADMNAAAEAF8ANQAECoEcAAIYAAkK8CYmAAAIBAAYAAkK8CYmAAAIBAAAAA==.Warklawx:BAEANQAECgcICwABNQAFFAcIFQAYAP8dAA==.Warknatty:BAEANQAFFAIJAgABNQAFFAcIFQAYAP8dAA==.',
We='Webex:BAEANQAECgUIBgAAAQ==.Weewees:BAEANQAECgYIDAABNQAFFAUIBwAUANAbAA==.',
Wh='Whitemanee:BAEANQAFFAIIAgABNQAFFAMJBQAFALoDAA==.',
Xh='Xheroleaker:BAEANQAECgQIBwAAAA==.',
Xi='Xiaoteezy:BAEANQAECggIEAABNQAFFAQIBQAKAHITAA==.Xiaoteèzy:BAEANQADCgEIAQABNQAFFAQIBQAKAHITAA==.Xiaotèezy:BAEANQAECggJBgABNQAFFAQIBQAKAHITAA==.Xiaotèèzy:BAEANQAECggJBwABNQAFFAQIBQAKAHITAA==.Xiaotèézy:BAEANQADCgYIBgABNQAFFAQIBQAKAHITAA==.Xiaotéezy:BAEANQAECgUIBQABNQAFFAQIBQAKAHITAA==.Xiaotëëzy:BAECNQAFFIEFAAIKAAQKchO/CACqAASODQAAAgBWAHUNAAABAEYAfw0AAAEAFgCpDQAAAQATAAoABApyE78IAKoABI4NAAACAFYAdQ0AAAEARgB/DQAAAQAWAKkNAAABABMANQAECoEdAAMKAAkKISDHCQCyAgAKAAgKeiDHCQCyAgABAAEKVh2vWgBFAAAAAA==.',
Za='Zayge:BAECNQAFFIEFAAIMAAIKdB4EHwC/AAKODQAAAwBdAKkNAAACAD4ADAACCnQeBB8AvwACjg0AAAMAXQCpDQAAAgA+ADUABAqBKAACDAAJCmMjvhEAdQMADAAJCmMjvhEAdQMAAAA=.',
Zo='Zorthak:BAEANQAECgcICwABNQAFFAkJHAAgABsjAA==.Zorthar:BAECNQAFFIEcAAIgAAkKGyMBAADHAwmODQAABABjAHUNAAAEAF8Afw0AAAQAZACpDQAAAwBjAFwNAAADAGQAXQ0AAAMAWgBlDQAAAgAbAKQNAAABAGQAMw0AAAQAXwAgAAkKGyMBAADHAwmODQAABABjAHUNAAAEAF8Afw0AAAQAZACpDQAAAwBjAFwNAAADAGQAXQ0AAAMAWgBlDQAAAgAbAKQNAAABAGQAMw0AAAQAXwA1AAQKgRoAAyAACQqHJpoRACQDACAACAr7JJoRACQDABkABQpgJpkMADgCAAAA.Zorthargirl:BAEBNQAECoEYAAIZAAkKAx5CBgDgAgmODQAAAwBSAHUNAAACAF0Afw0AAAQAYwCpDQAAAgBUAFwNAAACABsAXQ0AAAEANABlDQAAAwA/AKQNAAAFAFwAMw0AAAIAXwAZAAkKAx5CBgDgAgmODQAAAwBSAHUNAAACAF0Afw0AAAQAYwCpDQAAAgBUAFwNAAACABsAXQ0AAAEANABlDQAAAwA/AKQNAAAFAFwAMw0AAAIAXwABNQAFFAkJHAAgABsjAA==.Zorthasjond:BAEANQAECgYJBgABNQAFFAkJHAAgABsjAA==.Zorthasx:BAEANQAFFAIJAgABNQAFFAkJHAAgABsjAA==.',
['Öv']='Överdösë:BAEANQAECgYIDAABNQAFFAIIAgAHAAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
