-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('deDE') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Gossip-Optionen automatisieren"
L["Automate quests"] = "Quests automatisieren"
L["Automate repeatable quests"] = "Wiederholbare Quests automatisieren"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Quests automatisch teilen"
L["Block a new item by ID"] = "Neuen Gegenstand per ID blockieren"
L["Block a new NPC by ID or target"] = "Neuen NSC per ID oder Ziel blockieren"
L["Block a quest by title or ID"] = "Quest per Titel oder ID blockieren"
L["Highlight valuable reward"] = "Wertvolle Belohnung hervorheben"
L["Hold this key to temporarily disable all automation"] = "Halte diese Taste, um alle Automatisierungen vorübergehend zu deaktivieren"
L["Item Blocklist"] = "Gegenstands-Blockliste"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "NSC-Blockliste"
L["Pause mode modifier"] = "Pausenmodus-Modifikator"
L["Pay Darkmoon Faire teleport"] = "Teleport zum Dunkelmond-Jahrmarkt bezahlen"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Quest-Blockliste"
L["Reverse pause mode"] = "Umgekehrter Pausenmodus"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Quest-Gossip-Optionen überspringen"
L["Soloing"] = "Allein spielen"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Wenn \"%s\" ausgewählt ist, wird %s nur automatisiert, während sie verfolgt werden"
L["When to automate gossip"] = "Wann Gossip automatisieren"
L["While the pause key is NOT held don't automate anything"] = "Solange die Pausentaste NICHT gedrückt ist, wird nichts automatisiert"

