-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('esMX') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Automatizar opciones de diálogo"
L["Automate quests"] = "Automatizar misiones"
L["Automate repeatable quests"] = "Automatizar misiones repetibles"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Compartir misiones automáticamente"
L["Block a new item by ID"] = "Bloquear un nuevo objeto por ID"
L["Block a new NPC by ID or target"] = "Bloquear un nuevo NPC por ID o por objetivo"
L["Block a quest by title or ID"] = "Bloquear una misión por título o ID"
L["Highlight valuable reward"] = "Resaltar recompensa valiosa"
L["Hold this key to temporarily disable all automation"] = "Mantén esta tecla para desactivar temporalmente toda automatización"
L["Item Blocklist"] = "Lista negra de objetos"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "Lista negra de NPC"
L["Pause mode modifier"] = "Modificador del modo de pausa"
L["Pay Darkmoon Faire teleport"] = "Paga el teletransporte de la Feria de la Luna Oscura"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Lista negra de misiones"
L["Reverse pause mode"] = "Modo de pausa inverso"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Omitir opciones de diálogo de misión"
L["Soloing"] = "Jugando solo"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Cuando se selecciona \"%s\", %s solo se automatiza mientras se esté rastreando"
L["When to automate gossip"] = "Cuándo automatizar los diálogos"
L["While the pause key is NOT held don't automate anything"] = "Mientras no se mantenga presionada la tecla de pausa, nada se automatiza"

