-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('frFR') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Automatiser les options de bavardage"
L["Automate quests"] = "Automatiser les quêtes"
L["Automate repeatable quests"] = "Automatiser les quêtes répétables"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Partager automatiquement les quêtes"
L["Block a new item by ID"] = "Bloquer un nouvel objet par ID"
L["Block a new NPC by ID or target"] = "Bloquer un nouveau PNJ par ID ou cible"
L["Block a quest by title or ID"] = "Bloquer une quête par titre ou ID"
L["Highlight valuable reward"] = "Mettre en valeur une récompense précieuse"
L["Hold this key to temporarily disable all automation"] = "Maintenez cette touche enfoncée pour désactiver temporairement toute automatisation"
L["Item Blocklist"] = "Liste noire d'objets"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "Liste noire de PNJ"
L["Pause mode modifier"] = "Modificateur du mode pause"
L["Pay Darkmoon Faire teleport"] = "Payer le téléport de la Foire de Sombrelune"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Liste noire de quêtes"
L["Reverse pause mode"] = "Mode pause inversé"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Passer les options de bavardage de la quête"
L["Soloing"] = "En solo"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Lorsque \"%s\" est sélectionné, %s sera automatisé uniquement pendant leur suivi"
L["When to automate gossip"] = "Quand automatiser le bavardage"
L["While the pause key is NOT held don't automate anything"] = "Tant que la touche de pause n'est pas enfoncée, n'automatisez rien"

