-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('itIT') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Automatizza opzioni di dialogo"
L["Automate quests"] = "Automatizza le missioni"
L["Automate repeatable quests"] = "Automatizza le missioni ripetibili"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Condividi automaticamente le missioni"
L["Block a new item by ID"] = "Blocca un nuovo oggetto per ID"
L["Block a new NPC by ID or target"] = "Blocca un nuovo NPC per ID o target"
L["Block a quest by title or ID"] = "Blocca una missione per nome o ID"
L["Highlight valuable reward"] = "Evidenzia una ricompensa di valore"
L["Hold this key to temporarily disable all automation"] = "Tieni premuto questo tasto per disabilitare temporaneamente tutta l'automazione"
L["Item Blocklist"] = "Lista nera degli oggetti"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "Lista nera degli NPC"
L["Pause mode modifier"] = "Modificatore della modalità pausa"
L["Pay Darkmoon Faire teleport"] = "Paga il teletrasporto della Darkmoon Faire"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Lista nera delle missioni"
L["Reverse pause mode"] = "Modalità pausa invertita"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Salta le opzioni di dialogo della missione"
L["Soloing"] = "Giocare in solitaria"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Quando \"%s\" è selezionato, %s sarà automatizzato solo durante il monitoraggio"
L["When to automate gossip"] = "Quando automatizzare i dialoghi"
L["While the pause key is NOT held don't automate anything"] = "Finché il tasto pausa non è premuto, niente verrà automatizzato"

