-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ptBR') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Automatizar opções de conversa"
L["Automate quests"] = "Automatizar missões"
L["Automate repeatable quests"] = "Automatizar missões repetíveis"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Compartilhar missões automaticamente"
L["Block a new item by ID"] = "Bloquear um novo item por ID"
L["Block a new NPC by ID or target"] = "Bloquear um novo NPC por ID ou alvo"
L["Block a quest by title or ID"] = "Bloquear uma missão pelo título ou ID"
L["Highlight valuable reward"] = "Destacar recompensa valiosa"
L["Hold this key to temporarily disable all automation"] = "Segure esta tecla para desabilitar temporariamente toda automação"
L["Item Blocklist"] = "Lista de bloqueio de itens"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "Lista de bloqueio de NPCs"
L["Pause mode modifier"] = "Modificador de modo de pausa"
L["Pay Darkmoon Faire teleport"] = "Pagar o teletransporte da Darkmoon Faire"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Lista de bloqueio de missões"
L["Reverse pause mode"] = "Modo de pausa invertido"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Pular opções de conversa de missão"
L["Soloing"] = "Jogando sozinho"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Quando \"%s\" for selecionado, %s só será automatizado enquanto estiver sendo rastreado"
L["When to automate gossip"] = "Quando automatizar conversas"
L["While the pause key is NOT held don't automate anything"] = "Enquanto a tecla de pausa NÃO estiver pressionada, nada será automatizado"

