-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('ruRU') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "Автоматизировать опции разговоров"
L["Automate quests"] = "Автоматизировать задания"
L["Automate repeatable quests"] = "Автоматизировать повторяемые задания"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "Автоматически делиться заданиями"
L["Block a new item by ID"] = "Блокировать новый предмет по ID"
L["Block a new NPC by ID or target"] = "Блокировать нового NPC по ID или цели"
L["Block a quest by title or ID"] = "Блокировать задание по названию или ID"
L["Highlight valuable reward"] = "Выделить ценное вознаграждение"
L["Hold this key to temporarily disable all automation"] = "Удерживайте эту клавишу, чтобы временно отключить всю автоматизацию"
L["Item Blocklist"] = "Черный список предметов"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "Черный список NPC"
L["Pause mode modifier"] = "Модификатор режима паузы"
L["Pay Darkmoon Faire teleport"] = "Оплатить телепортацию на Ярмарку Темной Луны"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "Черный список заданий"
L["Reverse pause mode"] = "Обратный режим паузы"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "Пропустить опции разговоров задания"
L["Soloing"] = "Игра в соло"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "Когда выбрано \"%s\", %s будет автоматизировано только при отслеживании"
L["When to automate gossip"] = "Когда автоматизировать разговоры"
L["While the pause key is NOT held don't automate anything"] = "Пока клавиша паузы не нажата, автоматизация не происходит"

