-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhCN') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "自动处理闲聊选项"
L["Automate quests"] = "自动任务"
L["Automate repeatable quests"] = "自动重复任务"
--[[Translation missing --]]
--[[ L["Automatically choose reward"] = ""--]] 
L["Automatically share quests"] = "自动共享任务"
L["Block a new item by ID"] = "通过ID屏蔽新物品"
L["Block a new NPC by ID or target"] = "通过ID或目标屏蔽新NPC"
L["Block a quest by title or ID"] = "通过标题或ID屏蔽任务"
L["Highlight valuable reward"] = "高亮显示珍贵奖励"
L["Hold this key to temporarily disable all automation"] = "按住此键可暂时禁用所有自动化"
L["Item Blocklist"] = "物品屏蔽列表"
--[[Translation missing --]]
--[[ L["Most valuable"] = ""--]] 
L["NPC Blocklist"] = "NPC屏蔽列表"
L["Pause mode modifier"] = "暂停模式修饰键"
L["Pay Darkmoon Faire teleport"] = "支付暗月马戏团传送费用"
--[[Translation missing --]]
--[[ L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = ""--]] 
L["Quest Blocklist"] = "任务屏蔽列表"
L["Reverse pause mode"] = "反转暂停模式"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "跳过任务闲聊选项"
L["Soloing"] = "单独进行"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "当选择\"%s\"时，只有在追踪%s时才会自动化"
L["When to automate gossip"] = "何时自动处理闲聊"
L["While the pause key is NOT held don't automate anything"] = "未按住暂停键时，不会自动执行任何操作"

