-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('zhTW') -- luacheck: ignore
--[[Translation missing --]]
--[[ L["Already seen"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always for trivial quests"] = ""--]] 
--[[Translation missing --]]
--[[ L["Always most valuable"] = ""--]] 
L["Automate gossip options"] = "自動處理對話選項"
L["Automate quests"] = "自動任務"
L["Automate repeatable quests"] = "自動重複任務"
L["Automatically choose reward"] = "自動選擇獎勵"
L["Automatically share quests"] = "自動共享任務"
L["Block a new item by ID"] = "根據ID屏蔽新物品"
L["Block a new NPC by ID or target"] = "根據ID或目標屏蔽新NPC"
L["Block a quest by title or ID"] = "根據標題或ID屏蔽任務"
L["Highlight valuable reward"] = "突出顯示有價值的獎勵"
L["Hold this key to temporarily disable all automation"] = "按住此鍵可暫時停用所有自動化功能"
L["Item Blocklist"] = "物品屏蔽清單"
L["Most valuable"] = "最有價值"
L["NPC Blocklist"] = "NPC屏蔽清單"
L["Pause mode modifier"] = "暫停模式快捷鍵"
L["Pay Darkmoon Faire teleport"] = "支付暗月馬戲團傳送費用"
L[ [=[Pick the reward and complete the quest.

|cffff0000Warning:|r "%s" will always pick something, even when there is no clear choice]=] ] = "選擇獎勵並完成此任務。|cffff0000警告：|r \"%s\" 即使沒有明確選擇，也會選擇某個東西。"
L["Quest Blocklist"] = "任務屏蔽清單"
L["Reverse pause mode"] = "反轉暫停模式"
--[[Translation missing --]]
--[[ L["Skip cinematics"] = ""--]] 
--[[Translation missing --]]
--[[ L["Skip movies"] = ""--]] 
L["Skip quest gossip options"] = "跳過任務對話選項"
L["Soloing"] = "單人"
L["When \"%s\" is selected %s will only be automated while tracking them"] = "當選擇「%s」時，只有在追蹤%s時才會自動化"
L["When to automate gossip"] = "何時自動處理對話"
L["While the pause key is NOT held don't automate anything"] = "未按住暫停鍵時，不會自動執行任何操作"

